export const BIOLOGY30_UNIT_C_GLOSSARY: Record<string, string> = {
  "9:3:3:1 ratio": "The expected phenotype ratio in a dihybrid cross when two genes assort independently and both show complete dominance.",
  "A site": "The ribosome site that receives the next aminoacyl-tRNA during translation.",
  "ABO blood group": "A human blood-group system controlled by multiple alleles in which IA and IB are codominant and i is recessive.",
  "Chargaff's rules": "The observed DNA base relationships that adenine approximately equals thymine and guanine approximately equals cytosine in double-stranded DNA.",
  "DNA": "Deoxyribonucleic acid; the nucleotide polymer that stores hereditary information in most organisms.",
  "DNA ligase": "An enzyme that seals breaks in a DNA sugar-phosphate backbone by forming phosphodiester bonds.",
  "DNA polymerase": "An enzyme that builds DNA by adding complementary nucleotides to an existing 3-prime end and often proofreads the product.",
  "DNA profile": "A pattern of DNA markers used to compare biological samples; it is probabilistic evidence, not a complete identity record.",
  "DNA sequencing": "Determining the order of nucleotides in a DNA molecule or selected DNA region.",
  "E site": "The ribosome site from which an uncharged tRNA exits after donating its amino acid.",
  "Okazaki fragment": "A short DNA segment synthesized discontinuously on the lagging strand and later joined by DNA ligase.",
  "P site": "The ribosome site holding the tRNA attached to the growing polypeptide chain.",
  "PCR": "Polymerase chain reaction; a laboratory method that uses primers and repeated temperature cycles to amplify a selected DNA region.",
  "Photo 51": "Rosalind Franklin and Raymond Gosling's X-ray diffraction image whose pattern provided important evidence about DNA's helical structure.",
  "Punnett square": "A grid that organizes possible gamete combinations to calculate offspring genotype probabilities under stated assumptions.",
  "RNA polymerase": "An enzyme that uses a DNA template to synthesize a complementary RNA molecule.",
  "RNA splicing": "Removal of introns and joining of exons from a pre-mRNA transcript.",
  "X-inactivation": "Early developmental silencing of most genes on one X chromosome in many cells of individuals with more than one X.",
  "X-linked": "Describes a gene located on the X chromosome and its associated inheritance pattern.",
  "X-ray diffraction": "A method that infers molecular structure from the pattern produced when X-rays scatter through an ordered sample.",
  "Y-linked": "Describes a gene located on the Y chromosome and transmitted through Y-bearing lineages.",
  "actionability": "The degree to which a test result can support a useful, evidence-based decision or intervention.",
  "addition rule": "A probability rule for mutually exclusive alternatives: add the probabilities of the separate outcomes.",
  "allele": "One of two or more DNA-sequence versions at a gene or locus.",
  "alternation of generations": "A life cycle alternating multicellular haploid and multicellular diploid stages.",
  "alternative splicing": "Production of different mature RNA transcripts by combining exons from the same pre-mRNA in different ways.",
  "analytical validity": "How accurately and reliably a test detects the molecular feature it claims to measure.",
  "anaphase": "The division stage when separated chromosomes or chromatids move toward opposite poles.",
  "aneuploidy": "A chromosome number with one or more individual chromosomes added or missing rather than a complete set change.",
  "anticodon": "A three-nucleotide sequence on tRNA that pairs with a complementary mRNA codon.",
  "antigen": "A molecular feature recognized by an immune receptor or antibody; ABO antigens occur on red-blood-cell surfaces.",
  "antiparallel": "Describes DNA strands running in opposite 5-prime-to-3-prime directions.",
  "apoptosis": "A regulated form of cell death that removes selected cells without the uncontrolled rupture typical of severe injury.",
  "asexual reproduction": "Reproduction from one parent without gamete fusion, usually producing genetically similar descendants except for mutation.",
  "banding pattern": "The reproducible light-and-dark chromosome pattern used to identify chromosomes and some structural changes in a karyotype.",
  "blinding": "Keeping observers unaware of sample identity or treatment to reduce expectation bias.",
  "blunt end": "A double-stranded DNA end with no single-stranded overhang.",
  "branch method": "A probability method that multiplies along sequential branches and adds mutually exclusive final pathways.",
  "cancer": "A group of diseases involving abnormal cell growth caused by accumulated genetic and cellular-control changes in context.",
  "carrier": "In simple recessive inheritance, a heterozygous individual who has one recessive allele and usually lacks the associated phenotype.",
  "cell cycle": "The ordered sequence of cell growth, DNA replication, chromosome separation, and cell division.",
  "cell plate": "A plant-cell structure formed during cytokinesis that develops into new membranes and a separating cell wall.",
  "centimorgan": "A linkage-map unit corresponding to a one-percent recombination frequency, not a fixed physical DNA distance.",
  "centromere": "A chromosome region where sister chromatids remain joined and the kinetochore assembles.",
  "chain of custody": "A documented record of who collected, handled, transferred, stored, and analyzed a sample.",
  "checkpoint": "A regulatory control point that can delay cell-cycle progression when conditions or molecular events are unsuitable.",
  "chiasma": "The visible physical connection between homologous chromosomes associated with an earlier crossing-over event.",
  "chromatid": "One DNA-protein copy of a replicated chromosome; joined sister chromatids separate during cell division.",
  "chromatin": "DNA together with associated proteins that package and regulate genetic material in the nucleus.",
  "chromosome": "One continuous DNA molecule with associated proteins and organized genes and regulatory regions.",
  "cleavage furrow": "The inward pinching of an animal cell membrane during cytokinesis.",
  "clinical validity": "How well a test result predicts or associates with a clinical condition in the intended population.",
  "clone": "A cell or organism descended asexually from one source and therefore highly similar genetically, though not necessarily identical in phenotype.",
  "coding strand": "The DNA strand whose sequence matches the RNA transcript except that DNA has thymine where RNA has uracil.",
  "codominance": "An inheritance pattern in which both alleles in a heterozygote contribute distinct detectable products or traits.",
  "codon": "A three-nucleotide mRNA sequence that specifies an amino acid or a translation start or stop signal.",
  "complementary base pairing": "Specific hydrogen-bond pairing of adenine with thymine or uracil and guanine with cytosine.",
  "complete dominance": "An inheritance pattern in which the heterozygote has the same scored phenotype as one homozygote.",
  "controlled variable": "A factor intentionally kept consistent so it does not confound the tested comparison.",
  "converging evidence": "Independent evidence types that support the same bounded explanation.",
  "crossing over": "Reciprocal DNA exchange between non-sister chromatids of homologous chromosomes during meiotic prophase I.",
  "cyclin": "A regulatory protein whose changing concentration helps control cyclin-dependent kinase activity during the cell cycle.",
  "cyclin-dependent kinase": "A protein kinase activated by cyclin binding that phosphorylates targets controlling cell-cycle transitions.",
  "cytokinesis": "Physical division of a cell's cytoplasm into daughter cells.",
  "data sovereignty": "The right of a people or community to govern collection, ownership, access, interpretation, and use of data about them.",
  "deletion": "Loss of one or more nucleotides or of a chromosome segment.",
  "deoxyribose": "The five-carbon sugar found in DNA nucleotides.",
  "dependent variable": "The measured response used to evaluate an investigation's prediction.",
  "dihybrid cross": "A genetic cross that follows inheritance at two loci.",
  "diploid": "Having two chromosome sets, conventionally written 2n.",
  "diploid-dominant": "A life cycle in which the multicellular diploid stage is the main body and the haploid stage is limited to gametes.",
  "dominant": "Describes an allele whose scored phenotype appears in a heterozygote under specified conditions.",
  "double crossover": "Two crossing-over events within the chromosome interval being studied.",
  "double helix": "The two-stranded helical structure of DNA with antiparallel sugar-phosphate backbones and paired bases.",
  "driver mutation": "A somatic mutation that contributes causally to a cell's cancer-related growth or survival advantage.",
  "epigenetic": "Describes stable or regulated changes in gene activity that do not require changing the DNA base sequence.",
  "evidence scale": "The biological level and measurement context to which an observation belongs, such as molecule, cell, organism, family, or population.",
  "exon": "A transcript segment retained in a mature RNA after splicing, though not every exon segment is protein-coding.",
  "expected count": "The number predicted for a category by a specified probability model and total sample size.",
  "expressivity": "The degree or form in which a genotype-associated trait appears among individuals who express it.",
  "frameshift": "A reading-frame change caused by insertion or deletion of nucleotides not in a multiple of three within a coding region.",
  "functional assay": "An experiment that tests how a variant, molecule, cell, or process performs rather than only detecting its presence.",
  "gamete probability": "The probability that a gamete carries a specified allele combination under a stated genetic model.",
  "gel electrophoresis": "A method that separates charged molecules through a gel, commonly resolving DNA fragments mainly by length.",
  "gene": "A DNA region whose transcription contributes to a functional RNA or protein product, together with relevant regulation.",
  "gene linkage": "Tendency of loci on the same chromosome to be inherited together, especially when they are physically close.",
  "gene order": "The relative arrangement of loci along a chromosome inferred from recombination evidence or physical mapping.",
  "gene-environment interaction": "A pattern in which the effect of a genotype differs across environments or the environmental effect differs across genotypes.",
  "genetic counselling": "A professional process supporting informed understanding and decisions about genetic information, testing, uncertainty, and family implications.",
  "genetic privacy": "Protection of identifiable genetic information from collection, access, or use without appropriate consent and governance.",
  "genotype": "The allele combination an organism or cell carries at one or more loci.",
  "genotype probability": "The probability of a specified allele combination under the assumptions of a genetic cross or population model.",
  "genotype-phenotype map": "A model connecting genotype with possible phenotype while accounting for expression, development, environment, and variation.",
  "germ-line mutation": "A mutation in a gamete-producing lineage that can be transmitted to offspring.",
  "goodness of fit": "A comparison of observed category counts with counts expected under a stated model.",
  "haploid": "Having one chromosome set, conventionally written n.",
  "haploid-dominant": "A life cycle in which the multicellular haploid stage is the main body and the diploid stage is brief.",
  "helicase": "An enzyme that separates paired DNA strands at a replication fork.",
  "hemizygous": "Having only one copy of a gene or chromosome region in a diploid cell, as for many X-linked loci in XY cells.",
  "heritability": "The proportion of observed variation in a trait attributable to genetic variation within a specified population and environment.",
  "heteroplasmy": "Presence of more than one mitochondrial DNA sequence variant within a cell or individual.",
  "heterozygous": "Having two different alleles at a locus in a diploid cell or organism.",
  "homologous chromosome": "One of a pair of chromosomes with corresponding loci, one typically inherited from each parent, though alleles may differ.",
  "homozygous": "Having two copies of the same allele at a locus in a diploid cell or organism.",
  "hypothesis": "A testable proposed explanation that generates evidence-based predictions.",
  "incidental finding": "A potentially meaningful result discovered outside the original purpose of an analysis or test.",
  "incomplete dominance": "An inheritance pattern in which a heterozygote's measured phenotype differs from both homozygotes, often lying between them.",
  "independent assortment": "Independent orientation and separation of different homologous chromosome pairs during meiosis, producing independent allele assortment for unlinked loci.",
  "independent event": "An event whose occurrence does not change the probability of another event under the stated model.",
  "independent variable": "The factor deliberately changed or used to define comparison groups in an investigation.",
  "insertion": "Addition of one or more nucleotides or of a chromosome segment.",
  "interphase": "The cell-cycle period including G1, S, and G2, when cells grow, function, replicate DNA, and prepare for division.",
  "intron": "A transcribed segment removed from a pre-mRNA during RNA splicing.",
  "joint probability": "The probability that two or more specified events occur together.",
  "karyotype": "An organized display or description of chromosomes used to examine number and large-scale structure.",
  "kinetochore": "A protein complex assembled at the centromere that attaches a chromosome to spindle microtubules.",
  "lagging strand": "The new DNA strand synthesized discontinuously as Okazaki fragments away from each advancing replication fork.",
  "law of segregation": "The principle that two alleles at a locus separate into different gametes during gamete formation.",
  "leading strand": "The new DNA strand synthesized continuously toward an advancing replication fork.",
  "life cycle": "The sequence of developmental and reproductive stages connecting one generation with the next.",
  "likelihood": "How compatible observed evidence is with a specified model or parameter value.",
  "likelihood ratio": "A comparison of how probable the same evidence is under two competing hypotheses.",
  "locus": "A defined chromosome position or DNA region used to locate a gene or marker.",
  "map unit": "A linkage-map distance equal to a one-percent recombination frequency; also called a centimorgan.",
  "meiosis": "A two-division process following one DNA replication that produces haploid cells and generates genetic variation.",
  "meiosis I": "The meiotic division in which homologous chromosomes separate, reducing chromosome-set number.",
  "meiosis II": "The meiotic division in which sister chromatids separate without another preceding DNA replication.",
  "messenger RNA": "An RNA molecule carrying a coding sequence from DNA transcription to a ribosome for translation.",
  "metaphase": "The division stage when chromosomes align at the cell's metaphase plate and attach to spindle structures.",
  "microtubule": "A dynamic cytoskeletal polymer that forms much of the spindle and moves or positions chromosomes.",
  "missense": "A coding-sequence change that substitutes one amino acid for another in a protein.",
  "mitochondrial inheritance": "Inheritance of mitochondrial DNA, usually through the egg cytoplasm in humans, with effects influenced by heteroplasmy.",
  "mitosis": "Nuclear division that separates replicated sister chromatids into genetically similar daughter nuclei.",
  "mitotic index": "The proportion of observed cells that are in mitosis at a particular time.",
  "model assumption": "A stated condition required for a model's predictions or calculations to apply.",
  "model calibration": "Assessment of whether predicted probabilities match observed frequencies in an appropriate population.",
  "monohybrid cross": "A genetic cross that follows inheritance at one locus.",
  "monosomy": "Aneuploidy in which one chromosome from a pair is missing.",
  "mosaicism": "Presence of genetically distinct cell populations derived from one zygote within an individual.",
  "multifactorial trait": "A trait influenced by multiple genetic factors, environmental factors, and their interactions.",
  "multiple alleles": "Three or more allele versions present at one locus in a population, though a diploid individual carries at most two.",
  "multiplication rule": "A probability rule that multiplies probabilities along a sequence of independent or conditional events.",
  "mutation": "A change in DNA sequence; its effect may be neutral, harmful, beneficial, conditional, or not yet known.",
  "mutually exclusive": "Describes outcomes that cannot occur together in the same trial under the stated categories.",
  "negative control": "A comparison expected to lack the target signal, used to reveal contamination or background effects.",
  "nondisjunction": "Failure of homologous chromosomes or sister chromatids to separate normally during cell division.",
  "nonsense": "A coding-sequence change that converts an amino-acid codon into a stop codon.",
  "nucleotide": "A phosphate, five-carbon sugar, and nitrogenous base; the repeating subunit of DNA and RNA.",
  "observed count": "The number actually measured in a category before comparison with a model.",
  "oogenesis": "Development of female gametes through mitosis, growth, meiosis, and unequal cytokinesis.",
  "origin of replication": "A DNA region where replication begins and replication forks form.",
  "parental combination": "An allele arrangement matching a chromosome combination present in the original parent, often more frequent than recombinant types in linkage crosses.",
  "passenger mutation": "A somatic mutation carried by a tumour cell that did not provide the growth advantage driving that tumour lineage.",
  "pedigree": "A diagram of reported trait occurrence and relationships across generations, interpreted probabilistically and with privacy safeguards.",
  "penetrance": "The proportion of individuals with a genotype who show the associated phenotype under specified conditions.",
  "peptide bond": "The covalent bond linking amino acids in a polypeptide.",
  "phenotype": "An observable or measurable characteristic produced through genotype, gene expression, development, and environment.",
  "phenotype probability": "The probability of a scored characteristic after translating genotype possibilities through the inheritance model.",
  "phosphodiester bond": "The covalent linkage joining adjacent nucleotides in a DNA or RNA sugar-phosphate backbone.",
  "plasmid": "A usually circular DNA molecule that replicates separately from a cell's main chromosome and can serve as a biotechnology vector.",
  "ploidy": "The number of complete chromosome sets in a cell or life-cycle stage.",
  "polar body": "A small haploid cell produced by unequal cytokinesis during oogenesis that usually does not become an egg.",
  "polygenic score": "A statistical score combining effects associated with many genetic variants; its usefulness depends on data, population, calibration, and context.",
  "polygenic trait": "A trait influenced by variation at many genetic loci, commonly also affected by environment.",
  "polypeptide": "A chain of amino acids joined by peptide bonds that can fold or combine to form a functional protein.",
  "positive control": "A comparison expected to produce a known signal, used to show that a method can detect its target.",
  "pre-mRNA": "A newly transcribed eukaryotic RNA containing introns and exons before processing into mature messenger RNA.",
  "primary oocyte": "A developing oocyte that has entered meiosis I and may remain arrested in prophase I for years.",
  "primary spermatocyte": "A diploid germ cell that has replicated its DNA and enters meiosis I during spermatogenesis.",
  "primase": "An enzyme that synthesizes short RNA primers needed to begin DNA synthesis.",
  "primer": "A short nucleic-acid strand providing a free 3-prime end for polymerase extension and helping define the copied region.",
  "promoter": "A DNA region where transcription machinery assembles to initiate transcription of a gene.",
  "proofreading": "Detection and correction of some newly incorporated nucleotide errors during DNA replication.",
  "prophase": "An early division stage when chromosomes condense, the spindle forms, and nuclear organization changes.",
  "proto-oncogene": "A normal gene promoting regulated growth or survival that can contribute to cancer when abnormally activated.",
  "randomization": "Assignment or ordering by chance to reduce systematic differences and selection bias.",
  "reading frame": "The grouping of an RNA coding sequence into consecutive three-nucleotide codons.",
  "recessive": "Describes an allele whose scored phenotype in simple dominance is usually observed only without a dominant allele.",
  "recognition site": "A specific DNA sequence bound and cut by a particular restriction endonuclease.",
  "recombinant DNA": "A DNA molecule assembled from sequences joined from different sources.",
  "recombinant chromatid": "A chromatid containing a new allele combination produced by crossing over.",
  "recombinant combination": "An offspring or gamete allele combination different from the parental chromosome arrangements.",
  "recombination": "Formation of new allele combinations through crossing over, independent assortment, and fertilization.",
  "recombination frequency": "The percentage of recombinant offspring or gametes in a cross, used to estimate linkage distance up to a practical maximum of 50 percent.",
  "reduction division": "A division that reduces chromosome-set number, specifically separation of homologous chromosomes in meiosis I.",
  "reference population": "The defined population whose data are used to estimate frequencies, train a model, or interpret a genetic result.",
  "replication": "The semiconservative copying of DNA before cell division.",
  "replication fork": "The Y-shaped region where parental DNA strands separate and new DNA strands are synthesized.",
  "reporter gene": "A gene whose measurable product indicates whether a sequence, promoter, or cellular event is active.",
  "reproducibility": "The capacity for others to repeat or independently evaluate work using transparent methods, data, and analysis.",
  "resolution": "The smallest difference or structural feature a method can reliably distinguish.",
  "restriction endonuclease": "An enzyme that recognizes a particular DNA sequence and cuts the phosphodiester backbone at or near that site.",
  "revision rule": "A stated finding or condition that would cause an explanation, model, or decision to change.",
  "ribosome": "An RNA-protein complex that reads mRNA codons and catalyzes polypeptide synthesis.",
  "sampling variation": "Chance difference between a sample result and the underlying probabilities or population because only a finite sample was observed.",
  "secondary oocyte": "The cell produced after meiosis I in oogenesis; in humans it is typically arrested in metaphase II until fertilization.",
  "secondary spermatocyte": "A haploid cell produced by meiosis I that proceeds through meiosis II during spermatogenesis.",
  "selectable marker": "A gene that allows cells carrying a vector to survive or be identified under selected conditions.",
  "semiconservative replication": "DNA copying in which each daughter double helix contains one parental strand and one newly synthesized strand.",
  "sex-linked": "Describes inheritance of a gene located on a sex chromosome, most commonly discussed for X-linked loci.",
  "sexual reproduction": "Reproduction involving meiosis and fusion of gametes, generating new combinations of genetic information.",
  "short tandem repeat": "A DNA region containing a short sequence repeated a variable number of times and commonly used as a genetic marker.",
  "single-nucleotide polymorphism": "A common DNA-sequence variation at one nucleotide position in a population.",
  "somatic cell nuclear transfer": "A cloning technique that places a somatic-cell nucleus into an enucleated oocyte to begin development.",
  "somatic mutation": "A mutation arising in a non-gamete cell lineage that can affect descendant cells but is usually not inherited by offspring.",
  "spermatid": "A haploid cell produced by meiosis II that differentiates into a sperm cell.",
  "spermatogenesis": "Development of sperm through mitosis, meiosis, and cellular differentiation in the testes.",
  "spermatogonium": "A diploid germ-line stem or precursor cell that divides mitotically and can enter spermatogenesis.",
  "spindle": "A microtubule-based structure that attaches to and moves chromosomes during cell division.",
  "spore": "A haploid reproductive cell that can grow by mitosis into a multicellular haploid organism without gamete fusion.",
  "start codon": "A codon, usually AUG, that establishes the translation reading frame and specifies methionine.",
  "sticky end": "A single-stranded DNA overhang produced by staggered cutting and capable of complementary base pairing.",
  "stop codon": "An mRNA codon that recruits a release factor and ends translation rather than specifying an amino acid.",
  "substitution": "Replacement of one nucleotide or chromosome segment with another.",
  "synapsis": "Close pairing of homologous chromosomes during meiotic prophase I.",
  "telomere": "A repetitive DNA-protein structure protecting a chromosome end from degradation and mistaken repair.",
  "telophase": "A late division stage when chromosomes reach the poles and new nuclear organization forms.",
  "template strand": "The DNA strand read by RNA polymerase to synthesize a complementary RNA transcript.",
  "test cross": "A cross with a homozygous recessive partner used to infer an unknown genotype or gamete frequencies.",
  "test-cross class": "One offspring category in a test cross, used to infer the gamete type produced by the tested parent.",
  "testable question": "A focused question that can be answered with observable or measurable evidence under a feasible method.",
  "tetrad": "The four-chromatid structure formed when replicated homologous chromosomes pair during meiotic prophase I.",
  "three-point cross": "A linkage cross following three loci to infer gene order and map distances, including possible double crossovers.",
  "transcription": "Synthesis of RNA from a DNA template by RNA polymerase.",
  "transfer RNA": "An adaptor RNA carrying a specific amino acid and an anticodon that pairs with an mRNA codon.",
  "transformation": "Uptake and expression of external genetic material by a cell; in biotechnology it often introduces a plasmid into bacteria.",
  "translation": "Ribosome-directed synthesis of a polypeptide according to the codon sequence of messenger RNA.",
  "trisomy": "Aneuploidy in which a particular chromosome is present in three copies rather than the usual pair.",
  "tumour heterogeneity": "Genetic and functional differences among cells within one tumour or among tumours from different people.",
  "tumour suppressor": "A gene whose normal product restrains cell division, promotes repair, or supports apoptosis and whose loss can contribute to cancer.",
  "two-point cross": "A linkage cross following two loci to estimate recombination frequency between them.",
  "unequal cytokinesis": "Division of cytoplasm into cells of different sizes, as in human oogenesis.",
  "vector": "A DNA molecule used to carry and replicate or express inserted genetic material in a host cell."
};
