export const BIOLOGY30_UNIT_D_GLOSSARY: Record<string, string> = {
  "2pq": "The Hardy-Weinberg expected frequency of heterozygotes when two alleles have frequencies p and q.",
  "Hardy-Weinberg equilibrium": "A model in which allele and genotype frequencies remain stable under stated no-change assumptions.",
  "adaptive management": "A decision process that links action to predictions, monitoring, thresholds, and planned revision.",
  "adaptive recommendation": "A proposed action that includes evidence, uncertainty, indicators, and a rule for changing course.",
  "allele frequency": "The proportion of all copies of a locus in a population that are a particular allele.",
  "biological legacy": "Soil, organisms, seeds, roots, organic matter, or structures that remain after disturbance.",
  "bottleneck effect": "Genetic drift caused by a sharp population reduction that leaves an unrepresentative gene pool.",
  "carrying capacity": "The population size an environment can sustain over time under stated conditions.",
  "chronosequence": "A set of sites of different ages used to infer temporal change by substituting space for time.",
  "coevolution": "Reciprocal evolutionary change in interacting species caused by selection they impose on one another.",
  "commensalism": "An interaction in which one participant benefits and no effect on the other is detected.",
  "community": "Populations of different species living and interacting in an area.",
  "competition": "An interaction in which organisms reduce one another’s access to a limiting resource.",
  "competitive exclusion": "The prediction that complete competitors cannot coexist indefinitely under constant conditions.",
  "density dependence": "A relationship in which an effect or per-capita rate changes as population density changes.",
  "density-dependent": "Describes a limiting effect whose strength varies with population density.",
  "density-independent": "Describes an effect that is not systematically related to population density over the observed range.",
  "detectability": "The probability that an organism present in a study area is actually observed or captured.",
  "distribution": "The spatial pattern of individuals, commonly described as clumped, uniform, or approximately random at a stated scale.",
  "ecosystem": "A biological community together with the non-living environment and their transfers of energy and matter.",
  "effective population size": "The size of an idealized population that would experience genetic drift like the population being studied.",
  "emigration": "Movement out of a population that removes individuals from its count.",
  "expected frequency": "A model-derived proportion predicted under stated assumptions rather than directly observed.",
  "exponential growth": "Growth in which total change is proportional to population size at a constant positive per-capita rate.",
  "facilitation": "A succession mechanism in which earlier occupants change conditions in ways that help later establishment.",
  "factorial design": "An investigation that tests two or more factors alone and together to estimate separate and interacting effects.",
  "fitness": "Relative reproductive contribution to future generations in a particular environment.",
  "founder effect": "Genetic drift when a new population begins from a small, unrepresentative group.",
  "fundamental niche": "The range of resources and conditions a species could use without limiting biotic interactions.",
  "gene flow": "Transfer of alleles among populations when migrants or their gametes reproduce.",
  "gene pool": "All allele copies at all loci in a defined population.",
  "genetic diversity": "Variation in alleles and genotypes within a population or species.",
  "genetic drift": "Random allele-frequency change caused by finite sampling across generations.",
  "genetic equilibrium": "Stability of allele and genotype frequencies across generations under a specified model.",
  "genotype frequency": "The proportion of individuals in a population that have a particular genotype.",
  "goodness-of-fit": "A statistical comparison of observed values with values expected under a model.",
  "immigration": "Movement into a population that adds individuals to its count.",
  "inhibition": "A succession mechanism in which established organisms reduce later recruitment until conditions change.",
  "integrated evidence": "Evidence from multiple biological scales organized into one bounded explanation.",
  "intrinsic rate of increase": "The potential per-capita rate of population change under stated conditions.",
  "life history": "The pattern of growth, survival, reproduction, and allocation across an organism’s life.",
  "limiting factor": "A resource, condition, or interaction that constrains survival, reproduction, or population growth.",
  "logistic growth": "A model in which per-capita growth declines as population size approaches carrying capacity.",
  "mark-recapture": "A sampling method that estimates population size from marked individuals later recaptured in a second sample.",
  "model assumption": "A stated condition that defines when a scientific model’s predictions apply.",
  "mutation": "A change in DNA sequence that can create a new allele when inherited.",
  "mutualism": "An interaction in which both participants receive a net measured benefit under stated conditions.",
  "natural selection": "Differential reproductive contribution caused by heritable phenotypic differences in an environment.",
  "niche": "How a species uses resources and conditions and interacts within its ecological setting.",
  "overshoot": "A temporary rise of population size above the environment’s current carrying capacity.",
  "p": "The frequency assigned to one of two alleles in a Hardy-Weinberg model.",
  "parasitism": "An interaction in which a parasite benefits while reducing host fitness.",
  "population": "Individuals of one species in an area and time with a realistic opportunity to reproduce.",
  "population density": "The number of individuals per unit area or volume.",
  "population size": "The number of individuals, N, inside a defined population boundary.",
  "population viability": "The likelihood that a population persists under demographic, genetic, environmental, and catastrophic risks.",
  "precautionary approach": "Decision reasoning that considers serious or irreversible harm when evidence is uncertain.",
  "predation": "An interaction in which one organism captures and consumes another organism.",
  "primary succession": "Community development beginning where developed soil and substantial terrestrial biological legacies are absent.",
  "priority effect": "An effect of arrival order in which early occupants change opportunities for later arrivals.",
  "p²": "The Hardy-Weinberg expected frequency of the homozygous genotype formed from allele p.",
  "q": "The frequency assigned to the second of two alleles in a Hardy-Weinberg model, where p + q = 1.",
  "q²": "The Hardy-Weinberg expected frequency of the homozygous genotype formed from allele q.",
  "r/K continuum": "A simplified comparison of life-history trait trade-offs under different mortality and density conditions.",
  "random mating": "Mating in which genotype at the focal locus does not affect partner choice or gamete union.",
  "realized niche": "The resources and conditions a species actually uses under competition, predation, and other constraints.",
  "recruitment": "Addition of individuals to the life stage or count used by a population study.",
  "resource partitioning": "Reduced competition through differences in resource type, space, or time of use.",
  "secondary succession": "Community development after disturbance where soil or other biological legacies remain.",
  "tolerance": "A succession mechanism in which later species establish despite earlier occupants and persist under the resulting conditions.",
  "trade-off": "A biological constraint in which investment or benefit in one function carries a cost in another."
};
