export const BIOLOGY30_UNIT_B_GLOSSARY: Record<string, string> = {
  "FSH": "Follicle-stimulating hormone; an anterior-pituitary gonadotropin that supports ovarian follicle development and acts through Sertoli cells to support spermatogenesis.",
  "GnRH": "Gonadotropin-releasing hormone; a hypothalamic signal that stimulates anterior-pituitary release of FSH and LH.",
  "HPV": "Human papillomavirus; a group of viruses, some of which can cause warts and some of which can contribute to cancers after persistent infection.",
  "LH": "Luteinizing hormone; an anterior-pituitary gonadotropin involved in ovulation and corpus-luteum formation and in testicular testosterone production.",
  "SRY": "A gene region commonly located on the Y chromosome that can initiate a testis-development pathway; gene location and response can vary.",
  "Sertoli cell": "A supporting cell within a seminiferous tubule that helps regulate and nourish developing sperm cells.",
  "acrosome reaction": "Release of enzymes and membrane changes that help a sperm cell cross layers surrounding an oocyte.",
  "allantois": "An extra-embryonic structure that contributes to parts of the umbilical cord and urinary-bladder developmental pathway.",
  "amnion": "The extra-embryonic membrane that encloses the fluid-filled amniotic cavity.",
  "amniotic fluid": "Fluid surrounding the developing embryo or fetus that cushions, permits movement, and supports a stable local environment.",
  "androgen": "A class of steroid hormones, including testosterone and dihydrotestosterone, that act through androgen receptors.",
  "association": "A measured relationship between variables that does not, by itself, establish that one variable caused the other.",
  "asymptomatic": "Present without noticeable symptoms; an asymptomatic infection may still be transmissible or biologically important.",
  "barrier method": "A reproductive-health method that physically reduces movement or contact, with effectiveness depending on the specific method and use.",
  "blastocyst": "An early developmental stage with an outer trophoblast, inner cell mass, and fluid-filled cavity.",
  "blastomere": "One of the smaller cells produced by early cleavage divisions.",
  "bulbourethral gland": "An accessory gland, also called a Cowper’s gland, that releases fluid into the male reproductive tract.",
  "capacitation": "Functional changes sperm undergo in the female reproductive tract that help prepare them for fertilization.",
  "causal inference": "A reasoned judgment about whether and how one factor contributes to an outcome, based on design, mechanism, alternatives, and converging evidence.",
  "cervix": "The lower, narrow region of the uterus that opens into the vagina.",
  "chorion": "An outer extra-embryonic membrane that contributes to the fetal portion of the placenta and chorionic villi.",
  "chorionic villus": "A branching placental structure containing fetal vessels and providing a large exchange surface near maternal blood.",
  "cleavage": "Rapid early mitotic divisions that increase cell number without a proportional increase in overall conceptus size.",
  "competing explanation": "An alternative mechanism that could account for some or all of the same observations and must be tested against evidence.",
  "conception control": "Methods intended to reduce the probability of pregnancy by acting at defined reproductive steps.",
  "confounding": "Distortion that occurs when another factor is related to both the proposed cause and the measured outcome.",
  "continuity": "Reliable transmission of biological information and life processes across cells or generations.",
  "convergence": "Agreement among independent evidence types that strengthens an explanation.",
  "corpus luteum": "Temporary endocrine tissue formed from an ovulated follicle that produces progesterone and estrogen.",
  "cryopreservation": "Storage of cells or tissues at very low temperature to slow biological activity for later use.",
  "differentiation": "The regulated process through which cells develop specialized gene-expression patterns, structures, and functions.",
  "dihydrotestosterone": "A potent androgen produced from testosterone in selected tissues and involved in parts of reproductive development.",
  "discriminating evidence": "A result expected to differ between competing explanations and therefore help distinguish them.",
  "dose-response": "A pattern in which the magnitude or probability of an effect changes with exposure amount.",
  "ductus deferens": "A muscular duct, also called the vas deferens, that transports sperm from the epididymis toward the ejaculatory duct.",
  "ectoderm": "The primary germ layer that contributes to the epidermis, nervous system, and selected sensory structures.",
  "embryo transfer": "Placement of an embryo into a uterus during an assisted-reproduction procedure.",
  "embryonic period": "The prenatal period emphasizing implantation, gastrulation, body-plan establishment, and early organogenesis.",
  "endoderm": "The primary germ layer that contributes to much of the digestive and respiratory epithelial lining and to selected glands.",
  "endometrium": "The hormone-responsive inner lining of the uterus where implantation may occur.",
  "epididymis": "A coiled duct where sperm mature and are stored after leaving the testes.",
  "estrogen": "A class of steroid hormones involved in reproductive-tissue function, secondary sex characteristics, cycle regulation, and feedback.",
  "evidence ledger": "A structured record separating observations, sources, units, timing, interpretations, and limits.",
  "feedback": "Return information from a response or downstream signal that changes later activity in a control system.",
  "fertility": "The biological capacity or probability of reproduction, influenced by many interacting factors and not established by one classroom measure.",
  "fertilization": "A sequence in which sperm and oocyte membranes and genetic material combine to begin development of a zygote.",
  "fetal period": "The prenatal period emphasizing growth, maturation, and increasing functional integration after the embryonic period.",
  "follicle": "An ovarian structure containing an oocyte and surrounding support and hormone-producing cells.",
  "follicular phase": "The ovarian-cycle phase during which follicles develop before ovulation.",
  "gamete": "A haploid reproductive cell—sperm or egg lineage cell—that can contribute one chromosome set at fertilization.",
  "gastrulation": "Early embryonic cell movements that establish primary germ layers and body organization.",
  "gender": "A social and personal dimension of identity and roles that cannot be inferred from one chromosome, hormone, or anatomical measure.",
  "germ layer": "One of the primary embryonic tissue layers—ectoderm, mesoderm, or endoderm—from which tissues develop.",
  "gonad": "An ovary or testis; an organ that produces gametes and reproductive hormones.",
  "gonadotropin": "A hormone such as FSH or LH that acts on gonadal targets.",
  "hCG": "Human chorionic gonadotropin; a trophoblast-derived hormone that helps maintain corpus-luteum function early in pregnancy.",
  "hormonal contraception": "A conception-control approach that uses hormones to change ovulation, mucus, endometrial, or related reproductive conditions depending on the method.",
  "implantation": "Attachment and embedding of a hatched blastocyst in a receptive uterine endometrium.",
  "in vitro fertilization": "An assisted-reproduction process in which oocytes and sperm are combined or injected in a laboratory before an embryo may be transferred.",
  "inflammation": "A coordinated tissue response to injury or infection that can protect but may also contribute to pain, swelling, or tissue damage.",
  "informed consent": "A voluntary decision made with understandable information about purpose, benefits, risks, alternatives, and the right to refuse.",
  "inner cell mass": "The blastocyst cell cluster that contributes to the embryo proper and some extra-embryonic tissues.",
  "interstitial cell": "A testicular cell between seminiferous tubules that produces testosterone in response to LH.",
  "intrauterine device": "A small device placed in the uterus that reduces pregnancy probability through method-specific local mechanisms.",
  "lactation": "Production and delivery of milk by mammary glands after birth, regulated by endocrine and neural signals.",
  "luteal phase": "The ovarian-cycle phase after ovulation when the corpus luteum produces progesterone and estrogen.",
  "menstrual cycle": "A coordinated set of ovarian, uterine, and hormonal changes conventionally tracked from the first day of menstrual bleeding.",
  "menstruation": "Shedding of much of the functional endometrial layer after ovarian-hormone support declines in a non-pregnant cycle.",
  "mesoderm": "The primary germ layer that contributes to muscle, skeleton, connective tissues, blood, kidneys, gonads, and many reproductive structures.",
  "milk ejection": "Oxytocin-supported contraction of myoepithelial cells that moves milk through mammary ducts.",
  "morphogenesis": "Development of tissue and organ shape through coordinated growth, movement, folding, adhesion, and cell death.",
  "morula": "A compact early ball of blastomeres formed during cleavage before the blastocyst stage.",
  "myoepithelial cell": "A contractile cell around mammary secretory structures that responds to oxytocin during milk ejection.",
  "negative feedback": "Control in which a response reduces the original deviation or lowers upstream stimulation.",
  "neural crest": "Migratory cells arising near the neural tube that contribute to diverse structures, including parts of the peripheral nervous system.",
  "oocyte": "A developing female germ cell; stage names such as primary and secondary oocyte reflect meiotic state.",
  "oocyte retrieval": "A medical procedure used to collect oocytes from ovarian follicles for assisted reproduction.",
  "organogenesis": "Developmental formation and organization of organs from interacting tissues.",
  "ovarian cycle": "The sequence of follicular development, ovulation, and luteal activity in the ovaries.",
  "ovary": "A gonad that contains developing oocytes and produces reproductive hormones.",
  "ovulation": "Release of a secondary oocyte and surrounding cells from a mature ovarian follicle.",
  "oxytocin": "A posterior-pituitary-released hormone involved in uterine contraction and milk ejection.",
  "parturition": "The coordinated process of labour and birth.",
  "pathogen": "A biological agent, such as a bacterium or virus, capable of causing infection or disease.",
  "pelvic inflammatory disease": "Inflammation and infection of upper reproductive-tract tissues that can follow some untreated infections and may affect fertility.",
  "placenta": "A temporary exchange, endocrine, immune, and metabolic organ formed from fetal and maternal tissues during pregnancy.",
  "placental barrier": "The tissue interface separating maternal and fetal circulations while permitting selective exchange.",
  "positive feedback": "Control in which a response amplifies the initiating change until an endpoint interrupts the loop.",
  "progesterone": "A steroid hormone that supports secretory endometrial conditions, pregnancy-related changes, and reproductive feedback.",
  "prolactin": "An anterior-pituitary hormone that supports milk production in mammary tissue.",
  "proliferative phase": "The uterine-cycle phase in which estrogen supports rebuilding and growth of the endometrium.",
  "prostaglandin": "A locally acting lipid signal involved in processes including cervical change and uterine contraction.",
  "prostate gland": "A male accessory gland that contributes fluid to semen.",
  "receptor": "A protein that binds a signal and initiates or changes a cellular response.",
  "reproduction": "Biological processes that produce new organisms and transmit genetic information across generations.",
  "revision rule": "A stated result or condition that would cause an explanation or decision to be changed.",
  "secretory phase": "The progesterone-supported uterine phase in which the endometrium becomes more glandular and secretory after ovulation.",
  "semen": "Fluid containing sperm when present plus secretions from reproductive accessory glands.",
  "seminal vesicle": "A male accessory gland that contributes a substantial portion of seminal fluid.",
  "seminiferous tubule": "A coiled testicular tubule where sperm cells develop with Sertoli-cell support.",
  "sex characteristic": "A chromosomal, gonadal, hormonal, anatomical, or secondary physical trait related to sexual development; no one measure represents every dimension.",
  "sexually transmitted infection": "An infection that can be transmitted through sexual contact; pathogens, symptoms, prevention, testing, and treatment differ.",
  "sterilization": "A procedure intended as highly effective permanent conception control by interrupting gamete transport or reproductive anatomy.",
  "temporal plausibility": "The requirement that a proposed cause occur early enough and in the right developmental sequence to influence an outcome.",
  "teratogen": "An environmental agent that can disrupt development under particular dose, route, timing, and biological conditions.",
  "testosterone": "A steroid androgen produced mainly by testicular interstitial cells and involved in reproductive function and development.",
  "trimester": "One of three broad time divisions used to describe pregnancy; biological processes overlap these boundaries.",
  "trophoblast": "The blastocyst outer cell layer that contributes to implantation and the fetal portion of the placenta.",
  "umbilical artery": "A fetal vessel carrying blood from the fetus toward the placenta.",
  "umbilical vein": "A fetal vessel carrying oxygen- and nutrient-enriched blood from the placenta toward the fetus.",
  "uncertainty": "A transparent description of limits in measurement, sampling, models, evidence, or prediction.",
  "urethra": "A duct carrying urine and, at different times in typical male anatomy, semen to the exterior.",
  "uterine tube": "A duct, also called a Fallopian tube, that receives an ovulated oocyte and is the usual site of fertilization.",
  "uterus": "A muscular reproductive organ containing the endometrium and supporting implantation and prenatal development.",
  "vaccination": "Use of an antigen-based preparation to train immune protection against selected pathogens before exposure.",
  "vagina": "A muscular canal connecting the cervix with the exterior.",
  "variation": "Differences among organisms arising from genetic recombination, mutation, development, and environmental context.",
  "zygote": "The diploid cell formed after fertilization and combination of parental chromosome sets."
};
