from course_authoring import *
L=[]
L.append(lesson('Populations, gene pools and genetic variation','What changes when a population evolves?',
'Define a gene pool and distinguish change in a population from change within an individual.',
'Individuals carry alleles. Inheritance passes alleles between generations, while population size can also change.',[678,679],[3,4,5,6],
[term('population','Individuals of the same species occupying a defined area during a defined time.','The breeding rabbits in a specified valley during one season form the study population.','A population boundary must be stated before counting frequencies.','A population is every organism of every species in an ecosystem.'),term('gene pool','All the alleles present in the reproductive population being considered.','A population contains several alleles at many different loci.','A gene pool describes a population, not only one individual’s genotype.','A gene pool is the set of organs inside one organism.'),term('genetic variation','Differences in genetic information among individuals or lineages.','Individuals carry different alleles at a pigment locus.','Not all phenotypic variation is genetic.','Every visible difference must be caused by a different allele.'),term('microevolution','A change in allele frequencies in a population across generations.','An allele’s proportion changes from 0.30 to 0.45 between sampled generations.','A larger population can retain the same allele frequencies.','Any increase in population size is automatically an allele-frequency change.')],
[sec('Define the population you are studying','''Population genetics studies the genetic composition of populations and how that composition changes. A population consists of individuals of the same species within a defined place and time. Those boundaries matter: counting one breeding colony is not the same as counting every colony across a continent.

The gene pool is the collection of alleles present in that population. An individual carries only part of the population’s variation. At an ordinary diploid autosomal locus, each individual contributes two allele copies.'''),sec('Track proportions across generations','''Microevolution is a change in allele frequencies across generations. An allele frequency is its share of all allele copies at the locus. It is a proportion, not simply the number of individuals showing a trait.

Suppose a population doubles in size while every allele’s proportion stays the same. The number of copies increases, but the allele frequencies have not changed. Conversely, frequencies can change even if the total population size remains constant.

An individual’s body can grow, develop or adjust to conditions. Those changes are not themselves evidence that a population’s inherited allele frequencies have changed.'''),sec('Distinguish genetic and environmental differences','''Genetic variation can influence phenotypes, but environment and gene regulation also matter. A plant grown in shade may differ from a genetically similar plant grown in bright light. That observation alone does not identify an allele-frequency change.

To study evolution at a locus, specify the alleles and measure or infer their frequencies with appropriate evidence. Later lessons explain when genotype counts permit direct counting and when a mathematical model is required.

Do not assume every genetic difference is advantageous, or that evolution always moves toward greater size or complexity. The mechanisms can include selection and chance.''')],
worked('Count change versus frequency change','A population grows from 100 to 200 diploid individuals. Allele A rises from 60 of 200 copies to 120 of 400 copies.',
'At the first sampling, A frequency is 60/200 = 0.30.','At the second, it is 120/400 = 0.30.','The number of A copies doubled but its proportion did not.','These measurements show no allele-frequency change at this locus over the interval.'),
[g('Which unit has a gene pool?','A population',['A single protein','One organelle only'],'A gene pool is a population-level collection of alleles.','Identify the level of biological organization.'),g('Population size doubles while allele proportions stay equal. Has this alone shown microevolution at the locus?','No',['Yes, because all growth is evolution','Yes, because allele counts cannot rise'],'Microevolution is about frequencies, not count alone.','Compare the numerator with the denominator at both times.')],
[q('Which observation directly indicates microevolution at a locus?','A change in allele frequency across generations',['One individual gains body mass','The same allele proportions occur in a larger sample','Plants differ in height after receiving different amounts of water'],'An inherited population proportion is the relevant quantity.'),q('Why must the population boundary be defined?','It determines which individuals and allele copies belong in the sample',['It makes all individuals genetically identical','It prevents any future mutation','It guarantees Hardy–Weinberg equilibrium'],'Frequencies depend on the population and sampling frame.')],
[w('Use an example to distinguish an allele count from an allele frequency.','If A occurs 20 times among 100 copies, its frequency is 0.20. If it later occurs 40 times among 200 copies, its count increased but frequency remains 0.20. Frequency compares copies with the relevant total.'),w('Explain why a change in an individual’s phenotype does not automatically demonstrate population evolution.','Development or environmental conditions can change a phenotype without altering inherited allele frequencies. Population evolution must be evaluated across the defined population and generations, using evidence of changes in allele proportions.')],
q('A plant population’s mean height changes after fertilization of the soil, but no genetic data are supplied. What is justified?','An environmental explanation remains possible',['A new allele must have reached frequency 1','The population has definitely undergone genetic drift','Every short plant must have died'],'Phenotypic change does not alone establish an allele-frequency change.'),
('Can population size remain constant while allele frequencies change?','Yes. The composition can change even when the total number does not.')))

L.append(lesson('Allele frequencies and genotype frequencies','Why do allele calculations usually use twice as many copies as individuals?',
'Calculate genotype and allele frequencies directly from diploid genotype counts.',
'At a diploid autosomal locus, an individual carries two allele copies, even when both are the same.',[679,682],[6,7,8],
[term('genotype frequency','The proportion of individuals with a specified genotype.','Thirty AA individuals in a population of 100 give frequency 0.30.','Its denominator is the number of individuals sampled.','Genotype frequency always divides by twice the population size.'),term('allele frequency','The proportion of allele copies represented by a particular allele at a locus.','Twenty A copies among 50 copies give frequency 0.40.','For an ordinary diploid autosomal sample, the denominator is 2N.','An AA individual contributes only one A copy.'),term('heterozygote contribution','The contribution of one copy of each allele from a heterozygous individual.','Each Aa individual contributes one A and one a to the allele count.','Count both copies, not half an individual.','A heterozygote contributes two dominant alleles.'),term('frequency sum','The requirement that mutually exclusive complete categories account for the whole sample.','At a two-allele locus, p + q = 1.','The relevant categories and denominator must be consistent.','Genotype frequencies and allele frequencies may be mixed in one sum without distinction.')],
[sec('Count individuals for genotype frequencies','''Let N be the number of diploid individuals sampled at a two-allele autosomal locus. The possible genotypes are AA, Aa and aa. Genotype frequency is the number with one genotype divided by N.

For 30 AA, 50 Aa and 20 aa individuals, N = 100. The frequencies are 0.30, 0.50 and 0.20. They add to 1 because every sampled individual belongs to exactly one of these genotype categories.'''),sec('Count copies for allele frequencies','''The same sample contains 2N = 200 allele copies. Each AA contributes two A copies, each Aa contributes one A and one a, and each aa contributes two a copies.

The A count is 2(30) + 50 = 110, so p = 110/200 = 0.55. The a count is 2(20) + 50 = 90, so q = 90/200 = 0.45. The allele frequencies also add to 1.

The general relationships are p = [2(AA) + Aa]/2N and q = [2(aa) + Aa]/2N, where the genotype symbols inside the brackets represent counts. Write units or category names beside the numbers so that individuals are not mistaken for allele copies.'''),sec('Direct counting does not need equilibrium','''When all genotype counts are known, allele frequencies can be calculated directly. You do not need to assume Hardy–Weinberg equilibrium to count copies.

A recessive phenotype alone provides different information. Under a simple complete-dominance model, it identifies aa individuals but does not separate AA from Aa among dominant-phenotype individuals. Additional assumptions would be needed to infer all allele frequencies from that phenotype count alone.

Check every calculation: genotype counts total N, allele counts total 2N, and both sets of frequencies separately sum to 1.''')],
worked('Use all genotype counts','A sample has 40 AA, 40 Aa and 20 aa individuals. Find p and q.',
'Total individuals N = 100; total allele copies = 200.','A copies = 2(40) + 40 = 120, so p = 120/200 = 0.60.','a copies = 2(20) + 40 = 80, so q = 80/200 = 0.40.','Check: 0.60 + 0.40 = 1.','These are direct counts, not an inference from equilibrium.'),
[g('How many A copies do 12 AA individuals contribute?','24',['12','6'],'Each homozygote contributes two A copies.','Count copies per individual.'),g('A sample has 50 diploid individuals. What is the allele-copy denominator at one autosomal locus?','100',['50','25'],'There are two copies per individual.','Multiply N by ploidy for the stated locus.')],
[q('In 20 AA, 60 Aa and 20 aa individuals, what is p?','0.50',['0.20','0.60','0.80'],'A copies = 40 + 60 = 100 of 200.'),q('Which calculation is a genotype frequency?','Number of Aa individuals divided by N',['Number of A copies divided by 2N','Twice the number of AA plus the number of Aa','The square root of every observed proportion'],'Genotype frequency counts individuals in a genotype category.')],
[w('Calculate genotype frequencies and allele frequencies for 25 AA, 50 Aa and 25 aa individuals. Explain the denominators.','N = 100, giving genotype frequencies 0.25, 0.50 and 0.25. There are 200 allele copies. A copies = 50 + 50 = 100, and a copies = 50 + 50 = 100, giving p = q = 0.50. Genotypes use individuals; alleles use copies.'),w('Explain why directly known genotype counts do not require a Hardy–Weinberg assumption to determine p and q.','Every genotype explicitly specifies its two allele copies. Summing those contributions yields the observed allele totals directly. Equilibrium becomes relevant when predicting genotype frequencies from alleles or inferring unobserved genotypes from limited phenotype information.')],
q('A sample contains 10 AA, 20 Aa and 20 aa individuals. What is the a frequency?','0.60',['0.40','0.20','0.80'],'a copies = 20 + 40 = 60 of 100.'),
('Can the dominant phenotype always distinguish AA from Aa?','No. Under complete dominance, both can have the same phenotype.')))

L.append(lesson('The Hardy–Weinberg model and its assumptions','What does a non-evolving reference model allow us to predict?',
'Explain the model’s conditions and distinguish allele totals from expected genotype frequencies.',
'For two alleles, p + q = 1 by definition. Direct allele counts are possible when genotypes are known.',[681,684],[7,8,9,10],
[term('Hardy–Weinberg equilibrium','A model in which allele frequencies remain constant and genotype frequencies follow p², 2pq and q² under stated conditions.','A large randomly mating population with no selection, migration or mutation is the reference model.','The model is a baseline to test, not an automatic property of every population.','Any population with a recessive phenotype must be in equilibrium.'),term('random mating','Mating that is independent of the genotype being considered.','Gamete combinations can be modelled from allele frequencies without genotype-based mate preference.','Random mating at one locus does not mean every behaviour is random.','Random mating means every pair produces an identical number and genotype of offspring.'),term('p²','The expected frequency of one homozygous genotype under a two-allele Hardy–Weinberg model.','If p = 0.70, the expected AA frequency is 0.49.','It is an expected genotype frequency, not another allele frequency.','p² is always the frequency of the A allele itself.'),term('2pq','The expected heterozygote frequency under the two-allele Hardy–Weinberg model.','Aa can form from A then a or a then A.','The factor two counts the two ways to form a heterozygote.','The heterozygote frequency is pq because only one parental direction is possible.')],
[sec('Start with the allele pool','''At a locus with two alleles, let p be the frequency of A and q the frequency of a. Because these are the complete allele categories, p + q = 1. This identity does not require equilibrium.

If gametes combine randomly with those frequencies, AA has expected frequency p × p = p² and aa has q × q = q². A heterozygote can arise as A from one gamete and a from the other, or the reverse. Its total expected frequency is pq + qp = 2pq.'''),sec('Name the conditions rather than hiding them','''The Hardy–Weinberg reference model assumes a very large population, random mating with respect to the locus, no mutation, no migration and no natural selection affecting the alleles or genotypes. A very large population minimizes chance fluctuations from sampling.

Under these idealized conditions, allele frequencies remain constant across generations and genotype proportions follow p² + 2pq + q² = 1. The model gives a baseline for asking whether observed data fit the prediction.

A real population need not satisfy every condition perfectly. A mismatch can suggest that assumptions need investigation, but the mismatch alone does not identify which mechanism caused it.'''),sec('Dominance is not the cause of frequency','''The letters p and q can represent the two alleles whether or not one is dominant. In familiar complete-dominance problems, p often names the dominant allele and q the recessive allele. This notation does not make p larger than q.

Dominance determines the heterozygote’s phenotype. It does not determine the allele’s frequency or guarantee that the dominant allele is favoured by selection.

When only the recessive phenotype count is given, identifying q² and taking its square root requires the stated equilibrium and phenotype-model assumptions. Without them, do not silently infer the unobserved genotypes.''')],
worked('Derive a heterozygote prediction','At a two-allele locus, p = 0.70 and q = 0.30. Assume Hardy–Weinberg conditions.',
'AA expectation is 0.70 × 0.70 = 0.49.','aa expectation is 0.30 × 0.30 = 0.09.','Aa expectation is 2 × 0.70 × 0.30 = 0.42.','Check: 0.49 + 0.42 + 0.09 = 1.','These genotype predictions depend on the model, unlike the allele total p + q = 1.'),
[g('Why does heterozygote frequency contain a factor of two?','A and a can combine in two parental orders',['A heterozygote has four alleles','Dominant alleles are counted twice in every genotype'],'Both A/a and a/A combinations contribute.','Count the two ways gametes can combine.'),g('Which relationship is a two-allele identity even without equilibrium?','p + q = 1',['Observed AA must equal p²','Observed Aa must always equal 2pq'],'The two allele proportions account for all copies.','Separate a category total from a model prediction.')],
[q('Which population condition conflicts with the simplest Hardy–Weinberg assumptions?','Persistent genotype-dependent differences in reproductive success',['A very large population','No migration','Random mating at the locus'],'Genotype-dependent selection violates the no-selection condition.'),q('Can a dominant allele have frequency 0.10?','Yes; dominance and frequency describe different things',['No; a dominant allele must exceed 0.50','No; p is always exactly 1','Yes, but then all individuals must be homozygous'],'The heterozygote phenotype does not determine population prevalence.')],
[w('Explain how p² + 2pq + q² is obtained from gamete frequencies.','Random combination of A with frequency p and a with frequency q produces AA with p² and aa with q². Aa can form in two orders, each pq, giving 2pq. The three expected genotype categories sum to 1.'),w('List the five ideal conditions and explain why the model is useful even when real populations differ from it.','The model assumes a very large population, random mating, no mutation, no migration and no selection. It creates a reference prediction. Comparing real observations with it can reveal a mismatch and guide investigation of assumptions without automatically identifying one cause.')],
q('Only the proportion of recessive-phenotype individuals is known, with no equilibrium statement. What is missing before inferring q by a square root?','Justification for the genotype-frequency model',['The colour of the counting sheet','A rule that recessive alleles are uncommon','The maximum possible adult body size'],'The observed recessive fraction is an aa frequency, but equating it with q² needs the model.'),
('Does p² + 2pq + q² = 1 prove that a real population satisfies all five assumptions?','No. A calculation using the formula is not evidence that the assumptions hold.')))

L.append(lesson('Calculating expected genotype frequencies','How do you move from a recessive phenotype count to expected carrier numbers?',
'Solve Hardy–Weinberg problems with explicit assumptions, separate quantities and reasonableness checks.',
'Under the stated model, recessive phenotype aa has frequency q², not q.',[683,688],[11,12,13,14,15,16,17,18,19,20],
[term('q²','The expected aa genotype frequency under a two-allele Hardy–Weinberg model.','If q is 0.40, q² is 0.16.','A recessive phenotype fraction can be used as q² only with the appropriate model.','The recessive phenotype fraction always equals q directly.'),term('carrier frequency','The proportion of heterozygotes carrying a recessive allele in the stated model.','For Hardy–Weinberg p = 0.60 and q = 0.40, carriers have frequency 0.48.','For this simple recessive model, carriers are heterozygotes, not all individuals with a.','Every carrier is homozygous recessive.'),term('expected count','A model-predicted number obtained by multiplying a frequency by population size.','A frequency of 0.48 in N = 200 gives 96 expected individuals.','Expected counts need not be exactly realized in a finite sample.','An expected count guarantees the exact outcome in every sample.'),term('square-root step','Recovering q from q² when the Hardy–Weinberg assumptions apply.','If q² = 0.09, q = 0.30.','Taking a square root is not the same as dividing the frequency by two.','If q² is 0.16, q must be 0.08.')],
[sec('Identify the given quantity','''Suppose a recessive phenotype occurs in 32 of 200 individuals and the problem explicitly assumes Hardy–Weinberg equilibrium with complete dominance. The observed aa fraction is 32/200 = 0.16, which is used as q².

Take the square root to obtain the recessive allele frequency: q = √0.16 = 0.40. Then p = 1 − q = 0.60. Do not call 0.16 the allele frequency; it describes individuals with two recessive copies.'''),sec('Predict genotypes and convert to counts','''Use the allele frequencies to calculate the expected genotype frequencies: p² = 0.36, 2pq = 0.48 and q² = 0.16. These are the expected fractions of AA, Aa and aa individuals.

To obtain counts, multiply each frequency by N = 200. The expected numbers are 72 AA, 96 Aa and 32 aa. Check that the counts total 200 and the frequencies total 1.

The heterozygotes are carriers in this simple recessive model. The dominant-phenotype fraction includes AA and Aa together, so it is 0.36 + 0.48 = 0.84, not p alone.'''),sec('Keep precision until the final answer','''Carry sufficient decimal precision through square roots and multiplication. Round the final expected number to an appropriate whole individual only after completing the calculation. Rounding q too early can noticeably change a carrier estimate.

If allele frequency is already given, start with that value instead of taking another square root. If all genotype counts are given, direct allele counting may be the appropriate first method.

A strong answer states the model, labels each quantity, shows the calculation and interprets the result. A bare number makes it difficult to see whether the correct denominator and assumption were used.''')],
worked('Estimate carriers for a rare recessive condition','In a hypothetical population at Hardy–Weinberg equilibrium, 1 in 10 000 individuals has a fully recessive phenotype.',
'q² = 1/10 000 = 0.0001.','q = √0.0001 = 0.01, so p = 0.99.','Carrier frequency = 2pq = 2(0.99)(0.01) = 0.0198.','As a percentage, this is 1.98%, not 0.0198%.','The inference depends on the stated model; it is not a personal medical-risk estimate.'),
[g('Under Hardy–Weinberg, q² = 0.25. What is q?','0.50',['0.25','0.125'],'The square root of 0.25 is 0.50.','You are moving from an aa frequency to an allele frequency.'),g('If carrier frequency is 0.42 in N = 500, what is the expected count?','210',['42','21'],'Multiply 0.42 by 500.','Keep frequency and count distinct.')],
[q('Under the model, 9% show the recessive phenotype. What is the carrier frequency?','42%',['9%','30%','49%'],'q = 0.30 and p = 0.70; 2pq = 0.42.'),q('If p = 0.80 is already given, what is the expected AA frequency?','0.64',['0.80','0.20','0.40'],'AA is p² = 0.80² = 0.64.')],
[w('Assume Hardy–Weinberg equilibrium. In N = 400, 64 individuals have the recessive phenotype. Calculate p, q and the expected carrier count.','q² = 64/400 = 0.16, so q = 0.40 and p = 0.60. Carrier frequency is 2(0.60)(0.40) = 0.48, giving 0.48 × 400 = 192 expected carriers. The inference uses the stated equilibrium and phenotype model.'),w('Explain why the dominant phenotype fraction is not generally p.','p counts A allele copies among all allele copies. Under complete dominance, the dominant phenotype includes both AA and Aa individuals. Under Hardy–Weinberg its fraction is p² + 2pq, whereas p is an allele frequency.')],
q('Assume equilibrium with q = 0.20 and N = 250. How many aa individuals are expected?','10',['50','80','200'],'q² = 0.04; 0.04 × 250 = 10.'),
('Should you automatically take a square root whenever q is mentioned?','No. Take it when the given quantity is q² and the model justifies that interpretation.'),
['Identify the observed or supplied quantity','State the equilibrium and phenotype assumptions','Determine p and q','Calculate expected genotype frequencies','Convert frequencies to counts if requested','Check totals and interpret the result']))

L.append(lesson('Using population data to test a prediction','How can the same allele frequencies produce different genotype patterns?',
'Compare observed and expected genotype counts without claiming that one mismatch identifies its cause.',
'Direct counts yield observed allele frequencies. The Hardy–Weinberg model predicts genotype proportions from those frequencies.',[685,688],[14,15,16,17,18,19,20],
[term('observed count','A count actually supplied or measured in the sample.','A sample contains 40 AA, 20 Aa and 40 aa individuals.','Observed and expected values must be kept separate.','An observed count is whatever the formula predicts.'),term('expected genotype distribution','The genotype proportions predicted by the selected model.','For p = q = 0.50, Hardy–Weinberg predicts 0.25 AA, 0.50 Aa and 0.25 aa.','A prediction can be compared with observations rather than substituted for them.','Expected proportions must equal every observed sample exactly.'),term('sampling variation','Differences that arise because a finite sample does not reproduce population proportions perfectly.','Two small samples can show different counts by chance.','A small mismatch is not automatically strong evidence of a specific mechanism.','Every difference between samples proves natural selection.'),term('model comparison','Evaluation of how well observations fit a model’s predictions.','Observed heterozygotes are compared with the expected 2pq fraction.','Agreement does not prove every assumption; mismatch does not identify one cause alone.','A mismatch uniquely identifies mutation as the cause.')],
[sec('Calculate the observed allele pool first','''Suppose a sample has 40 AA, 20 Aa and 40 aa individuals. There are 100 individuals and 200 allele copies. A copies total 80 + 20 = 100, so p = 0.50; q is also 0.50.

These allele frequencies are directly observed from genotype counts. Under Hardy–Weinberg, they predict 25 AA, 50 Aa and 25 aa individuals in a sample of 100. The observed sample contains fewer heterozygotes than that prediction.'''),sec('A genotype mismatch is not a unique explanation','''A shortage of heterozygotes could be associated with non-random mating, population structure or other processes. The counts alone do not uniquely establish which mechanism acted. Sampling and measurement also need consideration.

Notice that the observed sample and the predicted distribution have the same p and q. Genotype proportions can differ while allele frequencies remain the same. Non-random mating can alter genotype proportions without necessarily changing allele frequencies by itself.

Keep two questions separate: do genotype proportions fit the random-mating model, and have allele frequencies changed across generations? They require related but different comparisons.'''),sec('Use consistent sampling and restrained conclusions','''To compare generations, sample the same defined population and locus using comparable methods. A change in p or q supports allele-frequency change at that locus, but a different sampling location or age group can complicate interpretation.

Agreement with a prediction is not proof that every Hardy–Weinberg condition is perfectly satisfied. Opposing effects can sometimes balance, and finite samples have limited resolution. A visible mismatch is a reason to investigate, not permission to name a mechanism without evidence.

These activities use direct comparisons and arithmetic. Formal statistical testing may be useful in research, but no unsupported significance claim is needed here.''')],
worked('Same alleles, different pairing','Population A has 25 AA, 50 Aa and 25 aa individuals. Population B has 50 AA, 0 Aa and 50 aa.',
'Both populations have N = 100 and 200 allele copies.','Both contain 100 A and 100 a copies, so p = q = 0.50.','Population A matches the 1:2:1 genotype prediction for p = q = 0.50.','Population B has the same allele frequencies but no heterozygotes.','Allele totals alone do not establish random genotype pairing.'),
[g('For p = q = 0.50, what fraction of heterozygotes is expected under the model?','0.50',['0.25','1.00'],'2pq = 2 × 0.50 × 0.50 = 0.50.','Use the heterozygote expression.'),g('A genotype mismatch alone tells you what?','The data do not exactly match the selected prediction',['Natural selection is uniquely proven','Mutation must be the only cause'],'More evidence is needed to identify a mechanism.','Separate detection of a mismatch from explaining it.')],
[q('Can two populations have identical p and q but different genotype frequencies?','Yes; alleles can be paired differently among individuals',['No; allele frequencies uniquely determine observed genotypes without assumptions','Only if DNA has no bases','Only if both populations contain one individual'],'Random-mating assumptions connect allele frequencies with expected genotype proportions.'),q('Which comparison most directly evaluates allele-frequency change over time?','p and q from comparable samples of successive generations',['Only the number of organisms','Only adult body size','Only whether the dominant phenotype is visible'],'Microevolution concerns allele proportions across generations.')],
[w('For 36 AA, 48 Aa and 16 aa individuals, find p and q and compare the genotype counts with Hardy–Weinberg expectations.','A copies = 72 + 48 = 120 of 200, so p = 0.60 and q = 0.40. Expected frequencies are 0.36, 0.48 and 0.16, giving 36, 48 and 16 in N = 100. These observations match the prediction, but do not prove every assumption exactly holds.'),w('Explain why a heterozygote deficit does not by itself prove that allele frequencies changed between generations.','A heterozygote deficit describes genotype pairing relative to a model. The same A and a copies can be distributed among more homozygotes without changing their total frequencies. To establish a temporal allele-frequency change, comparable allele estimates from generations are needed.')],
q('One sample is taken from one valley and a later sample from a different valley. Why is an apparent temporal change difficult to interpret?','Sampling different populations can confound the comparison',['Alleles have no frequencies in valleys','Only the second sample contains DNA','Genotype counts cannot ever be compared'],'Geographic population structure can differ from change within one population.'),
('Does an exact model match prove that no evolutionary process operates anywhere in the genome?','No. It concerns the sampled locus and conditions, not every locus or mechanism.')))

L.append(lesson('Natural selection and non-random mating','How do survival and mating success affect inherited variation?',
'Explain selection through differential reproductive success and distinguish it from mate-pairing effects.',
'Allele frequency describes copies in a population. A phenotype can affect survival or reproduction in a particular environment.',[689,692],[21,22,23],
[term('natural selection','Differential reproductive success associated with heritable variation in a particular environment.','A heritable resistance trait improves survival and subsequent reproduction under a specific challenge.','The environment influences which variants contribute more descendants.','Selection gives organisms the exact new mutation they need.'),term('relative fitness','Reproductive contribution compared with other genotypes or phenotypes in the relevant setting.','One genotype leaves more surviving reproductive descendants under the stated conditions.','Fitness is not simply physical strength or long life.','The largest individual must always have the highest fitness.'),term('sexual selection','Selection associated with differences in mating success.','A heritable courtship trait affects the probability of obtaining mates.','A mating advantage can occur even when a trait has survival costs.','A sexually selected trait must always improve survival in every environment.'),term('non-random mating','Mating patterns that depend on characteristics related to the genotype being studied.','Individuals preferentially mate with others having a similar phenotype.','It can alter genotype proportions without automatically changing allele frequencies by itself.','Non-random pairing must always change p and q immediately.')],
[sec('Follow reproduction, not intention','''Individuals vary, and some variation is heritable. If a heritable trait affects survival or reproduction, the associated alleles may be represented differently in the next generation. Natural selection describes that differential reproductive contribution.

The environment matters. A trait advantageous in one setting may have little benefit or a cost elsewhere. Fitness therefore refers to contribution to future generations in context, not simply strength, speed or size.

Selection does not make an organism deliberately produce a needed mutation. Variation must exist or arise independently before its consequences can affect reproductive success.'''),sec('Distinguish survival from mating success','''A trait can increase survival but reduce mating opportunities, or increase mating success while imposing a survival cost. Sexual selection focuses on differences in obtaining mates and reproducing.

For example, a conspicuous display might attract mates while also increasing exposure to predators. The overall evolutionary effect depends on the balance of reproductive consequences, not on whether the display appears efficient to an observer.

A claim that selection occurred needs evidence relating heritable differences to reproductive outcomes. A change in frequency alone can also arise through chance or movement between populations.'''),sec('Pairing patterns and allele totals are different','''Non-random mating changes who pairs with whom. It can change genotype frequencies, such as increasing homozygosity, without directly changing allele frequencies if all alleles retain the same overall reproductive contribution.

Sexual selection and non-random mating are related but not identical statements. When mating success differs, some individuals contribute more offspring. When only pairing patterns differ, allele totals need not immediately change.

Use the information in the case to identify what varies: pairing, survival, number of offspring, or several together.''')],
worked('A mating advantage with a survival cost','A hypothetical heritable display makes males more visible to predators but substantially increases successful mating.',
'The survival effect is a possible cost.','The mating effect is a possible advantage.','Assess overall reproductive contribution rather than judging only survival.','If display-associated variants contribute more descendants, sexual selection can favour them.','The conclusion depends on measured reproductive outcomes in the stated environment.'),
[g('Which measure best reflects evolutionary fitness?','Relative contribution to future generations',['Body mass alone','Age alone'],'Fitness concerns reproductive contribution.','Ask which variants leave descendants.'),g('Does non-random pairing always change allele frequencies by itself?','No',['Yes, by definition in every case','Only because dominant alleles disappear'],'Pairing can change genotype proportions without changing allele totals.','Distinguish distribution among genotypes from total copies.')],
[q('A resistant variant already exists before an antibiotic challenge. Its descendants become more common. Which explanation is appropriate?','Selection favoured existing resistant variation',['The antibiotic intentionally created the needed allele in each cell','All individuals changed their genotype because they needed to','Dominance alone caused the population change'],'Differential survival and reproduction can change representation of existing variants.'),q('Which evidence most strongly distinguishes selection from pure chance in a case?','A repeatable association between a heritable trait and reproductive success',['Only that population size is small','Only that a rare allele exists','Only a single frequency change without trait information'],'Trait-linked reproductive differences support selection.')],
[w('Explain natural selection using variation, heritability and reproductive success.','Individuals differ, some differences are heritable, and those differences can affect how many descendants contribute to later generations. Alleles associated with higher reproductive contribution can increase in frequency in the relevant environment. Selection does not generate directed needed mutations.'),w('Explain why a trait with a survival cost can still be favoured through sexual selection.','If the trait increases mating success enough to increase total reproductive contribution despite a survival cost, associated alleles may become more common. Survival alone is not the complete measure of fitness.')],
q('Individuals mate preferentially with similar genotypes, but all genotypes make equal overall allele contributions. Which immediate effect is possible?','Changed genotype proportions without changed allele frequencies',['Guaranteed loss of every recessive allele','A new allele created at each mating','No possible effect on genotype frequencies'],'Non-random pairing can redistribute existing alleles among genotypes.'),
('Does dominant mean selectively advantageous?','No. Dominance describes the heterozygote phenotype, while advantage depends on reproductive consequences.')))

L.append(lesson('Genetic drift, bottlenecks and founder effects','How can an allele become common without providing an advantage?',
'Distinguish chance sampling from selection and compare bottleneck and founder cases.',
'Finite populations pass on only a sample of existing allele copies in each generation.',[691,694],[24,25,26,27],
[term('genetic drift','Random change in allele frequencies caused by chance sampling in finite populations.','By chance, carriers of one allele leave fewer descendants in a small population.','Drift does not require the allele to affect survival or mating success.','Every frequency increase proves the allele is beneficial.'),term('bottleneck effect','A change in genetic composition associated with a sharp reduction in population size.','A small surviving subset carries only part of the earlier variation.','A demographic recovery does not automatically restore lost alleles.','Returning to the original population size automatically restores every lost allele.'),term('founder effect','A change in allele representation when a small subset establishes a new population.','A few colonists carry frequencies different from the source population by chance.','The original large population need not be destroyed.','Founder effects require the original population to go extinct.'),term('allele fixation','An allele reaching frequency 1 at the locus in the population considered.','Only A remains among sampled reproductive copies.','Fixation describes the locus and population, not the absence of variation everywhere.','Fixation of one allele means every gene in the species is identical.')],
[sec('Chance can change the sample','''Not every individual leaves the same number of descendants. In a finite population, chance differences can change allele frequencies even when the alleles have no effect on survival or reproduction. This is genetic drift.

Drift has a stronger relative effect in small populations because a small number of births, deaths or reproductive events can represent a large fraction of the gene pool. An allele may be lost or become fixed by chance.

A useful distinction is whether the case links reproductive success with a heritable trait. Trait-related differences support selection; random sampling independent of the trait supports drift. Both processes can operate together.'''),sec('A bottleneck samples the original population','''A bottleneck occurs when population size falls sharply. The survivors may carry a smaller and unrepresentative sample of the earlier alleles. If the reduction is random with respect to a studied allele, drift can strongly change that allele’s frequency.

If the population later increases, descendants reproduce the variation that survived. Recovery in numbers does not automatically bring back alleles that were lost. Mutation or gene flow might introduce variation later, but population growth alone does not guarantee restoration.'''),sec('Founders establish a new gene pool','''A founder effect occurs when a small group starts a new population. The founders may carry allele frequencies different from those of the source population simply because they are a small sample.

The source population can remain large and intact. That separates the founder case from a bottleneck that reduces an existing population. Both involve sampling, but the demographic history differs.

Do not infer that a newly common allele must be adaptive. A small island population can have unusual allele frequencies because of its founders even before evidence of local selection is available.''')],
worked('Name the demographic event','Five individuals leave a large population to establish an isolated colony. By chance, they carry an uncommon allele at a high frequency.',
'The original population remains large.','The new population begins from a small sample of its allele pool.','This is a founder effect, a form of genetic drift.','No selective advantage is needed to explain the initial frequency difference.'),
[g('Which population is generally more affected by chance sampling?','A small population',['An infinitely large population','Only populations without DNA'],'Individual reproductive events have larger proportional effects in small populations.','Compare one event with the size of the whole pool.'),g('After a bottleneck, population size recovers. Must every lost allele return?','No',['Yes, because size determines every allele','Yes, because mitosis creates all missing variants'],'Growth copies surviving variation rather than reconstructing all earlier alleles.','Separate demographic recovery from genetic recovery.')],
[q('Which example best fits a bottleneck?','A large population is reduced to a small surviving subset',['A few colonists establish a new population while the original remains large','All individuals mate randomly in an infinite population','An allele increases because it consistently improves mating success'],'A bottleneck is a sharp reduction of an existing population.'),q('An allele becomes common after random deaths unrelated to its phenotype. Which mechanism is supported?','Genetic drift',['Directed mutation','Sexual selection necessarily','Independent assortment alone guarantees it'],'The event samples allele copies by chance rather than trait advantage.')],
[w('Compare founder and bottleneck effects using the history of the populations involved.','A founder effect begins a new population from a small subset while the source may remain intact. A bottleneck reduces an existing population to a small survivor group. Both can change frequencies and reduce variation through chance sampling.'),w('Explain why allele-frequency increase does not alone prove natural selection.','Drift can raise an allele’s frequency by chance, and gene flow can introduce copies. To specifically support selection, evidence should connect heritable variation with differential reproductive success rather than only documenting a frequency change.')],
q('A neutral allele disappears from a small isolated population over generations. What conclusion is supported?','Drift is a plausible explanation without a selective disadvantage',['The allele must have been harmful','The population must have stopped reproducing','All loci must now be fixed'],'Chance sampling can eliminate neutral alleles in finite populations.'),
('Does fixation at one locus prove that every individual is identical across the whole genome?','No. Other loci can still vary.')))

L.append(lesson('Gene flow and mutation','How do alleles enter a population or arise for the first time?',
'Distinguish movement of existing alleles from the creation of new sequence variants.',
'A founder event samples a source population. Continued movement and new mutations can also alter genetic composition.',[694,697],[28,29,30],
[term('gene flow','Transfer of alleles between populations through successful genetic contribution.','Migrants reproduce in another population, introducing allele copies.','Movement without reproduction does not necessarily change the next generation’s gene pool.','Every visit by an individual is automatically inherited gene flow.'),term('mutation input','The introduction of new sequence variants through mutation.','A heritable DNA change creates an allele not previously present at that locus.','Mutation is a source of new alleles; selection acts on their consequences.','All mutations arise because they are needed.'),term('genetic connectivity','The degree to which populations exchange genetic contributions.','Reproductive movement connects two habitat patches.','Physical connection is not the same as demonstrated successful gene flow.','A visible corridor proves every population exchanges alleles equally.'),term('population differentiation','Differences in genetic composition among populations.','Two isolated populations have different allele frequencies.','Gene flow can reduce differences, while isolation can allow them to increase.','All separated populations must immediately have identical frequencies.')],
[sec('Track successful contributions, not movement alone','''Gene flow transfers alleles between populations. It can occur when individuals migrate and reproduce, or when gametes such as pollen move between populations. The important event is a genetic contribution to the recipient population.

An animal passing through a habitat without reproducing does not necessarily alter the next generation’s allele pool. Movement can create an opportunity, but successful reproduction connects that movement with inherited change.'''),sec('Combine copies with the correct weights','''Suppose 80 resident diploid breeders have A frequency 0.25 and 20 immigrant breeders have A frequency 0.75. If all contribute equally, residents supply 160 copies including 40 A; immigrants supply 40 copies including 30 A. The combined frequency is 70/200 = 0.35.

Do not take a simple average of 0.25 and 0.75 when the groups differ in size. Weight each frequency by the number of allele copies contributed. The equal-contribution assumption also matters: different reproductive success would change the weights.

Gene flow can add variation within a population and reduce genetic differences between populations, although the actual effect depends on their starting allele pools and contributions.'''),sec('Mutation supplies new variants','''Mutation changes DNA sequence and can create new alleles. A heritable mutation must enter the reproductive lineage to affect later generations. Many mutations have little effect in a particular setting; others can be harmful or beneficial.

Mutation and selection play different roles. Mutation generates sequence differences without knowing future need. Selection can favour or remove variants according to their reproductive consequences. Drift can also alter their frequencies, especially when a new variant is rare.

Isolation and habitat fragmentation can reduce opportunities for gene flow. A conservation argument about connectivity should therefore look for movement, successful reproduction and genetic evidence rather than assuming that a structure’s presence proves its effect.''')],
worked('Weight two contributing groups','A recipient population has 60 breeders at p = 0.20. Forty immigrants have p = 0.70. Assume equal contribution per diploid breeder.',
'Residents contribute 120 allele copies, including 24 A.','Immigrants contribute 80 copies, including 56 A.','Combined A copies = 80 of 200, so p = 0.40.','The larger resident group receives the larger weight.','The result predicts the combined contribution pool under the equal-contribution assumption.'),
[g('Which event most directly demonstrates gene flow?','A migrant reproduces and contributes alleles',['An animal visits without breeding','A rock moves between habitats'],'Inherited contribution distinguishes gene flow from movement alone.','Follow the alleles into descendants.'),g('What process can create a genuinely new allele sequence?','Mutation',['Only random pairing of unchanged alleles','Counting the same genotypes again'],'Mutation changes the sequence.','Separate new sequences from new combinations.')],
[q('Why can averaging two allele frequencies without group sizes be wrong?','The groups may contribute different numbers of allele copies',['Frequencies can never be averaged in any way','Every immigrant contributes exactly one copy regardless of ploidy','The dominant allele must always receive the larger weight'],'The combination must be weighted by relevant contributions.'),q('Which statement separates mutation from selection?','Mutation creates sequence variants; selection changes their reproductive representation',['Selection always produces the precise needed mutation','Mutation is the same as migration','Every mutation is immediately fixed'],'Origin of variation and differential contribution are distinct mechanisms.')],
[w('Calculate the combined A frequency for 75 equally contributing diploid residents at p = 0.40 and 25 immigrants at p = 0.80.','Residents contribute 150 copies including 60 A. Immigrants contribute 50 copies including 40 A. Combined p = 100/200 = 0.50. This is weighted by group size under equal reproductive contribution.'),w('Explain what evidence would distinguish an opportunity for gene flow from actual gene flow.','A corridor or observed movement demonstrates an opportunity for exchange. Evidence that migrants or their gametes contribute to reproduction, or appropriate genetic evidence in descendants, supports actual gene flow. The claim should match the measured outcome.')],
q('Two populations become genetically more similar after repeated successful interbreeding. Which process is directly implicated?','Gene flow',['Only a bottleneck','Only loss of every mutation','Only independent assortment within one isolated population'],'Alleles are exchanged through reproductive contributions.'),
('Can a new rare mutation be lost even if it is not harmful?','Yes. Chance sampling can eliminate a rare allele.')))

L.append(lesson('Genetic diversity and conservation evidence','Why should population size and genetic variation be measured separately?',
'Use population-genetic mechanisms to evaluate conservation evidence without assuming a universal outcome.',
'Drift, selection, mutation and gene flow can act together. No single measurement describes every aspect of a population.',[695,697],[25,26,27,28,29,30],
[term('genetic diversity','The variety of genetic variants represented in a population or set of populations.','A population contains several alleles at the loci examined.','A larger head count does not guarantee recovery of previously lost variants.','Population size alone precisely measures all genetic diversity.'),term('inbreeding','Mating between genetically related individuals.','Relatives are more likely to share copies inherited from a common ancestor.','It can increase homozygosity without creating harmful alleles on demand.','Inbreeding creates every harmful allele from nothing.'),term('conservation evidence','Observations used to evaluate a population’s condition and response to an action.','Breeding success, survival, connectivity and genetic markers are measured together.','Several measures are needed to distinguish mechanisms and outcomes.','A single attractive photograph proves a population is genetically secure.'),term('adaptive potential','The capacity for heritable variation to support responses to changing conditions.','Standing variation can provide different responses to a new challenge.','Genetic diversity can matter without guaranteeing survival under every change.','A genetically diverse population cannot become extinct.')],
[sec('A head count is only one measurement','''A population can recover numerically after a bottleneck while retaining reduced genetic variation. Descendants multiply surviving allele copies; they do not automatically restore every lost variant. Population size and genetic diversity therefore answer different questions.

Small isolated populations may experience strong drift and increased mating among relatives. Inbreeding can increase homozygosity and expose effects of recessive alleles already present. It does not mean related individuals deliberately create new harmful alleles.'''),sec('Connect a proposed action with its mechanism','''A connection between habitats may permit movement and gene flow. If migrants reproduce, new alleles can enter a population and genetic differentiation may decline. Whether this happens depends on actual movement, survival and reproduction.

A population-management proposal should specify its biological mechanism and the evidence needed to evaluate it. Adding individuals, improving habitat and connecting populations are different interventions with potentially different effects.

The effects can include trade-offs. For example, introduced individuals may carry genetic variants suited to a different environment. An evidence-based evaluation considers both genetic contribution and the ecological setting rather than assuming that every transfer is beneficial.'''),sec('Use cautious conclusions from limited data','''Suppose a hypothetical monitoring report records more animals using a crossing structure and a rise in population size. That supports use of the structure and a demographic change. It does not alone establish increased gene flow or restored diversity at every locus.

Useful additional evidence might include successful breeding between populations, marker diversity, survival and the persistence of changes over generations. Sampling should be comparable across time.

Genetic diversity can support adaptive potential, but it is not a guarantee against extinction. Habitat, environmental change, population size and many other factors also matter.''')],
worked('Evaluate a recovery claim','A population rises from 30 to 300 after a bottleneck. A report calls its original genetic diversity fully restored without genetic measurements.',
'The head count supports numerical recovery.','A bottleneck may have removed alleles that population growth alone cannot recover.','Genetic measurements are needed to assess current diversity relative to earlier or comparison samples.','The report’s genetic conclusion exceeds its demographic evidence.'),
[g('Does population growth alone prove lost alleles returned?','No',['Yes, because every birth recreates the original gene pool','Yes, because diversity is identical to head count'],'Numerical and genetic recovery are different measurements.','Ask what biological process would reintroduce the missing alleles.'),g('What tends to increase with inbreeding at relevant loci?','Homozygosity',['The number of homologous chromosome sets in every cell','A guaranteed new mutation at each locus'],'Related parents more often share allele copies from ancestors.','Think about shared alleles rather than chromosome-number changes.')],
[q('Which measurement most directly supports genetic exchange after habitat reconnection?','Evidence of reproductive contributions between formerly separated populations',['Only the width of the crossing','Only the colour of the vegetation','Only a photograph of one animal near the structure'],'Successful contribution connects movement with gene flow.'),q('Why is genetic diversity not a guarantee of persistence?','Environmental and demographic factors also affect survival',['Variation has no biological relevance','All diverse populations have identical habitats','Mutation stops permanently in diverse populations'],'Several interacting factors determine population outcomes.')],
[w('Explain why a conservation report should distinguish population size, breeding success and genetic diversity.','Size describes abundance, breeding success concerns contribution to future generations, and genetic diversity describes represented variation. A change in one does not guarantee the same change in the others. Together they provide a more informative picture of population condition.'),w('Design a paper-based monitoring comparison for a proposed habitat connection without inventing results.','Compare similar sampling periods before and after connection, measuring movement and successful reproduction as well as genetic markers and population size. Use suitable comparison populations where possible and account for other environmental changes. State that these are proposed measurements, not observed outcomes.')],
q('A population retains many alleles but loses its habitat. Which conclusion is reasonable?','Genetic diversity alone does not remove the habitat threat',['The population cannot decline because it is diverse','Habitat has no effect on allele transmission','Every allele must immediately become advantageous'],'Genetics is one part of the ecological and demographic context.'),
('Does inbreeding require new harmful mutations to produce a problem?','No. Increased homozygosity can expose effects of existing recessive alleles.')))
F=[q('A sample has 20 AA, 40 Aa and 40 aa. What is p?','0.40',['0.20','0.60','0.80'],'A copies = 40 + 40 = 80 of 200.'),q('Under Hardy–Weinberg, q² = 0.04. What is 2pq?','0.32',['0.04','0.20','0.64'],'q = 0.20, p = 0.80 and 2pq = 0.32.'),q('Which statement does not require equilibrium at a two-allele locus?','p + q = 1',['Observed AA must equal p²','Observed Aa must equal 2pq','A recessive phenotype fraction always uniquely determines q'],'The allele categories sum to 1 by definition.'),q('A random small survivor group follows a major population reduction. Which mechanism is highlighted?','Bottleneck-associated drift',['Directed mutation','Mate choice necessarily','Gene flow without any movement'],'A bottleneck samples the earlier gene pool.'),q('What distinguishes gene flow from movement alone?','Successful genetic contribution to another population',['Only distance travelled','Only a change in body mass','Only temporary presence in a habitat'],'Alleles must enter the recipient reproductive pool.'),q('A genotype pattern differs from Hardy–Weinberg predictions. What conclusion is justified?','The model’s fit or assumptions need investigation',['Natural selection is uniquely proven','Every locus in the species is evolving identically','No useful allele frequency can be calculated from genotype counts'],'A mismatch does not uniquely identify its cause.')]
FW=[w('Compare direct allele counting with inferring frequencies from a recessive phenotype under Hardy–Weinberg.','Known genotype counts allow direct summing of two copies per homozygote and one of each per heterozygote over 2N. A recessive phenotype count identifies aa but does not reveal the split between AA and Aa. Inferring q by √q² then requires the stated equilibrium and phenotype assumptions.'),w('Explain how selection, drift and gene flow could each change an allele frequency, and identify evidence useful for distinguishing them.','Selection involves heritable differences associated with reproductive success. Drift involves chance sampling, often strong in small populations. Gene flow transfers alleles through successful contributions between populations. Trait-linked reproductive data, demographic history and migration/breeding evidence help distinguish the mechanisms.')]
TR=[q('A sample contains 12 AA, 36 Aa and 12 aa. What is q?','0.50',['0.20','0.30','0.60'],'a copies = 36 + 24 = 60 of 120.'),q('Assume equilibrium. In 500 individuals, 20 show a recessive phenotype. How many carriers are expected?','160',['20','100','320'],'q² = 0.04, q = 0.20, p = 0.80 and 2pqN = 0.32 × 500 = 160.'),q('A small founder group carries a neutral allele at unusually high frequency. What is the appropriate initial explanation?','Chance sampling can explain the difference without a selective advantage',['The allele must be beneficial in every habitat','The original population must have gone extinct','The founders necessarily created a new allele'],'A founder effect can change representation by chance.')]
TW=w('Two samples both have p = q = 0.50, but only one has 25% AA, 50% Aa and 25% aa. Explain what is and is not established.','Both samples share allele frequencies. The 1:2:1 sample matches the Hardy–Weinberg genotype prediction for those values, while the other has a different pairing pattern. This alone does not prove temporal allele change or identify a unique cause of the genotype mismatch, nor does a match prove all assumptions perfectly hold.')
EX={'title':'Biotechnology and gene pools','question':'How could a new trait spread, and what evidence would track it?','sections':[sec('A hypothetical trait enters a breeding population','''A hypothetical crop line carries an introduced allele. Nearby compatible plants can potentially receive pollen, but no offspring genotypes have yet been measured.

Pollen movement creates an opportunity for gene flow. Establishing inherited spread requires evidence that the pollen contributed to viable offspring and that the allele persists in the recipient population.'''),sec('Separate movement, inheritance and consequences','''A marker can track allele presence while reproductive data evaluate contribution. Frequency change over generations can be measured separately from the allele’s ecological effects.

This paper-based case does not assume that movement is always beneficial or always harmful. It asks what observations would support each specific biological claim.''')],'writing':w('Identify the observations needed to distinguish pollen movement, gene flow and an ecological effect.','Pollen detection supports movement. Genotypes in viable recipient offspring support successful genetic contribution. Repeated sampling can track frequency change, while separate measurements of survival, reproduction or ecological interactions assess consequences. One observation should not be substituted for all three claims.')}
save(19,'Genetic Diversity in Populations',676,701,L,{'mc':F,'writing':FW},{'mc':TR,'writing':TW},EX,['Calculate allele and genotype frequencies with the correct denominators.','Use Hardy–Weinberg as an explicit reference model rather than an automatic assumption.','Distinguish selection, drift, gene flow and mutation.','Evaluate genetic and demographic evidence in population cases.'],
{'question':'Can you distinguish a counted frequency, a model prediction and a causal explanation?','goal':'Integrate allele arithmetic, model assumptions and mechanisms of population change.','prior':'Identify the population, locus, denominator and assumptions before calculating.','pages':[699,701],'anchors':['allele frequency','genotype frequency','Hardy–Weinberg equilibrium','genetic drift'],'sections':[sec('Use the right method for the information','''Genotype counts permit direct allele counting over 2N. Recessive phenotype information alone leaves some genotypes unknown, so a Hardy–Weinberg inference needs explicit assumptions. Expected genotype frequencies are p², 2pq and q² only within the model.

Keep frequencies distinct from counts. Multiply by population size only when an expected number is requested, and check that the complete categories total 1 or N as appropriate.'''),sec('Interpret change without choosing a cause too soon','''Selection links heritable variation with reproductive contribution; drift reflects chance; gene flow moves existing alleles between populations; mutation creates sequence variants. Non-random pairing can change genotype proportions without necessarily changing allele totals by itself.

A good population explanation uses the given evidence to distinguish these mechanisms. A small sample, an unexplained phenotype change or numerical recovery alone supports less than a complete claim about evolution or genetic diversity.''')],'worked':worked('Compare counts across population growth','Generation one has 16 aa individuals of 100 and generation two has 64 aa of 400. Assume the same complete-dominance Hardy–Weinberg model for both.','The aa fractions are both 0.16.','Under the stated model, q = 0.40 and p = 0.60 in both generations.','Counts increased while inferred allele frequencies stayed equal.','This supports no detected change at the studied locus under the assumptions.','Without those assumptions, the recessive fractions alone would not determine every allele frequency.')})
