(function () {
'use strict';
const D=window.S24_DATA, S=window.S24Storage, clone=S.copy;
D.banks['mixed-practice']=[...D.banks['multiple-choice'],...D.banks['fill-in-the-blanks']];
D.banks['unit-final-prep']=[...D.banks['multiple-choice'],...D.banks['fill-in-the-blanks']];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));
const now=()=>new Date().toISOString(), norm=v=>String(v).toLowerCase().trim().replace(/[‐‑–—-]/g,' ').replace(/[.,!?;:]+$/,'').replace(/\s+/g,' ');
const store=new S.BrowserStore(D.courseId);
const previousStore=new S.BrowserStore('science24-unit-c-review-v1');
let previousDraft=null,previousDraftError=null;
let state=S.empty(),confirmed={revision:0,payload:S.empty()},dirtyVersion=0,savedVersion=0,saveTimer,queue=Promise.resolve(),conflict=null,loadFailure=null;
let selectedWord=D.vocabulary[0].id,bookId=D.bookQuestions[0].id,readingPage=D.resources[0].pages[0].printed,activeRoute='overview',resetKey=null;
let selectedLabel=D.labeling[0].id;
const setups={},openers=new WeakMap(),scrollPositions=new Map();
const topicLabel=id=>D.topics.find(t=>t.id===id)?.label||'All topics';
const runFor=id=>state.runs[id];
function status(text){$('#save-status').textContent=text;}
function mark(){dirtyVersion++;status('Changes pending · This browser only; nothing is submitted automatically.');clearTimeout(saveTimer);saveTimer=setTimeout(flush,350);}
function reportFailure(error){
 if(error.name==='SaveConflict')conflict={remote:clone(error.remote),lastConfirmed:clone(confirmed)};
 const text=error.name==='SecurityError'?'This browser is blocking local course storage. Your work can remain on screen, but it will not survive closing this page. Print your work before leaving; use a browser that allows local storage for this file.':error.name==='QuotaExceededError'?'Browser storage is full. Your complete draft remains on screen and the last confirmed save is unchanged. Print your work before leaving.':error.message||'Saving failed. Your visible draft and last confirmed save are preserved.';
 $('#save-alert-message').textContent=text;$('#save-alert').hidden=false;$('#view-recovery').hidden=!conflict;$('#retry-save').hidden=!!conflict;
 status('Not saved · '+text);
}
function flush(){
 clearTimeout(saveTimer);
 queue=queue.then(async()=>{
  if(loadFailure){reportFailure(loadFailure);return false;}
  if(savedVersion===dirtyVersion)return true;
  if(conflict){reportFailure(new S.SaveConflict(conflict.remote));return false;}
  if(loadFailure){reportFailure(loadFailure);return false;}
  const version=dirtyVersion,snapshot=clone(state);
  try{const result=await store.save(snapshot,confirmed.revision);confirmed=result;savedVersion=version;$('#save-alert').hidden=true;status('Saved in this browser only · Print or save your work as PDF before changing devices.');updateProgress();return true;}
  catch(error){reportFailure(error);return false;}
 }).catch(e=>{reportFailure(e);return false;});
 return queue;
}
async function retryStorage(){
 if(loadFailure){
  try{await store.open();const remote=await store.load();loadFailure=null;
   if(remote.revision>confirmed.revision&&dirtyVersion!==savedVersion){reportFailure(new S.SaveConflict(remote));return false;}
   if(dirtyVersion===savedVersion){confirmed=remote;state=clone(remote.payload);renderAll();}
   else confirmed=remote;
  }catch(error){loadFailure=error;reportFailure(error);return false;}
 }
 const ok=await flush();if(ok){$('#save-alert').hidden=true;status('Saved in this browser only · Print your work before changing devices.');renderAll();}return ok;
}
function feedback(message,ok=false){return '<div class="feedback"'+(ok?'':' data-result="retry"')+' role="status">'+esc(message)+'</div>';}
function showDialog(dialog,opener){if(opener)openers.set(dialog,opener);if(!dialog.open)dialog.showModal();}
$$('dialog').forEach(d=>{
 d.addEventListener('close',()=>{const opener=openers.get(d);if(opener?.isConnected)opener.focus({preventScroll:true});});
 d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=$$('a[href],button:not([disabled]),select:not([disabled]),textarea:not([disabled]),input:not([disabled])',d).filter(el=>el.getClientRects().length);if(!items.length){e.preventDefault();return;}const first=items[0],last=items.at(-1);if((e.shiftKey&&document.activeElement===first)||(!e.shiftKey&&document.activeElement===last)){e.preventDefault();(e.shiftKey?last:first).focus();}});
});
function newRun(kind,title,questions,key){
 const seed=Math.floor(Math.random()*4294967295)>>>0;
 let n=seed||1;const rng=()=>{n^=n<<13;n^=n>>>17;n^=n<<5;return(n>>>0)/4294967296;};
 const shuffle=items=>{const a=clone(items);for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 return{id:uid(kind),kind,title,key,contentVersion:D.contentVersion,seed,startedAt:now(),questions:questions.map(q=>({...clone(q),...(q.options?{options:shuffle(q.options)}:{})})),answers:{},attempts:{},writing:{},revealed:{},position:0};
}
function lastAttempt(run,id){return(run.attempts[id]||[]).at(-1);}
function checkedCurrent(run,id){const e=lastAttempt(run,id);return !!e&&String(e.value)===String(run.answers[id]);}
function answeredCorrectly(run,q){return checkedCurrent(run,q.id)&&lastAttempt(run,q.id).correct===true;}
function coefficients(value){return String(value??'').trim().split(/[\s,;]+/).map(Number);}
function match(q,value){if(q.kind==='mc')return value===q.answer;if(q.kind==='number')return Math.abs(Number(value)-q.answer)<=(q.tolerance??0.0005);if(q.kind==='equation'){const a=coefficients(value);return a.length===q.answer.length&&a.every((n,i)=>n===q.answer[i]);}return(q.answers||[]).some(a=>norm(a)===norm(value));}
function validAnswer(q,value){const v=String(value??'').trim();if(!v)return false;if(q.kind==='mc')return q.options.some(o=>o.id===value);if(q.kind==='number')return /^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(v)&&Number.isFinite(Number(v));if(q.kind==='equation'){const a=coefficients(v);return a.length===q.answer.length&&a.every(n=>Number.isInteger(n)&&n>0);}return true;}
function invalidMessage(q){return q.kind==='equation'?'Enter one positive whole-number coefficient for each formula, in order, separated by commas. Include 1.':q.kind==='number'?'Enter a number using a decimal point. Put only the number in the answer field.':'Enter or choose an answer before checking.';}
function answerText(q,value){return q.options?.find(o=>o.id===value)?.text??String(value??'No response');}
function hintFor(q,run){const list=run.attempts[q.id]||[],last=list.at(-1);if(!last||!checkedCurrent(run,q.id))return'';if(last.correct)return feedback('Correct. '+q.explanation,true);return feedback(list.length===1?q.hint:'Compare: '+q.explanation);}
function choiceHTML(q,name,selected,attr){return '<fieldset><legend class="sr-only">Choose one answer</legend>'+q.options.map(o=>'<label class="choice-row"><input type="radio" name="'+esc(name)+'" value="'+esc(o.id)+'" '+attr+' '+(selected===o.id?'checked':'')+'><span>'+esc(o.text)+'</span></label>').join('')+'</fieldset>';}
function updateProgress(){
 const completed=new Set(confirmed.payload.history.filter(r=>r.kind==='required').map(r=>r.key));const count=Object.keys(D.checks).filter(k=>completed.has(k)).length,total=Object.keys(D.checks).length;
 $('[data-progress-count]').textContent=count+' of '+total+' checks';$('[data-progress-percent]').textContent=Math.round(count/total*100)+'%';$('[data-progress-fill]').style.width=count/total*100+'%';$('[data-progress-fraction]').textContent=count+' / '+total;
 $$('[data-check-status]').forEach(el=>el.textContent=completed.has(el.dataset.checkStatus)?'Required check completed':'Check not completed');
 const next=Object.values(D.checks).find(c=>!completed.has(c.id));$('#begin-route').href='#'+(next?.route||'process-collection');$('#begin-route').textContent=count?'Continue your learning':'Begin the lesson';
}
function renderRequired(container){
 const id=container.dataset.required,c=D.checks[id],r=runFor(id),past=state.history.filter(h=>h.key===id);
 if(!r){container.innerHTML='<h2>'+esc(c.title)+'</h2><p>'+c.questions.length+' selected responses and '+c.writing.length+' written explanations. Correct selections unlock writing. Written explanations are not automatically graded.</p><p class="small">Elapsed time is recorded from Start, including time away. It is not a speed grade. Completed earlier runs are preserved.</p>'+ (past.length?'<p class="status-label">'+past.length+' completed run(s) in All My Work.</p>':'')+'<button type="button" data-start-required="'+id+'">'+(past.length?'Redo check':'Start')+'</button>';return;}
 const unlocked=r.questions.every(q=>answeredCorrectly(r,q));
 container.innerHTML='<h2>'+esc(c.title)+'</h2><p class="timer" data-timer="'+esc(id)+'"></p>'+r.questions.map((q,i)=>'<section class="check-question" data-qid="'+q.id+'"><h3>'+(i+1)+'. '+esc(q.prompt)+'</h3>'+choiceHTML(q,r.id+'-'+q.id,r.answers[q.id],'data-required-answer="'+q.id+'"')+'<button type="button" data-check-required="'+q.id+'">Check answer</button>'+hintFor(q,r)+'<p class="inline-error" role="status"></p></section>').join('')+
 (unlocked?'<div class="required-writing"><h3>Explain your reasoning</h3><p>Drafts save in this browser. Save each written response explicitly, then finish the whole check. Writing is not automatically graded.</p>'+c.writing.map((w,i)=>{const a=r.writing[w.id]||{};return'<div class="writing-prompt"><label class="field-label" for="'+w.id+'">'+(i+1)+'. '+esc(w.prompt)+'</label><textarea id="'+w.id+'" data-required-writing="'+w.id+'" rows="5">'+esc(a.text||'')+'</textarea><div class="actions"><button type="button" data-save-writing="'+w.id+'">Save written response</button><span data-writing-status="'+w.id+'">'+(a.saved?'Saved written response':'Draft / not yet saved explicitly')+'</span></div></div>';}).join('')+'</div>':'<p class="overview-callout">Correct '+(c.questions.length>2?'all '+c.questions.length+' selections':'both selections')+' to open the written explanations.</p>')+
 '<div class="actions"><button type="button" data-finish-required="'+id+'" '+(!unlocked||!c.writing.every(w=>r.writing[w.id]?.saved)?'disabled':'')+'>Submit and finish</button><button type="button" class="button secondary" data-reset-run="'+id+'">Stop and reset</button></div><p class="run-status" role="status"></p>';
}
async function startRequired(id){if(state.runs[id])return;state.runs[id]=newRun('required',D.checks[id].title,D.checks[id].questions,id);mark();renderRequired($('[data-required="'+id+'"]'));await flush();}
async function checkRequired(btn){
 const box=btn.closest('[data-required]'),r=runFor(box.dataset.required),q=r.questions.find(x=>x.id===btn.dataset.checkRequired),value=r.answers[q.id];
 if(!validAnswer(q,value)){$('.inline-error',btn.closest('.check-question')).textContent='Choose an answer before checking.';return;}
 (r.attempts[q.id]??=[]).push({value,correct:match(q,value),at:now()});mark();renderRequired(box);await flush();
}
async function saveWriting(btn){
 const box=btn.closest('[data-required]'),r=runFor(box.dataset.required),id=btn.dataset.saveWriting,w=r.writing[id]||{text:'',saved:false,versions:[]};
 if(!w.text.trim()){$('[data-writing-status="'+id+'"]',box).textContent='Write an explanation before saving.';return;}
 w.versions??=[];w.versions.push({text:w.text,at:now()});w.saved=true;r.writing[id]=w;mark();const ok=await flush();
 const label=$('[data-writing-status="'+id+'"]',box);if(label)label.textContent=ok?'Saved written response':'Not saved to browser. Full text retained on screen.';
 const finish=$('[data-finish-required]',box);if(finish)finish.disabled=!ok||savedVersion!==dirtyVersion||!r.questions.every(q=>answeredCorrectly(r,q))||!D.checks[box.dataset.required].writing.every(item=>r.writing[item.id]?.saved);
}
async function finishRequired(id){const r=runFor(id),c=D.checks[id];if(!r||!r.questions.every(q=>answeredCorrectly(r,q))||!c.writing.every(w=>r.writing[w.id]?.saved))return;const before=clone(state),complete=clone(r);complete.endedAt=now();complete.writingPrompts=clone(c.writing);state.history.push(complete);delete state.runs[id];mark();const ok=await flush();if(!ok){state=before;renderRequired($('[data-required="'+id+'"]'));const status=$('.run-status',$('[data-required="'+id+'"]'));if(status)status.textContent='Completion was not saved. Your active check and written work are still here; resolve the save problem, then submit again.';renderWork();return;}renderRequired($('[data-required="'+id+'"]'));renderWork();}
function available(mode,s){return D.banks[mode].filter(q=>(s.topic==='all'||q.topic===s.topic)&&(s.difficulty==='Mixed'||q.difficulty===s.difficulty));}
function setup(mode){return setups[mode]??=( {topic:'all',difficulty:'Mixed',size:mode==='unit-final-prep'?15:5} );}
function renderPractice(box){
 const mode=box.dataset.practiceMode,r=runFor(mode),s=setup(mode);
 if(!r){const n=available(mode,s).length,history=state.history.filter(h=>h.key===mode);box.innerHTML='<div class="practice-setup"><label>Topic<select data-setup-topic><option value="all">All topics</option>'+D.topics.map(t=>'<option value="'+t.id+'" '+(s.topic===t.id?'selected':'')+'>'+esc(t.label)+'</option>').join('')+'</select></label><label>Difficulty<select data-setup-difficulty>'+['Mixed','Foundation','Application'].map(x=>'<option '+(s.difficulty===x?'selected':'')+'>'+x+'</option>').join('')+'</select></label><label>Set size<select data-setup-size>'+(mode==='unit-final-prep'?[15,30,50]:[5,10,15,20]).map(n=>'<option value="'+n+'" '+(s.size===n?'selected':'')+'>'+n+' questions</option>').join('')+'</select></label><div class="setup-action"><button type="button" data-start-practice '+(!n?'disabled':'')+'>Start practice</button></div></div><p class="small" data-bank-count>'+n+' unique item(s) available.'+(n<s.size?' Your set will contain '+n+', not '+s.size+'; no duplicates are added.':'')+'</p><p class="small">Finite authored bank. Once started, the set and option order are saved and remain stable.</p>'+ (history.length?summaryHTML(history.at(-1)):'');return;}
 const q=r.questions[r.position],events=r.attempts[q.id]||[],seen=checkedCurrent(r,q.id),canAdvance=q.kind==='flash'?events.length>0:seen&&(events.at(-1).correct||events.length>=2);
 let input;
 if(q.kind==='mc')input=choiceHTML(q,r.id+'-'+q.id,r.answers[q.id],'data-practice-input');
 else if(q.kind==='flash')input='<button type="button" class="button secondary" data-reveal-card>'+ (r.revealed[q.id]?'Hide comparison':'Turn card')+'</button>'+(r.revealed[q.id]?'<div class="practice-feedback">'+esc(q.answer)+'</div><div class="actions"><button type="button" data-rate-card="recalled">I recalled it</button><button type="button" class="button secondary" data-rate-card="repair">Needs more practice</button></div><p class="small">This is your self-assessment, not an automatically verified result.</p>':'');
 else input='<label class="field-label" for="'+mode+'-answer">'+(q.kind==='number'?'Your answer ('+q.unit+')':q.kind==='equation'?'Coefficients, in order (include 1)':'Your answer')+'</label><input id="'+mode+'-answer" type="text" '+(q.kind==='number'?'inputmode="decimal"':'')+' data-practice-input value="'+esc(r.answers[q.id]||'')+'">';
 box.innerHTML='<div class="practice-run-bar"><span>Question '+(r.position+1)+' of '+r.questions.length+'</span><span class="timer" data-timer="'+mode+'"></span></div><section class="practice-question"><p class="eyebrow">'+esc(topicLabel(q.topic))+'</p><h3>'+esc(q.prompt)+'</h3>'+input+(q.kind!=='flash'?'<button type="button" data-practice-check>Check answer</button>'+hintFor(q,r):events.length?'<p class="status-label">Self-assessment recorded: '+(events.at(-1).value==='recalled'?'recalled':'needs practice')+'.</p>':'')+'<p class="inline-error" role="status"></p></section><div class="practice-navigation"><button type="button" class="button secondary" data-practice-prev '+(r.position===0?'disabled':'')+'>Previous</button><button type="button" data-practice-next '+(!canAdvance?'disabled':'')+'>'+(r.position===r.questions.length-1?'Finish set':'Next question')+'</button></div><div class="actions"><button type="button" class="button secondary" data-reset-run="'+mode+'">Stop and reset</button></div>';
}
function sample(items,count){const a=clone(items);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,count);}
async function startPractice(box){const mode=box.dataset.practiceMode,s=setup(mode),pool=available(mode,s);if(!pool.length||runFor(mode))return;const title={practice:'Flash cards','fill-in-the-blanks':'Fill in the blanks','multiple-choice':'Multiple choice','mixed-practice':'Mixed practice','unit-final-prep':'Unit Final Prep'}[mode];state.runs[mode]=newRun('practice',title,sample(pool,Math.min(s.size,pool.length)),mode);state.runs[mode].selection=clone(s);mark();renderPractice(box);await flush();}
async function checkPractice(box){const r=runFor(box.dataset.practiceMode),q=r.questions[r.position],value=r.answers[q.id];if(!validAnswer(q,value)){$('.inline-error',box).textContent=invalidMessage(q);return;}(r.attempts[q.id]??=[]).push({value,correct:match(q,value),at:now()});mark();renderPractice(box);await flush();}
async function nextPractice(box){const mode=box.dataset.practiceMode,r=runFor(mode);if(r.position<r.questions.length-1){r.position++;mark();renderPractice(box);await flush();}else{const done=clone(r);done.endedAt=now();state.history.push(done);delete state.runs[mode];mark();await flush();renderPractice(box);renderWork();}}
function summaryHTML(r){const qs=r.questions||[],first=qs.filter(q=>r.attempts[q.id]?.[0]?.correct===true).length,flash=qs.every(q=>q.kind==='flash');return'<div class="practice-feedback"><h3>Most recent completed set</h3><p>'+esc(r.title)+' · '+qs.length+' items. '+(flash?'Flash-card results are self-assessments.':first+' correct on the first checked attempt.')+'</p><p>Review the prompts and your attempts in All My Work. Optional practice does not affect required progress.</p><a class="text-link" href="#process-collection">Open All My Work</a>'+(missedQuestions(r).length?'<div class="actions"><button type="button" data-retry-concepts="'+r.key+'">Retry concepts to study ('+missedQuestions(r).length+')</button></div>':'')+'</div>';}
function persistedRun(r){return confirmed.payload.history.some(h=>h.id===r.id);}
function missedQuestions(r){return (r.questions||[]).filter(q=>{const a=r.attempts[q.id]?.[0];return q.kind==='flash'?a?.value==='repair':a?.correct!==true;});}
async function retryConcepts(mode){if(runFor(mode))return;const last=state.history.filter(r=>r.key===mode).at(-1);if(!last)return;const items=missedQuestions(last);if(!items.length)return;const r=newRun('practice',last.title+' — targeted retry',items,mode);r.retryOf=last.id;r.selection={topic:'retry',difficulty:'Mixed',size:items.length};state.runs[mode]=r;mark();renderPractice($('[data-practice-mode="'+mode+'"]'));await flush();}
function termRecord(id){return D.vocabulary.find(v=>v.id===id);}
function frayerHTML(id,where){const f=state.frayers[id];if(!f)return'<div class="frayer-section"><h3>Make this word your own</h3><p>Choose up to eight words. Your four response fields start empty.</p><button type="button" data-choose-word="'+id+'">Choose this word</button></div>';return'<section class="frayer-section" data-vword="'+id+'"><h3>Your Frayer work</h3><p>Use your own words. Each field allows 240 characters; writing is not automatically graded.</p><div class="frayer-fields">'+[['meaning','Meaning'],['features','Features'],['example','Example'],['nonexample','Non-example']].map(([key,label])=>'<label for="'+where+'-'+id+'-'+key+'">'+label+'<textarea id="'+where+'-'+id+'-'+key+'" data-frayer-field="'+key+'" rows="3">'+esc(f.fields[key]||'')+'</textarea><small data-field-count="'+key+'">'+(f.fields[key]||'').length+' / 240 characters</small></label>').join('')+'</div><div class="actions"><button type="button" data-collect-word="'+id+'">Collect this word</button><button type="button" class="button secondary" data-frayer-model="'+id+'" '+(f.status==='collected'?'':'disabled')+'>Compare course model</button></div><p data-frayer-status role="status">'+(f.status==='collected'?'Collected. A saved version is in All My Work.':'Draft. Complete your four responses, then collect this word.')+'</p><div data-frayer-comparison hidden></div></section>';}
function wordHTML(id,where){const t=termRecord(id);return'<article data-biology-word-view="'+id+'"><div data-biology-word-details="'+id+'"><p class="eyebrow">'+esc(topicLabel(t.topic))+'</p><h2 tabindex="-1">'+esc(t.term)+'</h2><section><h3 class="section-label">Meaning</h3><p class="term-meaning">'+esc(t.meaning)+'</p></section><section><h3 class="section-label">Example</h3><p>'+esc(t.example)+'</p></section><section class="common-confusion"><h3>Important distinction</h3><p>'+esc(t.distinction)+'</p></section></div>'+frayerHTML(id,where)+'</article>';}
function renderIndex(){const search=norm($('#vocab-search').value),topic=$('#vocab-topic').value,terms=D.vocabulary.filter(t=>(topic==='all'||t.topic===topic)&&norm(t.term+' '+t.meaning).includes(search));$('#vocab-count').textContent=terms.length+' matching term'+(terms.length===1?'':'s');$('#vocab-index').innerHTML=D.topics.map(group=>{const list=terms.filter(t=>t.topic===group.id);return list.length?'<section class="word-category"><h2>'+esc(group.label)+'</h2>'+list.map(t=>'<button type="button" class="text-link" data-select-word="'+t.id+'" aria-pressed="'+(t.id===selectedWord)+'"><span>'+esc(t.term)+'</span><small>'+esc(state.frayers[t.id]?.status==='collected'?'Collected':state.frayers[t.id]?'Draft':'Reference available')+'</small></button>').join('')+'</section>':'';}).join('')||'<p>No matching terms. Try a different search.</p>';$('#frayer-count').textContent=Object.values(state.frayers).filter(f=>f.status==='collected').length+' of 8 collected · '+Object.keys(state.frayers).length+' selected.';}
function renderWords(){renderIndex();$('#vocab-detail').innerHTML=wordHTML(selectedWord,'core');$('#drawer-detail').innerHTML=wordHTML(selectedWord,'drawer');$('#drawer-word').innerHTML=D.vocabulary.map(v=>'<option value="'+v.id+'" '+(v.id===selectedWord?'selected':'')+'>'+esc(v.term)+'</option>').join('');}
function openWord(id,btn){if(!termRecord(id))return;selectedWord=id;renderWords();showDialog($('#vocab-dialog'),btn);}
async function chooseWord(id){if(state.frayers[id])return;if(Object.keys(state.frayers).length>=8){alert('Eight words are already selected. Your existing work has not been changed.');return;}state.frayers[id]={fields:{meaning:'',features:'',example:'',nonexample:''},status:'draft',versions:[]};mark();renderWords();await flush();}
async function collectWord(id,btn){const f=state.frayers[id],container=btn.closest('[data-vword]');if(!['meaning','features','example','nonexample'].every(k=>f.fields[k]?.trim())){$('[data-frayer-status]',container).textContent='Complete all four fields before collecting.';return;}if(Object.values(f.fields).some(s=>s.length>240)){$('[data-frayer-status]',container).textContent='A field exceeds 240 characters. The complete text remains visible; shorten it before collecting.';await flush();return;}f.versions.push({fields:clone(f.fields),at:now()});f.status='collected';mark();const ok=await flush();renderWords();renderWork();if(!ok)$$('[data-frayer-status]').forEach(x=>x.textContent='Collection is pending: browser save failed; text retained.');}
function updateNotes(){ $$('[data-note-id]').forEach(box=>{const id=box.dataset.noteId,n=state.notes[id];$('[data-note-text]',box).value=n?.text||'';$('[data-note-status]',box).textContent=n?.status==='saved'?'Saved response. Earlier saved versions remain in All My Work.':n?.text?'Draft. Select Save response to record a version.':'Not started. Drafts save in this browser.';$('[data-note-model]',box).disabled=n?.status!=='saved';});}
async function saveNote(box){const id=box.dataset.noteId,n=state.notes[id]||{text:'',versions:[],status:'draft'};if(!n.text.trim()){$('[data-note-status]',box).textContent='Write your response before saving.';return;}n.versions.push({text:n.text,at:now()});n.status='saved';state.notes[id]=n;mark();const ok=await flush();updateNotes();renderWork();if(!ok)$('[data-note-status]',box).textContent='Not saved to browser. Your full response is retained on screen.';}
function currentBookList(){const topic=$('#book-topic')?.value||'all';return D.bookQuestions.filter(q=>topic==='all'||q.topic===topic);}
function renderBook(){const list=currentBookList();if(!list.length)return;if(!list.some(q=>q.id===bookId))bookId=list[0].id;
 const groups=[];for(const q of list){let group=groups.find(item=>item.page===q.printedPage);if(!group){group={page:q.printedPage,items:[]};groups.push(group);}group.items.push(q);}
 $('#book-tiles').innerHTML='<p class="book-list-intro">Choose an original question · '+list.length+' question'+(list.length===1?'':'s')+'</p>'+groups.map(group=>'<section class="book-page-group"><h3>Printed p. '+group.page+'</h3><div class="book-question-tiles">'+group.items.map(q=>'<button type="button" data-book-select="'+q.id+'" aria-pressed="'+(q.id===bookId)+'"><strong>Q'+esc(q.questionNumber)+'</strong><span>'+esc(q.group)+'</span><small>'+esc(state.book[q.id]?.status==='saved'?'Saved':state.book[q.id]?.text?'Draft':'Not started')+'</small></button>').join('')+'</div></section>').join('');
 const q=list.find(q=>q.id===bookId),i=list.indexOf(q),rec=state.book[q.id],unit=((D.courseId.match(/unit-([a-d])/i)||[])[1]||'').toUpperCase();
 $('#book-workspace').innerHTML='<div data-book-id="'+q.id+'"><div class="book-heading"><div><p class="eyebrow">'+esc(q.group)+' · printed p. '+q.printedPage+'</p><h2>Question '+esc(q.questionNumber)+'</h2><p class="small">Question '+(i+1)+' of '+list.length+' · '+esc(topicLabel(q.topic))+' · optional and ungraded</p></div><div class="actions"><button type="button" class="button secondary" data-book-prev '+(i===0?'disabled':'')+'>Previous question</button><button type="button" class="button secondary" data-book-next '+(i===list.length-1?'disabled':'')+'>Next question</button></div></div><div class="book-source"><div class="book-source-intro"><p>Read this captured question, including every lettered part. Use the full textbook page when the prompt refers to a diagram, table or surrounding explanation.</p><div class="actions"><button type="button" class="button secondary" data-enlarge-question="'+q.id+'">Enlarge question</button><button type="button" class="text-link" data-open-reading="'+q.printedPage+'">View full textbook page</button></div></div><figure><img class="book-crop" src="'+q.image+'" alt="Original Unit '+esc(unit)+' textbook question '+esc(q.questionNumber)+' from printed page '+q.printedPage+'"><figcaption>Question '+esc(q.questionNumber)+' from printed p. '+q.printedPage+'. The full page remains available for context.</figcaption></figure><details><summary>Read the question text</summary><div class="written-response">'+esc(q.originalText)+'</div></details></div><label class="field-label" for="book-answer">Your response to question '+esc(q.questionNumber)+' (include every lettered part)</label><textarea id="book-answer" data-book-text rows="7">'+esc(rec?.text||'')+'</textarea><p class="small">Drafts save in this browser. Save this response when it is ready; this does not grade it. Paper work is not stored here.</p><button type="button" data-book-save>Save response</button><p data-book-status role="status">'+(rec?.status==='saved'?'Saved. Editing returns this to draft until you save again.':rec?.text?'Draft restored. Save response to keep a version.':'Not started.')+'</p></div>';
}
async function saveBook(){const r=state.book[bookId]||{text:'',status:'draft',versions:[]};if(!r.text.trim()){$('[data-book-status]').textContent='Write your method or explanation before saving.';return;}r.versions.push({text:r.text,at:now()});r.status='saved';state.book[bookId]=r;mark();const ok=await flush();renderBook();renderWork();if(!ok)$('[data-book-status]').textContent='Not saved to browser; full text retained on screen.';}
function currentLabel(){return runFor('labeling-practice')?.activity||D.labeling.find(a=>a.id===selectedLabel)||D.labeling[0];}
function numberDiagram(a){return'<img src="'+a.image+'" alt="'+esc(a.visualDescription||a.title)+'. Letter markers have fixed targets.">';}
function renderLabeling(){const box=$('[data-labeling]'),a=currentLabel(),r=runFor('labeling-practice');box.innerHTML='<label class="field-label" for="labeling-picker">Activity</label><select id="labeling-picker" '+(r?'disabled':'')+'>'+D.labeling.map(x=>'<option value="'+x.id+'" '+(x.id===a.id?'selected':'')+'>'+esc(x.title)+'</option>').join('')+'</select><p>'+esc(a.prompt)+'</p><figure class="label-diagram">'+numberDiagram(a)+'<figcaption>Follow each leader line to its target. The letters and answer mapping stay fixed between attempts.</figcaption><button type="button" class="text-link" data-enlarge-labeling>View larger</button></figure>'+(!r?'<button type="button" data-start-labeling>Start</button>':'<p class="timer" data-timer="labeling-practice"></p>'+a.values.map(x=>{const e=lastAttempt(r,x.letter),checked=checkedCurrent(r,x.letter);return'<div class="label-row"><label for="label-'+x.letter+'">'+x.letter+'</label><select id="label-'+x.letter+'" data-label-answer="'+x.letter+'"><option value="">Choose a label</option>'+a.options.map(o=>'<option value="'+o.id+'" '+(r.answers[x.letter]===o.id?'selected':'')+'>'+esc(o.text)+'</option>').join('')+'</select><button type="button" data-check-label="'+x.letter+'">Check</button><span class="label-feedback" role="status">'+(checked?(e.correct?'Correct.':'Not yet. Follow the leader line and reconsider its target.'):'')+'</span></div>';}).join('')+'<div class="actions"><button type="button" data-check-all-labels>Check all labels</button><button type="button" data-finish-labeling '+(!a.values.every(x=>checkedCurrent(r,x.letter))?'disabled':'')+'>Submit and finish</button><button type="button" class="button secondary" data-reset-run="labeling-practice">Stop and reset</button></div><p data-label-error role="status"></p><p class="small">Finish this run, or Stop and reset, before choosing a different diagram. A finished attempt is not necessarily all correct.</p>')+'<p class="small">'+state.history.filter(h=>h.key==='labeling-practice').length+' completed labeling attempt(s) in All My Work. Optional work does not change required progress.</p>';}
async function checkLabels(letters){const r=runFor('labeling-practice'),a=currentLabel();let blank=false;for(const letter of letters){const value=r.answers[letter];if(!value){blank=true;continue;}(r.attempts[letter]??=[]).push({value,correct:value===a.values.find(x=>x.letter===letter).answer,at:now()});}mark();renderLabeling();if(blank)$('[data-label-error]').textContent='Choose a response for every label you want to check.';await flush();}
function openReading(page,btn){const r=D.resources[0],p=r.pages.find(p=>p.printed===Number(page));if(!p){reportFailure(new Error('The requested printed page is not included in this source PDF. Your work has not changed.'));return;}readingPage=p.printed;$('#reading-title').textContent=r.title;$('#reading-subtitle').textContent=(p.printed?'Printed page '+p.printed:'Unnumbered historical MSDS insert')+' · PDF page '+p.physical+' of '+r.physicalPageCount;$('#reading-page').innerHTML=r.pages.map(p=>'<option value="'+p.printed+'" '+(p.printed===readingPage?'selected':'')+'>'+esc(p.label)+'</option>').join('');$('#reading-image').src=p.image;$('#reading-image').alt='Unit C textbook: '+p.label;$('#reading-image').dataset.physicalPage=p.physical;$('#reading-text').textContent=p.text;const index=r.pages.findIndex(x=>x.printed===readingPage);$('#reading-prev').disabled=index===0;$('#reading-next').disabled=index===r.pages.length-1;$('.reading-scroll').scrollTop=0;showDialog($('#reading-dialog'),btn);}
let pdfBlobURL;
function openPDF(){let url=D.resources[0].pdf;if(url.startsWith('data:')){if(!pdfBlobURL){const b64=url.split(',')[1],binary=atob(b64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);pdfBlobURL=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));}url=pdfBlobURL;}window.open(url+'#page='+D.resources[0].pages.find(p=>p.printed===readingPage).physical,'_blank','noopener,noreferrer');}
function renderVideos(){const selected=$('#video-select')?.value||D.videos[0].id;$$('[data-video-card]').forEach(node=>{const v=D.videos.find(v=>v.id===(node.dataset.videoCard||selected))||D.videos[0];node.innerHTML='<article class="video-card"><div class="video-copy"><p class="section-label">Optional video support</p><h3>'+esc(v.title)+'</h3><p class="small">'+esc(v.publisher)+'</p><p><strong>Viewing focus:</strong> '+esc(v.focus)+'</p><p>'+esc(v.purpose)+'</p></div><div class="video-stage" data-video-stage><button type="button" data-play-video="'+v.id+'">Play video</button></div><div class="video-footer"><a href="'+v.sourceUrl+'" target="_blank" rel="noopener noreferrer">Open the publisher’s video page</a><p class="small">Playback needs internet access. Turn on captions on the publisher page when offered. The written explanation below covers the concept; watching does not affect progress.</p></div><div class="concept-summary"><h4>Written explanation</h4><p>'+esc(v.written)+'</p></div></article>';});}
function describeRun(r){
 let detail='<p class="small">Started '+esc(r.startedAt)+' · '+(r.endedAt?'Finished '+esc(r.endedAt):'Unfinished')+'</p>';
 if(r.kind==='labeling'){detail+=r.activity.values.map(x=>'<h4>Label '+x.letter+': '+esc(x.value)+'</h4>'+attemptList(r,x.letter,{options:r.activity.options})).join('');}
 else detail+=(r.questions||[]).map(q=>'<h4>'+esc(q.prompt)+'</h4>'+attemptList(r,q.id,q)).join('');
 if(r.writingPrompts || r.kind==='required'){const prompts=r.writingPrompts||D.checks[r.key]?.writing||[];detail+=prompts.map(w=>{const x=r.writing[w.id];return'<h4>'+esc(w.prompt)+'</h4><p class="written-response">'+esc(x?.text||'No written response')+'</p><p class="small">'+(x?.saved?'Explicitly saved response; not automatically graded.':'Draft; not explicitly saved.')+'</p>'+(x?.versions?.length>1?'<details><summary>Earlier saved versions in this run</summary>'+x.versions.slice(0,-1).map(y=>'<p class="written-response">'+esc(y.text)+'</p>').join('')+'</details>':'');}).join('');}
 if(r.kind==='transfer')detail+='<p><strong>'+(r.laterPractice?'Later practice':'First whole-set submission')+'</strong> · Help used: '+esc(r.help||'not yet stated')+' (self-reported).</p>';
 return detail;
}
function attemptList(r,id,q){const events=r.attempts[id]||[];let out='';if(events.length)out='<ol>'+events.map((e,i)=>'<li>'+(i===0?'First checked attempt':'Later attempt '+(i+1))+': '+esc(answerText(q,e.value))+' — '+(q.kind==='flash'?'self-assessment':e.correct?'correct':'not correct')+'</li>').join('')+'</ol>';else out='<p>No checked attempt yet.</p>';if(r.answers[id]!==undefined&&!checkedCurrent(r,id))out+='<p>Current unchecked response: '+esc(answerText(q,r.answers[id]))+'</p>';return out;}
function renderWork(){
 const unfinished=Object.keys(state.runs).length;$('#work-summary').textContent=state.history.length+' completed run(s), '+unfinished+' unfinished run(s). '+(savedVersion!==dirtyVersion?'Some current changes are not yet confirmed saved. ':'')+'Written explanations and self-assessments are not automatically graded.';
 let h='<h2>Required checks and practice</h2>';
 if(!state.history.length&&!unfinished)h+='<p>No check or practice runs yet. Begin with the teaching lesson.</p>';
 for(const r of [...state.history,...Object.values(state.runs)])h+='<article class="record"><h3>'+esc(r.title)+'</h3><p class="status-label">'+(r.endedAt?(persistedRun(r)?'Completed run · saved':'Finished on screen · save pending'):'Unfinished run')+(r.kind==='required'?' · Required':' · Optional')+'</p><details><summary>View prompts, attempts and explanations</summary>'+describeRun(r)+'</details></article>';
 h+='<h2>Lesson practice and explanations</h2>';
 for(const [id,q] of Object.entries(D.exercises)){const r=state.calcs[id],method=state.drafts[id+'-method'];if(!r&&!method)continue;h+='<article class="record"><p class="eyebrow">'+esc(topicLabel(q.topic))+'</p><h3>'+esc(q.prompt)+'</h3><p>Current answer: '+esc(answerText(q,r?.answer))+(q.kind==='number'?' '+esc(q.unit):'')+'</p><p class="written-response">'+esc(method||'No written working yet.')+'</p><ol>'+(r?.attempts||[]).map((e,i)=>'<li><strong>'+(i===0?'First checked attempt':'Later checked attempt '+(i+1))+'</strong>: '+esc(answerText(q,e.value))+' — '+(e.correct?'answer matches':'not a match')+(e.method?'<p class="written-response">'+esc(e.method)+'</p>':'')+'</li>').join('')+'</ol><p class="small">Only the selected or short answer is automatically checked. Written reasoning is not automatically graded.</p></article>';}
 h+='<h2>Written responses</h2>';
 for(const [id,n] of Object.entries(state.notes)){const q=D.notes[id];h+='<article class="record"><h3>'+esc(q.title)+'</h3><p>'+esc(q.prompt)+'</p><p><strong>Current '+esc(n.status)+':</strong></p><p class="written-response">'+esc(n.text)+'</p>'+n.versions.map((v,i)=>'<details><summary>'+(i===0?'First saved response':'Later saved response '+(i+1))+'</summary><p class="written-response">'+esc(v.text)+'</p></details>').join('')+'</article>';}
 h+='<h2>Frayer work</h2>';
 for(const [id,f] of Object.entries(state.frayers)){const t=termRecord(id);h+='<article class="record"><h3>'+esc(t?.term||id)+'</h3><p>Current status: '+esc(f.status)+'</p>'+frayerPrint(f.fields)+f.versions.map((v,i)=>'<details><summary>'+(i===0?'First collected version':'Later collected version '+(i+1))+'</summary>'+frayerPrint(v.fields)+'</details>').join('')+'</article>';}
 h+='<h2>Original textbook question work</h2>';
 for(const q of [...D.bookQuestions,...(D.legacyBookQuestions||[])]){const a=state.book[q.id];if(!a)continue;const previous=(D.legacyBookQuestions||[]).some(item=>item.id===q.id);h+='<article class="record"><p class="eyebrow">'+(previous?'Previous page-based Textbook Practice work':'Current question-level Textbook Practice work')+'</p><h3>'+esc(q.title)+' · p. '+q.printedPage+'</h3><p>'+esc(q.prompt)+'</p><details><summary>'+(previous?'Original saved page context':'Original question text')+'</summary><div class="written-response">'+esc(q.originalText)+'</div></details><p>Current status: '+esc(a.status)+'</p><p class="written-response">'+esc(a.text)+'</p>'+(a.versions||[]).map((v,i)=>'<details><summary>'+(i===0?'First saved response':'Later saved response '+(i+1))+'</summary><p class="written-response">'+esc(v.text)+'</p></details>').join('')+'</article>';}
 if(state.recoveryCopies.length)h+='<h2>Preserved recovery copies</h2><p>Complete alternate versions remain available below. The normal work PDF does not expand these raw recovery archives. To print an archive separately, open it and use its Print this recovery copy button.</p>'+state.recoveryCopies.map(c=>'<article class="record recovery-archive"><h3>'+esc(c.label)+'</h3><details><summary>Complete retained copy · '+esc(c.at)+'</summary><button type="button" data-print-archive="'+c.id+'">Print this recovery copy</button><pre>'+esc(JSON.stringify(c.payload,null,2))+'</pre></details></article>').join('');
 h+=renderPreviousDraft();
 $('#work-records').innerHTML=h;
}
function renderPreviousDraft(){
 let h='<h2>Previous draft work</h2><p class="small">Responses from the earlier eight-lesson Unit C draft are preserved in a separate browser record. They are for reference only and never count toward the replacement lessons or checks.</p>';
 if(previousDraftError)return h+'<p role="status">The previous draft could not be opened: '+esc(previousDraftError.message)+'. Its stored record was not changed.</p>';
 if(!previousDraft)return h+'<p>Looking for previous draft work in this browser…</p>';
 const p=previousDraft.payload,c=window.S24_LEGACY_V1||{},lessons=c.lessons||[];
 const hasWork=Object.values(p.notes).some(x=>x?.text)||Object.values(p.book).some(x=>x?.draft||x?.versions?.length)||Object.keys(p.frayers).length||Object.keys(p.calcs).length||Object.values(p.drafts).some(Boolean)||p.history.length||p.recoveryCopies.length;
 if(!hasWork)return h+'<p>No previous draft responses were saved in this browser.</p>';
 h+='<p class="status-label">Earlier draft · '+esc(previousDraft.updatedAt||'save date unavailable')+' · read only</p>';
 for(const [i,l] of lessons.entries()){
  const n=p.notes[l.writingId],q=p.calcs[l.checkId];if(!n?.text&&!q)continue;
  h+='<article class="record"><h3>Earlier lesson '+(i+1)+': '+esc(l.title)+'</h3>'+(q?'<p>Selected answer: '+esc(l.options?.[q.answer]??q.answer)+' · '+(q.correct?'matched the former key':'did not match the former key')+'</p>':'')+(n?.text?'<p class="written-response">'+esc(n.text)+'</p>':'')+'</article>';
 }
 for(const [id,n] of Object.entries(p.notes)){if(lessons.some(l=>l.writingId===id)||!n?.text)continue;h+='<article class="record"><h3>Earlier written response · '+esc(id)+'</h3><p class="written-response">'+esc(n.text)+'</p></article>';}
 for(const [id,n] of Object.entries(p.book)){if(!n?.draft&&!n?.versions?.length)continue;h+='<article class="record"><h3>Earlier textbook work · '+esc(id)+'</h3>'+(n.draft?'<p class="written-response">'+esc(n.draft)+'</p>':'')+(n.versions||[]).map((v,i)=>'<details><summary>Saved version '+(i+1)+'</summary><p class="written-response">'+esc(v.text)+'</p></details>').join('')+'</article>';}
 for(const [id,n] of Object.entries(p.frayers)){h+='<article class="record"><h3>Earlier vocabulary · '+esc(id)+'</h3>'+frayerPrint(n.fields||{})+(n.versions||[]).map((v,i)=>'<details><summary>Collected version '+(i+1)+'</summary>'+frayerPrint(v.fields||{})+'</details>').join('')+'</article>';}
 for(const [id,value] of Object.entries(p.drafts)){if(String(value||'').trim())h+='<article class="record"><h3>Earlier draft · '+esc(id)+'</h3><p class="written-response">'+esc(value)+'</p></article>';}
 for(const r of p.history)h+='<article class="record"><h3>Earlier completed run · '+esc(r.title||r.id)+'</h3><details><summary>Saved run data</summary><pre class="written-response">'+esc(JSON.stringify(r,null,2))+'</pre></details></article>';
 for(const r of p.recoveryCopies)h+='<article class="record"><h3>Earlier recovery copy · '+esc(r.label)+'</h3><details><summary>Complete retained copy</summary><pre class="written-response">'+esc(JSON.stringify(r.payload,null,2))+'</pre></details></article>';
 return h;
}
function frayerPrint(fields){return'<dl>'+[['meaning','Meaning'],['features','Features'],['example','Example'],['nonexample','Non-example']].map(([key,label])=>'<dt><strong>'+label+'</strong></dt><dd class="written-response">'+esc(fields[key]||'No response')+'</dd>').join('')+'</dl>';}
function showRecovery(){if(!conflict)return;const pairs=[['Current tab (including all visible drafts)',state],['Last confirmed save in this tab',conflict.lastConfirmed.payload],['Other saved version',conflict.remote.payload]];const content=pairs.map(([label,p])=>'<h3>'+label+'</h3><details open><summary>Complete work copy</summary><pre class="written-response">'+esc(JSON.stringify(p,null,2))+'</pre></details>').join('');$('#recovery-records').innerHTML=content;showDialog($('#recovery-dialog'),$('#view-recovery'));}
function withoutRecovery(p){const q=clone(p);q.recoveryCopies=[];return q;}
async function resolveConflict(useRemote){if(!conflict)return;const local=clone(state),remote=clone(conflict.remote),base=clone(conflict.lastConfirmed),chosen=clone(useRemote?remote.payload:local);const history=new Map([...remote.payload.history,...local.history].map(x=>[x.id,x]));chosen.history=[...history.values()];const copies=new Map([...remote.payload.recoveryCopies,...local.recoveryCopies].map(x=>[x.id,x]));for(const [label,p] of [['My drafts before conflict resolution',local],['Other saved version before conflict resolution',remote.payload],['Last confirmed local save before conflict resolution',base.payload]]){const id=uid('recovery');copies.set(id,{id,label,at:now(),payload:withoutRecovery(p)});}chosen.recoveryCopies=[...copies.values()];state=chosen;confirmed=remote;conflict=null;mark();const ok=await flush();if(ok){$('#recovery-dialog').close();renderAll();}else{$('#recovery-status').textContent='Resolution was not saved. The complete copies remain available.';}}

function renderTransfer(){const box=$('[data-transfer]'),c=D.transfer,r=runFor(c.id),past=state.history.filter(h=>h.key===c.id);if(!r){box.innerHTML='<p class="eyebrow">Optional independent application</p><h2>'+esc(c.title)+'</h2><p>Try three selections and one explanation before any feedback. Indicate whether you used help. Your first whole-set submission is kept separately from later practice; this is not a secure test.</p><button type="button" data-start-transfer>'+(past.length?'Try again — later practice':'Start independent application')+'</button>'+(past.length?'<details><summary>Compare your most recent submission</summary>'+past.at(-1).questions.map(q=>'<h3>'+esc(q.prompt)+'</h3><p>'+esc(q.explanation)+'</p>').join('')+'<h3>Explanation criteria</h3><p>'+esc(c.criteria)+'</p></details>':'');return;}
box.innerHTML='<p class="eyebrow">Optional independent application</p><h2>'+esc(c.title)+'</h2><p>Complete the whole set before feedback. No individual answer checks appear here.</p>'+r.questions.map((q,i)=>'<section class="check-question"><h3>'+(i+1)+'. '+esc(q.prompt)+'</h3>'+choiceHTML(q,r.id+'-'+q.id,r.answers[q.id],'data-transfer-answer="'+q.id+'"')+'</section>').join('')+'<label class="field-label" for="transfer-writing">'+esc(c.writing[0].prompt)+'</label><textarea id="transfer-writing" data-transfer-writing rows="5">'+esc(r.writing[c.writing[0].id]?.text||'')+'</textarea><label class="field-label" for="transfer-help">Did you use help for this attempt?</label><select id="transfer-help"><option value="">Choose one</option><option value="no" '+(r.help==='no'?'selected':'')+'>No — I attempted it independently</option><option value="yes" '+(r.help==='yes'?'selected':'')+'>Yes — I used help or checked a resource</option></select><div class="actions"><button type="button" data-submit-transfer>Submit whole set</button><button type="button" class="button secondary" data-reset-run="'+c.id+'">Stop and reset</button></div><p data-transfer-status role="status"></p>';}
async function startTransfer(){const c=D.transfer;if(runFor(c.id))return;const r=newRun('transfer',c.title,c.questions,c.id);r.writingPrompts=clone(c.writing);r.laterPractice=state.history.some(h=>h.key===c.id);state.runs[c.id]=r;mark();renderTransfer();await flush();}
async function submitTransfer(){const c=D.transfer,r=runFor(c.id);if(!r)return;if(!r.questions.every(q=>validAnswer(q,r.answers[q.id]))||!r.writing[c.writing[0].id]?.text.trim()||!r.help){$('[data-transfer-status]').textContent='Answer all three selections, write your explanation, and state whether you used help before submitting.';return;}const done=clone(r);for(const q of done.questions)done.attempts[q.id]=[{value:done.answers[q.id],correct:match(q,done.answers[q.id]),at:now()}];done.writing[c.writing[0].id].saved=true;done.endedAt=now();state.history.push(done);delete state.runs[c.id];mark();await flush();renderTransfer();renderWork();}

function orderedExercise(q){const x=clone(q);if(!x.options)return x;let n=2166136261;for(const c of x.id)n=Math.imul(n^c.charCodeAt(0),16777619);for(let i=x.options.length-1;i>0;i--){n^=n<<13;n^=n>>>17;n^=n<<5;const j=(n>>>0)%(i+1);[x.options[i],x.options[j]]=[x.options[j],x.options[i]];}return x;}
function renderExercise(box){const id=box.dataset.exercise,q=orderedExercise(D.exercises[id]),r=state.calcs[id]||{answer:'',attempts:[]},last=r.attempts.at(-1),checked=last&&String(last.value)===String(r.answer);const guided=q.role.startsWith('guided');
 let input=q.kind==='mc'?choiceHTML(q,id,r.answer,'data-exercise-answer'):'<label class="field-label" for="'+id+'-answer">'+(q.kind==='equation'?'Coefficients in order — separate with commas and include 1':q.kind==='number'?'Your answer ('+esc(q.unit)+')':'Your answer')+'</label><input id="'+id+'-answer" type="text" '+(q.kind==='number'?'inputmode="decimal"':'')+' data-exercise-answer value="'+esc(r.answer)+'">';
 const result=checked?(last.correct?'Correct. '+q.explanation:r.attempts.length===1?q.hint:'Compare your reasoning: '+q.explanation):'';
 box.innerHTML='<h3>'+esc(q.prompt)+'</h3>'+input+((guided||r.attempts.length)?'<details class="exercise-hint"><summary>Need a starting point?</summary><p>'+esc(q.hint)+'</p></details>':'')+'<label class="field-label" for="'+id+'-working">Your working or reason <span class="small">(optional; not automatically graded)</span></label><textarea rows="3" id="'+id+'-working" data-draft-key="'+id+'-method">'+esc(state.drafts[id+'-method']||'')+'</textarea><button type="button" data-exercise-check>Check answer</button><p class="exercise-error" role="status"></p><div class="feedback exercise-result" data-result="'+(last?.correct?'match':'retry')+'" role="status" '+(!checked?'hidden':'')+'>'+esc(result)+'</div>'+(r.attempts.length?'<p class="small exercise-save-note">'+r.attempts.length+' checked attempt(s) retained in All My Work. Your first response is preserved.</p>':'<p class="small exercise-save-note">Try the question before checking. This practice does not change required progress.</p>');
}
async function checkExercise(box){const id=box.dataset.exercise,q=D.exercises[id],r=state.calcs[id]||{answer:'',attempts:[]};if(!validAnswer(q,r.answer)){$('.exercise-error',box).textContent=invalidMessage(q);return;}r.attempts.push({value:r.answer,method:state.drafts[id+'-method']||'',correct:match(q,r.answer),at:now()});state.calcs[id]=r;mark();const button=$('[data-exercise-check]',box);button.disabled=true;button.textContent='Saving attempt…';const ok=await flush();renderExercise(box);$('[data-exercise-check]',box)?.focus({preventScroll:true});if(!ok){$('.exercise-error',box).textContent='This checked attempt is still on screen but was not saved. Retry saving before leaving.';$('.exercise-save-note',box).textContent='The attempt is not in the confirmed browser record.';}}

function showWorkbookLesson(value,expand=false){const picker=$('#workbook-lesson');if(!picker)return;const lesson=[...picker.options].some(option=>option.value===value)?value:'01';picker.value=lesson;$$('#workbook-practice [data-workbook-lesson]').forEach(panel=>{const selected=panel.dataset.workbookLesson===lesson;panel.hidden=!selected;if(selected&&expand)panel.open=true;});}
function renderAll(){ $$('[data-exercise]').forEach(renderExercise); renderTransfer(); $$('[data-required]').forEach(renderRequired);$$('[data-practice-mode]').forEach(renderPractice);renderWords();renderBook();renderLabeling();updateNotes();renderWork();updateProgress();$$('[data-draft-key]').forEach(input=>input.value=state.drafts[input.dataset.draftKey]||'');}
function route(){const raw=location.hash.slice(1)||'overview',[id,query]=raw.split('?'),params=new URLSearchParams(query||'');let page=document.getElementById(id);let anchor=null;if(page&&!page.classList.contains('course-page')){anchor=page;page=page.closest('.course-page');}if(!page)page=$('#overview');if(activeRoute!==page.id)scrollPositions.set(activeRoute,window.scrollY);activeRoute=page.id;$$('.course-page').forEach(p=>p.hidden=p!==page);$$('.nav-link').forEach(a=>{const active=a.hash==='#'+page.id;a.classList.toggle('active',active);if(active){a.setAttribute('aria-current','page');a.closest('details').open=true;}else a.removeAttribute('aria-current');});if(page.id==='core-vocabulary'&&termRecord(params.get('term'))){selectedWord=params.get('term');renderWords();}if(page.id==='textbook-practice'&&params.has('topic')){const t=params.get('topic');$('#book-topic').value=[...$('#book-topic').options].some(o=>o.value===t)?t:'all';renderBook();}if(page.id==='textbook-practice'&&params.has('workbook'))showWorkbookLesson(params.get('workbook'),true);if(page.id==='process-collection')renderWork();document.body.classList.remove('nav-open');$('#nav-scrim').hidden=true;$('[data-menu-button]').setAttribute('aria-expanded','false');requestAnimationFrame(()=>{if(anchor)anchor.scrollIntoView();else if(page.id==='textbook-practice'&&params.has('workbook'))$('#workbook-practice').scrollIntoView();else window.scrollTo(0,scrollPositions.get(page.id)||0);$('h1',page)?.focus({preventScroll:true});});}
window.addEventListener('hashchange',route);
function resetPrompt(key,button){const r=runFor(key);if(!r)return;resetKey=key;$('#reset-message').textContent='Clear only the unfinished '+r.title+' run: its answers, feedback, position and timer. Completed history and all other activities will remain.';showDialog($('#reset-dialog'),button);}
function onInput(e){const t=e.target;
 if(t.matches('[data-exercise-answer]')){const box=t.closest('[data-exercise]'),id=box.dataset.exercise;state.calcs[id]??={answer:'',attempts:[]};state.calcs[id].answer=t.value;mark();$('.exercise-result',box).hidden=true;}

 if(t.matches('[data-transfer-answer]')){runFor(D.transfer.id).answers[t.dataset.transferAnswer]=t.value;mark();}
 if(t.matches('[data-transfer-writing]')){runFor(D.transfer.id).writing[D.transfer.writing[0].id]={text:t.value,saved:false,versions:[]};mark();}
 if(t.matches('[data-draft-key]')){state.drafts[t.dataset.draftKey]=t.value;mark();}
 if(t.matches('[data-required-writing]')){const box=t.closest('[data-required]'),r=runFor(box.dataset.required),id=t.dataset.requiredWriting;r.writing[id]??={text:'',saved:false,versions:[]};r.writing[id].text=t.value;r.writing[id].saved=false;$('[data-writing-status="'+id+'"]',box).textContent='Draft. Save this written response again.';$('[data-finish-required]',box).disabled=true;mark();}
 if(t.matches('[data-required-answer]')){const box=t.closest('[data-required]'),r=runFor(box.dataset.required);r.answers[t.dataset.requiredAnswer]=t.value;const qid=t.dataset.requiredAnswer,val=t.value;mark();renderRequired(box);$('[data-required-answer="'+qid+'"][value="'+val+'"]',box)?.focus({preventScroll:true});}
 if(t.matches('[data-practice-input]')){const box=t.closest('[data-practice-mode]'),r=runFor(box.dataset.practiceMode),q=r.questions[r.position];r.answers[q.id]=t.value;mark();const next=$('[data-practice-next]',box);next.disabled=true;$('.feedback',box)?.remove();}
 if(t.matches('[data-frayer-field]')){const box=t.closest('[data-vword]'),id=box.dataset.vword,key=t.dataset.frayerField;state.frayers[id].fields[key]=t.value;state.frayers[id].status='draft';$('[data-field-count="'+key+'"]',t.closest('label')).textContent=t.value.length+' / 240 characters';$('[data-frayer-status]',box).textContent=t.value.length>240?'Draft saved locally. Shorten this field to 240 characters before collecting the word.':'Draft. Collect this word again after editing.';$('[data-frayer-model]',box).disabled=true;$('[data-frayer-comparison]',box).hidden=true;mark();}
 if(t.matches('[data-note-text]')){const box=t.closest('[data-note-id]'),id=box.dataset.noteId;state.notes[id]??={text:'',status:'draft',versions:[]};state.notes[id].text=t.value;state.notes[id].status='draft';$('[data-note-status]',box).textContent='Draft. Save response records a version.';$('[data-note-model]',box).disabled=true;$('[data-note-comparison]',box).hidden=true;mark();}
 if(t.matches('[data-book-text]')){state.book[bookId]??={text:'',status:'draft',versions:[]};state.book[bookId].text=t.value;state.book[bookId].status='draft';$('[data-book-status]').textContent='Draft. Save question work records a version.';mark();}
 if(t.id==='vocab-search')renderIndex();
}
document.addEventListener('input',onInput);
document.addEventListener('change',e=>{const t=e.target;
 if(t.id==='transfer-help'){runFor(D.transfer.id).help=t.value;mark();}
 if(t.matches('[data-setup-topic],[data-setup-difficulty],[data-setup-size]')){const box=t.closest('[data-practice-mode]'),s=setup(box.dataset.practiceMode);s.topic=$('[data-setup-topic]',box).value;s.difficulty=$('[data-setup-difficulty]',box).value;s.size=Number($('[data-setup-size]',box).value);renderPractice(box);}
 if(t.id==='vocab-topic')renderIndex();if(t.id==='drawer-word'){selectedWord=t.value;renderWords();}
 if(t.matches('[data-label-answer]')){state.runs['labeling-practice'].answers[t.dataset.labelAnswer]=t.value;mark();renderLabeling();}
 if(t.id==='reading-page')openReading(Number(t.value));
 if(t.id==='library-page'){const p=D.resources[0].pages.find(x=>x.printed===Number(t.value));$('#library-page-image').src=p.image;$('#library-page-image').alt='Unit C textbook: '+p.label;}
 if(t.id==='video-select')renderVideos();if(t.id==='book-topic')renderBook();if(t.id==='workbook-lesson')showWorkbookLesson(t.value,true);if(t.id==='labeling-picker'){selectedLabel=t.value;renderLabeling();}
});
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;try{
 if(b.matches('[data-exercise-check]')){await checkExercise(b.closest('[data-exercise]'));return;}
 if(b.matches('[data-start-transfer]')){await startTransfer();return;}
 if(b.matches('[data-submit-transfer]')){await submitTransfer();return;}
 if(b.id==='reading-size'){const dialog=$('#reading-dialog'),expanded=dialog.classList.toggle('is-expanded');b.textContent=expanded?'Restore size':'Expand viewer';b.setAttribute('aria-pressed',String(expanded));return;}
 if(b.matches('[data-close-dialog]')){b.closest('dialog').close();return;}
 if(b.matches('[data-term-id]')){openWord(b.dataset.termId,b);return;}
 if(b.matches('[data-select-word]')){selectedWord=b.dataset.selectWord;renderWords();history.replaceState(null,'','#core-vocabulary?term='+selectedWord);return;}
 if(b.id==='open-core-term'){$('#vocab-dialog').close();location.hash='core-vocabulary?term='+selectedWord;return;}
 if(b.matches('[data-choose-word]')){await chooseWord(b.dataset.chooseWord);return;}
 if(b.matches('[data-collect-word]')){await collectWord(b.dataset.collectWord,b);return;}
 if(b.matches('[data-frayer-model]')){const box=b.closest('[data-vword]'),id=b.dataset.frayerModel;if(state.frayers[id]?.status!=='collected')return;const panel=$('[data-frayer-comparison]',box);panel.hidden=!panel.hidden;panel.innerHTML='<h4>Course model for comparison</h4>'+frayerPrint(termRecord(id).model);return;}
 if(b.matches('[data-start-required]')){await startRequired(b.dataset.startRequired);return;}
 if(b.matches('[data-check-required]')){await checkRequired(b);return;}
 if(b.matches('[data-save-writing]')){await saveWriting(b);return;}
 if(b.matches('[data-finish-required]')){await finishRequired(b.dataset.finishRequired);return;}
 if(b.matches('[data-retry-concepts]')){await retryConcepts(b.dataset.retryConcepts);return;}
 if(b.matches('[data-start-practice]')){await startPractice(b.closest('[data-practice-mode]'));return;}
 if(b.matches('[data-practice-check]')){await checkPractice(b.closest('[data-practice-mode]'));return;}
 if(b.matches('[data-practice-next]')){await nextPractice(b.closest('[data-practice-mode]'));return;}
 if(b.matches('[data-practice-prev]')){const box=b.closest('[data-practice-mode]');runFor(box.dataset.practiceMode).position--;mark();renderPractice(box);await flush();return;}
 if(b.matches('[data-reveal-card]')){const box=b.closest('[data-practice-mode]'),r=runFor(box.dataset.practiceMode),q=r.questions[r.position];r.revealed[q.id]=!r.revealed[q.id];mark();renderPractice(box);return;}
 if(b.matches('[data-rate-card]')){const box=b.closest('[data-practice-mode]'),r=runFor(box.dataset.practiceMode),q=r.questions[r.position];r.answers[q.id]=b.dataset.rateCard;(r.attempts[q.id]??=[]).push({value:b.dataset.rateCard,correct:null,selfAssessment:true,at:now()});mark();renderPractice(box);await flush();return;}
 if(b.matches('[data-reset-run]')){resetPrompt(b.dataset.resetRun,b);return;}
 if(b.id==='reset-confirm'){if(resetKey){const kept=clone(state.runs[resetKey]);delete state.runs[resetKey];mark();const ok=await flush();if(!ok){state.runs[resetKey]=kept;dirtyVersion++;$('#reset-message').textContent='Reset was not saved. Your unfinished run is retained. Keep working or resolve the save problem before resetting.';return;}}$('#reset-dialog').close();renderAll();return;}
 if(b.matches('[data-note-save]')){await saveNote(b.closest('[data-note-id]'));return;}
 if(b.matches('[data-note-model]')){const box=b.closest('[data-note-id]'),id=box.dataset.noteId;if(state.notes[id]?.status!=='saved')return;const panel=$('[data-note-comparison]',box);panel.hidden=!panel.hidden;panel.textContent=D.notes[id].model;return;}
 if(b.matches('[data-book-select]')){bookId=b.dataset.bookSelect;renderBook();return;}
 if(b.matches('[data-book-prev],[data-book-next]')){const list=currentBookList();let i=list.findIndex(q=>q.id===bookId);i+=b.matches('[data-book-next]')?1:-1;bookId=list[i].id;renderBook();return;}
 if(b.matches('[data-book-save]')){await saveBook();return;}
 if(b.matches('[data-open-reading],[data-open-pdf]')){openReading(Number(b.dataset.openReading??b.dataset.openPdf),b);return;}
 if(b.id==='reading-prev'){openReading(D.resources[0].pages[D.resources[0].pages.findIndex(p=>p.printed===readingPage)-1].printed);return;}if(b.id==='reading-next'){openReading(D.resources[0].pages[D.resources[0].pages.findIndex(p=>p.printed===readingPage)+1].printed);return;}if(b.id==='library-open'){openReading(Number($('#library-page').value),b);return;}
 if(b.matches('[data-pdf-window]')){openPDF();return;}
 if(b.matches('[data-enlarge-question]')){const q=D.bookQuestions.find(q=>q.id===b.dataset.enlargeQuestion);$('#figure-title').textContent='Unit C textbook · '+q.title;$('#figure-body').innerHTML='<img src="'+q.image+'" alt="'+esc(q.prompt)+'">';showDialog($('#figure-dialog'),b);return;}
 if(b.matches('[data-enlarge-figure]')){const f=D.figures[b.dataset.enlargeFigure];$('#figure-title').textContent=f.title;$('#figure-body').innerHTML='<img src="'+f.image+'" alt="'+esc(f.alt)+'">';showDialog($('#figure-dialog'),b);return;}
 if(b.matches('[data-supplementary-pdf]')){const r=D.supplementary.find(x=>x.id===b.dataset.supplementaryPdf);if(r)window.open(r.pdf,'_blank','noopener,noreferrer');return;}
 if(b.matches('[data-enlarge-labeling]')){$('#figure-title').textContent=currentLabel().title;$('#figure-body').innerHTML=numberDiagram(currentLabel());showDialog($('#figure-dialog'),b);return;}
 if(b.matches('[data-start-labeling]')){const r=newRun('labeling',currentLabel().title,[],'labeling-practice');r.activity=clone(currentLabel());state.runs['labeling-practice']=r;mark();renderLabeling();await flush();return;}
 if(b.matches('[data-check-label]')){await checkLabels([b.dataset.checkLabel]);return;}
 if(b.matches('[data-check-all-labels]')){await checkLabels(currentLabel().values.map(x=>x.letter));return;}
 if(b.matches('[data-finish-labeling]')){const r=runFor('labeling-practice');if(!currentLabel().values.every(x=>checkedCurrent(r,x.letter)))return;const done=clone(r);done.endedAt=now();state.history.push(done);delete state.runs['labeling-practice'];mark();await flush();renderLabeling();renderWork();return;}
 if(b.matches('[data-play-video]')){const v=D.videos.find(x=>x.id===b.dataset.playVideo),stage=b.closest('[data-video-stage]');const src=v.provider==='youtube'?'https://www.youtube-nocookie.com/embed/'+v.videoId+'?autoplay=1':'https://player.vimeo.com/video/'+v.videoId+'?autoplay=1';stage.innerHTML='<iframe title="'+esc(v.title)+'" src="'+src+'" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';return;}
 if(b.matches('[data-menu-button]')){const isOpen=document.body.classList.toggle('nav-open');$('#nav-scrim').hidden=!isOpen;b.setAttribute('aria-expanded',String(isOpen));return;}
 if(b.id==='nav-scrim'){document.body.classList.remove('nav-open');b.hidden=true;$('[data-menu-button]').setAttribute('aria-expanded','false');$('[data-menu-button]').focus();return;}
 if(b.matches('[data-sidebar-toggle]')){document.body.classList.add('sidebar-collapsed');$('#sidebar-reopen').hidden=false;return;}
 if(b.id==='sidebar-reopen'){document.body.classList.remove('sidebar-collapsed');b.hidden=true;return;}
 if(b.matches('[data-print-archive]')){const c=state.recoveryCopies.find(x=>x.id===b.dataset.printArchive);$('#recovery-print').innerHTML='<h1>'+esc(c.label)+'</h1><pre>'+esc(JSON.stringify(c.payload,null,2))+'</pre>';document.body.classList.add('print-recovery');window.print();return;}
 if(b.matches('[data-print-work]')){await flush();renderWork();window.print();return;}
 if(b.id==='retry-save'){await retryStorage();return;}if(b.id==='view-recovery'){showRecovery();return;}
 if(b.id==='keep-local'){await resolveConflict(false);return;}if(b.id==='keep-remote'){await resolveConflict(true);return;}
 if(b.id==='print-recovery'){$('#recovery-print').innerHTML=$('#recovery-records').innerHTML;document.body.classList.add('print-recovery');window.print();return;}
 }catch(err){reportFailure(err);console.error(err);}});
let printDetails=[];
window.addEventListener('afterprint',()=>{document.body.classList.remove('print-recovery');printDetails.forEach(d=>{if(d.isConnected)d.open=false;});printDetails=[];});
window.addEventListener('beforeprint',()=>{renderWork();printDetails=$$('#process-collection details:not([open])');printDetails.forEach(d=>d.open=true);});
window.addEventListener('beforeunload',e=>{if(savedVersion!==dirtyVersion||conflict){e.preventDefault();e.returnValue='Your latest work has not been confirmed saved.';}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&dirtyVersion!==savedVersion)flush();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('dialog[open]')&&document.body.classList.contains('nav-open')){$('#nav-scrim').click();}});
setInterval(()=>$$('[data-timer]').forEach(node=>{const r=runFor(node.dataset.timer);if(!r)return;const sec=Math.max(0,Math.floor((Date.now()-Date.parse(r.startedAt))/1000));node.textContent='Elapsed since start: '+Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');}),1000);
const ready=(async()=>{try{await store.open();confirmed=await store.load();state=clone(confirmed.payload);status(confirmed.revision?'Saved work opened · This browser only; nothing is automatically submitted.':'Local browser saving ready · Nothing is automatically submitted.');}catch(e){loadFailure=e;reportFailure(e);}try{await previousStore.open();previousDraft=await previousStore.load();}catch(e){previousDraftError=e;}renderAll();renderVideos();route();document.body.dataset.ready='true';})();
window.S24={ready,flush,inspect:()=>({state:clone(state),confirmed:clone(confirmed),dirty:dirtyVersion!==savedVersion,conflict:!!conflict,activeRoute}),openReading};
})();
