/* Math 10C Unit 3 runtime. Canonical HTML stays in place; only marked exercise/report regions render.
   Standalone browser recovery is separate from the existing Canvas Helper bridge's LMS ownership. */
(function(){'use strict';
const D=window.UNIT3_DATA,M=window.UnitMath,C=window.MathContracts,State=window.MathState,Pilot=window.MathPilotSlice;
const authoredQuestions=[...D.questions];
for(const family of ['positive','signed','common'])for(let p=family==='positive'?1:-9;p<=9;p++)for(let q=p;q<=9;q++)if(p&&q)for(let g=family==='common'?2:1;g<=(family==='common'?9:1);g++)D.questions.push(C.family(family,p,q,g));
const Q=Object.fromEntries(D.questions.map(q=>[q.id,q]));const questionIds=Object.keys(Q);
for(const q of D.questions){
 if(q.family)q.prompt='Factor completely over the integers, taking out the whole integer GCF first when needed.';
 Object.defineProperty(q,'hint',{get:()=>supportText(q,'hint')});
 Object.defineProperty(q,'steps',{get:()=>supportText(q,'steps')});
}
function supportText(q,kind){const host=document.querySelector(q.family?'[data-family-support="'+q.family+'"]':'[data-support-q="'+q.id+'"]');if(!host)return kind==='steps'?['Use the lesson explanation or keep your work for teacher review.']:'Use the lesson explanation.';
 const p=q.parameters||{},vals={...p,sum:(p.p||0)+(p.q||0),product:(p.p||0)*(p.q||0),answer:q.answer,expression:q.expression};const fill=s=>s.replace(/\{(p|q|g|sum|product|answer|expression)\}/g,(_,k)=>String(vals[k]));
 return kind==='hint'?fill(host.querySelector('[data-support-hint]').textContent):[...host.querySelectorAll('[data-support-steps] li')].map(x=>fill(x.textContent));
}
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>esc(s).replace(/\^([1-6])/g,'<sup>$1</sup>').replace(/[−-]/g,'−').replace(/\*/g,' · ');
const bridge=window.__canvasHelperScorm;let managed=false,blocked=true,dirty=false,timer,repairReturn=null,returnFocusId=null,printDisclosureState=[],saver;
const blank=()=>({v:D.version,rev:0,route:'u3-overview',r:{},active:[],pos:0,recent:[],pins:[],selectedTopic:'mixed',runMode:'learn',runSeed:0,firsts:{},drafts:{},counts:{},trig:{},reasons:{},paper:{},done:[],notes:{},exposed:[],seen:[],summary:{attempts:0,correct:0,supported:0},skills:{},legacySummary:{attempts:0,correct:0,supported:0},summaryRevision:0});
let S=blank();
const rawLimit=160;
const knownPages=new Set($$('.course-page').map(n=>n.id));
const allowedPages=new Set([...knownPages].filter(id=>Pilot.isActiveRoute(id)));
const validStr=(x,n)=>typeof x==='string'&&x.length<=n&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(x);
function pack(s){return State.encode(s,questionIds);}
function unpack(data){return State.decode(data,{questions:Q,pages:[...knownPages],version:D.version});}
function message(text,error=false){const host=$('#course-save-status'),node=$('#save-message');if(!host||!node)return;node.textContent=text;host.classList.toggle('error',error);host.style.display=error?'flex':'';$('#save-retry').hidden=!error;}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,5000);}
function snapshot(){return pack(S);}
function syncSaving(){const v=saver.inspect();managed=v.managed;blocked=v.blocked||!v.ownsWriterLock;dirty=v.dirty;}
function save(){if(blocked)return false;S.rev=Math.min(Number.MAX_SAFE_INTEGER,S.rev+1);try{compact();const ok=saver.edited();syncSaving();updateProgress();return ok;}catch(e){saver.fail(e);syncSaving();updateProgress();return false;}}
function showRecovery(branches,text){const p=$('#recovery-panel');p.hidden=false;$('#recovery-message').textContent=text;$('#recovery-versions').innerHTML='';for(const [i,b]of branches.entries()){const article=document.createElement('article');const heading=document.createElement('h3');heading.textContent='Saved copy '+(i+1);article.append(heading);const note=document.createElement('p');note.className='small';note.textContent=b.label+(b.durable?' · safely preserved for recovery':' · held in this tab; download it before closing');article.append(note);const actions=document.createElement('div');actions.className='actions';const dl=document.createElement('button');dl.type='button';dl.className='button secondary';dl.textContent='Download this copy';dl.dataset.recoveryDownload=String(i);actions.append(dl);try{unpack(b.raw);const use=document.createElement('button');use.type='button';use.className='button secondary';use.textContent='Restore this copy';use.dataset.recoveryChoose=String(i);actions.append(use);}catch{}article.append(actions);const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Show technical recovery data';details.append(summary);const preview=document.createElement('textarea');preview.readOnly=true;preview.rows=3;preview.value=b.raw;preview.setAttribute('aria-label','Technical recovery data for '+b.label);details.append(preview);article.append(details);$('#recovery-versions').append(article);} }
function setWritable(writable){blocked=!writable;for(const e of $$('[data-answer],[data-structured-part],[data-reason],[data-note],[data-paper],#practice-reason,#trig-side,#trig-adjacent,#trig-hypotenuse,#trig-ratio,#trig-angle,#trig-length,#trig-length-ratio,#trig-reason'))e.disabled=!writable;for(const e of $$('[data-check],[data-hint],[data-solution],[data-record],#start-practice,#start-independent,#trig-setup,#trig-angle-check,#trig-length-check'))e.disabled=!writable;}
saver=window.MathSaveController.create({bridge,key:'math10c-unit3-pilot:review:v2',getSnapshot:snapshot,setState:s=>{S=Pilot.migrateRoute(s);},decode:unpack,validate:State.checkCapacity,completedIds:()=>[...S.done.map(x=>'u3-check-'+x.replace('.',''))],onStatus:(text,error)=>{message(text,error);if(saver)syncSaving();},onRecovery:showRecovery,onWritable:setWritable});
async function connect(){await saver.open();syncSaving();}
function decide(message){return new Promise(resolve=>{const dialog=$('#decision-dialog'),before=document.activeElement;$('#decision-message').textContent=message;const finish=v=>{dialog.close();$('#decision-yes').onclick=null;$('#decision-no').onclick=null;before?.focus?.();resolve(v);};$('#decision-yes').onclick=()=>finish(true);$('#decision-no').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false);};dialog.showModal();$('#decision-no').focus();});}
function paused(q){const page=$('#u3-'+q.lesson?.replace('.',''));return D.disabledPracticeLessons.includes(q.lesson)||page?.dataset.mathChecking==='paused';}
function rec(qid,instance){const id=instance||'s-'+qid;if(!S.r[id]){const first=!instance&&S.firsts[qid];S.r[id]={q:qid,d:!instance?(S.drafts[qid]||''):'',a:first?[first]:[],n:S.counts[qid]||(first?1:0),s:S.exposed.includes(qid)?8:0,reason:'',closed:false,firstSuccess:first?.[2]==='correct',catalog:window.MathCatalogs.current};}
 if(!instance&&!/^c3[1-8]$/.test(qid)){S.recent=S.recent.filter(x=>x!==id);S.recent.push(id);}return S.r[id];}
function related(qid){const signature=C.signature(Q[qid]);return D.questions.filter(q=>C.signature(q)===signature).map(q=>q.id);}
function markSeen(qid){for(const id of related(qid))if(!S.seen.includes(id))S.seen.push(id);}
function expose(qid,mask){markSeen(qid);for(const id of related(qid)){if(!S.exposed.includes(id))S.exposed.push(id);for(const r of Object.values(S.r))if(r.q===id)r.s|=mask;}}
function getRaw(task){const parts=$$('[data-structured-part]',task);if(parts.length)return parts.map(x=>x.value).join('|');const inp=$('[data-answer]',task);return inp?inp.value:'';}
function supports(mask){const ar=[];if(mask&1)ar.push('hint');if(mask&2)ar.push('solution revealed');if(mask&4)ar.push('corrective feedback');if(mask&8)ar.push('prior in-course exposure');return ar.length?ar.join(', '):'without in-course mathematical support';}
function outcome(s){return({correct:'Correct in the requested form',incorrect:'Needs repair',equivalent:'Equivalent; form or next step unfinished',intermediate:'Correct for this step',ungraded:'Method retained; not automatically graded',hint:'A hint to get you moving',input:'Entry repair needed',unsupported:'Outside automatic checking'})[s]||s;}
function showFeedback(task,result){const box=$('[data-feedback]',task),input=$('[data-answer]',task);if(input){box.id='feedback-'+input.id;input.setAttribute('aria-describedby',box.id);}box.hidden=false;box.dataset.status=result.status;
 let key=result.status,params={};const q=Q[task.dataset.question];if(!result.historical&&result.status==='incorrect'&&q?.mode==='factor'){try{const actual=M.parse(input.value).p,target=M.parse(q.answer).p;if((actual['']||0)===(target['']||0)&&actual.xx===target.xx){key='wrong-middle';params={middle:actual.x||0,target:target.x||0};}}catch{}}
 if(result.status==='equivalent'&&q?.mode==='split')key='split-not-useful';if(result.status==='incorrect'&&q?.contract==='integer-root-bracket-v1')key='root-bracket-wrong';if(result.status==='incorrect'&&q?.contract==='factor-pair-v1')key='pair-wrong';
 const text=result.historical?result.detail:result.status==='hint'?result.detail:($('[data-feedback-source="'+key+'"]')?.textContent||'Your work is retained. Use the lesson explanation or ask for review.');
 const body=text.replace(/\{(middle|target)\}/g,(_,k)=>String(params[k]));box.innerHTML='<strong>'+esc(outcome(result.status))+'</strong><p>'+esc(body)+'</p>'+(result.expanded?'<p>Your response expands to <span class="inline-math">'+pretty(result.expanded)+'</span>.</p>':'');box.setAttribute('data-canvas-helper-studio-edit','annotation-only');}
function solutionHtml(q){return '<div class="note"><strong>Worked solution</strong><ol>'+q.steps.map(s=>'<li>'+pretty(s)+'</li>').join('')+'</ol></div>';}
function submitTask(task){if(task.dataset.visualInputBlocked==='true'){showFeedback(task,{status:'unsupported'});toast('The visual entry was not transferred. Repair it or use the preserved native entry.');return;}if(paused(Q[task.dataset.question])){toast('Automatic checking for this topic is paused. Your work is kept; use the written lesson or ask your teacher.');return;}if(blocked){toast('Saving is paused for recovery. Keep your work on paper or copy the current report.');return;}const qid=task.dataset.question,instance=task.dataset.instance,r=rec(qid,instance),raw=getRaw(task);r.d=raw;if(!instance)S.drafts[qid]=raw;
 const result=C.check(raw,Q[qid]);if(State.validText(raw,160)&&!['input','unsupported'].includes(result.status)){markSeen(qid);r.n=Math.min(Number.MAX_SAFE_INTEGER,r.n+1);if(!instance)S.counts[qid]=r.n;r.a.push([r.n,raw,result.status,r.s,State.resultProvenance(Q[qid],result.detail||'')]);if(!instance&&!S.firsts[qid])S.firsts[qid]=[r.n,raw,result.status,r.s,State.resultProvenance(Q[qid],result.detail||'')];if(r.a.length>4)r.a=[r.a[0],...r.a.slice(-3)];State.recordSummary(S,Q[qid].lesson,result.status,r.s);if(result.status==='correct')r.firstSuccess=true;if(['incorrect','equivalent'].includes(result.status))expose(qid,4);}
 showFeedback(task,result);if(!['input','unsupported'].includes(result.status))draftFeedback(task,r);const input=$('[data-answer]',task);input?.setAttribute('aria-invalid',String(result.status==='input'));if(instance)updateRunMeta();save();}
function hintTask(task,reveal){if(blocked)return;if(paused(Q[task.dataset.question])){toast('Automatic practice support for this topic is paused. Use the lesson explanation or your teacher’s route.');return;}const qid=task.dataset.question,r=rec(qid,task.dataset.instance),q=Q[qid];r.d=getRaw(task);expose(qid,reveal?2:1);r.s|=reveal?2:1;
 if(reveal){const box=$('[data-worked]',task);box.hidden=false;box.innerHTML=solutionHtml(q);}else showFeedback(task,{status:'hint',detail:q.hint});save();}
function keypad(){for(const box of $$('[data-keypad]')){if(box.childElementCount)continue;const q=Q[box.closest('.inline-task')?.dataset.question];const symbols=q?.contract==='whole-number-v1'?[['×','*'],['□²','^2'],['□³','^3'],['(','('],[')',')']]:q?.contract==='core-quadratic-v1'?[['x','x'],['x²','^2'],['(','('],[')',')'],['×','*'],['−','-']]:[['x','x'],['y','y'],['x²','^2'],['x³','^3'],['(','('],[')',')'],['×','*'],['−','-']];for(const [label,insert] of symbols){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.insert=insert;b.dataset.input=box.dataset.keypad;b.setAttribute('aria-label','Insert '+(label==='x²'?'power two':label==='x³'?'power three':label));box.append(b);}}}
function previewInput(input){const p=$('[data-preview="'+CSS.escape(input.id)+'"]');if(p)p.innerHTML=input.value?pretty(input.value):'<span class="small">Your notation preview appears here.</span>';}
function draftFeedback(task,r){const box=$('[data-feedback]',task);if(!box)return;const current=getRaw(task),a=r?.a?.at(-1);let history=$('[data-history-status]',task);if(!history){history=document.createElement('p');history.dataset.historyStatus='true';history.className='small';box.after(history);}
 if(a&&a[1]===current){showFeedback(task,{status:a[2],detail:a[4]?.detail||('Retained result from '+(a[4]?.engine||'legacy engine')+'; not regraded.'),historical:true});history.textContent='Checked response: '+a[1]+' · '+supports(a[3])+' · '+(a[4]?.engine||'legacy provenance');}
 else{box.hidden=false;box.dataset.status='ungraded';box.textContent='Current draft has not been checked.';history.textContent=a?'Last checked response: '+a[1]+' · '+outcome(a[2])+' · '+supports(a[3])+' · '+(a[4]?.engine||'legacy provenance'):'No mathematical submission has been recorded for this draft.';}}
function syncInputs(){for(const t of $$('.inline-task')){const qid=t.dataset.question,r=S.r[t.dataset.instance||'s-'+qid],inp=$('[data-answer]',t);if(inp){inp.value=r?r.d:S.drafts[qid]||'';previewInput(inp);const fields=$$('[data-structured-part]',t);if(fields.length){const values=inp.value.split('|');fields.forEach((f,i)=>f.value=values[i]||'');}draftFeedback(t,r);if(r&&(r.s&2)){$('[data-worked]',t).innerHTML=solutionHtml(Q[qid]);$('[data-worked]',t).hidden=false;}}}
 for(const e of $$('[data-reason]'))e.value=S.reasons[e.dataset.reason]||'';
 for(const e of $$('[data-paper]'))e.checked=!!S.paper[e.dataset.paper];
 for(const e of $$('[data-note]'))e.value=S.notes[e.dataset.note]||'';
 $('#practice-topic').value=S.selectedTopic;updateProgress();}
function updateProgress(){const chapter=Pilot.pilotProgress(S.done,S.trig),n=chapter.count;$('#progress-count').textContent=n+' of 8 lesson checkpoints';$('#progress-percent').textContent=Math.round(n/8*100)+'%';$('#progress-fill').style.width=(n/8*100)+'%';const transfer=$('#transfer-check-status');if(transfer)transfer.textContent=(Pilot.isTriangleComplete(S.trig)?'Triangle contrast complete: angle setup, angle value, length setup and value, and reasoning are all recorded.':'Triangle contrast not yet complete: finish the angle setup, angle value, length setup and value, and a nonempty explanation.')+' This optional lab does not count toward Chapter progress.';for(const el of $$('[data-check-status]')){const lesson=el.dataset.checkStatus,r=S.r['s-c'+lesson.replace('.','')];el.textContent=S.done.includes(lesson)?'Lesson check recorded'+(r?.a.at(-1)?.[2]==='correct'?' · answer checked; reasoning available for review.':' · keep working on the flagged answer.'):'Your lesson check has not been recorded.';}}
const seenSolved=new WeakSet();
const solvedObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{
 let changed=false;
 for(const e of entries){if(!e.isIntersecting||!e.target.getClientRects().length||seenSolved.has(e.target))continue;seenSolved.add(e.target);
  try{for(const expr of JSON.parse(e.target.dataset.solvedExpressions||'[]')){const sig=C.signature({expression:expr});const q=D.questions.find(q=>C.signature(q)===sig);if(q){expose(q.id,8);changed=true;}}}catch{} }
 if(changed&&!blocked)save();
},{threshold:.05}):null;
function observeSolvedExamples(id){for(const e of $$('[data-solved-expressions]',$('#'+id)))if(solvedObserver)solvedObserver.observe(e);}
const mobileMedia=window.matchMedia('(max-width: 760px)');let menuOpen=false;
function visibleMenuItems(){return $$('a,button,summary,input,select,textarea',$('#unit-sidebar')).filter(x=>{if(!x.getClientRects().length||x.disabled||x.closest('[hidden]')||getComputedStyle(x).visibility==='hidden')return false;for(let d=x.parentElement;d&&d!==$('#unit-sidebar');d=d.parentElement)if(d.tagName==='DETAILS'&&!d.open){const summary=d.querySelector(':scope > summary');if(!summary||!(summary===x||summary.contains(x)))return false;}return true;});}
function setMenuState(open,{returnFocus=false,routeFocus=false}={}){const sidebar=$('#unit-sidebar'),main=$('#main-content'),mobile=mobileMedia.matches,expanded=mobile&&open;
 if(mobile&&!expanded&&sidebar.contains(document.activeElement))$('#menu-open').focus();
 menuOpen=expanded;sidebar.inert=mobile&&!expanded;main.inert=expanded;document.body.classList.toggle('nav-open',expanded);$('#menu-open').setAttribute('aria-expanded',String(expanded));
 if(expanded){$('#reference-panel').hidden=true;visibleMenuItems().find(x=>x.tagName==='SUMMARY')?.focus();}
 else if(returnFocus&&mobile)$('#menu-open').focus();
 if(!mobile){sidebar.inert=false;main.inert=false;}
}
mobileMedia.addEventListener('change',()=>setMenuState(false,{returnFocus:mobileMedia.matches&&$('#unit-sidebar').contains(document.activeElement)}));
const referencePanel=$('#reference-panel'),referenceHead=$('#reference-panel>header'),desktopMedia=window.matchMedia('(min-width: 761px)');
function resetReferencePanel(){if(!referencePanel)return;for(const prop of ['left','top','right','bottom','width','height'])referencePanel.style.removeProperty(prop);}
function clampReferencePanel(left,top){if(!referencePanel||referencePanel.hidden||!desktopMedia.matches)return;const inset=12,topEdge=72,saveBar=48,box=referencePanel.getBoundingClientRect();const maxWidth=Math.max(280,window.innerWidth-inset*2),maxHeight=Math.max(200,window.innerHeight-topEdge-saveBar);const width=Math.min(box.width||320,maxWidth),height=Math.min(box.height||200,maxHeight);referencePanel.style.width=width+'px';referencePanel.style.height=height+'px';referencePanel.style.right='auto';referencePanel.style.bottom='auto';const x=left===undefined?box.left:left,y=top===undefined?box.top:top;referencePanel.style.left=Math.min(Math.max(x,inset),Math.max(window.innerWidth-width-inset,inset))+'px';referencePanel.style.top=Math.min(Math.max(y,topEdge),Math.max(window.innerHeight-saveBar-height,topEdge))+'px';}
if(referenceHead){referenceHead.dataset.referenceHandle='true';referenceHead.addEventListener('pointerdown',e=>{if(!desktopMedia.matches||!referencePanel||referencePanel.hidden)return;if(e.pointerType==='mouse'&&e.button!==0)return;if(e.target.closest('button,a,input,select,textarea,summary,[contenteditable]'))return;e.preventDefault();const box=referencePanel.getBoundingClientRect();const dx=e.clientX-box.left,dy=e.clientY-box.top;const move=ev=>clampReferencePanel(ev.clientX-dx,ev.clientY-dy);const stop=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',stop);document.removeEventListener('pointercancel',stop);};document.addEventListener('pointermove',move);document.addEventListener('pointerup',stop);document.addEventListener('pointercancel',stop);});}
if(referencePanel&&'ResizeObserver'in window)new ResizeObserver(()=>clampReferencePanel()).observe(referencePanel);
desktopMedia.addEventListener('change',()=>{if(desktopMedia.matches)clampReferencePanel();else resetReferencePanel();});
window.addEventListener('resize',()=>clampReferencePanel());
function route(id,focus=true){if(!allowedPages.has(id))id='u3-overview';for(const el of $$('.course-page'))el.hidden=el.id!==id;for(const a of $$('.nav-link')){const match=a.hash==='#'+id;if(match){a.setAttribute('aria-current','page');a.closest('details').open=true;}else a.removeAttribute('aria-current');}
 setMenuState(false);S.route=id;
 observeSolvedExamples(id);if(id==='u3-34')markAreaExposure();if(id==='u3-expansion-lab')markGridExposure();syncInputs();if(id==='u3-work')renderWork();if(id==='u3-practice')renderPractice();
 for(const page of $$('.course-page[data-math-checking]')){const n=$('[data-paused-note]',page);if(n)n.hidden=page.dataset.mathChecking!=='paused';}if(focus){window.scrollTo({top:0,behavior:'instant'});const h=$('#'+id+' h1');h.tabIndex=-1;h.focus({preventScroll:true});}if(!blocked)save();}
function endCheck(lesson){if(paused({lesson})){toast('This topic’s automatic check is paused. Previous work is preserved; no new completion is awarded.');return;}const qid='c'+lesson.replace('.',''),r=S.r['s-'+qid];if(!r?.a.length){toast('Try the lesson-check answer before recording the check.');return;}if(!(S.reasons[lesson]||'').trim()&&!S.paper[lesson]){toast('Add a short explanation or indicate that you kept your reasoning on paper.');$('#reason-'+lesson.replace('.','\\.'))?.focus();return;}if(!S.done.includes(lesson))S.done.push(lesson);save();updateProgress();toast('Lesson check recorded. This is not a grade or assignment submission.');}
function compact(){S.recent=S.recent.filter((id,i,a)=>S.r[id]&&!S.pins.includes(id)&&!S.active.includes(id)&&!/^s-c3[1-8]$/.test(id)&&a.indexOf(id)===i).slice(-2);
 const keep=new Set([...S.active,...S.recent,...S.pins,...Object.keys(S.r).filter(id=>/^s-c3[1-8]$/.test(id))]);for(const id of Object.keys(S.r))if(!keep.has(id)){const r=S.r[id];if(id.startsWith('s-')){S.drafts[r.q]=r.d;if(r.a.length&&!S.firsts[r.q])S.firsts[r.q]=r.a[0];}delete S.r[id];}}
async function startSet(independent=false){if(blocked)return;const topic=$('#practice-topic').value;
 let pool=topic.startsWith('core-')?D.questions.filter(q=>q.family===topic.slice(5)):authoredQuestions.filter(q=>(q.id.startsWith('p')||(topic==='mixed'&&q.id.startsWith('e')))&&(topic==='mixed'||q.lesson===topic));pool=pool.filter(q=>!paused(q));
 if(independent)pool=pool.filter(q=>!S.exposed.includes(q.id)&&!S.seen.includes(q.id));
 // Do not select the same mathematical target twice within one run.
 const unique=new Map();for(const q of pool)if(!unique.has(C.signature(q)))unique.set(C.signature(q),q);pool=[...unique.values()];
 if(pool.length<6){toast(independent?'Fewer than six unexposed problems remain in this pool. Practise with support, choose another topic, or request a teacher check.':'This pool does not have six available questions. Your current work is unchanged.');return;}
 const seed=crypto.getRandomValues(new Uint32Array(1))[0],random=(()=>{let n=seed;return()=>{n=Math.imul(1664525,n)+1013904223|0;return(n>>>0)/4294967296;};})();
 for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}let selected;try{selected=topic==='mixed'?C.selectMixed(pool,6,seed):pool.slice(0,6);}catch(e){toast(e.message);return;}
 if(S.active.length&&S.active.some(id=>!S.r[id].closed)&&!await decide('End this unfinished set and start another? Unfinished entries are kept until you explicitly end it. Two recent records remain in detail; selected work stays protected.'))return;
 for(const id of S.active){S.r[id].closed=true;S.recent.push(id);}S.active=[];
 let seq=Math.max(Date.now(),1+Math.max(0,...Object.keys(S.r).filter(id=>id.startsWith('r-')).map(id=>Number(id.slice(2)))));
 for(const q of selected){const id='r-'+seq++;S.active.push(id);rec(q.id,id);markSeen(q.id);}S.pos=0;S.runMode=independent?'independent':'learn';S.runSeed=seed;S.selectedTopic=topic;compact();save();renderPractice();}
function exerciseHtml(q,id){const eid='practice-answer';return '<div class="inline-task" data-question="'+q.id+'" data-instance="'+id+'"><p class="practice-prompt">'+esc(q.prompt)+'</p>'+(q.expression?'<div class="equation">'+pretty(q.expression)+'</div>':'')+'<div class="entry"><label for="'+eid+'">Your answer</label><input id="'+eid+'" data-answer="'+q.id+'" maxlength="160" type="text" autocomplete="off" spellcheck="false"><div class="notation-buttons" data-keypad="'+eid+'"></div><p class="small">Use x^2 for x². Changing notation does not count as mathematical help.</p><div class="live-preview" data-preview="'+eid+'" aria-hidden="true"></div></div><div class="actions"><button class="button" data-check="'+q.id+'">Check answer</button><button class="button secondary" data-hint="'+q.id+'">Give me a hint</button><button class="button quiet" data-solution="'+q.id+'">Show worked solution</button></div><div class="feedback" data-feedback="'+q.id+'" role="status" aria-live="polite" hidden></div><div data-worked="'+q.id+'" hidden></div><label for="practice-reason"><strong>A short note about my method</strong></label><textarea id="practice-reason" maxlength="120" rows="2" placeholder="Optional: record the decision you made or what you repaired."></textarea><p class="small">Up to 120 characters. Longer working can stay on paper.</p></div>';}
function renderPractice(){const root=$('#practice-root');if(!S.active.length){root.innerHTML='<p>Choose a topic and start a set. No practice set has been started yet.</p>';return;}const id=S.active[S.pos],r=S.r[id],q=Q[r.q];
 if(paused(q)){root.innerHTML='<div class="note"><h3>Automatic practice is paused for this topic</h3><p>Your existing responses and selected evidence are still kept. Continue with the written lesson or choose a different topic above.</p><p><a href="#u3-'+q.lesson.replace('.','')+'">Return to the lesson</a> · <a href="#u3-work">View retained work</a></p></div>';return;}
 root.innerHTML='<p class="practice-location">'+(S.runMode==='independent'?'Fresh check · ':'Learning practice · ')+q.lesson+' · '+D.lessons.find(l=>l.n===q.lesson).short+'</p><p><strong>Question '+(S.pos+1)+' of '+S.active.length+'</strong></p><div class="practice-meter"><div style="width:'+((S.pos+1)/S.active.length*100)+'%"></div></div>'+exerciseHtml(q,id)+'<div class="actions"><button class="button secondary" id="practice-back"'+(S.pos===0?' disabled':'')+'>Previous question</button><button class="button" id="practice-next">'+(S.pos===5?'Finish this set':'Next question')+'</button><button class="button secondary" id="pin-current">'+(S.pins.includes(id)?'Remove from selected evidence':'Keep as selected evidence')+'</button></div><p id="practice-record-meta" class="small"></p>';
 keypad();window.MathInputEnhancement?.enhance();const task=$('.inline-task',root);$('[data-answer]',task).value=r.d;$('#practice-reason').value=r.reason;previewInput($('[data-answer]',task));draftFeedback(task,r);if(r.s&2){$('[data-worked]',task).innerHTML=solutionHtml(q);$('[data-worked]',task).hidden=false;}updateRunMeta();}
function updateRunMeta(){const node=$('#practice-record-meta');if(!node||!S.active.length)return;const r=S.r[S.active[S.pos]];node.textContent=r.n+' submitted attempt'+(r.n===1?'':'s')+' · '+supports(r.s)+'. Up to four attempts are retained; you can keep trying.';}
function nextQuestion(delta){if(!S.active.length)return;const r=S.r[S.active[S.pos]];if(delta>0)r.closed=true;if(S.pos+delta>=S.active.length){save();toast('Set finished. Review your work or start another set.');route('u3-work');location.hash='u3-work';return;}S.pos=Math.max(0,S.pos+delta);save();renderPractice();$('#practice-answer')?.focus();}
async function togglePin(id){if(blocked||!S.r[id])return;if(S.pins.includes(id)){if(!await decide('Remove this record from protected evidence? Its ordinary detail may later roll into the disclosed summary window.'))return;S.pins=S.pins.filter(x=>x!==id);S.recent.push(id);}else{if(S.pins.length>=4){toast('Four selected places are full. Practice continues. Review and explicitly replace a selected record when ready.');return;}S.pins.push(id);}compact();save();if(S.route==='u3-work')renderWork();else renderPractice();}
function writtenRecord(r){return !!r&&(r.a.length>0||r.d.trim().length>0||r.reason.trim().length>0);}
function textReport(){const chapter=Pilot.pilotProgress(S.done,S.trig);const lines=[D.title,'Process report — retained evidence, not a complete history','This report is not an assignment submission.','Chapter checkpoints recorded: '+chapter.count+' of 8 ('+Pilot.COMPLETION_LESSONS.map(n=>'3.'+n.slice(2)+': '+(chapter.lessons.includes(n)?'recorded':'not recorded')).join('; ')+'). The triangle contrast is an optional lab and is not counted here.',''];
 function append(r,label,reason){if(!writtenRecord(r))return;const q=window.MathCatalogs.catalogs[r.catalog||window.MathCatalogs.current]?.questions[r.q]||Q[r.q];lines.push(label,q.prompt,q.expression||'');for(const a of r.a)lines.push('Attempt '+a[0]+': '+a[1]+' | '+outcome(a[2])+' | '+supports(a[3])+' | result version: '+(a[4]?.engine||'legacy/unknown'));if(r.d!==r.a.at(-1)?.[1])lines.push('Current draft (not checked): '+r.d);if(reason||r.reason)lines.push('My reasoning (retained for teacher review, not automatically assessed): '+(reason||r.reason));lines.push('');}
 for(const l of D.lessons)append(S.r['s-c'+l.n.replace('.','')],l.n+' '+l.title,S.reasons[l.n]||(S.paper[l.n]?'Kept on paper; not automatically assessed.':''));
 for(const[id,r]of Object.entries(S.r))if(id.startsWith('s-')&&!r.q.startsWith('c'))append(r,'RETAINED LESSON / UNIT REVIEW · '+Q[r.q].lesson);
 for(const id of S.pins)append(S.r[id],'SELECTED PRACTICE · '+Q[S.r[id].q].lesson);
 if(S.notes.error)lines.push('Error analysis: '+S.notes.error);if(S.notes.help)lines.push('Help request: '+S.notes.help);
 lines.push('Ordinary practice summary: '+S.summary.attempts+' submitted attempts; '+S.summary.correct+' correct submitted responses. '+S.summary.supported+' of these used in-course mathematical support before that submission.','This is a learning record, not a grade. Full work on paper can accompany the report. Unselected active/recent practice details are visible in All My Work but are not copied into this report.');for(const [qid,draft] of Object.entries(S.drafts)){if(S.r['s-'+qid]||!draft.trim())continue;const q=Q[qid],first=S.firsts[qid];lines.push('',q.lesson+' · retained lesson writing',q.prompt,q.expression||'');if(first)lines.push('First submitted response: '+first[1]+' · '+outcome(first[2])+' · '+supports(first[3])+' · result version: '+(first[4]?.engine||'legacy/unknown'));lines.push('Current retained draft (not rechecked): '+draft,'Intermediate detail has rolled out of the recent window; this is not a full history.');}
 const T=S.trig;if(T.angleRaw||T.lengthRaw||T.reason||T.setupAttempts?.length){lines.push('','Optional triangle contrast (not counted toward Chapter progress)','Triangle ABC, right angle B; AB = 12 m, BC = 6 m, reference A.','Chosen side: '+(T.side||'not selected')+'; chosen ratio: '+(T.ratio||'not selected'),'Angle entry: '+(T.angleRaw||'none')+'; value status: '+(T.angle||'not checked'),'Second triangle: reference 30 degrees, hypotenuse 10 m.','Chosen ratio: '+(T.length||'not selected')+'; length: '+(T.lengthRaw||'none'),'Reasoning (not automatically graded): '+(T.reason||'not recorded'));for(const [name,ar]of [['Setup',T.setupAttempts||[]],['Angle',T.aa||[]],['Length',T.la||[]]])for(const a of ar)lines.push(name+' attempt '+a[0]+': '+a[1]+' · '+a[2]+' · '+supports(a[3])+' · '+(a[4]?'checker '+a[4].checker+'; setup '+a[4].setup+'; relation '+a[4].relationship+'; value '+a[4].value.status:'legacy support chronology uncertain; not regraded'));if(T.angleRaw&&T.angleRaw!==T.aa?.at(-1)?.[1])lines.push('Current angle draft (not checked): '+T.angleRaw);if(T.lengthRaw&&T.lengthRaw!==T.la?.at(-1)?.[1])lines.push('Current length draft (not checked): '+T.lengthRaw);}
 for(const [skill,counts]of Object.entries(S.skills||{}))lines.push('Skill '+skill+': '+counts.attempts+' submissions; '+counts.correct+' correct; '+counts.supported+' correct with in-course mathematical support.');
 if(S.legacySummary?.attempts)lines.push('Legacy unclassified totals: '+S.legacySummary.attempts+' submissions. Earlier data cannot identify a skill reliably; these totals are not assigned to a skill.');
 lines.push('Retention: first plus latest three mathematical submissions per retained record, not a limit on attempts. One six-question active run, four protected selections, two ordinary recent details; fixed lesson writing and checks are retained separately. Current explanations are teacher-review evidence, not automatically assessed.');
 return lines.join('\n');}
function recordHtml(r,label,id,pin){if(!r)return'';const q=window.MathCatalogs.catalogs[r.catalog||window.MathCatalogs.current]?.questions[r.q]||Q[r.q];return '<article class="report-item"><h3>'+esc(label)+' · '+esc(q.lesson)+'</h3><p>'+esc(q.prompt)+'</p>'+(q.expression?'<div class="equation">'+pretty(q.expression)+'</div>':'')+r.a.map(a=>'<blockquote><strong>Attempt '+a[0]+':</strong> '+esc(a[1])+'<br><span class="small">'+esc(outcome(a[2]))+' · '+esc(supports(a[3]))+' · '+esc(a[4]?.engine||'legacy/unknown')+'</span></blockquote>').join('')+(r.d!==r.a.at(-1)?.[1]?'<p>Current draft (not checked): <span class="inline-math">'+pretty(r.d)+'</span></p>':'')+(r.reason?'<p><strong>My note:</strong> '+esc(r.reason)+'</p>':'')+(pin?'<button class="button secondary screen-only" data-toggle-pin="'+id+'">'+(S.pins.includes(id)?'Remove from selected evidence':'Keep as selected evidence')+'</button>':'')+'</article>';}
function renderWork(){let s='';for(const l of D.lessons){const r=S.r['s-c'+l.n.replace('.','')];if(!writtenRecord(r))continue;s+=recordHtml(r,l.short,'s-c'+l.n.replace('.',''),false);s+='<p><strong>My reasoning:</strong> '+esc(S.reasons[l.n]||(S.paper[l.n]?'Kept on paper; not automatically assessed.':'Not supplied yet.'))+'</p>';}
 if(!s)s='<p>No lesson-check work has been entered yet. Your guided practice and current practice set appear below when you work on them.</p>';
 const guided=Object.entries(S.r).filter(([id,r])=>id.startsWith('s-')&&!r.q.startsWith('c')&&writtenRecord(r));
 if(guided.length)s+='<details><summary>Guided work, error analysis & unit review · '+guided.length+' records</summary>'+guided.map(([id,r])=>recordHtml(r,r.q.startsWith('i')?'Unit review':'Lesson work',id,false)).join('')+'</details>';
 if(S.pins.length)s+='<h2>Selected practice</h2>'+S.pins.map(id=>recordHtml(S.r[id],'Protected selection',id,true)).join('');
 const active=S.active.filter(id=>!S.pins.includes(id)&&writtenRecord(S.r[id]));if(active.length)s+='<details open><summary>Current practice set · '+active.length+' worked questions</summary>'+active.map(id=>recordHtml(S.r[id],'Current practice',id,true)).join('')+'</details>';
 if(S.recent.length)s+='<details class="screen-only"><summary>Recent practice · limited detail window</summary>'+S.recent.map(id=>recordHtml(S.r[id],'Recent practice',id,true)).join('')+'</details>';
 const archived=Object.entries(S.drafts).filter(([qid,draft])=>!S.r['s-'+qid]&&draft.trim());if(archived.length)s+='<details><summary>Retained lesson writing · earlier detail window</summary>'+archived.map(([qid,draft])=>'<article class="work-record"><h3>'+esc(Q[qid].lesson+' · '+Q[qid].prompt)+'</h3><p>'+pretty(Q[qid].expression||'')+'</p><p>Current entry: '+esc(draft)+'</p>'+(S.firsts[qid]?'<p>First submitted response: '+esc(S.firsts[qid][1])+'</p>':'')+'<p class="small">Other intermediate detail has rolled into the summary.</p></article>').join('')+'</details>';
 if(S.trig.angleRaw||S.trig.lengthRaw||S.trig.reason||S.trig.setupAttempts?.length)s+='<details><summary>Triangle contrast · setup and value evidence</summary><p>Chosen side: '+esc(S.trig.side||'none')+'; ratio: '+esc(S.trig.ratio||'none')+'</p><p>Angle: '+esc(S.trig.angleRaw||'none')+' · '+esc(S.trig.angle||'not checked')+'</p><p>Unknown side setup: '+esc(S.trig.length||'none')+'; length: '+esc(S.trig.lengthRaw||'none')+'</p><p>Explanation (not automatically graded): '+esc(S.trig.reason||'none')+'</p></details>';
 s+='<details data-repair-report><summary>Complete retained report, skill summaries and support history</summary><pre class=report-text>'+esc(textReport())+'</pre></details>';$('#work-list').innerHTML=s;}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function printMode(mode){document.body.classList.remove('print-report','print-lesson');if(mode==='report'){renderWork();document.body.classList.add('print-report');printDisclosureState=$$('#u3-work details').map(d=>[d,d.open]);for(const[d]of printDisclosureState)d.open=true;}if(mode==='lesson'){document.body.classList.add('print-lesson');$$('.print-target').forEach(x=>x.classList.remove('print-target'));$('#'+S.route)?.classList.add('print-target');}window.print();}
function reportDownload(){const text=textReport();download('Math10C_Unit3_Process_Report.html','<!doctype html><html lang="en"><meta charset="utf-8"><title>Math 10C process report</title><style>body{max-width:850px;margin:40px auto;padding:0 20px;font:17px/1.6 Arial}pre{white-space:pre-wrap;font:inherit}h1{color:#154212}</style><h1>Math 10C — My process report</h1><pre>'+esc(text)+'</pre></html>','text/html');toast('Report downloaded, not submitted.');}
function area(){const p=Number($('[data-area-p]').value),q=Number($('[data-area-q]').value);$('[data-p-label]').textContent=p;$('[data-q-label]').textContent=q;$('[data-area-top]').textContent=q;$('[data-cell-q]').textContent=q+'x';$('[data-cell-p]').textContent=p+'x';$('[data-cell-c]').textContent=p*q;$('[data-area-equation]').innerHTML=pretty('(x + '+p+')(x + '+q+') = x^2 + '+(p+q)+'x + '+(p*q));$('[data-area-summary]').textContent='The x strips add to '+(p+q)+'x. The corner has area '+(p*q)+'.';$('[data-area-grid]').setAttribute('aria-label','Four rectangular regions: x squared, '+q+'x, '+p+'x, and '+(p*q)+'. Rows have heights x and '+p+'; columns have widths x and '+q+'.');}
function markExpressionExposure(expression){try{const sig=C.signature({expression}),q=D.questions.find(q=>C.signature(q)===sig);if(q){expose(q.id,8);save();}}catch{}}
function markAreaExposure(){const p=Number($('[data-area-p]').value),q=Number($('[data-area-q]').value);markExpressionExposure('(x+'+p+')(x+'+q+')');}
function markGridExposure(){const v=Object.fromEntries($$('[data-grid-coef]').map(e=>[e.dataset.gridCoef,Number(e.value)]));markExpressionExposure('('+v.a+'x+('+v.b+'))('+v.c+'x+('+v.d+'))');}
function numberLab(){const a=Number($('#number-a').value),b=Number($('#number-b').value),o=$('#number-output');o.hidden=false;if(!Number.isInteger(a)||!Number.isInteger(b)||a<2||b<2||a>10000||b>10000){o.textContent='Enter whole numbers from 2 to 10,000.';return;}const g=M.gcd(a,b),sq=Math.sqrt(a),cb=Math.round(Math.cbrt(a));o.innerHTML='<p>'+a+' = '+M.primes(a).join(' × ')+'</p><p>'+b+' = '+M.primes(b).join(' × ')+'</p><p><strong>GCF = '+g+'; LCM = '+(a/g*b)+'.</strong></p><p>'+a+(Number.isInteger(sq)?' is a perfect square: √'+a+' = '+sq: ' is not a perfect square; its square root lies between '+Math.floor(sq)+' and '+Math.ceil(sq))+'.</p><p>'+a+(cb**3===a?' is a perfect cube: ∛'+a+' = '+cb:' is not a perfect cube')+'.</p>';}
function grid(){const v=Object.fromEntries($$('[data-grid-coef]').map(e=>[e.dataset.gridCoef,Number(e.value)]));if(Object.values(v).some(n=>!Number.isInteger(n)||n<-9||n>9))return;const{a,b,c,d}=v;const expr='('+a+'x'+(b<0?b:'+'+b)+')('+c+'x'+(d<0?d:'+'+d)+')';$('#expansion-grid').innerHTML='<div class="equation">'+pretty(expr)+'</div><div class="table-wrap"><table><tr><th>×</th><th>'+c+'x</th><th>'+d+'</th></tr><tr><th>'+a+'x</th><td>'+a*c+'x²</td><td>'+a*d+'x</td></tr><tr><th>'+b+'</th><td>'+b*c+'x</td><td>'+b*d+'</td></tr></table></div><p>Combine the middle products: '+(a*d)+'x + ('+(b*c)+')x = '+(a*d+b*c)+'x.</p><div class="equation">'+pretty(M.fmt(M.parse(expr).p))+'</div>';}
function freezeBlocked(){if(!blocked)return;for(const e of $$('input,textarea,select'))e.disabled=true;for(const e of $$('[data-check],[data-hint],[data-solution],[data-record],#start-practice'))e.disabled=true;}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button,a,[data-toggle-pin]');if(!b)return;
 if(b.hasAttribute('data-repair-return')){const task=b.closest('.inline-task');repairReturn={route:S.route,input:$('[data-answer]',task)?.id};$('#return-to-problem').hidden=false;}
 if(b.id==='return-to-problem'&&repairReturn){returnFocusId=repairReturn.input;route(repairReturn.route,false);if(location.hash.slice(1)===repairReturn.route){document.getElementById(returnFocusId)?.focus();returnFocusId=null;}else location.hash=repairReturn.route;return;}
 if(b.id==='download-legacy-preview'){const raw=localStorage.getItem('math10c-unit3-pilot:review:v1');if(raw)download('Math10C_earlier_preview_work.json',raw,'application/json');return;}
 if(b.dataset.recoveryDownload!==undefined){const branch=saver.inspect().branches[Number(b.dataset.recoveryDownload)];if(branch)download('Math10C_Recovery_'+b.dataset.recoveryDownload+'.json',branch.raw,'application/json');return;}
 if(b.dataset.recoveryChoose!==undefined){const branch=saver.inspect().branches[Number(b.dataset.recoveryChoose)];if(!branch||!await decide('Use this validated version? Both original versions stay in their recovery records; they will not be merged automatically.'))return;try{saver.choose(branch.raw);syncSaving();syncInputs();syncTrig();$('#recovery-panel').hidden=false;route(S.route);}catch(e){message(e.message,true);}return;}
 if(b.id==='release-writer'){if(await decide('Release editing in this tab? Its unsaved draft remains here. The other tab must explicitly reopen or request ownership.'))await saver.releaseOwnership();syncSaving();return;}
 if(b.id==='request-writer'){await saver.requestOwnership();syncSaving();return;}
 if(b.dataset.practiceLesson){S.selectedTopic=b.dataset.practiceLesson;$('#practice-topic').value=S.selectedTopic;save();}
 if(b.dataset.check){submitTask(b.closest('.inline-task'));return;}
 if(b.dataset.hint||b.dataset.solution){hintTask(b.closest('.inline-task'),!!b.dataset.solution);return;}
 if(b.dataset.insert!==undefined){const input=document.getElementById(b.dataset.input),st=input.selectionStart??input.value.length,end=input.selectionEnd??st;if(input.value.length-(end-st)+b.dataset.insert.length>160){toast('This field holds up to 160 characters.');return;}input.setRangeText(b.dataset.insert,st,end,'end');input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));return;}
 if(b.dataset.record){endCheck(b.dataset.record);return;}
 if(b.dataset.togglePin){togglePin(b.dataset.togglePin);return;}
 if(b.hasAttribute('data-print-lesson')){printMode('lesson');return;}
 if(b.dataset.video){const id=b.dataset.video;if(!/^[A-Za-z0-9_-]{11}$/.test(id))return;const stage=b.closest('.video-stage');stage.style.padding='0';const f=document.createElement('iframe');f.title='Optional mathematics video explanation';f.src='https://www.youtube-nocookie.com/embed/'+id;f.allow='fullscreen; picture-in-picture';f.referrerPolicy='strict-origin-when-cross-origin';stage.replaceChildren(f);return;}
 switch(b.id){case'save-retry':if(!managed)await saver.retry();break;case'menu-open':setMenuState(!menuOpen,{returnFocus:menuOpen});break;case'sidebar-toggle':document.body.classList.toggle('sidebar-collapsed');b.setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-collapsed')));break;
 case'reference-open':setMenuState(false);$('#reference-panel').hidden=false;clampReferencePanel();$('#reference-close').focus();break;case'reference-close':$('#reference-panel').hidden=true;$('#reference-open').focus();break;
 case'start-practice':await startSet(false);break;case'start-independent':await startSet(true);break;case'practice-next':nextQuestion(1);break;case'practice-back':nextQuestion(-1);break;case'pin-current':togglePin(S.active[S.pos]);break;
 case'number-calc':numberLab();break;case'expand-tool':{try{const sig='poly:'+JSON.stringify(Object.entries(M.parse($('#algebra-tool').value).p).sort(([a],[b])=>a.localeCompare(b)));const match=D.questions.find(q=>C.signature(q)===sig);if(match){expose(match.id,2);save();}}catch{}const o=$('#algebra-output');o.hidden=false;try{o.innerHTML='<p>The expanded, simplified expression is:</p><div class="equation">'+pretty(M.fmt(M.parse($('#algebra-tool').value).p))+'</div><p class="small">Compare this with your partial products. This result is not evidence of an independent attempt.</p>';}catch(err){o.textContent=err.message;}break;}
 case'report-download':reportDownload();break;case'report-copy':try{await navigator.clipboard.writeText(textReport());toast('Report copied, not submitted.');}catch{download('Math10C_Unit3_Process_Report.txt',textReport());toast('Clipboard unavailable; a text report was downloaded instead.');}break;
 case'report-print':printMode('report');break;case'print-unit':printMode('unit');break;
 case'backup-download':download('Math10C_Unit3_Work_Backup.json',JSON.stringify(snapshot()),'application/json');toast('Backup downloaded, not submitted.');break;
 }
});
document.addEventListener('input',e=>{const el=e.target;if(blocked)return;if(el.matches('[data-structured-part]')){const t=el.closest('.inline-task'),hidden=$('[data-answer]',t);hidden.value=getRaw(t);hidden.dispatchEvent(new Event('input',{bubbles:true}));return;}if(el.matches('[data-answer]')){const task=el.closest('.inline-task'),qid=el.dataset.answer,r=rec(qid,task.dataset.instance);r.d=el.value;if(!task.dataset.instance)S.drafts[qid]=el.value;previewInput(el);draftFeedback(task,r);save();}
 if(el.matches('[data-reason]')){S.reasons[el.dataset.reason]=el.value;save();}
 if(el.matches('[data-note]')){S.notes[el.dataset.note]=el.value;save();}
 if(el.id==='practice-reason'&&S.active.length){S.r[S.active[S.pos]].reason=el.value;save();}
 if(el.hasAttribute('data-area-p')||el.hasAttribute('data-area-q')){area();markAreaExposure();}if(el.hasAttribute('data-grid-coef')){grid();markGridExposure();}
});
document.addEventListener('change',async e=>{const el=e.target;if(blocked&&el.id!=='backup-file')return;if(el.matches('[data-paper]')){S.paper[el.dataset.paper]=el.checked;save();}if(el.id==='backup-file'&&el.files[0]){try{if(el.files[0].size>200000)throw Error('The backup is too large.');const other=unpack(await el.files[0].text());if(!await decide('Replace the open browser work with this verified backup? Download the current version first to keep both.'))return;saver.choose(pack(other));syncSaving();syncInputs();route(S.route);toast('Validated backup selected; no assignment was submitted.');}catch(err){toast('Backup not restored: '+err.message);}el.value='';}});
$('#menu-scrim').addEventListener('click',()=>setMenuState(false,{returnFocus:true}));
document.addEventListener('keydown',e=>{if(e.key==='Tab'&&menuOpen&&!document.querySelector('dialog[open]')){const f=visibleMenuItems(),first=f[0],last=f.at(-1);if(e.shiftKey&&(document.activeElement===first||!$('#unit-sidebar').contains(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 if(e.key==='Escape'&&!e.target.closest('dialog')){if(!$('#reference-panel').hidden){$('#reference-panel').hidden=true;$('#reference-open').focus();return;}if(menuOpen){setMenuState(false,{returnFocus:true});return;}}
 if(e.key==='Enter'&&e.target.matches('[data-answer],[data-structured-part]')){e.preventDefault();submitTask(e.target.closest('.inline-task'));}});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(allowedPages.has(id)){route(id,!returnFocusId);if(returnFocusId){document.getElementById(returnFocusId)?.focus();returnFocusId=null;}}else if(knownPages.has(id)){location.hash='u3-overview';}else if(id.startsWith('check-'))document.getElementById(id)?.scrollIntoView();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('canvas-helper:scorm-status',e=>{saver.accept(e.detail);syncSaving();});
window.addEventListener('storage',e=>saver.observeStorage(e));
window.addEventListener('pagehide',()=>saver.teardown());
window.addEventListener('pageshow',e=>{if(e.persisted){setWritable(false);message('Reopen this activity to safely reacquire editing after returning to a cached page.',true);}});
window.addEventListener('afterprint',()=>{document.body.classList.remove('print-report','print-lesson');for(const[d,open]of printDisclosureState)d.open=open;printDisclosureState=[];});
(async()=>{setMenuState(false);await connect();keypad();syncInputs();syncTrig();area();grid();let id=location.hash.slice(1);if(!allowedPages.has(id))id=S.route;route(id,false);freezeBlocked();if(D.helpUrl&&/^https:\/\//.test(D.helpUrl)){const a=document.createElement('a');a.className='button';a.href=D.helpUrl;a.textContent='Open the course help route';a.rel='noopener noreferrer';a.target='_blank';$('#help-link').append(a);}})();

// Trig records keep setup and value distinct, and snapshot support before feedback.
const TRIG_VERSION='unit3-trig-2';
function trigSupport(kind){return S.trig[kind+'Support']??(S.trig.support||0);}
function trigSetup(kind){const t=S.trig;if(kind==='angle')return{relationship:t.ratio||'',status:!t.ratio?'not_attempted':t.side==='BC'&&t.adjacent==='AB'&&t.hypotenuse==='AC'&&t.ratio==='tan'?'correct':'incorrect'};return{relationship:t.length||'',status:!t.length?'not_attempted':t.length==='sin'?'correct':'incorrect'};}
function retainTrig(kind,raw,result,setup,supportBefore){if(result.status==='input')return;const key=kind==='angle'?'aa':'la',count=kind==='angle'?'an':'ln';S.trig[count]=Math.min(Number.MAX_SAFE_INTEGER,(S.trig[count]||0)+1);const rows=S.trig[key]||[],p={checker:TRIG_VERSION,instance:kind==='angle'?'abc-12-6-angle-a-v1':'right-30deg-h10-opposite-v1',relationship:setup.relationship,setup:setup.status,value:{status:result.status,detail:result.detail}};rows.push([S.trig[count],raw,result.status,supportBefore,p]);S.trig[key]=rows.length>4?[rows[0],...rows.slice(-3)]:rows;State.recordSummary(S,'trig-'+kind,result.status,supportBefore);}
function retainSetup(kind,setup,supportBefore){const t=S.trig;t.setupCount=Math.min(Number.MAX_SAFE_INTEGER,(t.setupCount||0)+1);const rows=t.setupAttempts||[];rows.push([t.setupCount,setup.relationship,setup.status==='correct'?'correct':'incorrect',supportBefore,{checker:TRIG_VERSION,instance:kind==='angle'?'abc-12-6-angle-a-v1':'right-30deg-h10-opposite-v1',relationship:setup.relationship,setup:setup.status,value:{status:'not_attempted'}}]);t.setupAttempts=rows.length>4?[rows[0],...rows.slice(-3)]:rows;State.recordSummary(S,'trig-setup',setup.status,supportBefore);}
function applyTrigFeedback(kind,result,setup){if(['incorrect','precision','different_requested_unit','missing_unit'].includes(result.status)||setup.status==='incorrect')S.trig[kind+'Support']=trigSupport(kind)|4;}
function trigFeedback(id,result){const p=$(id);p.hidden=false;p.dataset.status=result.status;p.textContent=result.detail;}
function syncTrig(){const T=S.trig||{};for(const [id,key]of [['trig-side','side'],['trig-adjacent','adjacent'],['trig-hypotenuse','hypotenuse'],['trig-ratio','ratio'],['trig-angle','angleRaw'],['trig-length','lengthRaw'],['trig-length-ratio','length'],['trig-reason','reason']])$('#'+id).value=T[key]||'';const angle=(T.rotation||0)*90;$('#trig-shape').setAttribute('transform','rotate('+angle+' 180 120)');for(const text of $$('#trig-shape text'))text.setAttribute('transform','rotate('+(-angle)+' '+text.getAttribute('x')+' '+text.getAttribute('y')+')');
 for(const [kind,key,raw]of [['angle','aa','angleRaw'],['length','la','lengthRaw']]){const a=T[key]?.at(-1);if(T[raw])trigFeedback('#trig-'+kind+'-feedback',a&&a[1]===T[raw]?{status:a[2],detail:'Retained response '+a[1]+': '+(a[4]?.value?.detail||'Legacy result; chronology is uncertain and was not regraded.')+' Setup: '+(a[4]?.setup||'legacy unknown')}:{status:'ungraded',detail:'Current draft has not been checked.'});}}
document.addEventListener('toggle',e=>{if(e.target.matches('[data-support-q]')&&e.target.open&&!blocked){expose(e.target.dataset.supportQ,2);save();}if(e.target.id==='trig-angle-support'&&e.target.open&&!blocked){S.trig.angleSupport=trigSupport('angle')|2;save();}},true);
document.addEventListener('input',e=>{const map={'trig-angle':'angleRaw','trig-length':'lengthRaw','trig-reason':'reason'};if(map[e.target.id]&&!blocked){S.trig[map[e.target.id]]=e.target.value;if(e.target.id!=='trig-reason')trigFeedback('#'+(e.target.id==='trig-angle'?'trig-angle':'trig-length')+'-feedback',{status:'ungraded',detail:'Current draft has not been checked.'});save();}});
document.addEventListener('change',e=>{const map={'trig-side':'side','trig-adjacent':'adjacent','trig-hypotenuse':'hypotenuse','trig-ratio':'ratio','trig-length-ratio':'length'};if(map[e.target.id]&&!blocked){S.trig[map[e.target.id]]=e.target.value;S.trig.setupSaved=false;trigFeedback('#trig-setup-feedback',{status:'ungraded',detail:'Current setup has not been checked.'});save();}});
document.addEventListener('click',e=>{if(blocked)return;const id=e.target.closest('button')?.id;
 if(id==='trig-rotate'){S.trig.rotation=((S.trig.rotation||0)+1)%4;syncTrig();save();}
 if(id==='trig-setup'){const setup=trigSetup('angle'),before=trigSupport('angle');if(!S.trig.side||!S.trig.adjacent||!S.trig.hypotenuse||!S.trig.ratio){trigFeedback('#trig-setup-feedback',{status:'input',detail:'Choose all three sides and a ratio before checking the setup.'});return;}retainSetup('angle',setup,before);S.trig.setupSaved=setup.status==='correct';trigFeedback('#trig-setup-feedback',{status:setup.status,detail:setup.status==='correct'?'The three sides and tangent relationship fit. Now calculate the angle.':'Use the marked angle as reference. Check the side across from it, the other leg, and the side opposite the right angle.'});applyTrigFeedback('angle',{status:'not_attempted'},setup);save();}
 if(id==='trig-angle-check'||id==='trig-length-check'){const kind=id==='trig-angle-check'?'angle':'length',raw=S.trig[kind+'Raw']||'',before=trigSupport(kind),setup=trigSetup(kind);
  if(setup.status==='not_attempted'||(kind==='angle'&&(!S.trig.side||!S.trig.adjacent||!S.trig.hypotenuse))){trigFeedback('#trig-'+kind+'-feedback',{status:'input',detail:'Select the requested sides and relationship before checking the value.'});return;}
  const result=C.trig(raw,kind==='length'?{kind:'length'}:{});
  if(result.status==='input'){if(!raw.trim())retainSetup(kind,setup,before);trigFeedback('#trig-'+kind+'-feedback',{status:'input',detail:'The numeric entry needs repair. '+(raw.trim()?'No mathematical submission was counted.':'Only your setup was recorded; no numeric attempt was counted.')});if(!raw.trim())applyTrigFeedback(kind,{status:'not_attempted'},setup);save();return;}
  retainTrig(kind,raw,result,setup,before);S.trig[kind==='angle'?'angle':'lengthStatus']=result.status;
  trigFeedback('#trig-'+kind+'-feedback',{status:result.status,detail:result.detail+' Setup: '+(setup.status==='correct'?'the selected relationship fits.':'the relationship needs repair; a correct number does not replace it.')});applyTrigFeedback(kind,result,setup);save();}
});
// Local diagnostic seam includes this tab’s work for explicit testing/recovery. No external collection.
window.Unit3Debug={snapshot,unpack,pack,question:id=>Q[id],stateChars:()=>JSON.stringify(snapshot()).length,version:D.version,ready:()=>!blocked,showMenu:setMenuState,saving:()=>saver.inspect(),retry:()=>saver.retry(),releaseWriter:()=>saver.releaseOwnership(),requestWriter:()=>saver.requestOwnership(),questions:()=>Object.keys(Q),expose:(id,mask)=>{expose(id,mask);save();},check:C.check,trig:C.trig,pilot:Pilot,knownPages:()=>[...knownPages],activePages:()=>[...allowedPages],triangleComplete:()=>Pilot.isTriangleComplete(S.trig)};
})();
