const courses = [
  { id: "biology30-a", title: "Biology 30 — Unit A (Pilot 2)", shortTitle: "Bio 30 A · Pilot 2", category: "biology30", area: "Biology 30", status: "Teacher review", description: "Nervous and endocrine systems pilot for teacher review.", url: "./biology30-a/index.html", version: "Pilot 2" },
  { id: "biology30-b", title: "Biology 30 — Unit B", shortTitle: "Bio 30 B", category: "biology30", area: "Biology 30", status: "Teacher review", description: "Reproduction and development unit build.", url: "./biology30-b/index.html", version: "Review build" },
  { id: "biology30-c", title: "Biology 30 — Unit C", shortTitle: "Bio 30 C", category: "biology30", area: "Biology 30", status: "Teacher review", description: "Cell division, genetics, and molecular biology unit build.", url: "./biology30-c/index.html", version: "Review build" },
  { id: "biology30-d", title: "Biology 30 — Unit D", shortTitle: "Bio 30 D", category: "biology30", area: "Biology 30", status: "Teacher review", description: "Population and community dynamics unit build.", url: "./biology30-d/index.html", version: "Review build" },
  { id: "biology20-a", title: "Biology 20 — Unit A", shortTitle: "Bio 20 A", category: "biology20", area: "Biology 20", status: "Teacher review", description: "Energy and matter exchange in the biosphere unit build.", url: "./biology20-a/index.html", version: "Review build" }
];
const state = { activeCourseId: "biology30-a", activeFilter: "all", activeDevice: "desktop" };
const q = (s) => document.querySelector(s), qa = (s) => [...document.querySelectorAll(s)];
const el = { rail:q("#courseRail"), desktop:q("#desktopFrame"), tablet:q("#tabletFrame"), mobile:q("#mobileFrame"), desktopTitle:q("#desktopTitle"), tabletTitle:q("#tabletTitle"), phoneTitle:q("#phoneTitle"), selectedTitle:q("#selectedTitle"), description:q("#selectedDescription"), area:q("#selectedArea"), status:q("#selectedStatus"), category:q("#selectedCategory"), host:q("#selectedHost"), version:q("#selectedVersion"), open:q("#openCourse"), copy:q("#copyLink"), prev:q("#previousCourse"), next:q("#nextCourse"), devices:q("#devicesShowcase"), menu:q("#siteMenu"), menuToggle:q("#siteMenuToggle") };
const filters = () => state.activeFilter === "all" ? courses : courses.filter((c) => c.category === state.activeFilter);
const active = () => courses.find((c) => c.id === state.activeCourseId) || courses[0];
function renderRail(){ el.rail.innerHTML=filters().map(c=>`<button class="course-selector${c.id===state.activeCourseId?" is-active":""}" type="button" data-course-id="${c.id}" aria-label="Preview ${c.title}"><span class="course-button" aria-hidden="true"></span><span class="course-title">${c.shortTitle}</span></button>`).join(""); }
function selectCourse(id){const c=courses.find(x=>x.id===id);if(!c)return;state.activeCourseId=id;[el.desktop,el.tablet,el.mobile].forEach(f=>f.src=c.url);[el.desktopTitle,el.tabletTitle,el.phoneTitle,el.selectedTitle].forEach(x=>x.textContent=c.title);el.description.textContent=c.description;el.area.textContent=c.area;el.status.textContent=c.status;el.category.textContent=c.area;el.host.textContent=new URL(c.url,location.href).pathname.replace(/^\//,"");el.version.textContent=c.version;el.open.href=c.url;renderRail();qa(".filter-button").forEach(b=>b.classList.toggle("is-active",b.dataset.filter===state.activeFilter));history.replaceState(null,"",`#${id}`);}
function setFilter(f){state.activeFilter=f;const list=filters();if(!list.some(c=>c.id===state.activeCourseId))state.activeCourseId=list[0]?.id||courses[0].id;selectCourse(state.activeCourseId);}
function setDevice(d){state.activeDevice=d;el.devices.dataset.deviceMode=d;qa(".device-button").forEach(b=>b.classList.toggle("is-active",b.dataset.device===d));}
function move(n){const list=filters(),i=list.findIndex(c=>c.id===state.activeCourseId);selectCourse(list[(i+n+list.length)%list.length].id);}
el.rail.addEventListener("click",e=>{const b=e.target.closest(".course-selector");if(b)selectCourse(b.dataset.courseId)});el.prev.addEventListener("click",()=>move(-1));el.next.addEventListener("click",()=>move(1));qa(".filter-button").forEach(b=>b.addEventListener("click",()=>setFilter(b.dataset.filter)));qa(".device-button").forEach(b=>b.addEventListener("click",()=>setDevice(b.dataset.device)));el.menuToggle?.addEventListener("click",()=>{const open=el.menu.hidden;el.menu.hidden=!open;el.menuToggle.setAttribute("aria-expanded",String(open));});el.copy.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(new URL(active().url,location.href).href);el.copy.textContent="Copied";setTimeout(()=>el.copy.textContent="Copy preview link",1600)}catch{el.copy.textContent=active().url}});
const initial=location.hash.slice(1);if(courses.some(c=>c.id===initial))state.activeCourseId=initial;renderRail();setDevice("desktop");selectCourse(state.activeCourseId);
