module.exports={
'ce1-05':{
foundation:[
['h3','The courses look right. Will the plan actually work?'],
['p','A student can list all the courses that seem useful for a career and still have a plan that cannot be followed. A later course may require an earlier one, a school may offer it only in a particular term, or a portfolio may be due before the course that helps produce it finishes. How do you turn a list of useful preparation into a route that fits the actual time available?'],
['h3','Start with the conditions at the destination'],
['p','A prerequisite is a step that must be completed before another course or entry point. Required preparation is a stated condition; recommended preparation may help without being compulsory. If a program requires two pieces of work, a particular school course may be one way to create them. We need to distinguish the evidence the program asks for from the route used to produce it.'],
['p','A portfolio is a selected collection of work with explanations of what it demonstrates. Some programs set a submission deadline for that evidence as well as a later date for completing a school course. Those are different points on the timeline. Applying before final school results are available can fit the supplied conditions if the record explicitly allows completion later. It still does not guarantee admission.'],
['h3','Join the deadline to the starting point'],
['p','Working backwards identifies what must be ready by the deadline and which earlier steps it needs. Working forwards checks what the learner has completed and when the next course is actually offered. Imagine a course requires an introductory course first: putting both names in the same term would not make the prerequisite complete. The two directions of reading need to meet in one workable sequence.'],
['p','Capacity means the space and resources available for the plan. A course can be offered and useful but still conflict with another elective or exceed the additional study time available. Money matters as well. We will count the listed material charges and state what they cover, rather than assume a school exercise supplies every future tuition or living cost.'],
['p','A checkpoint is a planned moment to review progress. A trigger is a change that makes revision necessary, such as a cancelled course. Leaving some room in the plan can make a later revision easier. A plan is therefore more than a timetable: it explains why the steps fit and when we will check whether those assumptions still hold.'],
['p','We will use Tariq’s school and provider records to build a design route while keeping information services possible. I will explain the first sequence. You will revise it after a course cancellation using the same facts and support. The final task introduces Nessa, whose records contain a different elective conflict. Your response will show the route, explain its limits and include checkpoints and questions.'],
['p','All course names, offerings and entry conditions in these scenarios are fictional and supplied on the page. You are planning the relevant pathway steps within an already arranged core timetable, rather than auditing real graduation requirements. Start by reading what Tariq has completed, what each provider requires and when the school offers the preparation.']
],
orientation:[
'Tariq wants to investigate visual design and keep an information-services option open. There is room for only one elective per term and at most three additional study hours each week. The interesting question is whether the two directions can share a workable plan without consuming evenings already committed elsewhere.',
'We have two kinds of notice to read. The providers identify entry evidence and deadlines; the school identifies prerequisites, offerings, weekly work and materials. A provider’s requirement does not tell us which school term can supply it. We will use both records when deciding where a course belongs.',
'The first completed plan will keep both directions possible. Supported practice then changes one offering, which tests whether the plan can be revised honestly. Nessa’s final situation uses different courses and deadlines. Carry the comparison method into that task, while keeping her facts separate from Tariq’s.'
],
caseGuide:[
'Read the provider rows as destinations. For Program A, locate the communication requirement and portfolio deadline. For Program B, locate its named courses and application deadline. The Preparation column includes useful ways to prepare, which must be read separately from the Required entry evidence column.',
'Then use the school table to trace each course from its prerequisite to its available slot. “Core, reserved” means a communication course is already placed within this exercise. An elective uses the limited elective slot and adds the hours shown. The first reading check asks which Program A item is actually required, so use the provider wording rather than infer a requirement from the recommended school route.'
],
method:[
['h3','Find the latest point at which evidence must be ready'],
['p','Program A’s portfolio is due April 15 of Grade 12. That means two original pieces need to exist by then. Portfolio Lab is a supplied way to develop them, finishing by March 30 of its year. I compare those dates first because a course finishing after the submission date would not support this route, however relevant its content might be.'],
['p','Now follow Portfolio Lab’s prerequisite backwards. It needs Digital Media 2, which needs the Digital Media 1 already completed. The school offers Media 2 in fall and the Lab in winter, so the sequence can move forward from Tariq’s existing preparation. We have connected a destination deadline to an available chain rather than simply selecting appealing course names.'],
['h3','Keep the shared preparation visible'],
['p','The communication chain runs from the completed Foundations to Applications in Grade 11 core and Capstone in Grade 12 core. These are already reserved if the prerequisites are completed. They do not compete for the elective slot. Applications contributes to Program B’s preparation, while Capstone meets the later condition named by Program A.'],
['p','Program B also requires Digital Records, which has an available place in the school table. It is a real condition within this fictional case, not a vague backup label. To keep B possible, the plan needs to show where that course will be completed and retain the May 1 application deadline.'],
['h3','Check whether each term has enough capacity'],
['p','Every additional elective needs its own available slot. Portfolio Lab takes three extra weekly hours; Digital Records takes two. Putting them together would use two slots and five hours, beyond both limits. A workable sequence separates those demands even when both courses are useful.'],
['p','The listed materials are $40 for Media 2, $35 for the Lab and $20 for Records. Adding them once each gives $95. Tariq has a $100 material limit, leaving $5 in that category. This is an elective-material calculation. It does not establish the cost of post-secondary study or provide money for an expense omitted from the record.'],
['h3','Decide what a checkpoint should check'],
['p','A good checkpoint has an object: the completed pieces, a prerequisite result, continued interest or a deadline. “Review at the end of Grade 11” becomes useful when the plan says what will be reviewed then and why the result could change the next step. A trigger, such as cancellation, may require a review before the scheduled date.'],
['p','Support questions should identify an uncertainty that matters. Asking which formats are accepted for the two portfolio pieces is more useful than asking whether everything is fine. You are drafting such questions here; no provider response is needed to finish the supplied plan. Clear notices, models and the optional planning tool provide the support available inside this lesson.'],
['p','The route guide below helps organize questions about shared preparation, course sequences and other evidence. Its Route A and Route B labels are illustrative: Tariq’s actual options each need their own complete conditions checked. Read the diagram alongside the notices, then follow how the worked plan places the relevant steps in time.']
],
workedBefore:[
'Let’s place the steps in Tariq’s timetable. I begin with what is already completed in Grade 10 and the reserved core communication chain. This matters because the elective plan must add to the existing program without displacing core preparation or treating an unfinished prerequisite as complete.',
'I put Media 2 in Grade 11 fall, followed by Portfolio Lab in Grade 11 winter. The order respects the prerequisite. The pieces can be completed by March 30 of Grade 11, giving time to review them before Program A’s April 15 deadline in Grade 12. That room for review is part of the reason for preparing them early.',
'Next I place Digital Records in Grade 12 fall. It keeps Program B’s additional course possible without sharing the Lab’s slot. Grade 12 winter can remain unassigned to an extra elective. Read the table below from the completed starting point through the planned steps; its last column explains why each belongs there.'
],
workedAfter:[
'The plan works through several checks at once: prerequisites come first, each elective has a stated offering, no term uses more than one elective slot and each additional course fits the weekly limit. The $95 material total also stays within $100. These checks support a feasible preparation plan; they do not establish that either provider will select Tariq.',
'Keep both kinds of date visible. Portfolio evidence is due April 15 and Program B’s application is due May 1 in Grade 12; the listed school-course completion conditions run to June where stated. A checkpoint should therefore check submission readiness as well as eventual course completion. Next, one course cancellation will test the room for revision in this plan.'
],
practiceBefore:[
'The cancellation notice changes one of the plan’s assumptions: Media 2 can no longer be taken in Grade 11 fall. Its later offering and the Lab’s March 30 completion date are supplied, so you can test whether the sequence still reaches the portfolio deadline. Other offerings and limits stay the same.',
'First try Choose a valid design sequence and check it against prerequisite order and actual offerings. Then list all four elective slots in Revised elective sequence. Include an unassigned slot when appropriate; a blank capacity is not a missing course you must invent.',
'In Deadline and capacity check, explain how the new arrangement affects both directions, the weekly limit and materials. In Checkpoint and precise support question, identify what needs closer attention now that the portfolio work is nearer the deadline. Use the supplied notice and the hint if needed, then compare and revise your own sequence.'
],
independentBefore:[
'Nessa’s case asks you to use the same planning checks with a different starting point. She wants records work as the primary direction and a visitor-services possibility kept open. Her conflict is already identified in the supplied feedback: two useful electives were placed in one term, creating a slot and weekly-work problem.',
'Read each course’s other available offering before moving it. A valid alternative must still respect Records 1 before Records 2 and the timing of the visitor samples. Nessa’s communication core is reserved, and her material budget is $120. Use those facts rather than Tariq’s course names or $100 limit.',
'The final response has three parts: a Grade 10–12 route with all four elective slots; goals, costs and the reason for the revision; then two checkpoints and support questions. Keep Program D’s April 1 sample deadline and Program C’s May 1 application deadline visible, as well as the stated course completion dates. Your explanation should show how the chosen sequence resolves the feedback while keeping both directions possible.'
],
closing:[
'The useful course list becomes a plan when its order, offerings, deadlines and resource limits work together. A cancelled course or conflicting term can change the route without automatically ending the goal. Your Nessa response should explain why its particular sequence fits and which evidence will be reviewed at its checkpoints.',
'The next lesson broadens the choice beyond training. The same practical interest can lead toward working for an employer or investigating a venture. We will compare the responsibilities and money in those arrangements, keeping the evidence just as carefully labelled as the costs and dates in this plan.'
],
corrections:[['A second is before April 1 in Grade 12, to check the samples.','A second is before April 1 in Grade 12, to check the samples and submission readiness; the plan also needs Program C’s May 1 application before the stated June course-completion limit.']]
},
'ce1-06':{
foundation:[
['h3','Five sales bring in $150. What does that actually tell us?'],
['p','Someone enjoys a practical task and sees money coming in from it. Does that make running a venture the best way to work? The sales figure is only part of the story. Someone also supplies materials, arranges the work, keeps records and accepts the uncertainty of finding the next customer. We will compare ways of working by following both the money and those responsibilities.'],
['h3','The same interest can lead to different arrangements'],
['p','An employee works under an employer’s arrangements and direction. A self-employed person obtains work from clients and takes responsibility for operating the work. An entrepreneur investigates an opportunity and organizes a venture to address it. The same interest, such as craft or practical problem solving, can appear in different arrangements. Enjoying the task does not by itself decide which set of responsibilities fits.'],
['p','An offer helps identify what a particular employer supplies and expects. A venture record helps identify sales, costs, time and uncertainties in a proposed activity. We will read the actual arrangements in each rather than assume every employee has guaranteed hours or every venture provides freedom from commitments. The question is what these records support for this person.'],
['h3','Name the money before comparing it'],
['p','Revenue is money from sales before expenses. An expense is a cost of providing the item or service. Subtracting listed expenses produces a remainder within that record’s assumptions. If time or other costs are not priced, the remainder cannot be presented as a complete profit or take-home amount. A large sales figure can therefore hide the resources needed to earn it.'],
['p','An employee’s gross wage is earnings before payroll deductions. A quoted hourly rate becomes a gross amount only after we know the paid hours. A venture’s incomplete remainder and gross wages have different boundaries. We can compare the evidence and responsibilities, but we should not relabel either as final personal income when the missing details have not been supplied.'],
['p','Kai’s first-week service trial will give us a claim to test: five customers paid $30, so Kai calls the $150 profit. A fictional shop also offers one supervised helper shift. I will show how to correct the money claim and compare the two arrangements. Supported practice then changes the number of paying customers, testing whether one week established a stable opportunity.'],
['p','Your final task uses Samir’s craft experience, a different shop offer and a four-sale paper trial. You will calculate the venture remainder, compare the arrangements and write a truthful employment-profile snippet. That last part connects an earning route to evidence a person could honestly present, without turning school experience into paid employment.'],
['p','All prices, wages, sales and work are supplied fictional cases. This lesson requires no sales, purchases, repairs, customer contact or public profile. Start by reading what Kai has actually done and what each arrangement assigns to Kai and to others. We will use that evidence before deciding which direction deserves further investigation.']
],
orientation:[
'Kai likes practical work and explaining it, wants more technical knowledge and values a predictable short weekly shift. Those goals could relate to more than one way of working. We need to examine the offered arrangements and the actual evidence behind the income claims.',
'Kai’s workshop experience can support some helper duties without establishing independent repair expertise. Read that starting evidence, the Cedar Cycle offer and the service-trial record as three different documents. One describes experience, one a particular offered shift and one the result of a supplied fictional trial.',
'We will first correct Kai’s claim and compare the shop’s responsibilities with the venture’s. You will then test how fewer customers change the trial. Samir’s independent case asks for the same kind of explanation and a truthful profile sentence using Samir’s own school-display evidence.'
],
caseGuide:[
'The shop offer tells us the hours and rate for one shift, the duties expected and what the employer handles. The trial record tells us what customers paid, the listed expenses and the time used. Look for the boundary of each: later shifts are unknown, and several venture costs are not priced.',
'Keep Kai’s claim beside those records. Its multiplication may be correct while its label is wrong. The reading check asks who handles a particular responsibility under the shop offer, so use that notice rather than decide from a general impression about employment.'
],
method:[
['h3','Start with the arrangement, not the promise'],
['p','Kai’s experience includes checking labels, explaining completed steps and asking before unfamiliar work. Those actions relate to the shop’s inventory and customer-explanation duties. The offer also supplies training and direction. This gives a reason to investigate helper work; it does not turn workshop participation into a history of paid work or independent technical competence.'],
['p','The shop handles bookings, tools, materials and payments. Kai would still need to check accurately, explain honestly and ask the supervisor about unfamiliar requests. The venture adds responsibility for finding customers, arranging costs and keeping the work’s records. We are comparing where responsibilities sit, not deciding that one route requires effort and the other does not.'],
['h3','Trace the sales money through the expenses'],
['p','The five paid jobs bring in five times $30, which is $150 revenue. Parts and other listed costs must be paid from that money before we can describe what remains. The record gives those costs; ignoring them would make the same work appear to produce more available money than it does.'],
['p','A per-item cost repeats with each job or item. A fixed cost stays the same within the particular scenario even if fewer sales occur. That distinction will matter when we change the trial. Always read which costs repeat and which are charged once; do not assume every expense rises or falls at the same rate as sales.'],
['p','The shop’s four-hour offer at $18 an hour gives a separate gross-wage calculation. It is before payroll deductions. The venture record leaves equipment wear, insurance, permits, taxes and payment for Kai’s six hours unpriced. Those gaps remain even after the listed arithmetic is correct, so a comparison must explain what each figure means.'],
['h3','Treat an opportunity as something to investigate'],
['p','Five customers paying in a supplied first week shows sales that week. It does not establish next week’s demand. Someone liking an idea is also different from agreeing to pay its price. To investigate a venture, we need evidence about the need it addresses, possible customers, alternatives and resources. A person’s enthusiasm helps choose what to explore but cannot supply those missing facts.'],
['p','Testing in this course means examining the supplied records and revised paper scenarios. A sensible next learning step might be making a fuller cost checklist or testing a smaller workload on paper. It does not require taking money from customers or attempting unfamiliar repairs. Keep the missing information visible in the proposed next step.'],
['h3','Connect employment documents to truthful evidence'],
['p','If Kai investigates the shop route, the workshop actions can become evidence in an application. A résumé organizes skills, education and experience. A common basic structure includes a contact heading, a short relevant summary, evidence-supported skills, dated experience and education. Our fictional practice needs no private contact details. The important move is to describe the actual workshop contribution rather than claim a paid shop job.'],
['p','A truthful compact entry could read: “Kai — practice candidate. Interested in supervised bicycle-shop helper work and developing technical knowledge. Community workshop participant, eight sessions: checked part labels against an inventory list, explained completed steps to visitors and asked the leader before unfamiliar work. Grade 12 completed.” Each experience claim comes from the starting record.'],
['p','A cover letter addresses a particular employer and explains why selected evidence relates to its opening. Kai could connect checking labels with the shop’s inventory duty. A portfolio contains selected examples with explanations; it is not every file a person owns. An online employment profile presents relevant background on a digital service. These documents have different purposes, but each should keep the evidence truthful. No application or profile is sent here.'],
['p','A blank sample inventory checklist with a note about Kai’s method could show relevant work without exposing someone else’s identifiable repair form. The résumé summarizes the experience, the letter explains its relevance and the portfolio can illustrate it. That connection will help you write Samir’s short profile snippet later without adding a separate résumé assignment.'],
['p','Next, watch or read The Entrepreneur’s Dozen for the role of research, resources and revision. Use it to ask what Kai still needs to know after one week’s sales. Then follow the worked comparison that labels the money and connects it to Kai’s goals.']
],
workedBefore:[
'Let’s check the claim one part at a time. Five paid jobs at $30 produce $150 revenue, so the multiplication is valid. I then subtract $75 in parts and $25 in transport and supplies. Together those listed costs are $100, leaving $50. The correction is not to dismiss the sales, but to give each amount its accurate name.',
'I keep the boundary after the answer: the $50 is before the other unpriced costs and payment for six hours. We have no evidence of repeating sales next week. Calling this a dependable weekly profit would add both complete costs and future demand that the trial does not supply.',
'For the shop, four hours at $18 gives $72 gross wages for one offered shift. That amount cannot be treated as deposited take-home pay, and one shift does not establish all future hours. I compare the defined support and duties as well as the money. The arrangement may fit Kai’s wish to learn technical work in a predictable short shift.',
'Read the completed comparison below. It corrects the labels, identifies the responsibilities and makes a provisional recommendation tied to Kai’s goals. A different preference could be argued from the records, but it would still need to retain these money and demand limits.'
],
workedAfter:[
'The recommendation investigates the shop first without declaring the venture impossible. It identifies what more evidence a venture earning plan would need. Employment also retains responsibilities for accuracy and appropriate requests for help; supervision does not mean the helper has no duties.',
'Now we will test how stable the first-week picture is. The practice record changes paid jobs from five to three, while keeping a weekly charge. That change lets you investigate the costs rather than assume all amounts simply shrink together.'
],
practiceBefore:[
'Read the second-week notice before calculating. The price remains $30 per paid job, parts are $15 per job and the weekly transport/supplies charge is still $25. There are three paying customers. The exclusions for time and other costs stay in place.',
'Try Which cost repeats per job? and check the explanation. Then enter Three-job revenue, Listed costs and Amount remaining in their fields. Count the repeating costs using this week’s jobs and the weekly charge once. Each amount has its own Check this calculation button. Use it to find any mismatch before explaining what changed in the opportunity.',
'Your two written notes interpret the arithmetic and propose a safe next learning step using course records. A lower remainder can tell us the earlier week did not establish dependable income; it cannot tell us to invent extra customers or remove necessary work. Use the hint and intentional model reveal if you need support, then revise the same fields.'
],
independentBefore:[
'Samir’s case changes the craft, customers, prices and employment offer. The comparison method transfers, but Kai’s amounts and workshop history do not. Start with Samir’s school-display actions, then read what the shop handles and what the four-sale venture record includes and excludes.',
'The first final field asks for the venture amount remaining. In Samir’s route comparison, show the sales and both listed cost calculations and explain their boundaries, then compare responsibilities, goals and a next learning step. The shop’s offered gross wages and the venture’s incomplete remainder should keep their labels throughout.',
'The employment-profile snippet uses a different part of the same evidence: what Samir can truthfully offer a reader interested in helper work. Use one or two sentences based on the display actions and their relevance. The record supplies no paid retail experience, and the task needs no contact details or public account. The profile supports the employment investigation rather than becoming an unrelated assignment.'
],
closing:[
'The original $150 claim was a starting point for reading more carefully. A meaningful earning comparison names sales, expenses, time, wage boundaries and the responsibilities each arrangement assigns. It also asks what evidence is still needed, rather than choosing from enthusiasm or the largest headline amount alone.',
'Before signing off on Samir’s response, check both the money explanation and the truthful experience snippet. The next lesson asks how a purposeful plan can change when time or circumstances change. The willingness to revise a venture idea when evidence changes is one example of that wider planning skill.'
]
},
'ce1-07':{
foundation:[
['h3','If the trip no longer fits, does the goal have to disappear?'],
['p','You make a plan for something you want to learn, then another commitment changes the week. The original trip no longer fits. It can feel as though the whole plan has failed, but the trip and the purpose are not the same thing. How can you keep a worthwhile goal while changing the route honestly? We will work through that question using supplied weekly plans.'],
['h3','Identify which part has changed'],
['p','A goal is what you want to accomplish. A route is the way you will work toward it. Timing places that route into a day or week. Wanting to try a design task is a goal; attending a club is one route; Tuesday afternoon is its scheduled time. A new commitment may change the time or route without telling us that the interest itself has vanished.'],
['p','A constraint is a limit the plan must respect. Capacity is the time or resources actually available. In our cases, fixed commitments cannot move and only the listed flexible blocks can be reassigned. This makes the planning question specific: which supplied option fits? We cannot repair the chart by inventing spare time elsewhere or counting the same interval twice.'],
['h3','Count the full activity, not just its title'],
['p','A one-hour session can need two hours if it includes travel in both directions. At home, an activity may still need reading, drafting and transition time. Those parts need a continuous block large enough for the stated work. Adding scattered spare minutes is not enough when the task or journey needs an uninterrupted period.'],
['p','A buffer is time left unassigned to allow for variation and transition. Recovery and existing commitments also need to stay visible. A chart that fits only by removing every break or assuming every step takes exactly its shortest possible time creates another planning problem. We will use the protected rest blocks stated in the cases.'],
['p','A revision note records the old assumption, the new evidence, the revised route or timing and when it will be reviewed. A checkpoint is a planned review moment; a trigger is a change that makes an earlier review useful. Naming both helps a plan respond to evidence rather than leaving “review later” as an empty intention.'],
['p','Maya wants to make two design samples while keeping family commitments and rest. I will show how one supplied written option replaces an unavailable trip. You will then revise a second session after transport changes. Arun’s final case uses the same reasoning, but its task takes 75 minutes and must fit a different set of blocks.'],
['p','The schedules supply the options, access and timing you need. No meeting, teacher response or outside account is needed. Your final response will place the task in a real available interval, explain why it fits and identify a useful review date and trigger. Begin by separating Maya’s goal from the original club trip before deciding what needs to change.']
],
orientation:[
'Maya’s purpose is to make two sample layouts over four weeks and learn whether design remains interesting after a first attempt. The original plan uses a Tuesday introduction and Thursday practice, each with travel. A new family commitment removes the Tuesday interval for four weeks.',
'The immediate question is which part of the plan must change. The records have not said Maya lost interest or that every option disappeared. Read the original board, the new commitment and the alternative notice before deciding whether the learning goal can still fit.',
'The worked plan will replace Tuesday while preserving the other commitments. Guided practice then changes Thursday’s transport. Arun’s independent task changes the person and work duration, so your final revision must use his own records. The method stays the same: identify the changed assumption, find a confirmed alternative and check its full timing.'
],
caseGuide:[
'Read the board as intervals, not just activity names. Each club hour needs an outward and return journey. The new Tuesday commitment covers the whole 15:30–17:30 interval at home. The alternative notice then states what can be done in a one-hour home block and confirms access to its materials.',
'The flexible Saturday block and its buffer provide a possible place to test; the afternoon rest is protected. The first reading check asks why the original Tuesday route fails. Use the overlap in the records, rather than infer a change in Maya’s interests or move an unrelated commitment.'
],
method:[
['h3','Trace the conflict before choosing a replacement'],
['p','The old plan assumes Maya can leave home at 15:30 and return at 17:30 on Tuesday. The family commitment occupies that same interval. The problem is therefore the availability of the route, including travel, rather than the one-hour session considered alone. Naming the changed assumption tells us what a replacement must solve.'],
['p','Maya’s design-learning goal remains in the record. A changed circumstance does not automatically cancel it, although later experience could lead Maya to revise the goal itself. For now, we should test a supplied route that keeps the goal possible without pretending two simultaneous commitments can both be completed.'],
['h3','Find a block that holds all the work'],
['p','The written package needs 40 minutes for the example and 20 for a draft: 60 minutes altogether. Its notice confirms that it can be used at home and that Maya has the access needed. Those are important facts. We cannot assume an online alternative exists merely because it would be convenient.'],
['p','The available Saturday hour is continuous and at home. The following 30 minutes are unassigned transition or buffer time, while the afternoon rest is protected. Checking each interval ensures the proposed work fits the actual week. It does not mean every spare minute needs to become another task.'],
['h3','Choose a digital habit that supports the task'],
['p','A calendar or reminder can support the plan, but the scheduled hour still needs to contain the work. Repeatedly checking messages could leave less time for the example or draft. A manageable habit might be keeping the task document visible, closing nonessential messages or setting a reminder at the change from one part to the next.'],
['p','A habit supports available capacity; it does not create time that the schedule lacks. If the task really takes longer, the route or scope needs to be reviewed. Fictional labels are sufficient for this course’s planning notes, so there is no need to publish family details or put personal routines in a public calendar.'],
['h3','Use overload as information for revision'],
['p','If the plan fits only by consuming protected rest, sleep or fixed commitments, the apparent solution hides another conflict. A reasonable response is to change conflicting demands, use a confirmed alternative or reduce the scope where allowed. The case’s written package is a specific support, not a requirement for Maya to solve every barrier through effort alone.'],
['p','Support can also be clear information or an accessible format. Here it comes from the notices, worked timing and comparison model. You may identify a question for future planning, but a real reply is not needed to complete the supplied task. Keep an uncertainty as a question rather than write an imagined permission into the plan.'],
['h3','Say when another look would be useful'],
['p','A review date gives the plan a place on the calendar. A trigger gives a reason to revisit it sooner or again: changed transport, missing materials or evidence that the work takes longer than expected. The revision note should name what would change after the review, not simply promise to try harder.'],
['p','We will now combine these checks in Maya’s Tuesday replacement. As you read, look for the preserved goal, the changed route, the full work block and a review that can test the plan against what happens. That is how a revision becomes a useful response to evidence.']
],
workedBefore:[
'Let’s begin with the overlap. Tuesday’s 15:30 departure and 17:30 return are no longer available. Moving only the session label would leave a travel conflict, so I need an alternative that can happen at home in a confirmed free block.',
'The notice supplies a written package taking 40 plus 20 minutes. I compare its 60 minutes with Saturday’s 10:00–11:00 block. They fit, and the device and materials are confirmed. That gives a supported replacement rather than an invented class or a promise that someone will provide new support.',
'Thursday’s original route is unchanged by the Tuesday notice, so I preserve it. This places the written introduction after Thursday’s practice in the first changed week. For this paper case, no prerequisite between the two activities is stated, so the worked schedule retains Thursday. A real activity that required the introduction first would need a further revision. I also leave Saturday’s 11:00–11:30 buffer and 14:00–16:00 rest in place. The revised board below shows the actual parts of the work, followed by a note explaining what was changed and how Maya will review it.'
],
workedAfter:[
'The revised note keeps the goal visible while changing the means of achieving it. The notification habit supports the focused work, and Sunday October 11 is a moment to compare the planned hour with the task’s actual demands. If the work did not fit, that evidence calls for revision rather than silently consuming the protected rest block.',
'Now the practice changes a different assumption: Thursday’s return transport. Keep the Tuesday-to-Saturday solution. You will investigate the new supplied Thursday package, whose parts still need to add up to one available hour.'
],
practiceBefore:[
'The new notice makes the return journey unavailable for two weeks. It also confirms a written practice package at home, its materials and an available Thursday 16:00–17:00 block. The goal and the Saturday introduction remain unchanged; only the Thursday route needs a new check.',
'Try Choose a supported Thursday revision and check your reasoning. Then write The changed assumption, Revised Thursday with full timing, and Review trigger and digital habit. Separate the 45-minute practice from the 15-minute reflection and explain what the home option means for travel.',
'Your review should connect to the change: when transport resumes or the task needs longer, the arrangement may need another look. Choose a digital habit that helps this particular work block. Use the comparison model to check the timing and limits, then revise your own notes.'
],
independentBefore:[
'Arun now needs to compare two program descriptions and write a question about each before October 20. The old Wednesday visit conflicts with a new fixed lab. The Friday visit also has a stated conflict. Use those records before choosing an alternative; a different label on the same unavailable time would not repair the plan.',
'The supplied written option takes 30 minutes reading, 30 comparing and 15 writing questions. The method is the same as Maya’s, but the total is now 75 minutes rather than 60. Compare that full task with Arun’s available 90-minute Saturday block and its fixed ending. Preserve the protected rest and do not invent another slot.',
'In the first field, show the revised sequence and its timing. In the second, explain why it fits, what stays protected and how a support or habit helps. In the third, give a review date before the October 20 goal and a trigger tied to a possible gap or changed circumstance. The question about a program is something Arun can identify from the supplied work; no outside response is needed.'
],
closing:[
'The trip and the goal can be separated. A useful revision identifies what changed, uses a confirmed alternative, counts the whole task and protects the other commitments. Your Arun response should make that reasoning visible, including the room left before the next fixed block.',
'This completes the career-planning sequence. We have moved from evidence about interests and strengths to reading work and preparation records, comparing routes and revising plans as information changes. The next course section examines employee rights and responsibilities: another setting where understanding the situation and checking the relevant conditions should come before acting.'
]
}
};
