// Synthetic review saving/isolation and changed-area visual inspection only.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=__dirname,manifest=JSON.parse(fs.readFileSync(path.join(root,'REVIEW_MANIFEST.json'))),out=path.join(root,'screens');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1360,height:1000}}),page=await context.newPage(),errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});
const sentinel='Synthetic course-state sentinel: must remain untouched';await context.addInitScript(({sentinel})=>{if(!localStorage.getItem('calm10-2026-draft:learning:v3'))localStorage.setItem('calm10-2026-draft:learning:v3',sentinel)},{sentinel});
const report={status:'pass',syntheticContextsOnly:true,noActualLearnerStorageAccess:true,lessons:{},media:[],limits:['Not teacher acceptance or release certification','Visual checks restricted to rewritten teaching areas','No comprehensive E2E or SCORM suite']};
for(let v of ['a','b']){await page.goto(`http://127.0.0.1:4195/review/${v}/index.html#ce1-01`,{waitUntil:'networkidle'});for(let id of manifest.lessons){await page.locator(`a.nav-link[data-page-target="${id}"]`).click();await page.locator('#'+id).waitFor({state:'visible'});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(200);const field=page.locator('#field-'+id),value='Synthetic '+v.toUpperCase()+' review answer for '+id;await field.fill(value);await page.waitForTimeout(550);if(v==='b'){report.lessons[id]={};await page.setViewportSize({width:1360,height:1000});let anchor=id==='ce1-04'?id+'-stage-1':id+'-foundations';await page.locator('#'+anchor).evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+scrollY-76,behavior:'instant'}));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,id+'-b-opening-desktop.png')});
await page.locator('#'+id+'-stage-4').evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+scrollY-76,behavior:'instant'}));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,id+'-b-worked-desktop.png')});
await page.setViewportSize({width:390,height:900});await page.waitForFunction(()=>document.getElementById('course-sidebar').getBoundingClientRect().right<=1);await page.locator('#'+anchor).evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+scrollY-86,behavior:'instant'}));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow '+id);await page.waitForTimeout(200);await page.screenshot({path:path.join(out,id+'-b-opening-mobile.png')});
await page.locator('#'+id+'-stage-7 .student-instructions').evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+scrollY-86,behavior:'instant'}));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,id+'-b-independent-mobile.png')});await page.setViewportSize({width:1360,height:1000});
report.lessons[id]={desktopOpeningAndWorkedCaptured:true,mobileOpeningAndIndependentInstructionsCaptured:true,noMobilePageOverflow:true};}}
await page.reload({waitUntil:'networkidle'});for(let id of manifest.lessons){let val=await page.locator('#field-'+id).inputValue();assert.equal(val,'Synthetic '+v.toUpperCase()+' review answer for '+id);if(v==='b')report.lessons[id].reviewAnswerRestored=true;}
}
// A must still retain A after B edits on the same origin.
await page.goto('http://127.0.0.1:4195/review/a/index.html#ce1-01',{waitUntil:'networkidle'});for(let id of manifest.lessons)assert.equal(await page.locator('#field-'+id).inputValue(),'Synthetic A review answer for '+id);
assert.equal(await page.evaluate(()=>localStorage.getItem('calm10-2026-draft:learning:v3')),sentinel);
await page.goto('http://127.0.0.1:4195/review/b/index.html#ce1-02',{waitUntil:'networkidle'});await page.locator('#ce1-02 details.lesson-vocabulary-help > summary').click();const word=page.locator('#ce1-02 details.lesson-vocabulary-help .vocab-term').first();await word.focus();await page.keyboard.press('Enter');await page.locator('.vocab-dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');assert.equal(await word.evaluate(e=>document.activeElement===e),true);report.vocabularyKeyboardPopupEscapeAndReturnFocus=true;
for(let id of ['ce1-01','ce1-04','ce1-06']){await page.locator(`a.nav-link[data-page-target="${id}"]`).click();let video=page.locator('#'+id+' video').first();assert.equal(await video.count(),1);const src=await video.locator('source').getAttribute('src');const url=new URL(src,page.url()).href;const response=await context.request.get(url,{headers:{Range:'bytes=0-1023'}});assert.ok([200,206].includes(response.status()),'Media missing '+url);assert.ok(await page.locator('#'+id+' video + details, #'+id+' .finlit-transcript').count()||await page.locator('#'+id+' details').filter({hasText:'Read the video transcript'}).count());report.media.push({id,url,status:response.status(),transcriptAvailable:true});}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);report.pageErrors=errors;report.failedRequests=failed;report.aAndBStorageIsolated=true;report.canonicalStorageSentinelUntouched=true;fs.writeFileSync(path.join(root,'render-checks.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'pass',reviewAnswerRestore:6,aAndBAndCourseStorageIsolated:true,vocabularyKeyboard:true,mediaAccessible:3,changedAreaScreenshots:24}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
