// Narrow preservation and review-isolation checks, not course certification.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),c=require('cheerio'),crypto=require('crypto');
const root=__dirname,baseline=JSON.parse(fs.readFileSync(path.join(root,'BASELINE.json'))),manifest=JSON.parse(fs.readFileSync(path.join(root,'REVIEW_MANIFEST.json'))),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
for(let [f,h]of Object.entries(baseline.files))assert.equal(sha(fs.readFileSync(path.join(baseline.canonicalWorkspace,f))),h,'Canonical changed '+f);
const alberta=require('./alberta-course-review.cjs');
const selectors=['input','textarea','select','button:not(.vocab-term)','fieldset','template','video','source','.student-instructions','details.lesson-vocabulary-help','.authored-hint'];
const report={status:'pass',canonicalRootFilesUnchanged:Object.keys(baseline.files).length,lessons:{},corrections:manifest.corrections};
const original=fs.readFileSync(path.join(root,'baseline/index.html'),'utf8'),originalDOM=c.load(original,{sourceCodeLocationInfo:true});
const raw=(html,$,sel)=>$(sel).toArray().map(e=>html.slice(e.sourceCodeLocation.startOffset,e.sourceCodeLocation.endOffset));
for(let id of manifest.lessons){let a=fs.readFileSync(path.join(root,'baseline',id+'.html'),'utf8'),b=fs.readFileSync(path.join(root,'manuscripts',id+'.html'),'utf8'),old=c.load(a,{sourceCodeLocationInfo:true}),next=c.load(b,{sourceCodeLocationInfo:true});let kept={};for(let sel of selectors){let expected=raw(a,old,sel); if(sel==='.student-instructions') for(let change of manifest.corrections.filter(x=>x.id===id&&['media-purpose','control-wording'].includes(x.type))) expected=expected.map(x=>x.replace(change.before,change.after)); if(id==='ce1-05')expected=expected.map(alberta.tasks); assert.deepEqual(raw(b,next,sel),expected,'Protected node changed '+id+' '+sel);kept[sel]=next(sel).length;}
 for(let attr of ['id','data-canvas-helper-edit-key']){let av=old('['+attr+']').map((i,e)=>old(e).attr(attr)).get(),bv=next('['+attr+']').map((i,e)=>next(e).attr(attr)).get();assert.equal(new Set(bv).size,bv.length,'Duplicate '+id+' '+attr);for(let x of av)assert.ok(bv.includes(x),'Lost '+id+' '+attr+' '+x);}
 let tables=raw(a,old,'table');if(id==='ce1-04')tables=tables.map(x=>x.replaceAll('Source period 2024–2026; section update','Forecast period 2024–2026; section update'));if(id==='ce1-05')tables=tables.map(alberta.map);assert.deepEqual(raw(b,next,'table'),tables,'Document data changed '+id);
 let models=raw(a,old,'.authored-model');for(let change of manifest.corrections.filter(x=>x.id===id&&x.type==='model-fidelity'))models=models.map(x=>x.replace(change.before,change.after));if(id==='ce1-05')models=models.map(alberta.map);assert.deepEqual(raw(b,next,'.authored-model'),models,'Unlogged model change '+id);
 next('.vocab-term').each((i,e)=>assert.equal(originalDOM('[data-word-view="'+next(e).attr('data-vocab-term')+'"]').length,1,'Missing glossary term'));
 assert.equal(sha(b),manifest.hashes[id].article);assert.equal(sha(fs.readFileSync(path.join(root,'manuscripts',id+'.md'))),manifest.hashes[id].manuscript);
 report.lessons[id]={protected:kept,originalIdsAndEditKeysRetained:true,documentTablesPreserved:id==='ce1-05'?'Explicit Alberta course mapping and INF2050 prerequisite correction; original amounts/dates retained':'CE1-04 forecast label correction only',modelsPreservedWithLoggedCorrections:true};
}
for(let v of ['a','b']){let html=fs.readFileSync(path.join(root,'review',v,'index.html'),'utf8'),$=c.load(html,{sourceCodeLocationInfo:true});let allIds=$('[id]').map((i,e)=>$(e).attr('id')).get();assert.equal(new Set(allIds).size,allIds.length);let preserved=0;originalDOM('article[data-lesson-id]').each((i,e)=>{let id=originalDOM(e).attr('id');if(v==='b'&&manifest.lessons.includes(id))assert.equal(raw(html,$,'#'+id)[0],fs.readFileSync(path.join(root,'manuscripts',id+'.html'),'utf8'));else{assert.equal(raw(html,$,'#'+id)[0],raw(original,originalDOM,'#'+id)[0]);preserved++;}});report[v]={unalteredLessonArticles:preserved,exactAuthoredFragments:true};
 for(let e of $('script[src]').toArray()){let f=$(e).attr('src').replace('./','');assert.equal(fs.readFileSync(path.join(root,'review',v,f),'utf8'),fs.readFileSync(path.join(root,'baseline',f),'utf8').replaceAll('calm10-2026-draft:',`calm10-2026-draft:career-standard-v1:${v}:`));}
}
const landing=c.load(fs.readFileSync(path.join(root,'index.html'),'utf8'));for(let id of manifest.lessons)assert.equal(landing('#'+id+' > h2').text(),id.toUpperCase()+' · '+originalDOM('#'+id+' > header h1').text(),'Comparison title drift');report.comparisonLessonTitlesMatchCanonical=true;report.runtimeChanges='Review delivery prefixes only';report.notProof=['teacher acceptance','curriculum coverage certification','Studio','SCORM','Brightspace','release'];fs.writeFileSync(path.join(root,'source-checks.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,canonicalRootFilesUnchanged:report.canonicalRootFilesUnchanged,proposedLessons:manifest.lessons.length,unalteredBArticles:report.b.unalteredLessonArticles,protectedControlsMediaKeysAndInstructions:true}));
