#!/usr/bin/env python3
"""Real Chromium interaction tests against the exact self-contained HTML bytes.
Requires Python Playwright and Chromium. No external service is contacted.
"""
from pathlib import Path
import json, hashlib, os, traceback
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'PLAY.html').read_text(encoding='utf-8')
SHOTS=ROOT/'qa/screenshots';SHOTS.mkdir(parents=True,exist_ok=True)
checks=[]; errors=[]; requests=[]; width_records=[]
def check(name,condition):
    checks.append({'check':name,'pass':bool(condition)})
    if not condition: raise AssertionError(name)
def shot(page,name):
    page.screenshot(path=str(SHOTS/name),full_page=True)
def snap(page):return page.evaluate('B2Game.snapshot()')
def rec(page,id):return snap(page)['records'][id]
def fill(page,id,text):
    page.locator('#'+id).fill(str(text))
    if id.startswith('hours-'): page.locator('#'+id).blur()
def skip_to_practice(page):
    page.get_by_role('button',name='Start guided route',exact=False).click()
    page.get_by_role('button',name='Skip to practice',exact=True).click()
def submit(page):page.get_by_role('button',name='Run & check plan',exact=False).click()
def next_step(page):
    page.locator('#self-review').check()
    page.get_by_role('button',name='Next step',exact=False).last.click()
def lighting(page):
    page.locator('#option-lights').select_option('led');fill(page,'hours-lights',6)
    page.locator('#choice-same-service').check();fill(page,'total','.360');submit(page)
def computers(page):
    for id,h in [('computers',2),('lights',3),('fan',2)]:fill(page,'hours-'+id,h)
    page.locator('#choice-all').check();fill(page,'total','1.616');submit(page)
def projector(page):
    page.locator('#option-projector').select_option('b');page.locator('#choice-time').check()
    fill(page,'total','0.369');fill(page,'explanation','I kept the full 90-minute projection and all four hours of lighting, using the equivalent 150 W projector.');submit(page)
def efficient(page):
    fill(page,'percent','60');fill(page,'other','600');page.locator('#choice-no').check()
    page.get_by_role('button',name='Check energy account',exact=False).click()
def progress_to_transfer(page):
    skip_to_practice(page);lighting(page);next_step(page);computers(page);next_step(page);projector(page);next_step(page);efficient(page);next_step(page)
def transfer(page,initial='.780',revised='.580'):
    fill(page,'initial',initial);fill(page,'revised',revised);page.locator('#choice-replace').check()
    fill(page,'explanation','The four lights use 0.180 kWh. Two 80 W workstations for 2.5 h use 0.400 kWh. The total is 0.580 kWh, below 0.650 kWh, with all service times unchanged.')
    page.get_by_role('button',name='Submit independent answer',exact=False).click()

def main():
 with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('B2_CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    def page_new(width=1648,height=1000,mobile=False,reduced=False):
        ctx=browser.new_context(viewport={'width':width,'height':height},device_scale_factor=1,is_mobile=mobile,has_touch=mobile,reduced_motion='reduce' if reduced else 'no-preference')
        ctx.on('request',lambda req: requests.append(req.url))
        pg=ctx.new_page();pg.on('pageerror',lambda e:errors.append(str(e)));pg.set_content(HTML,wait_until='load');return pg
    page=page_new()
    check('Loads the executable B2 application',page.locator('h1').inner_text()=='B2 Power Budget Challenge')
    check('Future stages are initially locked',page.locator('[data-action=stage][data-index="5"]').first.is_disabled())
    check('No whole-app live announcement region',page.locator('#app').get_attribute('aria-live') is None)
    check('Dedicated status region exists',page.locator('#announcer[role=status]').count()==1)
    check('All initial embedded photos loaded',page.locator('img').evaluate_all('(els)=>els.every(e=>e.complete&&e.naturalWidth>0)'))
    shot(page,'01-home-desktop.png')
    page.get_by_role('button',name='Start guided route',exact=False).click()
    check('Worked example starts at first step',rec(page,'B2-W01')['workedStep']==0)
    page.get_by_role('button',name='Next step',exact=False).first.click();check('Worked next changes modelled step',rec(page,'B2-W01')['workedStep']==1)
    page.get_by_role('button',name='Previous step',exact=False).first.click();check('Worked previous preserves route and returns',rec(page,'B2-W01')['workedStep']==0)
    for _ in range(3):page.get_by_role('button',name='Next step',exact=False).first.click()
    check('Final worked account is 0.440 kWh','0.440' in page.locator('#table-total').inner_text())
    shot(page,'03-worked-desktop.png')
    page.get_by_role('button',name='Try it yourself',exact=False).click()
    submit(page)
    check('Blank submission is not counted as an attempt',len(rec(page,'B2-P01')['attempts'])==0)
    check('Blank answer has visible corrective feedback','Complete the missing fields' in page.locator('#feedback').inner_text())
    check('Submit focuses feedback rather than heading',page.evaluate('document.activeElement.id')=='feedback')
    page.locator('#option-lights').select_option('led');fill(page,'hours-lights','0');page.locator('#choice-same-service').check();fill(page,'total','0');submit(page)
    check('Zero-energy service cancellation is rejected',not rec(page,'B2-P01')['passed'])
    check('Service failure names the constraint','service requirement' in page.locator('#feedback').inner_text())
    first=rec(page,'B2-P01')['first']
    page.get_by_role('button',name='Need a hint?',exact=False).click()
    check('Hint count is retained',rec(page,'B2-P01')['hints']==1)
    check('Hint focus stays with the opened hint',page.evaluate('document.activeElement.id')=='hint-text')
    lighting(page)
    check('Lighting valid plan passes',rec(page,'B2-P01')['passed'])
    check('Checked successful schedule is locked',page.locator('#hours-lights').is_disabled())
    check('Successful free text is not called automatically graded','not an automatic grade' in page.locator('#feedback').inner_text())
    check('Next stage waits for self-review',page.locator('[data-action=stage][data-index="2"]').first.is_disabled())
    page.locator('#self-review').check();check('Self-review unlocks next stage',not page.locator('[data-action=stage][data-index="2"]').first.is_disabled())
    page.get_by_role('button',name='Revise this answer',exact=False).click()
    check('Revision invalidates current passed state',not rec(page,'B2-P01')['passed'])
    check('Revision removes active forward continuation',page.get_by_role('button',name='Next step',exact=False).last.is_disabled())
    check('Revision unlocks input fields',not page.locator('#hours-lights').is_disabled())
    check('Revision preserves numeric answer',page.locator('#total').input_value()=='.360')
    check('First submission cannot be overwritten by revision',rec(page,'B2-P01')['first']==first)
    submit(page);page.locator('#self-review').check();shot(page,'04-lighting-checked-desktop.png')
    page.get_by_role('button',name='Next step',exact=False).last.click()
    fill(page,'hours-computers','2');fill(page,'explanation','A saved computer-room draft.');compdraft=rec(page,'B2-P02')['draft']
    page.get_by_role('button',name='Previous step',exact=False).last.click()
    check('Going back restores prior checked lighting answer',rec(page,'B2-P01')['passed'] and page.locator('#total').input_value()=='.360')
    check('Going back retains opened hints',rec(page,'B2-P01')['hints']==1)
    page.get_by_role('button',name='Next step',exact=False).last.click()
    check('Going forward restores unfinished later draft',rec(page,'B2-P02')['draft']==compdraft)
    check('Visible later explanation is restored',page.locator('#explanation').input_value()=='A saved computer-room draft.')
    computers(page);check('Computer room checks actual group count',rec(page,'B2-P02')['passed'])
    check('Computer room displays exact 1.616 kWh','1.616' in page.locator('#live-total').inner_text())
    shot(page,'05-computer-room-checked-desktop.png');next_step(page)
    check('Reduced-support projector starts without hint button',page.get_by_role('button',name='Need a hint?',exact=False).count()==0)
    projector(page);check('Projector replacement preserves full service and passes',rec(page,'B2-P03')['passed'])
    check('Projector exact sum is displayed','0.369' in page.locator('#table-total').inner_text())
    next_step(page);efficient(page);check('Efficiency and remaining output both pass',rec(page,'B2-P04')['passed'])
    shot(page,'06-efficiency-checked-desktop.png');next_step(page)
    check('Independent screen contains no live plan total',page.locator('#live-total').count()==0)
    check('Independent screen contains no hint control',page.get_by_role('button',name='Need a hint?',exact=False).count()==0)
    check('Independent model answer is not exposed before submission',page.locator('.worked-comparison').count()==0)
    shot(page,'07-transfer-before-submission-desktop.png')
    fill(page,'initial','.780');fill(page,'explanation','Draft preserved before returning.');td=rec(page,'B2-T01')['draft']
    page.get_by_role('button',name='Previous step',exact=False).last.click()
    page.get_by_role('button',name='Next step',exact=False).last.click()
    check('Transfer answer survives back/forward',rec(page,'B2-T01')['draft']==td)
    check('Returning to practice records support before transfer submission',snap(page)['transferSupport'])
    transfer(page,initial='.700')
    check('Incorrect transfer is not passed',not rec(page,'B2-T01')['passed'])
    tf=rec(page,'B2-T01')['first']
    check('Transfer first record includes support',tf['support'])
    fill(page,'initial','.780');page.get_by_role('button',name='Submit independent answer',exact=False).click()
    check('Corrected transfer passes checked parts',rec(page,'B2-T01')['passed'])
    check('Transfer correction does not replace failed first answer',rec(page,'B2-T01')['first']==tf)
    page.locator('#self-review').check();page.get_by_role('button',name='View session review',exact=False).click()
    check('Completed route shows final review','Practice route complete.' in page.locator('.review-page').inner_text())
    check('Review discloses writing is not automatically graded','Free-text explanations have not been automatically graded' in page.locator('.review-page').inner_text())
    check('Review does not turn a corrected first answer into independent success','Returned to support' in page.locator('.review-table').inner_text())
    shot(page,'08-session-review-desktop.png')
    page.get_by_role('button',name='Start a fresh session',exact=True).click()
    page.get_by_role('button',name='Keep my work',exact=True).click()
    check('Cancel restart keeps the session',rec(page,'B2-T01')['passed'])
    page.get_by_role('button',name='Open centre lab',exact=True).click()
    check('Centre lab default corrects the mockup total','14.920' in page.locator('#live-total').inner_text())
    shot(page,'02-centre-lab-desktop.png')
    for id in ['lights','heater','computers','water','chargers']:fill(page,'hours-'+id,'0')
    check('Lab updates totals live at zero','0.000' in page.locator('#live-total').inner_text())
    check('Lab visibly refuses zero-service plan','required service is missing' in page.locator('#plan-status').inner_text())
    page.get_by_role('button',name='Check centre plan',exact=False).click()
    check('Lab all-off check does not pass',not rec(page,'B2-LAB')['passed'])
    for id,h in [('lights',6),('heater',4),('computers',3),('water',1.5),('chargers',2)]:fill(page,'hours-'+id,h)
    check('Lab stretch exact total is 10.390 kWh','10.390' in page.locator('#live-total').inner_text())
    check('Lab stretch target includes service constraint','Stretch target achieved' in page.locator('#stretch-status').inner_text())
    page.get_by_role('button',name='Check centre plan',exact=False).click()
    page.get_by_role('button',name='Replay energy use',exact=False).click();page.wait_for_timeout(250)
    check('Replay starts a real timeline',page.locator('#replay-time').inner_text()!='0.0 h')
    page.get_by_role('button',name='Pause replay',exact=False).click();paused=page.locator('#replay-time').inner_text();page.wait_for_timeout(150)
    check('Replay can be paused',page.locator('#replay-time').inner_text()==paused)
    page.get_by_role('button',name='Continue replay',exact=False).click();page.wait_for_timeout(6200)
    check('Replay ends at correct total','10.390 kWh' in page.locator('#replay-used').inner_text())
    page.get_by_role('button',name='Reset centre plan',exact=True).click();page.get_by_role('button',name='Reset lab plan',exact=True).click()
    check('Lab reset restores only lab draft','14.920' in page.locator('#live-total').inner_text())
    check('Lab reset does not clear completed guided route',rec(page,'B2-T01')['passed'])
    page.get_by_role('button',name='Open formula and learning help',exact=True).click()
    check('Formula help uses native modal dialog',page.locator('dialog').evaluate('(d)=>d.open'))
    page.keyboard.press('Escape');check('Escape closes formula help',not page.locator('dialog').evaluate('(d)=>d.open'))
    check('Focus returns to formula help trigger',page.evaluate("document.activeElement.getAttribute('data-action')")=='help')
    # Complete a second clean route without in-game support to verify the first-attempt record.
    clean=page_new();progress_to_transfer(clean);transfer(clean)
    check('Clean transfer records a correct first attempt',rec(clean,'B2-T01')['first']['pass'])
    check('Clean transfer records no in-game support',not rec(clean,'B2-T01')['first']['support'])
    clean.locator('#self-review').check();clean.get_by_role('button',name='View session review',exact=False).click()
    clean.get_by_role('button',name='Start a fresh session',exact=True).click();clean.get_by_role('button',name='Start fresh',exact=True).click()
    check('Confirmed fresh session clears old records',snap(clean)['unlocked']==0 and not rec(clean,'B2-T01')['first'])
    # Adversarial text is escaped, never executed.
    inject=page_new();skip_to_practice(inject)
    fill(inject,'explanation','<img src=x onerror="window.B2INJECTED=1"> & <script>window.B2INJECTED=2</script>')
    lighting(inject);check('Markup in writing is not executable',inject.evaluate('window.B2INJECTED===undefined'))
    inject.locator('.attempt-history summary').click()
    check('Markup is preserved as literal writing','<img src=x' in inject.locator('.attempt-history').inner_text())
    check('Escaping does not create student-supplied images',inject.locator('img[src="x"]').count()==0)
    inject.get_by_role('button',name='Revise this answer',exact=False).click();fill(inject,'hours-lights','-0.5');fill(inject,'total','0');submit(inject)
    check('Malformed schedule fails without a runtime exception',not rec(inject,'B2-P01')['feedback']['ready'])
    # Keyboard, reduced motion and responsive routes.
    keyboard=page_new(width=1366,height=900,reduced=True)
    keyboard.get_by_role('button',name='Start guided route',exact=False).focus();keyboard.keyboard.press('Enter')
    check('Keyboard starts the route',snap(keyboard)['route']=='task')
    keyboard.get_by_role('button',name='Skip to practice',exact=True).focus();keyboard.keyboard.press('Enter')
    keyboard.locator('#option-lights').focus();keyboard.keyboard.press('ArrowDown');keyboard.keyboard.press('Tab')
    check('Native equipment selector is keyboard operable',rec(keyboard,'B2-P01')['draft']['options']['lights']=='led')
    keyboard.locator('#hours-lights').focus();keyboard.keyboard.press('ControlOrMeta+A');keyboard.keyboard.type('6');keyboard.keyboard.press('Tab')
    check('Typing hours does not send focus to page heading',keyboard.evaluate('document.activeElement.id')!='screen-title')
    keyboard.locator('#choice-same-service').focus();keyboard.keyboard.press('Space')
    keyboard.locator('#total').focus();keyboard.keyboard.type('.36')
    keyboard.get_by_role('button',name='Run & check plan',exact=False).focus();keyboard.keyboard.press('Enter')
    check('Keyboard-only primary plan checks correctly',rec(keyboard,'B2-P01')['passed'])
    keyboard.get_by_role('button',name='Replay energy use',exact=False).click()
    check('Reduced motion replay resolves without forced animation','0.360 kWh' in keyboard.locator('#replay-used').inner_text())
    for width in [320,360,390,430,590,760,768,1024,1366,1648]:
        pg=page_new(width=width,height=900,mobile=width<=430)
        for route in ['home','lab','worked','lighting']:
            if route=='lab':pg.get_by_role('button',name='Open centre lab',exact=True).click()
            if route=='worked':pg.get_by_role('button',name='Return to guided route',exact=False).click();pg.get_by_role('button',name='Start guided route',exact=False).click()
            if route=='lighting':pg.get_by_role('button',name='Skip to practice',exact=True).click()
            vals=pg.evaluate('({viewport:innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth})')
            width_records.append({'width':width,'route':route,**vals})
            check(f'No page overflow at {width}px on {route}', vals['doc']<=width+1 and vals['body']<=width+1)
            if width==390 and route=='lab':shot(pg,'09-centre-lab-mobile-390.png')
            if width==390 and route=='lighting':shot(pg,'10-lighting-mobile-390.png')
        if width==390:
            lighting(pg);next_step(pg);computers(pg);next_step(pg);projector(pg);next_step(pg);efficient(pg);next_step(pg)
            check('Independent table reflows at 390px',pg.evaluate('document.documentElement.scrollWidth')<=391)
            shot(pg,'11-transfer-mobile-390.png')
            pg.get_by_role('button',name='Open formula and learning help',exact=True).click()
            check('Formula modal fits narrow viewport',pg.locator('dialog').bounding_box()['width']<=390)
            shot(pg,'12-help-mobile-390.png')
        pg.context.close()
    check('No JavaScript runtime errors during exercised flows',not errors)
    check('No external requests or analytics',not [u for u in requests if u.startswith(('http:','https:'))])
    browser.close()

if __name__=='__main__':
 error=None
 try:main()
 except Exception as e:error=str(e);traceback.print_exc()
 result={'version':'1.0.0','html_sha256':hashlib.sha256((ROOT/'PLAY.html').read_bytes()).hexdigest(),'method':'Exact self-contained PLAY.html executed with Playwright set_content in system Chromium. This is runtime browser testing, not a design-image render.','browser_path':os.environ.get('B2_CHROMIUM','/usr/bin/chromium'),'passed':sum(c['pass'] for c in checks),'failed':sum(not c['pass'] for c in checks)+(1 if error and not any(not c['pass'] for c in checks) else 0),'exception':error,'runtime_errors':errors,'external_requests':[u for u in requests if u.startswith(('http:','https:'))],'checks':checks,'viewport_records':width_records}
 (ROOT/'qa/browser-results.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
 print(json.dumps({k:result[k] for k in ['passed','failed','exception','runtime_errors','external_requests']},indent=2))
 raise SystemExit(1 if result['failed'] or error else 0)
