import {gametes} from './engine.js';
import {escapeHTML as h,panel,scene,prediction,table,field,selectField,explanation,checkButtons,formGate} from './ui.js';
const genotypes=[['AA','AA'],['Aa','Aa'],['aa','aa']];
function pedigree(s){const constraint=s.kind==='constraint'||s.stage==='worked',unknown=s.kind==='uncertainty';const labels=unknown?['aa','Dominant; unknown']:constraint?['Dominant phenotype','Dominant phenotype']:s.parents;return `<figure class="live-pedigree"><svg viewBox="0 0 440 ${constraint?210:120}" role="img" aria-label="${h(labels.join(' and '))}${constraint?'; child aa':''}"><path d="M100 42H340" stroke="#17221b" stroke-width="2"/><rect x="78" y="20" width="44" height="44" fill="${labels[0]==='aa'?'#18572d':'white'}" stroke="#17221b" stroke-width="2"/><circle cx="340" cy="42" r="22" fill="${labels[1]==='aa'?'#18572d':'white'}" stroke="#17221b" stroke-width="2"/><text x="100" y="91" text-anchor="middle">${h(labels[0])}</text><text x="340" y="91" text-anchor="middle">${h(labels[1])}</text>${constraint?'<path d="M220 42V128" stroke="#17221b" stroke-width="2"/><circle cx="220" cy="150" r="22" fill="#18572d" stroke="#17221b" stroke-width="2"/><text x="220" y="194" text-anchor="middle">Child: aa</text>':''}</svg><figcaption>Fictional autosomal model. Green denotes the recessive phenotype; shapes distinguish people only. ${unknown?'No offspring evidence is supplied.':'Use only the labelled genotype evidence.'}</figcaption></figure>`;}
function square(s,m){const rows=gametes(s.parents[0]),cols=gametes(s.parents[1]);return `<table class="ledger punnett-table"><caption>Punnett square: row alleles from parent 1, column alleles from parent 2</caption><thead><tr><th scope="col">Parent 1 ↓ / Parent 2 →</th>${cols.map(c=>`<th scope="col">${c}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><th scope="row">${r}</th>${cols.map((_,j)=>`<td>${selectField('cell'+(i*2+j),'Cell '+(i*2+j+1),m.modelInputs['cell'+(i*2+j)],genotypes)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function evidence(s){if(s.kind==='constraint')return '<p>Parent 1: dominant phenotype. Parent 2: dominant phenotype. Child: aa.</p><div class="ped-row"><div class="person"><div class="symbol square"></div><span>Parent 1: AA or Aa?</span></div><div class="person"><div class="symbol circle"></div><span>Parent 2: AA or Aa?</span></div></div><p>Both parents contribute to an aa child.</p>';
 if(s.kind==='uncertainty')return '<div class="ped-row"><div class="person"><div class="symbol square"></div><span>Parent 1: aa</span></div><div class="person"><div class="symbol circle"></div><span>Parent 2: dominant phenotype; genotype unknown</span></div></div><p>No offspring or genotype-test evidence is supplied. List every compatible cross.</p>';
 return `<p>Parents: ${h(s.parents.join(' × '))}.</p>${s.history?`<p>Earlier fictional offspring: ${h(s.history.join(', '))}. No outcome is due next.</p>`:''}`;}
export function render(s,m,transfer=false){
 let task='';
 if(s.kind==='constraint')task=selectField('parent1','Parent 1 genotype',m.modelInputs.parent1,genotypes)+selectField('parent2','Parent 2 genotype',m.modelInputs.parent2,genotypes);
 else if(s.kind==='uncertainty')task=[1,2].map(i=>`<h3>Possible cross ${i}: aa ×</h3>${selectField('possible'+i,'Other parent genotype '+i,m.modelInputs['possible'+i],genotypes)}${field('probability'+i,'Recessive probability '+i,m.modelInputs['probability'+i],'% or fraction',{type:'text'})}`).join('')+selectField('uncertainty','What does the evidence justify?',m.modelInputs.uncertainty,[['single','One definite probability'],['underdetermined','Two possible crosses; genotype unknown']]);
 else task=(s.kind==='cross'?square(s,m):'')+['AA','Aa','aa'].map(g=>field('p_'+g,g+' probability',m.modelInputs['p_'+g],'% or fraction',{type:'text'})).join('')+(s.kind==='independent'?selectField('outcome','Next offspring',m.modelInputs.outcome,[['independent','Same probabilities; each outcome independent'],['due','A missing outcome is now due']]):'');
 const probabilityTask=s.kind==='cross'?['AA','Aa','aa'].map(g=>field('p_'+g,g+' probability',m.modelInputs['p_'+g],'% or fraction',{type:'text'})).join(''):'';
 if(s.kind==='cross')task=square(s,m);
 return panel(transfer?'Fresh Transfer':'Case File',1,transfer?'Conventional pedigree prompt':'State the model assumptions',(transfer?'':scene(s,'Context illustration of a fictional genetics case'))+`<p>One fictional autosomal locus. A is completely dominant to a; full penetrance is assumed only in this puzzle.</p>`+(transfer?'':prediction(s,m)))+
 panel(transfer?'Your Possible Crosses':'Build the Deduction',2,'Keep every supported possibility',pedigree(s)+evidence(s)+formGate(m,task,transfer))+
 panel('Genotype & Reasoning',3,'Probability is not destiny',(probabilityTask?formGate(m,probabilityTask,transfer):'')+(s.stage==='worked'?'<div class="callout"><h3>Phenotype per offspring</h3><p>75% dominant phenotype; 25% recessive phenotype.</p><p>These probabilities apply independently to each offspring. They do not guarantee a particular family count.</p></div>':'')+explanation(m.explanation,s.explanationPrompt)+checkButtons(m,transfer));
}
export function refresh(){}
export function worked(){}
