// Review-only teaching copy. Paragraph indices refer to the canonical snapshot,
// including its section label at index zero. Models and learner controls stay intact.
export function refineWorkedExamples($) {
 const replace = (id, indices, html) => {
  const paragraphs = $(`#${id}-stage-4`).children('p');
  paragraphs.eq(indices[0]).replaceWith(html);
  for (const index of indices.slice(1)) paragraphs.eq(index).remove();
 };
 replace('fl1-01', [1,2,3], `<p>Start at the pay-period dates in the picture. Before trusting the calculation, I check that Mika’s three time entries belong to September 1–14. Their 12.50 hours match the regular-work line. The gross-pay calculation therefore uses the right hours and rate, rather than a number from a different period.</p><p>Now follow the current deductions to net pay. These are the amounts taken from this payment; the year-to-date column accumulates amounts across earlier payments too. The diagram shows how the current figures produce $194.60. Comparing that result with the payment summary checks whether the supplied records agree. It does not independently establish that real payroll rules were applied correctly.</p>`);
 replace('fl1-03', [1,2,3,4], `<p>Look at the dashed zero line in the original plan. The phone payment takes Sam below it before the second income arrives; transit makes the shortfall larger. This is a timing problem: $900 income covers the $890 in planned payments across the month, but some money arrives after it is needed.</p><p>Compare that dip with the confirmed split plan. Both plans end at $90 because neither income nor total payments changed. What changed is when Sam pays the room cost. The written agreement permits two $210 payments without a fee, so I can use that alternative rather than invent permission to delay another bill. Follow the same dates in the transaction calendar to check the repair:</p>`);
 replace('fl2-03', [1], `<p>The small interest segment in the bar is part of Alex’s payment, but it does not reduce the amount borrowed. Only the $78.85 principal portion comes off the $1,000 debt. That distinction explains the $921.15 remaining balance in the diagram.</p><p>Follow the carry-forward arrow: month one’s closing balance becomes month two’s opening balance. Applying the same 1% monthly rate to a smaller balance produces $9.21 interest, rounded to cents. With the payment still $88.85, $79.64 now goes toward principal, leaving $841.51. The payment is unchanged, but its two parts change.</p>`);
 replace('fl3-03', [1,2], `<p>Begin with Noor’s need, not the highest rate: the $500 must be available for a course fee in six months. Read the diagram’s holding separately from its account arrangement. A TFSA supplies account rules; it does not tell us whether the money inside is a savings deposit, a locked investment or a holding whose market value can fall.</p><p>Now compare the holdings with that deadline. S preserves access and avoids market-price loss under the supplied terms. G locks the money beyond six months, while F could lose value when Noor needs the fee. S’s illustrative $5 interest is a modest extra, not the reason it fits. G’s full-year $25 interest cannot be treated as a six-month return or as money available at the deadline.</p>`);
 replace('ce1-05', [1,2,3], `<p>Start with the prerequisite chains in the picture. Tariq’s completed Grade 10 courses and reserved core communication chain give us the starting point. I keep those core steps in place, then add electives in the available slots. This is a selected preparation pathway within an Alberta school program; it is not a complete graduation audit.</p><p>Follow Art 20 into Art 30. Placing them in Grade 11 fall and winter respects their order and allows the pieces to be finished by March 30 of Grade 11. That creates time to review the work before Program A’s April 15 portfolio deadline in Grade 12. Earlier preparation is useful because a submission deadline can arrive before school finishes.</p><p>Now follow the backup branch. INF1050: Database 1 fits Grade 12 fall without competing for Art 30’s slot; Grade 12 winter remains available for an extra elective if the plan needs revision. Read the timetable below to connect each placement with its reason. Then check the capacity and deadline panels: a course sequence is only workable if its slots, weekly time, costs and submissions fit too.</p>`);
 replace('ce1-05', [5], `<p>The diagram’s capacity checks explain why this plan is feasible: no term uses more than one elective slot, each additional course fits the three-hour weekly limit, and $95 in materials fits the $100 budget. Passing those checks supports preparation; it does not guarantee that a provider will select Tariq.</p>`);
 const bar = `<figure class="payment-split" aria-labelledby="payment-split-title"><h4 id="payment-split-title">Where Alex’s first $88.85 payment goes</h4><div class="payment-split-bar" aria-hidden="true"><span class="payment-interest" style="flex-basis:${10/88.85*100}%"></span><span class="payment-principal" style="flex-basis:${78.85/88.85*100}%"></span></div><ul class="payment-split-key"><li><span class="payment-swatch interest" aria-hidden="true"></span><strong>$10 interest</strong> — pays the borrowing charge</li><li><span class="payment-swatch principal" aria-hidden="true"></span><strong>$78.85 principal</strong> — reduces the debt</li></ul><figcaption>The lengths show the two parts of this first payment in proportion. Later payments have a different split as the balance changes.</figcaption></figure>`;
 $('#fl2-03-stage-4 > .visual-review-figure').after(bar);
}
