// Exact relationships in editable HTML/SVG; all figures use published worked cases.
export function addRelationships($) {
 const add=(id,title,content,caption)=>$(`[data-visual-review="${id}"]`).after(`<figure class="visual-relationship"><h4>${title}</h4>${content}<figcaption>${caption}</figcaption></figure>`);
 const bars=(rows,max)=>`<ul class="relationship-bars">${rows.map(([label,n,text])=>`<li><p><strong>${label}</strong> — ${text}</p><div class="relationship-track" aria-hidden="true"><span style="width:${n/max*100}%"></span></div></li>`).join('')}</ul>`;
 add('fl1-05','When the phone bill crosses the monthly limit',`<svg class="phone-cost-chart" viewBox="0 0 620 260" role="img" aria-labelledby="phone-chart-title phone-chart-desc"><title id="phone-chart-title">Offer A rises above the $45 limit at month four</title><desc id="phone-chart-desc">Months one through three cost $35 each. Months four through twelve cost $53 each. The limit stays at $45. Offer B stays at $43 under the supplied assumption.</desc><g fill="none" stroke="#d9ded8"><path d="M60 30H590M60 95H590M60 160H590M60 225H590"/></g><g fill="#171b1b" font-size="15" font-family="inherit"><text x="5" y="35">$60</text><text x="5" y="100">$40</text><text x="5" y="165">$20</text><text x="14" y="230">$0</text><text x="60" y="250">Month 1</text><text x="204" y="250">4</text><text x="562" y="250">12</text></g><path d="M60 78.75H590" stroke="#a15c00" stroke-width="2" stroke-dasharray="7 5"/><path d="M60 85.25H590" stroke="#5b635d" stroke-width="2" stroke-dasharray="2 5"/><path d="M60 111.25H204.5V52.75H590" stroke="#146c60" stroke-width="4" fill="none"/><g fill="#171b1b" font-size="16" font-family="inherit"><text x="82" y="138">A: $35</text><text x="315" y="46">A: $53</text><text x="365" y="107">Limit: $45 · B: $43</text></g></svg><div class="phone-mobile-comparison"><p><strong>Each full track represents $60.</strong> The dashed mark is the $45 monthly limit.</p><p><strong>A: months 1–3</strong> — $35</p><div class="phone-month-track" aria-hidden="true"><span style="width:58.333333333333336%"></span><i></i></div><p><strong>A: months 4–12</strong> — $53</p><div class="phone-month-track" aria-hidden="true"><span style="width:88.33333333333333%"></span><i></i></div><p><strong>B: months 1–12</strong> — $43</p><div class="phone-month-track" aria-hidden="true"><span style="width:71.66666666666667%"></span><i></i></div></div><p>Months 1–3: A is $10 below the limit. Months 4–12: A is $8 over. B is $2 below throughout this supplied year.</p>`, 'Both displays start at $0 and compare monthly bills, not the twelve-month total; no extra usage occurs and taxes are included in this fictional case.');
 add('fl2-05','Compare the periods of access and commitment',bars([
  ['Confirmed loaner',4,'Course start through saving deposit 4'],
  ['Saving for purchase',4,'Four month-end deposits; buy at deposit 4'],
  ['Certificate course',10,'Ten months from course start'],
  ['Financing alternative',18,'Eighteen monthly payments; last payment at month 18']
 ],18), 'Lengths use the same eighteen-month scale. Financing lasts eight months beyond the course. The loaner and cash-price confirmation—not an assumed extension—bridge the wait for purchase.');
 add('fl2-06','Money left below the $223 allowance',bars([
  ['F regular payment',1.40,'$223 − $221.60 = $1.40 left'],
  ['V months 1–12',3.64,'$223 − $219.36 = $3.64 left'],
  ['V months 13–23',1.29,'$223 − $221.71 = $1.29 left']
 ],5), 'Each full track represents $5 of remaining allowance, starting at zero—not the payment amount. Final payments also fit: F leaves $1.31 and V leaves $1.30. V follows only the supplied 5%-then-7% path.');
 add('fl2-07','One term inside the repayment horizon',`<div class="mortgage-horizon" aria-hidden="true"><span></span><span></span></div><p><strong>Years 1–5:</strong> this quotation’s current term (one-fifth of the planned horizon). <strong>Years 6–25:</strong> the remaining amortization horizon, with future agreement conditions unknown.</p>`, 'The continuous strip uses one equal length per year. It represents time, not how much principal is repaid; $107,803.92 still owing at year five needs a further decision.');
 add('ce1-07','Check the revised blocks together',`<div class="document-table"><table><caption>Maya’s changed week — selected blocks only</caption><thead><tr><th scope="col">Day</th><th scope="col">Learning or fixed commitment</th><th scope="col">What remains protected</th></tr></thead><tbody><tr><th scope="row">Tuesday</th><td>15:30–17:30 family commitment; original travel and session unavailable</td><td>No replacement travel added here</td></tr><tr><th scope="row">Thursday</th><td>15:30–16:00 travel; 16:00–17:00 practice; 17:00–17:30 return</td><td>Original route unchanged</td></tr><tr><th scope="row">Saturday</th><td>10:00–10:40 written example; 10:40–11:00 layout draft at home</td><td>11:00–11:30 buffer; 14:00–16:00 rest/recreation</td></tr></tbody></table></div>`, 'Other school, meals, sleep and work remain accounted for outside these blocks. The case states no prerequisite between the introduction and Thursday practice. Review on Sunday October 11 whether the package fitted its hour.');
}
