ï»¿(() => {
  const data = window.MODULE_1_DATA;
  const refs = {
    body: document.body,
    menuToggle: document.getElementById("menu-toggle"),
    navHome: document.getElementById("nav-home"),
    tabs: Array.from(document.querySelectorAll("[data-tab]")),
    title: document.getElementById("section-title"),
    intro: document.getElementById("section-intro"),
    content: document.getElementById("content-body")
  };
  const state = { tab: "chapters", view: "overview" };
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]); }
  function setHash(value) { if (location.hash.slice(1) !== value) history.replaceState(null, "", "#" + value); }
  function setTab(tab, view = "overview") { state.tab = tab; state.view = view; refs.body.dataset.section = "home"; refs.body.dataset.tab = tab; refs.body.dataset.view = view; refs.navHome.classList.add("active"); refs.tabs.forEach((button) => button.classList.toggle("active", button.dataset.tab === tab)); setHash(view === "overview" ? tab : view); render(); }
  function openChapter() { setTab("chapters", "chapter"); }
  function openQuiz() { setTab("quizzes", "quiz"); }
  function openAssignment() { setTab("assignments", "assignment"); }
  function renderHeader(title, intro) { refs.title.textContent = title; refs.intro.textContent = intro; }
  function renderChaptersOverview() { renderHeader("Chapters", "Open the extracted Module 1 lesson package. This static version removes course locks, progress gates, and saved completion state."); refs.content.innerHTML = `<div class="card-grid"><article class="course-card" style="--accent:#8b6a24"><p class="card-code">${escapeHtml(data.chapter.code)}</p><h4 class="card-title">${escapeHtml(data.chapter.title)}</h4><p class="card-summary">${escapeHtml(data.chapter.summary)}</p><div class="card-meta"><span><strong>${escapeHtml(String(data.chapter.componentCount))}</strong> lesson components extracted from Module 1.</span><span><strong>${escapeHtml(data.quiz.title)}</strong></span><span><strong>${escapeHtml(data.assignment.title)}</strong></span></div><div class="card-actions"><button class="btn btn-primary" type="button" data-action="open-chapter"><i class="fa-solid fa-arrow-right"></i> Open module</button><button class="btn btn-secondary" type="button" data-action="open-quiz"><i class="fa-solid fa-circle-question"></i> Take quiz</button><button class="btn btn-secondary" type="button" data-action="open-assignment"><i class="fa-solid fa-pen"></i> Assignment</button></div></article><article class="course-card" style="--accent:#59a844"><p class="card-code">Review flow</p><h4 class="card-title">Module 1 only</h4><p class="card-summary">The package keeps the content needed for review and Google delivery while stripping the full-course runtime.</p><div class="card-meta"><span>No completion buttons or locked cards.</span><span>No gatekeeping meter or saved browser state.</span><span>Only Module 1 runtime data.</span></div></article></div>`; }
  function renderChapterDetail() { renderHeader(data.chapter.title, data.chapter.summary); refs.content.innerHTML = `<div class="detail-stack"><article class="detail-card" style="--accent:#8b6a24"><p class="detail-eyebrow">${escapeHtml(data.chapter.code)}</p><h4 class="detail-title">${escapeHtml(data.chapter.title)}</h4><p class="detail-summary">The lesson opens below as a local static page. External videos remain external, and local images have been copied into the package.</p><div class="detail-actions"><button class="btn btn-secondary" type="button" data-action="back-chapters"><i class="fa-solid fa-arrow-left"></i> Back to chapters</button><button class="btn btn-primary" type="button" data-action="open-quiz"><i class="fa-solid fa-circle-question"></i> Take quiz</button><button class="btn btn-secondary" type="button" data-action="open-assignment"><i class="fa-solid fa-pen"></i> Assignment</button></div></article><iframe class="lesson-frame" src="./lesson.html" title="Module 1 lesson content"></iframe></div>`; }
  function calculateScore() { return data.quiz.multipleChoice.reduce((score, question) => { const selected = document.querySelector('input[name="question-' + question.number + '"]:checked'); return score + (selected && selected.value === question.answer ? 1 : 0); }, 0); }
  function renderQuiz() { renderHeader("Quizzes", "Answer the Module 1 quiz locally. Results are shown on screen only and are not saved."); const questions = data.quiz.multipleChoice.map((question) => { const options = question.options.map((option) => `<label class="quiz-option"><input type="radio" name="question-${escapeHtml(question.number)}" value="${escapeHtml(option.label)}" /><span><strong>${escapeHtml(option.label)}.</strong> ${escapeHtml(option.text)}</span></label>`).join(""); return `<section class="quiz-question" data-question="${escapeHtml(question.number)}"><h4>Question ${escapeHtml(question.number)}</h4><p>${escapeHtml(question.prompt)}</p><div class="quiz-options">${options}</div><div class="quiz-feedback" aria-live="polite"></div></section>`; }).join(""); refs.content.innerHTML = `<article class="quiz-shell" style="--accent:#59a844"><div class="quiz-copy"><p class="detail-eyebrow">${escapeHtml(data.chapter.code)}</p><h4 class="detail-title">${escapeHtml(data.quiz.title)}</h4><p>Select an answer for each question, then submit to check your score. Nothing is saved to the browser.</p></div><form id="quiz-form" class="quiz-form">${questions}<div class="quiz-actions"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-check"></i> Submit quiz</button><button class="btn btn-secondary" type="button" id="try-again"><i class="fa-solid fa-rotate-right"></i> Try again</button><button class="btn btn-secondary" type="button" data-action="open-assignment"><i class="fa-solid fa-pen"></i> Open assignment</button></div><p id="quiz-score" aria-live="polite"></p></form></article>`; document.getElementById("quiz-form").addEventListener("submit", (event) => { event.preventDefault(); const score = calculateScore(); document.getElementById("quiz-score").textContent = "Score: " + score + " / " + data.quiz.multipleChoice.length; data.quiz.multipleChoice.forEach((question) => { const card = document.querySelector('[data-question="' + question.number + '"]'); const selected = document.querySelector('input[name="question-' + question.number + '"]:checked'); const isCorrect = Boolean(selected && selected.value === question.answer); card.classList.toggle("is-correct", isCorrect); card.classList.toggle("is-incorrect", !isCorrect); card.querySelector(".quiz-feedback").textContent = isCorrect ? "Correct" : "Correct answer: " + question.answer; }); }); document.getElementById("try-again").addEventListener("click", () => { document.getElementById("quiz-form").reset(); document.getElementById("quiz-score").textContent = ""; document.querySelectorAll(".quiz-question").forEach((card) => { card.classList.remove("is-correct", "is-incorrect"); card.querySelector(".quiz-feedback").textContent = ""; }); }); }
  function renderAssignmentsOverview() { renderHeader("Assignments", "Launch the Module 1 assignment as part of the same static package."); refs.content.innerHTML = `<article class="course-card" style="--accent:#59a844"><p class="card-code">Assignment</p><h4 class="card-title">${escapeHtml(data.assignment.title)}</h4><p class="card-summary">Open the assignment inside the Option Two-style shell or launch it in a separate tab for review.</p><div class="card-actions"><button class="btn btn-primary" type="button" data-action="open-assignment"><i class="fa-solid fa-pen"></i> Open assignment</button><a class="btn btn-secondary" href="./assignment/module1assignment.html" target="_blank" rel="noopener"><i class="fa-solid fa-up-right-from-square"></i> Full screen</a></div></article>`; }
  function renderAssignmentDetail() { renderHeader(data.assignment.title, "The assignment is included locally and storage calls in the copied bundle have been neutralized for static review."); refs.content.innerHTML = `<div class="detail-stack"><article class="detail-card" style="--accent:#59a844"><p class="detail-eyebrow">Assignment</p><h4 class="detail-title">${escapeHtml(data.assignment.title)}</h4><p class="assignment-copy">Use this embedded version for review, or open the assignment full screen before placing it into a Google delivery target.</p><div class="assignment-actions"><button class="btn btn-secondary" type="button" data-action="back-assignments"><i class="fa-solid fa-arrow-left"></i> Back to assignments</button><a class="btn btn-primary" href="./assignment/module1assignment.html" target="_blank" rel="noopener"><i class="fa-solid fa-up-right-from-square"></i> Open full screen</a></div></article><div class="assignment-frame-shell"><iframe class="assignment-frame" src="./assignment/module1assignment.html" title="${escapeHtml(data.assignment.title)}"></iframe></div></div>`; }
  function render() { if (state.tab === "chapters" && state.view === "chapter") return renderChapterDetail(); if (state.tab === "quizzes") return renderQuiz(); if (state.tab === "assignments" && state.view === "assignment") return renderAssignmentDetail(); if (state.tab === "assignments") return renderAssignmentsOverview(); return renderChaptersOverview(); }
  refs.menuToggle?.addEventListener("click", () => { const collapsed = refs.body.classList.toggle("sidebar-collapsed"); refs.menuToggle.setAttribute("aria-expanded", String(!collapsed)); }); refs.navHome?.addEventListener("click", () => setTab("chapters")); refs.tabs.forEach((button) => button.addEventListener("click", () => setTab(button.dataset.tab))); refs.content.addEventListener("click", (event) => { const target = event.target.closest("[data-action]"); if (!target) return; const action = target.dataset.action; if (action === "open-chapter") openChapter(); if (action === "open-quiz") openQuiz(); if (action === "open-assignment") openAssignment(); if (action === "back-chapters") setTab("chapters"); if (action === "back-assignments") setTab("assignments"); });
  const initial = location.hash.slice(1); if (initial === "quiz" || initial === "quizzes") setTab("quizzes", "quiz"); else if (initial === "assignment" || initial === "assignments") setTab("assignments", initial === "assignment" ? "assignment" : "overview"); else if (initial === "chapter" || initial === "lesson") setTab("chapters", "chapter"); else setTab("chapters");
})();
