"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER 15 — spatial and control schematics.
a=Art(15,'cleavage','Cleavage: more cells, little overall growth',2,'The sequence distinguishes a single zygote, a solid morula and a blastocyst with an inner cell mass and cavity.')
for x in [230,650,1100]:a.circle(x,350,120,'#f6f8f3',TEAL)
a.circle(230,350,95,'#f8dfc8',ORANGE);a.circle(230,350,24,'#ead3e7',PURPLE);a.label('A',230,175,'Zygote',275,350)
for dx,dy in [(-55,-55),(0,-65),(55,-55),(-65,0),(0,0),(65,0),(-55,55),(0,65),(55,55)]:a.circle(650+dx,350+dy,31,'#f8dfc8',ORANGE,2)
a.label('B',650,175,'Morula',650,350);a.text(650,525,'Section: some cells are hidden',20,MUTED,'middle')
for ang in range(0,360,30):a.circle(1100+101*math.cos(math.radians(ang)),350+101*math.sin(math.radians(ang)),18,'#dfebe4',TEAL,2)
for dx,dy in [(-55,-40),(-45,-3),(-75,18),(-80,-18)]:a.circle(1100+dx,350+dy,23,'#efd9e7',PURPLE,2)
a.arrow(370,350,500,350);a.arrow(790,350,945,350)
a.label('C',1200,520,'Blastocyst cavity',1130,350);a.label('D',900,220,'Inner cell mass',1040,320);a.label('E',1310,200,'Trophoblast',1150,264)
a.wrap(700,620,'Cell number increases during cleavage. The early embryo does not enlarge in proportion to each division.',70,26,anchor='middle');a.save()
a=Art(15,'germ-layers','Three germ layers after gastrulation',4,'Three adjacent embryonic layers provide different tissue lineages. The coloured bands compare the layers; the spaces between bands do not represent cavities.')
for i,(c,ans,desc)in enumerate([('#cfe6f3','Ectoderm','Nervous system; epidermis'),('#f1d8dc','Mesoderm','Muscle; skeleton; blood and vessels'),('#f7e9b6','Endoderm','Digestive and respiratory epithelial linings')]):
 y=205+i*140;a.box(250,y,860,105,'',c);a.label(chr(65+i),125,y+50,ans,300,y+50);a.wrap(680,y+45,desc,48,26,anchor='middle')
a.text(700,690,'All three layers are parts of one developing embryo.',25,MUTED,'middle');a.save()
a=Art(15,'support','Early extraembryonic support structures',5,'The amnion surrounds the embryo and amniotic cavity; the chorion lies outside it. The yolk sac is separate from the amniotic cavity, and the connecting stalk links toward the outer tissues.')
a.ellipse(700,400,475,230,'#f3e5df',RED,5);a.ellipse(670,340,270,145,'#dfedf5',BLUE,4)
a.add(f'<path d="M580 330 C570 250 730 235 785 325 C820 400 710 420 650 375 C620 365 600 355 580 330Z" fill="#efd2c3" stroke="{ORANGE}" stroke-width="3"/>')
a.ellipse(640,550,100,58,'#f7e9b6',ORANGE,3);a.line(655,492,662,397,ORANGE,14)
a.add(f'<path d="M790 385 L1090 420 L1105 455 L785 410Z" fill="#dbb9aa" stroke="{ORANGE}" stroke-width="3"/>')
a.add(f'<path d="M750 392 Q825 435 930 429" fill="none" stroke="{TEAL}" stroke-width="8"/>')
a.label('A',300,155,'Chorion',475,197.4);a.label('B',880,155,'Amnion',800,213);a.label('C',410,355,'Amniotic cavity',485,325);a.label('D',420,590,'Yolk sac',580,550);a.label('E',1235,450,'Connecting stalk',1000,429);a.label('F',960,580,'Allantois',885,426);a.save()
a=Art(15,'placenta','Placental exchange: two separate circulations',7,'Maternal blood surrounds a chorionic villus. Fetal blood flows through vessels inside that villus. Oxygen and nutrients cross inward; carbon dioxide and wastes cross outward. The blood streams stay separate.')
a.box(70,190,770,500,'Maternal blood space','#f8e0dc',25)
a.add(f'<path d="M1220 265 L630 265 Q440 265 440 460 Q440 630 630 630 L1220 630 Z" fill="#f5e6d5" stroke="{RED}" stroke-width="7"/>')
a.add(f'<path d="M1220 330 L650 330 Q515 330 515 460" fill="none" stroke="{BLUE}" stroke-width="24"/>')
a.add(f'<path d="M515 460 Q515 560 650 560 L1220 560" fill="none" stroke="{RED}" stroke-width="24"/>')
a.arrow(1080,330,860,330,'white',3);a.arrow(860,560,1080,560,'white',3);a.text(995,295,'From fetus',23,BLUE,'middle');a.text(995,607,'To fetus',23,RED,'middle')
a.arrow(215,405,535,405,ORANGE,4);a.arrow(535,520,215,520,TEAL,4)
a.wrap(260,350,'Oxygen and nutrients',18,23,anchor='middle');a.wrap(245,580,'Carbon dioxide and wastes',19,23,anchor='middle')
a.label('A',110,160,'Maternal blood',170,290);a.label('B',865,705,'Chorionic villus barrier',745,630);a.label('C',1090,195,'Umbilical arteries',1060,330);a.label('D',1225,705,'Umbilical vein',1120,560)
a.text(930,455,'Fetal capillary',27,INK,'middle');a.text(930,492,'inside the villus',23,MUTED,'middle');a.save()
flow(15,'birth-feedback','Labour: an amplifying feedback loop',9,[('Cervical stretch','Pressure increases stretch at the cervix'),('Sensory signalling','Signals travel to the hypothalamus'),('Oxytocin release','Posterior pituitary releases a hormone'),('Uterine contraction','Uterine muscle contracts more strongly'),('Increased cervical stretch','Pressure reinforces the original stimulus'),('Birth ends the loop','Delivery removes the main stretch stimulus')],'The first five features reinforce cervical stretch; birth removes the principal stimulus. Prostaglandins can also support contractions.')
a=Art(15,'lactation','Lactation: production is not ejection',10,'Suckling can stimulate two hormonal responses: anterior-pituitary prolactin supports milk production, while posterior-pituitary oxytocin supports milk ejection.')
a.box(480,160,430,85,'Suckling → sensory input');a.arrow(560,260,330,335);a.arrow(820,260,1060,335)
for x,part,act,key1,key2,ans1,ans2 in [(150,'Anterior pituitary','Milk production','A','B','Prolactin','Milk production'),(860,'Posterior pituitary','Milk ejection','C','D','Oxytocin','Milk ejection')]:
 a.box(x,340,380,100,part);a.arrow(x+190,442,x+190,465);a.label(key1,x+190,490,ans1);a.arrow(x+190,515,x+190,550);a.box(x,565,380,105,'Secretory cells'if key1=='A'else'Myoepithelial contraction');a.label(key2,x+410,615,ans2,x+340,615)
a.save()


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[15];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[15],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',15,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
