import {momentumChange,averageForce,lockedCartVelocity} from './engine.js';
import {escapeHTML as h,number,panel,scene,prediction,table,field,selectField,explanation,checkButtons,formGate} from './ui.js';
function model(s,m){
 if(s.kind==='boundary')return '<p>The occupant and whole vehicle are separate systems. Select the system named by the question.</p>';
 if(s.kind==='carts'){const r=lockedCartVelocity(s.carts),t=Math.min(m.replayTime,8),locked=t>=2,x=locked?50+(t-2)*r.finalVelocity*5:20+t*s.carts[0].v*5;return `<div class="replay-stage" aria-label="Abstract cart replay"><span class="cart-model" style="left:${Math.min(80,x)}%">${locked?'Locked: 3 kg':'Cart 1: 2 kg'}</span>${locked?'':'<span class="cart-model" style="left:50%">Cart 2: 1 kg</span>'}</div><p>${locked?'Carts locked; both move at +2 m/s.':'Cart 1 approaches cart 2.'} Replay positions are illustrative; the signed ledger defines the result.</p>`+table(['System','Mass','Initial velocity','Initial momentum'],s.carts.map((c,i)=>['Cart '+(i+1),c.m+' kg',c.v+' m/s',c.m*c.v+' kg·m/s']),'Two-cart system before locking')+table(['Combined momentum','Combined mass','Final velocity'],[[r.initialMomentum+' kg·m/s',r.combinedMass+' kg',r.finalVelocity+' m/s']],'After locking: external impulse negligible');}
 const dp=momentumChange(s.mass,s.vi,s.vf),forces=s.times.map(t=>averageForce(dp,t)),max=Math.max(...forces.map(Math.abs));
 const elapsed=m.replayTime/40,span=Math.max(...s.times)*Math.abs(s.vi)/2;
 const rows=s.times.map(duration=>{const t=Math.min(elapsed,duration),x=s.vi*t+(s.vf-s.vi)*t*t/(2*duration),v=s.vi+(s.vf-s.vi)*t/duration;return{duration,t,x,v};});
 const tracks=`<div class="replay-stage comparison-track">${rows.map((r,i)=>`<span class="cart-model" style="top:${12+i*45}px;bottom:auto;left:${Math.min(80,Math.abs(r.x)/span*75)}%">Fixture ${i+1}</span>`).join('')}</div>`;
 return tracks+'<details class="model-table"><summary>Synchronized stopping data</summary>'+table(['Stop duration','Elapsed','Velocity','Travel'],rows.map(r=>[r.duration+' s',number(r.t)+' s',number(r.v)+' m/s',number(r.x)+' m']),'Synchronized stopping comparisons')+'</details>'+`<p class="small-note">Same occupant and velocity change. Replay is slowed 40×; constant deceleration illustrates the comparison.</p>`;
}
function results(s){if(s.kind==='boundary'||s.kind==='carts')return'';const dp=momentumChange(s.mass,s.vi,s.vf),forces=s.times.map(t=>averageForce(dp,t)),max=Math.max(...forces.map(Math.abs));return `<div class="result-metrics"><div><span>Signed momentum change (Δp)</span><strong>${number(dp)}<small>kg·m/s</small></strong><small>m(v − u), same in both fixtures</small></div><div><span>Stopping durations (Δt)</span><strong>${s.times.join(' / ')}<small>s</small></strong><small>Only duration changes</small></div>${forces.map((f,i)=>`<div><span>Average net force ${i===0?'A':'B'}</span><strong>${number(f)}<small>N</small></strong><small>Magnitude ${number(Math.abs(f))} N</small></div>`).join('')}</div><div class="force-bars"><h3>Average force magnitude</h3>${s.times.map((t,i)=>`<div class="force-row"><span>${t} s</span><div class="force-bar"><span style="width:${Math.abs(forces[i])/max*100}%"></span></div><strong>${number(Math.abs(forces[i]))} N</strong></div>`).join('')}</div><p class="small-note">Signed force is opposite the positive initial velocity. Longer stopping time reduces average force for the same impulse; impulse stays Δp.</p>`;}
export function render(s,m,transfer=false){
 let data,fields;
 if(s.kind==='boundary'){data=table(['System','Supplied mass'],[['Occupant',s.occupant_mass+' kg'],['Whole vehicle',s.vehicle_mass+' kg']]);fields=selectField('system','Ledger system',m.modelInputs.system,[['occupant','Occupant'],['vehicle','Whole vehicle']])+field('mass','Mass used in occupant ledger',m.modelInputs.mass,'kg');}
 else if(s.kind==='carts'){data=table(['Cart','Mass','Signed velocity'],s.carts.map((c,i)=>['Cart '+(i+1),c.m+' kg','+'+c.v+' m/s']));fields=field('initialMomentum','Combined initial momentum',m.modelInputs.initialMomentum,'kg·m/s')+field('combinedMass','Combined mass',m.modelInputs.combinedMass,'kg')+field('finalVelocity','Locked-cart velocity',m.modelInputs.finalVelocity,'m/s')+selectField('energy','Kinetic energy',m.modelInputs.energy,[['not-guaranteed','Not claimed conserved in the locking collision'],['conserved','Always conserved in the locking collision']]);}
 else{data=table(['Quantity','Supplied value'],[['Occupant mass',s.mass+' kg'],['Initial velocity','+'+s.vi+' m/s'],['Final velocity',s.vf+' m/s'],['Duration A',s.times[0]+' s'],['Duration B',s.times[1]+' s']]);fields=field('deltaP','Signed momentum change',m.modelInputs.deltaP,'kg·m/s')+s.times.map((t,i)=>field('force'+i,'Average net force at '+t+' s',m.modelInputs['force'+i],'N')).join('');}
 return panel(transfer?'Fresh Transfer':'Test Setup',1,'State the system boundary',(transfer?'':scene(s,'Context illustration of an abstract stopping fixture'))+data+(transfer?'':prediction(s,m)))+
 panel(transfer?'Your Response':'Momentum & Force Ledger',2,'Signs and units visible',`<div id="force-results">${m.revealed||m.firstTransferResponse?results(s):''}</div>`+formGate(m,fields,transfer)+explanation(m.explanation,s.explanationPrompt)+checkButtons(m,transfer))+
 panel('Controlled Comparison',3,'Change duration, keep Δp fixed',`<div id="force-model">${m.revealed?model(s,m):'<p>Commit a prediction, then run the abstract comparison. The independent transfer has no bars or replay before submission.</p>'}</div>${transfer&&!m.firstTransferResponse?'':'<div class="btn-row"><button class="btn primary" data-action="replay">Run comparison</button><button class="btn" data-action="step">Step</button><button class="btn" data-action="pause">Pause</button></div>'}<p>Average force is not peak force and does not establish injury risk or restraint certification.</p>`);
}
export function refresh(root,s,m){const el=root.querySelector('#force-model');if(el&&(m.predictionLocked||s.stage==='worked'||m.firstTransferResponse))el.innerHTML=model(s,m);const r=root.querySelector('#force-results');if(r&&(m.revealed||s.stage==='worked'||m.firstTransferResponse))r.innerHTML=results(s);}
export function worked(){}
