import fs from 'node:fs/promises';
import path from 'node:path';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const document=(title,body)=>`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{margin:0;background:#fafcfa;color:#172b23;font:16px/1.5 Arial,sans-serif}header{background:#17271f;color:white;padding:24px}main{max-width:1500px;margin:auto;padding:24px}h1{margin:0}section{margin:30px 0;border-top:1px solid #b5cfc2;padding-top:20px}a{color:#125933;display:inline-block;min-height:44px}img{display:block;max-width:100%;height:auto;border:1px solid #cad9d0}figure{margin:16px 0}figcaption{padding:8px 0}.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.mobile{max-width:390px}@media(max-width:800px){.gallery{grid-template-columns:1fr}}:focus-visible{outline:3px solid #087c36;outline-offset:3px}</style><header><h1>${esc(title)}</h1></header><main>${body}</main></html>`;
export async function buildVisualReview({root,dir,suite,candidate}){
 const sections=[];
 for(const g of suite.games.slice(1)){
  const links=[];
  for(const [name,label]of [['title','Title'],['worked','Worked demonstration'],['feedback','Feedback after actual response'],['transfer','First transfer response']])links.push(`<figure><img loading="lazy" src="validation/browser/${g.id}-${name}-1440.png" alt="${esc(g.id+' '+label+' actual Chromium screenshot')}"><figcaption>${esc(label)} — implemented candidate, not an approved reference.</figcaption></figure>`);
  sections.push(`<section><h2>${esc(g.id+' '+g.title)}</h2><p><a href="games/${g.id}/PLAY.html">Play offline</a> · <a href="component-boards/${g.id}.html">Component board</a></p><figure><img loading="lazy" src="audit-records/premium-visual-v1/references/${g.id}-premium-gameplay.png" alt="${esc(g.id+' unchanged user premium reference')}"><figcaption>Supplied visual authority; science corrections are recorded in the production handoff.</figcaption></figure><div class="gallery">${links.join('')}</div><figure class="mobile"><img loading="lazy" src="validation/browser/${g.id}-worked-390.png" alt="${esc(g.id+' implemented mobile worked screenshot')}"><figcaption>Mobile implementation at 390 px. No independent approved premium mobile reference was supplied.</figcaption></figure></section>`);
  const board=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(g.id)} component board</title><link rel="stylesheet" href="../sources/${g.id}/css/shell.css"><link rel="stylesheet" href="../sources/${g.id}/css/game.css"><style>body{padding:24px;min-height:100vh}.board{max-width:1250px;margin:auto}.sample{margin:24px 0}.sample img{max-width:100%;height:auto}.board a{display:inline-block;min-height:44px}.samples{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}@media(max-width:700px){.samples{grid-template-columns:1fr}}</style><main class="board"><h1>${esc(g.id+' '+g.title)} component board</h1><p>Candidate ${esc(candidate.id)}. Presentation samples only. These controls do not submit learner answers.</p><a href="../VISUAL_REVIEW.html">Return to visual review</a><section class="panel sample"><h2>Scene plate</h2><img src="../sources/${g.id}/assets/premium/scene-v1.png" alt="Illustrative premium context; science data is rendered separately"></section><div class="samples"><section class="panel sample"><h2>Controls and focus</h2><p><button type="button">Primary action sample</button></p><p><button type="button" class="secondary">Secondary action sample</button></p><label for="sample-${g.id}">Labelled quantity sample</label><input id="sample-${g.id}" type="number" placeholder="Enter a value"><p>Real mechanics and keyboard behavior are reviewed in the game.</p></section><section class="panel sample"><h2>Feedback and typography</h2><h3>Model result</h3><p>Model correctness, support used and explanation review remain separate.</p><div class="feedback good">A supported result explains its evidence and units.</div><div class="feedback">An editable response invalidates its previous check.</div><p><strong>Transfer:</strong> Preserve the first response and distinguish later correction.</p></section></div></main></html>`;
  await fs.mkdir(path.join(dir,'component-boards'),{recursive:true});await fs.writeFile(path.join(dir,'component-boards',g.id+'.html'),board);
 }
 await fs.writeFile(path.join(dir,'VISUAL_REVIEW.html'),document('Science 24 premium visual review',`<p>Candidate ${esc(candidate.id)}. A1 remains unchanged as the visual floor.</p><p>The strict pixel/geometry gate remains open. Original references and candidate screenshots are separate. Title, feedback, transfer and mobile screenshots document implementation; they are not independently accepted visual baselines.</p><a href="START_REVIEW.html">Return to eight-game launcher</a>${sections.join('')}`));
}
