"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER20

a=Art(20,'distribution','Equal counts, different spatial patterns',1,'Each panel contains twelve individuals in the same area. The arrangements differ even though their average densities are equal.',subtitle='Constructed spatial examples — 12 individuals per equal-area panel')
positions=[[(40,40),(70,50),(48,78),(82,83),(165,180),(195,175),(174,210),(202,212),(260,50),(285,45),(272,82),(302,77)],[(50+i*87,45+j*95)for j in range(3)for i in range(4)],[(36,32),(103,72),(221,44),(306,104),(175,166),(49,241),(282,247),(135,278),(319,302),(47,136),(225,289),(317,22)]]
for i,(ps,ans)in enumerate(zip(positions,['Clumped','Uniform','Random'])):
 x=75+i*455;a.box(x,240,390,365,'')
 for px,py in ps:a.circle(x+px+18,255+py,10,TEAL,'white',1)
 a.label(chr(65+i),x+195,180,ans)
a.text(700,700,'A map shows distribution. A count divided by area gives density.',26,INK,'middle');a.save()
a=Art(20,'change','Population accounting across a boundary',2,'Births and immigration add individuals; deaths and emigration remove individuals. The totals must describe the same population and interval.')
a.box(470,295,470,270,'Population\nN₀ → N₀ + ΔN',size=30)
a.box(80,180,290,115,'New offspring',size=25);a.arrow(370,260,470,345);a.label('A',225,145,'Births')
a.box(80,540,290,115,'Individuals enter',size=25);a.arrow(370,580,470,500);a.label('B',225,710,'Immigration')
a.box(1030,180,290,115,'Individuals die',size=25);a.arrow(940,345,1030,260);a.label('C',1170,145,'Deaths')
a.box(1030,540,290,115,'Individuals leave',size=25);a.arrow(940,500,1030,580);a.label('D',1170,710,'Emigration');a.save()
a=Art(20,'rates','Choose the denominator that answers the question',3,'For N₀ = 200 and N₁ = 260 over three years, change is 60, average rate is 20 individuals/year and interval per-capita change is 0.30.',subtitle='Constructed example — a three-year interval is not one year')
for i,(desc,num,ans)in enumerate([('260 − 200','60 individuals','Net change'),('(260 − 200) / 3','20 individuals/year','Average growth rate'),('(260 − 200) / 200','0.30 over three years','Interval per-capita change')]):
 y=190+i*170;a.box(120,y,1120,125,'');a.text(250,y+50,desc,30);a.text(750,y+55,num,28,TEAL,'middle');a.label(chr(65+i),1275,y+60,ans)
a.save()
a=Art(20,'growth','Population growth: compare the curve and its slope',4,'The exponential curve steepens while the logistic curve slows near K. Both are constructed models, not measured population observations.',subtitle='Constructed model curves — arbitrary population units')
x0,y0=130,655;x1,y1=1250,195;a.arrow(x0,y0,x1+40,y0,INK,3);a.arrow(x0,y0,x0,y1-20,INK,3);a.text(730,717,'Time',25,INK,'middle');a.text(82,215,'N',30,INK,'middle')
K=245;a.line(x0,K,x1,K,MUTED,3,'8 6')
log=[];exp=[]
for i in range(100):
 t=i/99;x=x0+t*(x1-x0);val=1/(1+math.exp(-9*(t-.42)));log.append((x,y0-410*val));ev=math.exp(3.6*t)-1;exp.append((x,y0-450*ev/(math.exp(3.6)-1)))
for pts,c in [(log,TEAL),(exp,ORANGE)]:a.add('<polyline points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="none" stroke="{c}" stroke-width="6"/>')
a.label('A',1085,145,'Carrying capacity K',1090,K);a.label('B',630,315,'Logistic model',700,655-410/(1+math.exp(-9*((700-130)/1120-.42))));a.label('C',1150,505,'Exponential model',1070,655-450*(math.exp(3.6*((1070-130)/1120))-1)/(math.exp(3.6)-1));a.save()
a=Art(20,'survivorship','Survivorship is not population size through time',6,'The curves compare survival across age: Type I has greater late loss, Type II a steadier risk on a log-survivor plot, and Type III strong early loss.',subtitle='Constructed patterns — vertical axis is log survivors')
x0,y0=150,660;a.arrow(x0,y0,1260,y0,INK,3);a.arrow(x0,y0,x0,175,INK,3);a.text(710,725,'Age',28,INK,'middle');a.text(95,205,'log',22,INK,'middle');a.text(78,235,'survivors',20,INK,'middle')
curves=[([(150,205),(550,220),(850,270),(1000,420),(1170,640)],TEAL),([(150,205),(1170,640)],BLUE),([(150,205),(235,410),(430,550),(750,610),(1170,640)],ORANGE)]
for ps,c in curves:a.add('<polyline points="'+' '.join(f'{x},{y}'for x,y in ps)+f'" fill="none" stroke="{c}" stroke-width="6"/>')
a.label('A',780,170,'Type I',720,250);a.label('B',820,390,'Type II',740,457);a.label('C',430,660,'Type III',420,545);a.save()
a=Art(20,'predator-prey','Predator response can lag behind prey',7,'The constructed predator series peaks after the prey series. This is consistent with a delayed demographic response, but the curves alone do not prove a unique cause.',subtitle='Constructed time series — independently scaled relative abundance')
a.arrow(125,660,1290,660,INK,3);a.arrow(125,660,125,175,INK,3);a.text(735,725,'Time',27,INK,'middle');a.text(85,210,'Relative N',21,INK,'middle')
for shift,col in [(0,TEAL),(.7,ORANGE)]:
 ps=[]
 for i in range(180):
  t=i/179*11;x=150+i/179*1100;y=445-160*math.sin(t-shift);ps.append((x,y))
 a.add('<polyline points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in ps)+f'" fill="none" stroke="{col}" stroke-width="5"/>')
a.label('A',320,185,'Prey curve',308,285);a.label('B',510,225,'Predator curve',378,285);a.line(307.08,235,377.08,235,INK,3);a.line(307.08,225,307.08,245,INK,3);a.line(377.08,225,377.08,245,INK,3);a.label('C',695,160,'Time lag',342.08,235);a.save()
a=Art(20,'symbiosis','Classify the effects on both partners',9,'Each pair of signs records the effects on the two partners in the stated setting, not moral value. A plus indicates benefit, zero no appreciable effect and minus harm.')
for i,(pair,ans)in enumerate([('+/+','Mutualism'),('+/0','Commensalism'),('+/−','Parasitism')]):
 x=110+i*450;a.box(x,280,355,250,'');a.text(x+178,400,pair,64,TEAL,'middle');a.label(chr(65+i),x+178,610,ans)
a.save()
a=Art(20,'succession','Succession depends on what remains',10,'The upper case starts on exposed rock without developed soil. The lower case retains soil, seeds and roots after disturbance. Local conditions influence the subsequent pathway.')
for row,(y,txt,ans,soil)in enumerate([(245,'Exposed rock; little biological legacy','Primary succession',False),(535,'Soil, seeds and roots remain','Secondary succession',True)]):
 a.box(80,y-60,850,150,'');a.line(115,y+20,880,y+20,ORANGE,16 if soil else 5)
 if soil:
  for x in range(155,850,95):a.line(x,y+10,x+20,y-20,TEAL,4);a.circle(x+15,y+45,6,ORANGE,ORANGE)
 else:
  for x in range(130,850,120):a.add(f'<polygon points="{x},{y+15} {x+40},{y-10} {x+90},{y+15}" fill="#c2c9c2"/>')
 a.text(500,y-15,txt,26,INK,'middle');a.arrow(950,y,1080,y);a.label(chr(65+row),1180,y,ans)
a.save()


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[20];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[20],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',20,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
