(async function(){'use strict';
const slug='math10c-unit3-textbook-3',questions=JSON.parse(document.getElementById('question-data').textContent),bridge=window.__canvasHelperScorm;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const blank=()=>({v:1,rev:0,route:'overview',selected:[],answers:[]});let state=blank(),saver,blocked=true;
function clean(raw){let value=typeof raw==='string'?JSON.parse(raw):JSON.parse(JSON.stringify(raw));if(!value||value.v!==1||!Number.isSafeInteger(value.rev)||value.rev<0||typeof value.route!=='string'||!Array.isArray(value.selected)||!Array.isArray(value.answers))throw Error('This saved textbook notebook uses an unknown format. The original has been retained for recovery.');const pages=new Set(['overview',...$$('[data-section-id]').map(x=>x.id)]);if(!pages.has(value.route))value.route='overview';const answerMap=new Map();for(const row of value.answers){if(!Array.isArray(row)||row.length!==2||!Number.isSafeInteger(row[0])||row[0]<0||row[0]>=questions.length||typeof row[1]!=='string'||row[1].length>600)throw Error('A saved textbook response is invalid. The original has been retained for recovery.');if(row[1])answerMap.set(row[0],row[1]);}const selected=new Map();for(const row of value.selected){if(!Array.isArray(row)||row.length!==2||typeof row[0]!=='string'||!Number.isSafeInteger(row[1])||row[1]<0||row[1]>=questions.length||questions[row[1]].section!==row[0])throw Error('A saved question selection is invalid. The original has been retained for recovery.');selected.set(row[0],row[1]);}return{v:1,rev:value.rev,route:value.route,selected:[...selected],answers:[...answerMap]};}
function snapshot(){return clean(state)}function validate(value){const text=JSON.stringify(clean(value));if(text.length>55000)throw Error('This notebook is too large for safe SCORM saving. The last saved copy is unchanged; copy the visible response before leaving.');return text}
function setState(value){state=clean(value)}function answer(index){return new Map(state.answers).get(index)||''}function selection(section){return new Map(state.selected).get(section)}
function status(text,error=false){const node=$('#save-status');node.textContent=text;node.style.color=error?'#ffd0c7':''}
function recovery(branches,message){$('#recovery').hidden=false;$('#recovery-message').textContent=message;const host=$('#recovery-versions');host.innerHTML='';branches.forEach((b,i)=>{const a=document.createElement('article');const h=document.createElement('h3');h.textContent='Saved copy '+(i+1);const p=document.createElement('p');p.textContent=b.label+(b.durable?' · preserved in this browser':' · copy before closing this tab');const t=document.createElement('textarea');t.readOnly=true;t.rows=4;t.value=b.raw;a.append(h,p,t);host.append(a);});}
function writable(value){blocked=!value;for(const node of $$('textarea,[data-question-index]'))node.disabled=!value}
saver=window.MathSaveController.create({bridge,key:slug+':notebook:v1',getSnapshot:snapshot,setState,decode:clean,validate,onStatus:status,onRecovery:recovery,onWritable:writable,completedIds:()=>[]});
function update(next){if(blocked)return;state=clean(next);state.rev++;saver.edited()}
function showQuestion(index,focus=true){const q=questions[index],section=$(`[data-section-id="${CSS.escape(q.section)}"]`),stage=$('[data-question-stage]',section);if(!q||!stage)return;const figure=document.createElement('figure');figure.className='question-preview';const caption=document.createElement('figcaption');caption.textContent=q.label+' · printed p. '+q.printed;const image=document.createElement('img');image.src=q.image;image.alt='Textbook excerpt for '+q.label+', printed page '+q.printed;image.loading='lazy';figure.append(caption,image);const label=document.createElement('label');label.className='work-label';const strong=document.createElement('strong');strong.textContent='My written work for '+q.label;const help=document.createElement('span');help.textContent='Saved automatically · up to 600 characters';const textarea=document.createElement('textarea');textarea.maxLength=600;textarea.value=answer(index);textarea.dataset.answerIndex=String(index);textarea.disabled=blocked;label.append(strong,help,textarea);stage.replaceChildren(figure,label);for(const b of $$('[data-question-index]',section))b.setAttribute('aria-pressed',String(Number(b.dataset.questionIndex)===index));if(focus){stage.scrollIntoView({block:'nearest'});textarea.focus({preventScroll:true});const selected=new Map(state.selected);selected.set(q.section,index);update({...state,selected:[...selected]});}}
function printableWork(){const entries=[...new Map(state.answers)].filter(([index,work])=>questions[index]&&work.trim());const message=$('#print-message');if(!entries.length){message.textContent='Enter some written work beside a question before printing.';return}message.textContent='Preparing '+entries.length+' written '+(entries.length===1?'response':'responses')+' for printing…';const sheet=$('#print-sheet');sheet.replaceChildren();const title=document.createElement('h1');title.textContent=$('h1').textContent.trim()+' — my written work';const details=document.createElement('p');details.className='print-details';details.textContent='Name: ____________________________________    Date: __________________';const instructions=document.createElement('p');instructions.textContent='Save this as a PDF or print it, then upload it to the Math 10C evidence dropbox in Brightspace. This sheet is not submitted by the textbook activity.';sheet.append(title,details,instructions);const images=[];for(const [index,work] of entries){const q=questions[index],section=document.createElement('section'),heading=document.createElement('h2'),image=document.createElement('img'),answer=document.createElement('div'),label=document.createElement('h3');section.className='print-response';heading.textContent=q.section+' · '+q.label+' · printed p. '+q.printed;image.src=q.image;image.alt='Textbook excerpt for '+q.label;answer.className='print-answer';answer.textContent=work;label.textContent='My work';section.append(heading,image,label,answer);sheet.append(section);images.push(image)}sheet.hidden=false;Promise.allSettled(images.map(image=>image.decode())).then(()=>{message.textContent='Print window ready. Choose Save as PDF there if you want to upload a file.';window.print()})}
window.addEventListener('afterprint',()=>{$('#print-sheet').hidden=true});
$('#print-work').addEventListener('click',printableWork);
function openReader(button){const section=button.closest('[data-section-id]'),stage=$('[data-reader-stage]',section),opening=stage.hidden||stage.dataset.file!==button.dataset.readerFile;if(!opening){stage.hidden=true;return}const head=document.createElement('header'),h=document.createElement('h3'),close=document.createElement('button'),frame=document.createElement('iframe');h.textContent=button.dataset.readerTitle;close.type='button';close.textContent='Close full pages';close.addEventListener('click',()=>{stage.hidden=true;button.focus()});frame.title=button.dataset.readerTitle;frame.src=button.dataset.readerFile;head.append(h,close);stage.replaceChildren(head,frame);stage.dataset.file=button.dataset.readerFile;stage.hidden=false;stage.scrollIntoView({block:'nearest'});}
document.addEventListener('click',e=>{const q=e.target.closest('[data-question-index]');if(q){showQuestion(Number(q.dataset.questionIndex));return}const r=e.target.closest('[data-reader-file]');if(r)openReader(r)});
document.addEventListener('input',e=>{const t=e.target;if(!t.matches('[data-answer-index]')||blocked)return;const answers=new Map(state.answers),index=Number(t.dataset.answerIndex);if(t.value)answers.set(index,t.value);else answers.delete(index);update({...state,answers:[...answers]})});
function route(){const pages=new Set(['overview',...$$('[data-section-id]').map(x=>x.id)]);let page=location.hash.slice(1);if(!pages.has(page))page=state.route&&pages.has(state.route)?state.route:'overview';for(const a of $$('[data-page-link]'))a.toggleAttribute('aria-current',a.dataset.pageLink===page);if(state.route!==page&&!blocked)update({...state,route:page})}
window.addEventListener('hashchange',route);window.addEventListener('canvas-helper:scorm-status',e=>saver.accept(e.detail));window.addEventListener('storage',e=>saver.observeStorage(e));window.addEventListener('beforeunload',()=>saver.teardown());
await saver.open();for(const [section,index] of state.selected)showQuestion(index,false);route();
window.TextbookNotebookDebug={snapshot:()=>snapshot(),questionCount:questions.length,stateChars:()=>JSON.stringify(snapshot()).length,ready:()=>!blocked};
})();
