/** Runs inside A's existing runtime closure. No new persisted keys. */
export const A_VOCABULARY_BRIDGE = String.raw`
  var inlineVocabularyStatus="Writing saves as you type. Each field allows 240 characters.";
  var choiceManager=document.createElement("details");choiceManager.setAttribute("data-a-frayer-choices","");
  choiceManager.innerHTML='<summary>Manage my two chosen concepts</summary><p>Keep a copy and explicitly clear writing before replacing a choice. Six module anchors cannot be replaced.</p><div data-a-choice-list></div><p role="status" data-a-choice-status></p>';
  document.querySelector("[data-vocabulary-reader]").appendChild(choiceManager);
  function refreshInlineFrayers(){
    document.querySelectorAll("[data-frayer]").forEach(updateFrayer);
    var list=choiceManager.querySelector("[data-a-choice-list]");list.replaceChildren();
    state.vocabulary.choiceIds.forEach(function(id){var row=document.createElement("div"),label=document.createElement("label"),check=document.createElement("input"),button=document.createElement("button");check.type="checkbox";label.append(check," I have kept a copy of "+document.querySelector('[data-vocabulary-target="'+id+'"] span').textContent+" and want to clear and remove this choice.");button.type="button";button.textContent="Clear and remove this choice";button.disabled=true;check.addEventListener("change",function(){button.disabled=!check.checked});button.addEventListener("click",function(){if(!check.checked)return;var previousResponses=Object.assign({},state.responses),previousChoices=state.vocabulary.choiceIds.slice(),previousCollected=state.vocabulary.collectedIds.slice();frayerFields(id).forEach(function(field){delete state.responses[field.getAttribute("data-response-id")]});state.vocabulary.choiceIds=state.vocabulary.choiceIds.filter(function(value){return value!==id});state.vocabulary.collectedIds=state.vocabulary.collectedIds.filter(function(value){return value!==id});var result=save();inlineVocabularyStatus=saveMessage(result);if(!saveSucceeded(result)){state.responses=previousResponses;state.vocabulary.choiceIds=previousChoices;state.vocabulary.collectedIds=previousCollected;choiceManager.querySelector("[data-a-choice-status]").textContent="Clear was not saved. Writing and choices have been kept.";return}frayerFields(id).forEach(function(field){field.value=""});refreshInlineFrayers();renderCollections();updateVocabulary();choiceManager.querySelector("[data-a-choice-status]").textContent="Only this choice was cleared and removed."});row.append(label,button);list.append(row)});
  }
  document.querySelectorAll("[data-frayer-field]").forEach(function(field){field.setAttribute("data-frayer-limit",field.getAttribute("maxlength")||"240");field.removeAttribute("maxlength");var note=document.createElement("span");note.textContent="Maximum 240 characters. Oversized writing stays visible but cannot be saved.";field.after(note)});
  document.querySelectorAll("[data-frayer]").forEach(function(root){
    var id=root.getAttribute("data-frayer"),details=document.createElement("details"),summary=document.createElement("summary"),label=document.createElement("label"),check=document.createElement("input"),button=document.createElement("button"),status=document.createElement("p");
    summary.textContent="Clear this Frayer's writing";check.type="checkbox";label.append(check," I have kept a copy and want to clear only this Frayer.");button.type="button";button.textContent="Clear this Frayer";button.disabled=true;status.setAttribute("data-a-frayer-save-status","");status.setAttribute("role","status");
    check.addEventListener("change",function(){button.disabled=!check.checked});
    button.addEventListener("click",function(){if(!check.checked)return;var previous=Object.assign({},state.responses),collected=state.vocabulary.collectedIds.slice();frayerFields(id).forEach(function(field){delete state.responses[field.getAttribute("data-response-id")]});state.vocabulary.collectedIds=state.vocabulary.collectedIds.filter(function(value){return value!==id});var result=save();if(!saveSucceeded(result)){state.responses=previous;state.vocabulary.collectedIds=collected;status.textContent="Clear was not saved. Your writing remains available.";return}frayerFields(id).forEach(function(field){field.value=""});check.checked=false;button.disabled=true;updateFrayer(root);renderCollections();updateVocabulary();status.textContent="Only this Frayer's writing was cleared. "+saveMessage(result)});
    details.append(summary,label,button);root.querySelector("[data-frayer-fields]").append(details,status);
  });
  window.biologyVocabulary={unlocked:function(id){var button=document.querySelector('[data-vocabulary-target="'+id+'"]');return Boolean(button&&vocabularyUnlocked(button))},refresh:refreshInlineFrayers,status:function(){return inlineVocabularyStatus},selectedFamilies:function(){return state.vocabulary.choiceIds.slice()}};
  document.addEventListener("click",function(event){var button=event.target.closest&&event.target.closest("[data-select-frayer]");if(!button)return;queueMicrotask(function(){refreshInlineFrayers();if(state.vocabulary.choiceIds.length>=2){choiceManager.open=true;choiceManager.querySelector("[data-a-choice-status]").textContent="Both learner-choice slots are occupied. Existing writing is protected by the confirmation controls below."}})});
  refreshInlineFrayers();
`;
