import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
type Entry={id:string;label:string;familyTerms:string[];learnerDefinition:string;primaryLessonIds:string[];wordAnalysis:{kind:string;parts:{text:string;meaning:string}[];caution?:string}};
/** Generated by A's authored renderer; contains reference data, never learner state. */
export function renderAVocabularyPanel(entries:Entry[]){
  const families=entries.map(e=>({id:e.id,label:e.label,meaning:e.learnerDefinition,routes:e.primaryLessonIds,wordAnalysis:[e.wordAnalysis.kind.replace(/-/g,' '),...e.wordAnalysis.parts.map(p=>`${p.text}: ${p.meaning}`),...(e.wordAnalysis.caution?[e.wordAnalysis.caution]:[])]}));
  const terms=entries.flatMap(e=>[...new Set([e.label,...e.familyTerms])].map(term=>({term,familyIds:[e.id],...(term===e.label?{definition:e.learnerDefinition}:{})})));
  const bundle=buildSync({entryPoints:[fileURLToPath(new URL('./a-entry.ts',import.meta.url))],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022'}).outputFiles[0].text;
  return `<script type="application/json" id="bio-inline-vocabulary-data">${JSON.stringify({families,terms}).replace(/</g,'\\u003c')}</script><script>${bundle.replace(/<\/script/gi,'<\\/script')}</script>`;
}
