"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER18

a=Art(18,'dna','Complementarity and antiparallel direction',2,'An upper 5′-ATGC-3′ strand aligns with a lower 3′-TACG-5′ strand. The bases pair A–T and G–C, while strand directions oppose each other.')
for y in [270,535]:a.line(200,y,1200,y,TEAL,9)
a.text(140,280,'5′',34,INK,'middle');a.text(1270,280,'3′',34,INK,'middle');a.text(140,545,'3′',34,INK,'middle');a.text(1270,545,'5′',34,INK,'middle')
for i,(up,lo)in enumerate(zip('ATGC','TACG')):
 x=340+i*230;a.line(x,270,x,345,INK,3);a.line(x,455,x,535,INK,3);a.box(x-55,345,110,110,up+' / '+lo,fill='#f6f0df',size=26);a.line(x-35,408,x+35,408,TEAL,2,'5 5')
a.label('A',350,165,'Sugar–phosphate backbone',480,270);a.label('B',700,640,'Complementary base pair',800,395);a.label('C',1200,170,'3′ end',1270,270);a.label('D',180,655,'3′ end',140,535);a.save()
a=Art(18,'replication','Replication products: semiconservative',3,'Each daughter double-stranded molecule contains one old strand and one new strand. The diagram follows strand identity rather than chromosome number.',subtitle='Blue = parental strand · orange = newly synthesized strand')
for y in [345,415]:a.line(100,y,425,y,BLUE,12)
a.text(250,230,'Parental molecule',28,INK,'middle');a.arrow(465,380,650,275);a.arrow(465,380,650,520)
for idx,y in enumerate([275,525]):
 a.line(720,y-30,1260,y-30,BLUE,12);a.line(720,y+30,1260,y+30,ORANGE,12)
 for x in range(745,1250,40):a.line(x,y-25,x,y+25,BORDER,2)
 a.label(chr(65+idx*2),795,y-100,'Parental strand',915,y-30);a.label(chr(66+idx*2),1180,y+100,'New strand',1080,y+30)
a.save()
a=Art(18,'transcription','Coding DNA, template DNA and mRNA',5,'RNA polymerase reads the template 3′ to 5′ to produce complementary RNA 5′ to 3′. Coding DNA matches the message apart from T versus U.')
for y,seq,c in [(245,'5′– ATG  AAA  GGG  TAA –3′',BLUE),(385,'3′– TAC  TTT  CCC  ATT –5′',ORANGE),(630,'5′– AUG  AAA  GGG  UAA –3′',TEAL)]:a.box(350,y-60,970,105,seq,fill='#f7f8f4',size=32)
a.label('A',155,230,'Coding DNA strand',350,230);a.label('B',155,370,'Template DNA strand',350,370);a.arrow(840,445,840,535);a.label('C',1040,495,'Transcription',845,495);a.label('D',155,615,'mRNA',350,615);a.save()
a=Art(18,'translation','Read the message in codons',6,'A ribosome reads mRNA 5′ to 3′. A paired tRNA anticodon supplies its amino acid; the stop codon terminates rather than adding an amino acid.')
a.line(130,490,1260,490,TEAL,7)
for x,s in [(240,'AUG'),(480,'UUU'),(720,'GGC'),(1080,'UAA')]:a.box(x-100,450,200,82,s,fill='#e7f1ea',size=30)
a.text(95,505,'5′',28);a.text(1300,505,'3′',28);a.ellipse(720,470,165,135,'none',PURPLE,5)
a.line(720,355,720,255,PURPLE,7);a.text(720,350,'3′-CCG-5′',28,PURPLE,'middle');a.circle(720,215,35,'#f7e9b6',ORANGE);a.text(720,223,'Gly',22,INK,'middle')
a.label('A',390,590,'mRNA codon',480,490);a.label('B',1010,315,'tRNA anticodon',760,342);a.label('C',925,175,'Amino acid',720,215);a.label('D',990,630,'Stop codon',1080,490);a.label('E',500,245,'Ribosome',602,400);a.save()
a=Art(18,'gel','DNA gel: read direction, size and patterns',11,'Fragments move from the negative loading end toward the positive end. The ladder has known sizes; smaller fragments appear farther from the wells.',subtitle='Constructed band pattern — not a laboratory result')
a.box(245,180,855,505,'','#edf2ee');a.text(160,235,'−',42,BLUE,'middle');a.text(160,670,'+',42,RED,'middle');a.arrow(160,285,160,595,TEAL)
for x,lbl in [(430,'Ladder'),(710,'Sample 1'),(960,'Sample 2')]:a.box(x-55,230,110,22,'','#d2dcd4');a.text(x,210,lbl,24,INK,'middle')
for y,size in [(320,1000),(410,700),(515,400),(630,100)]:
 a.line(390,y,470,y,PURPLE,9);a.text(330,y+7,str(size)+' bp',19,MUTED,'end')
for x,ys in [(710,[345,515,630]),(960,[410,565])]:
 for y in ys:a.line(x-45,y,x+45,y,PURPLE,9)
a.label('A',1170,235,'Loading wells',960,241);a.label('B',1180,335,'Larger fragments',430,320);a.label('C',1180,650,'Smaller fragments',430,630);a.label('D',82,455,'DNA migration toward positive electrode',160,455);a.save()
flow(18,'recombinant','Recombinant DNA: different jobs in the pathway',10,[('Restriction enzyme','Recognizes and cuts DNA'),('Compatible ends','Complementary overhangs can pair'),('DNA ligase','Seals the joined backbone'),('Vector','Carries the inserted sequence'),('Host expression','Transcription and translation make a product'),('Function testing','An assay evaluates the intended activity')],'Cutting, joining, carrying, expressing and testing are distinct steps. This is a conceptual overview, not an experimental protocol.')


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[18];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[18],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',18,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
