export const CALM_MODULE_4_MAIN_STORAGE_KEY = 'calmModule4MainState';
export const CALM_MODULE_4_CAREER_PLANNER_STORAGE_KEY = 'calmModule4CareerPlannerState';
export const CALM_MODULE_4_RESOURCEFUL_PEOPLE_STORAGE_KEY = 'calmModule4ResourcefulPeopleState';
export const CALM_MODULE_4_MASTER_PLAN_STORAGE_KEY = 'calmModule4MasterPlanState';
export const CALM_MODULE_4_RESUME_BUILDER_STORAGE_KEY = 'calmModule4ResumeBuilderState';
export const CALM_MODULE_4_COVER_LETTER_STORAGE_KEY = 'calmModule4CoverLetterState';

export const CALM_MODULE_4_STORAGE_KEYS = [
  CALM_MODULE_4_MAIN_STORAGE_KEY,
  CALM_MODULE_4_CAREER_PLANNER_STORAGE_KEY,
  CALM_MODULE_4_RESOURCEFUL_PEOPLE_STORAGE_KEY,
  CALM_MODULE_4_MASTER_PLAN_STORAGE_KEY,
  CALM_MODULE_4_RESUME_BUILDER_STORAGE_KEY,
  CALM_MODULE_4_COVER_LETTER_STORAGE_KEY
];
