/** Fully online alternatives. These do not claim physical laboratory performance. */
const field=(suffix:string,label:string,max:number,frame:string)=>`<label>${label}<textarea rows="5" maxlength="${max}" data-response-id="biology30-unit-a-pilot-2:investigation:${suffix}" placeholder="${frame}"></textarea></label>`;
const table=(caption:string,columns:string[],rows:string[][])=>`<div class="comparison-table"><table><caption>${caption}</caption><thead><tr>${columns.map(column=>`<th scope="col">${column}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr><th scope="row">${row[0]}</th>${row.slice(1).map(value=>`<td>${value}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
const close=(id:string)=>`<button class="button button--secondary" type="button" data-save-investigation="biology30-unit-a-pilot-2:investigation:${id}">Save investigation checkpoint</button><span data-investigation-status="biology30-unit-a-pilot-2:investigation:${id}" aria-live="polite">Draft autosaves; checkpoint not saved yet</span></div></details>`;
const open=(id:string,title:string,description:string)=>`<details data-investigation="${id}" data-process-work-source="investigation-${id}"><summary id="work-focus-investigation-${id}" tabindex="-1"><strong>${title}</strong><span>${description}</span></summary><div><p>Complete this investigation online with the supplied evidence. No partner, equipment, body testing or personal health information is needed. This is model observation and data analysis, not a claim that you performed a physical experiment. Your earlier writing is kept; add a revised conclusion when useful.</p>`;

export function renderOnlineInvestigations(){return [
  open("reflex-response","Reflex and reaction-time evidence","Compare a reflex pathway with a voluntary reaction; revise a claim.")+`
  <section data-online-investigation-step="reflex-observation"><h3>1. Observe a reflex pathway</h3><p><strong>Question:</strong> Does a rapid response always mean a reflex? A reflex is an automatic response through a neural pathway. In this withdrawal model, a skin receptor activates a sensory neuron, spinal interneurons activate motor neurons, and a muscle contracts. Sensory information also travels toward the brain. The first spinal response need not wait for a conscious decision.</p>
  ${table("Synthetic withdrawal-pathway observations",["Condition","Sensory signal reaches spinal cord","Motor output","Withdrawal"],[["Pathway intact","Yes","Present","Present"],["Sensory path interrupted","No","Absent","Absent"],["Motor path interrupted","Yes","Absent downstream of interruption","Absent"]])}
  <p>Trace each row using <button class="text-link" type="button" data-open-model="myelin">the reflex-pathway labelling task</button>. Predict what evidence would distinguish a sensory interruption from a motor interruption. A missing movement alone cannot locate the disruption.</p></section>
  <section data-online-investigation-step="reaction-data"><h3>2. Analyse repeated reaction-time evidence</h3><p>A ruler catch begins with seeing a release and making a voluntary catch. It is reaction-time evidence, not a direct test of the spinal reflex above. Use the supplied distances; do not carry out a body test.</p>
  ${table("Supplied ruler-drop distance in centimetres",["Trial","1","2","3","4","5"],[["Distance","18","21","19","24","20"]])}
  <p>Calculate the mean and range. State why five trials are better evidence than one, and name two factors that could change the distance. Compare distances directly; they are not milliseconds.</p>
  <details class="worked-investigation"><summary>See a worked start</summary><p>The total is 102 cm, so the mean is 102 ÷ 5 = 20.4 cm. The values span 18–24 cm: the range is 6 cm. Trial variation may involve attention, release timing or movement. These values cannot identify one neuron's conduction speed or diagnose a condition.</p></details></section>
  <section data-online-investigation-step="neural-hypothesis"><h3>3. Test an explanation and revise it</h3><p>Two explanations predict different synaptic results. Claim A says arrival of an impulse is enough for transmitter release. Claim B says the terminal also needs calcium entry. In a supplied experiment, impulses reach the terminal in both conditions. Normal calcium produces strong transmitter release; reduced calcium produces much less release. Receptor conditions and stimulus settings are kept the same.</p><p>This comparison supports Claim B and challenges Claim A. It does not show that calcium is the only required step. Scientific explanations become stronger when they make testable predictions, face controlled evidence, and are revised when a prediction fails.</p>
  <p><strong>Your response:</strong> record the mean and range, distinguish the reflex from the ruler catch, and revise one claim using the calcium evidence. If a teacher or classmate comments online, identify their suggestion and your reason for accepting or rejecting it. Working alone? Compare with the worked explanation and label that comparison honestly.</p></section>
  ${field("reflex-response:pattern","Observations, calculation and comparison",500,"The mean is… The range is… Unlike the ruler catch, the reflex…")}
  ${field("reflex-response:claim","Claim, evidence and justified revision",500,"My original claim… The comparison shows… I revised… One limit…")}
  `+close("reflex-response"),
  open("sensory-receptors","Sensory-receptor investigation","Compare touch, visual detail and sound evidence without testing your senses.")+`
  <section data-online-investigation-step="sensory-design"><h3>1. Plan a fair comparison</h3><p><strong>Question:</strong> Does the smallest detected two-point spacing differ between a fingertip and forearm? Predict which site has finer spatial resolution. The location is the manipulated variable; smallest reported two-point spacing is the responding variable. Keep tip shape, pressure, reporting instructions and number of trials consistent. Receptor density and receptive-field size help explain differences, but skin and attention can also affect results.</p>
  ${table("Supplied two-point discrimination data",["Trial","Fingertip","Forearm"],[["1","3 mm","28 mm"],["2","4 mm","31 mm"],["3","3 mm","30 mm"]])}
  <p>Find each mean and compare them. Describe the result as evidence from this sample, not a rule about every person. This is not a medical sensory test.</p></section>
  <section data-online-investigation-step="vision-procedure"><h3>2. Follow a visual-discrimination procedure</h3><p>In a simulated visual study, a symbol is shown ten times at each detail size. The observer identifies its direction. A planned threshold is at least eight correct responses out of ten. Compare the centre of vision with a position away from the centre, keeping brightness, contrast, viewing distance and exposure time fixed. The table supplies the observations; you are not testing your own vision.</p>
  ${table("Synthetic visual-detail results — correct out of ten",["Detail size","Centre","Away from centre"],[["Large","10","10"],["Medium","10","8"],["Small","8","4"],["Very small","4","2"]])}
  <p>Apply the same threshold to both columns. Connect the result with the cone-rich fovea and retinal signal processing. Do not infer a disorder from this teaching dataset.</p><p><strong>Design decision:</strong> a device intended to show fine labels should allow enlargement and high contrast. Enlargement improves access but shows less information at once. Recommend one design choice using the data and state that tradeoff. Screen size is a tool setting, not a measurement of someone's eyesight.</p></section>
  <section data-online-investigation-step="hearing-procedure"><h3>3. Interpret sound-response evidence safely</h3><p>A supplied model presents tones at a constant safe setting and records neural responses across three cochlear regions. You will not play tones, raise volume, wear headphones or test hearing. The controlled variable is the presentation setting; the manipulated variable is frequency; the responding variable is the region with the strongest response.</p>
  ${table("Synthetic cochlear-region responses — relative units",["Tone","Near base","Middle","Near apex"],[["Low frequency","2","4","9"],["Middle frequency","3","9","4"],["High frequency","9","4","2"]])}
  <p>State the pattern, identify one limitation of relative model units, and explain why this table cannot establish an individual hearing threshold.</p>
  <details class="worked-investigation"><summary>Compare with a worked interpretation</summary><p>Mean tactile spacing is about 3.3 mm at the fingertip and 29.7 mm at the forearm. In the visual model, small detail meets the threshold centrally, but only medium detail meets it away from centre. High-frequency sound produces the strongest response near the cochlear base. These different results concern different receptors; a touch result does not measure visual or hearing ability.</p></details></section>
  <p><strong>Communicate and revise:</strong> write a short fair-test plan and a conclusion using at least two datasets. Compare it with the worked interpretation, or exchange it online with your teacher or classmate. State one change you made and why. A model comparison is not a claim that you collaborated with a person.</p>
  ${field("sensory-receptors:plan","Variables and fair-test plan",500,"I predict… I will change… measure… and keep… the same. My threshold rule…")}
  ${field("sensory-receptors:analysis","Data, design choice and revised explanation",500,"Two patterns are… My design choice… The tradeoff… After comparing, I revised…")}
  `+close("sensory-receptors"),
  open("endocrine-data","Endocrine supplied-data investigation","Test a model prediction, evaluate a tool and revise a conclusion.")+`
  <section data-online-investigation-step="endocrine-experiment"><h3>1. State a testable model question</h3><p><strong>Question:</strong> does increasing ADH increase kidney water reabsorption when the target responds normally? Predict that more effective ADH will reduce urine volume. ADH level is the manipulated variable; relative urine volume is the responding variable. In the model, keep fluid input, sodium intake, elapsed time and target sensitivity fixed.</p>
  <p>Open <button class="text-link" type="button" data-open-model="adh">the ADH model</button>, predict the dehydration response, select its test case, and note the displayed direction of water reabsorption and urine change. Compare that software observation with the supplied controlled results below. These are model observations, not measurements from people.</p>
  ${table("Synthetic controlled model — fixed input and normal target response",["Relative ADH","Trial 1 urine volume","Trial 2 urine volume","Trial 3 urine volume"],[["Low","10 units","11 units","9 units"],["High","4 units","5 units","3 units"]])}
  <p>Calculate the mean for each ADH condition and the change. Explain why changing fluid input at the same time would weaken the inference. Propose another test that changes target sensitivity while keeping ADH fixed.</p></section>
  <section data-online-investigation-step="endocrine-observation"><h3>2. Separate an observation from a controlled experiment</h3><p>The following two samples change several factors at once. They are useful for proposing explanations, but they cannot establish which factor caused the difference.</p>
  ${table("Original supplied glucose and water-balance evidence — synthetic values",["Sample","Blood glucose","Urine glucose","ADH","Urine pattern"],[["A","5.4 mmol/L","Not detected","Higher","Low volume, concentrated"],["B","12.8 mmol/L","Detected","Lower","High volume, dilute"]])}
  <p>Sample A fits greater ADH-related water reabsorption. Sample B combines glucose and water-balance evidence, so do not attribute all its urine changes to ADH. Glucose in urine can affect water loss. Neither sample provides a diagnosis, treatment decision, or complete health history.</p></section>
  <section data-online-investigation-step="endocrine-technology"><h3>3. Evaluate a tool and communicate a revision</h3><p>A glucose-monitoring tool can provide repeated readings that a single sample misses. An insulin-delivery device can provide controlled delivery, but its readings, settings and delivery system still have limits. People need professional guidance; a classroom model cannot select treatment. Access, cost and training affect who benefits. Disposable sensors, packaging and batteries also create waste, so safe disposal and resource use matter alongside the intended benefit.</p><p>Compare two claims: “One reading tells us everything” and “Repeated readings reveal a pattern, but we still need context.” Use the data to improve the first claim. Name one intended benefit, one limitation and one unintended consequence of a monitoring tool. If you receive feedback online, record the point that changed your conclusion. Otherwise use the course comparison and identify it as such.</p>
  <details class="worked-investigation"><summary>See a worked response</summary><p>Mean urine volume falls from 10 to 4 relative units as model ADH increases: a decrease of 6 units. Fixed inputs make the comparison clearer, but it remains a simplified model. The two original samples do not isolate ADH. Repeated monitoring can reveal a trend; it cannot replace context, careful interpretation or professional advice. My revised claim states the pattern and the limit rather than diagnosing a person.</p></details></section>
  ${field("endocrine-data:analysis","Hypothesis, evidence, tool evaluation and revision",700,"I predicted… The model showed… The means were… A fair follow-up changes… A tool benefit/limit is… An unintended effect is… I revised…")}
  `+close("endocrine-data")
].join("\n");}
