/** Authored question-by-question alignment, distinct from proof of a complete practical behaviour.
 * Read against every rendered prompt, key and wrong-choice explanation on 2026-09-05.
 * A selected-response item can support an example without demonstrating its full verb (e.g. label).
 */
export const PRACTICE_ACADEMIC_REVIEW: Record<string, [string, "recognize-explain" | "apply-infer", string]> = {
  "lesson-01-guided-1": ["A1.1k-01", "recognize-explain", "Axon function, not complete diagram identification"],
  "lesson-01-guided-2": ["A1.1k-02", "apply-infer", "Explain conduction through myelin and nodes"],
  "lesson-02-guided-01": ["A1.1k-09", "apply-infer", "Relate graph upstroke to sodium entry"],
  "lesson-02-guided-02": ["A1.1k-10", "apply-infer", "Distinguish intensity coding from spike amplitude"],
  "lesson-03-guided-1": ["A1.1k-11", "recognize-explain", "Define the chemical signal before its examples"],
  "lesson-03-guided-2": ["A1.1k-12", "apply-infer", "Predict reduced acetylcholine breakdown"],
  "lesson-04-guided-01": ["A1.2k-04", "apply-infer", "Trace somatic motor output"],
  "lesson-04-guided-02": ["A1.2k-06", "recognize-explain", "Qualify organ-specific autonomic responses"],
  "lesson-05-guided-01": ["A1.2k-07", "recognize-explain", "Identify the cerebellum by function, not on a complete diagram"],
  "lesson-05-guided-02": ["A1.2k-09", "recognize-explain", "Limit symptom-based inference"],
  "chapter-11-practice-01": ["A1.1k-01", "recognize-explain", "Dendrite function"],
  "chapter-11-practice-02": ["A1.1k-02", "recognize-explain", "Myelin insulation and speed"],
  "chapter-11-practice-03": ["A1.3k-01", "recognize-explain", "Order a withdrawal pathway"],
  "chapter-11-practice-04": ["A1.1k-03", "recognize-explain", "Sensory-neuron functional direction"],
  "chapter-11-practice-05": ["A1.1k-08", "recognize-explain", "Resting ion distribution, not full transport explanation"],
  "chapter-11-practice-06": ["A1.1k-10", "recognize-explain", "Threshold requirement"],
  "chapter-11-practice-07": ["A1.1k-10", "recognize-explain", "Intensity through frequency and recruitment"],
  "chapter-11-practice-08": ["A1.1k-09", "apply-infer", "Channel recovery and forward propagation"],
  "chapter-11-practice-09": ["A1.1k-11", "recognize-explain", "Calcium entry precedes transmitter release"],
  "chapter-11-practice-10": ["A1.1k-12", "recognize-explain", "Cholinesterase termination"],
  "chapter-11-practice-11": ["A1.2k-01", "recognize-explain", "CNS membership"],
  "chapter-11-practice-12": ["A1.2k-06", "recognize-explain", "Coordinated autonomic effects"],
  "lesson-06-guided-01": ["A1.6k-01", "recognize-explain", "Transduction as a sensing prerequisite"],
  "lesson-06-guided-02": ["A1.6k-01", "recognize-explain", "Adaptation as a sensing prerequisite"],
  "lesson-07-guided-01": ["A1.4k-05", "recognize-explain", "Optical portion of the visual pathway"],
  "lesson-07-guided-02": ["A1.4k-03", "recognize-explain", "Rod and cone functions"],
  "lesson-08-guided-01": ["A1.5k-03", "recognize-explain", "Hair-cell transduction site"],
  "lesson-08-guided-02": ["A1.5k-03", "recognize-explain", "Semicircular-canal function"],
  "chapter-12-practice-01": ["A1.4k-03", "recognize-explain", "Photoreception as the eye-function prerequisite"],
  "chapter-12-practice-02": ["A1.6k-01", "recognize-explain", "Mechanoreception across touch and hearing"],
  "chapter-12-practice-03": ["A1.6k-01", "recognize-explain", "Transduction prerequisite"],
  "chapter-12-practice-04": ["A1.6k-01", "apply-infer", "Apply adaptation to clothing sensation"],
  "chapter-12-practice-05": ["A1.4k-05", "recognize-explain", "Optical pathway ordering"],
  "chapter-12-practice-06": ["A1.4k-03", "recognize-explain", "Iris function"],
  "chapter-12-practice-07": ["A1.4k-03", "recognize-explain", "Rod sensitivity"],
  "chapter-12-practice-08": ["A1.4k-03", "recognize-explain", "Optic-disc receptor absence"],
  "chapter-12-practice-09": ["A1.5k-05", "recognize-explain", "Mechanical portion of the sound pathway"],
  "chapter-12-practice-10": ["A1.5k-03", "recognize-explain", "Cochlear receptor mechanism"],
  "chapter-12-practice-11": ["A1.5k-03", "recognize-explain", "Rotation detection"],
  "chapter-12-practice-12": ["A1.6k-01", "apply-infer", "Integrate spatial-orientation inputs"],
  "lesson-09-guided-01": ["A2.2k-02", "recognize-explain", "Negative-feedback prerequisite"],
  "lesson-09-guided-02": ["A2.2k-01", "recognize-explain", "Receptor prerequisite for hormone function"],
  "lesson-10-guided-01": ["A2.2k-01", "recognize-explain", "Tropic target relationship"],
  "lesson-10-guided-02": ["A2.1k-02", "recognize-explain", "Distinguish posterior release from synthesis"],
  "lesson-11-guided-01": ["A2.4k-01", "apply-infer", "Predict ADH-linked urine pattern"],
  "lesson-11-guided-02": ["A2.1k-02", "recognize-explain", "ADH synthesis location"],
  "lesson-12-guided-01": ["A2.2k-02", "apply-infer", "Interpret paired TSH and thyroxine"],
  "lesson-12-guided-02": ["A2.3k-01", "apply-infer", "PTH response to falling calcium"],
  "lesson-13-guided-1": ["A2.2k-02", "apply-infer", "Meal-linked insulin feedback"],
  "lesson-13-guided-2": ["A2.5k-01", "recognize-explain", "Compare adrenal pathways and timescales"],
  "chapter-13-practice-01": ["A2.2k-02", "recognize-explain", "Dynamic-homeostasis prerequisite"],
  "chapter-13-practice-02": ["A2.2k-02", "recognize-explain", "Recognize feedback direction"],
  "chapter-13-practice-03": ["A2.2k-01", "recognize-explain", "Target-cell receptor prerequisite"],
  "chapter-13-practice-04": ["A2.1k-02", "recognize-explain", "Hypothalamic source/control relationship"],
  "chapter-13-practice-05": ["A2.2k-01", "recognize-explain", "TSH target"],
  "chapter-13-practice-06": ["A2.3k-01", "recognize-explain", "Growth-hormone function"],
  "chapter-13-practice-07": ["A2.4k-01", "apply-infer", "Dehydration and water conservation"],
  "chapter-13-practice-08": ["A2.2k-02", "apply-infer", "Paired pituitary-thyroid output"],
  "chapter-13-practice-09": ["A2.3k-01", "recognize-explain", "Calcium-raising direction"],
  "chapter-13-practice-10": ["A2.2k-02", "recognize-explain", "Insulin response after eating"],
  "chapter-13-practice-11": ["A2.1k-02", "recognize-explain", "Adrenal-medulla hormone source"],
  "chapter-13-practice-12": ["A2.3k-01", "recognize-explain", "Aldosterone sodium effect"],
  "final-practice-core-01": ["A1.1k-13", "apply-infer", "Conduction evidence and myelin, not diagnosis"],
  "final-practice-core-02": ["A1.1k-10", "apply-infer", "Predict firing-frequency change"],
  "final-practice-core-03": ["A1.1k-11", "apply-infer", "Predict blocked presynaptic calcium entry"],
  "final-practice-core-04": ["A1.2k-04", "recognize-explain", "Somatic motor direction"],
  "final-practice-core-05": ["A1.2k-09", "apply-infer", "Cautious cerebellar localization"],
  "final-practice-core-06": ["A1.3k-01", "recognize-explain", "Initial receptor event"],
  "final-practice-core-07": ["A1.6k-01", "apply-infer", "Mechanical transduction case"],
  "final-practice-core-08": ["A1.4k-03", "recognize-explain", "Lens accommodation function"],
  "final-practice-core-09": ["A1.5k-03", "recognize-explain", "Cochlear transduction cells"],
  "final-practice-core-10": ["A2.2k-02", "apply-infer", "Thermoregulatory feedback prerequisite"],
  "final-practice-core-11": ["A2.2k-01", "recognize-explain", "Receptor-bearing target cells"],
  "final-practice-core-12": ["A2.1k-02", "recognize-explain", "Source-signal-target thyroid axis"],
  "final-practice-core-13": ["A2.4k-01", "apply-infer", "Dehydration response"],
  "final-practice-core-14": ["A2.3k-01", "apply-infer", "Calcium-regulation response"],
  "final-practice-core-15": ["A2.2k-02", "recognize-explain", "Glucose-feedback response"],
  "final-practice-core-16": ["A2.5k-01", "recognize-explain", "Adrenal pathway comparison"],
  "final-practice-core-17": ["A2.4k-01", "apply-infer", "Infer reduced target response from paired ADH and urine data"],
  "final-practice-core-18": ["A2.5k-01", "apply-infer", "Integrate stress responses over time"],
  "final-practice-challenge-01": ["A1.1k-02", "apply-infer", "Compare controlled axon examples; modest transfer, not automatically excellence"],
  "final-practice-challenge-02": ["A1.1k-11", "apply-infer", "Combine excitation and inhibition in the advanced synapse explanation"],
  "final-practice-challenge-03": ["A1.4k-05", "apply-infer", "Infer binocular contributions beyond the optic chiasm"],
  "final-practice-challenge-04": ["A2.2k-02", "apply-infer", "Locate upstream thyroid-axis disruption"],
  "final-practice-challenge-05": ["A2.3k-01", "apply-infer", "Separate kidney/ion regulation of aldosterone from ACTH"],
  "final-practice-challenge-06": ["A2.6k-01", "apply-infer", "Request target-response evidence before inferring a glucose disorder"]
};

export const FINAL_PRACTICE_TOPIC_REVIEW = {
  categoryOrder: ["Chapter 11", "Chapter 12", "Chapter 13 including homeostasis", "Integrated"],
  originallyPlanned: [6, 4, 6, 2],
  preservedCandidate: [6, 3, 7, 2],
  itemNumbers: [[1,2,3,4,5,6],[7,8,9],[10,11,12,13,14,15,16],[17,18]],
  disposition: "teacher-review-of-preserved-blueprint-variance",
  reason: "The approved preservation boundary keeps every existing question meaning and key. Core question 10 is homeostasis, not a fourth sensory question. Do not silently relabel it or claim the original 6/4/6/2 split is met.",
  demandLimit: "These selected-response questions chiefly reinforce recognition and one-step application. Six optional challenges add transfer but are not a calibrated diploma-exam simulation. Graph construction, investigations and extended explanations have separate saved-work destinations."
};
