"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER19

a=Art(19,'allele-counts','Count individuals and allele copies separately',2,'This constructed sample contains 3 AA, 5 Aa and 2 aa individuals. Its A frequency is 11/20 and its a frequency is 9/20.',subtitle='Constructed diploid sample: N = 10; allele copies = 20')
genos=['AA']*3+['Aa']*5+['aa']*2
for i,geno in enumerate(genos):
 x=165+(i%5)*265;y=270+(i//5)*240;a.ellipse(x,y,104,77,'#f6f8f3',TEAL)
 for j,al in enumerate(geno):a.circle(x-35+j*70,y,26,BLUE if al=='A'else ORANGE,'white',2);a.text(x-35+j*70,y+8,al,24,'white','middle','700')
a.label('A',165,160,'AA genotype',165,265);a.label('B',960,160,'Aa genotype',960,265);a.label('C',1225,640,'aa genotype',1225,510);a.label('D',510,650,'Two allele copies per individual',430,510);a.save()
a=Art(19,'hw-square','Random pairing from an allele pool',3,'Under Hardy–Weinberg assumptions, allele frequencies p and q combine into p², pq, qp and q²; the two heterozygous outcomes add to 2pq.')
a.text(430,230,'A: p',30,BLUE,'middle');a.text(800,230,'a: q',30,ORANGE,'middle');a.text(135,365,'A: p',27,BLUE,'middle');a.text(135,570,'a: q',27,ORANGE,'middle')
for key,x,y,txt,ans in [('A',260,270,'AA','p²'),('B',630,270,'Aa','pq'),('C',260,475,'Aa','pq'),('D',630,475,'aa','q²')]:a.box(x,y,365,200,txt,size=30);a.label(key,x+180,y+128,ans)
a.wrap(1175,325,'Two ways to form Aa: pq + qp = 2pq',15,25,anchor='middle');a.save()
flow(19,'hw-method','From recessive phenotype to expected counts',4,[('Observed aa fraction','32 recessive individuals / 200 total = 0.16'),('Recessive allele frequency','q = square root of 0.16 = 0.40'),('Other allele frequency','p = 1 − 0.40 = 0.60'),('Homozygous dominant frequency','p² = 0.36'),('Heterozygote frequency','2pq = 0.48'),('Expected carrier count','0.48 × 200 = 96')],'The square-root inference requires the stated complete-dominance and Hardy–Weinberg assumptions.',subtitle='Constructed example — assume Hardy–Weinberg equilibrium')
a=Art(19,'drift','Bottleneck and founder effect: different histories',7,'A bottleneck reduces an existing population; a founder event starts a new population from a small subset while the source can remain. Dot colours represent alleles, not fitness.')
def pool(a,x,y,w,h,n,blue):
 a.box(x,y,w,h,'')
 cols=max(1,int((w-35)//29))
 for i in range(n):a.circle(x+26+(i%cols)*29,y+28+(i//cols)*34,10,BLUE if i<blue else ORANGE,'white',1)
pool(a,90,220,270,190,32,16);a.arrow(390,305,560,305);pool(a,590,245,140,110,4,3);a.arrow(750,305,875,305);pool(a,920,220,320,190,24,18)
a.label('A',665,175,'Bottleneck',660,295);a.text(240,450,'Original population',22,MUTED,'middle');a.text(1090,450,'Descendants of survivors',22,MUTED,'middle')
pool(a,90,490,270,190,32,16);a.arrow(390,575,650,575);pool(a,735,520,170,125,6,5);a.label('B',1060,570,'Founder effect',830,575)
a.text(280,730,'Source persists',22,MUTED,'middle');a.text(820,730,'New isolated colony',22,MUTED,'middle');a.save()
a=Art(19,'geneflow','Combine allele pools using their contributions',8,'Eighty residents at p = 0.25 and twenty immigrants at p = 0.75 contribute equally per breeder. Their combined A frequency is 70/200 = 0.35.',subtitle='Constructed equal-contribution model — diploid autosomal locus')
a.box(100,210,475,220,'80 residents\n160 allele copies\n40 A copies',size=27);a.box(820,210,475,220,'20 immigrants\n40 allele copies\n30 A copies',size=27)
a.arrow(350,455,600,565);a.arrow(1070,455,800,565);a.box(440,575,520,115,'Combined: 200 copies, 70 A',size=27)
a.label('A',190,175,'Resident contribution',350,300);a.label('B',1205,175,'Immigrant contribution',1060,300);a.label('C',1050,660,'p = 0.35',900,625);a.save()
a=Art(19,'observed-expected','Same allele frequencies, different genotype pattern',5,'Observed counts of 40 AA, 20 Aa and 40 aa give p = q = 0.50. Hardy–Weinberg predicts 25, 50 and 25; the mismatch alone does not identify its cause.',subtitle='Constructed counts — observed and model-predicted values are distinct')
headers=['Category','Observed count','Expected count'];rows=[['AA','40','25'],['Aa','20','50'],['aa','40','25']]
for i,h in enumerate(headers):a.box(120+i*390,200,385,85,h,fill='#e8f1eb',size=27)
for j,row in enumerate(rows):
 for i,t in enumerate(row):a.box(120+i*390,300+j*115,385,110,t,size=29)
a.label('A',60,470,'Heterozygote deficit',600,470);a.label('B',800,715,'Same allele frequencies',710,610);a.save()


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[19];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[19],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',19,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
