// One-time adaptation of the reviewed teaching pilot. Never run over later Studio edits.
const fs=require('fs'),path=require('path'),cheerio=require('cheerio');const dir=__dirname,workspace=path.resolve(dir,'../../../workspace'),entry=path.join(workspace,'index.html');const repair=process.argv.includes('--repair-empty-templates');const current=fs.readFileSync(entry,'utf8');if(current.includes('data-learning-support')&&!repair)throw Error('Already applied; do not regenerate');if(repair&&cheerio.load(current)('template[data-learning-support]').toArray().some(e=>cheerio.load(current)(e).text().trim()))throw Error('Repair only allowed for initial empty templates');const source=repair?fs.readFileSync(dir+'/before/index.html','utf8'):current;
const methods=JSON.parse(fs.readFileSync(dir+'/lesson-methods.json')),numbers=JSON.parse(fs.readFileSync(dir+'/number-hints.json')),guided=JSON.parse(fs.readFileSync(dir+'/guided-hints.json'));const $=cheerio.load(source,{sourceCodeLocationInfo:true});let replacements=[],report=[],fallbacks=[];const seconds=new Set(['ce1-02','ce1-04','ce1-05','ce1-06','ce1-07','co1-04','fl1-02','fl1-03','fl2-01']);const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function label(f){const id=f.attr('id'),l=id?f.closest('article').find(`label[for="${id}"]`).first():f.closest('label');const copy=l.clone();copy.find('input,select,textarea,small,button').remove();return copy.text().trim()||f.attr('name')||f.attr('data-save-key');}
function hintFor(feedback,choice,same,lesson,key){if(!same)return feedback.replace(/^Feedback:\s*/,'').trim();const sentences=feedback.replace(/^Feedback:\s*/,'').replace(/^Answer:\s*[A-D]\.\s*/,'').split(/(?<=[.!?])\s+/);const match=sentences.find(s=>new RegExp('^'+choice+'\\b').test(s));if(match)return match.replace(new RegExp('^'+choice+'\\b'),'This choice').trim();fallbacks.push({lesson,key,choice,feedback});return methods[lesson];}
for(const element of $('article[data-lesson-id]').get()){
 const loc=element.sourceCodeLocation,id=$(element).attr('id');if(id==='fl2-03')continue;if(!methods[id])throw Error('Missing method '+id);const original=source.slice(loc.startOffset,loc.endOffset),d=cheerio.load(original,null,false),root=d('article').first(),items=[];const method=methods[id];
 const add=(control,data)=>{const n=items.length;data.attempt=`support:${id}:attempt:${data.key}`;control.attr('data-support-managed','').attr('data-support-item',String(n));items.push(data);};
 root.find('[data-question],[data-review-choice],[data-practice-id]').each((_,e)=>{const q=d(e),t=q.find('template[data-authored-feedback],template[data-review-messages],template[data-choice-feedback]').first();if(!t.length)throw Error('No feedback '+id);const feedback=JSON.parse(t.text()),correct=String(q.attr('data-correct')??q.attr('data-correct-index'));if(!feedback[correct])throw Error('No correct feedback '+id);const same=new Set(Object.values(feedback)).size===1;const key=q.find('input[data-save-key]').first().attr('data-save-key'),hints={};q.find('input[type=radio]').each((_,f)=>{const v=d(f).attr('value');if(v!==correct)hints[v]=hintFor(String(feedback[v]),v,same,id,key);});let button=q.find('[data-check-choice]').first();if(!button.length){q.find('legend').after('<button type="button" data-support-check>Check my answer</button>');}add(q,{kind:'choice',key,correct,hints,steps:method,worked:String(feedback[correct]).replace(/^(Feedback:\s*|Answer:\s*[A-D]\.\s*)/,'')});});
 root.find('[data-check-number]').each((_,e)=>{const b=d(e),f=b.closest('.authored-field').find('input'),key=f.attr('data-save-key');if(!numbers[key])throw Error('Missing number hint '+key);add(b,{kind:'number',key,field:f.attr('id'),correct:Number(f.attr('data-answer')),tolerance:Number(f.attr('data-tolerance')||'.005'),hints:{default:numbers[key]},steps:numbers[key]+' '+method,worked:`${label(f)}: ${f.attr('data-answer')}. ${numbers[key]} Use the supplied record and the nearby comparison model to check each step.`});});
 root.find('select[data-save-key^="guided:"]').each((_,e)=>{const f=d(e),key=f.attr('data-save-key');if(id==='fl3-04')return;const correct=id==='co1-01'?'attendance':seconds.has(id)?'1':'0';if(!guided[key])throw Error('No guided hints '+key);const choice=f.find(`option[value="${correct}"]`).text();add(f,{kind:'select',key,field:f.attr('id'),correct,hints:guided[key],steps:method,worked:`${choice} fits the supplied record. ${method} Use the nearby comparison to review your written explanation; it is not automatically graded.`});if(id==='co1-01')root.find('#co1-01-review-check-match').attr('data-support-managed','');});
 const customs=[];
 if(id==='ce1-03')customs.push({selector:'[data-review-check="ce-cost"]',kind:'bundle',key:'guided:ce1-03:costs',fields:['ce-b-travel','ce-b-total'],answers:[800,2650],hints:{default:'Travel is a repeated monthly cost. Count all ten months before adding tuition/fees and supplies.',80:'You counted one month of travel. The route lasts ten months; the one-time charges are separate.'},steps:'Calculate $80 × 10 for travel, then add $1,600 tuition/fees and $250 supplies once each.',worked:'Travel is $800. The complete listed total is $1,600 + $250 + $800 = $2,650, which is $1,250 above Leah’s $1,400 limit.'});
 if(id==='fl3-04')customs.push({selector:'#fl-check-fee',kind:'bundle',key:'guided:fl3-04:fee-comparison',fields:['fl-fee-difference','fl-fee-claim','fl-fee-explain'],answers:[1.04,'supported',null],hints:{default:'Compare the two end balances in the otherwise identical model runs. Keep a supported model comparison separate from a promise about next year.'},steps:'Subtract the fee-run balance ($102.96) from the no-fee balance ($104.00). Choose a statement about these two runs, then explain one assumption in your own words.',worked:'The fee run finishes $1.04 lower. The supported claim compares these two supplied runs; 4% is an assumption. The written explanation needs your own review of that limit and is not automatically graded.'});
 if(id==='fl1-03')customs.push({selector:'[data-check-flexible]',kind:'flexible',key:'guided:fl1-03:allocations',fields:['field-guided-fl1-03-part1','field-guided-fl1-03-part2'],hints:{default:'Keep each allocation within its original amount. Together, the saving and recreation allocations must fit the $55 available after protecting the required ending buffer.'},steps:'Use saving from $0–$70 and recreation from $0–$35. Add them and compare the sum with $55; then check both the October 10 balance and ending buffer.',worked:'Any pair inside the stated limits with a sum no greater than $55 meets this arithmetic check. Ending balance = $135 minus the two allocations. Also explain the October 10 balance of $45; that explanation is self-reviewed.'});
 if(id==='fl2-01')customs.push({selector:'[data-finlit-number="borrow-cost-difference"]',kind:'bundle',key:'finlit:fl2-01:cost-difference',fields:['borrow-cost-difference'],answers:[36.08],hints:{default:'Use the borrowing costs for the same $300 and 14 days. Do not subtract the principal from another principal.'},steps:'Subtract the lower displayed borrowing cost ($5.92) from the higher displayed cost ($42.00). Keep eligibility questions separate.',worked:'$42.00 − $5.92 = $36.08 more for the payday example over the same 14 days. This does not establish eligibility for either product.'});
 for(const data of customs){const c=root.find(data.selector);if(!c.length)throw Error('Missing custom '+data.selector);const parent=c.parent();let out=parent.find('[role=status]').first();if(!out.length){const ids={'ce1-03':'ce-cost-feedback','fl3-04':'fl-fee-feedback','fl1-03':null,'fl2-01':'borrow-cost-feedback'};out=ids[id]?root.find('#'+ids[id]):root.find('[data-flexible-feedback]');}if(!out.length)throw Error('No custom output '+id);data.output=out.attr('id')||`${id}-support-${items.length}-feedback`;out.attr('id',data.output);for(const fid of data.fields)root.find('#'+fid).attr('data-support-managed','');delete data.selector;add(c,data);}
 if(['ce1-03','fl3-04'].includes(id)){const expected=id==='ce1-03'?{'ce-final-c':1410,'ce-final-d':2700}:{'fl-final-price':252,'fl-final-gap':4};for(const[fid,target]of Object.entries(expected)){const f=root.find('#'+fid),key=f.attr('data-save-key');const hint=id==='ce1-03'?'Build this route’s full listed total. Multiply its repeated travel charge by its own number of months, and add its one-time costs once.':fid==='fl-final-price'?'Apply the supplied price increase to the original basket price, then add that dollar increase to the original price.':'Compare the new basket price with the final money available. This field asks for the shortfall, not the full basket price.';const n=items.length;f.after(`<button type="button" data-support-managed data-support-item="${n}">Check this calculation</button><p class="field-feedback" role="status" data-support-number-output></p>`);items.push({kind:'number',key,field:fid,correct:target,tolerance:.005,hints:{default:hint},steps:hint+' '+method,worked:`${label(f)}: ${target}. ${hint}`,attempt:`support:${id}:attempt:${key}`});}}
 const independent=root.find('[data-final-field]').first().closest('section'),models=independent.find('details.authored-model,details.finlit-model');if(!independent.length)throw Error('No final section '+id);independent.attr('data-independent-support','');models.attr('data-capture-first','');const firstKey=`support:${id}:first-independent`;
 const firstCard=`<div class="learning-first-copy" data-canvas-helper-edit-key="${id}-first-copy"><p>Your independent response uses the new case above. At your first calculation check or comparison-model opening, we keep a copy of what you have entered. You can revise your current response afterwards.</p><button type="button" data-support-review>Keep my first attempt and review</button><details><summary>View my first independent attempt</summary><input type="hidden" data-save-key="${firstKey}" data-support-first><pre data-support-first-display>No first attempt kept yet.</pre></details><p data-support-copy-status role="status"></p></div>`;
 independent.append(firstCard);
 const stages=root.children('section');let cueCount=0;for(const stage of stages.get()){const st=d(stage),sid=st.attr('id')||'';const worked=/-stage-4$|-worked$|co1-01-learn$/.test(sid),practice=/-stage-5$|-practice$|co1-01-practice$/.test(sid),checks=/-stage-6$|-checks$|co1-01-checks$/.test(sid);if(!worked&&!practice&&!checks)continue;const next=worked?root.find('#'+id+'-stage-5,#'+id+'-practice').first():practice?root.find('#'+id+'-stage-6,#'+id+'-checks').first():independent;let heading=next.children('h2,h3').first().text()|| (practice?'Check your understanding':checks?'Apply independently':'Practise with support');let action;if(worked){const f=next.find('[data-save-key]').not('[type=hidden]').first();action=`Try “${label(f)}” before opening its comparison model.`;}else if(practice)action='Choose an answer and check it. Use the hint to revise; a repeated unchanged check is not another attempt.';else action='Read the new situation and its supplied records before filling your independent response. Use the method you practised with the evidence in this new case.';st.append(`<p class="learning-next" data-canvas-helper-edit-key="${id}-next-${cueCount++}"><strong>Next:</strong> <a href="#${escape(next.attr('id'))}">${escape(heading)}</a>. ${escape(action)}</p>`);}
 root.children('details.lesson-roadmap').append(`<p class="learning-check-guide" data-canvas-helper-edit-key="${id}-check-guide">At a check, try an answer, read the hint and revise. A different incorrect answer brings method support and an option to show the worked reasoning. Written responses use the comparison and self-checks; they are not automatically graded.</p>`);
 const hidden=`<div hidden data-learning-support-fields>${items.map(item=>`<input type="hidden" data-save-key="${escape(item.attempt)}">`).join('')}</div>`;root.append(hidden);root.append('<template data-learning-support>'+escape(JSON.stringify({method,firstKey,items}))+'</template>');replacements.push({start:loc.startOffset,end:loc.endOffset,html:d.html()});report.push({id,items:items.length,choice:items.filter(x=>x.kind==='choice').length,numeric:items.filter(x=>x.kind==='number'||x.kind==='bundle'||x.kind==='flexible').length,guided:items.filter(x=>x.kind==='select').length,firstCopy:firstKey,nextCues:cueCount});
}
if(report.length!==39)throw Error('Expected 39 lessons');let result=source;for(const r of replacements.sort((a,b)=>b.start-a.start))result=result.slice(0,r.start)+r.html+result.slice(r.end);const marker='<script src="./fl2-03-pilot.js">';if(!result.includes(marker))throw Error('Script marker missing');result=result.replace(marker,'<script src="./learning-support.js" defer></script>\n'+marker);fs.writeFileSync(entry,result);fs.writeFileSync(dir+'/coverage.json',JSON.stringify({lessons:report,fallbacks},null,2));console.log(JSON.stringify({lessons:report.length,controls:report.reduce((a,r)=>a+r.items,0),fallbackHints:fallbacks.length}));
