/* Opt-in local review surface. Never loads a fixture into a player's saved slot. */
if(new URLSearchParams(location.search).has('review')){
  const panel=document.createElement('section');panel.id='developerReview';panel.style.cssText='position:fixed;left:10px;top:72px;z-index:200;background:#fff6df;color:#203e2e;padding:12px;max-width:min(680px,95vw);max-height:80vh;overflow:auto;border:2px solid #577c4d';
  panel.innerHTML='<h2>Candidate review</h2><button id="runReview">Run focused checks</button><pre id="reviewResults">Ready. Uses temporary in-memory fixtures.</pre>';document.body.appendChild(panel);
  $('runReview').onclick=()=>{
    const original=G,originalScreen=screen,originalPause=PPScene.paused,originalEnd=$('endWrap').style.display,results=[];PPCampaign.restoring=true;
    const check=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
    const assert=(condition,msg)=>{if(!condition)throw new Error(msg||'Assertion failed');};
    const approx=(a,b,eps=.001)=>assert(Math.abs(a-b)<=eps,`${a} != ${b}`);
    const fixture=(pace='class')=>{G=freshState();G.mode='free';G.campaign.pace=pace;G.campaign.routine={work:true,groceries:300,savings:0,creditMinimum:true};G.lane='retail';G.tierIdx=0;G.salary=2400;G.onboardDone=true;G.sawPlanner=true;G.cash=10000;G.energy=100;G.groc={cal:70000,spent:300,coffee:0,shopped:true};G.burnout=false;G.over=false;G.pendingShift=null;G.checkpoint=null;screen='town';PPScene.paused=false;closeModal();return G;};
    check('All art sheets loaded',()=>assert(Object.keys(PPAssets.sheets).every(k=>PPArt.ready[k]),'An atlas is missing'));
    check('All five characters have eight complete directions',()=>{for(const id of ['alex','maya','jay','sam','classic']){const def=PPAssets.sheets[id],im=PPArt.images[id];assert(def.frames.length===8);for(const f of def.frames)assert(f[0]>=0&&f[1]>=0&&f[0]+f[2]<=im.width&&f[1]+f[3]<=im.height,id+' crop');}});
    check('Eight input directions retain last facing at rest',()=>{for(const [x,y,d]of [[0,1,'s'],[-1,1,'sw'],[-1,0,'w'],[-1,-1,'nw'],[0,-1,'n'],[1,-1,'ne'],[1,0,'e'],[1,1,'se']])assert(PPWorld.direction(x,y)===d);assert(PPWorld.direction(0,0,'nw')==='nw');approx(Math.hypot(...Object.values(PPWorld.normalizeInput(1,1))),1);});
    check('Feet stop at walls, slide, and cannot tunnel',()=>{const wall=[{x:100,y:0,w:35,h:220}],bounds={x:0,y:0,w:400,h:400};let p=PPWorld.moveCircle({x:75,y:45,r:12},{x:300,y:110},wall,bounds);assert(p.x<=88.01);assert(p.y>100);assert(!PPWorld.circleRect(p.x,p.y,12,wall[0]));});
    check('Every room has a collision-free route to its activity and exit',()=>{for(const [id,props]of Object.entries(PPScene.rooms)){const rects=props.map(p=>p.solid),entry={x:450,y:539,r:12},t=PPScene.targets(id)[0];assert(PPWorld.pathfind(entry,t,rects,PPScene.roomBounds,22,12).length>0,id);assert(!PPWorld.circleRect(entry.x,entry.y,12,rects[0]),id+' spawn');}});
    check('Town doors and NPC routes remain reachable',()=>{for(const b of PPScene.buildings)assert(PPWorld.pathfind({x:240,y:430},{x:b.x,y:b.y+24},PPScene.townSolids,PPScene.bounds,32,12).length>0,b.id);for(const n of npcs)assert(PPWorld.pathfind({x:n.ax,y:n.ay},{x:n.bx,y:n.by},PPScene.townSolids,PPScene.bounds,32,12).length>0,n.name);});
    check('A shelf obstructs interaction reach',()=>assert(PPWorld.segmentBlocked({x:200,y:300},{x:300,y:300},[{x:240,y:270,w:20,h:60}],0)));
    check('Activity rewards are finite and do not charge the reward as a fee',()=>{fixture();const cash=G.cash,well=G.well;trainStat('well',3);approx(G.well,well+3);approx(G.cash,cash);assert(PPFinance.validNumbers(G));});
    check('Daily pay reconciles to cents through gross, deductions, and net',()=>{const p=payStubMath(92.73);approx(p.gross,92.73);approx(p.tax,11.13);approx(p.pen,4.64);approx(p.ei,1.85);approx(p.net,75.11);approx(p.gross,p.deduct+p.net);});
    check('World controls are exclusive during work, cabinets, results, and pause',()=>{fixture();const p={...player};keys.arrowright=true;for(const kind of ['work','cabinet','results','pause']){MG.active=kind==='work';CB.active=kind==='cabinet';$('cbWrap').style.display=kind==='results'?'flex':'none';PPScene.paused=kind==='pause';PPScene.step(1/60);approx(player.x,p.x);approx(player.y,p.y);}MG.active=false;CB.active=false;$('cbWrap').style.display='none';PPScene.paused=false;PPScene.clearInput();});
    check('All four stat activities charge and award once, including quit',()=>{for(const kind of ['gym','school','book','diner']){fixture();const d=PPStats.defs[kind],cash=G.cash,stat=G[d.stat];PPStats.start(kind);PPStats.start(kind);approx(G.cash,cash-d.fee);if(kind==='gym'){const c=PPStats.state.circuit;c.points=[36,c.beats.length*3,100];c.elapsed=60;}PPStats.state.correct=17;PPStats.state.rapport=6;PPStats.finish();const earned=G[d.stat];assert(earned>stat,kind);PPStats.finish();approx(G[d.stat],earned);approx(G.cash,cash-d.fee);assert(PPFinance.validNumbers(G));}fixture();const before=G.well;PPStats.start('gym');PPStats.quit();approx(G.well,before);});
    check('Legacy paid gym state keeps original reward rules',()=>{fixture();PPStats.start('gym');const paid=G.cash,old=G.well;delete PPStats.state.rulesVersion;delete PPStats.state.circuit;PPStats.state.results=Array(10).fill('perfect');PPStats.finish();assert(G.well>old);approx(G.cash,paid);});
    check('Action receipt reports capped actual values',()=>{fixture();const before={...PPExperience.snapshot(),cash:100,energy:94,happy:88,stress:15},after={...before,cash:86,energy:100,happy:100,stress:11};const result=PPExperience.receiptText('Hot meal',before,after);assert(result.includes('Cash $100 → $86'));assert(result.includes('Energy 94 → 100 (capped at 100)'));assert(result.includes('Happiness 88 → 100 (capped at 100)'));});
    check('Collected pay stub stays in bank without paying twice',()=>{fixture();const st=payStubMath(2040),cash=G.cash;G.pendingShift={kind:'chaos',perf:85,rawPerf:85,pen:0,mult:.85,base:2400,gross:2040,early:false};applyShiftPay(st);approx(G.cash,cash+st.net);assert((G.payStubs||[]).length===1);assert(bankTabStubs().includes(fmt$(st.net)));applyShiftPay(st);approx(G.cash,cash+st.net);assert(G.payStubs.length===1);});
    check('Tutorial movement requires actual character travel',()=>{fixture();G.onboardDone=false;G.onboardStarted=true;G.onboard=0;onboardTick();assert(G.onboard===0);noteTutorialMovement();assert(G.onboard===1&&G.tutorialMoved);clearObjective();});
    check('Tutorial shopping and budget steps require their guided actions',()=>{fixture();G.onboardDone=false;G.onboardStarted=true;G.onboard=2;G.sawPlanner=true;G.groc.shopped=true;onboardTick();assert(G.onboard===2);G.tutorialGroceriesBought=true;onboardTick();assert(G.onboard===3);onboardTick();assert(G.onboard===3);G.tutorialBudgetSaved=true;onboardTick();assert(G.onboard===4);clearObjective();});
    check('All ten location comparisons open from current state',()=>{fixture();for(const id of Object.keys(EXAMINE)){PPPlaces.show(id);assert(modalOpen(),id+' did not open');assert($('modal').querySelector('button'),id+' has no choice');closeModal();}});
    check('Reward thresholds and wheel expectation match approved rules',()=>{approx(PPRules.rhythm(19),0);approx(PPRules.rhythm(20),1);approx(PPRules.rhythm(26),3);approx(PPRules.rhythm(29),6);approx(PPRules.racer(999,3),1.5);approx(PPRules.racer(1000,0),6);approx(PPRules.racer(650,3),.5);approx(PPRules.wheelEV(),1.2);let total=0;for(let i=0;i<10000;i++)total+=PPRules.wheel((i+.5)/10000);approx(total/10000,1.2);});
    check('Cabinet fee and payout settle once',()=>{fixture();G.arc.visitMonth=PPRules.period(G);const cash=G.cash,a=cabEnter('rhythm');assert(a);approx(G.cash,cash-4);assert(cabPayout(a,6));assert(!cabPayout(a,6));approx(G.cash,cash+2);const b=cabEnter('racer');cabQuit(b);assert(!cabPayout(b,6));});
    check('Loans keep arrears inside one carrying balance',()=>{const L={bal:1000,pay:100,left:12,arrears:0};let r=PPFinance.loanMonth(L,0);approx(r.loan.bal,1040);approx(r.loan.arrears,125);r=PPFinance.loanMonth(r.loan,500);approx(r.due,225);approx(r.loan.bal,830.6);approx(r.loan.arrears,0);const mature=PPFinance.loanMonth({bal:100,pay:90,left:0,arrears:90},0);assert(mature.loan.bal>100&&mature.loan.left===0);});
    check('Credit minimum is capped at balance and missed minimum has a consequence',()=>{approx(PPFinance.minimum(12.50),12.50);const missed=PPFinance.creditMonth(1000,0,25),paid=PPFinance.creditMonth(975,25,25);assert(missed.missed&&missed.fee===25);assert(!paid.missed&&paid.fee===0);approx(paid.interest,17.06);});
    check('Quick / Class / Life calendars settle a month only once',()=>{for(const pace of ['quick','class','life']){fixture(pace);G.campaign.day=pace==='life'?30:1;sleep();assert(G.month===2,pace+' month');assert(G.campaign.monthsSettled.length===1);const cash=G.cash;sleep();approx(G.cash,cash);assert(G.month===2);if(pace==='quick'){assert(G.campaign.chapter===1&&G.campaign.pendingMonths===1);}if(pace==='class')assert(G.campaign.chapter===2);if(pace==='life')assert(G.campaign.day===1);assert(PPFinance.validNumbers(G));}});
    check('Life Sim advances ordinary days without monthly bills or salary',()=>{fixture('life');const cash=G.cash;sleep();assert(G.campaign.day===2&&G.month===1);approx(G.cash,cash);});
    check('Twenty-four monthly settlements stay finite in all three modes',()=>{for(const pace of ['quick','class','life']){fixture(pace);G.cash=100000;for(let m=1;m<=24;m++){G.checkpoint=null;G.over=false;G.campaign.day=30;G.stress=10;G.energy=100;G.groc={cal:70000,spent:300,coffee:0,shopped:true};sleep();assert(G.month===m+1,pace+' at '+m);assert(PPFinance.validNumbers(G),pace+' numeric at '+m);}assert(G.campaign.monthsSettled.length===24);}});
    check('Saved activity state round-trips without DOM or audio handles',()=>{const state={kind:'rhythm',elapsed:6200,judged:[true,false],ac:()=>{},master:()=>{},nested:{score:7}};const copy=JSON.parse(JSON.stringify(PPCampaign.plain(state)));assert(copy.elapsed===6200&&copy.judged[0]&&copy.nested.score===7&&!('ac'in copy));assert(!PPFinance.validNumbers({...freshState(),ms:NaN}));});
    PPStats.suspend();MG.active=false;CB.active=false;$('mgWrap').style.display='none';$('cbWrap').style.display='none';$('endWrap').style.display=originalEnd;
    G=original;screen=originalScreen;PPScene.paused=originalPause;closeModal();hud();PPCampaign.restoring=false;PPCampaign.dirty=false;
    const failed=results.filter(r=>!r.pass);$('reviewResults').textContent=JSON.stringify({passed:results.length-failed.length,total:results.length,results},null,2);panel.dataset.result=failed.length?'failed':'passed';
  };
}
