/* Readable status, action receipts, and a replayable first-session guide. */
window.PPExperience=(()=>{
  const status=$('hud'),receipt=$('actionReceipt'),details=$('statusDetails');
  const fields=[['cash','Cash',v=>fmt$(v)],['savings','Savings',v=>fmt$(v)],['debt','Debt',v=>fmt$(v)],['energy','Energy',v=>String(Math.round(v))],['happy','Happiness',v=>String(Math.round(v))],['stress','Stress',v=>String(Math.round(v))],['ms','Money skill',v=>String(Math.round(v))],['well','Wellness',v=>String(Math.round(v))],['ps','People skill',v=>String(Math.round(v))],['score','Credit',v=>String(Math.round(v))]];
  const state=()=>Object.fromEntries(fields.map(([k])=>[k,k==='debt'?_r2((G.debt||0)+(G.loan?.bal||0)):Number(G[k]||0)]));
  const cleanLabel=label=>ppPlainText(label||'Action').replace(/\s+/g,' ').split('—')[0].trim().slice(0,60);
  function receiptText(label,before,after){const changes=[];
    for(const [key,name,format] of fields){if(Math.abs(after[key]-before[key])<.005)continue;let line=`${name} ${format(before[key])} → ${format(after[key])}`;if(['energy','happy'].includes(key)&&after[key]===100)line+=' (capped at 100)';if(key==='stress'&&after[key]===0)line+=' (floor 0)';changes.push(line);}
    return changes.length?`${cleanLabel(label)}: ${changes.join(' · ')}`:'';
  }
  function updateReceipt(){const latest=G.actionHistory?.at(-1);receipt.textContent=latest?.text||'Choose an action to see its effect';receipt.title=G.actionHistory?.length?'Show recent changes':'Your action results appear here';}
  function record(label,before,extra=''){if(!before||!G.campaign||PPCampaign.restoring)return;const text=receiptText(label,before,state());if(!text&&!extra)return;G.actionHistory=G.actionHistory||[];G.actionHistory.push({month:G.month,day:G.campaign.day||1,text:text+(extra?' · '+extra:'')});G.actionHistory=G.actionHistory.slice(-8);updateReceipt();save();}
  function action(label,fn){const before=state();const result=fn();record(label,before);return result;}
  for(const host of [$('modal'),$('mgWrap'),$('cbWrap')])host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||!G.campaign)return;const before=state(),label=b.textContent;setTimeout(()=>record(label,before),0);},true);
  const history=document.createElement('div');history.id='receiptHistory';history.hidden=true;history.setAttribute('aria-label','Recent changes');document.body.appendChild(history);
  receipt.onclick=()=>{if(!G.actionHistory?.length)return;history.hidden=!history.hidden;if(history.hidden)return;history.replaceChildren();const title=document.createElement('strong');title.textContent='Recent changes';history.append(title);for(const item of [...G.actionHistory].reverse()){const p=document.createElement('p');p.textContent=`Month ${item.month}${G.campaign?.pace==='life'?' · day '+item.day:''}: ${item.text}`;history.append(p);}const close=document.createElement('button');close.textContent='Close';close.onclick=()=>history.hidden=true;history.append(close);};
  details.onclick=()=>{const expanded=status.classList.toggle('expanded');details.textContent=expanded?'Less status':'More status';details.setAttribute('aria-expanded',String(expanded));};
  new ResizeObserver(()=>{document.documentElement.style.setProperty('--hud-h',status.getBoundingClientRect().height+'px');}).observe(status);
  const priorHud=hud;hud=()=>{priorHud();if(status.style.display==='flex')status.style.display='grid';if(!G.campaign)return;const c=G.campaign,m=PPCampaign.MODES[c.pace];$('hMonth').parentElement.innerHTML=`<i>${c.pace==='life'?'Day':'Chapter'}</i><b id="hMonth">${c.pace==='life'?`${c.day} · Mo ${Math.min(24,G.month)}`:`${c.chapter}/${m.chapters} · Mo ${Math.min(24,G.month)}`}</b>`;$('hHappy').parentElement.querySelector('i').textContent='Happiness';$('hDebt').parentElement.querySelector('i').textContent='Debt';$('hDebt').textContent=fmt$(_r2((G.debt||0)+(G.loan?.bal||0)));$('hStats').parentElement.querySelector('i').textContent='Skills';$('hStats').textContent=`Money ${Math.round(G.ms)} · Well ${Math.round(G.well)} · People ${Math.round(G.ps)}`;if($('hEfund').textContent==='…')$('hEfund').textContent='Calculating';updateReceipt();};

  const help=document.createElement('section');help.id='helpPanel';help.className='help-panel';help.hidden=true;help.innerHTML='<div role="dialog" aria-modal="true" aria-labelledby="helpTitle"><h2 id="helpTitle">How to play</h2><div id="helpBody"></div><div id="helpPractice"></div><button id="helpDone">Return to game</button></div>';document.body.appendChild(help);
  let pausedForHelp=false,helpFromTitle=false,previousFocus=null;
  function introText(){const pace=G.campaign?.pace||'class';return pace==='life'?'Life Sim: sleep advances one day. Bills and reviews arrive after day 30.':pace==='quick'?'Quick Run: one chapter covers two months. Events and decisions interrupt the approved routine.':'Class Campaign: sleep advances one month and stops at reviews and decisions.';}
  function milestoneText(){if(!G.campaign)return '';
    const reserve=(G.savings||0)>=1000?'Reached $1,000 reserve':`${fmt$((G.savings||0))} / $1,000 reserve`;
    const promo=G.miles?.promos?.length?'Promoted at least once':`Next promotion: ${G.onboardStarted?nextCareerReq()?.name||'Top of lane':'choose a job'}`;
    const debt=(G.debt||0)+(G.loan?.bal||0)<=0?'No debt outstanding':`${fmt$((G.debt||0)+(G.loan?.bal||0))} debt outstanding`;
    return `<div class="help-milestones"><span>${reserve}</span><span>${promo}</span><span>${debt}</span></div>`;
  }
  function renderHelp(intro){const body=$('helpBody');body.innerHTML=`<p><b>Your goal:</b> Build a stable life over 24 months. Earn income, cover essentials, manage debt, improve your career, and save for surprises. Finish month 24 to complete the campaign. Cash below -$200 ends the run.</p><p><b>Move:</b> WASD, arrows, or the touch stick. Walk up to a door or marked activity and press E or tap the action button. Click an open floor space to walk there.</p><p><b>Choices:</b> Play a shift to earn a paycheck. Gross pay is before the game's fictional deductions; net pay goes into cash. Work performance and skills help promotions. Food and rest support energy and happiness. Spending and borrowing affect future bills.</p><p><b>Time:</b> ${intro?'Choose Quick Run, Class Campaign, or Life Sim next. Quick groups two months per chapter, Class reviews each month, and Life plays individual days.':introText()+' Quick and Class ask you to approve recurring choices before advancing.'} The arcade costs entertainment money.</p>${intro?'':milestoneText()+`<p><b>Next goal:</b> ${G.onboardStarted&&!G.onboardDone?ppPlainText(onboardGoalHTML()).replace(/<[^>]*>/g,' '):'Check your calendar, cover essentials, and choose a savings target.'}</p>`}`;
    $('helpDone').textContent=intro?'Choose campaign':'Return to game';$('helpDone').onclick=()=>{closeHelp();if(intro)pickMode();};
    const practice=$('helpPractice');practice.replaceChildren();if(!intro&&G.onboardStarted){const b=document.createElement('button');b.textContent='Try a free practice choice';b.className='secondary';b.onclick=practiceChoice;practice.append(b);}
  }
  function showHelp(intro=false){previousFocus=document.activeElement;helpFromTitle=intro;pausedForHelp=screen!=='title'&&!PPScene.paused;if(pausedForHelp)PPScene.togglePause();renderHelp(intro);help.hidden=false;$('helpDone').focus();}
  function closeHelp(){help.hidden=true;if(pausedForHelp&&PPScene.paused)PPScene.togglePause();pausedForHelp=false;previousFocus?.focus?.();}
  $('helpPanel').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeHelp();}if(e.key==='Tab'){const controls=[...help.querySelectorAll('button:not([disabled])')];if(!controls.length)return;const index=controls.indexOf(document.activeElement);if(e.shiftKey&&index<=0){e.preventDefault();controls.at(-1).focus();}else if(!e.shiftKey&&index===controls.length-1){e.preventDefault();controls[0].focus();}}});
  function practiceChoice(){const p=$('helpPractice');p.replaceChildren();const lane=G.lane;const q=lane==='retail'?{text:'Practice checkout: the visible price is $3.29. Which key scans it?',options:['1 · $3.29','2 · $2.27'],right:0}:lane==='office'?{text:'Practice inbox: a message urgently demands gift-card payment. What is safer?',options:['Pay now','Verify the sender'],right:1}:{text:'Practice delivery: traffic blocks the fastest road. What protects the parcel and your earnings?',options:['Take a safe clear route','Drive through traffic'],right:0};const text=document.createElement('p');text.textContent=q.text;p.append(text);q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='practice-choice';b.textContent=option;b.onclick=()=>{p.replaceChildren();const answer=document.createElement('p');answer.textContent=i===q.right?'Good choice. This practice costs nothing.':'Try the safer, more accurate choice next time. This practice costs nothing.';p.append(answer);};p.append(b);});}
  const helpButton=document.createElement('button');helpButton.textContent='How to play';helpButton.id='ppHelp';helpButton.onclick=()=>showHelp(false);$('worldTools').prepend(helpButton);
  const titleHelp=document.createElement('button');titleHelp.textContent='How to play';titleHelp.className='bigbtn ghost';titleHelp.onclick=()=>showHelp(false);$('btnContinue').after(titleHelp);
  $('btnStart').addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showHelp(true);},true);
  onboardGoalHTML=()=>{if(!G.onboardStarted||!LANES[G.lane])return '';const work=MAP_BUILDINGS.find(b=>b.id===LANES[G.lane].workplace)?.name||'workplace';switch(G.onboard){case 0:return `Goal 1/5: Move with arrows, WASD, or touch. Walk to ${work}; press E or tap to enter.`;case 1:return `Goal 2/5: Use the work station and complete a shift. Collect your net pay on the pay stub.`;case 2:return 'Goal 3/5: Shop at FreshMart. Watch cash and happiness change in the status header.';case 3:return 'Goal 4/5: At the Bank, enter a budget and press Save plan. Opening the planner alone does not finish this goal.';default:return `Goal 5/5: Return home and sleep. ${G.campaign?.pace==='life'?'One day passes; monthly bills arrive after day 30.':G.campaign?.pace==='quick'?'Review the approved routine for a two-month chapter; decisions pause it.':'A month passes, followed by bills and a review.'}`;}};
  const oldPause=PPScene.togglePause;PPScene.togglePause=()=>{oldPause();if(PPScene.paused&&G.campaign)save();};
  return{snapshot:state,record,action,showHelp,closeHelp,renderHelp,receiptText,updateReceipt};
})();
