/* Location details expose real decisions and use the live game economy. */
window.PPPlaces=(()=>{
  const back={label:'Back to room',fn:closeModal};
  function showMenu(title,desc,buttons,lesson){return window.showMenu(title,desc,buttons.filter(b=>b!==back),lesson);}
  const period=()=>PPCampaign.period();
  const resetLabel=()=>G.campaign?.pace==='life'?'tomorrow':'next month';
  const used=id=>G.placeUses?.[id]===period();
  const mark=id=>{G.placeUses=G.placeUses||{};G.placeUses[id]=period();};
  function recover(id,energy,stress,label){if(used(id)){toast(`Already used. Available ${resetLabel()}.`);return;}const gained=Math.min(energy,100-G.energy),relieved=Math.min(stress,G.stress);if(!gained&&!relieved){toast('Energy and stress are already at their best values.');return;}mark(id);G.energy=clamp(G.energy+energy,0,100);G.stress=clamp(G.stress-stress,0,100);hud();save();show(id);}
  function show(id){
    if(id==='home'){showMenu('Apartment window',`Take a quiet breathing break: up to 4 less stress, once per ${G.campaign?.pace==='life'?'day':'month'}. Current stress ${Math.round(G.stress)}. ${used(id)?'Available '+resetLabel()+'.':''}`,[{label:used(id)?`Already used — available ${resetLabel()}`:'Take breathing break',fn:()=>recover(id,0,4,'Breathing break'),disabled:used(id)||G.stress<=0},back],'Small recovery helps you make thoughtful choices. Sleeping and the larger nap remain separate actions.');return;}
    if(id==='office'){const next=nextCareerReq();showMenu('Office noticeboard',next?`Next role: <b>${next.name}</b>, pay ${fmt$(next.salary)}/month. ${next.parts.map(p=>`${p.ok?'Met':'Needed'}: ${ppPlainText(p.label)}`).join(' · ')}. Strong shifts require at least 80% performance.`:'You have reached the highest role in this career lane.',[{label:'Go to work desk',fn:openOffice},{label:'View training at school',fn:()=>{closeModal();leaveInterior();toast('Use Locations to walk to Night School.');}},back],'The current career rules, performance, and skills determine promotions.');return;}
    if(id==='grocery'){const options=['rice','pasta'].map(x=>GROC_ITEMS.find(i=>i.id===x)),[a,b]=options,pa=itemPrice(a.id),pb=itemPrice(b.id),ua=_r2(pa/a.cal*1000),ub=_r2(pb/b.cal*1000),cheap=ua<=ub?a:b;showMenu('Shelf price comparison',`${a.name}: ${fmt$(pa)} for ${a.cal.toLocaleString()} calories (${fmt$(ua)} per 1,000 calories; happiness +${a.happy}).<br>${b.name}: ${fmt$(pb)} for ${b.cal.toLocaleString()} calories (${fmt$(ub)} per 1,000 calories; happiness +${b.happy}).<br><b>${cheap.name}</b> currently costs less per calorie. Compare variety and happiness too.`,[{label:`Add ${cheap.name} to grocery cart`,fn:()=>{cart[cheap.id]=(cart[cheap.id]||0)+1;renderMarket();}},{label:'Open grocery shop',fn:renderMarket},back],'Unit prices use this month’s actual sale and shortage prices.');return;}
    if(id==='bank'){const savingsInterest=_r2(G.savings*.003),cardInterest=_r2(G.debt*.0175),loanInterest=_r2((G.loan?.bal||0)*.015);showMenu('Interest on your balances',`If balances stayed the same for one month: savings interest about <b>${fmt$(savingsInterest)}</b>; card interest about <b>${fmt$(cardInterest)}</b>${G.loan?`; loan interest about <b>${fmt$(loanInterest)}</b>`:''}. Payments and new spending change the actual amounts.`,[{label:'Open bank options',fn:()=>{G.bankTab='save';openBank();}},{label:'Review debt and repayments',fn:()=>{G.bankTab='debt';openBank();}},back],'Saving can earn interest. Carrying debt costs interest; compare rates and your upcoming bills.');return;}
    if(id==='school'){const next=nextCareerReq();showMenu('Course catalog',`Sort It Out costs <b>$40 and 6 energy</b> and can earn 1–3 Money Smarts from your score. Current Money Smarts: ${Math.round(G.ms)}. ${next?`Next career role ${next.name}: ${next.parts.map(p=>`${p.ok?'Met':'Needed'} ${ppPlainText(p.label)}`).join(' · ')}.`:'You are at the highest career tier.'}`, [{label:'View Sort It Out',fn:openSortItOut},back],'Compare the training cost with the career skill it can build.');return;}
    if(id==='gym'){showMenu('Water fountain',`Refill water: up to <b>+4 energy and -2 stress</b> at no cash cost, once per ${G.campaign?.pace==='life'?'day':'month'}. Energy ${Math.round(G.energy)}, stress ${Math.round(G.stress)}. ${used(id)?'Available '+resetLabel()+'.':''}`, [{label:used(id)?`Already used — available ${resetLabel()}`:'Drink water',fn:()=>recover(id,4,2,'Water fountain'),disabled:used(id)||(G.energy>=100&&G.stress<=0)},back],'A small, reliable recovery choice can reduce the need for a paid drink.');return;}
    if(id==='diner'){const news=G.mktNews?.length?ppPlainText(G.mktNews[0]):'No grocery supply change is posted this month.',energy=Math.round(G.energy),hot=Math.min(20,100-energy),burger=Math.min(12,100-energy);showMenu('Today at the diner',`Current market notice: ${news}<br>For your current energy ${energy}: the $14 hot meal would restore ${hot}; the $9 burger would restore ${burger}. Compare the cash and energy tradeoff before ordering.`,[{label:'View diner menu',fn:openDiner},back],'Menu effects are capped by your current state; the posted supply notice applies this month.');return;}
    if(id==='mall'){const budget=Number(G.budgetPlan?.fun||0),spent=Number(G.actuals?.fun||0),remaining=_r2(budget-spent),saved=!!G.wishlist?.movie;showMenu('Mall window display',`Your fun plan: ${fmt$(budget)}. Spent so far: ${fmt$(spent)}. ${remaining>=0?`Remaining ${fmt$(remaining)}`:`Over plan by ${fmt$(-remaining)}`}. Movie night costs $40 and offers up to 10 happiness. ${saved?'Movie night is on your wishlist.':''}`,[{label:saved?'Movie night saved to wishlist':'Save movie night to wishlist',fn:()=>{G.wishlist=G.wishlist||{};G.wishlist.movie=true;save();show('mall');},disabled:saved},{label:'View mall choices',fn:openMall},back],'Saving an idea to a wishlist costs nothing. Buying it later still uses the regular price and game rules.');return;}
    if(id==='dealer'){showMenu('Transport comparison',`Total recurring bills: ${fmt$(G.bills)} per month. ${G.flags.bike?'Bike owned; bus pass removed.':'A bike costs $350 and removes the $110 monthly bus pass (about four months to break even).'} ${G.flags.car?'Car owned; insurance is included in your current bills.':'A cash car costs $6,000 plus $120/month insurance; credit adds $6,000 card debt at 1.75% monthly interest.'}`, [{label:'View transport choices',fn:openDealer},back],'Compare upfront cost, recurring bills, and debt before buying. Other car costs can occur through game events.');return;}
    if(id==='lucky'){const s=casinoState(),left=s.cap===null?null:Math.max(0,s.cap-s.spent);const buttons=[];if(s.cap===null)for(const n of [0,10,20,50])buttons.push({label:n?`Set ${fmt$(n)} entertainment limit`:'Skip paid games this period',fn:()=>{G.casinoLimit={period:period(),cap:n,spent:0};save();show('lucky');}});buttons.push({label:'View casino games',fn:openLucky},back);showMenu('Odds and spending limit',`Slots: a pair pays $3, triples $50, three sevens $500. Roulette red/black: 18/37 chance to receive $20 on a $10 bet. Lucky 7: 4% to receive $100 on a $5 bet. Ticket: 1% to receive $100 on a $2 bet.<br>${s.cap===null?'Choose a spending limit for this period before playing.':`Limit ${fmt$(s.cap)}; wagered ${fmt$(s.spent)}; remaining ${fmt$(left)}. This limit stays locked until ${resetLabel()}.`}`,buttons,'Payouts include any returned stake. Track wagers separately from winnings.');}
  }
  function casinoState(){const p=period(),s=G.casinoLimit;return s?.period===p?s:{period:p,cap:null,spent:0};}
  function casinoAllowed(bet){const s=casinoState();if(s.cap===null){toast('Set an entertainment limit at the odds poster before playing.');return false;}if(s.spent+bet>s.cap){toast(`This wager exceeds your remaining ${fmt$(Math.max(0,s.cap-s.spent))} limit. Available ${resetLabel()}.`);return false;}return true;}
  function casinoSpent(bet){const s=casinoState();if(s.cap===null)return;G.casinoLimit={...s,spent:_r2(s.spent+bet)};save();}
  openExamine=show;for(const id of Object.keys(EXAMINE))MENU_FNS['ex'+id[0].toUpperCase()+id.slice(1)]=()=>show(id);
  Object.assign(PPExperience,{casinoState,casinoAllowed,casinoSpent});
  return{show,period,used,casinoState,casinoAllowed,casinoSpent};
})();
