/* Paycheck Panic 3: a fictional Alberta case, integer cents, explicit commitments. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.PPSim=api;})(typeof window==='object'?window:globalThis,function(){
'use strict';
const VERSION='2026.09.financial-story.1',round=Math.round;
const profiles={
 student:{name:'Finishing high school',age:18,wage:1750,hours:48,cash:30000,emergency:15000,foodShare:1/3,transport:8000,goal:'A course and equipment fund',intro:'You live at home while finishing school. Your household covers housing and two-thirds of a shared food plan. You contribute to food, travel, your phone, and personal essentials. Support is part of this case, not a measure of effort.',bills:[['Household essentials',4000,24,'essentials'],['Transit pass',8000,2,'transport'],['Phone plan',4500,20,'phone']]},
 independent:{name:'Starting independent life',age:20,wage:1850,hours:160,cash:150000,emergency:30000,foodShare:1,transport:11000,goal:'A move and training fund',intro:'You share an apartment and work a scheduled full-time job. Rent, food, utilities, travel, and insurance are your responsibility. Your $1,500 opening cash includes money needed before the first payday.',bills:[['Shared rent',95000,1,'housing'],['Utilities and internet',10000,10,'utilities'],['Transit pass',11000,2,'transport'],['Tenant insurance',2500,5,'insurance'],['Phone plan',4500,20,'phone'],['Household essentials',6000,24,'essentials']]}
};
const foodGroups=[
 {id:'staples',name:'Staples and breakfasts',art:'rice',sheet:'groceriesExtra',description:'Rice, oats, pasta, bread, potatoes; package quantities cover this case’s month.',options:[{name:'Value staples',cost:5500},{name:'Mixed staples',cost:7500},{name:'Prepared breakfasts',cost:11000}]},
 {id:'protein',name:'Protein and main dishes',art:'eggs',sheet:'groceries',description:'Beans, eggs, dairy, chicken or alternatives; compare batch cooking with prepared meals.',options:[{name:'Beans, eggs, batch meals',cost:10500},{name:'Mixed home cooking',cost:14000},{name:'Prepared main dishes',cost:23000}]},
 {id:'produce',name:'Fruit and vegetables',art:'veggies',sheet:'groceriesExtra',description:'Fresh and frozen produce; frozen packs make leftovers easier to plan.',options:[{name:'Seasonal and frozen',cost:7500},{name:'Mixed produce',cost:9000},{name:'Prepared produce',cost:11000}]},
 {id:'pantry',name:'Pantry and meal extras',art:'milk',sheet:'groceries',description:'Cooking ingredients, drinks, spreads, and meal extras. All four groups make a complete simulation basket.',options:[{name:'Basic pantry',cost:4500},{name:'Mixed pantry',cost:5500},{name:'Convenience extras',cost:7000}]}
];
const chapters=[
 {title:'Your money has jobs',npc:'Marta, your supervisor',opening:'The first payday is still ahead. Look at what is due before it, then give your money a job.',tasks:[['move','Walk around town','town'],['budget','Save a cash-flow plan','bank'],['food','Buy a complete monthly meal basket','grocery'],['paystub','Check a collected pay stub','office']]},
 {title:'A deal worth taking?',npc:'Devon, your friend',opening:'“Only $25 a month” sounds manageable. What does the whole agreement cost, and what else would you give up?',tasks:[['contract','Compare and choose a device arrangement','mall'],['social','Plan something you value','diner']]},
 {title:'Getting ahead costs something',npc:'Rae, the transport adviser',opening:'Transport and training could open doors. Compare the full commitment with the money and time you actually have.',tasks:[['transport','Choose a transport plan','dealer'],['borrowing','Compare two borrowing offers','bank']]},
 {title:'The plan meets real life',npc:'Marta, your supervisor',opening:'This month has 20% fewer scheduled hours. Your obligations continue. A revised plan can protect what matters most.',tasks:[['recovery','Revise the plan after reduced hours','home'],['debtStrategy','Compare responses to growing debt','bank']]},
 {title:'What should this dollar do next?',npc:'Avery, the bank adviser',opening:'Near-term goals need access to money. Long-term products bring different risks. Decide what each dollar is for.',tasks:[['allocation','Choose saving, debt, or investing','bank'],['future','Test inflation, risk, and leverage','bank'],['mortgage','Explore a future mortgage case','bank']]},
 {title:'Protect what you built',npc:'Devon, your friend',opening:'An urgent message uses details from a public profile. Verify the request, protect the account, and review your plan.',tasks:[['security','Reduce fictional information exposure','office'],['fraud','Verify a suspicious message and choose a response','office'],['consumer','Investigate a misleading offer','mall']]}
];
function money(c){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100);}
function initial(profile='independent',mode='story',seed=123456){const p=profiles[profile];if(!p||!['story','free'].includes(mode))throw Error('Unknown scenario');return {schema:3,rules:VERSION,id:'',profile,mode,char:'alex',month:1,day:0,cash:p.cash,emergency:p.emergency,goal:0,investment:0,card:0,loan:null,unpaid:[],ledger:[],receipts:{},decisions:[],tasks:{},budgets:{},budgetDraft:null,food:null,blocks:4,extraHours:0,trained:false,trainingMonth:0,transport:'transit',contract:null,casino:null,casinoNet:0,casinoWagers:0,rng:seed>>>0||1,activity:null,energy:80,happiness:70,stress:20,playedSeconds:0,completed:false,position:{room:null,x:240,y:424,dir:'s'},settings:{muted:false,reduced:false},ytd:{gross:0,cpp:0,ei:0,tax:0,net:0},stubs:[],statement:0,paidCard:0,investmentHistory:[],used:{}};}
function valid(s){const finite=v=>typeof v==='number'?Number.isFinite(v):!v||typeof v!=='object'||Object.values(v).every(finite),cent=v=>Number.isSafeInteger(v)&&v>=0,obj=v=>v&&typeof v==='object'&&!Array.isArray(v);try{return !!(s&&finite(s)&&s.schema===3&&s.rules===VERSION&&profiles[s.profile]&&['story','free'].includes(s.mode)&&['alex','maya','jay','sam','classic'].includes(s.char)&&['cash','emergency','goal','investment','card','blocks','month','day','statement','paidCard','extraHours','casinoWagers'].every(k=>cent(s[k]))&&s.month>=1&&s.day<=30&&s.blocks<=4&&['energy','happiness','stress'].every(k=>typeof s[k]==='number'&&s[k]>=0&&s[k]<=100)&&Number.isInteger(s.rng)&&s.rng>0&&Array.isArray(s.ledger)&&s.ledger.every(t=>obj(t.delta)&&obj(t.before)&&Object.values(t.delta).every(Number.isSafeInteger)&&Object.values(t.before).every(cent))&&Array.isArray(s.unpaid)&&s.unpaid.every(b=>cent(b.amount)&&typeof b.bill==='string')&&Array.isArray(s.decisions)&&Array.isArray(s.stubs)&&obj(s.ytd)&&Object.values(s.ytd).every(cent)&&obj(s.budgets)&&Object.values(s.budgets).every(b=>Object.values(b).every(cent))&&obj(s.tasks)&&obj(s.receipts)&&obj(s.used)&&obj(s.settings)&&typeof s.settings.muted==='boolean'&&typeof s.settings.reduced==='boolean'&&obj(s.position)&&typeof s.position.x==='number'&&typeof s.position.y==='number'&&(!s.loan||['principal','balance','payment','arrears'].every(k=>cent(s.loan[k]))&&s.loan.arrears<=s.loan.balance&&typeof s.loan.apr==='number'&&s.loan.apr>=0&&s.loan.apr<=1)&&(!s.activity||['gym','checkout','inbox','delivery','rhythm','racer','claw','wheel','trader'].includes(s.activity.kind)&&typeof s.activity.elapsed==='number'&&s.activity.elapsed>=0&&typeof s.activity.duration==='number'&&s.activity.duration>0&&Array.isArray(s.activity.items)&&Array.isArray(s.activity.points)&&s.activity.points.length===3&&Array.isArray(s.activity.market)&&typeof s.activity.score==='number')&&(!s.casino||cent(s.casino.limit)&&cent(s.casino.wagered)&&cent(s.casino.plays)));}catch(e){return false;}}
function record(s,key,label,delta,category='other',details={}){if(s.receipts[key])return false;for(const [k,n]of Object.entries(delta))if(!Number.isSafeInteger(n)||!Number.isSafeInteger(s[k]+n)||s[k]+n<0)throw Error('Transaction would overdraw '+k);const before={};for(const k of Object.keys(delta)){before[k]=s[k];s[k]+=delta[k];}s.receipts[key]=true;s.ledger.push({id:key,month:s.month,day:s.day,label,category,delta,before,...details});return true;}
function marked(s,key){return !!s.tasks[s.month+':'+key];}
function mark(s,key){s.tasks[s.month+':'+key]=true;}
function reason(s,key,choice,text){const id=s.month+':'+key;const existing=s.decisions.find(d=>d.id===id);if(existing)return; s.decisions.push({id,month:s.month,day:s.day,key,choice,reason:String(text||'').trim(),cash:s.cash,goal:s.goal,card:s.card,forecast:forecast(s)});mark(s,key);}
function monthlyHours(s){return profiles[s.profile].hours*(s.month===4?.8:1)+s.extraHours;}
function payroll(gross){ // Limited case: Alberta basic claims, 24 periods, annual earnings under $50,000.
 const annual=gross*24/100,cpp=round(Math.max(0,gross/100-3500/24)*.0595*100),ei=round(gross*.0163),baseCPP=Math.max(0,annual-3500)*.0495,additional=Math.max(0,annual-3500)*.01,taxable=annual-additional;
 const fed=Math.max(0,taxable*.14-.14*(16452+1501+baseCPP+annual*.0163)),ab=Math.max(0,taxable*.08-.08*(22769+baseCPP+annual*.0163));const tax=round((fed+ab)/24*100);return{gross,cpp,ei,tax,net:gross-cpp-ei-tax};
}
function wage(s){return profiles[s.profile].wage+(s.trained&&s.month>s.trainingMonth?50:0);}
function payHours(s,day){const paid=s.stubs.filter(p=>p.month===s.month).reduce((n,p)=>n+p.hours,0);return day===15?monthlyHours(s)/2:Math.max(0,monthlyHours(s)-paid);}
function projectedPay(s,day=s.day<15?15:30){return payroll(round(wage(s)*payHours(s,day)));}
function monthNet(s){const stubs=s.stubs.filter(p=>p.month===s.month);if(stubs.length===2)return stubs.reduce((n,p)=>n+p.net,0);return stubs.length===1?stubs[0].net+projectedPay(s,30).net:projectedPay(s,15).net*2;}
function bills(s){const a=profiles[s.profile].bills.map(([name,amount,day,category])=>({id:category,name,amount,day,category}));if(s.transport==='bike'){const i=a.findIndex(b=>b.id==='transport');if(i>=0)a.splice(i,1);a.push({id:'bike',name:'Bike maintenance reserve',amount:1000,day:24,category:'transport'});}if(s.contract?.kind==='term'&&s.month<s.contract.start+24)a.push({id:'device',name:'Device instalment',amount:2500,day:20,category:'phone'});return a;}
function foodQuote(s,choices=[1,1,1,1]){if(choices.length!==4||choices.some((c,i)=>!foodGroups[i].options[c]))return {ok:false,error:'Choose a basket for every meal group.'};const inflation=s.month>=6?1.05:1,total=round(foodGroups.reduce((n,g,i)=>n+g.options[choices[i]].cost,0)*inflation),cost=round(total*profiles[s.profile].foodShare);const blocks=choices.every(c=>c===0)?2:choices.every(c=>c===2)?0:1;return{ok:true,kind:'food',choices:[...choices],total,cost,blocks,days:30,label:'Monthly meal basket',category:'food',support:total-cost};}
function loanPayment(principal,apr,months,convention='monthly'){const r=convention==='semiannual'?Math.pow(1+apr/2,1/6)-1:apr/12;return r?round(principal*r/(1-Math.pow(1+r,-months))):Math.ceil(principal/months);}
function schedule(principal,apr,months,convention='monthly'){const rate=convention==='semiannual'?Math.pow(1+apr/2,1/6)-1:apr/12,payment=loanPayment(principal,apr,months,convention),rows=[];let balance=principal,total=0;for(let i=1;i<=months+5&&balance>0;i++){const interest=round(balance*rate),paid=Math.min(balance+interest,payment);balance=balance+interest-paid;total+=paid;rows.push({period:i,interest,principal:paid-interest,payment:paid,balance});}return{payment,rows,total,interest:total-principal};}
function minimum(balance){return Math.min(balance,Math.max(2500,round(balance*.02)));}
function forecast(s){const nextPay=s.day<15?15:30,pay=projectedPay(s),due=bills(s).filter(b=>b.day>s.day&&b.day<=nextPay).reduce((n,b)=>n+b.amount,0),arrears=s.unpaid.reduce((n,b)=>n+b.amount,0),cardDue=s.day<25&&nextPay>=25?Math.max(0,minimum(s.statement)-s.paidCard):0,loanDue=s.day<25&&nextPay>=25&&s.loan?Math.min(s.loan.balance+round(s.loan.balance*s.loan.apr/12),s.loan.payment+s.loan.arrears):0,food=s.food?.month===s.month||marked(s,'food')?0:foodQuote(s).cost,plan=s.budgets[s.month]||{},saved=k=>s.ledger.filter(t=>t.month===s.month).reduce((n,t)=>n+Math.max(0,t.delta[k]||0),0),reserved=Math.max(0,(plan.goal||0)-saved('goal'))+Math.max(0,(plan.emergency||0)-saved('emergency'));return{nextPay,pay:pay.net,due:due+cardDue+loanDue,arrears,food,reserved,available:s.cash-due-cardDue-loanDue-arrears-food-reserved,monthNet:monthNet(s),monthlyBills:bills(s).reduce((n,b)=>n+b.amount,0)};}
function quote(s,kind,arg={}){if(!['food','gym','membership','arcade','meal','social','rest','training','extra','bike','contract','emergency','goal','invest','repay','arrears','loan','withdraw','scam','accessory'].includes(kind))return{ok:false,error:'Unknown choice.'};let q={ok:true,kind,label:kind,cost:0,blocks:0,category:'other',...arg};if(kind==='food')q=foodQuote(s,arg.choices);
 if(kind==='gym')Object.assign(q,{label:'Gym visit',cost:s.used.membership===s.month?0:1200,blocks:1,category:'leisure'});
 if(kind==='membership')Object.assign(q,{label:'Monthly gym membership',cost:4500,category:'leisure'});
 if(kind==='arcade')Object.assign(q,{label:'Arcade visit',cost:500,blocks:1,category:'leisure'});
 if(kind==='scam')Object.assign(q,{label:'Pay unverified fee',cost:7500,category:'loss'});if(kind==='accessory')Object.assign(q,{label:'Accessory with disclosed fee',cost:4200,category:'leisure'});
 if(kind==='meal')Object.assign(q,{label:'Diner meal',cost:arg.small?900:1800,category:'leisure'});
 if(kind==='social')Object.assign(q,{label:arg.choice==='free'?'Walk and meet a friend':'Movie and food with friends',cost:arg.choice==='free'?0:3500,blocks:1,category:'leisure'});
 if(kind==='rest')Object.assign(q,{label:'Rest and regroup',blocks:1,category:'wellbeing'});
 if(kind==='training')Object.assign(q,{label:'Workplace certificate',cost:12000,blocks:2,category:'training'});
 if(kind==='extra')Object.assign(q,{label:'An extra 8-hour shift',blocks:1,category:'work'});
 if(kind==='bike')Object.assign(q,{label:'Used bicycle and lock',cost:35000,category:'transport'});
 if(kind==='contract')Object.assign(q,{label:arg.choice==='cash'?'Buy refurbished device':arg.choice==='term'?'Start 24-month device agreement':'Keep current device',cost:arg.choice==='cash'?42000:0,category:'phone',commitment:arg.choice==='term'?60000:0});
 if(['emergency','goal','invest','repay','arrears'].includes(kind))Object.assign(q,{label:{emergency:'Transfer to emergency savings',goal:'Transfer to your goal',invest:'Invest for a long-term goal',repay:'Pay down card debt',arrears:'Pay overdue obligations'}[kind],cost:arg.amount,category:kind});
 if(kind==='loan')Object.assign(q,{label:'Take a 12-month personal loan',cost:0,amount:arg.amount,category:'borrowing'});
 if(kind==='withdraw')Object.assign(q,{label:'Use emergency savings',cost:0,amount:arg.amount,category:'transfer'});
 if(!q.ok)return q;if(!Number.isSafeInteger(q.cost)||q.cost<0)q.error='Enter a positive amount in dollars and cents.';
 if(q.cost>s.cash)q.error='There is not enough cash. Review savings, obligations, or an alternative.';
 if(q.blocks>s.blocks)q.error='No discretionary time remains for that choice this month.';
 if(kind==='food'&&s.food?.month===s.month)q.error='This month’s basket is already paid and covers 30 days.';
 if(kind==='training'&&s.trained)q.error='This certificate is already complete.';
 if(kind==='extra'&&(s.extraHours||s.day>=30))q.error='The extra shift is available once before the last payday.';
 if(kind==='bike'&&s.transport==='bike')q.error='You already own the bike.';
 if(kind==='contract'&&s.contract)q.error='Your device choice is already recorded.';
 if(kind==='arcade'&&s.used.arcade===s.month)q.error='This month’s arcade visit is already paid.';
 if(kind==='membership'&&s.used.membership===s.month)q.error='This month is already covered.';
 if(kind==='loan'&&(s.loan||![60000,120000].includes(arg.amount)))q.error='Use one of the supplied loan offers; only one can be active.';
 if(kind==='withdraw'&&(!Number.isSafeInteger(arg.amount)||arg.amount<=0||arg.amount>s.emergency))q.error='This exceeds your emergency savings.';
 if(['emergency','goal','invest','repay','arrears'].includes(kind)&&(!Number.isSafeInteger(arg.amount)||arg.amount<=0))q.error='Enter an amount greater than zero.';
 if(kind==='repay'&&arg.amount>s.card)q.error='The payment exceeds the card balance.';
 if(kind==='arrears'&&arg.amount>s.unpaid.reduce((n,b)=>n+b.amount,0))q.error='The payment exceeds overdue bills.';
 q.ok=!q.error;q.after=s.cash-q.cost+(['withdraw','loan'].includes(kind)?q.amount:0);const f=forecast(s);q.available=f.available+q.after-s.cash;if(['goal','emergency'].includes(kind))q.available+=Math.min(q.cost,(s.budgets[s.month]?.[kind]||0)-Math.min(s.budgets[s.month]?.[kind]||0,s.ledger.filter(t=>t.month===s.month).reduce((n,t)=>n+Math.max(0,t.delta[kind]||0),0)));if(kind==='food')q.available+=f.food;q.warning=q.available<0?'This leaves a gap before payday. You can revise your plan or use a reserve.':'';return q;
}
function apply(s,key,kind,arg={}){if(s.receipts[key])return{ok:false,error:'This action already settled.'};const q=quote(s,kind,arg);if(!q.ok)return q;const statsBefore={energy:s.energy,happiness:s.happiness,stress:s.stress},delta={cash:-q.cost};
 if(kind==='withdraw'){delta.cash=q.amount;delta.emergency=-q.amount;}
 if(kind==='emergency')delta.emergency=q.cost;if(kind==='goal')delta.goal=q.cost;if(kind==='invest')delta.investment=q.cost;if(kind==='repay')delta.card=-q.cost;
 if(kind==='loan')delta.cash=arg.amount;record(s,key,q.label,delta,q.category,{blocks:q.blocks});s.blocks-=q.blocks;
 if(kind==='food'){s.food={month:s.month,choices:q.choices,total:q.total,cost:q.cost,days:30};mark(s,'food');}
 if(kind==='membership')s.used.membership=s.month;if(kind==='arcade')s.used.arcade=s.month;if(kind==='scam')s.fraud={response:'paid',loss:7500};
 if(kind==='gym'){s.energy=Math.min(100,s.energy+10);s.stress=Math.max(0,s.stress-5);}
 if(kind==='meal'){s.energy=Math.min(100,s.energy+(arg.small?12:20));s.happiness=Math.min(100,s.happiness+8);s.stress=Math.max(0,s.stress-3);}
 if(['social','arcade'].includes(kind)){s.happiness=Math.min(100,s.happiness+8);s.energy=Math.max(0,s.energy-5);}
 if(kind==='rest'){s.energy=Math.min(100,s.energy+20);s.stress=Math.max(0,s.stress-10);}
 if(kind==='training'){s.trained=true;s.trainingMonth=s.month;}
 if(kind==='extra'){s.extraHours=8;s.energy=Math.max(0,s.energy-10);s.stress=Math.min(100,s.stress+3);}
 if(kind==='bike')s.transport='bike';if(kind==='contract')s.contract={kind:arg.choice,start:s.month,total:arg.choice==='term'?60000:arg.choice==='cash'?42000:0};
 if(kind==='loan')s.loan={principal:arg.amount,balance:arg.amount,apr:arg.variable?.12:.10,variable:!!arg.variable,payment:loanPayment(arg.amount,arg.variable?.12:.10,12),arrears:0,origin:s.month};
 if(kind==='repay')s.paidCard+=q.cost;
 if(kind==='arrears'){let rem=q.cost;for(const b of s.unpaid){const paid=Math.min(rem,b.amount);b.amount-=paid;rem-=paid;}s.unpaid=s.unpaid.filter(b=>b.amount>0);}
 s.ledger.at(-1).stats=Object.fromEntries(Object.keys(statsBefore).map(k=>[k,[statsBefore[k],s[k]]]));return{...q,ok:true};
}
function cardPurchase(s,key,amount,label){if(!Number.isSafeInteger(amount)||amount<=0||s.card+amount>200000||s.receipts[key])return false;record(s,key,label,{card:amount},'credit');return true;}
function bill(s,b){const key=`bill:${s.month}:${b.id}`;if(s.receipts[key])return;const carry=s.unpaid.filter(x=>x.bill===b.id&&!(x.arrangedUntil>s.month)).reduce((n,x)=>n+x.amount,0),due=b.amount+carry,paid=Math.min(s.cash,due);s.unpaid=s.unpaid.filter(x=>x.bill!==b.id||x.arrangedUntil>s.month);record(s,key,b.name,{cash:-paid},b.category,{due,paid,unpaid:due-paid});if(paid<due){const fee=b.id==='housing'?2500:1000;s.unpaid.push({bill:b.id,name:b.name,amount:due-paid+fee,fee,origin:s.month});s.stress=Math.min(100,s.stress+5);}}
function payday(s,day){const key=`pay:${s.month}:${day}`;if(s.receipts[key])return;const hours=payHours(s,day),p=payroll(round(hours*wage(s)));record(s,key,'Payday — '+hours+' hours',{cash:p.net},'income',p);for(const k of Object.keys(p))s.ytd[k]+=p[k];s.stubs.push({...p,id:key,month:s.month,day,hours,wage:wage(s),ytd:{...s.ytd}});}
function settleDebt(s){if(s.receipts[`debt:${s.month}`])return;const due=Math.max(0,minimum(s.statement)-s.paidCard),paid=Math.min(s.cash,due),missed=paid<due;record(s,`debt:${s.month}`,'Card minimum',{cash:-paid,card:-paid},'debt',{due,paid});s.paidCard+=paid;if(missed)record(s,`cardfee:${s.month}`,'Missed card minimum fee',{card:2500},'fee');
 if(s.loan){const L=s.loan;if(L.variable&&s.month>=4)L.apr=.15;const interest=round(L.balance*L.apr/12);L.balance+=interest;const dueL=Math.min(L.balance,L.payment+L.arrears),pay=Math.min(s.cash,dueL);record(s,`loan:${s.month}`,'Loan payment',{cash:-pay},'debt',{interest,due:dueL,paid:pay});L.balance-=pay;L.arrears=dueL-pay;if(pay<dueL){L.balance+=2500;L.arrears+=2500;s.ledger.push({id:`loanfee:${s.month}`,month:s.month,day:s.day,label:'Loan late fee',category:'fee',delta:{},before:{},fee:2500});}if(!L.balance)s.loan=null;}}
function endMonth(s){const key=`close:${s.month}`;if(s.receipts[key])return;const interest=round(s.card*.2099/12);record(s,key,'Card interest',{card:interest},'interest');const saving=round(s.emergency*.03/12);record(s,`savings:${s.month}`,'Emergency savings interest',{emergency:saving},'interest');if(s.investment){const fee=round(s.investment*.005/12);record(s,`fundfee:${s.month}`,'Investment management cost',{investment:-fee},'fee');const path=[-.04,.03,-.12,.06,.02,-.05],rate=path[(s.month-1)%path.length],change=round(s.investment*rate);record(s,`market:${s.month}`,'Investment market change',{investment:change},'market',{rate});s.investmentHistory.push({month:s.month,rate,value:s.investment});}if(s.food?.month!==s.month){s.energy=Math.max(0,s.energy-10);s.stress=Math.min(100,s.stress+5);}s.energy=Math.min(100,s.energy+15);}
function tasks(s){return [...chapters[Math.min(5,s.month-1)].tasks,...(s.month>1?[['budget','Revise and save this month’s plan','bank'],['food','Choose this month’s meal coverage','grocery']]:[])];}
function missing(s){return tasks(s).filter(([key])=>!marked(s,key));}
function advance(s){if(s.completed)return{ok:false,error:'The story is complete. Start Free Play for another campaign.'};if(s.day===30){if(s.mode==='story'&&missing(s).length)return{ok:false,error:'Finish the chapter decisions before the review.',missing:missing(s)};endMonth(s);if(s.mode==='story'&&s.month===6){s.completed=true;return{ok:true,complete:true};}s.month++;if((s.month-1)%12===0)s.ytd={gross:0,cpp:0,ei:0,tax:0,net:0};s.day=0;s.blocks=4;s.extraHours=0;s.statement=s.card;s.paidCard=0;s.casino=null;return{ok:true,newMonth:true};}
 const events=[...bills(s).filter(b=>b.day>s.day).map(b=>b.day),15,25,30].filter(d=>d>s.day);s.day=Math.min(...events);for(const b of bills(s).filter(b=>b.day===s.day))bill(s,b);if(s.day===15||s.day===30)payday(s,s.day);if(s.day===25)settleDebt(s);return{ok:true,day:s.day};}
function saveBudget(s,plan){const keys=['food','leisure','goal','emergency','debt'],clean={};for(const k of keys){const n=plan[k];if(!Number.isSafeInteger(n)||n<0||n>10000000)return false;clean[k]=n;}s.budgets[s.month]=clean;s.budgetDraft=null;mark(s,'budget');return true;}
function nextRandom(s){let x=s.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296;}
function casinoEnter(s,limit){if(!Number.isSafeInteger(limit)||limit<500)return{ok:false,error:'Use a whole-cent wager limit of at least $5.'};if(s.casino?.month===s.month&&s.casino.active)return{ok:true};if(s.blocks<1)return{ok:false,error:'A casino visit needs one discretionary time block.'};s.blocks--;s.casino={month:s.month,limit,wagered:0,plays:0,active:true,last:null};return{ok:true};}
function roulette(s,stake,kind){if(!['red','black','seven'].includes(kind))return{ok:false,error:'Choose a supplied bet.'};const c=s.casino;if(!c?.active||c.plays>=10||![500,2000,5000].includes(stake)||stake>s.cash)return{ok:false,error:'Check cash, session plays, and stake.'};if(c.wagered+stake>c.limit)return{ok:false,error:'Revise your limit before placing this wager.'};const number=Math.floor(nextRandom(s)*37),red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(number),win=kind==='seven'?number===7:kind==='red'?red:number!==0&&!red,payout=win?stake*(kind==='seven'?36:2):0;c.plays++;c.wagered+=stake;s.casinoWagers+=stake;s.casinoNet+=payout-stake;c.last={number,kind,stake,payout,net:payout-stake,id:`casino:${s.month}:${s.ledger.length}`};record(s,c.last.id,'Roulette '+kind,{cash:payout-stake},'gambling',{stake,payout,number});return{ok:true,...c.last};}
function slots(s,stake){const c=s.casino;if(!c?.active||c.plays>=10||![500,1000,2500].includes(stake)||stake>s.cash)return{ok:false,error:'Check cash, session plays, and stake.'};if(c.wagered+stake>c.limit)return{ok:false,error:'Revise your limit before placing this wager.'};const bag=['cherries','cherries','cherries','cherries','lemon','lemon','lemon','bell','bell','star','star','gem','seven'],reels=Array.from({length:3},()=>bag[Math.floor(nextRandom(s)*13)]),same=new Set(reels).size===1,pair=new Set(reels).size===2,payout=same?(reels[0]==='seven'?stake*100:stake*10):pair?round(stake*.6):0;c.plays++;c.wagered+=stake;s.casinoWagers+=stake;s.casinoNet+=payout-stake;c.last={kind:'slots',reels,stake,payout,net:payout-stake,id:`casino:${s.month}:${s.ledger.length}`};record(s,c.last.id,'Slots',{cash:payout-stake},'gambling',{stake,payout,reels});return{ok:true,...c.last};}
function future(principal,monthly,years,annual=.05,inflation=.02,fee=.005){const rate=Math.pow(1+annual-fee,1/12)-1,n=years*12,value=round(principal*Math.pow(1+rate,n)+monthly*(rate?(Math.pow(1+rate,n)-1)/rate:n));return{value,contributed:principal+monthly*n,real:round(value/Math.pow(1+inflation,years)),years};}
return{VERSION,profiles,foodGroups,chapters,tasks,money,initial,valid,record,marked,mark,reason,monthlyHours,payroll,wage,payHours,projectedPay,monthNet,bills,foodQuote,loanPayment,schedule,minimum,forecast,quote,apply,cardPurchase,bill,payday,settleDebt,endMonth,missing,advance,saveBudget,nextRandom,casinoEnter,roulette,slots,future};
});
