/* Illustrated town, shared art, exclusive scene input, fixed 60 Hz movement. */
window.PPSimWorld=(()=>{
 const ids=['home','office','grocery','bank','school','gym','diner','mall','dealer','lucky'],names=['Home','Workplace','FreshMart','Bank','Learning centre','Gym','Diner','Mall & arcade','Transport','Lucky’s'];
 const buildings=ids.map((id,i)=>({id,name:names[i],x:240+i%5*425,y:i<5?360:900,index:i,w:320,h:i===1?335:280})),bounds={x:0,y:0,w:2200,h:1280},roomBounds={x:45,y:270,w:810,h:330};
 const trees=[{x:75,y:625},{x:570,y:680},{x:990,y:680},{x:1420,y:660},{x:2050,y:650},{x:1520,y:1190},{x:1790,y:1190},{x:90,y:1145}],townSolids=buildings.map(b=>({x:b.x-142,y:b.y-81,w:284,h:81})).concat(trees.map(t=>({x:t.x-13,y:t.y-14,w:26,h:22})),[{x:340,y:1090,w:730,h:110}]);
 const prop=(kind,x,y,w,h,depth=35)=>({kind,x,y,w,h,solid:{x:x-w*.43,y:y-depth,w:w*.86,h:depth}});
 const rooms={home:[prop('bed',200,355,185,166,65),prop('sofa',685,350,210,132,52),prop('desk',260,520,155,132),prop('plant',778,535,85,110,24)],grocery:[prop('shelf',240,320,180,154,42),prop('shelf',640,320,180,154,42),prop('produce',240,478,170,110,48),prop('produce',640,478,170,110,48),prop('checkout',450,275,190,104,45)],office:[prop('desk',235,330,200,130,50),prop('desk',645,330,200,130,50),prop('chair',242,393,70,82),prop('bookcase',755,520,120,160)],bank:[prop('teller',450,305,420,145,58),prop('plant',150,455,95,125),prop('sofa',740,478,175,115)],school:[prop('study',220,350,190,120,50),prop('study',655,350,190,120,50),prop('study',220,510,190,120,50),prop('bookcase',680,505,160,190)],gym:[prop('weights',230,350,220,137,58),prop('weights',650,350,220,137,58),prop('plant',725,535,90,118)],diner:[prop('booth',190,338,205,147,60),prop('booth',697,338,205,147,60),prop('table',220,507,165,130,55),prop('table',660,507,165,130,55)],mall:[prop('arcade',200,352,130,183,40),prop('arcade',450,352,130,183,40),prop('arcade',695,352,130,183,40),prop('plant',160,540,90,118)],dealer:[prop('desk',245,340,220,150,60),prop('sofa',660,360,220,135,50),prop('plant',740,535,90,118)],lucky:[prop('arcade',220,340,140,180,40),prop('arcade',450,340,140,180,40),prop('arcade',675,340,140,180,40),prop('booth',720,530,190,120,40)]};
 const cv=document.getElementById('game'),ctx=cv.getContext('2d'),keys={},cam={x:0,y:0},actor={x:240,y:424,r:12,dir:'s',walk:0,moving:false},inside={x:450,y:555,r:12,dir:'n',walk:0,moving:false};
 const S={room:null,paused:false,reduced:false,debug:false,route:[],zoom:1,npcs:[],state:null,game:null,joy:{x:0,y:0},last:0,acc:0,time:0};window.PPScene=S;
 const active=()=>S.room?inside:actor,solids=()=>S.room?rooms[S.room].map(p=>p.solid):townSolids,limit=()=>S.room?roomBounds:bounds,busy=()=>!S.state||S.paused||S.game?.busy();
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 function clear(){for(const k in keys)delete keys[k];S.joy={x:0,y:0};S.route=[];actor.moving=inside.moving=false;const knob=document.getElementById('knob');if(knob)knob.style.transform='';}
 function camera(){S.zoom=cv.width<650?.82:1.05;cam.x=clamp(actor.x-cv.width/S.zoom/2,0,Math.max(0,bounds.w-cv.width/S.zoom));cam.y=clamp(actor.y-cv.height/S.zoom*.53,0,Math.max(0,bounds.h-cv.height/S.zoom));}
 function interiorRect(){const top=document.getElementById('hud').offsetHeight+18,bottom=cv.width<650?150:64,available=Math.max(200,cv.height-top-bottom),phone=cv.width<650,s=phone?Math.max(cv.width/900,available/620):Math.min(cv.width/900,available/620),w=900*s,h=620*s;return{x:phone?clamp(cv.width/2-inside.x*s,Math.min(0,cv.width-w),0):(cv.width-w)/2,y:top+(available-h)/2,w,h,top,bottom:cv.height-bottom};}
 function targets(){return S.room?[{id:S.room,x:450,y:405,range:78,name:'Choices & conversation'},{id:'examine',x:820,y:280,range:70,name:'Look around'},{id:'leave',x:450,y:580,range:48,name:'Leave'}]:buildings.map(b=>({...b,y:b.y+24,range:68}));}
 function nearest(){return PPWorld.nearestInteraction(active(),targets(),solids());}
 function remember(){if(!S.state)return;const a=active();S.state.position={room:S.room,x:a.x,y:a.y,dir:a.dir,returnX:actor.x,returnY:actor.y};}
 function enter(id){const b=buildings.find(b=>b.id===id);if(!b)return;clear();S.room=id;inside.x=450;inside.y=555;inside.dir='n';remember();S.game?.save();S.game?.visit(id);}
 function leave(){clear();S.room=null;actor.y+=24;Object.assign(actor,PPWorld.moveCircle(actor,{x:0,y:0},townSolids,bounds));actor.dir='s';camera();remember();S.game?.save();}
 function interact(){if(busy())return;const t=nearest();if(!t)return;clear();if(!S.room)enter(t.id);else if(t.id==='leave')leave();else S.game?.location(S.room,t.id==='examine');}
 function navigate(id){const b=buildings.find(b=>b.id===id);if(!b)return;if(S.room)leave();walkTo(b.x,b.y+24);}
 function walkTo(x,y){clear();S.route=PPWorld.pathfind(active(),{x,y},solids(),limit(),24,12);if(!S.route.length)S.game?.toast('Choose a clear spot on the floor.');}
 function step(dt){if(busy()){actor.moving=inside.moving=false;return;}S.time+=dt;const a=active(),start={x:a.x,y:a.y};let v=PPWorld.normalizeInput((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+S.joy.x,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+S.joy.y);
 if(v.x||v.y)S.route=[];else if(S.route.length){const d=S.route[0],dx=d.x-a.x,dy=d.y-a.y,m=Math.hypot(dx,dy);if(m<5)S.route.shift();else v={x:dx/m,y:dy/m};}
 a.dir=PPWorld.direction(v.x,v.y,a.dir);a.moving=!!(v.x||v.y);Object.assign(a,PPWorld.moveCircle(a,{x:v.x*195*dt,y:v.y*195*dt},solids(),limit()));a.walk+=dt*(a.moving?10.2:.9);
 if(Math.hypot(a.x-start.x,a.y-start.y)>.01)S.game?.moved();
 if(!S.room){for(const n of S.npcs){if(!n.route.length)n.route=PPWorld.pathfind(n,n.toB?n.b:n.a,townSolids,bounds,32,12);const t=n.route[0];if(t){const dx=t.x-n.x,dy=t.y-n.y,d=Math.hypot(dx,dy);if(d<5){n.route.shift();if(!n.route.length)n.toB=!n.toB;}else{n.dir=PPWorld.direction(dx,dy,n.dir);Object.assign(n,PPWorld.moveCircle(n,{x:dx/d*65*dt,y:dy/d*65*dt},townSolids,bounds));n.walk+=dt*7;}}Object.assign(n,PPWorld.separate(n,[actor,...S.npcs.filter(x=>x!==n)],townSolids,bounds,.12));}camera();}remember();
 const n=nearest(),action=document.getElementById('btnAct');action.disabled=!n;action.textContent=n?(S.room?n.name:'Enter '+n.name)+' · E':'E';document.getElementById('prompt').textContent=S.room?buildings.find(b=>b.id===S.room).name:'';
 }
 function ground(){ctx.fillStyle='#91b97b';ctx.fillRect(0,0,2200,1280);if(PPArt.ready.ground)for(let y=0;y<1280;y+=640)for(let x=0;x<2200;x+=960)ctx.drawImage(PPArt.images.ground,x,y,960,640);ctx.fillStyle='#e4d6b9';for(const y of [390,930])ctx.fillRect(0,y,2200,125);for(const x of [20,410,835,1260,1685,2130])ctx.fillRect(x,275,62,800);ctx.fillStyle='#74817a';for(const y of [467,1007])ctx.fillRect(0,y,2200,57);ctx.strokeStyle='#eedfbb';ctx.lineWidth=3;ctx.setLineDash([25,25]);for(const y of [495,1035]){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(2200,y);ctx.stroke();}ctx.setLineDash([]);ctx.fillStyle='#6398a3';ctx.fillRect(340,1090,730,110);}
 function render(){ctx.clearRect(0,0,cv.width,cv.height);const near=nearest();if(S.room){ctx.fillStyle='#213e30';ctx.fillRect(0,0,cv.width,cv.height);const r=interiorRect();ctx.save();ctx.beginPath();ctx.rect(0,r.top,cv.width,r.bottom-r.top);ctx.clip();ctx.translate(r.x,r.y);ctx.scale(r.w/900,r.h/620);PPArt.sprite(ctx,PPAssets.sheets.roomsA.names.includes(S.room)?'roomsA':'roomsB',S.room,450,620,900,620);const objects=rooms[S.room].map(p=>({y:p.y,draw:()=>PPArt.sprite(ctx,'furniture',p.kind,p.x,p.y,p.w,p.h)}));objects.push({y:inside.y,draw:()=>PPArt.person(ctx,S.state?.char||'alex',inside.x,inside.y,inside.dir,inside.walk,inside.moving?'walk':'idle',140)});objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());for(const t of targets()){ctx.strokeStyle='#bb9b48';ctx.beginPath();ctx.ellipse(t.x,t.y,16,6,0,0,Math.PI*2);ctx.stroke();if(near?.id===t.id)PPArt.label(ctx,t.name,t.x,t.y-12,true);}debug(solids(),[inside]);ctx.restore();}else{ctx.save();ctx.scale(S.zoom,S.zoom);ctx.translate(-cam.x,-cam.y);ground();const objects=buildings.map(b=>({y:b.y,draw:()=>{PPArt.sprite(ctx,'town',b.index,b.x,b.y,b.w,b.h);PPArt.label(ctx,b.name,b.x,b.y+45,near?.id===b.id);}}));for(const t of trees)objects.push({y:t.y,draw:()=>PPArt.sprite(ctx,'town','tree',t.x,t.y,170,200)});for(const n of S.npcs)objects.push({y:n.y,draw:()=>PPArt.person(ctx,n.char,n.x,n.y,n.dir,n.walk,'walk',84)});objects.push({y:actor.y,draw:()=>PPArt.person(ctx,S.state?.char||'alex',actor.x,actor.y,actor.dir,actor.walk,actor.moving?'walk':'idle',88)});objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());debug(townSolids,[actor,...S.npcs]);ctx.restore();}
 const hide=busy();document.getElementById('joy').hidden=hide;document.getElementById('btnAct').hidden=hide;}
 function debug(rects,people){if(!S.debug)return;ctx.strokeStyle='#e62a5b';ctx.lineWidth=2;rects.forEach(r=>ctx.strokeRect(r.x,r.y,r.w,r.h));ctx.strokeStyle='#37dee4';for(const a of people){ctx.beginPath();ctx.arc(a.x,a.y,12,0,Math.PI*2);ctx.stroke();if(a.route?.length){ctx.beginPath();ctx.moveTo(a.x,a.y);a.route.forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();}}ctx.strokeStyle='#eda82f';targets().forEach(t=>{ctx.beginPath();ctx.arc(t.x,t.y,t.range,0,Math.PI*2);ctx.stroke();});}
 function frame(ts){const dt=Math.min(.1,(ts-(S.last||ts))/1000);S.last=ts;S.acc+=dt;let i=0;while(S.acc>=1/60&&i++<6){step(1/60);S.acc-=1/60;}if(S.state&&!S.paused&&!document.hidden&&S.game?.playing())S.state.playedSeconds+=dt;S.reduced=!!S.state?.settings.reduced;render();requestAnimationFrame(frame);}
 function resize(){cv.width=innerWidth;cv.height=innerHeight;camera();}addEventListener('resize',resize);resize();requestAnimationFrame(frame);
 addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.target.matches('input,textarea,select'))return;if(k==='f2'){S.debug=!S.debug;e.preventDefault();return;}if(k==='escape'){S.game?.escape();return;}if(busy())return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys[k]=true;if(k==='e'&&!e.repeat)interact();});addEventListener('keyup',e=>delete keys[e.key.toLowerCase()]);
 cv.addEventListener('pointerdown',e=>{if(busy())return;const r=interiorRect();walkTo(S.room?(e.clientX-r.x)*900/r.w:e.clientX/S.zoom+cam.x,S.room?(e.clientY-r.y)*620/r.h:e.clientY/S.zoom+cam.y);});
 const stick=document.getElementById('joy');function stickPoint(e){const r=stick.getBoundingClientRect();S.joy=PPWorld.normalizeInput((e.clientX-r.left-r.width/2)/(r.width*.36),(e.clientY-r.top-r.height/2)/(r.height*.36));document.getElementById('knob').style.transform=`translate(${S.joy.x*34}px,${S.joy.y*34}px)`;}
 stick.onpointerdown=e=>{if(busy())return;e.preventDefault();clear();stick.setPointerCapture(e.pointerId);stickPoint(e);};stick.onpointermove=e=>{if(e.buttons)stickPoint(e);};stick.onpointerup=stick.onpointercancel=clear;document.getElementById('btnAct').onclick=interact;
 addEventListener('blur',()=>{clear();S.game?.autoPause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();S.game?.autoPause();}});addEventListener('pointercancel',clear);
 function start(state,game){clear();S.state=state;S.game=game;S.paused=false;const p=state.position;S.room=p.room;Object.assign(S.room?inside:actor,{x:p.x,y:p.y,dir:p.dir});if(S.room){actor.x=p.returnX||240;actor.y=p.returnY||424;}S.npcs=[['maya',470,430,1320,990],['jay',1090,430,1720,990],['sam',180,990,2010,990]].map(([char,x,y,bx,by])=>({char,x,y,r:12,a:{x,y},b:{x:bx,y:by},dir:'s',walk:0,toB:true,route:[]}));camera();}
 return Object.assign(S,{start,clear,interact,navigate,enter,leave,nearest,remember,buildings,rooms,solids,targets,bounds,roomBounds,step});
})();
