// Historical one-time instructional edit. Canonical HTML remains the owner.
const fs=require('fs'),path=require('path'),c=require('cheerio');const dir=__dirname,p=path.resolve(dir,'../../../workspace/index.html');let source=fs.readFileSync(p,'utf8');if(source.includes('ce1-01-worked-purpose'))throw Error('Already applied; do not regenerate');const $=c.load(source,{sourceCodeLocationInfo:true}),edits=[];
const change=(id,fn)=>{const node=$('#'+id)[0],loc=node.sourceCodeLocation,d=c.load(source.slice(loc.startOffset,loc.endOffset),null,false);fn(d,d('section').first());edits.push({a:loc.startOffset,b:loc.endOffset,t:d.html()});};
change('ce1-01-stage-4',(d,s)=>{
 s.children('.section-label').text('Read a worked example');s.children('h3').text('See how Jordan’s poster note becomes an evidence card');
 s.children('h3').after(`<div class="student-guide" data-canvas-helper-edit-key="ce1-01-worked-purpose"><p><strong>What you will do here:</strong> Read an answer that has already been completed, then follow the steps that explain how it was built. This is a <strong>worked example</strong>: it shows how to use the evidence before you try the method yourself.</p><p>An <strong>evidence card</strong> is a short written response that connects an action and its result to a possible skill, explains what the evidence cannot establish, and identifies a useful question about work. You will write your own response in the lesson’s fields.</p><p>For this example, use the <strong>school-event poster</strong> row in <a href="#ce1-01-stage-2">Jordan’s experience notebook</a>. Read the four steps below, then find those parts in the completed paragraph.</p></div>`);
 const first=s.children('p').filter((_,e)=>d(e).text().startsWith('First I identify'));
 first.replaceWith(`<ol class="student-guide" data-canvas-helper-edit-key="ce1-01-worked-steps"><li><strong>Start with the recorded action and result.</strong> Two classmates could not find the time and location. Jordan moved those details into a larger heading, reduced decoration and asked for another check. Both classmates then found the details without help. This gives us something observable to use.</li><li><strong>Explain the possible skill.</strong> These actions suggest some skill in organizing visual information and responding to feedback. The claim explains what the action shows; it does more than call Jordan “brilliant.”</li><li><strong>Keep the claim within the evidence.</strong> The notebook describes one school task. It does not show that Jordan can manage a professional client’s project, use professional software or meet every workplace deadline. A useful skill claim can still have a limit.</li><li><strong>Connect a question to Jordan’s goals.</strong> Jordan wants visual problem solving and clear explanations, with regular time outside work. Asking about revisions and unpredictable deadlines could help Jordan test whether a possible role fits both goals.</li></ol>`);
 s.children('p').filter((_,e)=>d(e).text().startsWith('The skill claim should')).remove();
 s.children('p').filter((_,e)=>d(e).text()==='Completed poster card').html('<strong>The completed evidence card</strong>');
 s.children('p').filter((_,e)=>d(e).text().startsWith('Notice that the card')).html('<strong>Check the example before moving on:</strong> Find the action and result, the possible skill, the limit and the question in the paragraph above. The question keeps a career possibility open for investigation; it does not promise that an occupation will fit Jordan.');
 s.children('p').filter((_,e)=>d(e).text().startsWith('Now you will use')).text('Next, you will practise these same steps using Jordan’s science-display experience. You will choose a claim, write three short notes and compare them with a model.');
 s.find('.learning-next a').text('Try the science-display example with guidance');
});
change('ce1-01-stage-5',(d,s)=>{
 s.children('.section-label').text('Try it with guidance');s.children('h3').text('Build Jordan’s science-display response');
 s.children('h3').after(`<div class="student-guide" data-canvas-helper-edit-key="ce1-01-guided-purpose"><p><strong>Your turn, with help:</strong> Use the same four steps you just saw, with a different experience from Jordan’s notebook. The notes below supply the facts, the choice check gives feedback, and the comparison model helps you review your writing.</p><p>Your practice response is three short notes in the fields below. It prepares you for Amina’s task later in this lesson.</p></div>`);
 s.children('p').filter((_,e)=>d(e).text().startsWith('The person and their')).html('<strong>The facts to use:</strong> In a three-person science display, Jordan asked what each person could finish, made a shared checklist and arranged Wednesday’s check-in. The group noticed a missing caption on Wednesday, finished it Thursday and had all three parts ready Friday. Jordan found repeated follow-up tiring. Jordan’s goals and preference for a reasonably predictable schedule remain the same.');
 s.children('p').filter((_,e)=>d(e).text().startsWith('First select the claim')).replaceWith(`<ol class="student-guide" data-canvas-helper-edit-key="ce1-01-guided-steps"><li><strong>Choose a claim you can defend.</strong> In <a href="#field-guided-ce1-01-match">Choose a supported claim</a>, pick the statement that fits the science-display notes. Use <strong>Check my choice</strong>, read the feedback and revise if needed.</li><li><strong>Describe what happened.</strong> In <a href="#field-guided-ce1-01-part1">Action and result</a>, name what Jordan did and what the group achieved. Keep Jordan’s contribution separate from the group’s result.</li><li><strong>Explain what that evidence shows.</strong> In <a href="#field-guided-ce1-01-part2">Skill and limit</a>, name a possible skill and one thing this small-group experience does not prove. You can begin, “This suggests… It does not yet show…”</li><li><strong>Ask a question that could help Jordan choose.</strong> In <a href="#field-guided-ce1-01-part3">Next question linked to a value</a>, ask about an actual task or working condition. Explain why the answer would matter to Jordan’s goals or reaction to follow-up.</li></ol>`);
 s.children('p').filter((_,e)=>d(e).text().startsWith('Write short notes')).html('<strong>Then compare and revise:</strong> Open <strong>Compare your response with a model</strong> to see your notes beside an example. Compare the evidence and reasoning, rather than looking for identical wording. Use <strong>Return to my response</strong> to improve the same fields. You can open the model earlier if you need help getting started.');
});
change('ce1-01-stage-7',(d,s)=>{
 s.children('.section-label').text('Write your response for a new situation');const title=s.children('h3').first(),intro=s.children('p').filter((_,e)=>d(e).text().startsWith('Amina is considering'));title.remove();intro.remove();
 s.children('.section-label').after(`<h3>Amina’s strengths-and-goals response</h3><div class="student-guide" data-canvas-helper-edit-key="ce1-01-independent-purpose"><p><strong>What you will produce:</strong> One strengths-and-goals card, written across the three fields below. Here, a “card” means a short written response that connects experiences, possible skills, goals and questions about work.</p><p><strong>Meet the new person:</strong> Amina is considering practical problem-solving work. Her two experiences, goal note and possible work directions are supplied below. Use the method you practised with Jordan, with Amina’s own evidence.</p><p><strong>Start by reading:</strong> Read both rows of Amina’s experience notes, then her goal note and the two role sketches. You have the information needed for this task here in the lesson. A role sketch is a brief description of work to investigate; it does not establish actual hours or entry requirements.</p></div>`);
 s.children('p').filter((_,e)=>d(e).text().startsWith('Create one strengths')).html('<strong>Write your response in three parts.</strong> Use approximately 160–240 words across the fields; useful detail matters more than the count. Follow the steps below, using the field with the matching label.');
 const list=s.children('ul').first();list.replaceWith(`<ol class="student-guide" data-canvas-helper-edit-key="ce1-01-independent-steps"><li><strong><a href="#field-ce1-01">Two examples and what they suggest</a>:</strong> Use both the bicycle workshop and the board game. For each, describe Amina’s action, the result and a skill it could support. Identify a growth area: something Amina still needs to develop. Keep help received and limits of the evidence visible.</li><li><strong><a href="#field-evidence-ce1-01-directions">Goals, values and two directions</a>:</strong> Use Amina’s goal note to state her career direction and what she wants work to support in her life. Explain how each role sketch might connect to her experiences. Separate demonstrated skills from preferences such as movement or finishing at a predictable time.</li><li><strong><a href="#field-evidence-ce1-01-questions">A question that could change each direction</a>:</strong> Write one specific question about repair-shop assistance and one about recreation activity assistance. For each question, explain how its answer could make that direction a better or poorer fit for Amina.</li></ol>`);
 s.children('p').filter((_,e)=>d(e).text().startsWith('Use Compare')).html('<strong>Review your own reasoning:</strong> Try the three parts, then use <strong>Compare your response with a model</strong> to check how the example uses Amina’s evidence. You may open it whenever you need support. Different wording and different priorities can be reasonable; your claims must come from the supplied notes. Revise your fields, then use <a href="#ce1-01-stage-8">Review and complete</a> to check the four statements and finish the lesson.');
 s.find('.learning-first-copy > p').text('Before revising, use “Keep my first attempt and review” to keep a comparison copy of your current three entries. Opening the comparison model also keeps that first copy. Your current response stays editable.');
});
const roadmap=$('#ce1-01 > details.lesson-roadmap')[0],loc=roadmap.sourceCodeLocation,d=c.load(source.slice(loc.startOffset,loc.endOffset),null,false);for(const [n,text] of [[4,'Read Jordan’s completed poster example and follow the reasoning'],[5,'Try the science-display response, check your choice and compare your notes'],[7,'Read Amina’s records and write your own three-part response']])d(`[href="#ce1-01-stage-${n}"]`).text(text);edits.push({a:loc.startOffset,b:loc.endOffset,t:d.html()});
for(const edit of edits.sort((a,b)=>b.a-a.a))source=source.slice(0,edit.a)+edit.t+source.slice(edit.b);fs.writeFileSync(p,source);console.log('Updated CE1-01 stages 4, 5, 7 and matching roadmap only.');
