/* Canonical calculation families. Constants are explicit within each question. */
(function(root){'use strict';const P=root.ChemistryPractice=root.ChemistryPractice||{};P.templates=[];const builders={};
const fmt=n=>Number(n.toPrecision(7)).toString();
function add(id,lesson,skill,title,build){const chapter=lesson.startsWith('c9-')?9:lesson.startsWith('c11-')?11:10;P.templates.push({id:'calc-'+id,lesson,chapter,skill,family:skill,type:'numeric',kind:'calculations',title,sourceRefs:['guided:'+lesson]});builders['calc-'+id]=build;}
P.calculate=(template,seed,existing)=>{const random=P.random(seed),pick=(lo,hi,step=1)=>lo+Math.floor(random()*((hi-lo)/step+1))*step;const params=existing?{...existing}:{};const v=(key,lo,hi,step=1)=>params[key]??(params[key]=pick(lo,hi,step));const choose=(key,values)=>params[key]??(params[key]=values[Math.floor(random()*values.length)]);const result=builders[template.id](v,choose);if(!Number.isFinite(result.answer)||!result.prompt||!result.steps?.length)throw Error('Invalid generated calculation '+template.id);return {...template,...result,params,cue:result.cue||'Write the relationship first. Check the sign, the reaction basis and the units before substituting.',tolerance:result.tolerance??Math.max(Math.abs(result.answer)*0.005,0.005)};};
function water(v,sign=1){return {m:v('m',50,350,25),ti:v('ti',15,35),dt:sign*v('dt',3,15),c:4.19};}
function profile(v){const r=v('r',10,70,10),change=v('change',-50,60,10),p=r+change,peak=Math.max(r,p)+v('barrier',30,90,10);return {r,p,peak,change};}
add('water-warming','c9-heat','c9-heat-equation','Heat absorbed by water',v=>{const x=water(v);return {prompt:`${x.m} g of water warms from ${x.ti} °C to ${x.ti+x.dt} °C. Use c = 4.19 J/(g·°C). Calculate the heat absorbed by the water.`,answer:x.m*x.c*x.dt,unit:'J',steps:[`ΔT = ${x.ti+x.dt} − ${x.ti} = ${x.dt} °C.`,`q = mcΔT = (${x.m})(${x.c})(${x.dt}) = ${fmt(x.m*x.c*x.dt)} J.`,`The positive sign means energy entered the water.`]};});
add('water-cooling','c9-heat','c9-heat-sign','Signed heat during cooling',v=>{const x=water(v,-1);return {prompt:`${x.m} g of water cools from ${x.ti} °C to ${x.ti+x.dt} °C. Use c = 4.19 J/(g·°C). Calculate signed q for the water.`,answer:x.m*x.c*x.dt,unit:'J',steps:[`ΔT = ${x.dt} °C.`,`q = (${x.m})(4.19)(${x.dt}) = ${fmt(x.m*x.c*x.dt)} J.`,`Negative q means the water lost energy; do not report the positive released-energy magnitude here.`]};});
add('water-mass','c9-heat','c9-heat-equation','Mass from heat transfer',v=>{const x=water(v),q=x.m*x.c*x.dt;return {prompt:`Water absorbs ${fmt(q)} J while warming by ${x.dt} °C. Use c = 4.19 J/(g·°C). Find its mass.`,answer:x.m,unit:'g',steps:[`q = mcΔT, so m = q/(cΔT).`,`m = ${fmt(q)}/(4.19 × ${x.dt}) = ${x.m} g.`]};});
add('final-temperature','c9-heat','c9-temperature-change','Final temperature',v=>{const x=water(v),q=x.m*x.c*x.dt;return {prompt:`${x.m} g of water starts at ${x.ti} °C and absorbs ${fmt(q)} J. Use c = 4.19 J/(g·°C). Find its final temperature.`,answer:x.ti+x.dt,unit:'°C',steps:[`ΔT = q/(mc) = ${x.dt} °C.`,`Tfinal = Tinitial + ΔT = ${x.ti} + ${x.dt} = ${x.ti+x.dt} °C.`]};});
add('initial-temperature','c9-heat','c9-temperature-change','Initial temperature',v=>{const x=water(v),q=x.m*x.c*x.dt;return {prompt:`${x.m} g of water absorbs ${fmt(q)} J and finishes at ${x.ti+x.dt} °C. Use c = 4.19 J/(g·°C). Find its initial temperature.`,answer:x.ti,unit:'°C',steps:[`ΔT = q/(mc) = ${x.dt} °C.`,`Tinitial = Tfinal − ΔT = ${x.ti+x.dt} − ${x.dt} = ${x.ti} °C.`]};});
add('specific-heat','c9-heat','c9-specific-heat','Specific heat capacity',v=>{const m=v('m',50,200,25),dt=v('dt',5,15),c=v('c',0.5,2.5,0.1),q=m*dt*c;return {prompt:`A ${m} g sample absorbs ${fmt(q)} J while warming by ${dt} °C, with no phase change. Find its specific heat capacity.`,answer:c,unit:'J/(g·°C)',steps:[`c = q/(mΔT).`,`c = ${fmt(q)}/(${m} × ${dt}) = ${fmt(c)} J/(g·°C).`]};});
add('calorimeter-heat','c9-bomb','c9-apparatus-capacity','Whole-apparatus heat',v=>{const c=v('c',5,15,0.5),dt=v('dt',1,5,0.5);return {prompt:`A calibrated calorimeter has whole-apparatus heat capacity C = ${c} kJ/°C and warms by ${dt} °C. Calculate the heat gained by the calorimeter.`,answer:c*dt,unit:'kJ',steps:[`q = CΔT, because C already describes the entire apparatus.`,`q = ${c} × ${dt} = ${fmt(c*dt)} kJ. Do not multiply by mass again.`]};});
add('calorimeter-capacity','c9-bomb','c9-apparatus-capacity','Calibrate heat capacity',v=>{const c=v('c',5,15,0.5),dt=v('dt',1,5,0.5);return {prompt:`A calibration transfers ${fmt(c*dt)} kJ to an apparatus and raises its temperature by ${dt} °C. Find its whole-apparatus heat capacity C.`,answer:c,unit:'kJ/°C',steps:[`C = q/ΔT.`,`C = ${fmt(c*dt)}/${dt} = ${c} kJ/°C.`]};});
add('reaction-molar-heat','c9-solution','c9-molar-calorimetry','Molar reaction enthalpy',v=>{const n=v('n',0.02,0.1,0.01),heat=v('heat',0.8,3.2,0.2);return {prompt:`A reaction involving ${fmt(n)} mol of the specified reactant transfers ${fmt(heat)} kJ to the solution. Assume the solution captures all the reaction heat. Find ΔHm per mole of that reactant.`,answer:-heat/n,unit:'kJ/mol',steps:[`qreaction = −qsolution = −${fmt(heat)} kJ.`,`ΔHm = qreaction/n = −${fmt(heat)}/${fmt(n)} = ${fmt(-heat/n)} kJ/mol.`,`The negative sign belongs to the reaction that released energy.`]};});
add('moles-from-mass','c9-molar','c9-mole-mass','Mass to amount',v=>{const m=v('m',2,12,0.5);return {prompt:`A carbon dioxide sample has mass ${m} g. Use M(CO₂) = 44.01 g/mol. Find its amount in moles.`,answer:m/44.01,unit:'mol',steps:[`n = m/M.`,`n = ${m}/44.01 = ${fmt(m/44.01)} mol.`]};});
add('energy-from-moles','c9-molar','c9-molar-energy','Amount to reaction energy',v=>{const n=v('n',0.1,0.9,0.1);return {prompt:`Methane combustion has ΔHm = −890.5 kJ/mol CH₄ when water is liquid. Find signed ΔH when ${fmt(n)} mol CH₄ reacts completely.`,answer:-890.5*n,unit:'kJ',steps:[`ΔH = nΔHm.`,`ΔH = ${fmt(n)} × (−890.5) = ${fmt(-890.5*n)} kJ.`]};});
add('fuel-mass','c9-molar','c9-reaction-basis','Fuel mass from released energy',v=>{const e=v('e',100,600,25);return {prompt:`Propane combustion releases 2035 kJ per mole of propane under the stated model. Use M(C₃H₈) = 44.10 g/mol. Find the propane mass needed to release ${e} kJ.`,answer:e/2035*44.10,unit:'g',steps:[`Use the positive released-energy magnitude: n = ${e}/2035 mol.`,`m = nM = (${e}/2035)(44.10) = ${fmt(e/2035*44.10)} g.`]};});
add('reverse-scale','hess','c10-hess-transform','Reverse and scale enthalpy',v=>{const k=v('k',1,4);return {prompt:`N₂(g) + 3H₂(g) → 2NH₃(g) has ΔH = −92.2 kJ. Reverse this equation, then multiply every coefficient by ${k}. Find the new ΔH.`,answer:92.2*k,unit:'kJ',steps:[`Reversing changes −92.2 kJ to +92.2 kJ.`,`Multiplying coefficients by ${k} multiplies ΔH by ${k}: +${fmt(92.2*k)} kJ.`]};});
add('hess-combination','hess','c10-hess-cancel','Combine two reactions',v=>{const k=v('k',1,4);return {prompt:`2C(s) + O₂(g) → 2CO(g), ΔH = −221.0 kJ. 2CO(g) + O₂(g) → 2CO₂(g), ΔH = −566.0 kJ. Find ΔH for ${2*k}C(s) + ${2*k}O₂(g) → ${2*k}CO₂(g).`,answer:-787*k,unit:'kJ',steps:[`Add the two equations; 2CO(g) cancels.`,`For 2C + 2O₂ → 2CO₂, ΔH = −221.0 −566.0 = −787.0 kJ.`,`Scale by ${k}: ΔH = ${-787*k} kJ.`]};});
add('formation-total','formation-data','c10-formation-sum','Products minus reactants',v=>{const k=v('k',1,3);return {prompt:`For CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l), use ΔHf° values CH₄ −74.6, O₂ 0, CO₂ −393.5 and H₂O(l) −285.8 kJ/mol. Find signed energy change when ${k} mol CH₄ reacts.`,answer:-890.5*k,unit:'kJ',steps:[`ΔH° = [−393.5 + 2(−285.8)] − [−74.6 + 2(0)] = −890.5 kJ for 1 mol CH₄.`,`For ${k} mol: ΔH = ${fmt(-890.5*k)} kJ.`]};});
add('unknown-formation','formation-data','c10-unknown-formation','Find a formation value',(v,choose)=>{const which=choose('compound',['CO','CH4']),co=which==='CO',total=co?-283:-890.5,products=co?-393.5:-965.1,answer=co?-110.5:-74.6;return {prompt:co?'CO(g) + ½O₂(g) → CO₂(g) has ΔH° = −283.0 kJ. Use ΔHf°(CO₂) = −393.5 and ΔHf°(O₂) = 0 kJ/mol. Find ΔHf°(CO).':'CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l) has ΔH° = −890.5 kJ. Use ΔHf° values CO₂ −393.5, H₂O(l) −285.8 and O₂ 0 kJ/mol. Find ΔHf°(CH₄).',answer,unit:'kJ/mol',steps:[`ΔH° = sum(products) − sum(reactants).`,`The unknown reactant formation value is ${products} − (${total}) = ${answer} kJ/mol.`]};});
add('calorimetry-hess','calorimetry','c10-calorimetry-chain','Calorimetry into Hess law',v=>{const n=v('n',0.01,0.02,0.002),m=v('m',150,300,25),dt=466.9*n*1000/(m*4.19);return {prompt:`${fmt(n)} mol Mg reacts with excess HCl and warms ${m} g solution by ${fmt(dt)} °C. Use c = 4.19 J/(g·°C), complete heat capture and negligible apparatus heat. This gives reaction 1: Mg + 2HCl → MgCl₂ + H₂. Reaction 2: MgO + 2HCl → MgCl₂ + H₂O, ΔH₂ = −151.0 kJ/mol. Reaction 3: H₂ + ½O₂ → H₂O, ΔH₃ = −285.8 kJ/mol. Find ΔH for Mg + ½O₂ → MgO using 1 + 3 − 2, on a one-mole basis.`,answer:-601.7,unit:'kJ/mol',steps:[`qsolution = mcΔT = ${fmt(466.9*n)} kJ.`,`ΔH₁ = −qsolution/n = −466.9 kJ/mol.`,`ΔHtarget = ΔH₁ + ΔH₃ − ΔH₂ = −466.9 −285.8 −(−151.0) = −601.7 kJ/mol.`]};});
add('useful-energy','efficiency','c10-useful-energy','Useful energy output',v=>{const input=v('input',100,500,25),eta=v('eta',40,85,5);return {prompt:`A device receives ${input} kJ and converts ${eta}% into useful output. Find the useful energy.`,answer:input*eta/100,unit:'kJ',steps:[`Useful energy = input × efficiency fraction.`,`Euseful = ${input} × ${eta/100} = ${fmt(input*eta/100)} kJ.`]};});
add('efficiency-percent','efficiency','c10-efficiency-ratio','Efficiency as a percentage',v=>{const input=v('input',100,400,25),eta=v('eta',30,90,5),useful=input*eta/100;return {prompt:`A process takes in ${input} kJ and delivers ${fmt(useful)} kJ of useful output. Find its efficiency as a percentage.`,answer:eta,unit:'%',steps:[`Efficiency = useful/input × 100%.`,`(${fmt(useful)}/${input}) × 100% = ${eta}%.`]};});
add('two-stage-efficiency','efficiency','c10-efficiency-stages','Successive efficiency stages',v=>{const input=v('input',100,500,50),a=v('a',50,90,10),b=v('b',40,80,10);return {prompt:`${input} kJ passes through a ${a}%-efficient stage and then a ${b}%-efficient stage. Find the final useful energy.`,answer:input*a*b/10000,unit:'kJ',steps:[`Multiply the efficiency fractions; do not add percentages.`,`Efinal = ${input} × ${a/100} × ${b/100} = ${fmt(input*a*b/10000)} kJ.`]};});
add('fuel-useful-mass','fuels','c10-fuel-basis','Compare useful fuel output',v=>{const need=v('need',20,100,10),eta=v('eta',40,80,10);return {prompt:`A fuel releases 29.7 kJ/g and a heater converts ${eta}% into useful heat. Find the fuel mass needed for ${need} kJ useful heat. Use positive energy magnitudes.`,answer:need/(29.7*eta/100),unit:'g',steps:[`Each gram supplies 29.7 × ${eta/100} = ${fmt(29.7*eta/100)} kJ useful heat.`,`m = ${need}/(${fmt(29.7*eta/100)}) = ${fmt(need/(29.7*eta/100))} g.`]};});
add('profile-enthalpy','c11-profiles','c11-profile-delta','Endpoint energy difference',v=>{const x=profile(v);return {prompt:`A reaction profile has reactants at ${x.r} kJ, products at ${x.p} kJ and a peak at ${x.peak} kJ. Find signed ΔH.`,answer:x.change,unit:'kJ',steps:[`ΔH = Eproducts − Ereactants.`,`ΔH = ${x.p} − ${x.r} = ${x.change} kJ. The peak is not used in this subtraction.`]};});
add('profile-forward','c11-profiles','c11-profile-forward','Forward activation energy',v=>{const x=profile(v);return {prompt:`Reactants are at ${x.r} kJ, products at ${x.p} kJ and the reaction-profile peak at ${x.peak} kJ. Find forward activation energy.`,answer:x.peak-x.r,unit:'kJ',steps:[`Ea,forward = Epeak − Ereactants.`,`${x.peak} − ${x.r} = ${x.peak-x.r} kJ.`]};});
add('profile-reverse','c11-profiles','c11-profile-reverse','Reverse activation energy',v=>{const x=profile(v);return {prompt:`Reactants are at ${x.r} kJ, products at ${x.p} kJ and the peak at ${x.peak} kJ. Find reverse activation energy.`,answer:x.peak-x.p,unit:'kJ',steps:[`The reverse reaction starts at the original product level.`,`Ea,reverse = Epeak − Eproducts = ${x.peak} − ${x.p} = ${x.peak-x.p} kJ.`]};});
add('catalyst-barrier','c11-catalysts','c11-catalyst-barrier','Catalyzed activation energy',v=>{const r=v('r',10,40,10),barrier=v('barrier',20,50,10),uncat=barrier+v('extra',20,60,10);return {prompt:`Reactants are at ${r} kJ. An uncatalyzed pathway peaks at ${r+uncat} kJ, while a catalyzed pathway peaks at ${r+barrier} kJ. Find the catalyzed forward activation energy.`,answer:barrier,unit:'kJ',steps:[`Use the catalyzed peak and the unchanged reactant level.`,`Ea,catalyzed = ${r+barrier} − ${r} = ${barrier} kJ.`]};});
add('average-rate','c11-investigation','c11-rate-evidence','Average product-formation rate',v=>{const start=v('start',0,20,5),gain=v('gain',20,80,10),time=v('time',10,40,5);return {prompt:`A gas volume rises from ${start} mL to ${start+gain} mL over ${time} s in a controlled reaction-rate trial. Find average gas-formation rate.`,answer:gain/time,unit:'mL/s',steps:[`Average rate = change in gas volume/change in time.`,`Rate = (${start+gain} − ${start})/${time} = ${fmt(gain/time)} mL/s.`]};});
add('bond-budget','c11-bonds','c11-bond-budget','Approximate bond-energy budget',v=>{const broken=v('broken',500,900,50),formed=v('formed',400,1000,50);return {prompt:`An average-bond-enthalpy model requires ${broken} kJ to break the stated bonds and releases ${formed} kJ when new bonds form, for the same reaction basis. Estimate ΔH.`,answer:broken-formed,unit:'kJ',steps:[`Approximate ΔH = energy required to break bonds − energy released by forming bonds.`,`ΔH ≈ ${broken} − ${formed} = ${broken-formed} kJ. This is an approximate model, not an exact formation-data result.`]};});
add('reverse-barrier-relation','c11-profiles','c11-profile-reverse','Relate forward and reverse barriers',v=>{const dh=v('dh',-40,40,10),forward=v('forward',70,120,10);return {prompt:`A single-barrier reaction has ΔH = ${dh} kJ and forward activation energy ${forward} kJ. Find reverse activation energy.`,answer:forward-dh,unit:'kJ',steps:[`Ea,reverse = Ea,forward − ΔH.`,`Ea,reverse = ${forward} − (${dh}) = ${forward-dh} kJ.`]};});
})(typeof window==='undefined'?globalThis:window);
