import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdir} from 'node:fs/promises';import {createServer} from 'node:http';import path from 'node:path';import {chromium,expect} from '@playwright/test';
test('BCD optional explanation labels have divider clearance, aligned checkboxes and persistent non-gating state',async()=>{
 const evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-c-optional-label';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const match=/^\/([bcd])\/(.*)$/.exec(decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!match)throw Error('unit');const rel=match[2]||'index.html';if(rel.split('/').includes('..'))throw Error('path');const bytes=await readFile(path.join(process.cwd(),`projects/biology30-unit-${match[1]}/workspace`,rel));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.ttf':'font/ttf'} as Record<string,string>)[path.extname(rel)]??'application/octet-stream');res.end(bytes);}catch{res.statusCode=404;res.end();}});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch();
 try{for(const [unit,topic,count] of [['b','male-reproductive-structures',34],['c','chromosomes-and-dna',71],['d','hardy-weinberg',22]] as const){const page=await browser.newPage({viewport:{width:1440,height:900}});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto(`http://127.0.0.1:${address.port}/${unit}/#${unit}-topic-${topic}`);
 const detail=page.locator('.p2-advanced').first(),label=detail.locator('label'),box=label.locator('input');await expect(page.locator('.p2-advanced>label')).toHaveCount(count);
 await detail.locator('summary').click();const progress=await page.locator('[data-pilot2-progress-count]').textContent();await box.check();await page.reload();await detail.locator('summary').click();await expect(box).toBeChecked();await expect(page.locator('[data-pilot2-progress-count]')).toHaveText(progress!);
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});if(width===390)await expect.poll(async()=>{const b=await page.locator('#course-sidebar').boundingBox();return b?b.x+b.width:0;}).toBeLessThanOrEqual(1);await label.scrollIntoViewIfNeeded();await expect(label).toHaveCSS('display','flex');await expect(label).toHaveCSS('gap','10px');const metrics=await label.evaluate(el=>{const row=el.getBoundingClientRect(),input=el.querySelector('input')!.getBoundingClientRect(),parent=el.parentElement!.getBoundingClientRect();return {clearance:parent.bottom-row.bottom,rowX:row.x,rowRight:row.right,inputWidth:input.width,inputTop:input.top-row.top};});assert.ok(metrics.clearance>=20);assert.ok(metrics.rowX>=0&&metrics.rowRight<=width+1);assert.equal(metrics.inputWidth,20);assert.ok(metrics.inputTop>=8&&metrics.inputTop<=12);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${evidence}/${unit}-${width}.png`});}
 await box.uncheck();await expect(box).not.toBeChecked();await page.close();}
 }finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
});
