import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from '@playwright/test';

test('Actual BCD model labs use A investigation structure and gated case-prediction-evidence-save workflow',async()=>{
 const root=process.cwd(),evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-model-lab-process';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const match=/^\/([bcd])\/(.*)$/.exec(decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!match||match[2].split('/').includes('..'))throw Error('Invalid path');const relative=match[2]||'index.html',body=await readFile(path.join(root,`projects/biology30-unit-${match[1]}/workspace`,relative));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.ttf':'font/ttf'} as Record<string,string>)[path.extname(relative)]??'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch();let checks=0;
 try{for(const unit of ['b','c','d']){const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto(`http://127.0.0.1:${address.port}/${unit}/#${unit}-models`);await expect(page.getByRole('navigation',{name:'Lesson investigations'})).toBeVisible();const ids=await page.locator('[data-pilot2-model]').evaluateAll(nodes=>nodes.map(n=>n.id));for(const id of ids){await page.locator(`[data-p2-panel-target="${id}"]`).click();const panel=page.locator('#'+id),prediction=panel.locator('textarea').first(),explanation=panel.locator('textarea').last(),cases=panel.locator('[data-pilot2-model-case]'),result=panel.locator('[data-pilot2-model-result]');await expect(panel.locator('.model-plan dt')).toHaveText(['What you change','What stays the same','Evidence to examine']);await expect(panel.locator('.model-workflow-step')).toHaveCount(4);await expect(prediction).toBeDisabled();await expect(explanation).toBeDisabled();await cases.first().click();await expect(cases.first()).toHaveAttribute('aria-pressed','true');assert.notEqual(await cases.first().evaluate(n=>getComputedStyle(n).backgroundColor),await cases.nth(1).evaluate(n=>getComputedStyle(n).backgroundColor),'selected case must be visually distinct');await prediction.fill('I predict the selected change affects the measured comparison.');await panel.getByRole('button',{name:'Test my prediction',exact:true}).click();await expect(result).toBeVisible();await explanation.fill('The tested case differs from the reference; the displayed observations support this comparison.');await panel.getByRole('button',{name:'Save my investigation to Process Collection',exact:true}).click();await expect(panel.locator('[data-pilot2-collection-status]')).toContainText(/saved/i);await page.reload();await page.locator(`[data-p2-panel-target="${id}"]`).click();await expect(result).toBeVisible();await expect(explanation).not.toHaveValue('');if(id===ids[0]){await page.screenshot({path:`${evidence}/${unit}-desktop.png`});await page.setViewportSize({width:390,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${evidence}/${unit}-mobile.png`});await page.setViewportSize({width:1440,height:1000});}await cases.nth(1).click();await expect(result).toBeHidden();await expect(explanation).toBeDisabled();await expect(panel.locator('[data-pilot2-collect]')).toBeDisabled();checks++;}await page.close();}console.log(`${checks} actual model workflows and all-unit responsive checks passed`);
 }finally{await browser.close();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});
