import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import path from 'node:path';

test('generated practice starts, responds, restores and stays formative offline',async()=>{
 const root=path.resolve('projects/biology30-unit-a-pilot-3/workspace'),server=createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!file.startsWith(root+path.sep))throw Error();const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'application/octet-stream');res.end(data);}catch{res.statusCode=404;res.end();}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${(server.address() as any).port}/index.html`;
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1100,height:800}});await context.route(/youtube|google|vimeo|youtu\.be/,route=>route.abort());const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  const finishCurrent=async(section:string)=>{const root=page.locator(section);while(!await root.locator('.practice-summary').count()){if(await root.locator('[data-generated-reveal]').count()){await root.locator('[data-generated-reveal]').click();await root.locator('[data-generated-self="recalled"]').click();}else{const answerOnce=async()=>{const typed=root.locator('input[type=text][data-generated-answer]:not(:disabled)');if(await typed.count()){await typed.fill('test answer');assert.equal(await typed.inputValue(),'test answer');}const boxes=root.locator('input[type=radio][data-generated-answer]:not(:disabled),input[type=checkbox][data-generated-answer]:not(:disabled)');if(await boxes.count())await boxes.first().check();await root.locator('[data-generated-check]:not(:disabled)').click();await page.waitForTimeout(150);if(!await root.locator('[data-generated-feedback]').innerText())throw Error(`${await page.locator('[data-local-status]').innerText()}\n${await root.innerText()}`);};await answerOnce();if(await root.locator('[data-generated-check]:not(:disabled)').count())await answerOnce();}await root.locator('[data-generated-next]').waitFor();await root.locator('[data-generated-next]').click();await page.waitForTimeout(80);} };
  await page.goto(url+'#practice');await page.waitForTimeout(500);assert.match(await page.locator('[data-local-status]').innerText(),/Saved work opened/,errors.join('\n'));const flash=page.locator('[data-activity="flashcards"]');assert.equal(await flash.locator('[data-practice-count]').inputValue(),'10');await flash.locator('[data-practice-count]').selectOption('5');await flash.locator('[data-generated-start]').click();await page.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('projection updated'));const prompt=await flash.locator('.generated-question h3').innerText();assert.ok(await page.evaluate(()=>localStorage.getItem('biology30-unit-a-pilot-3:generated-practice-resume:v1')?.includes('flashcards')));await page.reload();await page.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('Saved work opened'));assert.equal(await flash.locator('.generated-question h3').innerText(),prompt);await finishCurrent('#activity-flashcards');assert.match(await flash.innerText(),/Flash-card self-assessments/);await flash.locator('[data-generated-another]').click();await page.waitForFunction(()=>document.querySelector('#activity-flashcards')?.textContent?.includes('Item 1 of'));
  const beforeProgress=await page.locator('[data-progress-percent]').innerText();await page.goto(url+'#fill-in-the-blanks');const blanks=page.locator('[data-activity="blanks"]');await blanks.locator('[data-practice-lesson]').selectOption('lesson-11');await blanks.locator('[data-practice-count]').selectOption('5');await blanks.locator('[data-generated-start]').click();await page.waitForFunction(()=>document.querySelector('#activity-blanks')?.textContent?.includes('Item 1 of 5'));await finishCurrent('#activity-blanks');assert.match(await blanks.innerText(),/First-try result/);assert.equal(await page.locator('[data-progress-percent]').innerText(),beforeProgress);
  await page.goto(url+'#mixed-practice');const mixed=page.locator('[data-activity="mixed-practice"]');await mixed.locator('[data-generated-start]').click();await page.waitForFunction(()=>document.querySelector('#activity-mixed-practice')?.textContent?.includes('Item 1 of 10'));assert.match(await mixed.innerText(),/Item 1 of 10/);for(const width of [1100,320]){await page.setViewportSize({width,height:800});if(width===320){await page.evaluate(()=>{document.body.classList.remove('nav-open');document.querySelector('.sidebar')?.classList.remove('is-open');});await page.waitForTimeout(250);assert.ok(await page.locator('.sidebar').evaluate(n=>n.getBoundingClientRect().right<=1));}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`/tmp/biology30-pilot3-generated-practice-${width}.png`,fullPage:true});}await finishCurrent('#activity-mixed-practice');assert.match(await mixed.innerText(),/Set complete/);
  const stale=await context.newPage();await stale.goto(url+'#mixed-practice');await stale.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('Saved work opened'));await page.evaluate(()=>localStorage.setItem('biology30-unit-a-pilot-3:v1:frayers','x'.repeat(60000)));await mixed.locator('[data-generated-another]').click();await page.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('60,000-character'));assert.match(await page.locator('[data-local-status]').innerText(),/Local IndexedDB work is intact/);await page.evaluate(()=>localStorage.removeItem('biology30-unit-a-pilot-3:v1:frayers'));await stale.locator('[data-activity="mixed-practice"] [data-generated-another]').click();await stale.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('Another tab changed'));await stale.close();await page.reload();await page.waitForFunction(()=>document.querySelector('#activity-mixed-practice')?.textContent?.includes('Resume saved set'));
  assert.deepEqual(errors,[]);
  const legacyContext=await browser.newContext(),legacy=await legacyContext.newPage();await legacy.goto(url+'#practice');await legacy.evaluate(async()=>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('biology30-unit-a-pilot-3:v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('work');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('work','readwrite');tx.objectStore('work').put({version:1,revision:0,current:{flashcards:{id:'legacy-run',activity:'flashcards',startedAt:1,drafts:{},attempts:[],questionIds:['card-1'],keys:(window as any).PILOT3_CATALOG}},history:[]},'state');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);};});});await legacy.reload();await legacy.waitForFunction(()=>document.querySelector('[data-local-status]')?.textContent?.includes('Saved work opened'));assert.ok(await legacy.locator('[data-legacy-practice]:visible').count());assert.match(await legacy.locator('#activity-flashcards').innerText(),/Legacy flashcards/);await legacyContext.close();
 }finally{await browser.close();server.close();}
});
