import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from '@playwright/test';

test('Advanced Learning has aligned gutters, separated headings and readable activity controls',async()=>{
 const root=process.cwd(),evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-advanced-spacing';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const match=/^\/([bcd])\/(.*)$/.exec(decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!match||match[2].split('/').includes('..'))throw Error('Invalid path');const relative=match[2]||'index.html',body=await readFile(path.join(root,`projects/biology30-unit-${match[1]}/workspace`,relative));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.ttf':'font/ttf'} as Record<string,string>)[path.extname(relative)]??'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch();let checks=0;
 try{for(const unit of ['b','c','d']){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${address.port}/${unit}/#${unit}-advanced`);for(const width of [1667,1280,900,390]){await page.setViewportSize({width,height:1000});const metrics=await page.locator('.advanced-index').evaluate(n=>{const box=n.getBoundingClientRect(),heading=n.querySelector('h3')!.getBoundingClientRect(),list=n.querySelector('ol')!.getBoundingClientRect(),row=n.querySelector('li')!,copy=row.querySelector('.advanced-index-copy')!.getBoundingClientRect(),actions=row.querySelector('.advanced-index-actions')!.getBoundingClientRect();return{width:innerWidth,leftGap:heading.left-box.left,rightGap:box.right-list.right,headingGap:list.left-heading.right,stacked:list.top>=heading.bottom,controlsGap:actions.left-copy.right,controlsStacked:actions.top>=copy.bottom,overflow:document.documentElement.scrollWidth>innerWidth+1};});assert.ok(metrics.leftGap>=21,JSON.stringify(metrics));assert.ok(metrics.rightGap>=21,JSON.stringify(metrics));assert.ok(metrics.stacked||metrics.headingGap>=31,JSON.stringify(metrics));assert.ok(metrics.controlsStacked||metrics.controlsGap>=27,JSON.stringify(metrics));assert.equal(metrics.overflow,false);checks++;if(width===1667||width===390)await page.screenshot({path:`${evidence}/${unit}-${width}.png`});}await page.setViewportSize({width:1667,height:1000});const row=page.locator('.advanced-index li').first(),checkbox=row.locator('input[type=checkbox]');await checkbox.check();await page.reload();await expect(row.locator('input[type=checkbox]')).toBeChecked();await row.getByRole('link',{name:'Open in lesson',exact:true}).click();await expect(page.locator('.course-page:visible .p2-advanced[open]')).toHaveCount(1);await page.close();}console.log(`${checks} all-unit spacing checks plus checklist reload and return-to-lesson passed`);
 }finally{await browser.close();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});
