import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,firefox,webkit,expect} from '@playwright/test';
import {load} from 'cheerio';
import {courseFixture} from './fixtures/biology30-pilot2/renderer.js';
import {selectTopicMedia,renderTopicVideoLibrary,type TopicMediaManifest} from '../lib/biology30-course/v1/pilot2-media.js';
import {renderTopicCourse} from '../lib/biology30-course/v1/pilot2-render-course.js';
import {bundleTopicBrowser} from '../lib/biology30-course/v1/pilot2-browser-bundle.js';
function fixture(){const input=courseFixture(),topic=input.topic.contract.topics[0],manifest:TopicMediaManifest={unit:'B',teacherDecision:null,youtubeCandidates:[{videoId:'testClip_01',learnerSelected:true,required:false,providerFilesDownloaded:false,sourceOccurrences:[{videoId:'testClip_01',unit:'B',url:'https://www.youtube.com/watch?v=testClip_01',relationshipId:'fixture'}],teachingTopicIds:[topic.id],localWalkthroughTargets:[topic.id+'-walkthrough'],selection:{title:'Synthetic <video> comparison',category:'Comparisons',startSeconds:15,endSeconds:45,captionGuidance:'Use captions in the provider controls.',prerequisiteGuidance:'Read the supplied symbols first.',review:{status:'author-reviewed-provisional',evidencePath:'projects/resources/biology30-production/v1/fixture.json',evidenceSha256:'a'.repeat(64),captions:'Synthetic test review.',facts:'Synthetic test review.',prerequisites:'Synthetic test review.',pace:'Synthetic test review.',relevance:'Synthetic test review.',segment:'Synthetic test review.',localEquivalence:'Synthetic test review.'}}}]};return{input,manifest};}
test('media requires explicit reviewed selection, exact mappings and one entry per video identity',()=>{
 const {input,manifest}=fixture(),select=(m:TopicMediaManifest,figures=input.topic.figures.map(f=>f.id))=>selectTopicMedia(m,input.topic.contract,input.topic.framing,figures);
 const clips=select(manifest);assert.equal(clips.length,1);assert.equal(clips[0].topics[0].checkpointId,'b-topic-fixture-media');
 for(const mutate of [(m:TopicMediaManifest)=>{delete m.youtubeCandidates[0].selection;},(m:TopicMediaManifest)=>{m.youtubeCandidates[0].selection!.review.captions='';},(m:TopicMediaManifest)=>{m.youtubeCandidates[0].selection!.endSeconds=0;},(m:TopicMediaManifest)=>{m.youtubeCandidates[0].providerFilesDownloaded=true;},(m:TopicMediaManifest)=>{m.youtubeCandidates.push(structuredClone(m.youtubeCandidates[0]));},(m:TopicMediaManifest)=>{m.youtubeCandidates[0].localWalkthroughTargets=['missing'];}]){const bad=structuredClone(manifest);mutate(bad);assert.throws(()=>select(bad));}
 assert.throws(()=>select(manifest,[]),/illustrated/);
 const unselected=structuredClone(manifest);unselected.youtubeCandidates[0].learnerSelected=false;delete unselected.youtubeCandidates[0].selection;assert.deepEqual(select(unselected),[]);unselected.youtubeCandidates[0].required=true;assert.throws(()=>select(unselected),/required/);
 const $=load(renderTopicVideoLibrary(clips,input.topic.contract));assert.equal($('video,iframe,script,button').length,0);assert.equal($('[data-pilot2-video]').length,1);assert.equal($('h3').text(),'Synthetic <video> comparison');assert.equal($('[data-pilot2-return-focus="b-topic-fixture-walkthrough"]').length,2);
});
test('whole-course media owns one library entry and reuses the original walkthrough/checkpoint',()=>{
 const{input,manifest}=fixture(),videos=selectTopicMedia(manifest,input.topic.contract,input.topic.framing,input.topic.figures.map(f=>f.id));const $=load(renderTopicCourse({...input,videos}).html);
 assert.equal($('#b-video-library [data-pilot2-video]').length,1);assert.equal($('#b-topic-fixture [data-pilot2-video]').length,1);assert.equal($('#b-topic-fixture-walkthrough').length,1);assert.equal($('[data-pilot2-response="b-topic-fixture-media"]').length,1);
 for(const link of $('[data-pilot2-return-route]').toArray()){const route=$(link).attr('data-pilot2-return-route')!,focus=$(link).attr('data-pilot2-return-focus')!;assert.equal($(`[id="${route}"] [id="${focus}"]`).length,1);}
 assert.equal($('[autoplay]').length,0);
});
for(const type of [chromium,firefox,webkit])test(`media visible-only preview, failure path and same checkpoint in ${type.name()}`,async()=>{
 const{input,manifest}=fixture(),videos=selectTopicMedia(manifest,input.topic.contract,input.topic.framing,input.topic.figures.map(f=>f.id)),html=renderTopicCourse({...input,videos}).html,script=(await bundleTopicBrowser(process.cwd())).bytes;
 const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/assets/pilot2-course.js'?'text/javascript':req.url==='/assets/fixture.svg'?'image/svg+xml':'text/html');res.end(req.url==='/assets/pilot2-course.js'?script:req.url==='/assets/fixture.svg'?'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><text>A B</text></svg>':html);});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await type.launch();
 try{const context=await browser.newContext({viewport:{width:390,height:900}});await context.addInitScript(`window.mediaCalls=[];window.mediaErrors=[];window.YT={Player:class{constructor(host,options){this.iframe=document.createElement('iframe');host.replaceWith(this.iframe);window.mediaCalls.push({kind:'create',options:options.playerVars});window.mediaErrors.push(options.events.onError);queueMicrotask(()=>options.events.onReady({target:this}));}getIframe(){return this.iframe}cueVideoById(segment){window.mediaCalls.push({kind:'cue',segment})}pauseVideo(){window.mediaCalls.push({kind:'pause'})}destroy(){this.iframe.remove()}}};`);const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${address.port}`);assert.equal(await page.evaluate('window.mediaCalls.length'),0);
 await page.evaluate(()=>{location.hash='b-video-library'});await page.locator('#b-video-library [data-pilot2-video]').scrollIntoViewIfNeeded();await expect.poll(()=>page.evaluate('window.mediaCalls.filter(c=>c.kind==="cue").length')).toBe(1);assert.deepEqual(await page.evaluate('window.mediaCalls.find(c=>c.kind==="cue").segment'),{videoId:'testClip_01',startSeconds:15,endSeconds:45});assert.equal(await page.evaluate('window.mediaCalls.find(c=>c.kind==="create").options.autoplay'),0);
 await page.evaluate('window.mediaErrors[0]()');await expect(page.locator('#b-video-library [data-pilot2-video-local]')).toHaveAttribute('open','');if(process.env.BIOLOGY30_MEDIA_SCREENSHOTS){await mkdir(process.env.BIOLOGY30_MEDIA_SCREENSHOTS,{recursive:true});await page.addStyleTag({content:'html,body{scroll-behavior:auto!important;overflow-anchor:none!important}'});await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur()});await expect.poll(()=>page.evaluate(()=>{scrollTo({top:0,behavior:'instant'});return scrollY})).toBe(0);await page.screenshot({path:path.join(process.env.BIOLOGY30_MEDIA_SCREENSHOTS,`${type.name()}-media-fallback-390-v3.png`),fullPage:true});}await page.locator('#b-video-library [data-pilot2-video-local] [data-pilot2-return-focus="b-topic-fixture-media"]').click();await expect(page.locator('[data-pilot2-response="b-topic-fixture-media"]')).toBeFocused();await page.locator('[data-pilot2-response="b-topic-fixture-media"]').fill('The two symbols differ.');await page.getByRole('button',{name:'Save checkpoint attempt',exact:true}).click();await page.reload();await expect(page.locator('[data-pilot2-response="b-topic-fixture-media"]')).toHaveValue('The two symbols differ.');
 await context.setOffline(true);await page.evaluate(()=>{location.hash='b-video-library'});await page.locator('#b-video-library [data-pilot2-video]').scrollIntoViewIfNeeded();await expect(page.locator('#b-video-library [data-pilot2-video-local]')).toHaveAttribute('open','');await page.locator('#b-video-library [data-pilot2-return-focus="b-topic-fixture-walkthrough"]').last().click();await expect(page.locator('#b-topic-fixture-walkthrough')).toBeVisible();await expect(page.locator('[data-pilot2-response="b-topic-fixture-media"]')).toHaveValue('The two symbols differ.');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
 await context.setOffline(false);const blocked=await context.newPage();await blocked.route('https://www.youtube.com/**',route=>route.abort());await blocked.goto(`http://127.0.0.1:${address.port}`);await blocked.evaluate('delete window.YT');await blocked.evaluate(()=>{location.hash='b-video-library'});await blocked.locator('#b-video-library [data-pilot2-video]').scrollIntoViewIfNeeded();await expect(blocked.locator('#b-video-library [data-pilot2-video-local]')).toHaveAttribute('open','');await expect(blocked.locator('#b-video-library [data-pilot2-video-status]')).toContainText('could not load');
 }finally{await browser.close();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));}
});
