import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,firefox,webkit,expect} from '@playwright/test';
import {bundleTopicBrowser} from '../lib/biology30-course/v1/pilot2-browser-bundle.js';
import {courseFixture} from './fixtures/biology30-pilot2/renderer.js';
import {renderTopicCourse} from '../lib/biology30-course/v1/pilot2-render-course.js';
import {emptyTopicState,encodeTopicState} from '../lib/biology30-course/v1/pilot2-state.js';
for(const type of [chromium,firefox,webkit])test(`synthetic whole-course shell and session in ${type.name()}`,async()=>{
 const input=courseFixture(),rendered=renderTopicCourse(input),key='biology30-unit-b:pilot2-v3';
 const script=(await bundleTopicBrowser(process.cwd())).bytes,svg='<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><text x="100" y="200" font-size="90">A B</text></svg>';
 const server=createServer((req,res)=>{const [kind,body]=req.url==='/assets/pilot2-course.js'?['text/javascript',script]:req.url==='/assets/fixture.svg'?['image/svg+xml',svg]:['text/html',rendered.html];res.setHeader('Content-Type',kind);res.end(body);});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await type.launch();
 try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${address.port}`);await expect(page.locator('#overview')).toBeVisible();await page.locator('#overview a[data-page-target="b-topic-fixture"]').click();await expect(page.locator('#b-topic-fixture')).toBeVisible();
 await page.locator('[data-pilot2-response="written"]').fill('An answer in the assembled shell.');await page.locator('#b-topic-fixture .p2-required-nav a[data-page-target="b-chapter-14-practice"]').click();await expect(page.locator('#b-chapter-14-practice')).toBeVisible();await expect(page.locator('#b-topic-fixture')).toBeHidden();
 await page.locator('[data-pilot2-textbook-attempt]').click();await expect(page.locator('#fixture-textbook-guide')).toBeVisible();await page.reload();await expect(page.locator('#b-chapter-14-practice')).toBeVisible();await expect(page.locator('#fixture-textbook-guide')).toBeHidden();
 await page.locator('#b-chapter-14-practice .p2-required-nav a[data-page-target="b-review-seminar"]').click();await expect(page.locator('#b-review-seminar')).toBeVisible();
 await page.evaluate(()=>{location.hash='b-all-my-work';});await expect(page.locator('#b-all-my-work')).toBeVisible();await page.locator('#b-all-my-work [data-pilot2-return-focus="written"]').click();await expect(page.locator('#b-topic-fixture')).toBeVisible();await expect(page.locator('[data-pilot2-response="written"]')).toBeFocused();await expect(page.locator('[data-pilot2-response="written"]')).toHaveValue('An answer in the assembled shell.');
 // Focus return is proved above. End smooth scrolling and release the caret
 // before resizing for static screenshots; Chromium can otherwise keep the
 // focused answer visible and override the requested top-of-page capture.
 // Reapply the static capture position while resize anchoring settles; this
 // assertion is capture setup, after the actual focus-return assertion.
 await page.evaluate("document.activeElement.blur();document.documentElement.style.scrollBehavior='auto'");
 for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});await page.evaluate("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await expect.poll(()=>page.evaluate(()=>{scrollTo({top:0,behavior:"instant"});return scrollY;})).toBe(0);if(process.env.BIOLOGY30_FIXTURE_SCREENSHOTS){await mkdir(process.env.BIOLOGY30_FIXTURE_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.BIOLOGY30_FIXTURE_SCREENSHOTS,`${type.name()}-course-${width}.png`),fullPage:false});}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),JSON.stringify(await page.evaluate("({width:innerWidth,scroll:document.documentElement.scrollWidth,nodes:Array.from(document.querySelectorAll('body *')).map(n=>({tag:n.tagName,id:n.id,cls:n.className,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})).filter(n=>n.right>innerWidth+1&&n.left>=0).slice(0,20)})")));}
 const radio=await page.locator('[data-pilot2-choice="selected"]').first().boundingBox();assert.ok(radio&&radio.width<=28&&radio.height<=28);assert.deepEqual(errors,[]);
 const context=await browser.newContext(),local=emptyTopicState(input.topic.state),platform=emptyTopicState(input.topic.state);local.responses.written='Device original';platform.responses.written='Platform original';
 await context.addInitScript(`window.platformCalls=[];window.API_1484_11={Initialize(){return 'true'},GetValue(){return ${JSON.stringify(encodeTopicState(platform,input.topic.state))}},GetLastError(){return '0'},SetValue(name,value){window.platformCalls.push([name,value]);return 'true'},Commit(){return 'false'},Terminate(){return 'true'}};localStorage.setItem(${JSON.stringify(key)},${JSON.stringify(encodeTopicState(local,input.topic.state))});`);
 const conflict=await context.newPage();await conflict.goto(`http://127.0.0.1:${address.port}`);await expect(conflict.locator('#pilot2-course-surface')).toBeHidden();assert.equal(await conflict.evaluate('platformCalls.length'),0);await conflict.locator('[data-pilot2-recovery-choice]').selectOption('lms');await conflict.locator('[data-pilot2-recovery-confirm]').check();await conflict.locator('[data-pilot2-recovery-continue]').click();await conflict.evaluate("location.hash='b-topic-fixture'");await expect(conflict.locator('[data-pilot2-response="written"]')).toHaveValue('Platform original');await conflict.locator('[data-pilot2-response="written"]').fill('A new platform-session answer');await expect(conflict.locator('[data-pilot2-save-status]')).toContainText('did not confirm saving');await expect(conflict.locator('[data-pilot2-save-status]')).toContainText('Saved on this device');await conflict.evaluate("location.hash='b-all-my-work'");await expect(conflict.locator('[data-pilot2-work-list]')).toContainText('Device original');await context.close();
 const deniedContext=await browser.newContext();await deniedContext.addInitScript("Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked storage')}})");const denied=await deniedContext.newPage();await denied.goto(`http://127.0.0.1:${address.port}`);await expect(denied.locator('#pilot2-course-surface')).toBeHidden();await expect(denied.locator('#pilot2-recovery')).toContainText('No empty replacement has been saved');await deniedContext.close();
 }finally{await browser.close();await new Promise<void>((r,j)=>server.close(error=>error?j(error):r()));}
});
