import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {compactResumeProjection,generatePracticeSession,gradeGeneratedItem,normalizePracticeAnswer,restoreGeneratedItem,validatePracticeBank,type PracticeBank} from '../lib/biology30-pilot3/practice-engine.js';

async function bank(){const context:{window:Record<string,unknown>}={window:{}};vm.runInNewContext(await readFile('projects/biology30-unit-a-pilot-3/workspace/assets/pilot3-practice-bank.js','utf8'),context);return context.window.PILOT3_PRACTICE_BANK as PracticeBank;}

test('Pilot 3 bank covers every learner-facing Chapter 11 selection and validates legacy concepts',async()=>{const data=await bank();assert.deepEqual(validatePracticeBank(data),[]);assert.equal(data.lessons.length,13);for(const lesson of data.lessons)assert.ok(data.concepts.filter(x=>x.lessonId===lesson.id).length>=2,lesson.id);const legacy=data.concepts.filter(x=>!data.lessons.some(lesson=>lesson.id===x.lessonId));assert.equal(legacy.length,2);assert.ok(legacy.every(x=>x.lessonId==='lesson-14'));});
test('generation is deterministic, unique, filtered and mixed-balanced',async()=>{const data=await bank();for(const lesson of data.lessons){for(const kind of ['flashcards','blanks','mixed-practice'] as const){const a=generatePracticeSession(data,kind,{lessonId:lesson.id,count:15},12345),b=generatePracticeSession(data,kind,{lessonId:lesson.id,count:15},12345);assert.deepEqual(a,b);assert.ok(a.items.length>=5,`${lesson.id} ${kind}`);assert.equal(new Set(a.items.map(x=>x.id)).size,a.items.length);assert.ok(a.items.every(x=>x.lessonId===lesson.id));}}const mixed=generatePracticeSession(data,'mixed-practice',{lessonId:'all',count:15},88,{'resting-potential':{correct:0,attempts:3}});for(const family of ['retrieval','discrimination','application','sequence','misconception','diagram-pathway','adaptive-review'])assert.ok(mixed.items.some(x=>x.family===family),family);assert.ok(mixed.items.some(x=>x.id.includes(':mc-')),'mixed practice reuses the MC bank');for(let i=2;i<mixed.items.length;i++)assert.ok(!(mixed.items[i].interaction===mixed.items[i-1].interaction&&mixed.items[i].interaction===mixed.items[i-2].interaction));});
test('multiple-choice sets are substantial, deterministic, filtered and broadly distributed',async()=>{const data=await bank();assert.equal(data.concepts.flatMap(x=>x.mcVariants).length,280);for(const lesson of data.lessons.filter(x=>!x.optional)){const session=generatePracticeSession(data,'multiple-choice',{lessonId:lesson.id,count:20,difficulty:'mixed'},12345);assert.equal(session.items.length,20,lesson.id);assert.ok(session.items.every(x=>x.lessonId===lesson.id));for(const item of session.items){assert.equal(item.interaction,'single');assert.equal(item.options?.length,4);assert.equal(new Set(item.options).size,4);assert.equal(item.options?.filter(x=>x===item.answers[0]).length,1);}}const a=generatePracticeSession(data,'multiple-choice',{lessonId:'all',count:20,difficulty:'mixed'},88),b=generatePracticeSession(data,'multiple-choice',{lessonId:'all',count:20,difficulty:'mixed'},88),c=generatePracticeSession(data,'multiple-choice',{lessonId:'all',count:20,difficulty:'mixed'},89);assert.deepEqual(a,b);assert.notDeepEqual(a.items.map(x=>[x.id,x.options]),c.items.map(x=>[x.id,x.options]));assert.ok(new Set(a.items.map(x=>x.lessonId)).size>=10);const foundations=generatePracticeSession(data,'multiple-choice',{lessonId:'foundations',count:15,difficulty:'mixed'},42);assert.ok(foundations.items.every(x=>['lesson-01','lesson-02','lesson-03'].includes(x.lessonId)));for(const [difficulty,levels] of [['foundation',[1]],['developing',[2]],['application',[3,4]]] as const){const filtered=generatePracticeSession(data,'multiple-choice',{lessonId:'lesson-05',count:5,difficulty},7);assert.equal(filtered.items.length,5);assert.ok(filtered.items.every(x=>x.difficulty&&levels.includes(x.difficulty)));}});
test('grading normalizes only harmless text differences and projection restores variants',async()=>{const data=await bank();assert.equal(normalizePracticeAnswer('  Na+  .'),'na+');const session=generatePracticeSession(data,'blanks',{lessonId:'lesson-04',count:5},7);assert.ok(gradeGeneratedItem(session.items[0],[session.items[0].answers[0].toUpperCase()+'!']));const projection=compactResumeProjection({blanks:session},{});assert.ok(JSON.stringify(projection).length<8000);for(const stored of projection.sessions.blanks.items){const restored=restoreGeneratedItem(data,'blanks',stored.id,stored.options);assert.equal(restored.id,stored.id);assert.deepEqual(restored.options,stored.options);}});
