import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from '@playwright/test';
import {inspectTopicInputs} from '../lib/biology30-course/v1/pilot2-inputs.js';
import {renderTopicCourse} from '../lib/biology30-course/v1/pilot2-render-course.js';
import {bundleTopicBrowser} from '../lib/biology30-course/v1/pilot2-browser-bundle.js';
const root=process.cwd();
test('actual A presentation transfer: navigation, vocabulary, model, textbook, save/reload and mobile',async()=>{
 const bundle=await bundleTopicBrowser(root),inputs=await Promise.all((['B','C','D'] as const).map(u=>inspectTopicInputs(root,u))),html=inputs.map(i=>renderTopicCourse(i,i.legacySchema).html);
 const evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-vocabulary-source-videos';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const url=new URL(req.url!,'http://localhost'),match=/^\/([abcd])\/(.*)$/.exec(decodeURIComponent(url.pathname));if(!match)throw 0;const unit=match[1],relative=match[2]||'index.html';if(relative.split('/').includes('..'))throw 0;
  const i='bcd'.indexOf(unit);let body:Uint8Array|string;
  if(unit==='a')body=await readFile(path.join(root,'projects/biology30-unit-a-pilot-2/workspace',relative));else if(relative==='index.html')body=html[i];else if(relative===bundle.destination)body=bundle.bytes;else{const copy=inputs[i].copies.find(c=>c.destination===relative);if(!copy)throw 0;body=await readFile(path.join(root,copy.sourcePath));}
  res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.ttf':'font/ttf'} as Record<string,string>)[path.extname(relative)]??'application/octet-stream');res.end(body);
 }catch{res.statusCode=404;res.end('Not found');}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const base=`http://127.0.0.1:${address.port}`,browser=await chromium.launch();
 try{
 const reference=await browser.newPage({viewport:{width:1440,height:1000}});await reference.goto(base+'/a/');await reference.evaluate(()=>document.fonts.ready);const font=await reference.locator('.overview-hero h1').evaluate(n=>({family:getComputedStyle(n).fontFamily,size:getComputedStyle(n).fontSize}));await reference.screenshot({path:evidence+'/a-overview.png'});
 for(const input of inputs){const unit=input.unit.toLowerCase(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const go=async(id:string)=>{await page.locator(`[data-page-target="${id}"]`).first().evaluate((n:HTMLElement)=>n.click());await expect(page.locator(`section#${id}`)).toBeVisible();};
  await page.goto(base+'/'+unit+'/');await expect(page.locator('#overview')).toBeVisible();await page.evaluate(()=>document.fonts.ready);assert.deepEqual(await page.locator('.overview-hero h1').evaluate(n=>({family:getComputedStyle(n).fontFamily,size:getComputedStyle(n).fontSize})),font);await page.screenshot({path:`${evidence}/${unit}-overview.png`});
  const first=input.topic.contract.topics[0],future=input.topic.vocabulary.conceptFamilies.find(f=>!first.parts.some(p=>f.teachingPartIds.includes(p.id)))!;
  await go(first.id);await expect(page.locator(`#${first.id} .lesson-words dl>div`)).toHaveCount(4);await page.screenshot({path:`${evidence}/${unit}-lesson.png`});
  await go(unit+'-core-vocabulary');await page.locator('[data-p2-vocabulary-filter]').selectOption('all');await page.locator(`[data-p2-family-target="${future.id}"]`).click();await expect(page.locator(`#${future.id} [data-p2-family-locked]`)).toBeVisible();await expect(page.locator(`#${future.id} [data-p2-family-content]`)).toBeHidden();
  const unlockRoute=await page.locator(`#${future.id}`).getAttribute('data-p2-unlock-route');await page.locator(`#${future.id} [data-p2-family-locked] a`).click();await expect(page.locator('section#'+unlockRoute)).toBeVisible();await go(unit+'-core-vocabulary');await page.locator(`[data-p2-family-target="${future.id}"]`).click();await expect(page.locator(`#${future.id} [data-p2-family-content]`)).toBeVisible();
  const family=input.topic.vocabulary.conceptFamilies.find(f=>input.topic.state.families.fixed.includes(f.id)&&first.parts.some(p=>f.teachingPartIds.includes(p.id)))??input.topic.vocabulary.conceptFamilies.find(f=>first.parts.some(p=>f.teachingPartIds.includes(p.id)))!;
  await page.locator('[data-p2-vocabulary-search]').fill(family.label);await page.locator(`[data-p2-family-target="${family.id}"]`).click();const choose=page.locator(`[data-p2-choose-family="${family.id}"]`);if(await choose.count())await choose.click();
  for(const id of input.topic.state.families.responseIds[family.id])await page.locator(`[data-pilot2-response="${id}"]`).fill('Saved presentation regression evidence.');
  await page.locator(`[data-pilot2-collect="${family.id}-collected"]`).click();await expect(page.locator(`[data-pilot2-frayer-compare="${family.id}"]`)).toBeEnabled();const collect=page.locator(`[data-pilot2-collect="${family.id}-collected"]`);await expect(collect).toHaveText('Remove from Process Collection');await collect.click();await expect(collect).toHaveText('Add to Process Collection');await collect.click();const compare=page.locator(`[data-pilot2-frayer-compare="${family.id}"]`);await compare.click();await expect(page.locator(`#${family.id}-guide`)).toBeVisible();await compare.click();await expect(page.locator(`#${family.id}-guide`)).toBeHidden();await page.screenshot({path:`${evidence}/${unit}-vocabulary.png`});
  await go(unit+'-all-my-work');await page.locator(`#${unit}-all-my-work [data-pilot2-return-focus="${family.id}"]`).click();await expect(page.locator(`#${family.id}`)).toBeVisible();await expect(page.locator(`[data-pilot2-response="${input.topic.state.families.responseIds[family.id][0]}"]`)).toBeFocused();
  await page.reload();await expect(page.locator('#'+unit+'-core-vocabulary')).toBeVisible();await expect(page.locator(`#${family.id}`)).toBeVisible();await page.locator('[data-p2-vocabulary-filter]').selectOption('all');await page.locator(`[data-p2-family-target="${family.id}"]`).click();await expect(page.locator(`[data-pilot2-response="${input.topic.state.families.responseIds[family.id][0]}"]`)).toHaveValue('Saved presentation regression evidence.');
  await go(unit+'-video-library');await expect(page.locator('.video-playlist [data-p2-panel-target]')).toHaveCount(input.sourceVideos!.length);const firstVideo=input.sourceVideos!.find(v=>v.metadataReachable)!;await page.locator(`[data-p2-panel-target="source-library-${firstVideo.videoId}"]`).click();await expect(page.locator('.source-video iframe')).toHaveCount(1);await expect(page.locator('.source-video iframe')).toHaveAttribute('src',new RegExp(firstVideo.videoId.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));await page.screenshot({path:`${evidence}/${unit}-videos.png`});
  await go(unit+'-models');const model=input.models[1];await page.locator(`[data-p2-panel-target="${model.id}"]`).click();await expect(page.locator('#'+model.id)).toBeVisible();await page.locator(`[data-pilot2-model-case="${model.id}"][data-pilot2-model-case-value="${model.options[0]}"]`).click();await page.locator(`[data-pilot2-response="${model.predictionId}"]`).fill('I predict the case changes this process.');await page.locator(`[data-pilot2-model-test="${model.id}"]`).click();await expect(page.locator(`[data-pilot2-model-result="${model.id}"]`)).toBeVisible();await page.screenshot({path:`${evidence}/${unit}-model.png`});
  await go(unit+'-advanced');const advancedId=input.topic.instruction.parts[0].advanced.id;await page.locator(`#${unit}-advanced [data-pilot2-optional-flag="${advancedId}-complete"]`).check();await go(first.id);await expect(page.locator(`#${first.id} [data-pilot2-optional-flag="${advancedId}-complete"]`)).toBeChecked();await page.reload();await go(unit+'-advanced');await expect(page.locator(`[data-p2-advanced-progress]`)).toContainText('1 of');await page.screenshot({path:`${evidence}/${unit}-advanced.png`});
  await go(unit+'-all-my-work');const note=page.locator(`[data-pilot2-response="${unit}-process-note"]`);await expect(note).toBeVisible();await note.fill('A process note saved inside the collection.');await page.reload();await expect(note).toHaveValue('A process note saved inside the collection.');await page.locator('[data-p2-work-chapter]').selectOption('Personal and collection work');await expect(page.locator('[data-pilot2-work-list]')).toContainText('A process note saved inside the collection.');await page.locator('[data-p2-work-chapter]').selectOption('');await page.screenshot({path:`${evidence}/${unit}-collection.png`});
  await go(unit+'-final-practice');await expect(page.locator(`#${unit}-diploma-challenge`)).toBeHidden();await page.locator(`#${unit}-final-practice .final-challenge>summary`).click();await expect(page.locator(`#${unit}-diploma-challenge`)).toBeVisible();
  await go(unit+'-textbook');await expect(page.locator('.library-frame:visible')).toHaveCount(1);await page.locator('.library-tabs [role=tab]').nth(1).click();await expect(page.locator('.library-tabs [role=tab]').nth(1)).toHaveAttribute('aria-selected','true');await page.screenshot({path:`${evidence}/${unit}-textbook.png`});await page.getByRole('link',{name:'Sources and Credits',exact:true}).click();await expect(page.locator('#'+unit+'-sources')).toBeVisible();await page.screenshot({path:`${evidence}/${unit}-sources.png`});
  const chapter=unit+'-chapter-'+first.chapter+'-practice';await go(chapter);await page.screenshot({path:`${evidence}/${unit}-practice.png`});await page.locator('#'+chapter+' [data-p2-textbook-group-attempt]').click();const book=input.textbookGroups.find(g=>g.chapter===first.chapter)!.items[0];await page.locator('#'+book.id+' [data-pilot2-textbook-attempt]').click();await page.reload();await expect(page.locator('#'+book.id+'-guide')).toBeHidden();
  for(const width of [1440,1024,720,390]){await page.setViewportSize({width,height:1000});for(const route of ['overview',...input.topic.contract.requiredRoutes,unit+'-core-vocabulary',unit+'-models',unit+'-investigations',unit+'-textbook',unit+'-all-my-work',unit+'-advanced',unit+'-glossary',unit+'-video-library',unit+'-sources-and-credits']){await go(route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),unit+'/'+route+'/'+width);}}
  await go(first.id);await page.getByRole('button',{name:'Open course menu',exact:true}).click();await expect(page.locator('.sidebar')).toHaveClass(/is-open/);await page.getByRole('link',{name:'Overview',exact:true}).click();await expect(page.locator('.sidebar')).not.toHaveClass(/is-open/);await expect.poll(()=>page.locator('.sidebar').evaluate(n=>n.getBoundingClientRect().right)).toBeLessThanOrEqual(1);await page.screenshot({path:`${evidence}/${unit}-mobile.png`});assert.deepEqual(errors,[]);await page.close();
 }
 }finally{await browser.close();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));}
});
