import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import path from 'node:path';import {chromium,expect} from '@playwright/test';
test('staged tasks remain usable on desktop/mobile and preserve synthetic writing on return',async()=>{
 const evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-instructional-repairs';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const match=/^\/(a-pilot-2|b|c|d)\/(.*)$/.exec(decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!match)throw Error('unit');const rel=match[2]||'index.html';if(rel.split('/').includes('..'))throw Error('path');const bytes=await readFile(path.join(process.cwd(),`projects/biology30-unit-${match[1]}/workspace`,rel));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.ttf':'font/ttf'} as Record<string,string>)[path.extname(rel)]??'application/octet-stream');res.end(bytes);}catch{res.statusCode=404;res.end();}});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch(),results:any[]=[];
 try{for(const unit of ['b','c','d']){const input=JSON.parse(await readFile(`projects/resources/biology30-production/v1/units/unit-${unit}/pilot2-practice.json`,'utf8'));const page=await browser.newPage({viewport:{width:1440,height:900}});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 for(const item of input.items.filter((x:any)=>x.stages)){
 await page.goto(`http://127.0.0.1:${address.port}/${unit}/#${item.routeId}`);const article=page.locator(`[data-pilot2-practice="${item.id}"]`),list=article.locator('.p2-task-stages');await expect(list.locator('li')).toHaveCount(item.stages.length);
 const response=article.locator('textarea[data-pilot2-response],textarea[data-pilot2-graph-explanation]').first();const sample='Synthetic test fixture only.\nWorking: 3′ → 5′; 6 plants/m². Résumé: separate evidence.';await response.fill(sample);await response.blur();await expect(response).toHaveValue(sample);await page.reload();await expect(response).toHaveValue(sample);
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});if(width===390)await expect.poll(async()=>{const b=await page.locator("#course-sidebar").boundingBox();return b?b.x+b.width:0;}).toBeLessThanOrEqual(1);await list.scrollIntoViewIfNeeded();const box=await list.boundingBox();assert.ok(box&&box.x>=0&&box.x+box.width<=width+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${evidence}/${item.id}-${width}.png`});results.push({unit,id:item.id,width,stages:item.stages.length,saveReload:true});}
 }
 await page.close();}
 const page=await browser.newPage();await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto(`http://127.0.0.1:${address.port}/a-pilot-2/#lesson-01`);for(const width of [1440,390]){await page.setViewportSize({width,height:900});if(width===390)await expect.poll(async()=>{const b=await page.locator("#course-sidebar").boundingBox();return b?b.x+b.width:0;}).toBeLessThanOrEqual(1);await page.locator('[data-core-zone="lesson-01-part-2"]>p').filter({hasText:"Channels are tiny"}).scrollIntoViewIfNeeded();await page.screenshot({path:`${evidence}/a-first-use-${width}.png`});}await page.close();
 await writeFile(`${evidence}/browser-results.json`,JSON.stringify({syntheticFixturesOnly:true,results},null,2)+'\n');
 }finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));}
});
