import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import path from 'node:path';
import {mkdir} from 'node:fs/promises';
import {chromium,firefox,webkit,expect} from '@playwright/test';
import {build} from 'esbuild';
import {studyFixture} from './fixtures/biology30-pilot2/renderer.js';
import {renderTopicModel} from '../lib/biology30-course/v1/pilot2-render-model.js';
import {renderTopicVocabulary} from '../lib/biology30-course/v1/pilot2-render-vocabulary.js';
import {renderTopicCollectionPage,TOPIC_COLLECTION_CSS} from '../lib/biology30-course/v1/pilot2-collection-view.js';
import {TOPIC_COMPONENT_CSS} from '../lib/biology30-course/v1/pilot2-render-topic.js';
for(const type of [chromium,firefox,webkit])test(`synthetic Predict-Test-Explain-Save and Frayer lifecycle in ${type.name()}`,async()=>{
 const fixture=studyFixture(),owner=path.resolve('scripts/lib/biology30-course/v1'),schema=fixture.schema,model=fixture.model;
 const code=`import {mountTopicControls} from ${JSON.stringify(owner+'/pilot2-controls-runtime.ts')};import {mountTopicModelControls} from ${JSON.stringify(owner+'/pilot2-model-controls.ts')};import {mountTopicFrayerControls} from ${JSON.stringify(owner+'/pilot2-frayer-controls.ts')};import {mountTopicCollection} from ${JSON.stringify(owner+'/pilot2-collection-view.ts')};import {emptyTopicState,decodeTopicState,persistTopicState} from ${JSON.stringify(owner+'/pilot2-state.ts')};
 const schema=${JSON.stringify(schema)},model=${JSON.stringify(model)},key='biology30-unit-b:pilot2-v3',raw=localStorage.getItem(key),state=raw?decodeTopicState(raw,schema):emptyTopicState(schema),root=document.getElementById('fixture');const controls=mountTopicControls(root,state,schema,s=>{const r=persistTopicState(s,schema,localStorage,null);return{saved:r.local==='saved',message:r.local==='saved'?'Saved on this device.':'Not saved.'};});mountTopicModelControls(root,state,schema,[model],controls);mountTopicFrayerControls(root,state,schema,controls);/* Component harness exposes all families; route/unlock presentation is tested against actual courses. */root.querySelectorAll('[data-p2-family-panel],[data-p2-family-content]').forEach(n=>n.hidden=false);root.querySelectorAll('[data-p2-family-locked]').forEach(n=>n.hidden=true);mountTopicCollection(root,${JSON.stringify(fixture.index)},state,schema);`;
 const script=(await build({stdin:{contents:code,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'browser',format:'iife'})).outputFiles[0].text;
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Synthetic study controls</title><style>body{font-family:system-ui;margin:16px}button,input,textarea,select{font:inherit}textarea{max-width:100%}${TOPIC_COMPONENT_CSS}${TOPIC_COLLECTION_CSS}</style><body><main id="fixture"><p data-pilot2-save-status role="status"></p>${renderTopicModel(model,schema)}${renderTopicVocabulary(fixture.vocabulary,fixture.input.contract,schema)}${renderTopicCollectionPage()}</main><script src="/fixture.js"></script></body></html>`;
 const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/fixture.js'?'text/javascript':'text/html');res.end(req.url==='/fixture.js'?script:html);});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await type.launch();
 try{
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${address.port}`);await expect(page.locator('.model-use-sequence span')).toHaveText(['1. Predict','2. Test','3. Explain','4. Save']);
  const prediction=page.locator('[data-pilot2-response="model-prediction"]'),explanation=page.locator('[data-pilot2-response="model-explanation"]'),choose=page.locator('[data-pilot2-model-choice]'),testButton=page.locator('[data-pilot2-model-test]'),result=page.locator('[data-pilot2-model-result]'),save=page.locator('[data-pilot2-collect="model-collected"]');
  await expect(testButton).toBeDisabled();await expect(prediction).toBeDisabled();await page.locator('[data-pilot2-model-case-value="support-defect"]').click();await prediction.fill('Support changes production.');await expect(testButton).toBeEnabled();await expect(result).toBeHidden();await expect(explanation).toBeDisabled();await expect(save).toBeDisabled();await testButton.click();await expect(result).toContainText('Case P');await explanation.fill('A draft explanation before testing.');await expect(save).toBeEnabled();await save.click();await page.reload();await expect(result).toContainText('Case P');await expect(prediction).toHaveValue('Support changes production.');
  await page.locator('[data-pilot2-model-case-value="duct-obstruction"]').click();await expect(result).toBeHidden();await expect(save).toBeDisabled();await expect(explanation).toHaveValue('A draft explanation before testing.');await testButton.click();await expect(result).toContainText('Case T');await prediction.fill('A revised prediction.');await expect(result).toBeHidden();await expect(save).toBeDisabled();
  await page.locator('.p2-family-choices>summary').click();const one=page.locator('[data-pilot2-frayer-choice="0"]'),two=page.locator('[data-pilot2-frayer-choice="1"]');await expect(two).toBeDisabled();await one.selectOption('family-one');await two.selectOption('family-two');
  for(let i=0;i<4;i++)await page.locator(`[data-pilot2-response="family-one-${i}"]`).fill(`First family response ${i}`);
  await page.locator('[data-pilot2-response="family-two-0"]').fill('Keep the other family.');await page.locator('[data-pilot2-frayer-compare="family-one"]').click();await expect(page.locator('#family-one-guide')).toBeVisible();
  await one.selectOption('family-three');await expect(one).toHaveValue('family-one');await expect(page.locator('[data-pilot2-frayer-status]')).toContainText('explicitly clear');
  const family=page.locator('#family-one');await family.locator('details summary').click();await expect(family.locator('[data-pilot2-frayer-clear]')).toBeDisabled();await family.locator('[data-pilot2-frayer-clear-confirm]').check();await family.locator('[data-pilot2-frayer-clear]').click();
  for(let i=0;i<4;i++)await expect(page.locator(`[data-pilot2-response="family-one-${i}"]`)).toHaveValue('');await expect(page.locator('[data-pilot2-response="family-two-0"]')).toHaveValue('Keep the other family.');await expect(explanation).toHaveValue('A draft explanation before testing.');
  await one.selectOption('family-three');await expect(one).toHaveValue('family-three');await expect(two).toHaveValue('family-two');await page.reload();await expect(one).toHaveValue('family-three');await expect(two).toHaveValue('family-two');await expect(page.locator('[data-pilot2-response="family-two-0"]')).toHaveValue('Keep the other family.');
  const oversized='Long current explanation: '+ 'x'.repeat(260);await testButton.click();await explanation.fill(oversized);await expect(page.locator('[data-pilot2-work-list]')).toContainText(oversized);
  await page.locator('[data-pilot2-work-category]').selectOption('Frayer');await expect(page.locator('[data-pilot2-work-list]')).not.toContainText(oversized);
  await page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text)=>{window.copied=text;}}});window.print=()=>{window.printed=document.querySelector('[data-pilot2-print-work]').textContent;window.dispatchEvent(new Event('afterprint'));};");
  await page.locator('[data-pilot2-copy-all]').click();const copied=await page.evaluate(()=>(window as any).copied);assert.ok(copied.includes(oversized));assert.ok(copied.includes('Keep the other family.'));await page.locator('[data-pilot2-print-all]').click();const printed=await page.evaluate(()=>(window as any).printed);assert.ok(printed.includes(oversized));assert.ok(printed.includes('Keep the other family.'));assert.equal(await page.locator('body').getAttribute('class'),'');
  if(process.env.BIOLOGY30_FIXTURE_SCREENSHOTS){const directory=process.env.BIOLOGY30_FIXTURE_SCREENSHOTS;await mkdir(directory,{recursive:true});await prediction.fill('A revised prediction.');await testButton.click();for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('[data-pilot2-model]').screenshot({path:path.join(directory,`${type.name()}-model-${width}.png`)});}await page.locator('#family-two').screenshot({path:path.join(directory,`${type.name()}-frayer-390.png`)});}
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise<void>((r,j)=>server.close(error=>error?j(error):r()));}
});
