import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createServer} from 'node:http';import {chromium,expect} from '@playwright/test';import {buildShowcase} from '../deploy-biology30-showcase.js';
test('showcase preserves unit workspaces and separates navigation/save state',async()=>{
 const stage=await mkdtemp(path.join(os.tmpdir(),'biology-showcase-test-'));const {publicRoot,release}=await buildShowcase(process.cwd(),stage);assert.equal(Object.keys(release.entries).length,4);assert.ok(Object.keys(release.files).every(p=>!p.includes('/meta/')&&!p.includes('/raw/')));const config=JSON.parse(await readFile(path.join(stage,'firebase.json'),'utf8'));assert.equal(config.hosting.site,'biology30pilot');
 const server=createServer(async(req,res)=>{try{let rel=new URL(req.url!,'http://local').pathname;if(rel.includes('..'))throw Error('path');if(rel.endsWith('/'))rel+='index.html';const file=path.join(publicRoot,rel);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'} as Record<string,string>)[path.extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end();}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch(),evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-08-showcase';await mkdir(evidence,{recursive:true});
 try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());const base=`http://127.0.0.1:${address.port}`;await page.goto(base+'/#lesson-02');await expect(page.locator('#unit')).toHaveValue('a');let frame=page.frameLocator('#course');await expect(frame.locator('#lesson-02')).toBeVisible();const aField=frame.locator('#lesson-02 textarea').filter({visible:true}).first();const aId=await aField.getAttribute('id');await aField.fill('Synthetic Unit A preview response.');await aField.blur();
 const fixtures:Record<string,{route:string;id:string;text:string}>={};
 for(const unit of ['b','c','d']){await page.locator('#unit').selectOption(unit);frame=page.frameLocator('#course');await expect(frame.locator('#overview')).toBeVisible();const source=JSON.parse(await readFile(`projects/resources/biology30-production/v1/units/unit-${unit}/pilot2-practice.json`,'utf8')),item=source.items.find((x:any)=>x.role==='guided'&&x.kind==='constructed'&&!x.dataset);const text=`Synthetic teacher-preview test for ${unit}: 3′ → 5′; résumé.`;fixtures[unit]={route:item.routeId,id:item.id,text};await frame.locator(`[data-page-target="${item.routeId}"]`).first().click();const field=frame.locator(`[data-pilot2-response="${item.id}"]`);await expect(field).toBeVisible();await field.fill(text);await field.blur();await expect(page).toHaveURL(new RegExp('#'+unit+'/'+item.routeId));}
 for(const unit of ['b','c','d']){await page.locator('#unit').selectOption(unit);const f=fixtures[unit];await expect(page.frameLocator('#course').locator(`[data-pilot2-response="${f.id}"]`)).toHaveValue(f.text);await expect(page).toHaveURL(new RegExp('#'+unit+'/'+f.route));}
 await page.reload();await expect(page.locator('#unit')).toHaveValue('d');await expect(page.frameLocator('#course').locator(`[data-pilot2-response="${fixtures.d.id}"]`)).toHaveValue(fixtures.d.text);
 await page.locator('#unit').selectOption('a');await expect(page.frameLocator('#course').locator('#lesson-02')).toBeVisible();await expect(page.frameLocator('#course').locator(`[id="${aId}"]`)).toHaveValue('Synthetic Unit A preview response.');await page.evaluate(()=>history.back());await expect(page.locator('#unit')).toHaveValue('d');
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390)await expect.poll(async()=>{const b=await page.frameLocator("#course").locator("#course-sidebar").boundingBox();return b?b.x+b.width:0;}).toBeLessThanOrEqual(1);await page.screenshot({path:`${evidence}/showcase-${width}.png`});}
 const fresh=await browser.newPage();await fresh.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await fresh.goto(base+'/#c/c-topic-transcription');await expect(fresh.locator('#unit')).toHaveValue('c');await expect(fresh.frameLocator('#course').locator('#c-topic-transcription')).toBeVisible();await fresh.close();
 await writeFile(`${evidence}/browser-results.json`,JSON.stringify({status:'passed',unitSwitches:true,unitResponsesPreserved:true,reload:true,back:true,legacyALink:true,freshDirectLink:true,widths:[1440,390],externalProviders:'blocked; no playback claim',entries:release.entries},null,2)+'\n');
 }finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));await rm(stage,{recursive:true,force:true});}
});
