import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from '@playwright/test';

test('BCD content fills the space beside expanded/collapsed navigation and after mobile resize',async()=>{
 const root=process.cwd(),evidence='projects/resources/biology30-production/v1/pilot2/verification/2026-09-07-sidebar-content-width';await mkdir(evidence,{recursive:true});
 const server=createServer(async(req,res)=>{try{const match=/^\/([bcd])\/(.*)$/.exec(decodeURIComponent(new URL(req.url!,'http://localhost').pathname));if(!match||match[2].split('/').includes('..'))throw Error('Invalid path');const relative=match[2]||'index.html',body=await readFile(path.join(root,`projects/biology30-unit-${match[1]}/workspace`,relative));res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.ttf':'font/ttf'} as Record<string,string>)[path.extname(relative)]??'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address==='object');const browser=await chromium.launch();let checks=0;
 try{for(const unit of ['b','c','d']){const page=await browser.newPage({viewport:{width:1920,height:1000}});await page.goto(`http://127.0.0.1:${address.port}/${unit}/`);const check=async()=>{const m=await page.locator('.main').evaluate(n=>{const box=n.getBoundingClientRect(),style=getComputedStyle(n),frame=n.querySelector('.course-frame')!.getBoundingClientRect();return{available:box.width-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),width:frame.width,left:frame.left,expectedLeft:box.left+parseFloat(style.paddingLeft),overflow:document.documentElement.scrollWidth>innerWidth+1};});assert.ok(Math.abs(m.width-m.available)<2,JSON.stringify(m));assert.ok(Math.abs(m.left-m.expectedLeft)<2,JSON.stringify(m));assert.equal(m.overflow,false);checks++;return m.width;};
 for(const width of [1920,1440,1024]){await page.setViewportSize({width,height:1000});const open=await check();await page.getByRole('button',{name:'Collapse course navigation',exact:true}).click();await expect(page.locator('body')).toHaveClass(/sidebar-collapsed/);const closed=await check();assert.ok(closed>open+100,'content must gain the space released by navigation');for(const route of ['all-my-work','core-vocabulary','video-library','textbook']){await page.locator(`.course-nav a[href="#${unit}-${route}"]`).evaluate((n:HTMLAnchorElement)=>n.click());await check();}if(width===1920)await page.screenshot({path:`${evidence}/${unit}-collapsed.png`});await page.getByRole('button',{name:'Expand course navigation',exact:true}).click();assert.ok(Math.abs(await check()-open)<2);}
 await page.getByRole('button',{name:'Collapse course navigation',exact:true}).click();for(const width of [720,390]){await page.setViewportSize({width,height:900});await check();await page.getByRole('button',{name:'Open course menu',exact:true}).click();await expect(page.locator('.sidebar')).toHaveClass(/is-open/);await page.keyboard.press('Escape');await expect(page.locator('.sidebar')).not.toHaveClass(/is-open/);await check();}await page.close();}
 console.log(`${checks} frame-width/position/overflow checks passed across B/C/D`);
 }finally{await browser.close();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});
