import assert from "node:assert/strict";
import { mkdtemp,mkdir,readFile,writeFile,rm,copyFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { repoRoot } from "../lib/paths.ts";
import { captureStandardsCheckpoint,decideStandardsCandidate,resolveStandard,readStandardsQueue } from "../lib/course-standards.ts";
import { checkStandardLesson,checkStandardHtml,renderStandardLesson,starterLesson,type Lesson } from "../lib/standard-lesson.ts";
import { createCodexStudioCourse } from "../lib/codex-course.ts";
import { findStorageKeysInScriptSources,buildScormBridgeScript } from "../lib/scorm.ts";
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'canvas-standards-'));await mkdir(path.join(root,'config/course-standards'),{recursive:true});await copyFile(path.join(repoRoot,'config/course-standards/v1.json'),path.join(root,'config/course-standards/v1.json'));return root;}
import { biologyLesson } from "./fixtures/standards-biology.ts";
test('checkpoint deduplicates, stores identities only, and defer/skip never promote',async()=>{const root=await fixture();try{let q=await captureStandardsCheckpoint('biology-synthetic','review','synthetic-review',root);const original=q.candidates[0];q=await captureStandardsCheckpoint('biology-synthetic','review','synthetic-review',root);assert.equal(q.candidates.length,1);assert.equal(JSON.stringify(q).includes('synthetic-review'),false);q=await decideStandardsCandidate({id:original.id,revision:q.revision,decision:'defer'},root);assert.equal(q.releases.length,0);q=await decideStandardsCandidate({id:original.id,revision:q.revision,decision:'skip'},root);assert.equal(q.releases.length,0);await assert.rejects(decideStandardsCandidate({id:original.id,revision:q.revision,decision:'universal',rule:'targetGrade',value:9},root));}finally{await rm(root,{recursive:true,force:true});}});
test('explicit decisions create immutable scoped releases, reject stale decisions and retain lineage',async()=>{const root=await fixture();try{let q=await captureStandardsCheckpoint('biology-synthetic','review','a',root);await assert.rejects(decideStandardsCandidate({id:q.candidates[0].id,revision:999,decision:'universal',rule:'targetGrade',value:9},root));await assert.rejects(decideStandardsCandidate({id:q.candidates[0].id,revision:q.revision,decision:'universal',rule:'targetGrade',value:2},root));q=await decideStandardsCandidate({id:q.candidates[0].id,revision:q.revision,decision:'universal',rule:'targetGrade',value:9},root);const v2=JSON.stringify(q.releases[0]);q=await captureStandardsCheckpoint('biology-synthetic','review','b',root);q=await decideStandardsCandidate({id:q.candidates[1].id,revision:q.revision,decision:'family',rule:'maxParagraphWords',value:80},root);assert.equal((await resolveStandard(root,'new-biology','biology')).rules.maxParagraphWords,80);assert.equal((await resolveStandard(root,'new-english','english')).rules.maxParagraphWords,120);q=await captureStandardsCheckpoint('biology-synthetic','review','c',root);q=await decideStandardsCandidate({id:q.candidates[2].id,revision:q.revision,decision:'course-specific',rule:'targetGrade',value:8},root);assert.equal((await resolveStandard(root,'biology-synthetic','biology')).rules.targetGrade,8);assert.equal((await resolveStandard(root,'new-biology','biology')).rules.targetGrade,9);assert.equal(JSON.stringify(q.releases[0]),v2);assert.equal(q.releases[1].parent,'outreach-v2');}finally{await rm(root,{recursive:true,force:true});}});
test('exclusive writer lock protects concurrent work without overwriting',async()=>{const root=await fixture();try{await writeFile(path.join(root,'config/course-standards/promotion-queue.json.lock'),'external writer');await assert.rejects(captureStandardsCheckpoint('biology-synthetic','review','d',root),/EEXIST/);assert.equal((await readStandardsQueue(root)).candidates.length,0);}finally{await rm(root,{recursive:true,force:true});}});
test('fresh Biology course inherits actual starter, blueprint, checks and pinned provenance without example-course input',async()=>{const root=await fixture();try{await writeFile(path.join(root,'package.json'),JSON.stringify({scripts:{'course:doctor':'node -e "process.exit(0)" --',verify:'node -e "process.exit(0)" --'}}));const standard=await resolveStandard(root);assert.deepEqual(checkStandardLesson(biologyLesson,standard),[]);assert.ok(checkStandardLesson(starterLesson('Draft'),standard).some(e=>e.includes('Unfilled')));const broken=structuredClone(biologyLesson);delete broken.sections.guided.purpose;assert.ok(checkStandardLesson(broken,standard).some(e=>e.includes('purpose')));const long=structuredClone(biologyLesson);long.sections.explanation.text='word '.repeat(121);assert.ok(checkStandardLesson(long,standard).some(e=>e.includes('ceiling')));const result=await createCodexStudioCourse({repoRoot:root,slug:'biology-synthetic',title:'Biology feedback lesson',courseCode:'Biology 30',summary:'Synthetic inheritance validation.',lesson:biologyLesson});const html=await readFile(result.workspaceEntry,'utf8');assert.match(html,/data-standard="outreach-v1"/);assert.deepEqual(checkStandardHtml(html,standard),[]);assert.ok(checkStandardHtml(html.replace("data-lesson-purpose", "missing-purpose"),standard).some(e=>e.includes("purpose")));for(const stage of standard.blueprint)assert.ok(html.includes(`data-lesson-stage="${stage}"`));const manifest=JSON.parse(await readFile(result.manifestPath,'utf8'));assert.equal(manifest.courseStandard.id,'outreach-v1');assert.ok(manifest.courseStandard.fingerprint);assert.equal(JSON.parse(await readFile(path.join(result.projectRoot,'meta/course-standard.json'),'utf8')).id,'outreach-v1');const script=await readFile(path.join(result.projectRoot,'workspace/course.js'),'utf8');assert.match(script,/Saved on this device/);assert.ok(manifest.googleHosted.trackedStorageKeys.includes('canvas-standard:biology-synthetic'));const bridge=buildScormBridgeScript({projectSlug:'biology-synthetic',storageKeys:manifest.googleHosted.trackedStorageKeys,version:'2004'});assert.match(bridge,/canvas-standard:biology-synthetic/);assert.match(bridge,/cmi.suspend_data/);assert.match(await readFile(path.join(result.projectRoot,'workspace/styles.css'),'utf8'),/max-width:700px/);assert.equal((await readStandardsQueue(root)).candidates.length,0);}finally{await rm(root,{recursive:true,force:true});}});
