// Uses the existing chapter word IDs, state and Frayer controls.
let displayedWord=C.words[0].id,frayerMarker=null;
function wordDetails(w){return `<p class="eyebrow">${esc(C.lessons[w.lesson-1].title)}</p><h2>${esc(w.term)}</h2><section><p class="section-label">Meaning</p><p>${esc(w.meaning)}</p></section><section><p class="section-label">${w.whatItDoes?'What it does':'Example'}</p><p>${esc(w.whatItDoes||w.example)}</p></section><section><h3>Important distinction</h3><p>${esc(w.importantDistinction||w.confusion)}</p></section>${w.aliases.length?`<details><summary>More about this word</summary><p>Related wording: ${w.aliases.map(esc).join(', ')}.</p></details>`:''}`;}
function showReaderWord(id){displayedWord=id;const w=word(id);$('[data-biology-word-details]').innerHTML=wordDetails(w)+`<section class="frayer"><p class="section-label">Frayer model</p><h3>${esc(w.term)}</h3>${S.frayers[id]?'<p>Your selected word’s writing is below.</p>':`<p>Choose any eight words. Choosing opens an empty Frayer; it does not fill in your answers.</p><button type="button" data-add-frayer="${id}">Choose this word</button>`}</section>`;$$('[data-biology-select-word]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.biologySelectWord===id)));if(S.frayers[id]){activeWord=id;renderFrayers();}}
function filterWordIndex(){const q=norm($('[data-vocab-search]').value),topic=$('[data-vocab-topic]').value;let n=0;$$('[data-word-card]').forEach(el=>{const w=word(el.dataset.wordCard);el.hidden=Boolean((q&&!norm(w.term+' '+w.meaning).includes(q))||(topic!=='all'&&String(w.lesson)!==topic));if(!el.hidden)n++;});$$('.word-category').forEach(s=>s.hidden=![...s.querySelectorAll('[data-word-card]')].some(b=>!b.hidden));$('[data-vocab-count]').textContent=`${n} matching terms`;}
function restoreFrayerHome(){if(frayerMarker){const editor=$('[data-frayer-editor]');frayerMarker.replaceWith(editor);frayerMarker=null;}}
function showVocabularyPopup(id){restoreFrayerHome();const w=word(id);openDialog(w.term,`<label>Core Vocabulary<select data-popup-word>${C.words.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(x.term)}</option>`).join('')}</select></label><article data-biology-word-details>${wordDetails(w)}</article><details class="popup-frayer"><summary>My Frayer</summary><div data-popup-frayer>${S.frayers[id]?'':`<p>Choose this word to write your own Frayer.</p><button type="button" data-add-frayer="${id}">Choose this word</button>`}</div></details><p><a href="#core-vocabulary" data-dialog-route>Open Core Vocabulary</a></p>`,'bio-vocabulary');if(S.frayers[id]){activeWord=id;renderFrayers();const editor=$('[data-frayer-editor]');frayerMarker=document.createComment('Frayer home');editor.before(frayerMarker);$('[data-popup-frayer]').append(editor);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-biology-select-word]');if(b)showReaderWord(b.dataset.biologySelectWord);const choose=e.target.closest('[data-add-frayer]');if(choose){showReaderWord(choose.dataset.addFrayer);if(dialog.open&&dialog.classList.contains('bio-vocabulary')){const trigger=modalTrigger;showVocabularyPopup(choose.dataset.addFrayer);modalTrigger=trigger;}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-popup-word]')){const id=e.target.value,trigger=modalTrigger;showVocabularyPopup(id);modalTrigger=trigger;}});
// The portable HTML uses the embedded PDF for its inline library as well.
if(location.pathname.endsWith(`Biology30_Chapter${C.chapter}.html`)){const url=URL.createObjectURL(new Blob([Uint8Array.from(atob($('#textbook-data').textContent.trim()),c=>c.charCodeAt(0))],{type:'application/pdf'}));$('[data-library-textbook]').src=url+'#page=1';$('[data-library-fullscreen]').href=url;$('[data-library-download]').href=url;}
showReaderWord(displayedWord);
