// Authored narrative replacements. Original documents/controls are retained by the assembler.
module.exports={
'ce1-01':{
foundation:[
['h3','How do you know what you might be good at?'],
['p','A friend sees something you have made and says, “You should do that for a living.” The suggestion might be encouraging, but what makes it useful? Enjoying a task, doing it well and wanting the conditions that come with it are three different things. In this lesson, we will learn how to turn an experience into a reason to investigate a kind of work.'],
['h3','Look for three different clues'],
['p','An interest is something you enjoy or want to explore. A skill is an ability you can demonstrate through an action. A work value is something that matters to you about working, such as having variety or knowing when the day will finish. These clues belong together in a career decision, but each answers a different question. “I like drawing” does not show how well I explain an idea with a drawing.'],
['p','A career goal describes a direction for work or learning. A life goal describes what you want your wider life to support. Someone might want to investigate creative work and also keep regular time for activities outside work. A promising direction should be examined against both goals. We are looking for a next step that makes sense, rather than asking a short school experience to decide an entire future.'],
['h3','Start with something that actually happened'],
['p','Suppose a learner rewrites confusing club directions and two readers can then follow them without help. The rewritten directions are an action; the readers managing without help are a result. Together, they provide evidence for some skill in explaining information. Saying “an excellent communicator” gives a label without showing a reader why it fits. Naming the action and result makes the claim open to examination.'],
['p','The size of the claim matters too. One set of successful directions does not establish that the learner can explain every subject to every audience. That limit leaves room for learning while preserving the useful evidence. Our method will be to describe an action and result, identify a possible skill, explain the limit, then ask a question about work that could use the skill.'],
['p','We will begin with Jordan’s notes from a poster and a science display. I will show how the poster note becomes a short evidence card: a written explanation, not a card you need to download. You will use the display note for supported practice. Then you will use a different person’s experiences to write your final strengths-and-goals response in three fields. The page supplies the evidence for both people.'],
['p','As you read, keep asking two questions: “What did this person do?” and “What do they want work to support?” The answer to the first can support a skill claim. The answer to the second helps decide what to investigate. You will not need paid employment, an account or a personal survey result to practise this distinction. Let’s meet Jordan and look at the notes.']
],
orientation:[
'Jordan likes making things look clear. After seeing Jordan’s school poster, a friend suggests graphic design. Jordan is interested, but wants to examine the experience behind that suggestion. The question we will carry through the first part of the lesson is: what does Jordan’s work give us a reason to investigate?',
'Jordan’s notebook records two school tasks, the actions taken and what happened afterwards. The reflection note adds enjoyment, difficulties and goals. Read both kinds of information before making a judgement. We will need the successful actions and the concerns; one should not erase the other.',
'You will first read the notebook and try a short reading check. We will then connect its details to the method and a completed poster response. Supported practice uses the science display. The independent task introduces Amina and a different set of notes, so your final answer will use her evidence rather than reuse Jordan’s.',
'Your practice and final responses save in their own fields. At each check, try an answer, read its explanation and revise if needed. For writing, the comparison model shows how evidence can support an answer; it is available when you need help. At the end, you will review your final response and mark the lesson complete.'
],
caseGuide:[
'Use the notebook’s columns as a reading path. “What needed doing” explains the problem; “What Jordan did” identifies Jordan’s contribution; “What happened afterwards” reports the result. In the poster row, look for the change made to help the readers. In the display row, keep Jordan’s organizing actions separate from the group’s completed work.',
'After the table, read the reflection as Jordan’s account of what felt enjoyable or tiring and what matters in future work. A preference for predictable hours is important, but it does not prove a skill or establish any occupation’s hours. The reading check asks you to identify an observable action in the notebook, so return to that column before choosing.'
],
method:[
['h3','Read what Jordan did, then read what Jordan wants'],
['p','We now have more than a friend’s opinion. In the poster row, two classmates could not find essential information. Jordan changed the layout and asked them to check it. That sequence lets us connect a specific action to a reported result. The reflection adds that Jordan enjoyed deciding which information came first and improving the draft after feedback. Enjoyment gives us a reason to keep exploring; the action gives us evidence to examine.'],
['p','The science display adds a complication worth keeping. Jordan made a checklist and arranged a check-in, but found repeated follow-up tiring. A person can be able to organize a task and still dislike part of the work. If we record only the successful group result, we lose a useful question about how often a future role would require chasing incomplete work.'],
['p','The schedule note answers a third question. Jordan wants reasonably predictable hours and regular time outside work. This is a work value connected to a life goal. It is not a claim that Jordan has already organized a workplace or that graphic design provides predictable hours. We will use it to ask about conditions in work that might use Jordan’s strengths.'],
['h3','Give the reader enough detail to judge the claim'],
['p','A claim is a statement you want someone to accept. Before writing “Jordan has some skill in organizing visual information,” ask what the reader could check. The problem, layout change and classmates’ response give that statement a basis. The result need not be a prize or a grade: readers finding the information is useful evidence of what changed.'],
['p','Ownership of the action matters. Jordan organized the display check-in; the group found and completed the missing caption. “Jordan completed everyone’s work” would add a contribution the notebook never reports. Describe Jordan’s part in the team result. This keeps a truthful claim useful without making the person responsible for everything the team did.'],
['h3','Use an inventory as a starting suggestion'],
['p','An interest or strengths inventory organizes a person’s answers to questions about themselves. If it suggests creative work for Jordan, it tells us something about the reported answers. It does not independently establish professional skill. We can test the suggestion against the poster evidence and ask whether the working conditions would fit Jordan’s goals. A disagreement between an inventory and experience becomes a question to investigate. No inventory account is needed here.'],
['h3','Carry a skill into a new question'],
['p','A transferable skill is one that may be useful in another setting. Organizing a poster could provide a starting point for organizing instructions or explaining information to a customer. It does not establish knowledge of professional software, client budgets or workplace deadlines. The next question should connect the action to work without skipping the learning still needed.'],
['p','For Jordan, “How often does visual-communication work involve urgent revisions?” is useful because the answer could affect the schedule preference. “Is design good?” would give us much less direction. A provisional goal is a direction that can change as evidence develops. Jordan can investigate roles using visual explanations while keeping the possibility of changing the plan.'],
['p','Financial goals can become part of that investigation: for example, keeping later training costs within a budget. This lesson does not supply a training price or wage, so we cannot decide affordability yet. We are establishing a direction and the questions that later evidence would need to answer. Next, use the inventory check to test that distinction, then watch or read how values can be influenced.']
],
workedBefore:[
'Let’s build the poster response together. Begin with the reader’s problem: the time and location were hard to find. That context explains why enlarging and moving information mattered. If I began with “Jordan is creative,” the reader would have to guess what Jordan had done.',
'Next I connect the action to the result. Jordan changed the layout, reduced decorative text and asked the same classmates to check it. Both then found the information without help. I can therefore describe some skill in organizing visual information and responding to feedback. I keep “some skill” because one school task gives a narrower basis than repeated professional work.',
'The final step connects that evidence to Jordan’s goals. Visual communication is a direction worth investigating. The preference for regular time outside work gives us a question about revisions and deadlines. Notice that the work value shapes the question; it is not added to the skill claim as if it were an ability. Read how those parts fit together in the completed response below.'
],
workedAfter:[
'The completed response gives a reader a path from an observed change to a possible direction. It also says what has not been established: professional design expertise. That boundary does not cancel the useful evidence. It identifies the difference between a reason to explore and a qualification to claim.',
'You will now keep Jordan’s goals but use the science-display row. Look for Jordan’s part in organizing the shared task, the group’s result and the reflection about follow-up. Your three short practice notes will use the same reasoning with this different experience.'
],
practiceBefore:[
'We have tested the poster suggestion; now investigate whether the display gives another useful clue. The person and goals stay the same. The evidence changes to a team task, which makes it especially important to distinguish Jordan’s action from what the group finished.',
'First try Choose a supported claim and use its check to examine your choice. Then use Action and result to explain what Jordan contributed and what happened. In Skill and limit, say what that suggests without claiming Jordan did every part. In Next question linked to a value, use the tiring follow-up or schedule preference to ask something that could change the direction.',
'Your notes can be brief. Their job is to make the reasoning visible before you tackle the independent case. If you are unsure, use the first-step hint or comparison model; compare the relationship between evidence and claim, then revise your own fields. Different wording is expected.'
],
independentBefore:[
'You have practised with one person’s two experiences. The next response uses Amina, whose interests and actions are different. The method stays the same: describe actions and results, make supported skill claims, keep their limits, and connect possible work directions to goals.',
'Amina’s workshop note includes help with tool selection. Keep that detail when interpreting the successful check: useful observation and explanation do not establish independent repair competence. The game note gives another kind of evidence about explaining a task. Read both rows, then use the goal note and role sketches to decide which questions would help Amina investigate further.',
'The three final fields divide one response into manageable parts. The first needs both experiences and their results; the second connects both work directions to Amina’s goals and values; the third gives a question for each direction. A useful question should have an answer that could change the plan. You do not need to invent an employer’s hours or qualifications.'
],
closing:[
'We began with a friend’s career suggestion. You can now give such a suggestion a stronger foundation: an action and result, a possible skill, an honest limit and a question tied to the person’s goals. Your Amina response should make each of those connections visible before you sign off.',
'The next lesson takes the investigation further. Once there is a direction worth exploring, you need to find out what that kind of work actually involves. We will read occupation profiles and employer notices while keeping duties, working conditions and preparation separate.'
],
corrections:[['At the workshop, Amina compared wheel movement around an adjustment and explained the change.','At the workshop, Amina compared wheel movement around an adjustment and explained the change; the wheel then turned without rubbing during the workshop check.']]
},
'ce1-02':{
foundation:[
['h3','A career title sounds interesting. What would the work involve?'],
['p','You might like a title such as graphic designer and still be unsure what the person does during a working day. A career page can help, but it may contain more information than you need at first. How do you find the parts that answer your question, and avoid using one sentence as a promise about every job? That is the reading task for this lesson.'],
['h3','Choose the document that answers your question'],
['p','A job is a particular position with an employer. An occupation groups work with similar duties. A career is a longer path that may include several jobs, learning and other life roles. An occupation profile describes a kind of work across workplaces. A job posting advertises one opening. A broad description and a particular opening can both be useful, as long as we keep their different purposes visible.'],
['p','Canada’s National Occupational Classification, or NOC, organizes occupations into groups with identifying codes. A code helps you check whether two records cover the same group. It does not rank someone’s ability or make every job identical. We will keep that group information with the source when comparing occupations later in the lesson.'],
['h3','Read for work, conditions and preparation'],
['p','A duty answers “What would I do?” A working condition answers “When, where or under what demands?” Preparation describes the education, experience or other evidence used to enter the work. For example, “prepare notices” names a duty, “evening shifts” a condition and “provide examples of your writing” requested preparation. An appealing task does not answer the question about evening hours.'],
['p','The strength of the wording matters. “Some employers prefer experience” does not say every applicant must have it. “Required” identifies a stated condition. We will read the words around a fact before turning it into a claim. We will also keep the place, section date and retrieval date attached: when a page was read and when its content was revised are different facts.'],
['p','Jordan’s poster experience gives us the first research question. I will show how to use a Graphic Designer profile and a fictional employer notice to investigate duties and hours. You will then read the preparation statements with support. Your final task introduces Nia and a second occupation, Web Designer, so you can practise making a fair comparison.'],
['p','Your final response will explain evidence for both occupations and recommend a direction for Nia to investigate. The records are provided beside the response fields; live website reading is optional. Begin by asking which field would help answer the person’s question. We will make that choice before collecting facts, rather than assuming every number on a page has equal importance.']
],
orientation:[
'In the previous lesson, Jordan’s poster provided a reason to explore visual-communication work. It did not establish professional skill or tell us the hours that work would involve. Now we will use a different kind of evidence: records describing work, working conditions and preparation.',
'Jordan’s question brings two concerns together: could the work use an interest in visual problem solving, and could its conditions fit a preference for predictable finishing times? Read the profile and the particular employer notice with both concerns in mind. A match in one field can coexist with a concern in another.',
'The completed research note will demonstrate a careful conclusion. Supported practice asks you to interpret the employer’s preparation statement. The independent comparison uses Nia’s interests and two profiles, so the method transfers while the person and evidence change. Your writing may differ from the model if you explain the connection to the records.'
],
caseGuide:[
'In the profile table, begin with Duties and Working conditions. The first describes tasks; the second describes patterns and possible demands. Then look at Preparation. Classification and Dates help you identify the source, rather than describing what Jordan would do. The first check asks for a task, so look for the work itself.',
'When you reach Prairie Print Studio’s notice, notice its narrower purpose. It describes the duties, hours and application evidence for one fictional opening. Compare its actual wording with the broad profile. A possible Saturday shift is a condition for this notice; it is not a statement about every designer.'
],
method:[
['h3','Read the useful sentence before making the claim'],
['p','Jordan wants to know about visual problem solving. The profile’s duties include discussing project needs, developing visual solutions and preparing work for approval. Those tasks give the interest a connection to an occupation. They do not establish that Jordan has already done them in a workplace. We are deciding whether the direction deserves investigation.'],
['p','A career cluster can group related possibilities for exploration, such as visual-communication work. A NOC group has a more formal information-organizing purpose. Keeping the code and group label prevents us from combining numbers about different occupations simply because both titles involve design. It also reminds us that the Graphic Designer group includes illustrators and related work.'],
['h3','Ask a separate question about the schedule'],
['p','For predictable finishing times, the duties field is not enough. I move to Working conditions. It says weekday work is usual and deadlines can bring overtime or weekend work. That gives a pattern and an exception. Removing the exception would create a much stronger claim than the record supports.'],
['p','Now compare the fictional notice: usual weekday hours are stated, together with a possible Saturday shift before the festival. The profile and notice can both be accurate. They describe different levels of detail. We should ask how often busy periods change the hours of a particular opening, rather than average the statements or choose the more convenient one.'],
['h3','Separate a preparation summary from an entry decision'],
['p','A credential is a formal record of qualification. A portfolio is a selected collection of work showing what someone can do. The profile says design education is common and a strong portfolio important; it does not decide admission to a program. The employer notice asks for three layout examples and describes paid experience as helpful. That wording lets us distinguish requested evidence from an experience preference.'],
['p','A person may have relevant school examples without a paid studio job. A truthful portfolio explains the task, the person’s contribution and the work produced. It should not change a school activity into professional employment. Whether the examples meet this opening’s expectations still depends on the kinds of layout and presentation requested.'],
['h3','Keep the source and its limits with the answer'],
['p','The three-pass reading method is useful here: locate the field that answers the question, explain its fact in your own words, then state what it supports and leaves open. For example, the overtime statement supports asking about scheduling; it does not support “every design job always ends late.”'],
['p','The record’s March 22, 2023 section date and September 28, 2026 retrieval date also need different labels. Retrieval tells us when the page was read. It does not make every field newly updated. The supplied record is enough for this exercise; a real future decision would need current information relevant to its particular opening.'],
['p','The comparison strip below organizes that reading process. Read each row from question to starting evidence, then to the remaining uncertainty. It shows why duties, conditions and preparation each earn a place in the research note. The worked example that follows will combine those parts into an explanation for Jordan.']
],
workedBefore:[
'Let’s answer Jordan’s question without deciding more than the evidence allows. I begin with the duties because the question mentions an interest in visual problem solving. Developing visual solutions relates to that interest. This is my reason to keep graphic design under consideration, not proof that Jordan is qualified for every design task.',
'Next I check the other part of the question: predictable finishing times. Both records mention possible work beyond the usual weekday pattern. Prairie Print Studio makes the condition more specific by naming a possible Saturday shift. I therefore keep the schedule concern in the conclusion even though the duties look promising.',
'I attach the profile’s place and dates so a reader can find the basis of the claim. Finally, I turn the remaining gap into a precise question about hours and portfolio expectations. The completed note below joins an encouraging connection to those unresolved points. Notice how “worth investigating” follows from the evidence without becoming a job offer.'
],
workedAfter:[
'If we wrote “this job definitely fits,” we would skip the hours and preparation. If we wrote “no designer has regular hours,” we would turn a possibility into a universal statement. The example avoids both by naming what interests Jordan and what still needs checking.',
'You will now investigate the preparation statement yourself. Keep the same documents and person. Focus on the difference between the three layout examples requested and the previous paid experience described as helpful.'
],
practiceBefore:[
'Jordan still needs to decide how to prepare truthful evidence for an application. The notice contains two statements about preparation, and they have different strengths. Your practice response will explain that difference before proposing one unresolved question.',
'Try Classify the experience statement and check your choice. Then use Evidence and source to name the relevant wording and its document, What Jordan can conclude to explain its meaning, and One unresolved preparation question to identify something the notice leaves open. You are drafting a question, not contacting an employer.',
'Use the comparison to check whether your conclusion has become stronger than the notice. Requested layout examples can guide preparation; a preference for experience cannot be rewritten as a universal rule, and neither statement guarantees selection.'
],
independentBefore:[
'The final comparison introduces Nia. Her interest in testing websites gives you a new question, alongside her interest in arranging images and text. Use her goals rather than carry Jordan’s priorities into this answer. The method is still to examine duties, conditions, preparation and source limits.',
'The Graphic Designer record is repeated so you can compare it directly with Web Designer. Read corresponding fields together. A difference in duties may suggest which direction to investigate first; a shared uncertainty about hours may remain relevant to either choice. The NOC codes identify different groups, so keep their source information separate.',
'Your first two fields explain the evidence for each occupation. The third gives a provisional direction and specific questions that could change it. There is no single compulsory career choice: prioritizing either occupation can be reasonable if you connect it to Nia’s interests and handle preparation and schedule limits. The records do not establish a current opening or guaranteed admission.'
],
closing:[
'An occupation title is now a starting point for better questions. You can find the duties that relate to an interest, check the conditions that affect a goal, and distinguish preparation summaries from actual entry requirements. Your Nia comparison should show those connections and their sources before you sign off.',
'The next lesson investigates how someone could prepare for a particular role. We will compare training routes, including entry conditions, time and full listed costs. The careful reading you have practised here will help distinguish a promising title from a route that actually supports the intended work.'
]
},
'ce1-04':{
opening:[
['h3','Does “good job prospects” mean there is a job nearby?'],
['p','A report describes promising work across Alberta, but a search near home finds only a few advertisements. It is tempting to think one source must be wrong. Before deciding, ask what each one is measuring. A forecast, a count of people already employed and a list of advertised openings can tell us different things about the same broad area of work.'],
['p','Labour-market information describes work and workers: occupations, employment, vacancies and the conditions affecting them. A claim is a statement drawn from that information, such as “this occupation has favourable prospects.” Its usefulness depends on the measure, group, place and time it describes. We will learn to read those parts before applying them to a person’s choices.'],
['p','In the last lesson, a workable preparation route still did not guarantee a place or a job. This lesson asks what evidence of opportunity can add to a career decision. An employment figure can help describe a field, but it does not by itself settle a learner’s entry requirements, travel limits or living costs.'],
['p','First I will explain how to label the information. We will then meet Noor, who wants to investigate database work within a stated travel area. I will show how to compare a provincial profile record with a local search log. Supported practice changes the search date; your final response introduces Ellis and two design directions.'],
['p','Your final product has three fields: notes on each official record and an evidence-based next step for Ellis. The lesson reproduces the records and clearly labels the invented searches. You do not need to carry out a job search, contact an employer or find a live website figure. Start with the explanation below, then test it against Noor’s documents.']
],
method:[
['h3','Ask what a number is counting'],
['p','Imagine reading “500” beside an occupation name. Five hundred workers already employed would tell us something different from five hundred unfilled positions. The unit and field heading make the number useful. An employment count concerns people already working in a stated group and place. A vacancy is an unfilled position. An advertisement is a way a position may be publicized; a search captures the advertisements it finds, which is not automatically every vacancy.'],
['h3','Read a forecast as an estimate over a period'],
['p','A forecast estimates what may happen during a specified period. A favourable label is a summary of that estimate, not a count of positions available to one learner. We will see a label called Hot in a dated record. Its name is not a personal recommendation. To interpret it, retain the forecast period and the occupational group to which it belongs.'],
['p','The National Occupational Classification, or NOC, organizes work into groups. A group can include related occupations. When the record names database analysts and data administrators, keep the full label; do not narrow the group’s figure to one employer or assume every related role has identical duties and entry conditions.'],
['h3','Give the figure a complete label'],
['p','The scope is what the information covers. For each claim, identify the measure, the occupation or group, the place and the period or date supplied. The employment count we will read is 2,470 employed in Alberta for a named database group. That label prevents us from calling it 2,470 local openings. The nearby log will instead name the search area, boards, search words and date.'],
['p','The dates need their own labels. The source period describes the time covered by particular information, such as a forecast. The section update records when a section was revised. The retrieval date records when someone read the page. A later retrieval does not restart a three-year forecast, and an older section update does not establish the collection year of every number on the page.'],
['p','For Noor’s profile record, the forecast period is 2024–2026, the section update shown is April 8, 2022 and the retrieval is September 28, 2026. These can be recorded together without making them interchangeable. The record does not supply a separate measurement period for the employment count, so do not invent one.'],
['h3','Connect the evidence to the person’s question'],
['p','A provincial forecast asks a broader question than a local search made on one day. A favourable provincial picture could coexist with few advertisements in a small travel area. We can preserve both observations by explaining their different questions. We cannot subtract the advertisements from an employment count or rank a forecast label as if it were another numerical count.'],
['p','A person’s plans also involve preparation, transport and costs. Knowing which openings were advertised can help identify something to investigate, but the search must record requirements before we can know whether those openings relate to the person’s preparation. Even a confirmed opening would not guarantee selection.'],
['h3','Recognize what wage information would need'],
['p','A wage headline raises another kind of comparison. The cost of living is the expense of meeting everyday needs in a place and situation, including housing and transport. To judge whether an income could cover those needs, the income and expense figures need a compatible time basis. An hourly figure and a monthly rent cannot be compared as though they describe the same unit.'],
['p','The supplied Noor and Ellis records contain no wages or living-cost amounts. That means this lesson cannot settle affordability or the cost of moving. The separate Sam video shows why a provincial median wage is not automatically an entry wage for a local opening. Watch or read it for that measurement distinction, then return to the records used in your own response.'],
['h3','Write a conclusion with a boundary and a next step'],
['p','A conditional conclusion states what the evidence supports now and what might change it. “Continue investigating within the travel limit” is different from predicting a job or dismissing the whole occupation after a small search. A useful next step names the gap: for example, entry requirements for relevant roles or a wider set of employers within the same area.'],
['p','The comparison table below summarizes which question each record can help answer and which it cannot settle. Use it as a reading guide when you meet Noor. Once the records are labelled, we can explain why they may coexist instead of forcing them into an apparent contradiction.']
],
caseGuide:[
'Read Noor’s decision note first: the 20-kilometre limit makes local evidence relevant, and moving is outside the present plan. In the Database Analyst table, distinguish the forecast label from the employment figure. In the search log, find how the search was conducted before treating its results as evidence about the local area.',
'The first reading check asks what 2,470 represents. Return to the employment row and the occupational group. You are identifying the measure, not making a training choice or deciding whether Noor will be hired.'
],
workedBefore:[
'Let’s return to the opening question: must one record be wrong? I first identify what each record can actually describe. The Database Analyst profile gives an Alberta-wide forecast label for 2024–2026 and a separate employment count for the named group. That provides broad context. It does not tell me how many entry openings are inside Noor’s 20-kilometre area.',
'The search log narrows the place and date. Two boards, using two search terms, displayed two distinct open advertisements on September 24. I can state that observation exactly. I cannot use it to count every local vacancy or explain future hiring. The log includes different requirements, so the number alone cannot establish that Noor could enter both roles.',
'Now I connect the evidence to the decision. Noor enjoys this area of work but has not investigated training and is not planning to move. A reasonable conclusion is to keep investigating preparation and reachable entry roles. The completed interpretation below states what is useful, its limits and what could change the plan.'
],
workedAfter:[
'The interpretation keeps the two scales separate. Saying “2,470 jobs are waiting” would change employment into vacancies. Saying “two advertisements prove there is no future” would generalize a narrow search far beyond its date and sources. A careful explanation can recognize local constraints without inventing either guarantee.',
'We have interpreted one local snapshot. In the supported practice, the same search is repeated on a new date. Your task is to describe what changed while keeping the reason for that change separate from the observation.'
],
practiceBefore:[
'Keep Noor’s area, search words and two boards. The new fact is what appears on October 1: no open advertisements were captured. A comparison across two dates is more informative than one snapshot, but it still does not tell us why the earlier advertisements disappeared.',
'Try Which statement does the new log support? before writing your notes. In Observation with scope/date, describe the two captured results using their dates and limits. In What the two searches cannot establish, identify an explanation we do not have. In A useful next comparison, name evidence that could help Noor’s travel-limited investigation.',
'A useful next comparison should add information. Repeating a number without a new source or question does not resolve the gap. You are proposing research within a paper case; no employer contact or outside search is part of this task. Compare your reasoning with the model when you need support, then revise.'
],
independentBefore:[
'The final task applies the same reading method to Ellis, who is investigating graphic design and web design in the fictional city of Lakeford. Noor’s database group and travel radius are no longer the relevant facts. Read Ellis’s two official records and local search log together, while keeping their different measures separate.',
'The table’s 2024–2026 source period refers to the forecast displays. It does not establish when the employment counts were measured. Record the section-update and retrieval dates separately too. The local log reports advertisements captured on September 26 and says requirements were not yet recorded, so those advertisements cannot establish Ellis’s eligibility.',
'The first two fields are record notes, or annotations: short explanations of what each source describes and its limit. The third uses those notes to propose a next step. Explain why the larger employment count, warmer forecast label and local advertisement count cannot be ranked as one measure. You may prioritize an investigation if you give a relevant reason and state what still needs checking before training.'
],
closing:[
'The opening comparison now has an answer: a provincial forecast and a small local search can coexist because they describe different measures, groups, places and dates. A trustworthy conclusion keeps those labels attached and uses uncertainty to form a useful next question.',
'Before finishing Ellis’s response, check that you have interpreted both official records and the local log without predicting selection or personal fit. The next lesson turns preparation into a high-school plan, using stated prerequisites, course offerings and deadlines rather than treating promising opportunity information as a complete route.'
]
}
};
