import json, re, hashlib, datetime
from pathlib import Path
from html import unescape
root=Path('/workspace/shared/ch14_0910')
blind=root/'review-blind-final'; rendered=root/'review-rendered-final'; out=root/'review-reports'

def clean(s):return ' '.join(unescape(re.sub('<[^>]+>',' ',s)).split())
sources={}
page_map={
'09':{'01':2,'02':3,'03':4,'04':4},
'10':{'01':2,'02':2,'03':4,'04':4}}
for l in ['09','10']:
    html=(blind/f'lesson-{l}.html').read_text()
    for m in re.finditer(r'<p\b([^>]*)>(.*?)</p>',html,re.S):
        im=re.search(r'data-canvas-edit-key="(ch14-l\d+-teaching-(\d+)-p(\d+))"',m.group(1))
        if im:
            sid,sec,para=im.groups();page=page_map[l][sec]
            if l=='09' and sec=='02' and para=='4':page=4
            if l=='09' and sec=='04' and para=='4':page=5
            if l=='10' and sec=='02' and int(para)>=3:page=3
            pp=[2,3] if l=='10' and sec=='02' and para=='2' else [page]
            sources[sid]={'file':f'lesson-{l}.html','locator':f'#{sid}','rendered_pages':pp,'visible_text':clean(m.group(2))}
extra={
'L09-W2':('09',5,'#ch14-l09-worked ol li:nth-child(2)','Trace A upstream: weaker inhibition permits FSH/LH stimulation to rise. Trace back to the target: poor follicular responsiveness means more stimulation need not restore maturation or ovulation.'),
'L09-W3':('09',5,'#ch14-l09-worked ol li:nth-child(3)','Locate the change in Model B: an external inhibitory signal is supplied. Trace upstream output: normal FSH/LH stimulation and the LH surge can be suppressed. Responsive ovaries still need the appropriate stimulation to complete the normal sequence.'),
'L10-W2':('10',5,'#ch14-l10-worked ol li:nth-child(2)','Locate the process that can continue: ovulation releases a secondary oocyte at an ovary. Blocking the oviduct does not itself remove that ovarian event.'),
'L10-W4':('10',5,'#ch14-l10-worked ol li:nth-child(4)','Answer the question: no. Removing the pathogen is different from removing established scar tissue. We need separate evidence about the ducts before claiming that the normal route is restored.'),
'L09-FIG':('09',3,'.science-figure img (actual rendered pixels)','Three ovarian boxes read Early follicular phase / Follicles develop, Late follicular phase / Estrogen rises, and After ovulation / Corpus luteum active. The corresponding uterine boxes read Menstrual flow / Part of lining is shed, Rebuilding / Endometrium grows, and Maintenance / Progesterone supports lining. Downward arrows connect each pair. The footer states Flow overlaps early follicular development and Hormone decline after corpus-luteum regression permits the next flow.'),
'L10-FIG':('10',3,'.science-figure img (actual rendered pixels)','Normal sagittal female reproductive anatomy includes clearly legible labels for oviduct, ovary, uterus, cervix and vagina; the image does not show infection, scars, both oviducts as a bilateral frontal pair, or a gamete transport sequence.')}
for sid,(l,p,loc,txt) in extra.items():sources[sid]={'file':f'lesson-{l}.html','locator':loc,'rendered_pages':[p],'visible_text':txt}

records=[]
def task(id,lesson,category,prompt,answer,refs,note,demand,page=None):
    records.append({'id':id,'lesson':lesson,'category':category,'prompt':prompt,'first_attempt_answer':answer,'support_ids':refs,'support_map':note,'cognitive_demand':demand,'prompt_rendered_pages':page,'visible_support_judgment':'Sufficient for this answer within the stated prerequisite; no unseen content used','feedback_status':'Not accessed before freeze','correctness_status':'Ungraded first attempt'})
S=lambda l,sec,p:f'ch14-l{l:02d}-teaching-{sec:02d}-p{p}'
task('ch14-l09-check-mc-1',9,'required_selection','In a functioning control system, reduced ovarian hormone feedback can produce which response?','Increased FSH and LH stimulation',[S(9,2,2)],'The paragraph identifies reduced inhibitory ovarian feedback and explicitly says a functioning anterior pituitary can release more FSH and LH.','Direct recognition of taught relation',[6])
task('ch14-l09-check-mc-2',9,'required_selection','Which statement correctly explains one effect of combined hormonal contraception?','Feedback can reduce the normal LH surge and prevent ovulation',[S(9,4,1)],'The supplied estrogen/progestin signals reduce pituitary stimulation; the paragraph explicitly links LH-surge suppression to prevention of ovulation.','Direct recognition of taught relation',[7])
task('ch14-l09-check-writing-1',9,'required_writing','Explain why low ovarian hormone output and high pituitary hormone output can occur together.','Ovarian hormones normally inhibit the hypothalamus and anterior pituitary. If ovarian output falls, less inhibition reaches a functioning control system, so the anterior pituitary can release more FSH and LH. Reduced inhibin also contributes, especially to higher FSH. The extra stimulation does not guarantee more ovarian output when follicles respond poorly.',[S(9,2,2),S(9,2,3),'L09-W2'],'02-p2 supplies the inhibition → reduced inhibition → higher FSH/LH chain and inhibin qualification; 02-p3 and worked step 2 explain why the weak target response can persist.','Reconstruct a taught causal chain',[7])
task('ch14-l09-check-writing-2',9,'required_writing','Contrast a cycle without pregnancy with early pregnancy in terms of corpus-luteum activity and endometrial support.','Without pregnancy support, the corpus luteum regresses, its progesterone and estrogen output falls, and the functional endometrial lining is shed. In early pregnancy, developing trophoblast releases hCG, which supports the corpus luteum. The corpus luteum keeps supplying progesterone and estrogen, maintaining support for the endometrium rather than following its usual decline.',[S(9,1,2),S(9,1,3),S(9,3,1),S(9,3,2),S(9,3,3)],'01-p2/3 supply the unsupported baseline and shedding; 03-p1/2/3 supply the trophoblast → hCG → corpus luteum → hormones → lining chain.','Compare two explicitly taught causal pathways',[7])
task('ch14-l09-guided-q1',9,'supported','Which signal helps maintain the corpus luteum in early pregnancy?','hCG',[S(9,3,2)],'The paragraph explicitly states that hCG travels in blood and supports the corpus luteum.','Retrieval',[6])
task('ch14-l09-guided-q2',9,'supported','Why does a combined contraceptive pill not protect against an STI?','Changing hormonal feedback does not create a barrier to pathogen transmission',[S(9,4,3)],'The paragraph directly distinguishes altered hormone feedback from a physical barrier to infectious organisms.','Direct recognition',[6])
task('lesson-09-stop',9,'stop','Would low progesterone in one sample prove that ovulation never occurred?','No. One sample only shows that progesterone was low when it was taken. It may have been taken before the usual post-ovulation rise, so the timing and a more complete pattern are needed before interpreting ovulation.',[S(9,1,4)],'01-p4 gives this precise limitation and the pre-rise sampling example.','Apply a stated evidence limitation',[6])
task('lesson-09-new-optional',9,'new_optional','Optional model challenge: hCG is present in early pregnancy, but in a constructed model the corpus luteum cannot respond to it. No other tissue supplies enough progesterone or estrogen to replace that lost output. Would the presence of hCG alone guarantee maintenance of the endometrium? Trace the missing link.','No. hCG is the signal that normally supports the corpus luteum, but the target cannot respond in this model. Therefore the normal link from hCG to continued corpus-luteum progesterone and estrogen output is broken. With no adequate replacement source, the presence of hCG alone cannot guarantee hormonal support of the endometrium.',[S(9,3,2),S(9,3,3),'L09-W2'],'03-p2/3 supply the source–signal–target–output chain; the challenge itself supplies target failure and absence of replacement. Worked step 2 shows that a signal need not restore an unresponsive target.','Near transfer: interrupt an explicitly taught pathway',[5])
task('ch14-source-OBJ_2131183',9,'original_saved_optional','Explain how the hormones in a combined contraceptive pill can reduce the chance of pregnancy. Trace the feedback effect to ovarian activity.','A combined pill supplies an estrogen and a progestin, which has progesterone-like activity. Their feedback on the hypothalamus and anterior pituitary reduces the normal FSH/LH stimulation of the ovaries. Reduced follicular development and suppression of the LH surge make ovulation less likely, so an oocyte is less likely to be available for fertilization.',[S(9,4,1),S(9,4,2)],'04-p1 defines the supplied signals and traces their effect through FSH/LH to follicular development and ovulation. This is a written answer to the saved-response prompt, not a test of saving or persistence.','Reconstruct a taught mechanism',[7])
task('ch14-l10-check-mc-1',10,'required_selection','Which chain best explains one way an STI can reduce fertility?','Infection → inflammation and scarring → disrupted transport',[S(10,2,2),S(10,2,3)],'02-p2 traces infection/PID through inflammation and scar blockage to disrupted meeting or embryo movement; 02-p3 connects this to infertility.','Direct recognition of taught causal chain',[6])
task('ch14-l10-check-mc-2',10,'required_selection','Which comparison is accurate?','Hormonal contraception and STI risk reduction are different functions',[S(10,4,1),S(10,4,2)],'04-p1 states hormonal suppression changes oocyte availability without preventing pathogen exposure; 04-p2 supplies the separate barrier mechanism.','Direct recognition',[6])
task('ch14-l10-check-writing-1',10,'required_writing','Explain how an STI could interfere with reproduction while gamete and hormone production continue.','An infection can cause inflammation and leave scar tissue that narrows or blocks an oviduct. The ovaries may still develop follicles, release an oocyte and produce hormones, but the damaged route can prevent sperm and the oocyte from meeting or interfere with early-embryo movement toward the uterus. Gamete production, hormone production and an open transport pathway are different functions, so damage to one does not require all the others to stop.',[S(10,1,1),S(10,2,1),S(10,2,2),S(10,2,3),'L10-W2'],'01-p1 separates functions; 02-p1 locates ovulation at the ovary; 02-p2/3 explain duct damage and consequences; worked step 2 explicitly preserves ovulation with blocked ducts.','Reconstruct a taught mechanism and distinguish functions',[6])
task('ch14-l10-check-writing-2',10,'required_writing','A student says, “If a method prevents pregnancy, it must prevent STIs too.” Explain the flaw using two different mechanisms.','Preventing pregnancy and reducing infection transmission act on different parts of the process. Combined hormonal contraception can suppress the LH surge and ovulation, reducing the availability of an oocyte, but it does not block exposure to pathogens. An appropriate condom used correctly and consistently is a physical barrier that reduces contact with infectious material and can obstruct sperm passage. It can reduce STI risk, although exposed skin outside its coverage means protection is not absolute.',[S(10,4,1),S(10,4,2)],'04-p1 supplies the hormone-control mechanism and its STI limit; 04-p2 supplies the physical-barrier mechanism and its coverage limitation.','Compare two explicitly taught mechanisms',[7])
task('ch14-l10-guided-q1',10,'supported','Why might the absence of symptoms fail to rule out an STI?','Some infections are asymptomatic',[S(10,1,3)],'The paragraph defines asymptomatic as no obvious symptoms and rejects appearance or lack of discomfort as proof of no infection.','Direct recognition',[5])
task('ch14-l10-guided-q2',10,'supported','Which consequence most directly follows scarring that blocks an oviduct?','Disrupted reproductive-cell transport',[S(10,2,2)],'The paragraph links scar narrowing/blockage to failure of gametes to meet or abnormal embryo movement.','Direct recognition',[5])
task('lesson-10-stop',10,'stop','Would treating an infection necessarily remove all scarring it caused?','No. Removing the pathogen does not necessarily undo established scar tissue. Separate evidence would be needed to know whether the damaged transport route had reopened.',[S(10,3,4),'L10-W4'],'03-p4 explicitly distinguishes treatment of infection from reversing tissue damage; worked step 4 applies this to the ducts.','Apply a stated distinction',[6])
task('lesson-10-new-optional',10,'new_optional','Optional comparison: Model A has open oviducts but no ovulation because the LH surge is suppressed. Model B has normal ovulation but scar tissue blocking both oviducts. Identify the disrupted step in each model. Would removing the infection that caused the old scar tissue necessarily repair either stated problem? Explain.','In Model A the disruption is the hormonal stimulation needed for ovulation, so an oocyte is not released despite open ducts. In Model B ovulation continues, but the blocked oviducts disrupt the normal route for sperm and the oocyte to meet. Removing the infection does not necessarily restore the suppressed LH surge in A and does not by itself show that old scarring has disappeared in B. Neither stated problem is necessarily repaired just by removing the infection.',[S(10,4,1),S(10,2,1),S(10,2,2),S(10,3,4),'L10-W4'],'04-p1 supplies LH-suppression/ovulation; 02-p1/2 separate ovulation from transport; 03-p4 and worked step 4 reject equating pathogen removal with structural repair. The prompt supplies the two model states and gives no basis to infer restoration of the LH surge.','Near transfer: compare control failure with transport failure',[5])

concepts={
'menopause':(9,'Menopause is the end of menstrual cycling associated with declining ovarian follicular activity.','Menopause','Reduced ovarian hormone output can remove some inhibitory feedback, allowing a functioning anterior pituitary to increase FSH and LH rather than making them both low.',[S(9,2,1)],[S(9,2,2),S(9,2,3)]),
'hcg':(9,'hCG is human chorionic gonadotropin, released by developing trophoblast tissue in early pregnancy. It supports the corpus luteum so that its hormone output continues.','hCG','hCG and progesterone are different hormones. Trophoblast releases hCG, which supports the corpus luteum; the corpus luteum releases progesterone, which helps maintain the endometrium.',[S(9,3,1),S(9,3,2)],[S(9,3,3)]),
'hormonal-contraception':(9,'Hormonal contraception uses hormones or hormone-like substances to alter reproductive processes for conception control. In the combined-method example, estrogen and a progestin reduce FSH/LH stimulation and suppress the LH surge to help prevent ovulation.','Hormonal contraception','Preventing pregnancy by altering hormone feedback does not create a barrier to pathogens. A combined contraceptive pill does not protect against STIs.',[S(9,4,1)],[S(9,4,3)]),
'sti':(10,'An STI is a sexually transmitted infection, an infection that can pass through sexual contact.','STI','A person can have an STI without obvious symptoms because some infections are asymptomatic. Absence of symptoms alone cannot rule out infection.',[S(10,1,2)],[S(10,1,3)]),
'pathogen':(10,'A pathogen is an organism or infectious agent capable of causing disease.','Pathogen','A pathogen is an organism or infectious agent capable of causing disease. A reproductive hormone is a chemical message acting on responsive cells, not a pathogen.',[S(10,1,2)],[S(10,1,2)]),
'pelvic-inflammatory-disease':(10,'Pelvic inflammatory disease, or PID, involves inflammation in upper female reproductive structures, often associated with infection. Untreated chlamydia or gonorrhea can spread there and contribute to it.','Pelvic inflammatory disease','Normal ovarian hormones do not protect a duct from infection-related tissue damage. Inflammation and healing can leave scar tissue that narrows or blocks an oviduct even while ovarian function continues.',[S(10,2,2)],[S(10,2,2),'L10-W2']),
'infertility':(10,'Infertility is difficulty establishing a pregnancy due to one or more reproductive factors. For example, damage to a transport pathway can make pregnancy harder to establish.','Infertility','Infertility does not require every gonad to stop making hormones and gametes. Ovarian activity can continue while a scarred oviduct disrupts the route needed for sperm and the oocyte to meet.',[S(10,2,3)],[S(10,1,1),S(10,2,2),'L10-W2']),
'ectopic-pregnancy':(10,'An ectopic pregnancy is a pregnancy in which implantation occurs outside the normal uterine site.','Ectopic pregnancy','Normal fertilization in an oviduct is not an ectopic pregnancy. The defining difference is implantation outside the normal uterine site, not the normal location of fertilization.',[S(10,2,3)],[S(10,2,3)])}
# The infertility definition's full wording is in visible vocabulary, not wholly in 02-p3.
sources['L10-V-INF']={'file':'lesson-10.html','locator':'#lesson-10-anchor-words; infertility dt/dd','rendered_pages':[2],'visible_text':'Difficulty establishing a pregnancy due to one or more reproductive factors.'}
cs=list(concepts['infertility']);cs[4]=['L10-V-INF',S(10,2,3)];concepts['infertility']=tuple(cs)
gen=json.loads((blind/'generated-09-10.json').read_text())
extras={
'ch14-import-OBJ_2131525':('Ovulation',[S(10,2,1),'L10-W2'],'Ovulation is located at the ovary, and worked step 2 explicitly says oviduct blockage does not itself remove this event. Unknown distractor terminology is not needed to choose the supported event.','Recognition/application'),
'ch14-import-OBJ_2131570':('Estrogen and progesterone',[S(9,4,1)],'The paragraph says combined methods supply an estrogen and a progestin and defines progestin as progesterone-like. This supports the option phrased as hormones similar to estrogen and progesterone.','Recognition'),
'ch14-import-OBJ_2131114':('Menopause',[S(9,2,1)],'The paragraph defines menopause in the terms used by the prompt.','Retrieval'),
'ch14-sequence-08':('1. Developing trophoblast tissue releases hCG → 2. hCG supports the corpus luteum → 3. The corpus luteum continues hormone release → 4. Progesterone helps maintain the endometrium',[S(9,3,1),S(9,3,2),S(9,3,3)],'03-p3 states the complete causal order. The supplied steps are already stored/displayed in this order; this answer verifies a readable sequence only, not independent ordering or a native shuffle.','Pathway reconstruction; display order cues answer'),
'ch14-application-16':('Less ovarian hormone feedback allows greater pituitary stimulation',[S(9,2,2),S(9,2,3)],'Reduced ovarian output removes inhibition; the functioning anterior pituitary can release more FSH/LH even while the target responds poorly.','Close application/recognition'),
'ch14-application-16-flash':('If follicles respond less strongly, their ovarian hormone output can fall. With less inhibitory feedback, a functioning hypothalamic–pituitary system allows the anterior pituitary to release more FSH and LH. More gonadotropin stimulation does not guarantee that poorly responsive follicles recover.',[S(9,2,2),S(9,2,3),'L09-W2'],'The paragraphs and worked step 2 supply the entire weak response → less inhibition → higher pituitary output chain.','Taught scenario explanation'),
'ch14-application-17':('Reduced likelihood of follicle maturation and ovulation',[S(9,4,1),'L09-W3'],'04-p1 links reduced FSH/LH support to reduced follicular development and suppressed LH surge to reduced ovulation; worked step 3 connects ovarian responsiveness to needed stimulation.','Close application/recognition'),
'ch14-application-17-flash':('The intended consequence is less follicle maturation and a lower likelihood of ovulation. The ovaries receive reduced FSH/LH stimulation, and suppressing the LH surge removes the normal signal needed for ovulation.',[S(9,4,1),'L09-W3'],'The same taught causal links explain the intended ovarian consequence without requiring unseen information.','Taught scenario explanation'),
'ch14-application-18':('Absence of symptoms alone cannot rule out an infection',[S(10,1,3)],'Asymptomatic infection and the limits of appearance are explicitly stated.','Direct recognition'),
'ch14-application-18-flash':('No visible symptoms do not establish that there is no STI. Some infections are asymptomatic, so appearance or lack of discomfort alone cannot rule infection out.',[S(10,1,3)],'The paragraph directly defines asymptomatic and explains the inference limit.','Explain stated evidence limitation'),
'ch14-application-19':('The route needed for gametes to meet is disrupted',[S(10,2,1),S(10,2,2)],'Follicular/ovarian events are separated from oviduct transport, which scar blockage can disrupt.','Close application/recognition'),
'ch14-application-19-flash':('Follicles may still develop at the ovary, but scar tissue can obstruct the oviduct route through which sperm and the oocyte would meet. A functioning source of gametes does not repair the transport pathway, so fertility can be reduced.',[S(10,2,1),S(10,2,2),S(10,2,3)],'The teaching locates the separate functions and states transport impairment can contribute to infertility. One affected duct is phrased as a reduction in fertility, not a guarantee that all reproduction stops.','Taught scenario explanation'),
'ch14-application-20':('It can reduce transmission risk but does not eliminate every risk',[S(10,4,2)],'The paragraph explains barrier action and continuing transmission risk from affected uncovered skin.','Direct recognition'),
'ch14-application-20-flash':('An appropriate condom used correctly and consistently acts as a physical barrier that reduces contact with infectious material. It can lower transmission risk, but affected skin outside the covered area can still transmit some infections, so the protection is not absolute.',[S(10,4,2)],'The paragraph supplies both the positive mechanism and its limitation.','Reconstruct stated mechanism'),
'ch14-typed-19':('hCG',[S(9,3,2)],'The early-pregnancy signal supporting the corpus luteum is explicitly named.','Retrieval'),
'ch14-typed-20':('Pelvic inflammatory disease (PID)',[S(10,2,2)],'The paragraph names the condition and abbreviation after describing spread into upper reproductive structures.','Scenario retrieval'),
'ch14-multiple-select-5':('a and b: Some infections may be present without obvious symptoms; scarring in an oviduct can interfere with reproduction.',[S(10,1,3),S(10,2,2),S(10,2,3)],'01-p3 supports a, rejects diagnosis from an online symptom list, and names both bacterial and viral infections (rejecting c and d). 02-p2/3 supports b.','Discriminate multiple stated conclusions')}
for i,g in enumerate(gen,1):
    gid=g['id'];page=1 if i<=10 else 2 if i<=23 else 3 if i<=33 else 4 if i<=38 else 5 if i<=44 else 6
    if gid.startswith('ch14-concept-'):
        tail=gid[len('ch14-concept-'):];key,variant=tail.rsplit('-',1);l,explain,term,mis,refs,mrefs=concepts[key]
        if variant=='misconception':a=mis;rr=mrefs;demand='Correct a directly taught misconception';note='The referenced teaching explicitly distinguishes the claim from the stated mechanism or limitation.'
        elif variant=='flash':a=explain;rr=refs;demand='Explain a taught term';note='The referenced teaching defines the term and supplies the mechanism included in this answer.'
        else:a=term;rr=refs;demand='Term retrieval from definition';note='The referenced visible definition matches the prompt; reverse and blank versions are representations of the same term, not separate concepts.'
    else:a,rr,note,demand=extras[gid]
    task(gid,g['lesson'],'optional_generated',g['prompt'],a,rr,note,demand,[page])
    records[-1].update({'representation_number':i,'kind':g['kind'],'family':g['family'],'prompt_source':'generated-09-10.json; generated-09-10.pdf'})
assert len(records)==66 and sum(r['category']=='optional_generated' for r in records)==49
assert len({r['id'] for r in records})==66
assert all(x in sources for r in records for x in r['support_ids'])

layout=[
('lesson-09-page-01.png','Title, purpose, completion directions and first definitions readable; vocabulary continues onto page 2. Trophoblast appears in the short hCG glossary definition before being explained in the teaching on page 4; no task requires it before that explanation.'),
('lesson-09-page-02.png','Baseline explanation and sampling limitation readable with ample bottom space. The figure it introduces is on page 3, creating a page-turn integration demand, but all relevant text is complete.'),
('lesson-09-page-03.png','Cycle figure text and arrows legible. Downward early-follicle-to-menstrual-flow arrow can suggest causation when viewed alone; page 2 explicitly corrects that interpretation and the figure footer supplies hormone-decline causation. No explicit ovulation event box or post-active regression box; those transitions rely on adjacent prose/footer. Menopause feedback explanation is readable.'),
('lesson-09-page-04.png','Dense but readable page covering age comparison, early pregnancy and combined contraception. No clipped lines. New trophoblast, implantation and progestin terms receive explanatory apposition before the assessed mechanisms.'),
('lesson-09-page-05.png','Worked example and non-responsive corpus-luteum challenge fully readable. Supported-practice introduction sits at the page bottom, with actual questions on page 6; mild navigation burden only.'),
('lesson-09-page-06.png','Both supported prompts, stop prompt, video-independent explanation and required selection 1 are readable and complete. Lowest choice stays clear of footer.'),
('lesson-09-page-07.png','Required selection 2, both writing prompts and original optional saved-response prompt readable; character limits and navigation are present. Static placeholders and inactive controls provide no persistence or gate evidence.'),
('lesson-10-page-01.png','Title, purpose, completion directions and first terms readable. Terms continue onto page 2; no clipped content.'),
('lesson-10-page-02.png','Vocabulary and first two teaching sections readable. The inflammation/scarring paragraph crosses to page 3 at a sentence boundary; no text loss, but route consequences require a page turn.'),
('lesson-10-page-03.png','Continuation and consequences readable. Normal sagittal anatomy image is large, with legible oviduct/ovary/uterus labels. It does not portray scarring or both ducts as a bilateral route; teaching and caption explicitly limit its use to normal location. No figure label clipping detected.'),
('lesson-10-page-04.png','Pathogen/tissue differences and conception-control/barrier comparison are dense but readable through the bottom paragraph, clear of the footer.'),
('lesson-10-page-05.png','Worked case, new optional comparison and both supported questions fully readable, including all options near page bottom.'),
('lesson-10-page-06.png','Stop prompt, both required selections and writing 1 complete and readable. No clipping.'),
('lesson-10-page-07.png','Writing 2 and navigation readable; most of page is intentionally blank in this static rendering. This is inefficient pagination, not missing question content.'),
('generated-page-01.png','Representations 1–10 fully readable. Intro correctly warns that 49 representations are not 49 concepts and this is not a native shuffled session.'),
('generated-page-02.png','Representations 11–23 readable and complete. Long PID identifiers fit; final misconception stays above bottom margin.'),
('generated-page-03.png','Representations 24–33 readable, including all bilateral-blockage MC options. No clipping.'),
('generated-page-04.png','Representations 34–38 readable. Sequence 36 is already listed in the biologically supported order, so independent ordering/shuffling is not measured.'),
('generated-page-05.png','Representations 39–44 readable. The four choices under item 39 lack visible bullet dots while other MC groups have them; wording remains separated and usable. This is a minor presentation inconsistency.'),
('generated-page-06.png','Representations 45–49 readable and complete; multi-select option IDs a–d are visible. No clipping.')]
observations=[
{'id':'O1','severity':'limitation','finding':'First-attempt answers are supported, but most assessment is close retrieval or reconstruction of immediately taught statements.','evidence':'The required selections contain conspicuous impossibilities such as moving ovaries into the uterus, LH turning into sperm, and bacterial/viral guarantees. The four writing tasks reconstruct taught chains or comparisons. The two new optional tasks require a useful small transfer: target non-response and hormonal versus transport failure.','consequence':'Do not interpret success on this packet alone as robust independent diagnostic or unfamiliar-scenario reasoning.'},
{'id':'O2','severity':'minor residual visual risk','finding':'The unchanged cycle diagram can imply an incorrect causal arrow from developing follicles to menstrual flow when seen alone.','evidence':'Actual lesson09 page 3 pixels show a downward arrow between those boxes; lesson09 01-p3 explicitly says this is overlap and not follicle-caused shedding, and the footer supplies preceding hormone decline.','consequence':'The integrated lesson supports the correct reading. An isolated diagram/read-aloud still should not be counted as proof that learners will interpret the arrow correctly.'},
{'id':'O3','severity':'boundary','finding':'No required-answer-blocking first-use gap identified within the allowed prerequisite.','evidence':'Corpus luteum and endometrium are restated; gonadotropins, inhibin, trophoblast, implantation, progestin, asymptomatic, inflammation, PID, infertility, ectopic pregnancy and epididymis are explained by the time they are needed. Trophoblast first occurs in the hCG glossary before the later explanation. HIV is not expanded, and imported-MC distractors include parturition/relaxin/oxytocin/prolactin without explanations here.','consequence':'These latter terms could impose incidental reading load, but none is required to select or explain the supported answer. I did not supply unseen definitions in answering.'},
{'id':'O4','severity':'boundary','finding':'Normal-anatomy figure is correctly scoped, not a damage illustration.','evidence':'Lesson10 page 3 and 02-p1/caption explicitly describe normal anatomy, not infection or scars. Bilateral duct count and consequences are supplied by text and worked case.','consequence':'Answers about blockage depend on taught mechanism and stipulated model conditions; the picture itself cannot prove bilateral obstruction.'},
{'id':'O5','severity':'minor layout','finding':'Static pagination adds mild page-turn effort but no lost content.','evidence':'Lesson09 figure/prose and support introduction/questions are separated; lesson10 scarring paragraph spans pages 2–3; lesson10 writing 2 occupies a sparse seventh page; generated item39 choices lack bullet dots.','consequence':'Readable at supplied render size; no course/mobile/runtime acceptance inferred.'},
{'id':'O6','severity':'scope','finding':'Optional 49 representations cover repeated concepts and repeated scenario variants.','evidence':'Eight term concepts each appear in four forms (32 items); three imported MCs, one already-ordered pathway, five MC/flash pairs, two typed retrievals and one multi-select account for the remaining 17.','consequence':'All were attempted individually; the count is not a claim of 49 independent concepts or 49 independent demonstrations of mastery.'},
{'id':'O7','severity':'untested','finding':'Interaction, grading and persistence were not tested.','evidence':'The review pages explicitly have inactive controls, withheld feedback and separate writing placeholders. No native session was opened.','consequence':'Start/unlock gating, wrong-answer hints, answer normalization, native shuffle, term dialogs, video playback, textbook navigation, save/edit state, reload persistence, All My Work, Submit/finish and mobile/responsive accessibility remain unverified.'}]
files=[blind/n for n in ['lesson-09.html','lesson-10.html','generated-09-10.json']]+[rendered/n for n in ['lesson-09.pdf','lesson-10.pdf','generated-09-10.pdf']]+[rendered/n for n,_ in layout]
manifest=[{'path':str(p.relative_to(root)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]
report={'status':'FROZEN_BLIND_FIRST_ATTEMPT','frozen_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'CH14 lessons09–10; authorized direct Scout content review only','read_boundary':'Read only the two blind HTML files, generated-09-10.json, and actual PDF/PNG files in review-rendered-final. Did not read candidate/, teaching-copy.json, review-feedback/, source-read/, other reviewers, originals, integrity JSONs or extracted text files.','prerequisite':'Only basic reproductive anatomy and normal hormonal cycles assumed. No gap filled using external expertise. No web lookup used.','counts':{'required_selections':4,'required_writings':4,'supported':4,'stops':2,'new_optional':2,'original_saved_optional':1,'complete_lesson_tasks':17,'optional_generated_representations':49,'all_attempts':66,'rendered_pages_inspected':20},'result':'All 66 prompts have one recorded first answer and visible teaching support. Correctness remains ungraded until the authorized feedback comparison. No blocking text/figure clipping or answer-support gap found. This is not runtime, mobile, clinical or course acceptance.','source_manifest':manifest,'visible_support_registry':sources,'attempts':records,'rendered_page_observations':[{'file':n,'observation':o,'actual_pixels_inspected':True} for n,o in layout],'cross_cutting_observations':observations,'pending':'Await parent permission to inspect feedback. Preserve this frozen file unchanged and record any later comparison separately.'}
(out/'first-attempt.json').write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n')
md=['# Frozen blind first attempt: CH14 lessons 09–10', '',f"Frozen at: {report['frozen_at_utc']}", '',report['result'],'', '## Scope and integrity',report['read_boundary'],report['prerequisite'],'','Counts: 17 complete lesson tasks (4 selections, 4 writings, 4 supported, 2 stops, 2 new optional, 1 original saved-response prompt), plus all 49 optional generated representations. All 20 supplied pages were inspected as actual rendered pixels.','', '## Main observations']
for o in observations:md += [f"### {o['id']} · {o['severity']}",o['finding'],f"Evidence: {o['evidence']}",f"Consequence: {o['consequence']}",'']
md += ['## First answers and per-task support','The following answers are frozen before feedback. “Sufficient support” is a pre-feedback support judgment, not an answer-key score. Every source identifier resolves to a paragraph/figure and exact visible text in the registry below.','']
for i,r in enumerate(records,1):
 md += [f"### {i}. {r['id']} ({r['category']})",f"Prompt: {r['prompt']}",f"First answer: {r['first_attempt_answer']}",f"Visible support: {', '.join(r['support_ids'])}",f"Support map: {r['support_map']}",f"Demand: {r['cognitive_demand']}",f"Prompt render page(s): {r['prompt_rendered_pages']}",'']
md += ['## Page-by-page pixel observations','']
for n,o in layout:md += [f'- {n}: {o}']
md += ['','## Visible support registry','']
for sid,s in sources.items():md += [f"### {sid}",f"Location: {s['file']} {s['locator']}; rendered page(s) {s['rendered_pages']}",s['visible_text'],'']
md += ['## Source hashes','']
for f in manifest:md += [f"- {f['path']} · {f['bytes']} bytes · SHA-256 {f['sha256']}"]
md += ['','## Pending',report['pending'],'']
(out/'first-attempt.md').write_text('\n'.join(md))
for name in ['first-attempt.json','first-attempt.md']:
 p=out/name;print(name,p.stat().st_size,hashlib.sha256(p.read_bytes()).hexdigest())
print('attempt count',len(records),'support entries',len(sources),'manifest',len(manifest),'pages',len(layout))
