#!/usr/bin/env python3
"""Write reproducible handoff inventories from the built Chapter 14 files."""
from pathlib import Path
from collections import Counter,defaultdict
import hashlib,json,sys,shutil,re,importlib.metadata
from bs4 import BeautifulSoup
R=Path(__file__).resolve().parents[1];A=R/'authoring';V=R/'verification';sys.path.insert(0,str(R/'scripts'));from content import LESSONS,VIDEOS
j=lambda f:json.loads(f.read_text())
def save(name,obj): (A/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
C=j(A/'course-config.json');M=j(A/'textbook-question-manifest.json');pool=j(A/'generated-practice-items.json');D=j(A/'assessment-dispositions.json');figs=j(A/'diagram-review.json')
source_files=[('workspace/assets/textbook/chapter-14.pdf','Textbook: chapter content, original figures/questions; printed 476–505.'),('authoring/source-inputs/Unit B Chapter 14 Notes.pptx','35-slide teacher deck: emphasis, terminology, examples and explanatory level.'),('authoring/source-assessment-catalogue.json','191 physical item records from the actual supplied Unit B quiz/test/review XMLs, including answer information; developer only.'),('authoring/daily-plan-reference.txt','Transcribed Chapter 14 daily-plan rows, days 24–29; pacing history, not required student workflow.')]
save('source-inventory.json',{'chapter':14,'sources':[{'path':p,'sha256':sha(R/p),'bytes':(R/p).stat().st_size,'role':role}for p,role in source_files], 'referenceSnapshot':'Biology30_Chapters_11_12_13_Post_Audit_v8.zip','sourceArchive':'UnitB.zip, nested D2LExport_156587_26-27 _ S1 _ Biology 30 _ Per 1(A) _ Sec 10_202691736.zip','quizXmls':['quiz_d2l_59226.xml','quiz_d2l_59227.xml','quiz_d2l_59228.xml','quiz_d2l_59237.xml'],'physicalItems':191,'duplicateHandling':'Each physical item retains its original source identity. Identical whole-course files were deduplicated during the preceding preflight; physical quiz items were not assumed identical merely because exports were duplicates.','reservedScope':'The uploaded Chapter 15–20 decks remain future chapter inputs and were not authored into this Chapter 14 package.'})
lessons=[]
for n,l in enumerate(LESSONS,1):
 lessons.append({'lesson':n,'route':f'lesson-{n:02d}','title':l['title'],'goal':l['goal'],'teacherSlides':l['slides'],'textbookPrintedAnchors':l['pages'],'dailyPlanDays':([24]if n in[1,2]else[25]if n in[3,4]else[26]if n in[5,6]else[27]if n in[7,8,9]else[]),'teachingKeys':[f'ch14-l{n:02d}-teaching-{i:02d}'for i in range(1,len(l['sections'])+1)],'figureIds':list(l.get('figures',{}).values()),'requiredCheck':C['checks'][n-1]['id'],'optionalTextbookIds':[q['id']for q in M['questions']if f'lesson-{n:02d}'in q['topics']],'sourceAssessmentIds':[q['id']for q in C['practiceQuestions']if q['lesson']==n],'disposition':'Taught directly, with worked example and two supported selections before the required check.'})
lessons.append({'lesson':11,'route':'lesson-11','title':C['lessons'][-1]['title'],'teacherSlides':'Synthesis of 3–35','textbookPrintedAnchors':[503,504,505],'dailyPlanDays':[28,29],'requiredCheck':C['checks'][-1]['id'],'disposition':'Integrated review, worked synthesis, optional independent transfer and 6-selection/2-writing final check.'})
save('lesson-source-map.json',lessons)
# Scope anchored in supplied outcome list; avoid claiming an inaccessible official PDF was fully read.
outcomes=[('30-B1.1k','Female reproductive structures and functions',[5,6]),('30-B1.2k','Male reproductive structures and functions',[2,3]),('30-B1.3k','Gametes and their supporting structures',[3,6]),('30-B1.4k','Chromosomal and hormonal influences on reproductive development',[1,4,9]),('30-B1.5k','STIs and reproductive function',[10]),('30-B2.1k','Reproductive hormones and primary/secondary sex characteristics',[1,4,9]),('30-B2.2k','Female reproductive hormones and menstrual-cycle interactions',[6,7,8,9]),('30-B2.3k','Male reproductive hormones and interactions',[3,4])]
save('outcome-coverage.json',{'scopeBasis':'Unit B Review Seminar Notes.pdf, supplied outcomes 1 and 2, pages 2 and 10. Descriptions below are paraphrases, not purported exact official wording.','officialVerification':'Alberta 2025–26 bulletin identifies the 2014 Biology 20–30 Program of Studies. The official 2014 PDF fetch was blocked. These candidate outcome codes require final cross-check against the school’s current official outcome register; current-year complete alignment is not certified.','records':[{'candidateCode':k,'scope':v,'lessons':ls,'reviewLesson':11,'status':'Scope taught; exact current official code/wording pending confirmation.'}for k,v,ls in outcomes]})
# Auditable finite bank, with explicit caution against treating templates as unrelated cases.
coverage=defaultdict(Counter)
for q in pool:coverage[(q['lesson'],q['conceptId'])][(q['family'],q['difficulty'],q['kind'])]+=1
save('practice-coverage.json',{'finiteBank':True,'liveAiGeneration':False,'totalGeneratedRepresentations':len(pool),'countsByKind':dict(Counter(q['kind']for q in pool)),'countsByLesson':dict(Counter(q['lesson']for q in pool)),'interpretation':'Multiple representations reuse core concepts. This is not a claim of 409 independent case studies or equally deep coverage of every concept. Some mode/concept filters legitimately repeat an item because no alternative exists.','records':[{'lesson':l,'conceptId':c,'families':[{'family':f,'difficulty':d,'kind':k,'count':v}for(f,d,k),v in cs.items()]}for(l,c),cs in coverage.items()]})
video_source={v[0]:{'id':v[0],'lesson':v[1],'courseTitle':v[2],'purpose':v[3],'writtenEquivalent':v[4],'url':'https://www.youtube.com/watch?v='+v[0],'source':'Chapter 14 teacher deck relationship hyperlink','status':'ID recovered from supplied PPT relationships; current playback and full video content not independently verified. Optional and never required to complete the lesson.','titleNote':'The course title describes the topic; it is not asserted to be the uploader’s verbatim video title.'}for v in VIDEOS}
save('video-map.json',list(video_source.values()))
for f in figs:
 f['finalAssetSha256']=sha(R/'workspace'/f['src']);f['reviewStatus']='Visually inspected source/crop or schematic and corresponding letter targets. Review does not constitute clinical/teacher certification.'
 f['checksPerformed']=['Readability at full size','Structure/letter association','Source crop completeness or schematic direction','Answer-map consistency where used for labeling']
save('diagram-review.json',figs)
save('textbook-visual-review.json',{'questions':len(M['questions']),'status':'All active question crops inspected against their original wording and supporting context during authoring; final thought-lab corrections inspected separately.','repairs':['Trimmed following-question fragments from two in-text crops.','Replaced initial erroneous Thought Lab 14.2 crop boundaries with its two actual analysis items and two eligible paper procedures.','Included all five paper-based Thought Lab 14.3 prompts with the required source pages.','Kept multipart question continuations and shared graphs/tables.'],'limits':['Historical textbook wording is preserved in original crops. Historical terminology, dates and clinical claims are not automatically endorsed as current advice.','The source hormone graph in Chapter Review question 11 uses a faint colour; full-page context and enlargement are provided.'],'cropManifest':'textbook-question-manifest.json','exclusions':len(M['excluded'])})
# Component reference catalogue is developer-only.
recipes=['Overview','Ordinary lesson','Final review','Optional extension','Collapsed page guide','Optional reading band','Anchor and expanded vocabulary','Worked example','Guided activity','Independent transfer','Required check','Optional source response','Flash cards','Fill in the blanks','Multiple choice','Mixed practice','Labeling','Textbook Practice','All My Work','Core Vocabulary','Vocabulary drawer and Frayer','PDF library and modal','Video library and lesson video','Reset confirmation','Print']
save('component-catalogue.json',{'reference':'Copied v8 Chapter 12/13 component markup and exact CSS; fixtures in authoring/templates.','recipes':[{'name':n,'owner':'workspace/index.html; workspace/main.js; applicable assets/*.js','states':'See verification/surface-matrix.json, browser-results.json and additional-browser-results.json. States not exercised are not inferred from source appearance.'}for n in recipes]})
# Export current counts and static contracts.
soup=BeautifulSoup((R/'workspace/index.html').read_text(),'html.parser');ids=[x['id']for x in soup.select('[id]')];missing=[]
for q in pool:
 if q['kind']in('mc','diagram')and(q['answer']not in q['options']):missing.append(q['id'])
checks={'uniqueDomIds':len(ids)==len(set(ids)),'requiredChecks':len(C['checks'])==11,'allAutoMcAnswersInOptions':not missing,'exactMainCss':sha(R/'workspace/styles.css')=='94fe523654289edd8b0f951dd6782f83dce7d08f5e18a3d903d25576fbfa0ba5','exactTextbookCss':sha(R/'workspace/assets/textbook-practice.css')=='4101415cce977a4a8553754a01cea3d33ad194add1198db00ddc0ba99bfeea12'}
(V/'static-checks.json').write_text(json.dumps(checks,indent=2))
for f in ['browser-results.json','additional-browser-results.json']:
 x=j(V/f)
 if 'exception'in x or any(t['status']!='passed'for t in x['tests']):raise RuntimeError('Resolve/report verification failures in '+f)
if not all(checks.values()):raise RuntimeError(str(checks))
print('Handoff records written. Bank:',len(pool),'questions:',len(M['questions']))
