import path from "node:path";

import type { EmbeddedAssetRecord } from "./exports/shared.js";

export type AppsScriptDriveAssetManifestEntry = {
  id: string;
  relativePath: string;
  mimeType: string;
  contentKind: EmbeddedAssetRecord["contentKind"];
  serveMode: "apps-script" | "drive";
};

export type AppsScriptDriveAssetManifest = {
  shellAssetPath: string;
  assets: AppsScriptDriveAssetManifestEntry[];
};

export const APPS_SCRIPT_DRIVE_ASSET_DIR = "drive-assets";
export const APPS_SCRIPT_SHELL_ASSET_PATH = "__canvas_helper_shell/index.html";
export const APPS_SCRIPT_ASSET_MANIFEST_PATH = "asset-manifest.json";

function extensionForAsset(record: EmbeddedAssetRecord) {
  if (record.contentKind === "file") {
    const sourceExtension = path.extname(record.sourcePath);
    if (sourceExtension) {
      return sourceExtension;
    }
  }

  switch (record.mimeType) {
    case "text/html":
      return ".html";
    case "text/css":
      return ".css";
    case "text/javascript":
    case "application/javascript":
      return ".js";
    case "application/json":
    case "text/json":
      return ".json";
    case "application/pdf":
      return ".pdf";
    case "image/svg+xml":
      return ".svg";
    case "image/png":
      return ".png";
    case "image/jpeg":
      return ".jpg";
    case "image/webp":
      return ".webp";
    case "image/gif":
      return ".gif";
    case "video/mp4":
      return ".mp4";
    case "audio/mpeg":
      return ".mp3";
    default:
      return ".bin";
  }
}

function buildAssetRelativePath(record: EmbeddedAssetRecord) {
  const bucket = record.contentKind === "text" ? "text-assets" : "binary-assets";
  return `${bucket}/${record.id}${extensionForAsset(record)}`;
}

export function buildAppsScriptAssetManifest(documentAssets: Array<EmbeddedAssetRecord>): AppsScriptDriveAssetManifest {
  return {
    shellAssetPath: APPS_SCRIPT_SHELL_ASSET_PATH,
    assets: documentAssets.map((record) => ({
      id: record.id,
      relativePath: buildAssetRelativePath(record),
      mimeType: record.mimeType,
      contentKind: record.contentKind,
      serveMode: record.contentKind === "text" ? "apps-script" : "drive"
    }))
  };
}

export function buildAppsScriptManifest() {
  return `${JSON.stringify(
    {
      timeZone: "America/Denver",
      exceptionLogging: "STACKDRIVER",
      runtimeVersion: "V8"
    },
    null,
    2
  )}\n`;
}

export function buildAppsScriptClaspIgnore() {
  return [
    "drive-assets/**",
    "**/drive-assets/**",
    "README-deploy.md",
    "**/README-deploy.md",
    ""
  ].join("\n");
}

type BuildAppsScriptCodeOptions = {
  assetManifestPath: string;
  projectSlug: string;
  projectTitle: string;
  shellAssetPath: string;
  storageKeys: string[];
};

export function buildAppsScriptCode(options: BuildAppsScriptCodeOptions) {
  const projectSlugLiteral = JSON.stringify(options.projectSlug);
  const titleLiteral = JSON.stringify(options.projectTitle);
  const shellAssetPathLiteral = JSON.stringify(options.shellAssetPath);
  const assetManifestPathLiteral = JSON.stringify(options.assetManifestPath);
  const storageKeysLiteral = JSON.stringify([...new Set(options.storageKeys.map((value) => value.trim()).filter(Boolean))]);

  return [
    "const CANVAS_HELPER_DRIVE_ROOT_FOLDER_ID_KEY = 'canvas_helper_drive_root_folder_id';",
    "const CANVAS_HELPER_DRIVE_INDEX_KEY = 'canvas_helper_drive_asset_index_v1';",
    "const CANVAS_HELPER_DRIVE_INDEX_FOLDER_ID_KEY = 'canvas_helper_drive_asset_index_folder_id_v1';",
    "const CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY = 'canvas_helper_drive_asset_manifest_v1';",
    "const CANVAS_HELPER_AUTOSAVE_FOLDER_ID_KEY = 'canvas_helper_apps_script_autosave_folder_id_v1';",
    "const CANVAS_HELPER_DRIVE_ASSET_ROOT_LABEL = 'drive-assets';",
    `const CANVAS_HELPER_SHELL_ASSET_PATH = ${shellAssetPathLiteral};`,
    `const CANVAS_HELPER_ASSET_MANIFEST_PATH = ${assetManifestPathLiteral};`,
    `const CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG = ${projectSlugLiteral};`,
    `const CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS = ${storageKeysLiteral};`,
    "const CANVAS_HELPER_AUTOSAVE_FOLDER_NAME = 'Canvas Helper Autosaves - ' + CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG;",
    `const CANVAS_HELPER_PROJECT_TITLE = ${titleLiteral};`,
    "",
    "function doGet(e) {",
    "  if (e && e.parameter && e.parameter.asset) {",
    "    return serveTextAsset_(String(e.parameter.asset), e.parameter.raw === '1');",
    "  }",
    "",
    "  return serveShell_(e);",
    "}",
    "",
    "function setDriveRootFolderId(folderId) {",
    "  if (!folderId) {",
    "    throw new Error('setDriveRootFolderId(folderId) requires the uploaded drive-assets folder id.');",
    "  }",
    "",
    "  const scriptProperties = PropertiesService.getScriptProperties();",
    "  scriptProperties.setProperty(CANVAS_HELPER_DRIVE_ROOT_FOLDER_ID_KEY, String(folderId));",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_INDEX_KEY);",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_INDEX_FOLDER_ID_KEY);",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY);",
    "  return rebuildDriveAssetIndex();",
    "}",
    "",
    "function rebuildDriveAssetIndex() {",
    "  return rebuildDriveAssetIndex_();",
    "}",
    "",
    "function serveShell_(e) {",
    "  const assetContext = buildAssetContext_();",
    "  const shellHtml = readDriveTextFileByPath_(CANVAS_HELPER_SHELL_ASSET_PATH, assetContext.driveIndex);",
    "  const injectedHtml = injectHtmlTag_(shellHtml, buildAssetBootstrap_(assetContext) + buildAutosaveBootstrap_());",
    "  return HtmlService.createHtmlOutput(injectedHtml)",
    "    .setTitle(CANVAS_HELPER_PROJECT_TITLE)",
    "    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);",
    "}",
    "",
    "function getCanvasHelperAutosave() {",
    "  const userKey = getCanvasHelperAutosaveUserKey_();",
    "  const record = readCanvasHelperAutosaveRecord_(userKey);",
    "  return {",
    "    ok: true,",
    "    projectSlug: CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG,",
    "    userKey: userKey,",
    "    savedAt: record && record.savedAt ? record.savedAt : '',",
    "    storageKeys: CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS,",
    "    storageValues: record && record.storageValues ? record.storageValues : {}",
    "  };",
    "}",
    "",
    "function saveCanvasHelperAutosave(payload) {",
    "  const lock = LockService.getScriptLock();",
    "  lock.waitLock(10000);",
    "  try {",
    "    const userKey = getCanvasHelperAutosaveUserKey_();",
    "    const normalizedPayload = normalizeCanvasHelperAutosavePayload_(payload);",
    "    const savedAt = new Date().toISOString();",
    "    const record = {",
    "      schemaVersion: 1,",
    "      projectSlug: CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG,",
    "      userKey: userKey,",
    "      savedAt: savedAt,",
    "      storageKeys: CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS,",
    "      storageValues: normalizedPayload.storageValues",
    "    };",
    "    writeCanvasHelperAutosaveRecord_(userKey, record);",
    "    return {",
    "      ok: true,",
    "      projectSlug: CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG,",
    "      userKey: userKey,",
    "      savedAt: savedAt,",
    "      storageKeys: CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS",
    "    };",
    "  } finally {",
    "    lock.releaseLock();",
    "  }",
    "}",
    "",
    "function serveTextAsset_(assetId, rawMode) {",
    "  const assetContext = buildAssetContext_();",
    "  const manifestEntry = assetContext.assetById[assetId];",
    "  if (!manifestEntry) {",
    "    throw new Error('Unknown Canvas Helper asset id: ' + assetId);",
    "  }",
    "",
    "  if (manifestEntry.serveMode !== 'apps-script') {",
    "    throw new Error('Asset ' + assetId + ' is Drive-backed and should not be requested through Apps Script.');",
    "  }",
    "",
    "  const assetText = readDriveTextFileByPath_(manifestEntry.relativePath, assetContext.driveIndex);",
    "  return createTextOutput_(assetText, manifestEntry.mimeType, rawMode);",
    "}",
    "",
    "function buildAssetContext_() {",
    "  const driveIndex = getDriveAssetIndex_();",
    "  const assetManifest = getAssetManifest_(driveIndex);",
    "  const assetById = {};",
    "",
    "  for (let index = 0; index < assetManifest.assets.length; index += 1) {",
    "    const asset = assetManifest.assets[index];",
    "    assetById[asset.id] = asset;",
    "  }",
    "",
    "  return {",
    "    assetManifest: assetManifest,",
    "    assetById: assetById,",
    "    driveIndex: driveIndex",
    "  };",
    "}",
    "",
    "function getAssetManifest_(driveIndex) {",
    "  const scriptProperties = PropertiesService.getScriptProperties();",
    "  const cachedManifest = scriptProperties.getProperty(CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY);",
    "  if (cachedManifest) {",
    "    return JSON.parse(cachedManifest);",
    "  }",
    "",
    "  const manifestJson = readDriveTextFileByPath_(CANVAS_HELPER_ASSET_MANIFEST_PATH, driveIndex);",
    "  const manifest = JSON.parse(manifestJson);",
    "  scriptProperties.setProperty(CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY, JSON.stringify(manifest));",
    "  return manifest;",
    "}",
    "",
    "function getDriveAssetIndex_() {",
    "  const scriptProperties = PropertiesService.getScriptProperties();",
    "  const currentDriveRootFolderId = getDriveRootFolderId_();",
    "  const cachedIndexFolderId = scriptProperties.getProperty(CANVAS_HELPER_DRIVE_INDEX_FOLDER_ID_KEY);",
    "  const cachedIndex = scriptProperties.getProperty(CANVAS_HELPER_DRIVE_INDEX_KEY);",
    "  if (cachedIndex && cachedIndexFolderId === currentDriveRootFolderId) {",
    "    const parsedIndex = JSON.parse(cachedIndex);",
    "    if (parsedIndex[CANVAS_HELPER_ASSET_MANIFEST_PATH]) {",
    "      return parsedIndex;",
    "    }",
    "  }",
    "",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_INDEX_KEY);",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_INDEX_FOLDER_ID_KEY);",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY);",
    "",
    "  return rebuildDriveAssetIndex_();",
    "}",
    "",
    "function rebuildDriveAssetIndex_() {",
    "  const driveRootFolderId = getDriveRootFolderId_();",
    "  const driveRootFolder = DriveApp.getFolderById(driveRootFolderId);",
    "  const driveIndex = {};",
    "",
    "  indexDriveFolder_(driveRootFolder, '', driveIndex);",
    "",
    "  const scriptProperties = PropertiesService.getScriptProperties();",
    "  scriptProperties.setProperty(CANVAS_HELPER_DRIVE_INDEX_KEY, JSON.stringify(driveIndex));",
    "  scriptProperties.setProperty(CANVAS_HELPER_DRIVE_INDEX_FOLDER_ID_KEY, driveRootFolderId);",
    "  scriptProperties.deleteProperty(CANVAS_HELPER_DRIVE_ASSET_MANIFEST_CACHE_KEY);",
    "",
    "  return {",
    "    driveAssetCount: Object.keys(driveIndex).length,",
    "    driveRootFolderId: driveRootFolderId,",
    "    driveAssetRootLabel: CANVAS_HELPER_DRIVE_ASSET_ROOT_LABEL",
    "  };",
    "}",
    "",
    "function getDriveRootFolderId_() {",
    "  const folderId = PropertiesService.getScriptProperties().getProperty(CANVAS_HELPER_DRIVE_ROOT_FOLDER_ID_KEY);",
    "  if (!folderId) {",
    "    throw new Error('Drive asset folder id is not configured. Upload the drive-assets folder, then run setDriveRootFolderId(\"FOLDER_ID\").');",
    "  }",
    "",
    "  return folderId;",
    "}",
    "",
    "function indexDriveFolder_(folder, prefix, driveIndex) {",
    "  const files = folder.getFiles();",
    "  while (files.hasNext()) {",
    "    const file = files.next();",
    "    const relativePath = prefix ? prefix + '/' + file.getName() : file.getName();",
    "    driveIndex[relativePath] = file.getId();",
    "  }",
    "",
    "  const folders = folder.getFolders();",
    "  while (folders.hasNext()) {",
    "    const childFolder = folders.next();",
    "    const nextPrefix = prefix ? prefix + '/' + childFolder.getName() : childFolder.getName();",
    "    indexDriveFolder_(childFolder, nextPrefix, driveIndex);",
    "  }",
    "}",
    "",
    "function readDriveTextFileByPath_(relativePath, driveIndex) {",
    "  const fileId = driveIndex[relativePath];",
    "  if (!fileId) {",
    "    throw new Error('Drive asset not indexed: ' + relativePath + '. Re-upload drive-assets or rerun rebuildDriveAssetIndex().');",
    "  }",
    "",
    "  return DriveApp.getFileById(fileId).getBlob().getDataAsString();",
    "}",
    "",
    "function buildAssetBootstrap_(assetContext) {",
    "  const assetUrlMap = {};",
    "  const textAssetMap = {};",
    "  const textAssetMimeMap = {};",
    "",
    "  for (let index = 0; index < assetContext.assetManifest.assets.length; index += 1) {",
    "    const asset = assetContext.assetManifest.assets[index];",
    "    assetUrlMap[asset.id] = asset.serveMode === 'apps-script'",
    "      ? '__CH_APPS_SCRIPT_ASSET__'",
    "      : buildDriveAssetUrl_(asset, assetContext.driveIndex);",
    "",
    "    if (asset.serveMode === 'apps-script') {",
    "      textAssetMap[asset.id] = readDriveTextFileByPath_(asset.relativePath, assetContext.driveIndex);",
    "      textAssetMimeMap[asset.id] = asset.mimeType;",
    "    }",
    "  }",
    "",
    "  return [",
    "    '<script>(function(){',",
    "    'function buildAppsScriptAssetUrl_(assetId, rawMode){const assetBaseUrl = new URL(window.location.href);assetBaseUrl.search = \"\";assetBaseUrl.hash = \"\";const assetUrl = new URL(assetBaseUrl.toString());assetUrl.searchParams.set(\"asset\", assetId);if (rawMode) { assetUrl.searchParams.set(\"raw\", \"1\"); }return assetUrl.toString();}',",
    "    'function getTextAssetFetchId_(input){try{const requestUrl=typeof input === \"string\" ? input : input && input.url;if(!requestUrl){return null;}const parsedUrl=new URL(requestUrl, window.location.href);return parsedUrl.searchParams.get(\"asset\");}catch(error){return null;}}',",
    "    'const textAssetBlobUrlMap={};',",
    "    'function buildEmbeddedTextAssetUrl_(assetId){const mappedTextAsset=window.__CH_TEXT_ASSET__(assetId);if(typeof mappedTextAsset !== \"string\" || typeof URL === \"undefined\" || typeof Blob === \"undefined\"){return null;}if(textAssetBlobUrlMap[assetId]){return textAssetBlobUrlMap[assetId];}const mappedTextAssetMime=window.__CH_TEXT_ASSET_MIME_MAP__[assetId]||\"text/plain;charset=utf-8\";textAssetBlobUrlMap[assetId]=URL.createObjectURL(new Blob([mappedTextAsset],{type:mappedTextAssetMime}));return textAssetBlobUrlMap[assetId];}',",
    "    'window.__CH_ASSET_MAP__=' + toScriptSafeJson_(assetUrlMap) + ';',",
    "    'window.__CH_TEXT_ASSET_MAP__=' + toScriptSafeJson_(textAssetMap) + ';',",
    "    'window.__CH_TEXT_ASSET_MIME_MAP__=' + toScriptSafeJson_(textAssetMimeMap) + ';',",
    "    'window.__CH_ASSET__=function(assetId){var mapped = window.__CH_ASSET_MAP__[assetId];if(mapped === \"__CH_APPS_SCRIPT_ASSET__\"){return buildEmbeddedTextAssetUrl_(assetId)||buildAppsScriptAssetUrl_(assetId, false);}return mapped||assetId;};',",
    "    'window.__CH_TEXT_ASSET__=function(assetId){return window.__CH_TEXT_ASSET_MAP__[assetId]||null;};',",
    "    'window.__CH_ASSET_RAW__=function(assetId){return buildEmbeddedTextAssetUrl_(assetId)||buildAppsScriptAssetUrl_(assetId, true);};',",
    "    'const nativeFetch = window.fetch ? window.fetch.bind(window) : null;',",
    "    'if(nativeFetch && typeof window.Response === \"function\"){window.fetch=function(input, init){const assetId=getTextAssetFetchId_(input);const mappedTextAsset=assetId ? window.__CH_TEXT_ASSET__(assetId) : null;if(typeof mappedTextAsset === \"string\"){return Promise.resolve(new Response(mappedTextAsset,{status:200,headers:{\"Content-Type\":\"text/plain;charset=utf-8\"}}));}return nativeFetch(input, init);};}',",
    "    '})();</script>'",
    "  ].join('');",
    "}",
    "",
    "function buildAutosaveBootstrap_() {",
    "  if (!CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS.length) {",
    "    return '';",
    "  }",
    "",
    "  const autosaveConfig = {",
    "    projectSlug: CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG,",
    "    storageKeys: CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS,",
    "    metaKey: 'canvas-helper.apps-script-autosave.' + CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG + '.meta',",
    "    restoreGuardKey: 'canvas-helper.apps-script-autosave.' + CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG + '.restore'",
    "  };",
    "",
    "  return [",
    "    '<script>(function(){',",
    "    'const config=' + toScriptSafeJson_(autosaveConfig) + ';',",
    "    'const trackedKeySet=new Set(config.storageKeys);',",
    "    'let saveTimer=null;',",
    "    'let applyingRemote=false;',",
    "    'let lastSnapshot={};',",
    "    'function hasRunner(){return !!(window.google&&window.google.script&&window.google.script.run);}',",
    "    'function safeGetItem(key){try{return window.localStorage?localStorage.getItem(key):null;}catch(error){return null;}}',",
    "    'function safeSetItem(key,value){try{if(window.localStorage){localStorage.setItem(key,value);return true;}}catch(error){}return false;}',",
    "    'function readMeta(){try{return JSON.parse(safeGetItem(config.metaKey)||\"{}\");}catch(error){return {};}}',",
    "    'function writeMeta(value){safeSetItem(config.metaKey,JSON.stringify(value||{}));}',",
    "    'function getStorageValues(){const values={};config.storageKeys.forEach(function(key){const value=safeGetItem(key);if(value!==null){values[key]=value;}});return values;}',",
    "    'function valuesDiffer(left,right){return config.storageKeys.some(function(key){const hasLeft=Object.prototype.hasOwnProperty.call(left||{},key);const hasRight=Object.prototype.hasOwnProperty.call(right||{},key);return hasLeft!==hasRight || (hasLeft&&String(left[key])!==String(right[key]));});}',",
    "    'function hasValues(values){return !!values&&Object.keys(values).length>0;}',",
    "    'function setStatus(message,tone){try{let node=document.querySelector(\"[data-canvas-helper-apps-script-autosave]\");if(!node&&document.body){node=document.createElement(\"div\");node.setAttribute(\"data-canvas-helper-apps-script-autosave\",\"true\");node.style.cssText=\"position:fixed;right:14px;bottom:14px;z-index:2147483647;max-width:260px;padding:8px 10px;border:1px solid rgba(0,255,194,.35);border-radius:999px;background:rgba(4,10,18,.88);color:#d7fff6;font:600 11px/1.3 system-ui,sans-serif;box-shadow:0 12px 30px rgba(0,0,0,.28)\";document.body.appendChild(node);}if(node){node.textContent=message;node.setAttribute(\"data-tone\",tone||\"neutral\");}}catch(error){}}',",
    "    'function updateSnapshot(){lastSnapshot=getStorageValues();}',",
    "    'function detectAndQueueSave(reason){if(applyingRemote){return;}const nextSnapshot=getStorageValues();if(valuesDiffer(nextSnapshot,lastSnapshot)){lastSnapshot=nextSnapshot;queueSave(reason||\"change\");}}',",
    "    'function applyStorageValues(values,savedAt){applyingRemote=true;try{config.storageKeys.forEach(function(key){if(Object.prototype.hasOwnProperty.call(values||{},key)){safeSetItem(key,String(values[key]));}});writeMeta({savedAt:savedAt||\"\",source:\"apps-script\"});updateSnapshot();}finally{applyingRemote=false;}}',",
    "    'function reloadAfterRestore(savedAt){try{const signature=config.projectSlug+\":\"+(savedAt||\"\");if(sessionStorage.getItem(config.restoreGuardKey)===signature){return;}sessionStorage.setItem(config.restoreGuardKey,signature);}catch(error){}window.location.reload();}',",
    "    'function flushSave(reason){if(saveTimer){window.clearTimeout(saveTimer);saveTimer=null;}if(!hasRunner()||applyingRemote){return;}const storageValues=getStorageValues();lastSnapshot=storageValues;window.google.script.run.withSuccessHandler(function(result){writeMeta({savedAt:result&&result.savedAt?result.savedAt:new Date().toISOString(),source:\"apps-script\"});setStatus(\"Autosave ready\",\"saved\");}).withFailureHandler(function(error){setStatus(\"Autosave failed\",\"error\");console.warn(\"[apps-script-autosave]\",error);}).saveCanvasHelperAutosave({projectSlug:config.projectSlug,reason:reason||\"change\",storageValues:storageValues});}',",
    "    'function queueSave(reason){if(applyingRemote){return;}if(saveTimer){window.clearTimeout(saveTimer);}setStatus(\"Autosave queued\",\"working\");saveTimer=window.setTimeout(function(){saveTimer=null;flushSave(reason);},900);}',",
    "    'function restore(){if(!hasRunner()){setStatus(\"Autosave unavailable\",\"error\");return;}setStatus(\"Checking saved progress\",\"working\");window.google.script.run.withSuccessHandler(function(remote){const remoteValues=remote&&remote.storageValues?remote.storageValues:{};const localValues=getStorageValues();lastSnapshot=localValues;const localMeta=readMeta();if(hasValues(remoteValues)&&valuesDiffer(remoteValues,localValues)){if(hasValues(localValues)&&localMeta.savedAt&&remote.savedAt&&localMeta.savedAt>remote.savedAt){queueSave(\"local-newer\");return;}applyStorageValues(remoteValues,remote&&remote.savedAt?remote.savedAt:\"\");setStatus(\"Saved progress restored\",\"saved\");reloadAfterRestore(remote&&remote.savedAt?remote.savedAt:\"\");return;}if(hasValues(localValues)&&!hasValues(remoteValues)){queueSave(\"initial-local-state\");return;}setStatus(\"Autosave ready\",\"saved\");}).withFailureHandler(function(error){setStatus(\"Autosave unavailable\",\"error\");console.warn(\"[apps-script-autosave]\",error);}).getCanvasHelperAutosave();}',",
    "    'function scheduleRestore(){if(document.readyState===\"loading\"){document.addEventListener(\"DOMContentLoaded\",restore,{once:true});return;}window.setTimeout(restore,0);}',",
    "    'window.__CH_APPS_SCRIPT_AUTOSAVE__={save:function(){queueSave(\"manual\");},flush:function(){flushSave(\"manual\");},restore:restore};',",
    "    'updateSnapshot();',",
    "    'window.setInterval(function(){detectAndQueueSave(\"interval\");},1500);',",
    "    'window.addEventListener(\"storage\",function(event){if(event&&trackedKeySet.has(String(event.key))){detectAndQueueSave(\"storage-event\");}});',",
    "    'window.addEventListener(\"pagehide\",function(){detectAndQueueSave(\"pagehide\");flushSave(\"pagehide\");});',",
    "    'document.addEventListener(\"visibilitychange\",function(){if(document.visibilityState===\"hidden\"){detectAndQueueSave(\"visibilitychange\");flushSave(\"visibilitychange\");}});',",
    "    'scheduleRestore();',",
    "    '})();</script>'",
    "  ].join('');",
    "}",
    "",
    "function normalizeCanvasHelperAutosavePayload_(payload) {",
    "  if (!payload || payload.projectSlug !== CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG) {",
    "    throw new Error('Invalid Canvas Helper autosave payload.');",
    "  }",
    "",
    "  const incomingValues = payload.storageValues && typeof payload.storageValues === 'object' ? payload.storageValues : {};",
    "  const storageValues = {};",
    "  for (let index = 0; index < CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS.length; index += 1) {",
    "    const key = CANVAS_HELPER_AUTOSAVE_STORAGE_KEYS[index];",
    "    if (Object.prototype.hasOwnProperty.call(incomingValues, key) && incomingValues[key] !== null && incomingValues[key] !== undefined) {",
    "      storageValues[key] = String(incomingValues[key]);",
    "    }",
    "  }",
    "",
    "  return { storageValues: storageValues };",
    "}",
    "",
    "function getCanvasHelperAutosaveUserKey_() {",
    "  const temporaryKey = Session.getTemporaryActiveUserKey();",
    "  if (temporaryKey) {",
    "    return temporaryKey;",
    "  }",
    "",
    "  const activeEmail = Session.getActiveUser().getEmail();",
    "  if (activeEmail) {",
    "    return activeEmail;",
    "  }",
    "",
    "  return 'anonymous';",
    "}",
    "",
    "function getCanvasHelperAutosaveFolder_() {",
    "  const scriptProperties = PropertiesService.getScriptProperties();",
    "  const existingFolderId = scriptProperties.getProperty(CANVAS_HELPER_AUTOSAVE_FOLDER_ID_KEY);",
    "  if (existingFolderId) {",
    "    try {",
    "      return DriveApp.getFolderById(existingFolderId);",
    "    } catch (error) {",
    "      scriptProperties.deleteProperty(CANVAS_HELPER_AUTOSAVE_FOLDER_ID_KEY);",
    "    }",
    "  }",
    "",
    "  const folder = DriveApp.createFolder(CANVAS_HELPER_AUTOSAVE_FOLDER_NAME);",
    "  scriptProperties.setProperty(CANVAS_HELPER_AUTOSAVE_FOLDER_ID_KEY, folder.getId());",
    "  return folder;",
    "}",
    "",
    "function getCanvasHelperAutosaveFileName_(userKey) {",
    "  return 'autosave-' + hashCanvasHelperAutosaveKey_(userKey) + '.json';",
    "}",
    "",
    "function hashCanvasHelperAutosaveKey_(userKey) {",
    "  const bytes = Utilities.computeDigest(",
    "    Utilities.DigestAlgorithm.SHA_256,",
    "    CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG + ':' + userKey",
    "  );",
    "  let hash = '';",
    "  for (let index = 0; index < bytes.length; index += 1) {",
    "    let value = bytes[index];",
    "    if (value < 0) {",
    "      value += 256;",
    "    }",
    "    const hex = value.toString(16);",
    "    hash += hex.length === 1 ? '0' + hex : hex;",
    "  }",
    "  return hash;",
    "}",
    "",
    "function getCanvasHelperAutosaveFile_(userKey) {",
    "  const folder = getCanvasHelperAutosaveFolder_();",
    "  const files = folder.getFilesByName(getCanvasHelperAutosaveFileName_(userKey));",
    "  return files.hasNext() ? files.next() : null;",
    "}",
    "",
    "function readCanvasHelperAutosaveRecord_(userKey) {",
    "  const file = getCanvasHelperAutosaveFile_(userKey);",
    "  if (!file) {",
    "    return null;",
    "  }",
    "",
    "  try {",
    "    return JSON.parse(file.getBlob().getDataAsString());",
    "  } catch (error) {",
    "    return null;",
    "  }",
    "}",
    "",
    "function writeCanvasHelperAutosaveRecord_(userKey, record) {",
    "  const folder = getCanvasHelperAutosaveFolder_();",
    "  const fileName = getCanvasHelperAutosaveFileName_(userKey);",
    "  const json = JSON.stringify(record);",
    "  const files = folder.getFilesByName(fileName);",
    "  if (files.hasNext()) {",
    "    files.next().setContent(json);",
    "    return;",
    "  }",
    "",
    "  const file = folder.createFile(fileName, json, MimeType.PLAIN_TEXT);",
    "  file.setDescription('Canvas Helper Apps Script autosave for ' + CANVAS_HELPER_AUTOSAVE_PROJECT_SLUG);",
    "}",
    "",
    "function toScriptSafeJson_(value) {",
    "  return JSON.stringify(value).replace(/<\\//g, '<\\\\/');",
    "}",
    "",
    "function buildDriveAssetUrl_(asset, driveIndex) {",
    "  const fileId = driveIndex[asset.relativePath];",
    "  if (!fileId) {",
    "    throw new Error('Drive-backed asset is missing: ' + asset.relativePath);",
    "  }",
    "",
    "  if (asset.mimeType && asset.mimeType.indexOf('image/') === 0) {",
    "    return 'https://drive.google.com/thumbnail?id=' + encodeURIComponent(fileId) + '&sz=w4000';",
    "  }",
    "",
    "  return 'https://drive.google.com/uc?export=download&id=' + encodeURIComponent(fileId);",
    "}",
    "",
    "function createTextOutput_(textContent, mimeType, rawMode) {",
    "  if (mimeType === 'text/html' && !rawMode) {",
    "    return HtmlService.createHtmlOutput(textContent)",
    "      .setTitle(CANVAS_HELPER_PROJECT_TITLE)",
    "      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);",
    "  }",
    "",
    "  const textOutput = ContentService.createTextOutput(textContent);",
    "  if (rawMode) {",
    "    textOutput.setMimeType(ContentService.MimeType.TEXT);",
    "    return textOutput;",
    "  }",
    "",
    "  switch (mimeType) {",
    "    case 'application/json':",
    "    case 'text/json':",
    "      textOutput.setMimeType(ContentService.MimeType.JSON);",
    "      break;",
    "    case 'text/javascript':",
    "    case 'application/javascript':",
    "      textOutput.setMimeType(ContentService.MimeType.JAVASCRIPT);",
    "      break;",
    "    case 'application/xml':",
    "    case 'text/xml':",
    "    case 'image/svg+xml':",
    "      textOutput.setMimeType(ContentService.MimeType.XML);",
    "      break;",
    "    default:",
    "      textOutput.setMimeType(ContentService.MimeType.TEXT);",
    "      break;",
    "  }",
    "",
    "  return textOutput;",
    "}",
    "",
    "function injectHtmlTag_(html, tagMarkup) {",
    "  if (/<head\\b[^>]*>/i.test(html)) {",
    "    return html.replace(/<head\\b[^>]*>/i, function(match) {",
    "      return match + tagMarkup;",
    "    });",
    "  }",
    "",
    "  if (/<body\\b[^>]*>/i.test(html)) {",
    "    return html.replace(/<body\\b[^>]*>/i, function(match) {",
    "      return match + tagMarkup;",
    "    });",
    "  }",
    "",
    "  return tagMarkup + html;",
    "}",
    ""
  ].join("\n");
}

type BuildAppsScriptDeployReadmeOptions = {
  driveAssetFileCount: number;
  projectSlug: string;
  projectTitle: string;
  shellFileCount: number;
  storageKeys: string[];
};

export function buildAppsScriptDeployReadme(options: BuildAppsScriptDeployReadmeOptions) {
  return [
    "# Apps Script Deployment",
    "",
    `- Project title: ${options.projectTitle}`,
    `- Project slug: ${options.projectSlug}`,
    `- Apps Script shell files: ${options.shellFileCount}`,
    `- Google Drive asset files: ${options.driveAssetFileCount}`,
    "",
    "## What This Package Is",
    "",
    "- A clasp-ready Apps Script shell that serves the Canvas Helper app from Google Apps Script.",
    "- A `drive-assets/` folder that must be uploaded to Google Drive for the web app to read project files.",
    "- A Google Sites-friendly web app package that keeps delivery inside the Google ecosystem.",
    "- An Apps Script autosave bridge that syncs tracked browser progress keys to private JSON files in the script owner's Drive.",
    "",
    "## Autosave",
    "",
    `- Tracked localStorage keys: ${options.storageKeys.length ? options.storageKeys.join(", ") : "(none detected)"}`,
    "- The generated page patches localStorage and also listens for storage events from same-origin frames.",
    "- Server functions `getCanvasHelperAutosave()` and `saveCanvasHelperAutosave(payload)` store one JSON file per active Google user key.",
    "- Apps Script creates a private `Canvas Helper Autosaves - <slug>` folder in the script owner's Drive on first save or restore.",
    "",
    "## Deployment Flow",
    "",
    "1. Upload the generated `drive-assets/` folder to Google Drive.",
    "2. Create or link a standalone Apps Script project for this export.",
    "3. Push the shell files with `clasp push`.",
    "4. In the Apps Script editor, run `setDriveRootFolderId('YOUR_DRIVE_FOLDER_ID')`.",
    "5. If you replace Drive files later, rerun `rebuildDriveAssetIndex()`.",
    "6. Deploy the script as a web app and use the `/exec` URL in Google Sites.",
    "",
    "## clasp Notes",
    "",
    "- `.claspignore` excludes `drive-assets/` because those files belong in Google Drive, not in Apps Script source.",
    "- If `.clasp.json` already exists in this export folder, the exporter preserves it across re-runs.",
    "",
    "## Google Sites Embed",
    "",
    "1. Deploy the web app from Apps Script.",
    "2. Copy the `/exec` URL.",
    "3. In Google Sites, use `Insert > Embed > By URL` and paste the Apps Script URL.",
    "",
    "## Google Drive Access Notes",
    "",
    "- Binary files are Drive-backed, so viewers still need access to the uploaded Drive assets.",
    "- If an asset is missing after upload, rerun `setDriveRootFolderId(...)` or `rebuildDriveAssetIndex()`.",
    "- The generated shell injects `window.__CH_ASSET__` at runtime so the exported course can resolve Drive and Apps Script asset URLs.",
    ""
  ].join("\n");
}
