import { load } from "cheerio";
import type { Standard } from "./course-standards.js";
export type Lesson = {title:string;outcomes:string[];sources:string[];exemplar:string;sections:Record<string,{text:string;purpose?:string;instructions?:string;reasoningSteps?:{action:string;why:string}[];check?:{choices:string[];correctIndex:number;feedback:string}}>};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function checkStandardLesson(lesson:Lesson,s:Standard,allowDraft=false) {
 const errors:string[]=[];
 if(!lesson.title||!lesson.outcomes.length||!lesson.sources.length||!lesson.exemplar)errors.push("Title, Alberta outcomes, sources and teacher exemplar required.");
 for(const stage of s.blueprint){ const slot=lesson.sections[stage]; if(!slot?.text)errors.push(`Missing ${stage}`); else {if(slot.text.split(/\s+/).length>s.rules.maxParagraphWords)errors.push(`${stage}: paragraph ceiling exceeded`); if(["guided","independent-check"].includes(stage)&&(!slot.purpose||!slot.instructions))errors.push(`${stage}: purpose and instructions required`);} }
 if(s.rules.modeledReasoningBeforeGuided && JSON.stringify(s.blueprint)!==JSON.stringify(["context","explanation","worked","modeled-reasoning","guided","independent-check"]))errors.push("Conflicting modeled-reasoning blueprint.");
 if(s.rules.modeledReasoningBeforeGuided){const steps=lesson.sections["modeled-reasoning"]?.reasoningSteps;if(!steps||steps.length<2||steps.some(step=>!step.action?.trim()||!step.why?.trim()))errors.push("Modeled reasoning requires at least two action-and-why steps before guided practice.");}
 if(!allowDraft && JSON.stringify(lesson).includes("Author:"))errors.push("Unfilled authoring slots require completion before release.");
 if(!allowDraft && !lesson.sections["independent-check"]?.check)errors.push("Independent check requires choices, answer key and explanatory feedback.");
 for(const slot of Object.values(lesson.sections)){if(slot.check&&(!slot.check.feedback||slot.check.choices.length<2||!Number.isInteger(slot.check.correctIndex)||slot.check.correctIndex<0||slot.check.correctIndex>=slot.check.choices.length))errors.push("Invalid answer key.");}
 return errors;
}
export function renderStandardLesson(lesson:Lesson,s:Standard,allowDraft=false) {
 const errors=checkStandardLesson(lesson,s,allowDraft); if(errors.length)throw new Error(errors.join(" "));
 return `<section class="standard-lesson" data-standard="${escape(s.id)}" data-reading-grade="${s.rules.targetGrade}"><h2>${escape(lesson.title)}</h2><p data-lesson-outcomes>Outcomes: ${lesson.outcomes.map(escape).join('; ')}</p>${s.blueprint.map((stage,i)=>`<section id="lesson-${stage}" data-lesson-stage="${stage}"><h3>${escape(stage.replaceAll('-',' '))}</h3><p data-canvas-helper-edit-key="lesson-${stage}-text">${escape(lesson.sections[stage].text)}</p>${lesson.sections[stage].reasoningSteps?`<ol data-modeled-reasoning>${lesson.sections[stage].reasoningSteps!.map((step,j)=>`<li data-canvas-helper-edit-key="modeled-step-${j}"><p data-reasoning-action>${escape(step.action)}</p><p data-reasoning-why><strong>Why:</strong> ${escape(step.why)}</p></li>`).join('')}</ol>`:''}${lesson.sections[stage].purpose?`<p data-lesson-purpose><strong>Purpose:</strong> ${escape(lesson.sections[stage].purpose!)}</p><p data-lesson-instructions><strong>Instructions:</strong> ${escape(lesson.sections[stage].instructions!)}</p><label>Your reasoning <textarea data-lesson-answer="${stage}" aria-label="${stage} reasoning"></textarea></label>`:''}${lesson.sections[stage].check?`<fieldset data-lesson-check data-correct="${lesson.sections[stage].check!.correctIndex}"><legend>Check your understanding</legend>${lesson.sections[stage].check!.choices.map((choice,j)=>`<label><input type="radio" name="check-${stage}" value="${j}">${escape(choice)}</label>`).join('')}<button type="button" data-check-answer>Check answer</button><p role="status" data-check-feedback data-explanation="${escape(lesson.sections[stage].check!.feedback)}"></p></fieldset>`:''}${i<s.blueprint.length-1?`<a class="next-step" href="#lesson-${s.blueprint[i+1]}">Next step</a>`:''}</section>`).join('')}<details><summary>Sources and teacher exemplar</summary><p data-lesson-sources>${lesson.sources.map(escape).join('; ')}</p><p data-lesson-exemplar>${escape(lesson.exemplar)}</p></details><p role="status" data-lesson-save-status></p></section>`;
}
export const standardLessonStyles=`.course-index{background:#182331;color:#fff;padding:1.25rem}.course-index a{color:#fff}.standard-lesson{max-width:68ch;line-height:1.7}.standard-lesson section{scroll-margin-top:5rem;margin-block:2rem}.standard-lesson textarea{display:block;width:100%;min-height:6rem}.standard-lesson fieldset{min-width:0}.standard-lesson fieldset label{display:block;margin:.5rem 0}.next-step{display:inline-block;padding:.6rem 0}@media(max-width:700px){.course-layout{display:block}.course-index{position:static}.standard-lesson{width:100%}}`;
export const standardLessonScript=`(()=>{const root=document.querySelector('[data-standard]');if(!root)return;const key='canvas-standard:'+document.body.dataset.projectSlug;for(const check of root.querySelectorAll('[data-lesson-check]')){check.querySelector('[data-check-answer]').addEventListener('click',()=>{const selected=check.querySelector('input:checked');const feedback=check.querySelector('[data-check-feedback]');feedback.textContent=selected?(selected.value===check.dataset.correct?'Correct. ':'Try again. ')+feedback.dataset.explanation:'Choose an answer first.'})}let answers={};let storage=true;try{const saved=JSON.parse(localStorage.getItem(key)||'{}');answers=saved&&typeof saved==='object'&&!Array.isArray(saved)?saved:{}}catch{storage=false}const status=root.querySelector('[data-lesson-save-status]');for(const field of root.querySelectorAll('[data-lesson-answer]')){field.value=typeof answers[field.dataset.lessonAnswer]==='string'?answers[field.dataset.lessonAnswer]:'';field.addEventListener('input',()=>{answers[field.dataset.lessonAnswer]=field.value;try{localStorage.setItem(key,JSON.stringify(answers));status.textContent='Saved on this device.'}catch{status.textContent='Saving unavailable. Keep a copy before leaving.'}})}status.textContent=storage?'Answers resume on this device.':'Saving unavailable.'})();`;
export function starterLesson(title:string,standard?:Standard):Lesson{return {title:'Lesson blueprint: '+title,outcomes:['Author: map the exact Alberta outcome before release.'],sources:['Author: add curriculum/source identity and location.'],exemplar:'Teacher exemplar: compare Biology30 chapters 12/13; select subject-appropriate tools.',sections:Object.fromEntries((standard?.blueprint??['context','explanation','worked','guided','independent-check']).map(stage=>[stage,{text:'Author: replace this '+stage+' slot with a self-teaching explanation or task.',...(stage==='modeled-reasoning'?{reasoningSteps:[{action:'Author: show the first reasoning action.',why:'Author: explain why this step is useful.'},{action:'Author: show the next reasoning action.',why:'Author: connect it to the conclusion.'}]}:{}),...(['guided','independent-check'].includes(stage)?{purpose:'Author: explain why this task matters.',instructions:'Author: state the steps, expected evidence and feedback.'}:{})}]))};}

export function checkStandardHtml(html:string,s:Standard){
 const $=load(html);const errors:string[]=[];const lesson=$('.standard-lesson');
 if(!lesson.length)return ['No standard lesson blueprint found.'];
 if(lesson.attr('data-standard')!==s.id)errors.push('Rendered standard does not match pinned version.');
 if(lesson.text().includes('Author:'))errors.push('Unfilled authoring slots.');
 for(const stage of s.blueprint){const section=lesson.find(`[data-lesson-stage="${stage}"]`);if(section.length!==1)errors.push(`Missing or duplicate ${stage}.`);if(section.find('p[data-canvas-helper-edit-key]').text().trim().split(/\s+/).length>s.rules.maxParagraphWords)errors.push(`${stage}: paragraph ceiling exceeded.`);if(['guided','independent-check'].includes(stage)&&(!section.find('[data-lesson-purpose]').text().trim()||!section.find('[data-lesson-instructions]').text().trim()))errors.push(`${stage}: purpose and instructions required.`);}
 if(s.rules.modeledReasoningBeforeGuided){const order=lesson.find('[data-lesson-stage]').map((_,el)=>$(el).attr('data-lesson-stage')).get();if(JSON.stringify(order)!==JSON.stringify(s.blueprint))errors.push('Teaching sequence must place worked example and modeled reasoning before guided practice.');const steps=lesson.find('[data-lesson-stage="modeled-reasoning"] [data-modeled-reasoning] > li');if(steps.length<2||steps.toArray().some(el=>!$(el).find('[data-reasoning-action]').text().trim()||!$(el).find('[data-reasoning-why]').text().trim()))errors.push('Modeled reasoning requires at least two action-and-why steps.');}
 for(const field of ['outcomes' ,'sources','exemplar'])if(!lesson.find(`[data-lesson-${field}]`).text().trim())errors.push(`Missing ${field}.`);
 const check=lesson.find('[data-lesson-stage="independent-check"] [data-lesson-check]');if(!check.length||!check.find('[data-check-feedback]').attr('data-explanation')||check.find('input[type=radio]').length<2)errors.push('Independent answer key and explanatory feedback required.');
 return errors;
}

export function inspectModeledReasoningEvidence(html:string){
 const $=load(html);const lesson=$('.standard-lesson');const order=lesson.find('[data-lesson-stage]').map((_,el)=>$(el).attr('data-lesson-stage')).get();
 const worked=order.indexOf('worked');const guided=order.indexOf('guided');
 const eligible=lesson.length===1&&worked>=0&&guided>worked&&!lesson.find('[data-modeled-reasoning]').length;
 return {eligible,description:eligible?'Canonical lesson contains a worked stage before guided practice, but no explicit action-and-why modeled reasoning list.':'No eligible preserved lesson structure found.'};
}
