"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER16

a=Art(16,'chromosome','One chromosome before and after replication',3,'Replication doubles DNA amount without initially doubling chromosome number. The two sister chromatids remain one replicated chromosome until they separate.')
a.box(90,170,390,390,'Before S phase');a.chr(290,375,BLUE,False,2);a.label('A',120,350,'One unreplicated chromosome',290,330)
a.arrow(510,365,690,365);a.text(600,325,'DNA replication',23,TEAL,'middle');a.box(750,170,560,390,'After S phase');a.chr(1020,380,BLUE,True,2)
a.label('B',820,310,'Sister chromatid',986,300);a.label('C',1220,310,'Sister chromatid',1054,300);a.label('D',1210,485,'Centromere region',1020,380)
a.text(300,640,'1 chromosome · 1 DNA molecule',25,INK,'middle');a.text(1015,640,'1 chromosome · 2 DNA molecules',25,INK,'middle');a.save()
a=Art(16,'mitosis','Mitosis in a model cell: 2n = 4',4,'Four replicated chromosomes align individually; sister chromatids separate. Each daughter nucleus receives four chromosomes. Blue and orange identify parental origins, not different cell types.')
for i,stage in enumerate(['Prophase','Metaphase','Anaphase','Telophase']):
 x=180+i*345;a.ellipse(x,390,150,180,'#f7f8f5',TEAL);a.label(chr(65+i),x,175,stage)
 if i==0:
  for j,(xx,yy,c,sc)in enumerate([(-55,-50,BLUE,1),(45,-45,ORANGE,1),(-45,65,BLUE,.6),(55,55,ORANGE,.6)]):a.chr(x+xx,390+yy,c,True,sc)
 elif i==1:
  for j,c in enumerate([BLUE,ORANGE,BLUE,ORANGE]):a.chr(x,285+j*70,c,True,.65 if j<2 else .39)
 elif i==2:
  for side in [-1,1]:
   for j,c in enumerate([BLUE,ORANGE,BLUE,ORANGE]):a.chr(x+side*78,294+j*62,c,False,.55 if j<2 else .33)
 else:
  for side in [-1,1]:
   a.ellipse(x+side*75,390,59,125,'#eef3ef',TEAL,2)
   for j,c in enumerate([BLUE,ORANGE,BLUE,ORANGE]):a.chr(x+side*75,320+j*46,c,False,.43 if j<2 else .258)
 a.text(x,625,['Condense','Align singly','Separate sisters','Re-form nuclei'][i],24,INK,'middle')
a.text(700,700,'During anaphase: 8 chromosomes in the whole undivided cell, 4 moving toward each pole.',23,MUTED,'middle');a.save()
a=Art(16,'meiosis','Meiosis: separate homologues, then sisters',7,'A diploid 2n = 4 model begins after replication. Meiosis I produces two haploid cells with replicated chromosomes. Meiosis II separates sisters into four haploid products.')
a.ellipse(215,390,160,205,'#f8faf7',TEAL)
for x,y,c,sc in [(170,315,BLUE,1),(255,315,ORANGE,1),(170,475,BLUE,.65),(255,475,ORANGE,.65)]:a.chr(x,y,c,True,sc)
a.label('A',215,145,'Replicated diploid cell');a.arrow(395,300,530,265);a.arrow(395,490,530,530)
for j,y in enumerate([265,530]):
 a.ellipse(650,y,112,100,'#f4f8f1',TEAL);a.chr(620,y,BLUE if j==0 else ORANGE,True,.85);a.chr(690,y,ORANGE if j==0 else BLUE,True,.5)
a.label('B',650,140,'Haploid cells after meiosis I');a.text(450,670,'Homologues separate',23,INK,'middle')
for j,y in enumerate([205,365,525,685]):
 a.ellipse(1160,y,115,67,'#f4f8f1',TEAL);a.chr(1115,y,BLUE if j<2 else ORANGE,False,.6);a.chr(1200,y,ORANGE if j<2 else BLUE,False,.4)
a.arrow(780,250,1020,205);a.arrow(780,280,1020,365);a.arrow(780,510,1020,525);a.arrow(780,555,1020,685)
a.label('C',1170,140,'Haploid cells after meiosis II');a.text(920,735,'Sister chromatids separate',22,INK,'middle');a.save()
a=Art(16,'crossing-over','Crossing over involves non-sister chromatids',8,'Two replicated homologues contain four chromatids. Exchange between one chromatid from each homologue can produce two recombinant and two unchanged chromatids.')
for j,(y,c)in enumerate([(240,BLUE),(315,BLUE),(460,ORANGE),(535,ORANGE)]):
 a.line(160,y,575,y,c,15);a.text(125,y+9,'A'if c==BLUE else'a',24,c,'middle');a.text(605,y+9,'B'if c==BLUE else'b',24,c,'middle')
a.line(350,315,450,460,PURPLE,4);a.line(350,460,450,315,PURPLE,4);a.label('A',420,650,'Non-sister chromatids',400,385)
a.arrow(680,385,810,385)
for y,left,right,lbl1,lbl2 in [(240,BLUE,BLUE,'A','B'),(315,BLUE,ORANGE,'A','b'),(460,ORANGE,BLUE,'a','B'),(535,ORANGE,ORANGE,'a','b')]:
 a.line(880,y,1050,y,left,15);a.line(1050,y,1250,y,right,15);a.text(850,y+8,lbl1,24,left,'middle');a.text(1280,y+8,lbl2,24,right,'middle')
a.label('B',1010,160,'Parental chromatid',1030,240);a.label('C',1235,385,'Recombinant chromatid',1150,315);a.label('D',1020,650,'Parental chromatid',1080,535);a.save()
a=Art(16,'nondisjunction','Nondisjunction: compare the gamete outcomes',10,'For one affected chromosome, a meiosis I error produces two n + 1 and two n − 1 gametes; a one-cell meiosis II error produces two normal, one n + 1 and one n − 1 gamete.')
for row,(y,answer,counts)in enumerate([(250,'Meiosis I nondisjunction',[2,2,0,0]),(535,'Meiosis II nondisjunction',[1,1,2,0])]):
 a.label(chr(65+row),100,y,answer)
 for i,count in enumerate(counts):
  x=380+i*280;a.circle(x,y,88,'#f3f7f2',TEAL)
  for j in range(count):a.chr(x+(j-(count-1)/2)*35,y,BLUE,False,.8)
  a.text(x,y+125,{0:'n − 1',1:'n',2:'n + 1'}[count],26,INK,'middle')
a.text(700,730,'Only the affected chromosome is shown; the rest of the chromosome set is omitted.',22,MUTED,'middle');a.save()
flow(16,'alternation','Alternation of generations',12,[('Sporophyte (2n)','Diploid multicellular generation'),('Meiosis','Chromosome-set number is reduced'),('Spore (n)','Haploid cell develops by mitosis'),('Gametophyte (n)','Haploid multicellular generation'),('Gametes (n)','Produced by mitosis in this generation'),('Fertilization','Gametes join to form a 2n zygote')],'Spores grow into gametophytes by mitosis. Fertilization restores diploidy, and mitosis grows the zygote into a sporophyte.')


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[16];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[16],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',16,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
