import {escapeHTML as h,asset,panel,scene,prediction,table,field,selectField,explanation,checkButtons,formGate,modelGate} from './ui.js';
function symbol(value){const v=String(value||'').toLowerCase();if(!v)return'<span class="equipment-placeholder">Choose a form</span>';let cell=v.includes('food')?[2,1]:v.includes('plant')?[3,1]:v.includes('battery')?[0,1]:v.includes('generator')?[1,0]:v.includes('motor')?[1,1]:v.includes('light')||v.includes('lamp')?[3,0]:v.includes('electrical')?[2,0]:v.includes('wind')||v.includes('moving air')||v.includes('kinetic')||v==='mechanical input'?[0,0]:null;if(cell)return `<span class="equipment-cutout" aria-hidden="true"><img src="${asset('assets/premium/equipment-atlas-v1.png')}" alt="" style="left:${-cell[0]*100}%;top:${-cell[1]*100}%"></span>`;const n=v.includes('sun')?'sun':v.includes('thermal')?'thermal':v.includes('sound')?'sound':'motion';return `<img class="equipment-symbol" src="${asset('assets/sprites/sprite_'+n+'.png')}" alt="">`;}
function account(s,m){const values=Object.keys(s.whole_system).map(k=>m.modelInputs['out_'+k]);const complete=values.every(v=>v!==''&&v!=null&&Number.isFinite(Number(v)));const total=complete?values.reduce((a,v)=>a+Number(v),0):'Not complete';return table(['Input','Allocated','Difference'],[[s.input+' J',total==='Not complete'?total:total+' J',complete?(s.input-total)+' J':'Not complete']],'Your current energy account');}
export function render(s,m,transfer=false){
 const path=s.path.map((_,i)=>`<div class="path-slot"><span class="slot-letter">${String.fromCharCode(65+i)}</span><div data-path-icon="${i}">${symbol(m.modelInputs['path'+i])}</div><span class="path-role">${i===0?'Energy source':i===s.path.length-1?'Output':'Transformation / transfer'}</span>${selectField('path'+i,'Pathway step '+(i+1),m.modelInputs['path'+i],s.pathOptions.map(v=>[v,v]))}</div>`).join('');
 const outputs=Object.keys(s.whole_system).map(k=>field('out_'+k,k.replace('_',' ')+' output',m.modelInputs['out_'+k],'J')).join('');
 return panel(transfer?'Fresh Transfer':'Rescue Mission',1,transfer?'Conventional data':'Purpose defines useful output',(transfer?'':scene(s,'Context illustration of an energy conversion system'))+`<h3>Purpose: ${h(s.purpose)}</h3><p>Whole-system input: ${s.input} J.</p><p>${h(s.records)}</p>${s.matterNote?`<div class="callout"><p>${h(s.matterNote)}</p></div>`:''}`+(transfer?'':prediction(s,m)))+
 panel(transfer?'Your Account':'Energy Pathway',2,transfer?'No animation or hints':'Route and allocate every joule',formGate(m,transfer?'<p>Use the supplied source and output data to construct the account independently.</p>':`<div class="energy-account">${path}</div>`,transfer))+
 panel('Energy Account & Reasoning',3,'Nothing disappears',formGate(m,outputs+(transfer?field('fraction','Useful fraction',m.modelInputs.fraction,'%'):''),transfer)+`<div id="live-account">${!transfer||m.firstTransferResponse?modelGate(m,account(s,m),transfer):'<p>Complete the account independently before checking.</p>'}</div>`+explanation(m.explanation,s.explanationPrompt)+checkButtons(m,transfer));
}
export function refresh(root,s,m){const el=root.querySelector('#live-account');if(el&&(m.predictionLocked||m.firstTransferResponse))el.innerHTML=account(s,m);root.querySelectorAll('[data-path-icon]').forEach(el=>el.innerHTML=symbol(m.modelInputs['path'+el.dataset.pathIcon]));}
export function worked(){}
