(() => {
  const app = document.getElementById('app');
  const scenarios = window.RD_SCENARIOS;
  const state = {screen:'intro',index:0,tokens:2,revealed:[],selected:[],conclusion:null,reaction:null,explanation:'',attempts:[],hints:0,results:{}};
  const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function resetCase(){state.tokens=2;state.revealed=[];state.selected=[];state.conclusion=null;state.reaction=null;state.explanation='';state.attempts=[];state.hints=0;}
  function steps(active){const names=['Brief','Worked example','Your turn','Feedback','Transfer','Review'];return `<div class="progress">${names.map((n,i)=>`<span class="step ${i<active?'done':''} ${i===active?'active':''}">${i+1}. ${n}</span>`).join('')}</div>`}
  function intro(){app.innerHTML=`<section class="hero"><div class="eyebrow">Game A1</div><h1>Reaction Detective</h1><p class="muted">Use evidence to explain a change.</p>${steps(0)}</section><section class="intro-grid"><article class="panel intro-card"><h2>Your mission</h2><p>Investigate supplied science records, decide what the evidence supports, and explain what happened.</p><img class="scene" src="assets/scenes/scene_01_peroxide.png" alt="Contextual laboratory glassware image"></article><article class="panel intro-card"><h2>What you’ll practise</h2><ul><li>Evidence of chemical change</li><li>Physical vs chemical change</li><li>Reaction classification</li><li>Evidence-based explanations</li></ul></article><article class="panel intro-card"><h2>How it works</h2><ol><li>Inspect the situation.</li><li>Build a claim from evidence.</li><li>Explain your reasoning and use feedback.</li></ol><p><strong>Speed is not scored.</strong></p></article></section><div class="strip"><span>5 cases + 1 independent transfer</span><button class="btn btn-primary big-action" id="start">Start investigation →</button></div>`;document.getElementById('start').onclick=()=>{state.screen='worked';state.index=0;render()}}
  function worked(){const s=scenarios[0];app.innerHTML=`<section class="hero"><div class="eyebrow">Worked example</div><h1>${esc(s.title)}</h1><p>This round demonstrates the full reasoning process. It does not count as independent evidence.</p>${steps(1)}</section><section class="grid"><article class="panel"><h2>The Case</h2><div class="content"><img class="scene" src="${s.image}" alt="Contextual lab reaction image"><p>${esc(s.caseText)}</p></div></article><article class="panel"><h2>The Evidence</h2><div class="content evidence-list">${s.evidence.map(e=>`<div class="card"><strong>${esc(e.label)}</strong><span>${esc(e.detail)}</span></div>`).join('')}</div></article><article class="panel"><h2>Watch the reasoning</h2><div class="content"><ol><li><strong>Claim:</strong> Chemical change.</li><li><strong>Strong evidence:</strong> Water and oxygen are identified as products.</li><li><strong>Classification:</strong> Decomposition.</li><li><strong>Explanation:</strong> ${esc(s.model)}</li></ol><div class="feedback"><strong>Key idea:</strong> new substance identities are stronger evidence than bubbles alone.</div></div></article></section><div class="strip"><span>Worked example complete.</span><button class="btn btn-primary" id="next">Next: Your Turn →</button></div>`;document.getElementById('next').onclick=()=>{state.screen='practice';state.index=1;resetCase();render()}}
  function practice(){const s=scenarios[state.index];const isTransfer=s.stage==='transfer';const active=isTransfer?4:2;app.innerHTML=`<section class="hero"><div class="eyebrow">${isTransfer?'Independent transfer — no hints':'Case '+state.index+' of 4'}</div><h1>${esc(s.title)}</h1><p>${esc(s.caseText)}</p>${steps(active)}</section><section class="grid"><article class="panel"><h2>The Case</h2><div class="content"><img class="scene" src="${s.image}" alt="Context image for ${esc(s.title)}"><h3>Base observations</h3><ul>${s.base.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${!isTransfer?`<p class="token">Investigation tokens: ${state.tokens}</p>`:''}</div></article><article class="panel"><h2>${isTransfer?'Recorded Evidence':'Investigate'}</h2><div class="content evidence-list">${isTransfer?`<div class="card"><strong>Supplied record</strong><span>The substance before and after is water (H₂O).</span></div>`:s.evidence.map(e=>{const rev=state.revealed.includes(e.id);return `<div class="card ${rev?'':'locked'}"><strong>${esc(e.label)}</strong><span>${rev?esc(e.detail):'Not revealed yet.'}</span>${rev?`<label class="check-row"><input type="checkbox" data-evidence="${e.id}" ${state.selected.includes(e.id)?'checked':''}> Use as support</label>`:`<button class="btn btn-secondary reveal" data-id="${e.id}" ${state.tokens<=0?'disabled':''}>Reveal record</button>`}</div>`}).join('')}</div></article><article class="panel"><h2>Your Reasoning</h2><div class="content"><fieldset><legend><strong>What does the evidence support?</strong></legend>${[['physical','Physical change'],['chemical','Chemical change'],['insufficient','Not enough evidence']].map(([v,l])=>`<label class="choice radio-row"><input type="radio" name="conclusion" value="${v}" ${state.conclusion===v?'checked':''}> <span>${l}</span></label>`).join('')}</fieldset>${s.reaction!=='none'?`<label><strong>Reaction type</strong><select id="reaction"><option value="">Choose…</option>${[['decomposition','Decomposition'],['corrosion','Rusting / corrosion'],['composition','Composition'],['neutralization','Neutralization / acid–base'],['combustion','Combustion']].map(([v,l])=>`<option value="${v}" ${state.reaction===v?'selected':''}>${l}</option>`).join('')}</select></label>`:''}<label><strong>Explain your reasoning</strong><textarea id="explanation" placeholder="Use specific evidence from the supplied record.">${esc(state.explanation)}</textarea></label><div class="actions"><button class="btn btn-primary" id="submit">${isTransfer?'Submit transfer':'Check claim'}</button>${!isTransfer&&state.attempts.length?`<button class="btn btn-secondary" id="hint">Hint ${Math.min(state.hints+1,3)} of 3</button>`:''}</div><div id="feedbackBox"></div></div></article></section><div class="strip"><span>${isTransfer?'Speed is not scored. Take the time to think.':'Select evidence because it is relevant, not because it looks dramatic.'}</span><button class="btn btn-secondary" id="reset">Reset case</button></div>`;
    document.querySelectorAll('.reveal').forEach(b=>b.onclick=()=>{if(state.tokens>0&&!state.revealed.includes(b.dataset.id)){state.revealed.push(b.dataset.id);state.tokens--;render()}});
    document.querySelectorAll('[data-evidence]').forEach(c=>c.onchange=()=>{if(c.checked){if(state.selected.length>=2){c.checked=false;return}state.selected.push(c.dataset.evidence)}else state.selected=state.selected.filter(x=>x!==c.dataset.evidence)});
    document.querySelectorAll('input[name=conclusion]').forEach(r=>r.onchange=()=>state.conclusion=r.value);
    const reaction=document.getElementById('reaction');if(reaction)reaction.onchange=()=>state.reaction=reaction.value;
    document.getElementById('explanation').oninput=e=>state.explanation=e.target.value;
    document.getElementById('reset').onclick=()=>{resetCase();render()};
    const hint=document.getElementById('hint');if(hint)hint.onclick=()=>showHint(s);
    document.getElementById('submit').onclick=()=>submit(s,isTransfer);
  }
  function submit(s,isTransfer){const feedback=document.getElementById('feedbackBox');const acceptedReaction=s.acceptedReaction||[s.reaction];const conclusionOK=state.conclusion===s.conclusion;const reactionOK=s.reaction==='none'||acceptedReaction.includes(state.reaction);const strongOK=isTransfer||s.strong.length===0||state.selected.some(id=>s.strong.includes(id));const explanationPresent=state.explanation.trim().length>=15;const structuredOK=conclusionOK&&reactionOK&&strongOK;state.attempts.push({conclusion:state.conclusion,reaction:state.reaction,evidence:[...state.selected],explanation:state.explanation,structuredOK});
    let msg;if(!state.conclusion)msg='Choose a conclusion before submitting.';else if(!conclusionOK)msg=state.conclusion==='chemical'?'What evidence establishes a new substance? Bubbles or temperature change alone are not enough.':'Re-check what the identity/product records establish.';else if(!reactionOK)msg='Your change classification is on track. Compare the stated reactants and products with the reaction-type definitions.';else if(!strongOK)msg='Your conclusion may be defensible, but select evidence that most directly establishes substance identity.';else if(!explanationPresent)msg='Your structured choices are on track. Add a short explanation that names the evidence and connects it to the claim.';else msg='Structured choices are correct. Now use the explanation rubric to judge whether your written reasoning fully supports the claim.';
    feedback.className='feedback '+(structuredOK?'':'revise');feedback.innerHTML=`<strong>${structuredOK?'Structured answer checks out':'Revise this attempt'}</strong><p>${esc(msg)}</p>${structuredOK?`<ul class="rubric"><li>Claim: clear?</li><li>Evidence: specific?</li><li>Reasoning: connection explained?</li><li>Limits: no overclaim?</li></ul>`:''}`;
    if(structuredOK&&explanationPresent){state.results[s.id]={completed:true,hints:state.hints,retries:state.attempts.length-1,explanation:'submitted'};const btn=document.createElement('button');btn.className='btn btn-primary';btn.textContent=isTransfer?'Review results →':'Next case →';btn.onclick=()=>advance(isTransfer);feedback.appendChild(btn)}
  }
  function showHint(s){if(!s.hints||!s.hints.length)return;const i=Math.min(state.hints,s.hints.length-1);state.hints++;const box=document.getElementById('feedbackBox');box.className='feedback';box.innerHTML=`<strong>Hint ${state.hints}</strong><p>${esc(s.hints[i])}</p>`}
  function advance(isTransfer){if(isTransfer){state.screen='review';render();return}if(state.index<4){state.index++;resetCase();render()}else{state.index=5;resetCase();render()}}
  function review(){const rows=scenarios.filter(s=>s.stage!=='worked').map(s=>{const r=state.results[s.id];return `<div class="status-row"><span>${esc(s.title)}</span><strong>${r?'Completed':'Not completed'}</strong></div>`}).join('');app.innerHTML=`<section class="hero"><div class="eyebrow">Review</div><h1>Reaction Detective — Review</h1><p>You investigated, selected evidence and built explanations.</p>${steps(5)}</section><section class="intro-grid"><article class="panel intro-card"><h2>What you practised</h2><ul><li>Evidence of chemical change</li><li>Physical vs chemical change</li><li>Reaction classification</li><li>Using evidence to justify a claim</li></ul></article><article class="panel intro-card"><h2>Your case record</h2><div class="case-status">${rows}</div></article><article class="panel intro-card"><h2>Important</h2><p><strong>Completion is not the same as mastery.</strong></p><p>Written explanations were submitted but were not auto-graded by keywords.</p><p>Replay a case if you needed hints or want more practice.</p></article></section><div class="strip"><button class="btn btn-secondary" id="again">Replay from first practice</button><span>Next useful step: return to Unit A or practise a case again.</span></div>`;document.getElementById('again').onclick=()=>{state.screen='practice';state.index=1;state.results={};resetCase();render()}}
  function render(){if(state.screen==='intro')intro();else if(state.screen==='worked')worked();else if(state.screen==='practice')practice();else review();window.scrollTo({top:0,behavior:'auto'})}
  render();
})();
