/* Biology 30 standalone HTML runtime, schema 1.
 * Authored teaching remains in HTML. No network, AI service, framework or build step
 * is required for teaching, questions, practice, vocabulary or local work saving.
 * External fonts and explicitly loaded YouTube videos require connectivity.
 */
(() => {
'use strict';
const C=JSON.parse(document.getElementById('course-data').textContent);
const SC=window.__canvasHelperScorm, LMS=SC&&SC.connectionState()!=='preview';
const KEY=LMS?SC.scopeKey(`biology30-chapter-${C.chapter}:html:v1`):`biology30-chapter-${C.chapter}:html:v1`;
const LMS_INITIAL=LMS?SC.readCourseState():null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x??'').normalize('NFKC').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/[–—]/g,'-').replace(/[.!?]+$/,'').replace(/\s+/g,' ');
const uid=()=>globalThis.crypto?.randomUUID?.()||`run-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const clone=x=>JSON.parse(JSON.stringify(x));
const time=ms=>{let s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60)}m ${s%60}s`;};
let S={version:1,chapter:C.chapter,revision:0,checks:{},practice:{},history:[],frayers:{},notes:{}};
let blocked=false,persistenceAvailable=true,activeWord=null,modalTrigger=null,printDetails=[],pdfBytes=null,pdfUrl=null;
let resetMode=null,removeWord=null,oversizeFrayers=new Set(),unsavedFrayerText=new Map();
function status(message,error=false){const el=$('[data-local-status]');el.textContent=message;el.classList.toggle('is-error',error);el.setAttribute('role',error?'alert':'status');}
try{const disk=localStorage.getItem(KEY);let raw=disk;
 if(LMS){raw=LMS_INITIAL?JSON.stringify(LMS_INITIAL):null;
  if(disk&&raw&&disk!==raw){localStorage.setItem(KEY+':recovery:'+Date.now(),disk);if(JSON.parse(disk).revision>LMS_INITIAL.revision&&window.confirm('This browser has newer unsent work. Continue with the browser draft? Cancel opens the Brightspace copy; the browser recovery copy is retained.'))raw=disk;}
  if(raw)localStorage.setItem(KEY,raw);else localStorage.removeItem(KEY);
 }
 if(raw){const v=JSON.parse(raw);if(v.version!==1||v.chapter!==C.chapter||!Number.isInteger(v.revision)||!v.checks||!v.practice||!Array.isArray(v.history)||!v.frayers||!v.notes)throw Error('Existing save has an unsupported format.');S=v;}status('Browser saving is ready. Work stays on this browser and device; it is not sent to a teacher.');}
catch(e){blocked=true;persistenceAvailable=false;if(LMS)SC.failCourseSave(e);status('Existing work could not be opened, or storage is blocked. Nothing has been overwritten. Enable browser storage before starting. '+e.message,true);}
function save(next,message='Saved in this browser. Nothing has been sent to a teacher.'){
 if(blocked){status('Saving is paused. Another tab or a storage problem requires attention. Copy visible unsaved writing before reloading.',true);return false;}
 try{const raw=localStorage.getItem(KEY);const disk=raw?JSON.parse(raw):{revision:0};if(disk.revision!==S.revision){blocked=true;throw Error('Another tab changed this chapter. Copy visible unsaved writing, then reload.');}
 next.revision=S.revision+1;const rawNext=JSON.stringify(next);localStorage.setItem(KEY,rawNext);S=next;if(LMS)publishLms();status(LMS?'Work stored; waiting for Brightspace confirmation.':message);return true;
 }catch(e){blocked=true;if(LMS)SC.failCourseSave(e);status('NOT SAVED: '+e.message+' Copy visible writing before closing this tab.',true);return false;}
}
function publishLms(){SC.publishCourseState(S,C.checks.filter(c=>S.history.some(r=>r.kind==='check'&&r.checkId===c.id)).map(c=>c.id));}
window.addEventListener('canvas-helper:scorm-status',e=>{if(LMS)status(e.detail.message,e.detail.error);});
if(LMS&&!blocked){publishLms();SC.registerCourse({flush:async()=>{await window.biologyTextbookPractice?.flush();if(blocked)throw Error('Course saving is paused; keep this page open.');publishLms();}});}
function change(fn,message){const next=clone(S);fn(next);return save(next,message);}
window.addEventListener('storage',e=>{if(e.key===KEY){blocked=true;if(LMS)SC.failCourseSave(Error('Another tab changed this chapter. Copy unsaved writing before reloading.'));status('Another tab changed this chapter’s work. This tab will not overwrite it. Copy any visible unsaved writing, then reload.',true);}});
const revisionActivities=window.mountBiologyRevisionActivities({C,read:()=>S,change,status});
function progress(){const completed=new Set(S.history.filter(x=>x.kind==='check').map(x=>x.checkId));let count=C.checks.filter(x=>completed.has(x.id)).length;const percent=Math.round(count/C.checks.length*100);$('[data-progress-count]').textContent=`${count} of ${C.checks.length} checks`;$('[data-progress-percent]').textContent=percent+'%';$('[data-progress-fill]').style.width=percent+'%';$('[data-progress-fraction]').textContent=`${count} / ${C.checks.length}`;$$('[data-lesson-completion]').forEach(el=>{let check=C.checks.find(q=>q.route===el.dataset.lessonCompletion);el.textContent=completed.has(check?.id)?'Check completed':'Check not completed';});}
function checkSpec(id){return S.checks[id]?.spec||C.checks.find(x=>x.id===id);}
function hasCorrect(run,q){return (run.mc[q.id]?.attempts||[]).some(a=>a.correct);}
function unlocked(run,spec){return spec.mc.every(q=>hasCorrect(run,q));}
function renderCheck(section){const id=section.dataset.checkId,spec=checkSpec(id),run=S.checks[id];const ended=!!run?.endedAt;
 $('[data-start-check]',section).hidden=!!run;
 $('[data-start-check]',section).disabled=!persistenceAvailable||blocked;
 $('[data-redo-check]',section).hidden=!ended;
 const body=$('[data-check-body]',section);body.disabled=!run||ended;
 $('[data-finish-check]',section).disabled=!run||ended;
 $('[data-check-status]',section).textContent=!run?'Select Start to begin. The timer includes breaks until you finish.':ended?`Completed. First-try multiple choice: ${scoreCheck(run,spec)}. Writing saved, not automatically graded.`:'In progress. Correct the selections, save every written response, then finish.';
 if(!run)return;
 spec.mc.forEach(q=>{const node=$(`[data-check-question="${q.id}"]`,section),data=run.mc[q.id]||{selected:'',attempts:[]};$$('input[type=radio]',node).forEach(input=>{input.checked=input.value===data.selected;input.disabled=ended||hasCorrect(run,q);});$('[data-check-answer]',node).disabled=ended||hasCorrect(run,q);
 const tries=data.attempts,last=tries.at(-1),out=$('[data-feedback]',node);out.className='inline-feedback'+(last&&!last.correct?' incorrect':'');out.textContent=!last?'':last.correct?`Correct. ${q.explanation}`:tries.length===1?`Not correct yet. Hint: ${q.cue}`:`Not correct yet. Answer: ${q.answer}. ${q.explanation} Select and check the correct answer to unlock the writing.`;
 });
 $('[data-writing-gate]',section).disabled=ended||!unlocked(run,spec);
 $('[data-unlock-message]',section).textContent=unlocked(run,spec)?'Writing unlocked. Save each response separately.':'Answer the multiple-choice questions correctly to unlock the writing.';
 spec.writing.forEach(w=>{const node=$(`[data-writing-question="${w.id}"]`,section),data=run.writing[w.id]||{draft:'',submitted:null};const field=$('textarea',node);if(document.activeElement!==field)field.value=data.draft;
 const valid=data.submitted!==null&&data.submitted===data.draft.trim();$('[data-writing-status]',node).textContent=valid?'Written response saved. It has not been automatically graded.':data.draft.length>w.limit?`Draft exceeds ${w.limit} characters. It is stored locally but must be shortened before submission.`:'Draft only. Select Save written response.';
 $('details',node).dataset.locked=valid?'false':'true';if(!valid)$('details',node).open=false;
 });
}
function scoreCheck(run,spec){return `${spec.mc.filter(q=>run.mc[q.id]?.attempts?.[0]?.correct).length}/${spec.mc.length}`;}
function renderAllChecks(){ $$('[data-check-id]').forEach(renderCheck);progress();}
function startCheck(id){const spec=C.checks.find(x=>x.id===id);if(!spec)return;if(change(n=>{n.checks[id]={id:uid(),spec:clone(spec),bankVersion:C.bankVersion,startedAt:Date.now(),endedAt:null,mc:Object.fromEntries(spec.mc.map(q=>[q.id,{selected:'',attempts:[]}])),writing:Object.fromEntries(spec.writing.map(w=>[w.id,{draft:'',submitted:null,at:null}]))};},'Check started and saved in this browser.'))renderAllChecks();}
function finishCheck(id){const spec=checkSpec(id),run=S.checks[id];if(!run||run.endedAt)return;
 if(!unlocked(run,spec)){status('Finish the multiple-choice corrections before completing this check.',true);return;}
 const missing=spec.writing.filter(w=>{const x=run.writing[w.id];return !x?.draft.trim()||x.draft.length>w.limit||x.submitted!==x.draft.trim();});
 if(missing.length){status('Save each valid written response before finishing. Changed drafts must be saved again.',true);return;}
 if(change(n=>{const r=n.checks[id];r.endedAt=Date.now();n.history.push({kind:'check',checkId:id,title:spec.title,spec:clone(spec),run:clone(r)});},'Check completed and stored in All My Work. Writing still requires human review.')){renderAllChecks();renderWork();}
}
// Seeded, finite authored practice selection. The full generated set is saved.
function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function seed(){let a=new Uint32Array(1);if(globalThis.crypto?.getRandomValues){crypto.getRandomValues(a);return a[0];}return Math.floor(Math.random()*4294967296);}
function makePool(mode,topic,diff){return BiologyRevisionPractice.pool(C,mode,topic,diff);}
function selectItems(pool,count,random,mixed){return BiologyRevisionPractice.select(pool,count,random,mixed);}
function startPractice(mode,items=null){const section=$(`[data-practice-mode="${mode}"]`),topic=$('[data-topic]',section).value,count=Number($('[data-set-size]',section).value),diff=$('[data-difficulty]',section)?.value||'mixed',ss=seed(),random=rng(ss);let pool=items||makePool(mode,topic,diff),chosen=items?items.map(x=>clone(x)):selectItems(pool,count,random,mode==='mixed');
 if(!chosen.length){$('[data-practice-message]',section).textContent='No reviewed items match that combination. Choose another topic or difficulty.';return;}
 const run={id:uid(),mode,seed:ss,bankVersion:C.bankVersion,generatorVersion:'reviewed-2',topic,difficulty:diff,requestedSize:items?items.length:count,startedAt:Date.now(),endedAt:null,index:0,items:chosen,responses:{}};
 if(change(n=>{n.practice[mode]=run;},'Practice set created and saved, including its exact questions and option order.'))renderPractice(mode);
}
function resp(run,item){return run.responses[item.id]||{draft:item.kind==='order'?Array(item.steps.length).fill(''):item.kind==='multi-select'?[]:'',attempts:[],revealed:false,rating:null};}
function itemDone(run,item){const a=resp(run,item);return item.kind==='flash'?!!a.rating:!!a.attempts.at(-1)?.correct||a.attempts.length>=2;}
function practiceSummary(run){const graded=run.items.filter(x=>x.kind!=='flash'),first=graded.filter(i=>resp(run,i).attempts[0]?.correct).length;if(!graded.length){let recalled=run.items.filter(i=>resp(run,i).rating==='recalled').length;return `${recalled}/${run.items.length} self-reported as recalled. This is self-assessment, not a graded mark.`;}return `First-try result: ${first}/${graded.length}. Later corrections are recorded separately.`;}
function renderPractice(mode){const section=$(`[data-practice-mode="${mode}"]`),run=S.practice[mode],setup=$('[data-practice-setup]',section),stage=$('[data-practice-stage]',section),summary=$('[data-practice-summary]',section);setup.hidden=!!run;stage.hidden=!run||!!run.endedAt;summary.hidden=!run?.endedAt;$('[data-practice-message]',section).textContent=run&&run.items.length<run.requestedSize?`This filter has ${run.items.length} reviewed unique items, so the set is smaller than requested.`:'';
 if(!run){stage.innerHTML='';return;}
 if(run.endedAt){summary.innerHTML=`<h3>Practice completed</h3><p>${esc(practiceSummary(run))}</p><p>Elapsed ${time(run.endedAt-run.startedAt)}. This activity does not change required-check progress.</p><div class="actions"><button type="button" data-again="${mode}">Start another set</button><button type="button" data-retry="${mode}" class="button--secondary">Retry concepts to study</button><a href="#process-collection">See All My Work</a></div>`;return;}
 const item=BiologyRevisionPractice.safe(C,run.items[run.index]),r=resp(run,item),last=r.attempts.at(-1),done=itemDone(run,item);
 let form='';
 if(item.kind==='flash'){form=`<div class="flash-face"><p class="eyebrow">Recall before revealing</p><h3>${esc(item.prompt)}</h3></div><button type="button" data-reveal="${mode}" ${r.revealed?'hidden':''}>Reveal reference answer</button><div class="practice-feedback" ${r.revealed?'':'hidden'}><p><strong>${esc(item.answer)}</strong></p><p>${esc(item.example)}</p><p>${esc(item.explanation)}</p><div class="actions"><button type="button" data-rate="recalled" data-mode="${mode}" ${r.rating?'disabled':''}>I recalled it</button><button type="button" data-rate="study" data-mode="${mode}" ${r.rating?'disabled':''}>Study again</button></div>${r.rating?`<p>Recorded: ${r.rating==='recalled'?'I recalled it':'Study again'}.</p>`:''}</div>`;}
 else if(item.kind==='mc'||item.kind==='diagram'){form=`<h3>${esc(item.prompt)}</h3><fieldset class="options"><legend class="sr-only">Choose one answer</legend>${item.options.map((a,i)=>`<label class="option-row"><input type="radio" name="practice-${mode}" value="${esc(a)}" data-practice-input="${mode}" ${r.draft===a?'checked':''} ${done?'disabled':''}><span>${esc(a)}</span></label>`).join('')}</fieldset>`;}
 else if(item.kind==='multi-select'){form=`<h3>${esc(item.prompt)}</h3><fieldset class="options"><legend>Select every correct statement</legend>${item.options.map(a=>`<label class="option-row"><input type="checkbox" value="${esc(a.id)}" data-practice-input="${mode}" ${Array.isArray(r.draft)&&r.draft.includes(a.id)?'checked':''} ${done?'disabled':''}><span>${esc(a.text)}</span></label>`).join('')}</fieldset>`;}
 else if(item.kind==='blank'){form=`<h3>${esc(item.prompt)}</h3><label for="practice-input-${mode}">Your term</label><input id="practice-input-${mode}" autocomplete="off" spellcheck="false" type="text" data-practice-input="${mode}" value="${esc(r.draft)}" ${done?'disabled':''}>`;}
 else{form=`<h3>${esc(item.prompt)}</h3><p>Choose one step for each position. Use every step once.</p><div class="order-controls">${item.steps.map((_,i)=>`<label>Step ${i+1}<select data-practice-input="${mode}" data-order-position="${i}" ${done?'disabled':''}><option value="">Choose a step</option>${item.options.map(v=>`<option ${r.draft[i]===v?'selected':''} value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`).join('')}</div>`;}
 if(item.kind==='diagram'){const d=labelSpec(item.diagramId);form=`<figure class="science-figure" data-practice-diagram><div class="figure-toolbar"><strong>${esc(d.title)}</strong><button type="button" data-enlarge-label="${d.id}">Larger diagram</button></div><img src="${esc(d.src)}" alt="${esc(d.alt)}"></figure>`+form;}
 if(item.kind!=='flash'){let feedback=!last?'':last.correct?`Correct. ${item.explanation}`:r.attempts.length===1?`Not correct yet. Hint: ${item.cue}`:`Answer: ${item.kind==='multi-select'?item.options.filter(o=>item.answers.includes(o.id)).map(o=>o.text).join(' · '):Array.isArray(item.answer)?item.answer.join(' → '):item.answer}. ${item.explanation}`;
 form+=`<button type="button" data-practice-check="${mode}" ${done?'disabled':''}>Check answer</button><div class="inline-feedback ${last&&!last.correct?'incorrect':''}" role="status" aria-live="polite">${esc(feedback)}</div>`;}
 stage.innerHTML=`<div class="practice-meta"><span>Question ${run.index+1} of ${run.items.length} · ${esc(item.kind==='diagram'?'Diagram':item.kind==='multi-select'?'Multiple select':item.kind==='blank'?'Fill in the blank':item.kind==='order'?'Sequence':item.kind==='mc'?'Multiple choice':'Flash card')}</span><span data-practice-timer="${mode}"></span></div><div class="practice-question">${item.repeatPractice?'<p><strong>Repeat practice.</strong> No alternative representation is available in this filter.</p>':''}${form}<p><a href="#${esc(item.reviewRoute)}">Review this lesson</a></p></div><div class="practice-navigation actions"><button type="button" data-practice-back="${mode}" ${run.index===0?'disabled':''}>Previous</button>${run.index<run.items.length-1?`<button type="button" data-practice-next="${mode}" ${!done?'disabled':''}>Next question</button>`:`<button type="button" data-practice-finish="${mode}" ${!run.items.every(i=>itemDone(run,i))?'disabled':''}>Submit and finish</button>`}<button type="button" class="button--secondary" data-reset-request="${mode}">Stop and reset</button></div><div class="reset-confirmation" data-reset-panel ${resetMode===mode?'':'hidden'}><h3>Reset this unfinished practice?</h3><p>Clear this set’s responses, feedback, position and timer. Completed work and other activities will remain.</p><div class="actions"><button type="button" data-reset-confirm="${mode}">Reset unfinished practice</button><button type="button" data-reset-cancel="${mode}">Keep working</button></div></div>`;
 tick();}
function checkPractice(mode){const run=S.practice[mode];if(!run||run.endedAt)return;const item=run.items[run.index],r=resp(run,item);if(itemDone(run,item))return;
 if(item.kind==='order'){if(!Array.isArray(r.draft)||r.draft.length<item.steps.length||r.draft.some(x=>!x)||new Set(r.draft).size!==item.steps.length){status('Choose each sequence step once before checking.',true);return;}}
 else if(item.kind==='multi-select'?!Array.isArray(r.draft)||!r.draft.length:!String(r.draft).trim()){status('Enter or select an answer before checking.',true);return;}
 const correct=item.kind==='multi-select'?BiologyRevisionPractice.equalSet(r.draft,item.answers):item.kind==='order'?r.draft.every((v,i)=>v===item.steps[i]):(item.kind==='mc'||item.kind==='diagram')?r.draft===item.answer:[item.answer,...(item.aliases||[])].some(x=>norm(x)===norm(r.draft));
 if(change(n=>{const rr=n.practice[mode],a=rr.responses[item.id]??=clone(r);a.attempts.push({answer:clone(r.draft),correct,at:Date.now(),firstTry:a.attempts.length===0});},'Practice attempt saved in this browser.'))renderPractice(mode);
}
function finishPractice(mode){const run=S.practice[mode];if(!run||run.endedAt)return;if(!run.items.every(i=>itemDone(run,i))){status('Finish every item before submitting the set.',true);return;}if(change(n=>{let r=n.practice[mode];r.endedAt=Date.now();n.history.push({kind:'practice',title:C.modeNames[mode],run:clone(r)});},'Formative practice saved in All My Work. Required progress is unchanged.')){renderPractice(mode);renderWork();progress();}}
function retryPractice(mode){const old=S.practice[mode];if(!old?.endedAt)return;const misses=old.items.filter(i=>i.kind==='flash'?resp(old,i).rating==='study':!resp(old,i).attempts[0]?.correct);if(!misses.length){status('No missed or Study again items in this run. Start another set to continue.');return;}startPractice(mode,BiologyRevisionPractice.retry(C,old,misses));}
function resetPractice(mode){if(mode==='labeling'){if(change(n=>{delete n.practice.labeling;},'Unfinished labeling cleared. Completed history remains.')){resetMode=null;renderLabels();}return;}
 if(change(n=>{delete n.practice[mode];},'Unfinished practice cleared. Completed history remains.')){resetMode=null;renderPractice(mode);}}
// Labeling: one diagram, answer snapshots and attempts. Perfection is not required.
function labelSpec(id){return C.labelDiagrams.find(d=>d.id===id);}
function renderLabels(){const sec=$('[data-labeling]'),run=S.practice.labeling,selected=run?.diagramId||$('[data-diagram-select]',sec).value,d=labelSpec(selected);$('[data-diagram-select]',sec).disabled=!!run&&!run.endedAt;$('[data-start-labels]',sec).hidden=!!run;$('[data-redo-labels]',sec).hidden=!run?.endedAt;
 $('[data-label-stage]',sec).innerHTML=`<figure class="science-figure label-figure"><div class="figure-toolbar"><strong>${esc(d.title)}</strong><button type="button" data-enlarge-label="${d.id}" class="text-link">Larger diagram</button></div><img src="${d.src}" alt="${esc(d.alt)}"><figcaption>Match each letter to one of the listed structures. This is a schematic, not a measured anatomical specimen.${d.reviewNote?`<p>${esc(d.reviewNote)}</p>`:''}${d.legend?`<details><summary>Detailed cochlear chamber names</summary><p>${esc(d.legend)}</p></details>`:''}</figcaption></figure><fieldset ${!run||run.endedAt?'disabled':''} class="label-controls"><legend>Identify the labelled structures</legend><div class="label-grid">${Object.entries(d.answers).map(([letter,answer])=>{const v=run?.labels[letter]||{selected:'',attempts:[]},last=v.attempts.at(-1);return `<div class="label-row"><label for="label-${letter}"><strong>${letter}</strong></label><select id="label-${letter}" data-label-answer="${letter}"><option value="">Choose a structure</option>${d.options.map(x=>`<option value="${esc(x)}" ${v.selected===x?'selected':''}>${esc(x)}</option>`).join('')}</select><button type="button" data-label-check="${letter}">Check</button><p class="inline-feedback ${last&&!last.correct?'incorrect':''}" aria-live="polite">${!last?'':esc(last.correct?'Correct.':v.attempts.length===1?'Not correct yet. Revisit the diagram and the lesson.':`Answer: ${answer}. Review the location and function.`)}</p></div>`;}).join('')}</div><div class="actions"><button type="button" data-label-check-all>Check all labels</button><button type="button" data-label-finish>Submit and finish</button><button type="button" data-reset-request="labeling" class="button--secondary">Stop and reset</button></div></fieldset><div class="reset-confirmation" ${resetMode==='labeling'?'':'hidden'}><h3>Reset unfinished labeling?</h3><p>Clear this unfinished run. Completed labeling history and other work remain.</p><div class="actions"><button type="button" data-reset-confirm="labeling">Reset unfinished practice</button><button type="button" data-reset-cancel="labeling">Keep working</button></div></div>`;
 $('[data-label-status]',sec).textContent=!run?'Select Start. Check every label before finishing; a perfect score is not required.':run.endedAt?`Completed. Latest checked labels: ${Object.values(run.labels).filter(v=>v.attempts.at(-1)?.correct).length}/${Object.keys(d.answers).length} correct. This does not change required progress.`:'In progress. Check each selected response before finishing; incorrect attempts are still recorded.';tick();}
function startLabels(){const d=labelSpec($('[data-diagram-select]').value);if(change(n=>{n.practice.labeling={id:uid(),mode:'labeling',diagramId:d.id,startedAt:Date.now(),endedAt:null,labels:Object.fromEntries(Object.keys(d.answers).map(k=>[k,{selected:'',attempts:[]}]))};},'Labeling run started and saved.'))renderLabels();}
function checkLabels(letter=null){const run=S.practice.labeling;if(!run||run.endedAt)return;const d=labelSpec(run.diagramId),keys=letter?[letter]:Object.keys(d.answers);let count=0;if(change(n=>{let r=n.practice.labeling;for(const k of keys){const v=r.labels[k];if(!v.selected)continue;v.attempts.push({answer:v.selected,correct:v.selected===d.answers[k],at:Date.now()});count++;}},'Label checks saved.')){renderLabels();if(!count)status('Choose a structure before checking.',true);}}
function finishLabels(){const run=S.practice.labeling;if(!run||run.endedAt)return;const d=labelSpec(run.diagramId);if(!Object.keys(d.answers).every(k=>{let v=run.labels[k];return v.selected&&v.attempts.some(a=>a.answer===v.selected);})){status('Choose and check every current label response before finishing. A perfect result is not required.',true);return;}if(change(n=>{let r=n.practice.labeling;r.endedAt=Date.now();n.history.push({kind:'labeling',title:d.title,diagram:clone(d.answers),run:clone(r)});},'Labeling saved in All My Work. Required progress is unchanged.')){renderLabels();renderWork();}}
// Dialogs and in-context vocabulary.
const dialog=$('#app-dialog');
function openDialog(title,body,kind=''){modalTrigger=document.activeElement;dialog.className='app-dialog '+kind;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;dialog.showModal();$('#close-dialog').focus();}
function closeDialog(){if(dialog.open)dialog.close();}
dialog.addEventListener('close',()=>{restoreFrayerHome();$$('.textbook-subtitle',dialog).forEach(e=>e.remove());const last=modalTrigger;$('#dialog-body').innerHTML='';if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl=null;}if(last?.isConnected)last.focus({preventScroll:true});});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function word(id){return C.words.find(w=>w.id===id);}
function openWord(id){showVocabularyPopup(id);}
function filterVocabulary(){filterWordIndex();}
function addFrayer(id){if(S.frayers[id]){activeWord=id;renderFrayers();return;}if(Object.keys(S.frayers).length>=8){status('Eight words are already selected. Copy and explicitly remove a word before selecting another.',true);return;}
 if(change(n=>{n.frayers[id]={answers:['','','',''],collected:false,updatedAt:Date.now()};},'Word selected. Complete all four fields before collecting it.')){activeWord=id;renderFrayers();const b=$(`[data-add-frayer="${id}"]`,dialog);if(b){b.disabled=true;b.textContent='Already selected';}}}
function frayerValid(id){let f=S.frayers[id];return f&&f.answers.every((a,i)=>a.trim()&&a.length<=240&&!oversizeFrayers.has(id+':'+i));}
function renderFrayers(){const ids=Object.keys(S.frayers);if(!ids.includes(activeWord))activeWord=ids[0]||null;$('[data-frayer-count]').textContent=`${ids.length} of 8 words selected`;$('[data-frayer-tabs]').innerHTML=ids.map(id=>`<button type="button" data-frayer-select="${id}" aria-pressed="${id===activeWord}">${esc(word(id).term)} · ${S.frayers[id].collected?'Collected':'Draft'}</button>`).join('');
 const host=$('[data-frayer-editor]');if(!activeWord){host.innerHTML='<p>Choose a term above or from a word popup. You can select up to eight words for this chapter.</p>';return;}
 const id=activeWord,w=word(id),f=S.frayers[id],labels=['Meaning in your own words','Key features or what it does','A specific example','A non-example or common confusion'];host.innerHTML=`<h3>${esc(w.term)}</h3><p>Write your own responses. Each field permits 240 characters. Overlong text stays visible but is not saved until shortened.</p><div class="frayer-fields">${labels.map((l,i)=>`<label for="frayer-${i}">${l}<textarea id="frayer-${i}" rows="3" data-frayer-input="${id}" data-field="${i}">${esc(unsavedFrayerText.get(id+':'+i)??f.answers[i])}</textarea><small data-frayer-counter="${i}">${(unsavedFrayerText.get(id+':'+i)??f.answers[i]).length}/240</small></label>`).join('')}</div><p data-frayer-state>${f.collected?'Collected. Editing a field will return this word to draft.':'Draft. Complete all four fields before collection.'}</p><div class="actions"><button type="button" data-collect-frayer="${id}" ${!frayerValid(id)?'disabled':''}>Collect this word</button><button type="button" data-copy-frayer="${id}">Copy my responses</button><button type="button" class="button--secondary" data-remove-frayer="${id}">Remove selected word</button></div><details data-frayer-model data-locked="${!frayerValid(id)}"><summary>Compare with the course model after completing all four fields</summary><div class="frayer-model"><p><strong>Meaning:</strong> ${esc(w.meaning)}</p><p><strong>Key feature:</strong> ${esc(w.feature||w.meaning)}</p><p><strong>Example:</strong> ${esc(w.example)}</p><p><strong>Important distinction:</strong> ${esc(w.importantDistinction||w.confusion)}</p></div></details><div class="reset-confirmation" data-remove-panel ${removeWord===id?'':'hidden'}><h4>Remove this word and its Frayer responses?</h4><p>Copy the responses first if you need them. Other words and completed activity runs will remain.</p><div class="actions"><button type="button" data-remove-confirm="${id}">Remove this word</button><button type="button" data-remove-cancel>Keep this word</button></div></div>`;
}
function updateFrayerState(){if(!activeWord)return;const id=activeWord,valid=frayerValid(id);$('[data-collect-frayer]').disabled=!valid;$('[data-frayer-model]').dataset.locked=String(!valid);if(!valid)$('[data-frayer-model]').open=false;$('[data-frayer-state]').textContent=S.frayers[id].collected?'Collected. Editing returns this word to draft.':'Draft. All four valid responses are needed for collection.';}
function copyFrayer(id){const w=word(id),f=S.frayers[id],text=[w.term,...f.answers.map((a,i)=>unsavedFrayerText.get(id+':'+i)??a)].join('\n\n');if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(()=>status('Your Frayer responses were copied.')).catch(()=>manualCopy(text));}else manualCopy(text);}
function manualCopy(text){openDialog('Copy your responses',`<p>Select and copy this text before removing the word.</p><textarea readonly rows="12" class="copy-box">${esc(text)}</textarea>`);const t=$('textarea',dialog);t.focus();t.select();}
// Embedded textbook creates a local PDF Blob only when opened.
function openPdf(printed){const lo=C.chapter===12?404:434,hi=C.chapter===12?433:471;printed=Number(printed);if(!Number.isInteger(printed)||printed<lo||printed>hi){status(`Choose a printed page from ${lo} to ${hi}.`,true);return;}
 const offset=C.chapter===12?403:433,physical=printed-offset;
 try{if(!pdfBytes){const encoded=$('#textbook-data').textContent.trim(),bin=atob(encoded);pdfBytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)pdfBytes[i]=bin.charCodeAt(i);}if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(new Blob([pdfBytes],{type:'application/pdf'}));const src=`${pdfUrl}#page=${physical}&view=FitH`;
 openDialog(`Textbook page ${printed}`,`<iframe class="embedded-pdf" title="Chapter ${C.chapter} textbook at printed page ${printed}" src="${src}"></iframe><div class="textbook-dialog-actions"><a href="${src}" target="_blank" rel="noopener">Open this page in a new window</a></div>`,'pdf-dialog textbook-dialog'); const subtitle=document.createElement('p');subtitle.className='textbook-subtitle';subtitle.textContent=`Chapter ${C.chapter}: PDF page ${physical} of ${C.pdfPages}`;$('#dialog-title').after(subtitle);
 }catch(e){status('The embedded PDF could not be opened: '+e.message,true);}
}
// Videos are optional network resources. No external player is created before a click.
function videoMarkup(v){return `<div class="video-copy"><p class="eyebrow">Watch and make sense of it</p><h3>${esc(v.title)}</h3><p><strong>As you watch:</strong> ${esc(v.purpose)}</p><p class="muted">Optional video. Internet access is required. The explanation below covers the idea without the video.</p><p><a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener">Open on YouTube</a></p></div><div class="video-visual"><div class="video-stage" data-video-stage="${v.id}"><button type="button" data-play-video="${v.id}">Load video</button></div><div class="concept-summary"><h4>Read the explanation</h4><p>${esc(v.fallback)}</p></div></div>`;}
function renderVideoLibrary(){const v=C.videos.find(x=>x.id===$('[data-video-select]').value);$('[data-video-library-card]').innerHTML=videoMarkup(v);}
function loadVideo(button){const id=button.dataset.playVideo,stage=button.closest('[data-video-stage]');stage.innerHTML=`<iframe title="Optional video for Chapter ${C.chapter}" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>`;}
// Work collection uses text escaping and preserves submitted rather than invented marks.
function renderWork(){revisionActivities.renderWork();const host=$('[data-work-history]');$('[data-work-summary]').textContent=`${S.history.length} completed activity run${S.history.length===1?'':'s'}. Required checks and formative practice are recorded separately.`;
 host.innerHTML=S.history.slice().reverse().map(h=>{
 let r=h.run,body='';
 if(h.kind==='check'){body=`<p><strong>First-try multiple choice: ${scoreCheck(r,h.spec)}</strong>. Writing is not automatically graded.</p>`+h.spec.mc.map(q=>`<section><h4>${esc(q.prompt)}</h4><p>Options: ${q.options.map(esc).join(' · ')}</p>${r.mc[q.id].attempts.map((a,i)=>`<p>Attempt ${i+1}: ${esc(a.answer)} — ${a.correct?'Correct':'Incorrect'}</p>`).join('')}</section>`).join('')+h.spec.writing.map(w=>`<section><h4>${esc(w.prompt)}</h4><p class="written-record">${esc(r.writing[w.id].submitted)}</p><p class="muted">Submitted writing; human review required.</p></section>`).join('');}
 else if(h.kind==='practice'){body=`<p>${esc(practiceSummary(r))}</p>`+r.items.map(raw=>{const item=BiologyRevisionPractice.safe(C,raw);let a=resp(r,raw);return `<section><h4>${esc(item.prompt)}</h4>${item.options?`<p>Options shown: ${item.options.map(x=>esc(typeof x==='object'?x.text:x)).join(' · ')}</p>`:''}${item.kind==='flash'?`<p>Self-report: ${a.rating==='recalled'?'I recalled it':'Study again'}.</p>`:a.attempts.map((t,i)=>`<p>Attempt ${i+1}: ${esc(Array.isArray(t.answer)?t.answer.join(' → '):t.answer)} — ${t.correct?'Correct':'Incorrect'}.</p>`).join('')}<p>Reference: ${esc(item.kind==='multi-select'?item.options.filter(o=>item.answers.includes(o.id)).map(o=>o.text).join(' · '):Array.isArray(item.answer)?item.answer.join(' → '):item.answer)}</p></section>`;}).join('');}
 else {body=Object.entries(r.labels).map(([letter,v])=>`<section><h4>Label ${letter}</h4>${v.attempts.map((a,i)=>`<p>Attempt ${i+1}: ${esc(a.answer)} — ${a.correct?'Correct':'Incorrect'}</p>`).join('')}<p>Reference: ${esc(h.diagram[letter])}</p></section>`).join('');}
 return `<article class="history-run"><h3>${esc(h.title)}</h3><p>${esc(new Date(r.startedAt).toLocaleString())} · Elapsed ${time(r.endedAt-r.startedAt)} · ${h.kind==='check'?'Required check':'Formative practice'}</p><details class="work-details"><summary>Review submitted responses and attempts</summary><div>${body}</div></details></article>`;
 }).join('')||'<p>No completed runs yet. Unfinished runs remain in their own activities.</p>';
 $('[data-work-frayers]').innerHTML=Object.entries(S.frayers).map(([id,f])=>`<article class="history-run"><h3>${esc(word(id).term)} — ${f.collected?'Collected':'Draft'}</h3>${['Meaning','Key features','Example','Non-example / common confusion'].map((label,i)=>`<p><strong>${label}:</strong> <span class="written-record">${esc(f.answers[i]||'(not yet written)')}</span></p>`).join('')}</article>`).join('')||'<p>No Frayer words selected.</p>';
 $('[data-work-notes]').innerHTML=Object.entries(S.notes).filter(([id,n])=>n.submitted).map(([id,n])=>`<article class="history-run"><h3>${esc(C.notes.find(v=>v.id===id)?.title||id)}</h3><p class="written-record">${esc(n.submitted)}</p>${n.draft.trim()!==n.submitted?'<p class="muted">A newer draft exists in the activity. This is the last explicitly saved response.</p>':''}</article>`).join('')||'<p>No optional written responses collected.</p>';
 const activeChecks=Object.values(S.checks).filter(x=>!x.endedAt).length,activePractice=Object.values(S.practice).filter(x=>!x.endedAt).length;$('[data-unfinished-count]').textContent=`Unfinished work: ${activeChecks} required check(s), ${activePractice} practice run(s). Resume them from their original sections; they are not counted as completed.`;
}
function restoreNotes(){ $$('[data-note-input]').forEach(el=>{let n=S.notes[el.dataset.noteInput];el.value=n?.draft||'';});}
function tick(){const now=Date.now();$$('[data-check-id]').forEach(sec=>{let r=S.checks[sec.dataset.checkId];$('[data-check-timer]',sec).textContent=r?time((r.endedAt||now)-r.startedAt):'Not started';});$$('[data-practice-timer]').forEach(el=>{let r=S.practice[el.dataset.practiceTimer];el.textContent=r?time((r.endedAt||now)-r.startedAt):'';});let r=S.practice.labeling;$('[data-label-timer]').textContent=r?time((r.endedAt||now)-r.startedAt):'Not started';}
function setNav(open){const wasOpen=document.body.classList.contains('nav-open');document.body.classList.toggle('nav-open',open);$('[data-menu-button]').setAttribute('aria-expanded',String(open));const mobile=matchMedia('(max-width: 980px)').matches;$('#course-sidebar').inert=mobile&&!open;$('#nav-scrim').hidden=!open;$('#course-main').inert=mobile&&open;if(mobile&&open&&!wasOpen)$('#course-sidebar .nav-link')?.focus();}
function route(){const raw=location.hash.slice(1),target=document.getElementById(raw),page=target?.closest('.course-page'),id=page?.id||'overview';$$('.course-page').forEach(el=>el.hidden=el.id!==id);$$('.nav-link').forEach(a=>{let active=a.getAttribute('href')==='#'+id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $$('.course-page[hidden] [data-video-stage] iframe').forEach(frame=>{let stage=frame.parentElement,id=stage.dataset.videoStage;stage.innerHTML=`<button type="button" data-play-video="${id}">Load video</button>`;});
 if(id==='process-collection')renderWork();if(id==='core-vocabulary'){filterVocabulary();renderFrayers();}setNav(false);window.scrollTo(0,0);const heading=$('h1',document.getElementById(id));if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}document.title=`${C.courseTitle} — ${heading?.textContent||'Overview'}`;if(target&&target!==page){target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView();}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('nav-open')){setNav(false);$('[data-menu-button]').focus();}});window.addEventListener('hashchange',route);window.addEventListener('resize',()=>setNav(document.body.classList.contains('nav-open')));
// Prevent opening answer models before the associated writing is valid.
document.addEventListener('click',e=>{const summary=e.target.closest('summary');if(summary&&summary.parentElement.dataset.locked==='true'){e.preventDefault();status('Complete and save the required writing before comparing with this model.',true);}});
document.addEventListener('input',e=>{const el=e.target;
 if(el.matches('[data-vocab-search]')){filterVocabulary();return;}
 if(el.matches('[data-check-choice]')){const id=el.closest('[data-check-id]').dataset.checkId,run=S.checks[id],qid=el.dataset.checkChoice;if(!run||run.endedAt)return;change(n=>{n.checks[id].mc[qid].selected=el.value;});return;}
 if(el.matches('[data-check-writing]')){const id=el.closest('[data-check-id]').dataset.checkId,wid=el.dataset.checkWriting,run=S.checks[id];if(!run||run.endedAt)return;if(change(n=>{n.checks[id].writing[wid].draft=el.value;})){const node=el.closest('[data-writing-question]');$('[data-writing-status]',node).textContent=el.value.length>Number(el.dataset.limit)?'Oversized draft saved locally. Shorten before submission.':'Draft saved locally. Select Save written response to submit this version.';$('details',node).open=false;$('details',node).dataset.locked='true';}return;}
 if(el.matches('[data-practice-input]')){const mode=el.dataset.practiceInput,run=S.practice[mode];if(!run||run.endedAt)return;const item=run.items[run.index],current=resp(run,item);change(n=>{let r=n.practice[mode].responses[item.id]??=clone(current);if(el.hasAttribute('data-order-position')){if(!Array.isArray(r.draft))r.draft=Array(item.steps.length).fill('');r.draft[Number(el.dataset.orderPosition)]=el.value;}else if(item.kind==='multi-select'){r.draft=Array.from(el.closest('fieldset').querySelectorAll('input:checked')).map(x=>x.value);}else r.draft=el.value;});return;}
 if(el.matches('[data-label-answer]')){const run=S.practice.labeling;if(!run||run.endedAt)return;change(n=>{n.practice.labeling.labels[el.dataset.labelAnswer].selected=el.value;});return;}
 if(el.matches('[data-frayer-input]')){const id=el.dataset.frayerInput,i=Number(el.dataset.field),key=id+':'+i;$(`[data-frayer-counter="${i}"]`).textContent=`${el.value.length}/240`;
 if(el.value.length>240){oversizeFrayers.add(key);unsavedFrayerText.set(key,el.value);if(S.frayers[id].collected)change(n=>{n.frayers[id].collected=false;});status('This Frayer field exceeds 240 characters. Extra text remains visible but is NOT saved. Shorten it before leaving.',true);updateFrayerState();return;}
 oversizeFrayers.delete(key);unsavedFrayerText.delete(key);if(change(n=>{n.frayers[id].answers[i]=el.value;n.frayers[id].collected=false;n.frayers[id].updatedAt=Date.now();}))updateFrayerState();return;}
 if(el.matches('[data-note-input]')){const saved=change(n=>{let v=n.notes[el.dataset.noteInput]??={draft:'',submitted:null};v.draft=el.value;});const out=$(`[data-note-status="${el.dataset.noteInput}"]`);if(out)out.textContent=saved?'Draft saved locally. Select Save response to collect it.':'NOT SAVED. Copy this draft before leaving.';}
});
document.addEventListener('change',e=>{const el=e.target;if(el.matches('[data-vocab-topic]'))filterVocabulary();if(el.matches('[data-video-select]'))renderVideoLibrary();if(el.matches('[data-diagram-select]')){const r=S.practice.labeling;if(r?.endedAt){if(!change(n=>delete n.practice.labeling))return;}renderLabels();}});
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
 if(b.classList.contains('skip-link')){e.preventDefault();$('#course-main').focus();return;}if(b.id==='close-dialog'){closeDialog();return;}if(b.hasAttribute('data-dialog-route'))closeDialog();
 if(b.hasAttribute('data-menu-button')){setNav(!document.body.classList.contains('nav-open'));return;}
 if(b.hasAttribute('data-sidebar-toggle')){document.body.classList.toggle('sidebar-collapsed');const closed=document.body.classList.contains('sidebar-collapsed');b.setAttribute('aria-expanded',String(!closed));return;}
 if(b.hasAttribute('data-save-exit')){if(oversizeFrayers.size){status('Some Frayer text is over 240 characters and has not been saved. Shorten or copy it before closing.',true);return;}change(()=>{},'Work saved in this browser. You may close this tab. Use All My Work to print or save a PDF before changing devices.');return;}
 if(b.dataset.openPdf){e.preventDefault();openPdf(b.dataset.openPdf);return;}if(b.hasAttribute('data-open-library-pdf')){openPdf($('[data-pdf-page]').value);return;}
 if(b.dataset.termId){openWord(b.dataset.termId);return;}if(b.dataset.enlargeFigure){const figure=b.closest('figure'),img=$('img',figure);openDialog($('.figure-toolbar strong',figure)?.textContent||'Diagram',`<img class="large-diagram" src="${img.src}" alt="${esc(img.alt)}"><p>${esc($('figcaption',figure)?.textContent||'')}</p>`,'image-dialog');return;}
 if(b.dataset.enlargeLabel){let d=labelSpec(b.dataset.enlargeLabel);openDialog(d.title,`<img class="large-diagram" src="${d.src}" alt="${esc(d.alt)}">`,'image-dialog');return;}
 if(b.hasAttribute('data-start-check')||b.hasAttribute('data-redo-check')){startCheck(b.closest('[data-check-id]').dataset.checkId);return;}
 if(b.dataset.checkAnswer){const sec=b.closest('[data-check-id]'),id=sec.dataset.checkId,run=S.checks[id],q=checkSpec(id).mc.find(x=>x.id===b.dataset.checkAnswer);if(!run||run.endedAt)return;let selected=run.mc[q.id].selected;if(!selected){status('Choose an answer before checking.',true);return;}if(change(n=>{let r=n.checks[id].mc[q.id];r.attempts.push({answer:selected,correct:selected===q.answer,at:Date.now()});}))renderCheck(sec);return;}
 if(b.dataset.saveWriting){const sec=b.closest('[data-check-id]'),id=sec.dataset.checkId,run=S.checks[id],spec=checkSpec(id),w=spec.writing.find(x=>x.id===b.dataset.saveWriting);if(!run||run.endedAt||!unlocked(run,spec))return;let txt=run.writing[w.id].draft;if(!txt.trim()||txt.length>w.limit){status(`Write a response of 1–${w.limit} characters before saving it.`,true);return;}if(change(n=>{let r=n.checks[id].writing[w.id];r.submitted=txt.trim();r.at=Date.now();},'Written response saved. It is not automatically graded.'))renderCheck(sec);return;}
 if(b.hasAttribute('data-finish-check')){finishCheck(b.closest('[data-check-id]').dataset.checkId);return;}
 if(b.dataset.practiceStart){startPractice(b.dataset.practiceStart);return;}if(b.dataset.practiceCheck){checkPractice(b.dataset.practiceCheck);return;}
 if(b.dataset.reveal){const mode=b.dataset.reveal,run=S.practice[mode],item=run.items[run.index];if(change(n=>{let r=n.practice[mode].responses[item.id]??=clone(resp(run,item));r.revealed=true;}))renderPractice(mode);return;}
 if(b.dataset.rate){const mode=b.dataset.mode,run=S.practice[mode],item=run.items[run.index];if(change(n=>{let r=n.practice[mode].responses[item.id];r.rating=b.dataset.rate;r.at=Date.now();}))renderPractice(mode);return;}
 if(b.dataset.practiceNext||b.dataset.practiceBack){const mode=b.dataset.practiceNext||b.dataset.practiceBack,run=S.practice[mode],delta=b.dataset.practiceNext?1:-1;if(!run||run.endedAt||delta===1&&!itemDone(run,run.items[run.index]))return;if(change(n=>{n.practice[mode].index=Math.max(0,Math.min(run.items.length-1,run.index+delta));}))renderPractice(mode);return;}
 if(b.dataset.practiceFinish){finishPractice(b.dataset.practiceFinish);return;}
 if(b.dataset.again){const mode=b.dataset.again;if(change(n=>delete n.practice[mode]))renderPractice(mode);return;}
 if(b.dataset.retry){retryPractice(b.dataset.retry);return;}
 if(b.dataset.resetRequest){resetMode=b.dataset.resetRequest;if(resetMode==='labeling')renderLabels();else renderPractice(resetMode);const confirm=$(`[data-reset-confirm="${resetMode}"]`);confirm?.focus();return;}
 if(b.dataset.resetCancel){let mode=b.dataset.resetCancel;resetMode=null;if(mode==='labeling')renderLabels();else renderPractice(mode);$(`[data-reset-request="${mode}"]`)?.focus();return;}
 if(b.dataset.resetConfirm){resetPractice(b.dataset.resetConfirm);return;}
 if(b.hasAttribute('data-start-labels')||b.hasAttribute('data-redo-labels')){startLabels();return;}if(b.dataset.labelCheck){checkLabels(b.dataset.labelCheck);return;}if(b.hasAttribute('data-label-check-all')){checkLabels();return;}if(b.hasAttribute('data-label-finish')){finishLabels();return;}
 if(b.dataset.addFrayer){addFrayer(b.dataset.addFrayer);return;}if(b.dataset.frayerSelect){if(oversizeFrayers.size){status('Shorten or copy the unsaved overlong Frayer text before switching words.',true);return;}activeWord=b.dataset.frayerSelect;renderFrayers();return;}
 if(b.dataset.collectFrayer){const id=b.dataset.collectFrayer;if(!frayerValid(id)){status('All four Frayer fields must contain 1–240 characters before collection.',true);return;}if(change(n=>n.frayers[id].collected=true,'Frayer word collected. Its scientific accuracy still needs review.')){renderFrayers();renderWork();}return;}
 if(b.dataset.copyFrayer){copyFrayer(b.dataset.copyFrayer);return;}if(b.dataset.removeFrayer){removeWord=b.dataset.removeFrayer;renderFrayers();return;}if(b.hasAttribute('data-remove-cancel')){removeWord=null;renderFrayers();return;}if(b.dataset.removeConfirm){const id=b.dataset.removeConfirm;if(change(n=>delete n.frayers[id],'Selected word removed. Other work remains.')){for(let i=0;i<4;i++){oversizeFrayers.delete(id+':'+i);unsavedFrayerText.delete(id+':'+i);}removeWord=null;activeWord=null;renderFrayers();}return;}
 if(b.dataset.saveNote){const id=b.dataset.saveNote,v=S.notes[id];if(!v?.draft.trim()||v.draft.length>5000){status('Enter a response of 1–5000 characters before collecting it.',true);return;}if(change(n=>{n.notes[id].submitted=v.draft.trim();n.notes[id].at=Date.now();},'Optional written response collected. Required progress is unchanged.')){$(`[data-note-status="${id}"]`).textContent='Saved response collected. It has not been automatically graded.';renderWork();revisionActivities.render();}return;}
 if(b.dataset.playVideo){loadVideo(b);return;}
 if(b.hasAttribute('data-print-work')){renderWork();window.print();return;}
});
$('#nav-scrim').addEventListener('click',()=>setNav(false));
window.addEventListener('beforeprint',()=>{renderWork();document.body.classList.add('print-work');printDetails=$$('#process-collection details').map(d=>[d,d.open]);printDetails.forEach(([d])=>d.open=true);});
window.addEventListener('afterprint',()=>{printDetails.forEach(([d,open])=>d.open=open);document.body.classList.remove('print-work');});
window.addEventListener('beforeunload',e=>{if(oversizeFrayers.size||blocked){e.preventDefault();e.returnValue='';}});
// Preserve removed-diagram attempts without displaying retired images.
if(S.practice.labeling&&!labelSpec(S.practice.labeling.diagramId)){
 change(n=>{(n.retiredLabelingRuns??=[]).push(clone(n.practice.labeling));delete n.practice.labeling;},'Older diagram attempts preserved. Choose a package diagram to continue.');
}
window.mountBiologyTextbookPractice({chapter:C.chapter,read:()=>S.textbookWork||{},write:async(id,record)=>{if(!change(next=>{(next.textbookWork??={})[id]=record;}))throw Error('Chapter response storage failed.');}});
renderAllChecks();['flash','blanks','mc','mixed'].forEach(renderPractice);renderLabels();renderFrayers();restoreNotes();renderVideoLibrary();renderWork();route();tick();setInterval(tick,1000);
// Read-only inspection API for the local browser tests and later Codex integration.
Object.defineProperty(window,'BIOLOGY_HTML',{value:Object.freeze({chapter:C.chapter,storageKey:KEY,bankVersion:C.bankVersion,getSnapshot:()=>clone(S),getConfig:()=>clone(C)}),writable:false});
// Uses the existing chapter word IDs, state and Frayer controls.
let displayedWord=C.words[0].id,frayerMarker=null;
function wordDetails(w){return `<p class="eyebrow">${esc(C.lessons[w.lesson-1].title)}</p><h2>${esc(w.term)}</h2><section><p class="section-label">Meaning</p><p>${esc(w.meaning)}</p></section><section><p class="section-label">${w.whatItDoes?'What it does':'Example'}</p><p>${esc(w.whatItDoes||w.example)}</p></section><section><h3>Important distinction</h3><p>${esc(w.importantDistinction||w.confusion)}</p></section>${w.aliases.length?`<details><summary>More about this word</summary><p>Related wording: ${w.aliases.map(esc).join(', ')}.</p></details>`:''}`;}
function showReaderWord(id){displayedWord=id;const w=word(id);$('[data-biology-word-details]').innerHTML=wordDetails(w)+`<section class="frayer"><p class="section-label">Frayer model</p><h3>${esc(w.term)}</h3>${S.frayers[id]?'<p>Your selected word’s writing is below.</p>':`<p>Choose any eight words. Choosing opens an empty Frayer; it does not fill in your answers.</p><button type="button" data-add-frayer="${id}">Choose this word</button>`}</section>`;$$('[data-biology-select-word]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.biologySelectWord===id)));if(S.frayers[id]){activeWord=id;renderFrayers();}}
function filterWordIndex(){const q=norm($('[data-vocab-search]').value),topic=$('[data-vocab-topic]').value;let n=0;$$('[data-word-card]').forEach(el=>{const w=word(el.dataset.wordCard);el.hidden=Boolean((q&&!norm(w.term+' '+w.meaning).includes(q))||(topic!=='all'&&String(w.lesson)!==topic));if(!el.hidden)n++;});$$('.word-category').forEach(s=>s.hidden=![...s.querySelectorAll('[data-word-card]')].some(b=>!b.hidden));$('[data-vocab-count]').textContent=`${n} matching terms`;}
function restoreFrayerHome(){if(frayerMarker){const editor=$('[data-frayer-editor]');frayerMarker.replaceWith(editor);frayerMarker=null;}}
function showVocabularyPopup(id){restoreFrayerHome();const w=word(id);openDialog(w.term,`<label>Core Vocabulary<select data-popup-word>${C.words.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(x.term)}</option>`).join('')}</select></label><article data-biology-word-details>${wordDetails(w)}</article><details class="popup-frayer"><summary>My Frayer</summary><div data-popup-frayer>${S.frayers[id]?'':`<p>Choose this word to write your own Frayer.</p><button type="button" data-add-frayer="${id}">Choose this word</button>`}</div></details><p><a href="#core-vocabulary" data-dialog-route>Open Core Vocabulary</a></p>`,'bio-vocabulary');if(S.frayers[id]){activeWord=id;renderFrayers();const editor=$('[data-frayer-editor]');frayerMarker=document.createComment('Frayer home');editor.before(frayerMarker);$('[data-popup-frayer]').append(editor);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-biology-select-word]');if(b)showReaderWord(b.dataset.biologySelectWord);const choose=e.target.closest('[data-add-frayer]');if(choose){showReaderWord(choose.dataset.addFrayer);if(dialog.open&&dialog.classList.contains('bio-vocabulary')){const trigger=modalTrigger;showVocabularyPopup(choose.dataset.addFrayer);modalTrigger=trigger;}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-popup-word]')){const id=e.target.value,trigger=modalTrigger;showVocabularyPopup(id);modalTrigger=trigger;}});
// The portable HTML uses the embedded PDF for its inline library as well.
if(location.pathname.endsWith(`Biology30_Chapter${C.chapter}.html`)){const url=URL.createObjectURL(new Blob([Uint8Array.from(atob($('#textbook-data').textContent.trim()),c=>c.charCodeAt(0))],{type:'application/pdf'}));$('[data-library-textbook]').src=url+'#page=1';$('[data-library-fullscreen]').href=url;$('[data-library-download]').href=url;}
showReaderWord(displayedWord);

})();
