import {readFile,writeFile,mkdir,copyFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {load} from 'cheerio';
import {loadBiology20UnitA} from './lib/biology20-course/unit-a-inputs.js';
import {biology20Profile} from './lib/biology20-course/profile.js';
import {presentUnitAHubs} from './lib/biology20-course/hubs.js';
import {completeUnitAResources,UNIT_A_PARITY_CSS} from './lib/biology20-course/reference-parity.js';
import {TOPIC_MEDIA_CSS} from './lib/biology30-course/v1/pilot2-media.js';
import {topicHtml as h} from './lib/biology30-course/v1/pilot2-render-common.js';
import {renderBiology30Topic,TOPIC_COMPONENT_CSS} from './lib/biology30-course/v1/pilot2-render-topic.js';
import {renderPresentationShell} from './lib/biology30-course/v1/pilot2-presentation-shell.js';
import {renderTopicVocabulary} from './lib/biology30-course/v1/pilot2-render-vocabulary.js';
import {renderTopicCollectionPage,TOPIC_COLLECTION_CSS} from './lib/biology30-course/v1/pilot2-collection-view.js';
import {renderTopicSeminar,renderTopicPracticePage} from './lib/biology30-course/v1/pilot2-render-review.js';
import {renderTopicInvestigation} from './lib/biology30-course/v1/pilot2-render-investigation.js';
import {renderTopicModel} from './lib/biology30-course/v1/pilot2-render-model.js';
import {renderTopicNotes} from './lib/biology30-course/v1/pilot2-render-reference.js';
import {TOPIC_FIGURE_VIEWER_CSS} from './lib/biology30-course/v1/pilot2-figure-viewer.js';
import {VOCABULARY_PANEL_CSS} from './lib/biology30-vocabulary/panel.js';
import {addUnitAWordBrowser} from './lib/biology20-course/word-browser.js';
import {buildTopicActivityIndex} from './lib/biology30-course/v1/pilot2-activity-index.js';

const args=process.argv.slice(2);if(args.join(' ')!=='--module a')throw Error('This bounded owner currently accepts --module a only.');
const repo=process.cwd(),a=await loadBiology20UnitA(repo),{input,activities}=a,profile=biology20Profile('a');
const out=path.join(repo,'projects/biology20-unit-a/workspace'),resource=path.join(repo,'projects/resources/biology20-production/v1');
const pages=new Map<string,{title:string;html:string}>(),add=(id:string,title:string,html:string)=>{if(pages.has(id))throw Error('Duplicate route');pages.set(id,{title,html});};
const section=(title:string,body:string)=>`<div class="p2-topic"><h1>${h(title)}</h1>${body}</div>`;
for(const t of input.contract.topics)add(t.id,t.title,renderBiology30Topic(t.id,input));
for(const [route,title] of [['a-chapter-1-practice','Chapter 1 Practice'],['a-chapter-2-practice','Chapter 2 Practice'],['a-final-practice','Final Practice']])add(route,title,renderTopicPracticePage(title,route,a.practice.filter(p=>p.routeId===route),a.schema));
add('a-review-seminar','Review Seminar',renderTopicSeminar(a.integrated.seminar,a.schema)+section('Source links','<p>The summaries above are available offline. <a href="https://www.epa.gov/nutrientpollution/basic-information-nutrient-pollution" target="_blank" rel="noopener">EPA: Nutrient pollution</a> · <a href="https://science.nasa.gov/earth/earth-observatory/the-carbon-cycle/" target="_blank" rel="noopener">NASA: The Carbon Cycle</a></p>'));
add('a-core-vocabulary','Core Vocabulary',renderTopicVocabulary(input.vocabulary,input.contract,a.schema));
add('a-all-my-work','All My Work',renderTopicCollectionPage());
add('a-notes','My notes',renderTopicNotes(a.schema));
add('a-models','Models and Data Lab',section('Models and Data Lab','<p>Optional: predict, test, explain and save. These models do not add required responses.</p>'+a.integrated.models.map((m:any)=>renderTopicModel(m,a.schema,{lesson:input.contract.topics.find(t=>t.id===m.teachingTopicId),teaching:{...input.framing.topics.find(t=>t.topicId===m.teachingTopicId)!,observableQuestion:m.predictionPrompt}})).join('')+'<p><a href="#a-investigations" data-page-target="a-investigations">Open the supplied-data investigation</a> · <a href="#a-notes" data-page-target="a-notes">My notes</a></p>'));
add('a-investigations','Supplied-data investigation',section('Supplied-data investigation',a.integrated.investigations.map((i:any)=>renderTopicInvestigation(i,input.contract,a.schema,[],[])).join('')));
add('a-advanced','Advanced Learning',section('Advanced Learning','<p>Optional six-minute extensions. Each link returns to its exact lesson block.</p>'+input.contract.topics.map(t=>`<h2>${h(t.title)}</h2><ul>${t.parts.map(p=>{const x=a.instruction.parts.find((x:any)=>x.partId===p.id).advanced;return`<li><a href="#${h(t.id)}" data-pilot2-return-route="${h(t.id)}" data-pilot2-return-focus="${h(x.id)}">${h(x.title)}</a> — 6 minutes</li>`;}).join('')}</ul>`).join('')));
add('a-glossary','Glossary',section('Glossary','<label>Find a term<input type="search" data-pilot2-glossary-search></label><p data-pilot2-glossary-status role="status"></p><dl>'+input.vocabulary.introducedTerms.map(t=>`<div data-pilot2-glossary-term="${h(t.term)}"><dt>${h(t.term)}</dt><dd>${h(t.definition)} <a href="#${h(t.firstTeachingTopicId)}" data-pilot2-return-route="${h(t.firstTeachingTopicId)}" data-pilot2-return-focus="${h(t.firstTeachingPartId)}">Teaching explanation</a></dd></div>`).join('')+'</dl>'));
const books=[{file:'textbook-chapter-1.pdf',sha:'43ac232c5a3ee564e9bb443c5ff904e7faa3f990942929c4ea74c7145ab5925d',title:'Chapter 1 and Unit opening',pages:'2–31'}, {file:'textbook-chapter-2a.pdf',sha:'cd92f3543261cc7d369f839ed1ac72a8510cd1873b17b0d985c44d1d2a31dd90',title:'Chapter 2: Water',pages:'32–40'}, {file:'textbook-chapter-2b.pdf',sha:'e204fba085cd57b583710b24d927b29ea19a847bfbf57cdce0a8c1ef37b91797',title:'Chapter 2: Matter cycles and review',pages:'41 onward'}];
add('a-textbook','Textbook Library',section('Textbook Library','<p>Local supporting reading from the supplied course materials. The online lessons and saved practice contain the required work; physical and group textbook tasks are not additional requirements.</p>'+books.map(b=>`<section><h2>${h(b.title)}</h2><p>Printed pages ${h(b.pages)}. <a href="assets/${b.file}#page=1" target="_blank" rel="noopener">Open local PDF</a></p></section>`).join('')+'<p>Some source diagrams simplify system boundaries and transfer efficiencies. Use the distinctions and limitations developed in the lessons.</p>'));
add('a-video-library','Video and Walkthrough Library',section('Video and Walkthrough Library','<p>These local illustrated walkthroughs work without streaming, sound or an account. Each has the same saved checkpoint used in its lesson.</p><ul>'+input.contract.topics.map(t=>`<li><a href="#${h(t.id)}" data-pilot2-return-route="${h(t.id)}" data-pilot2-return-focus="${h(t.id)}-walkthrough">${h(t.title)}: illustrated walkthrough</a></li>`).join('')+'</ul>'));
add('a-sources-and-credits','Sources and Credits',section('Sources and Credits','<p>Teaching sequence: supplied Biology 20 Unit A slides and chapter daily plans. Supporting reading: supplied Inquiry into Biology chapters 1–2. Curriculum reference: Alberta Biology 20–30 Program of Studies.</p><p>New examples, numerical datasets and model results are illustrative, not reported experiments. The producer comparison is a ChatGPT-generated conceptual illustration, not microscopy or field evidence. Other lesson diagrams are course-authored scientific representations. Source archives, teacher keys and private LMS records are excluded.</p><p>This is a local review candidate. Technical verification is not teacher acceptance or formal curriculum certification. No physical experimentation or collaboration is claimed by the online investigations.</p><p>Fonts: Hanken Grotesk and Work Sans, with bundled Open Font Licenses.</p>'));
presentUnitAHubs(a,pages,books);
await completeUnitAResources(a,pages);
const wordDetailsPath='projects/resources/biology20-production/v1/units/a/word-details.json';
const wordDetails=JSON.parse(await readFile(path.join(repo,wordDetailsPath),'utf8'));
pages.get('a-core-vocabulary')!.html=addUnitAWordBrowser(a,pages.get('a-core-vocabulary')!.html,wordDetails);
let html=renderPresentationShell({title:profile.title,logoPath:'assets/brand/nxt-ce-logo-white-with-ce.png',seminar:a.integrated.seminar,topic:{contract:input.contract,practice:a.practice}},pages,TOPIC_COMPONENT_CSS+TOPIC_COLLECTION_CSS+TOPIC_FIGURE_VIEWER_CSS+VOCABULARY_PANEL_CSS+TOPIC_MEDIA_CSS,profile.presentation);
const $=load(html);$('.lesson-bottom-bar').remove();
$('head').append(`<style>${UNIT_A_PARITY_CSS}</style>`);
$('#overview .overview-intro>ol>li').last().find('span').text('Complete 12 core questions, use feedback and revise your reasoning.');
$('#overview .overview-intro>div>p').last().text('About 400 minutes of required online work, plus 108 minutes of optional Advanced Learning. These are online-task estimates, not classroom-hour equivalents.');
for(const [i,route] of input.contract.requiredRoutes.entries()){const prev=input.contract.requiredRoutes[i-1]??'overview',next=input.contract.requiredRoutes[i+1];$(`[id="${route}"]`).append(`<nav class="p2-required-nav" aria-label="Required activity sequence"><a href="#${prev}" data-page-target="${prev}">Previous</a>${next?`<a href="#${next}" data-page-target="${next}">Next: ${h(pages.get(next)!.title)}</a>`:'<a href="#a-all-my-work" data-page-target="a-all-my-work">Review all my work</a>'}</nav>`);}
$('body').children().not('script').wrapAll('<div id="pilot2-course-surface"></div>');
const payload=JSON.stringify({schemaVersion:1,activities,models:a.integrated.models,graphs:[]}).replace(/</g,'\\u003c');
$('body').append(`<div id="pilot2-recovery" hidden></div><script id="pilot2-course-data" type="application/json">${payload}</script><script defer src="assets/pilot2-course.js"></script>`);
const index=buildTopicActivityIndex(activities),ids=$('[id]').map((_,n)=>$(n).attr('id')).get();if(new Set(ids).size!==ids.length)throw Error('Duplicate HTML identity');
for(const entry of index)if($(`[id="${entry.routeId}"] [id="${entry.focusId}"]`).length!==1)throw Error('Missing activity destination: '+entry.id);
for(const dir of ['assets','assets/fonts','assets/brand'])await mkdir(path.join(out,dir),{recursive:true});
const files:string[]=[];const copy=async(src:string,dest:string)=>{await copyFile(src,path.join(out,dest));files.push(dest);};
await copy(path.join(repo,'projects/resources/biology30-unit-a-pilot/v2/assets/brand/nxt-ce-logo-white-with-ce.png'),'assets/brand/nxt-ce-logo-white-with-ce.png');
for(const font of ['HankenGrotesk-Variable.ttf','WorkSans-Variable.ttf','OFL-Hanken-Grotesk.txt','OFL-Work-Sans.txt'])await copy(path.join(repo,'projects/resources/biology30-production/v1/pilot2/presentation-assets/fonts',font),'assets/fonts/'+font);
for(const f of a.proof.input.figures)await copy(path.join(a.base,'figures',path.basename(f.src)),f.src);
for(const f of a.diagramFiles){await writeFile(path.join(out,f.src),f.svg);files.push(f.src);}
for(const f of a.sourceFigures)await copy(path.join(resource,'assets',f.file),'assets/source-'+f.suffix+'.png');
for(const b of books)await copy(path.join(resource,'assets',b.sha+'.pdf'),'assets/'+b.file);
const bundled=(await build({entryPoints:[path.join(repo,'scripts/lib/biology20-course/browser-entry.ts')],bundle:true,write:false,format:'iife',platform:'browser'})).outputFiles[0].text;
await writeFile(path.join(out,'assets/pilot2-course.js'),bundled);await writeFile(path.join(out,'index.html'),$.html());files.push('assets/pilot2-course.js','index.html');
const hashes=await Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(await readFile(path.join(out,file))).digest('hex')})));
const manifest=JSON.parse(await readFile(path.join(repo,'projects/biology20-unit-a/meta/project.json'),'utf8'));
const sourcePaths=new Set<string>(manifest.canonicalSources);
sourcePaths.add(wordDetailsPath);
for(const dir of ['scripts/lib/biology30-course/v1','scripts/lib/biology20-course','scripts/lib/biology30-vocabulary'])for(const f of await readdir(path.join(repo,dir)))if(f.endsWith('.ts'))sourcePaths.add(dir+'/'+f);
const sources=await Promise.all([...sourcePaths].sort().map(async file=>({file,sha256:createHash('sha256').update(await readFile(path.join(repo,file))).digest('hex')})));
await writeFile(path.join(out,'build.json'),JSON.stringify({status:'local-review-candidate; final-verification-required',regenerateCommand:'npx tsx scripts/build-biology20-course.ts --module a',sources,files:hashes,topics:6,teachingParts:18,advanced:18,practice:a.practice.length,requiredRoutes:input.contract.requiredRoutes.length,maximumState:a.maximum,capacity:a.capacity},null,2)+'\n');
console.log(JSON.stringify({workspace:out,files:hashes.length,maximumState:a.maximum,activities:index.length}));
