/** One-shot Science conversion. Refuses existing targets; never regenerates Studio edits. */
import {createHash,randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir,cp,access,rename,rm,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {execFileSync} from 'node:child_process';
import {load} from 'cheerio';
import JSZip from 'jszip';
import {build} from 'esbuild';
import {renderBiologyWordReader,BIOLOGY_WORD_READER_CSS} from './lib/biology30-vocabulary/word-reader.js';
import {termMatches} from './lib/biology30-vocabulary/panel.js';

const slug='biology30-unit-a-pilot-3',base='projects/biology30-unit-a-pilot-2',target='projects/'+slug;
const hash=(s:Buffer|string)=>createHash('sha256').update(s).digest('hex');
try{await access(target);throw Error('Pilot 3 already exists. Edit its canonical workspace; initialization cannot overwrite it.');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
const source=await readFile(base+'/workspace/index.html','utf8');
const protectedSlugs=['biology30-unit-a-pilot-2','biology30-unit-b','biology30-unit-c','biology30-unit-d'];
const protectedHashes=Object.fromEntries(await Promise.all(protectedSlugs.map(async s=>[s,hash(await readFile(`projects/${s}/workspace/index.html`))])));
const staging=await mkdtemp(path.join(os.tmpdir(),'biology30-pilot3-'));
const project=path.join(staging,slug),workspace=path.join(project,'workspace'),meta=path.join(project,'meta');
await mkdir(workspace,{recursive:true});await mkdir(meta);await mkdir(path.join(project,'raw'));
const write=(p:string,s:string)=>writeFile(path.join(project,p),s,'utf8');
const json=(p:string,d:unknown)=>write(p,JSON.stringify(d,null,2)+'\n');
try{
 for(const folder of ['brand','fonts','textbook'])await cp(`${base}/workspace/assets/${folder}`,`${workspace}/assets/${folder}`,{recursive:true});
 await mkdir(`${workspace}/assets/source`,{recursive:true});
 const deckPath='projects/resources/biology30-unit-a-pilot/_sources/74630659f9860c65b17356513c37f954d4df7b2a55742f1d535f5041e40abfb1.pptx';
 const deckBytes=await readFile(deckPath);if(hash(deckBytes)!==path.basename(deckPath,'.pptx'))throw Error('Slide source drift');
 const deck=await JSZip.loadAsync(deckBytes);
 await writeFile(`${workspace}/assets/source/neuron-slide9.png`,await deck.file('ppt/media/image3.png')!.async('nodebuffer'));
 await writeFile(`${workspace}/assets/source/reflex-slide18.png`,await deck.file('ppt/media/image9.png')!.async('nodebuffer'));
 // Source extraction only. Crops are in the observed 1200px page coordinate system.
 const pdf=`${workspace}/assets/textbook/chapter-11.pdf`;
 for(const [name,page,x,y,w,h] of [['neuron-textbook',13,90,580,445,515],['label-neurons',43,440,245,380,270]] as const){
  execFileSync('pdftoppm',['-f',String(page),'-l',String(page),'-scale-to','1200','-x',String(x),'-y',String(y),'-W',String(w),'-H',String(h),'-singlefile','-png',pdf,`${workspace}/assets/source/${name}`]);
 }
 const old=load(source),faithful=load(await readFile('projects/biology30-unit-a-class-2026-faithful/workspace/index.html','utf8'));
 const originals=[2130965,2130967].map(id=>faithful(`input[id*="obj-${id}"]`).first().closest('fieldset'));
 const questions=originals.map((node,i)=>({id:'check-'+(i+1),sourceId:'class-2026-27:res-quiz-59222:obj-'+[2130965,2130967][i],correct:JSON.parse(node.attr('data-correct-values')!)[0],choices:node.find('input').map((_,n)=>faithful(n).val()).get()}));
 await cp('projects/biology30-unit-a-class-2026-faithful/workspace/assets/source/class-2026-27/PastedImage_bwqjs29q7mlij8c432ahi7dpnq65w5ll002.png',`${workspace}/assets/source/reflex-question-table.png`);
 const sourceQuestions=questions.map((q,i)=>({...q,prompt:originals[i].find('.practice-prompt').text().trim(),choiceLabels:originals[i].find('.practice-choice label').map((_,n)=>faithful(n).text().trim()).get()}));
 const wordData=JSON.parse(await readFile(base+'/meta/word-details.json','utf8'));
 const wordSchema={identity:hash(JSON.stringify(wordData.words.map((w:any)=>w.id))),wordIds:wordData.words.map((w:any)=>w.id),legacyIds:[],limit:240};
 const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const reading=(page:number)=>`<a href="#textbook-library" data-book-page="${page-359}">Textbook p. ${page}</a>`;
 const header=(label:string,title:string,intro:string)=>`<header class="page-header"><p class="eyebrow">${label}</p><h1>${title}</h1><p>${intro}</p></header>`;
 const page=(id:string,content:string)=>`<section class="course-page" id="${id}" hidden><div class="p2-topic">${content}</div></section>`;
 const figure=(src:string,alt:string,caption:string)=>`<figure><a href="assets/source/${src}" target="_blank" rel="noopener"><img src="assets/source/${src}" alt="${alt}" loading="lazy"></a><figcaption>${caption} Select the image to enlarge.</figcaption></figure>`;
 const videos=[{id:'A44brRGG4Ys',title:'Structure of a Neuron',slide:11,watch:'Identify the dendrite, cell body, axon and myelin. Follow the direction of the message.'},{id:'4WcZR_k_a0I',title:'Types of Neurons: Reflex Arcs',slide:19,watch:'Follow the sensory neuron into the spinal cord and the motor neuron out to the muscle.'}];
 const video=(i:number,instance:string)=>{const v=videos[i];return `<section class="video-support" data-video="${v.id}"><h3>${v.title}</h3><p>${v.watch}</p><div data-video-slot></div><button type="button" data-load-video>Load video</button> <a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener">Watch on YouTube</a><p class="muted">Chapter 11 PowerPoint, slide ${v.slide}. The lesson explanation also covers this idea if playback is unavailable.</p></section>`;};
 const run=(id:string,title:string,body:string)=>`<section class="activity" data-activity="${id}" id="activity-${id}"><h2>${title}</h2><p>Start when you are ready. Elapsed time includes breaks and time away until you submit.</p><div class="save-row"><button type="button" data-start>Start</button><output data-timer aria-label="Elapsed time">Not started</output></div><fieldset data-run-body disabled>${body}</fieldset><div class="save-row"><button type="button" data-submit-run disabled>Submit and finish</button><button type="button" data-redo hidden>Redo whole activity</button></div><p data-run-status role="status" aria-live="polite"></p></section>`;
 const labels=[['A','sensory neuron','The upper neuron carries a message from the skin.'],['B','interneuron','The middle neuron links the incoming and outgoing neurons.'],['C','motor neuron','The lower neuron carries a message towards the muscle.'],['D','sensory receptor','This structure detects the change in the skin.'],['J','effector','The muscle responds by contracting.']];
 const blanks=[['dendrite','A short branch that receives a nerve impulse is a _____.'],['axon','The long fibre carrying an impulse away from the cell body is the _____.'],['myelin','The insulating layer that speeds transmission is called _____.'],['interneuron','The neuron that links sensory and motor neurons in the CNS is an _____.']];
 const fields=(rows:string[][],type:string)=>rows.map(([answer,prompt],i)=>`<div class="question" data-question="${type}-${i+1}"><label for="${type}-${i+1}">${prompt}</label><input id="${type}-${i+1}" type="text" autocomplete="off" data-answer><button type="button" data-check>Check answer</button><p data-feedback role="status"></p></div>`).join('');
 const cards=[['Dendrite','Receives impulses and carries them towards the cell body.'],['Cell body','Contains the nucleus and other organelles.'],['Axon','Carries impulses away from the cell body.'],['Myelin','Insulates many axons and speeds impulse transmission.'],['Sensory neuron','Carries impulses from receptors towards the CNS.'],['Interneuron','Links sensory and motor neurons within the CNS.'],['Motor neuron','Carries impulses from the CNS to an effector.'],['Reflex arc','The pathway followed during a rapid, involuntary response.']];
 const flash=cards.map(([term,meaning],i)=>`<div class="question" data-question="card-${i+1}"><h3>${term}</h3><details><summary>Reveal meaning</summary><p>${meaning}</p></details><p>Could you recall the meaning before revealing it?</p><button type="button" data-self="recalled">I recalled it</button> <button type="button" data-self="study-again">Study again</button><p data-feedback role="status"></p></div>`).join('');
 const writing=['List the three types of neurons, and identify their primary functions.','A student puts her hand on hot glassware, but withdraws her hand before she feels the pain. Explain how and why her awareness of the pain is delayed.'];
 const check=questions.map((q,i)=>`<section class="question" data-question="${q.id}"><h3>Question ${i+1}</h3>${i===1?'<img src="assets/source/reflex-question-table.png" alt="Rows: a, axon to dendrite; b, sensory receptor to muscle effector; c, brain to gland effector; d, motor neuron to sensory neuron.">':''}<p>${esc(sourceQuestions[i].prompt)}</p>${q.choices.map((v:string,j:number)=>`<label class="choice"><input type="radio" name="${q.id}" value="${v}" data-answer> ${esc(sourceQuestions[i].choiceLabels[j])}</label>`).join('')}<button type="button" data-check>Check answer</button><p data-feedback role="status"></p><p class="muted">Original learner-visible Chapter 11 Quiz, question ${i===0?1:3}.</p><fieldset class="paired-writing" data-unlock="${q.id}" disabled><legend>After a correct answer: explain the related idea</legend><label for="written-${i+1}">${writing[i]}</label><textarea id="written-${i+1}" rows="5" data-writing="written-${i+1}" aria-describedby="written-limit-${i+1}"></textarea><small id="written-limit-${i+1}">Up to 900 characters. Submitted for teacher review, not automatically graded.</small><p>${reading(i===0?370:371)} · ${i===0?'Question 5':'Investigation 11.A, application 4'}</p><button type="button" data-submit-writing>Save written response</button><p data-writing-status role="status"></p></fieldset></section>`).join('');
 const reviewPrompts=['Describe the structure of a myelinated neuron.','Compare the structure and functions of myelinated neurons and unmyelinated neurons.'];
 const review=reviewPrompts.map((p,i)=>`<section class="question" data-question="review-${i+1}"><label for="review-${i+1}">${p}</label><textarea id="review-${i+1}" rows="5" data-writing="review-${i+1}"></textarea><small>Up to 900 characters. Written evidence, not automatically graded.</small><p>${reading(i===0?372:384)} · ${i===0?'Question 8':'Section 11.1 review, question 3'}</p><button type="button" data-submit-writing>Save written response</button><p data-writing-status role="status"></p></section>`).join('');
 const pages=[
 page('overview',header('Biology 30 · Unit A · Pilot 3','How do neurons carry messages?','Learn the parts of a neuron and how they work together in a reflex arc.')+`<div class="content-section"><h2>One lesson for comparison</h2><p>This pilot follows your Chapter 11 notes. Read the lesson, try the practice activities and complete the lesson check. Your saved work stays in this browser.</p><a class="button primary" href="#lesson-01">Begin Neuron Structure</a><h2>Your route</h2><ol><li>Learn from the notes, textbook figures and videos.</li><li>Practise with flashcards, blanks and image labels.</li><li>Answer two multiple-choice questions, then write about the same ideas.</li><li>Open Process Collection to review your attempts, time and writing.</li></ol><p>Other Unit A lessons and the separate advanced course are not part of this pilot.</p></div>`),
 page('lesson-01',header('Learn · Chapter 11','Neuron Structure','Use the parts of a neuron to follow a message from a receptor to an effector.')+`<div class="content-section"><p><strong>Reading:</strong> ${reading(367)}–372 and ${reading(384)}. Source sequence: Chapter 11 slides 1–20.</p><p><strong>Before you start:</strong> a stimulus is a change, such as heat or pressure. A response is what the body does after detecting that change.</p></div>
 <section class="content-section" data-teaching><h2>Nerves and nerve cells</h2><p>The nervous system helps the body respond to changes inside and outside the body. It works with the endocrine system to maintain homeostasis. Nervous messages are electrochemical. Endocrine messages are hormones carried in the blood.</p><p>A neuron is a nerve cell that carries nerve impulses. Glial cells support and nourish neurons. A nerve is a bundle of nerve fibres in the peripheral nervous system.</p></section>
 <section class="content-section" data-teaching><h2>Parts of a neuron</h2><dl class="plain-definitions"><div><dt>Dendrite</dt><dd>A short branch that receives impulses and carries them towards the cell body.</dd></div><div><dt>Cell body</dt><dd>The main part of the cell. It contains the nucleus and other organelles.</dd></div><div><dt>Axon</dt><dd>A longer fibre that carries impulses away from the cell body.</dd></div><div><dt>Axon terminal</dt><dd>A branching end that passes a message to another cell. The junction between cells is called a synapse.</dd></div></dl>${figure('neuron-textbook.png','Textbook neuron with dendrites, cell body, nucleus, axon, myelin sheath, Schwann cell and a node of Ranvier.','Textbook Figure 11.9, printed p. 372. The arrows show the direction of the impulse.')}<p>${reading(372)}</p>${video(0,'lesson')}</section>
 <section class="content-section" data-teaching><h2>Myelin helps messages travel faster</h2><p>Myelin is a fatty covering around many axons. It insulates the axon and speeds up impulse transmission. A Schwann cell makes myelin in the peripheral nervous system. Other glial cells make it in the brain and spinal cord.</p><p>A node of Ranvier is a gap between myelin segments. In a myelinated axon, the impulse is renewed at these gaps. This is called saltatory conduction and is often described as the impulse “jumping” from node to node.</p><table><caption>Myelinated and unmyelinated axons</caption><thead><tr><th>Myelinated</th><th>Unmyelinated</th></tr></thead><tbody><tr><td>Has a myelin covering</td><td>Has no myelin covering</td></tr><tr><td>Impulse transmission is generally faster</td><td>Impulse transmission is generally slower</td></tr></tbody></table><p>Damage to myelin can slow or interrupt nerve messages. Multiple sclerosis is one condition that damages myelin and can affect sensation, movement and balance.</p></section>
 <section class="content-section" data-teaching><h2>Three types of neurons</h2><dl class="plain-definitions"><div><dt>Sensory neuron</dt><dd>Carries impulses from sensory receptors towards the brain and spinal cord.</dd></div><div><dt>Interneuron</dt><dd>Found in the central nervous system. It links sensory and motor neurons.</dd></div><div><dt>Motor neuron</dt><dd>Carries impulses from the central nervous system to an effector, such as a muscle or gland.</dd></div></dl><p>The central nervous system, or CNS, is the brain and spinal cord. An effector carries out a response. Neurons can also have different shapes: multipolar, bipolar or unipolar.</p><p>${reading(369)}–370</p></section>
 <section class="content-section" data-teaching><h2>The reflex arc</h2><p>A reflex is a quick, involuntary response to a stimulus. A withdrawal reflex can protect you by moving your hand away from something hot before you consciously feel the pain.</p><ol><li>A sensory receptor detects the stimulus.</li><li>A sensory neuron carries an impulse towards the spinal cord.</li><li>An interneuron passes the message to a motor neuron.</li><li>The motor neuron carries an impulse to an effector.</li><li>The muscle contracts and pulls the hand away.</li></ol>${figure('reflex-slide18.png','Source reflex-arc diagram showing the sensory receptor, sensory neuron, interneuron, motor neuron and muscle effector.','Chapter 11 PowerPoint, slide 18. This shows one reflex pathway.')}<p>The message also travels to the brain. The spinal response can happen before conscious awareness. Some other reflexes connect a sensory neuron directly to a motor neuron without an interneuron.</p>${video(1,'lesson')}<p>${reading(370)}–371</p></section><div class="content-section"><a class="button primary" href="#practice">Practise these ideas</a> <a href="#lesson-check">Go to the lesson check</a></div>`),
 page('practice',header('Practice & Review','Memorization practice','These drills are adapted from your slides and textbook labels. They collect attempts and time but do not affect your lesson-check mark.')+run('flashcards','Flashcards',flash)+run('blanks','Fill in the blanks',fields(blanks,'blank'))+run('labeling','Label the source figure',figure('label-neurons.png','Lettered textbook diagram. Upper pathway runs from the skin to a central neuron; lower pathway runs from the central neuron to a muscle.','Textbook p. 402, question 10 figure. The five-label drill is adapted from the source task.')+labels.map(([letter,answer,hint])=>`<section class="question" data-question="label-${letter}"><label for="label-${letter}">Label ${letter}</label><input id="label-${letter}" type="text" data-answer autocomplete="off"><details><summary>Accessible description for label ${letter}</summary><p>${hint}</p></details><button type="button" data-check>Check answer</button><p data-feedback role="status"></p></section>`).join(''))),
 page('lesson-check',header('Practice & Review','Lesson check','Answer correctly to unlock the related writing. Your mark uses your first answer to each multiple-choice question in this run.')+run('lesson-check','Neuron Structure check',check)),
 page('topic-review',header('Practice & Review','Topic review','Revisit myelin using the original textbook questions. Your explanations and elapsed time are collected. Writing is not automatically graded.')+run('topic-review','Myelination review',review)),
 page('process-collection',header('Process Collection','All My Work','Review your submitted answers, first-try marks, retries and elapsed time. These are local records, not Brightspace submissions.')+`<div class="content-section"><button type="button" data-download>Download my Process Collection</button> <button type="button" data-print>Print</button><p data-collection-status role="status"></p><div data-history data-canvas-helper-studio-edit="annotation-only"></div><h2>My Frayers</h2><div data-frayer-history data-canvas-helper-studio-edit="annotation-only"></div></div>`),
 page('core-vocabulary',header('Process Collection','Core Vocabulary','Explore individual words. Choose any eight for your own Frayers. Definitions are available immediately; no writing is filled in for you.')+`<p class="content-section"><strong data-p2-vocabulary-progress>0 of 8</strong> added to Process Collection. The reference includes Unit A vocabulary beyond this one-lesson pilot.</p>`+renderBiologyWordReader(wordData.words,wordData.categories)),
 page('textbook-library',header('Resources','Textbook Library','Open Chapter 11 at the page linked from the lesson or questions.')+`<div class="content-section"><h2>Chapter 11 · The Nervous System</h2><p>44 PDF pages · printed pp. 360–403</p><p><a href="assets/textbook/chapter-11.pdf" data-book-external target="_blank" rel="noopener">Open chapter full screen</a> <a href="assets/textbook/chapter-11.pdf" download>Download chapter</a></p><iframe title="Chapter 11 textbook" data-textbook src="assets/textbook/chapter-11.pdf#page=8" style="width:100%;height:72vh;border:1px solid var(--border)"></iframe></div>`),
 page('video-library',header('Resources','Video Library','The same source videos used in Neuron Structure. Each has a local lesson explanation.')+videos.map((v,i)=>`<div class="content-section">${video(i,'library')}<p><a href="#lesson-01">Return to Neuron Structure</a></p></div>`).join('')),
 page('sources-and-credits',header('Resources','Sources and Credits','A local, one-lesson comparison pilot based on the supplied Biology 30 material.')+`<div class="content-section"><h2>Teaching and pictures</h2><p>Chapter 11 daily plan, slides 1–20, and the supplied textbook Chapter 11. Pictures are extracted source figures, not AI-generated illustrations. PowerPoint figure reuse is for this private review; original third-party permissions remain a release check.</p><h2>Questions</h2><p>The lesson check retains learner-visible Chapter 11 Quiz questions 1 and 3 from the 2026–27 Brightspace export. Paired writing uses textbook p. 370 question 5 and p. 371 application 4. Topic review uses p. 372 question 8 and p. 384 question 3. Memorization drills are explicitly adapted from source definitions and labels.</p><h2>Small scientific corrections</h2><p>Schwann cells make peripheral myelin; different glial cells make central myelin. Myelin alone does not determine whether an injured neuron regenerates. The notes’ “MS is a genetic disorder” statement is not repeated. The reflex explanation refers specifically to the spinal withdrawal pathway, rather than implying every reflex bypasses the brain.</p><h2>Saving and review</h2><p>All work is saved only in this browser. Clearing browser data removes local records. Download Process Collection before changing devices. Brightspace reporting, other lessons and the separate advanced course are deferred.</p><p>Fonts and branding are reused from Pilot 2 under their existing licenses. Pilot 2 has not been modified.</p></div>`)
 ];
 const doc=load('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Biology 30 Unit A Pilot 3</title><link rel="stylesheet" href="styles.css"></head><body></body></html>');
 const top=old('.course-header').first().length?old('.course-header').first():old('body>header').first();
 doc('body').append(top.clone());doc('body').append(old('#course-sidebar').clone());
 doc('.sidebar-title').text('Biology 30 — Unit A: Pilot 3');doc('.sidebar-title').attr('data-canvas-helper-course-title','');
 const nav=doc('#course-sidebar nav').empty();
 for(const [title,items] of [['Start',[['overview','Overview']]],['Learn',[['lesson-01','1. Neuron Structure']]],['Practice & Review',[['practice','Memorization practice'],['lesson-check','Lesson check'],['topic-review','Topic review']]],['Process Collection',[['process-collection','All My Work'],['core-vocabulary','Core Vocabulary']]],['Resources',[['textbook-library','Textbook Library'],['video-library','Video Library'],['sources-and-credits','Sources and Credits']]]] as [string,string[][]][]){nav.append(`<details class="nav-group" open><summary>${title}</summary><div class="nav-links">${items.map(([id,label])=>`<a class="nav-link" href="#${id}" data-page-target="${id}">${label}</a>`).join('')}</div></details>`);}
 doc('[data-save-exit],.save-exit,.sidebar-exit').remove();doc('#course-sidebar').append('<div class="sidebar-footer"></div>');
 doc('body').append(`<main class="main" id="course-main"><div class="course-frame">${pages.join('')}</div></main><p class="local-save-status" data-local-status role="status">Opening local saved work…</p>`);
 doc('body').append(`<script type="application/json" id="pilot3-words">${JSON.stringify({data:{...wordData,wordFrayers:{},choicePolicy:'any-eight'},schema:wordSchema}).replace(/</g,'\\u003c')}</script><script src="assets/pilot3-runtime.js"></script>`);
 // Pre-link in canonical HTML so the runtime does not replace editable lesson prose.
 doc('[data-teaching]').each((_,section)=>{const seen=new Set<string>();const walk=(n:any)=>{for(const child of [...(n.children??[])]){if(child.type==='text'){const text=child.data,matches=termMatches(text,wordData.words.map((w:any)=>w.term),seen);if(matches.length){let at=0,out='';for(const m of matches){out+=esc(text.slice(at,m.start))+`<button type="button" class="bio-term" data-bio-term="${esc(m.term)}" data-bio-term-route="lesson-01" aria-haspopup="dialog">${esc(text.slice(m.start,m.end))}</button>`;at=m.end;}doc(child).replaceWith(out+esc(text.slice(at)));}}else if(!['a','button','script','style','label','summary'].includes(child.name))walk(child);}};walk(section);});
 doc('h1,h2,h3,p,li,figure,table,dl,a').each((i,n)=>doc(n).attr('data-canvas-helper-edit-key','p3-content-'+i));
 doc('[data-start],[data-submit-run],[data-redo],[data-check],[data-self],[data-submit-writing],[data-timer],[data-history],[data-local-status]').attr('data-canvas-helper-studio-edit','annotation-only');
 await write('workspace/index.html',doc.html());
 await write('workspace/styles.css',old('style').map((_,n)=>old(n).text()).get().join('\n')+'\n'+BIOLOGY_WORD_READER_CSS+'\n'+await readFile('scripts/lib/biology30-pilot3/pilot3.css','utf8'));
 await build({entryPoints:['scripts/lib/biology30-pilot3/runtime.ts'],outfile:`${workspace}/assets/pilot3-runtime.js`,bundle:true,platform:'browser',format:'iife',target:'es2022'});
 const catalog={schema:1,questions:sourceQuestions,blanks:blanks.map(([answer],i)=>({id:'blank-'+(i+1),answers:[answer,...(answer==='myelin'?['myelin sheath']:[])]})),labels:labels.map(([l,a])=>({id:'label-'+l,answers:a==='effector'?[a,'muscle','muscle effector']:a==='sensory receptor'?[a,'receptor']:[a]}))};
 // Scoring is a code-controlled companion, not duplicated in editable prompts.
 await write('workspace/assets/pilot3-catalog.js','window.PILOT3_CATALOG='+JSON.stringify(catalog)+';\n');
 const final=load(await readFile(`${workspace}/index.html`,'utf8'));final('script[src]').before('<script src="assets/pilot3-catalog.js"></script>');await write('workspace/index.html',final.html());
 await write('raw/pilot-2-reference.html',source);
 await json('meta/source-map.json',{schemaVersion:1,scope:'Lesson 1 only; local saving. LMS reporting deferred.',sourceHtmlSha:hash(source),deck:{path:deckPath,sha256:hash(deckBytes),slides:[1,20]},textbook:{path:base+'/workspace/assets/textbook/chapter-11.pdf',sha256:hash(await readFile(pdf)),printedPages:[367,368,369,370,371,372,384]},questions:catalog.questions.map(q=>({id:q.id,sourceId:q.sourceId,prompt:q.prompt})),written:[{id:'written-1',page:370,question:5},{id:'written-2',page:371,question:'11.A application 4'},{id:'review-1',page:372,question:8},{id:'review-2',page:384,question:3}],protectedHashes,corrections:['Peripheral versus central myelin','No regeneration guarantee from myelination','Do not call MS simply a genetic disorder','Spinal withdrawal reflex scope'],figurePolicy:'Source figures only; embedded PowerPoint provenance remains a release boundary',initializer:'npx tsx scripts/create-biology30-unit-a-pilot-3.ts (one-time, refuses existing target)'});
 await json('meta/project.json',{id:randomUUID(),slug,title:'Biology 30 — Unit A: Pilot 3',inputKind:'html',sourcePath:`${target}/raw/pilot-2-reference.html`,projectType:'conversion',migrationState:'migrated',preferredWorkflows:['conversion'],canonicalEntry:`${target}/workspace/index.html`,canonicalSources:[`${target}/workspace/index.html`,`${target}/workspace/styles.css`,`${target}/workspace/assets/pilot3-catalog.js`,'scripts/lib/biology30-pilot3/runtime.ts'],generatedOutputs:[`${target}/workspace/assets/pilot3-runtime.js`],workspaceEntrypoint:'workspace/index.html',authoringStatus:'blocked',authoring:{driverId:'direct-workspace-v1',editabilityContract:{schemaVersion:1,profileId:'studio-routine-content-v1'},learnerSurfaces:{schemaVersion:1,mode:'static-pages-complete',pages:[{htmlPath:'index.html',route:''}]},studioEditing:{enabled:false,renameCourse:false,imageAssets:false}},exportTargets:[{target:'html',enabled:false},{target:'scorm',enabled:false}],referenceOnly:[`${target}/raw/pilot-2-reference.html`,'scripts/create-biology30-unit-a-pilot-3.ts','scripts/lib/biology30-pilot3/pilot3.css'],sourceOfTruthNotes:'One-time source conversion. Workspace HTML/CSS and catalog are canonical; no content regeneration. Runtime-only bundle rebuild: npx esbuild scripts/lib/biology30-pilot3/runtime.ts --bundle --platform=browser --format=iife --target=es2022 --outfile=projects/biology30-unit-a-pilot-3/workspace/assets/pilot3-runtime.js. Studio remains disabled until measured ownership and lifecycle gates pass. No LMS reporting or export yet.'});
 await write('meta/prompt-pack.md','# Biology30 A Pilot 3\n\nOne-lesson, local-only comparison. Canonical content is workspace/index.html and styles.css. Initializer is reference-only and refuses overwrite. Never run Pilot 2 builders on this project. Preserve original A/Pilot2/B/C/D. Activities use source questions and adapted drills. Any-eight vocabulary remains. Brightspace reporting, other lessons, advanced course, export and ZIP are deferred.\n');
 for(const s of protectedSlugs)if(hash(await readFile(`projects/${s}/workspace/index.html`))!==protectedHashes[s])throw Error('Protected workspace drift '+s);
 await rename(project,target);console.log('Created '+target+'; direct ownership pending readiness proof.');
}finally{await rm(staging,{recursive:true,force:true});}
