import content from '../content/critical-essay.json';
import { TeachingStudio, isLearningNotebook } from './teaching.js';
const E = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]);
const icon = name => `<img class="ico" src="assets/icons/${name}.svg" alt="">`;
const link = (path,label,primary=false) => `<a class="btn ${primary?'primary':''}" href="#${path}">${E(label)}${icon('arrow-right')}</a>`;
const paragraphs = items => items.map(text=>`<p>${E(text)}</p>`).join('');
const sourceLabel = () => `<p class="model-source">${E(content.label)}</p>`;
const lessonRows = lessons => lessons.map((lesson,i)=>`<a class="lesson-row" href="#/critical/${lesson.id}"><span class="lesson-number">${i+1}</span><div><h3>${E(lesson.title)}</h3><p>${E(lesson.summary)}</p></div>${icon('arrow-right')}</a>`).join('');
export function criticalHelp(ids,title='Teaching for this stage') {
  return `<details class="critical-help"><summary>${icon('book-open')}${E(title)}</summary>${ids.map(id=>{const lesson=content.lessons.find(item=>item.id===id);return `<div><h3>${E(lesson.title)}</h3><p>${E(lesson.explanation[0])}</p><p class="mini-model"><strong>Teaching model</strong><br>${E(lesson.model)}</p><a href="#/critical/${id}">Study the explanation, comparison &amp; practice →</a></div>`;}).join('')}<p class="model-source">Models are separate from your work. Every stage is optional.</p></details>`;
}
export function revisionCategory(passId) {
  const category=content.categories.find(item=>item.pass.includes(passId));
  return category?`<section class="category-guidance"><h3>${E(category.name)}</h3><p>${E(category.question)}</p><p class="meta"><strong>Example:</strong> ${E(category.example)}</p><a href="#/critical/review">See the five review categories</a></section>`:'';
}
export class CriticalEssayStudio extends TeachingStudio {
  home() {
    const projects=(this.getWorkspace()?.projects||[]).filter(item=>!isLearningNotebook(item)&&!item.archived).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
    return `${this.header('Critical Essay Studio','English 30-1 · Develop an interpretation, explain your evidence, and shape a purposeful argument.')}<section class="critical-intro"><div class="critical-welcome-copy"><p>Bring your own assignment and literary text. Study a skill, try a short practice, plan an essay, or use the optional editor. Choose any stage in any order.</p><div class="page-actions">${link('/projects/new','Start my essay',true)}${link('/projects','Open My Work')}${link('/critical','Explore the teaching')}</div></div><img class="welcome-desk" src="assets/thumbnails/desk.webp" alt=""></section><div class="teaching-entry-grid"><a href="#/critical/model">${icon('book-open')}<div><h3>Study a complete example</h3><p>Read an original story and a complete annotated essay. Follow how the interpretation develops from precise details.</p><span>Open story &amp; annotated essay →</span></div></a><a href="#/critical/alternative">${icon('lightbulb')}<div><h3>Try another approach</h3><p>A second short passage shows how another interpretation and arrangement can be equally defensible.</p><span>Compare approaches →</span></div></a></div>${projects.length?`<section class="card recent-work"><p class="eyebrow">Your recent work</p><h2>${E(projects[0].title)}</h2><p>${E(projects[0].type.replaceAll('-',' '))} · Your own work</p>${link(`/project/${projects[0].id}/plan`,'Reopen my work',true)}</section>`:''}<section class="recommended-lessons"><h2>Choose the move you need</h2>${lessonRows(content.lessons)}</section><section class="teaching-scope"><h2>Classroom tasks and diploma preparation</h2><p>The teaching supports Alberta English 30-1. Your teacher’s assignment sets the permitted text, length, form, and citation requirements. Diploma-specific instructions are explained separately.</p><a href="#/critical/review">Understand self-review and diploma expectations →</a></section>`;
  }
  list() { return `${this.header('Critical essay teaching','Eight substantial sections. Start anywhere, return when needed, and save only the practice you want to keep.')}<div class="page-actions">${link('/critical/model','Read the connected model')}${link('/critical/review','Self-review & diploma expectations')}</div><section class="recommended-lessons">${lessonRows(content.lessons)}</section>`; }
  lesson(id) {
    const lesson=content.lessons.find(item=>item.id===id);
    if(!lesson)return this.list();
    return `<a class="teaching-back" href="#/critical">${icon('arrow-left')}Critical essay teaching</a>${this.header(lesson.title,lesson.summary)}<section class="lesson-explanation" id="learn"><h2>Understand the move</h2>${paragraphs(lesson.explanation)}</section><section class="lesson-worked" id="model"><h2>Study an annotated model</h2><div class="annotated-excerpt prose">${paragraphs([lesson.model])}</div>${sourceLabel()}<ol class="model-reasoning">${lesson.annotations.map((text,i)=>`<li><strong>Notice ${i+1}</strong><p>${E(text)}</p></li>`).join('')}</ol><a href="#/critical/model">Read the story and complete essay →</a><h3>Weaker to stronger</h3><div class="comparison"><div><h4>Weaker starting point</h4><p>${E(lesson.weak)}</p></div><div><h4>Stronger reasoning</h4><p>${E(lesson.strong)}</p></div></div><p>${E(lesson.comparisonReason)}</p></section>${this.practice(`learning:critical:${id}`,`Critical essay — ${lesson.title}`,lesson.practice,lesson.hints,[`How does my response answer the task?`,`Which precise detail supports the reasoning?`,`What might qualify or change my interpretation?`])}<section class="lesson-transfer" id="transfer"><h2>Transfer to your own work</h2><p>${E(lesson.transfer)}</p><div class="practice-actions"><button data-study-action="reviewed:critical-${id}" ${this.canSave()?'':'disabled'}>${icon(this.reviewed(`critical-${id}`)?'check':'book-open')}${this.reviewed(`critical-${id}`)?'Marked reviewed — change':'Mark section reviewed'}</button>${link('/projects','Open My Work')}${link('/critical','Choose another section')}</div></section><p class="model-source">English 30-1 outcomes: ${E(lesson.outcomes.join(', '))} · Self-review: ${E(lesson.categories.join('; '))}</p>`;
  }
  model() {
    return `${this.header('A connected critical essay example','Read the source, then examine the essay’s choices. The source and response are original teaching models.')}<nav class="example-links" aria-label="Example sections"><button data-study-scroll="story">Read the story</button><button data-study-scroll="essay">Jump to annotated essay</button><a href="#/critical/alternative">Try the second passage</a></nav><section class="card model-task"><h2>Teaching task</h2><p>${E(content.task)}</p><p class="model-source">This task is for studying the example. Use your own assignment for your essay.</p></section><article id="story" class="original-story"><h2>${E(content.story.title)}</h2>${sourceLabel()}<div class="prose">${content.story.paragraphs.map((text,i)=>`<p><span class="paragraph-locator">${i+1}</span>${E(text)}</p>`).join('')}</div></article><article id="essay" class="annotated-essay"><h2>${E(content.essay.title)}</h2><p class="model-source">Complete original model essay · ${content.essay.paragraphs.map(item=>item.text).join(' ').split(/\s+/).length} words · Paragraph locators refer to the teaching story.</p>${content.essay.paragraphs.map((item,i)=>`<section class="essay-section"><div class="prose"><p>${E(item.text)}</p></div><details class="essay-annotations" open><summary>Why paragraph ${i+1} works</summary>${item.annotations.map(annotation=>`<p><strong>${E(annotation.label)}</strong><br>${E(annotation.detail)}</p>`).join('')}</details></section>`).join('')}<p>The model uses five body paragraphs because its argument has five distinct jobs. Your argument determines its own length and organization.</p>${link('/critical','Study the individual skills')}</article>`;
  }
  alternative() {
    return `${this.header('Alternative interpretations and structures','The same task can produce a different argument. Let this passage’s details determine the approach.')}<article class="original-story"><h2>${E(content.second.title)}</h2>${sourceLabel()}<div class="prose">${content.second.paragraphs.map((text,i)=>`<p><span class="paragraph-locator">${i+1}</span>${E(text)}</p>`).join('')}</div></article><section class="lesson-worked"><h2>Two defensible directions</h2>${content.alternative.interpretations.map(item=>`<section class="card alternative-claim"><p class="prose">${E(item.claim)}</p><p><strong>Why it is plausible</strong><br>${E(item.why)}</p></section>`).join('')}<h3>Choose an arrangement</h3><p>${E(content.alternative.organization)}</p></section>${this.practice('learning:critical:alternative','Critical essay — alternative approaches',content.alternative.practice,['Consider what the final action changes and what it leaves unresolved.','Acknowledge the role of the erased line; the apron alone does not explain the conflict.','You may defend a different interpretation with accurate evidence.'])}<section class="lesson-transfer"><h2>Transfer</h2><p>Test two interpretations of your own text. Choose the one that explains the evidence most fully, and keep a useful qualification from the other.</p>${link('/critical/interpretation','Develop an interpretation')}</section>`;
  }
  review() {
    return `${this.header('Self-review and assignment expectations','Use questions and examples to make revision decisions. These categories do not generate grades.')}<section class="category-list">${content.categories.map(category=>`<section class="card"><h2>${E(category.name)}</h2><p>${E(category.question)}</p><p class="mini-model"><strong>Teaching example</strong><br>${E(category.example)}</p><p class="meta">Studio passes: ${E(category.pass.join(' · '))}</p></section>`).join('')}</section><section class="lesson-explanation"><h2>Your classroom assignment</h2><p>Use the instructions and criteria your teacher provides. A classroom task can specify a particular work, comparison, paragraph, length, or citation format. Ask for clarification when those requirements are unclear. The tool does not assume every classroom response is a diploma assignment.</p><h2>Diploma-specific preparation</h2><p>The Critical / Analytical Response to Literary Texts asks you to discuss ideas developed by a text creator in a literary text you have studied. Prepare with a text complex enough to support developed analysis. The prompting texts supplied for Personal Response are not the literary source for this critical response.</p><p>Alberta’s student guide suggests 800–1600 words for this response; that is guidance, not a compulsory word count in this studio. Accurate, specific references can include paraphrase and scene details as well as quotations. Do not invent quotations. Follow the current exam instructions for any source restrictions or procedures.</p><p>The official scoring guide describes performance across the five categories above. Use it to understand expectations alongside the student guide. The questions here are original teaching prompts, not an official rubric or automated assessment.</p><ul><li><a href="https://curriculum.learnalberta.ca/curriculum/en/pos/LANENG_HS/ELA3105" target="_blank" rel="noopener noreferrer">Implemented English 30-1 curriculum</a></li><li><a href="https://www.alberta.ca/system/files/edc-ela-30-1-scoring-guide.pdf" target="_blank" rel="noopener noreferrer">Alberta English 30-1 scoring guide</a></li><li><a href="https://www.alberta.ca/system/files/custom_downloaded_images/edc-ela30-1-guide-for-students.pdf" target="_blank" rel="noopener noreferrer">Alberta English 30-1 guide for students</a></li></ul></section>${link('/critical/revision','Practise a deliberate revision')}`;
  }
  resources() { return `${this.header('Resources','Teaching for your critical essay, with earlier writing resources available for reference.')}<div class="teaching-entry-grid"><a href="#/critical">${icon('book-open')}<div><h3>Critical essay teaching</h3><p>The eight sections for English 30-1, with models and optional practice.</p></div></a><a href="#/critical/model">${icon('file')}<div><h3>Story &amp; annotated essay</h3><p>The complete original teaching example and connected process.</p></div></a><a href="#/lessons">${icon('book-open')}<div><h3>Writing lessons</h3><p>All 18 earlier writing lessons. Existing lesson routes and saved practice are retained.</p></div></a><a href="#/explorer/characterization">${icon('eye')}<div><h3>Analysis Explorer</h3><p>Earlier literary concept teaching, original passages, and worked explanations.</p></div></a></div><section class="card"><h2>Earlier guided practice</h2><p>Earlier analytical and personal response teaching stays available. This build creates critical essays. Expanded Personal Response development is a separate later task.</p><div class="page-actions">${link('/response/analytical/0','Earlier analytical practice')}${link('/response/personal/0','Earlier personal practice')}${link('/study-notes','Saved practice & notes')}</div></section><p class="teaching-scope"><a href="#/critical/review">Curriculum, scoring categories &amp; source links →</a></p>`; }
  criticalWritingHelp() {
    const concerns=['I am unsure what the question asks','My controlling idea is too general','I have too much evidence or cannot choose','My explanation keeps retelling the text','My paragraphs repeat each other','My opening or ending does not develop the idea','My sentences do not express the relationship clearly','I need a revision decision'];
    return `${this.header('Help with my critical essay','Choose the concern that fits your work. Each link opens the relevant explanation, model and practice.')}<section class="critical-help-list">${content.lessons.map((lesson,i)=>`<section class="card"><h2>${E(concerns[i])}</h2><p>${E(lesson.summary)}</p><a href="#/critical/${lesson.id}">Work on ${E(lesson.title.toLowerCase())} →</a></section>`).join('')}</section><p class="teaching-scope"><a href="#/help">Help with saving, recovery &amp; export →</a></p>`;
  }
  render(path) {
    if(path==='/home')return this.home();
    if(path==='/resources')return this.resources();
    if(path==='/writing-help')return this.criticalWritingHelp();
    if(path.startsWith('/critical')) {const id=path.split('/')[2];if(id==='model')return this.model();if(id==='alternative')return this.alternative();if(id==='review')return this.review();return id?this.lesson(id):this.list();}
    const earlier=['/lessons','/library','/explorer','/response'].some(prefix=>path===prefix||path.startsWith(`${prefix}/`));
    let result;
    if(path.startsWith('/lessons/')||path.startsWith('/library/'))result=TeachingStudio.prototype.lesson.call(this,path.startsWith('/library/')?({ 'guide-purpose':'purpose','guide-thesis':'interpretation','guide-paragraph':'paragraph','guide-evidence':'evidence','guide-analysis':'beyond-summary','guide-quotation':'quotation','guide-opening':'opening','guide-organization':'organization','guide-narrative':'narrative','guide-voice':'precise-language','guide-revision':'revision','guide-feedback':'feedback' }[path.split('/')[2]]||path.split('/')[2]):path.split('/')[2]);
    else result=super.render(path);
    return earlier?`<p class="earlier-resource-label">Earlier writing resource · <a href="#/critical">Open Critical Essay Studio teaching →</a></p>${result}`:result;
  }

  context(path) {
    if(!['/home','/resources'].includes(path)&&!path.startsWith('/critical'))return super.context(path);
    const id=path.split('/')[2], lesson=content.lessons.find(item=>item.id===id);
    return `<section class="card teaching-context"><h2>${lesson?'In this section':'Your next move'}</h2>${lesson?`<button data-study-scroll="learn">Understand the move</button><button data-study-scroll="model">Study the model</button><button data-study-scroll="try-it">Try it yourself</button><button data-study-scroll="transfer">Transfer to my work</button><h3>Your focus</h3><p>${E(lesson.summary)}</p>`:'<p>Choose any skill or stage. You can learn and practise without creating an essay.</p><a href="#/critical">Browse critical essay teaching →</a><a href="#/critical/model">Story &amp; annotated essay →</a>'}<h3>Bring your own text</h3><p>The original examples teach a process. They do not supply material for your assignment.</p><a href="#/projects">Open My Work →</a><a href="#/study-notes">Saved practice &amp; notes →</a></section><section class="card"><h2>Keep your thinking</h2><p>Save practice only when it helps. It goes to your separate learning notebook. Your draft changes only when you choose to write or insert your own material.</p></section>`;
  }
}
