import lessonContent from '../content/lessons.json';
import explorerContent from '../content/analysis-lessons.json';

export const NOTEBOOK_PROMPT = 'Writing Studio learning notebook. Practice and notes shared across assignments.';
export const isLearningNotebook = project => project.practiceMode && project.prompt === NOTEBOOK_PROMPT;
export const isTeachingRoute = path => ['/critical', '/resources', '/home', '/lessons', '/explorer', '/response', '/study-notes', '/writing-help', '/library'].some(prefix => path === prefix || path.startsWith(`${prefix}/`));
const E = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const icon = name => `<img class="ico" src="assets/icons/${name}.svg" alt="">`;
const link = (path, label, primary = false) => `<a class="btn ${primary ? 'primary' : ''}" href="#${path}">${E(label)}${icon('arrow-right')}</a>`;
const legacyGuideRoutes = { 'guide-purpose':'purpose', 'guide-thesis':'interpretation', 'guide-paragraph':'paragraph', 'guide-evidence':'evidence', 'guide-analysis':'beyond-summary', 'guide-quotation':'quotation', 'guide-opening':'opening', 'guide-organization':'organization', 'guide-narrative':'narrative', 'guide-voice':'precise-language', 'guide-revision':'revision', 'guide-feedback':'feedback' };
const personalSteps = [
  { title:'Understand the task', lesson:'read-the-task', description:'Start with the actual assignment. Find the idea it asks you to explore and the forms or sources it permits.', explanation:'A personal response develops an understanding through the text and a meaningful connection. It is not automatically a personal story, and it does not require private disclosure. Read the teacher’s instructions before selecting a form.', prompt:'What does your task ask you to explore? What forms and sources are permitted?', model:'Practice focus: explore how a person’s sense of belonging changes when they are trusted to contribute.', why:'The focus names a relationship to explore. It does not prescribe someone’s personal experience or a fixed essay shape.', hints:['Retain the important words and relationship in the prompt.','If you are practising independently, write a question you want to explore.'] },
  { title:'Find your impression and insight', lesson:'purpose', description:'Name an impression from the text, then explain the idea behind it.', explanation:'An impression can start as a feeling, question, or observation. Develop it into an insight you can explore. Instead of “the scene is sad,” ask which choice produces that impression and what it suggests about the situation.', prompt:'What idea, feeling, or impression does the text create? Which detail produces it, and what might it suggest?', model:'The spare chair makes the welcome seem incomplete: Noor is present but not yet treated as someone whose ideas matter. The scene suggests that participation depends on recognition as well as access.', why:'The interpretation begins with a specific detail, explains the impression, and develops a larger idea.', hints:['Move from the feeling to the detail that creates it.','A working insight may change as you explore the evidence.'] },
  { title:'Choose and explain a detail', lesson:'beyond-summary', description:'Make the connection between a precise moment and your insight visible.', explanation:'Keep enough context for a reader to understand the detail. Then explain the choice or contrast that gives it significance. A second quotation is not a replacement for explaining the first.', prompt:'Record a verified quotation, paraphrase, or scene detail. Label its type. Explain how it develops the insight you are exploring.', model:'Scene detail: Noor’s chair moves from the corner to the table. Explanation: the movement gives a physical form to the change in her role. She is no longer only accommodated; she is included in the group’s decisions.', why:'The explanation uses the change in position to develop a distinction between presence and participation.', hints:['Do not place quotation marks around remembered or paraphrased wording.','Ask: Why this action or language, rather than another?'] },
  { title:'Make a meaningful connection', lesson:'personal-connection', description:'Use a safe connection to deepen the idea, then return to the text.', explanation:'Where your task permits, connect through knowledge, observation, experience, or imagination. Similar events do not need to be identical. A useful connection helps you question, clarify, or complicate the insight.', prompt:'What connection helps you understand this idea? Explain its significance and an important similarity or difference. Use an example you are comfortable sharing.', model:'An observed team member became more confident after receiving a small responsibility. This helps explain why asking Noor for her judgment matters more than simply finding her a chair: trust makes the welcome active.', why:'The observation has a reflective purpose and returns to the source’s specific detail.', hints:['You do not have to disclose private experiences.','Explain what the connection helps you understand; do not only describe it.'] },
  { title:'Choose a form and organize the thinking', lesson:'form', description:'Decide how the reader will experience the idea and the connection.', explanation:'Choose a permitted form that serves your purpose. A reflection may move between a moment and its meaning. An analytical response makes its reasoning explicit. Plan the role of each section rather than only numbering examples.', prompt:'Which permitted form and perspective will you use, and why? Outline the jobs of your beginning, development, and ending.', model:'A reflection: begin with being offered a place; consider why a responsibility changes the experience; return to the text with a clearer distinction between access and participation.', why:'Each part changes what the reader understands, and the order has a reason.', hints:['Your form must fit the assignment.','Use the organization lesson when sections repeat the same point.'] },
  { title:'Try an opening and review your plan', lesson:'opening', description:'Give the reader a starting point and test the direction before you continue.', explanation:'A useful opening leads toward the idea your response will develop. It can begin with a precise moment, a contrast, or a direct insight. Review the plan for a clear focus, explained evidence, and a connection that has a purpose.', prompt:'Try a short opening or controlling idea. Then identify one strength in the plan and one connection you still need to develop.', model:'A seat makes someone present; being asked for an opinion can make them matter. I want to explore the difference between being welcomed into a room and being trusted to participate in it.', why:'The opening introduces a specific contrast that the planned response can develop.', hints:['An opening is provisional; revisit it after developing the response.','Use the revision lesson to explain a meaningful change rather than just checking boxes.'] }
];
const analyticalSteps = [
  { title:'Read the task and establish a focus', lesson:'read-the-task', description:'Identify the question your interpretation must answer.', explanation:'An analytical response investigates how choices develop meaning. The actual task may require a particular source, comparison, or interpretive concern. State the question before gathering quotations.', prompt:'What relationship or question does your task ask you to analyze? Identify the source you will use if the task requires one.', model:'How does a change in a character’s role develop an idea about inclusion?', why:'The question requires a relationship between a specific change and a larger idea.', hints:['Separate the topic from the task.','Use the teacher’s prompt and criteria as the authority.'] },
  { title:'Develop a working interpretation', lesson:'interpretation', description:'Connect an observable choice to an effect and a larger idea.', explanation:'Your interpretation should give the response a direction while remaining open to refinement. Name the choice or pattern it depends on and the meaning it suggests. Avoid a topic label that can fit almost any text.', prompt:'What does the source suggest about your focus? Which choice, contrast, or pattern supports that interpretation?', model:'The movement of the spare chair from corner to table suggests that inclusion becomes meaningful when someone’s knowledge influences shared decisions.', why:'The claim is grounded in an observable pattern and explains a relationship.', hints:['Use choice → effect → meaning.','Keep the claim specific and qualified enough to support.'] },
  { title:'Select evidence and test the claim', lesson:'evidence', description:'Choose details that support, refine, or complicate the interpretation.', explanation:'Look for precise details with a purpose. An interpretation becomes stronger when it can account for important complications rather than ignoring them. Verify the wording and locator before quoting.', prompt:'Record two precise details and label their evidence type. Explain what each supports or complicates in your interpretation.', model:'Early detail: Noor records decisions without speaking. Later detail: the group asks what she observed. Together they contrast passive presence with a recognized contribution.', why:'The two details work together; neither is selected simply because it is dramatic.', hints:['Keep scene descriptions separate from direct quotations.','Ask what evidence would make you refine the claim.'] },
  { title:'Explain the reasoning', lesson:'beyond-summary', description:'Show the link a reader cannot get from the detail alone.', explanation:'Analysis explains how a choice creates an effect. Focus on a particular action, word, contrast, or position. Replace a repeated summary with the reasoning that connects it to your point.', prompt:'Choose one detail. Explain its significant choice, its effect, and how that effect develops your interpretation.', model:'A chair offers physical access; a question recognizes knowledge. This contrast explains why Noor’s change is social, not simply spatial: the group begins to treat her as a participant.', why:'The explanation adds a relationship instead of repeating where Noor sits.', hints:['Ask “Why this detail?” and “What changes because of it?”.','Do not claim an author’s private intention as a verified fact.'] },
  { title:'Plan distinct paragraph roles', lesson:'organization', description:'Arrange points so the reader’s understanding develops.', explanation:'Give each paragraph a job within the response. You might establish a condition, trace a change, and consider its consequence. Use only a sequence that fits your evidence, and explain the relationships between sections.', prompt:'Plan two or three paragraph roles. State the point, detail, and reasoning each needs, then explain the order.', model:'First: show the limits of the apparent welcome. Next: explain the turning point when Noor is asked to contribute. Finally: connect the chair’s changed position to continuing participation.', why:'The sections develop an argument from condition, through change, to consequence.', hints:['Do not organize only as quotation one, two, and three.','A complication can refine your argument rather than weaken it.'] },
  { title:'Practise a developed paragraph', lesson:'paragraph', description:'Use a short practice paragraph to test the plan’s thinking.', explanation:'Write enough context for the detail, integrate evidence accurately, and develop the connection. End with what the paragraph establishes. This is a practice space, not a requirement to write the whole assignment here.', prompt:'Draft one paragraph. Then identify its purpose, evidence, reasoning, and one revision you would make.', model:'The group’s welcome initially gives Noor access without influence. Although a chair is found for her, its placement in the corner leaves her recording decisions rather than joining them. When the group later asks for her observations, her knowledge becomes part of the shared work. The changed role reveals that meaningful inclusion depends on recognizing a contribution.', why:'The paragraph develops one point through a contrast and its consequences.', hints:['The paragraph’s sentence count is not its purpose.','Use the revision lesson before polishing individual sentences.'] }
];

export class TeachingStudio {
  constructor({ main, getWorkspace, canSave, saveResponse, markReviewed, announce, download, repaint, tabOnly }) {
    Object.assign(this, { main, getWorkspace, canSave, saveResponse, markReviewed, announce, download, repaint, tabOnly });
    this.responses = new Map(); this.answers = new Map(); this.saved = new Set(); this.search = ''; this.category = 'all'; this.termSearch = '';
    main.addEventListener('input', event => {
      const target = event.target;
      if (target.dataset.studyResponse) { this.responses.set(target.dataset.studyResponse, target.value); this.saved.delete(target.dataset.studyResponse); const status = main.querySelector('[data-study-status]'); if (status) status.textContent = 'Practice changed. Save when you are ready.'; }
      if (target.id === 'lesson-search') { this.search = target.value; this.filterLessons(); }
      if (target.id === 'term-search') { this.termSearch = target.value; this.filterTerms(); }
    });
    main.addEventListener('change', event => {
      if (event.target.id === 'lesson-category') { this.category = event.target.value; this.filterLessons(); }
      if (event.target.id === 'practice-text') { const term = location.hash.split('/')[2] || 'characterization'; location.hash = `/explorer/${term}/${event.target.value}`; }
    });
    main.addEventListener('click', async event => {
      const target = event.target.closest('[data-study-action]');
      if (!target) return;
      try { await this.action(target.dataset.studyAction); } catch (error) { this.announce(String(error)); const output = main.querySelector('[data-study-status]'); if (output) output.textContent = String(error); }
    });
  }
  notes() { return (this.getWorkspace()?.projects || []).filter(isLearningNotebook).flatMap(project => project.notes).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); }
  value(key) { return this.responses.has(key) ? this.responses.get(key) : this.notes().find(note => note.originLabel === key)?.body || ''; }
  reviewed(id) { return !!this.getWorkspace()?.library.bookmarks.includes(`lesson:${id}:reviewed`); }
  practice(key, title, prompt, hints, checklist = []) {
    const writable = this.canSave();
    return `<section class="lesson-practice" id="try-it"><h2>Try it yourself</h2><p>${E(prompt)}</p><label for="practice-answer">Your practice response</label><textarea id="practice-answer" rows="6" maxlength="16000" data-study-response="${E(key)}" placeholder="Try a short response to practise the move. You can use any text or task.">${E(this.value(key))}</textarea><details class="teaching-details"><summary>${icon('lightbulb')}Show hints</summary><ul>${hints.map(hint => `<li>${E(hint)}</li>`).join('')}</ul></details>${checklist.length ? `<h3>Review your thinking</h3><ul class="self-check-list">${checklist.map(item => `<li>${icon('check')}<span>${E(item)}</span></li>`).join('')}</ul>` : ''}<div class="practice-actions"><button class="btn primary" data-study-action="save:${E(key)}" data-study-title="${E(title)}" ${writable ? '' : 'disabled'}>${icon('save')}${this.tabOnly() ? 'Save practice in this tab' : 'Save practice to my notes'}</button><a href="#/study-notes">Open saved practice</a></div><p class="practice-status" data-study-status role="status">${this.saved.has(key) ? 'Practice recorded in your notebook. Check the save status above.' : writable ? 'Saving is optional. Keep the practice that helps your thinking.' : 'Lessons and practice are available. Saved changes are unavailable in this launch; you can copy your response.'}</p></section>`;
  }
  header(title, description, back = '') { return `${back ? `<a class="teaching-back" href="#${back}">${icon('arrow-left')}Writing lessons</a>` : ''}<header class="teaching-header"><h1>${E(title)}</h1><p>${E(description)}</p></header>`; }
  home() {
    const count = lessonContent.lessons.filter(lesson => this.reviewed(lesson.id)).length;
    return `${this.header('Writing Studio', 'Learn the moves that make your ideas clearer. Study a model, try a short practice, and apply it to any text or assignment.')}<section class="studio-start"><h2>What would you like to work on?</h2><div class="teaching-entry-grid"><a href="#/explorer/characterization">${icon('eye')}<div><h3>Understand a text</h3><p>Explore nine literary concepts through observations and worked analysis.</p><span>Open Analysis Explorer →</span></div></a><a href="#/response/personal/0">${icon('plan')}<div><h3>Build a response</h3><p>Work from an idea to explained evidence and a purposeful response plan.</p><span>Choose a guided practice →</span></div></a><a href="#/lessons">${icon('book-open')}<div><h3>Learn a writing skill</h3><p>Use 18 lessons with explanations, models, hints, and practice.</p><span>Browse writing lessons →</span></div></a><a href="#/writing-help">${icon('lightbulb')}<div><h3>Get unstuck</h3><p>Find the next move when a claim, paragraph, or revision is not working.</p><span>Find help with my writing →</span></div></a></div></section><section class="teaching-home-model"><div class="section-heading"><h2>See what analysis adds</h2><a href="#/lessons/beyond-summary">Study this lesson →</a></div><div class="comparison"><div><h3>Summary</h3><p>The character keeps a broken key.</p><p class="muted">Tells us what happens.</p></div><div><h3>Analysis</h3><p>Keeping a key that can no longer open the door suggests an attachment to what the home represented, rather than to entering the building.</p><p class="muted">Explains why that particular detail matters.</p></div></div><p class="model-source">Original fictional teaching example. Models are for learning; your response remains your own.</p></section><section class="recommended-lessons"><div class="section-heading"><h2>A useful starting path</h2><span>${count} of 18 lessons marked reviewed</span></div>${['read-the-task','interpretation','evidence','beyond-summary','paragraph','revision'].map((id,index) => { const lesson=lessonContent.lessons.find(item=>item.id===id); return `<a class="lesson-row" href="#/lessons/${id}"><span class="lesson-number">${index+1}</span><div><h3>${E(lesson.title)}</h3><p>${E(lesson.summary)}</p></div>${icon(this.reviewed(id)?'check':'arrow-right')}</a>`; }).join('')}</section><p class="teaching-scope">Use the studio whenever you need it. No required novel, story, film, or assignment is attached to these tools.</p>`;
  }
  lessonList() {
    const categories = [...new Set(lessonContent.lessons.map(lesson=>lesson.category))];
    return `${this.header('Writing lessons', 'Choose the move you need today. Every lesson teaches the thinking, shows a model, and gives you a short practice.')}<div class="lesson-filters"><label for="lesson-search">Find a skill<input id="lesson-search" type="search" value="${E(this.search)}" placeholder="Search analysis, openings, evidence…"></label><label for="lesson-category">Area<select id="lesson-category"><option value="all">All writing skills</option>${categories.map(category=>`<option ${this.category===category?'selected':''}>${E(category)}</option>`).join('')}</select></label></div><p class="lesson-result-count" data-lesson-results>18 lessons</p><div class="lesson-library">${lessonContent.lessons.map((lesson,index)=>`<article class="teaching-lesson-card" data-lesson-category="${E(lesson.category)}" data-lesson-search="${E(`${lesson.title} ${lesson.summary} ${lesson.category}`.toLowerCase())}"><div class="lesson-card-meta"><span>${E(lesson.category)} · ${lesson.minutes} min practice</span>${this.reviewed(lesson.id)?`${icon('check')}<span>Reviewed</span>`:''}</div><h2><a href="#/lessons/${lesson.id}">${E(lesson.title)}</a></h2><p>${E(lesson.summary)}</p><a class="lesson-open" href="#/lessons/${lesson.id}">Study lesson ${index+1}${icon('arrow-right')}</a></article>`).join('')}</div><p class="model-source">Original teaching lessons and fictional models · teacher review candidate.</p>`;
  }
  lesson(id) {
    const lesson=lessonContent.lessons.find(item=>item.id===id);
    if(!lesson) return this.lessonList();
    const index=lessonContent.lessons.indexOf(lesson), chosen=this.answers.get(id);
    return `${this.header(lesson.title,lesson.summary,'/lessons')}<div class="lesson-meta">Lesson ${index+1} of 18 · ${E(lesson.category)} · About ${lesson.minutes} minutes of practice</div><section class="lesson-purpose"><h2>What you will learn</h2><p>${E(lesson.aim)}</p></section><section class="lesson-explanation" id="learn"><h2>Understand the move</h2>${lesson.explanation.map(text=>`<p>${E(text)}</p>`).join('')}<ol class="teaching-steps">${lesson.steps.map(step=>`<li><h3>${E(step.label)}</h3><p>${E(step.detail)}</p></li>`).join('')}</ol></section><section class="lesson-worked" id="model"><h2>Study a worked model</h2><h3>${E(lesson.model.title)}</h3><div class="comparison"><div><h4>Starting point</h4><p>${E(lesson.model.before)}</p></div><div><h4>Developed version</h4><p>${E(lesson.model.after)}</p></div></div><p class="model-source">${E(lessonContent.exampleLabel)}.</p><h3>Why the developed version works</h3><ol class="model-reasoning">${lesson.model.annotations.map(item=>`<li><strong>${E(item.label)}</strong><p>${E(item.detail)}</p></li>`).join('')}</ol></section><section class="thinking-check" id="check-thinking"><h2>Check your thinking</h2><p>${E(lesson.check.question)}</p><div class="thinking-choices">${lesson.check.choices.map((choice,i)=>`<button data-study-action="check:${id}:${i}" aria-pressed="${chosen===i}" class="${chosen===i?'selected':''}">${E(choice.text)}</button>`).join('')}</div>${chosen!==undefined?`<div class="thinking-feedback" role="status"><strong>${lesson.check.choices[chosen].correct?'That reasoning fits.':'Reconsider the connection.'}</strong><p>${E(lesson.check.choices[chosen].feedback)}</p></div>`:''}<p class="model-source">This checks a writing decision, not the quality of your own response.</p></section>${this.practice(`learning:lesson:${id}`,lesson.title,lesson.practice,lesson.hints,lesson.selfCheck)}<section class="lesson-transfer"><h2>Use it in your own work</h2><p>${E(lesson.transfer)}</p><div class="practice-actions"><button data-study-action="reviewed:${id}" ${this.canSave()?'':'disabled'}>${icon(this.reviewed(id)?'check':'book-open')}${this.reviewed(id)?'Marked reviewed — change':'Mark lesson reviewed'}</button>${index<lessonContent.lessons.length-1?link(`/lessons/${lessonContent.lessons[index+1].id}`,'Next lesson'):link('/lessons','Choose another lesson')}</div></section>`;
  }
  explorer(termId='characterization', textId='key') {
    const term=explorerContent.terms.find(item=>item.id===termId)||explorerContent.terms[0];
    const text=explorerContent.practiceTexts.find(item=>item.id===textId)||explorerContent.practiceTexts[0];
    const example=term.examples.find(item=>item.textId===text.id);
    return `${this.header('Analysis Explorer','Learn how a literary choice becomes an interpretation. Apply the same thinking to any story, poem, play, film, or image.')}<div class="analysis-learning-shell"><aside class="concept-nav" aria-label="Literary concepts"><label for="term-search">Find a concept<input id="term-search" type="search" value="${E(this.termSearch)}" placeholder="Search nine concepts"></label>${explorerContent.terms.map(item=>`<a data-term-search="${E(item.title.toLowerCase())}" href="#/explorer/${item.id}/${text.id}" ${item.id===term.id?'aria-current="page"':''}>${E(item.title)}</a>`).join('')}</aside><article class="concept-detail"><h2>${E(term.title)}</h2><p class="concept-definition">${E(term.definition)}</p><h3>What to notice</h3><p>${E(term.notice)}</p><details class="teaching-details"><summary>A common trap</summary><p>${E(term.avoid)}</p></details><div class="practice-text-control"><label for="practice-text">Study an original practice passage<select id="practice-text">${explorerContent.practiceTexts.map(item=>`<option value="${item.id}" ${item.id===text.id?'selected':''}>${E(item.title)}</option>`).join('')}</select></label><p>These short passages are examples for learning. They do not select the text for your assignment.</p></div><details class="practice-passage" open><summary>${icon('book-open')}Read “${E(text.title)}”</summary>${text.text.split('\n\n').map(p=>`<p>${E(p)}</p>`).join('')}<p class="model-source">${E(text.label)} · created for this studio.</p></details><section class="explorer-worked"><h3>Work through the analysis</h3><div class="analysis-observation"><span>1. Notice a precise detail</span><p>${E(example.detail)}</p></div><div class="analysis-interpretation"><span>2. Explain what it suggests</span><p>${E(example.analysis)}</p></div><div class="analysis-reasoning"><span>3. Follow the reasoning</span><p>${E(example.why)}</p></div><p class="writing-move"><strong>The writing move</strong><br>${E(term.move)}</p><button data-study-action="keep-model:${term.id}:${text.id}" ${this.canSave()?'':'disabled'}>${icon('evidence')}Keep this model in my notes</button><p class="model-source">Saved models remain labelled as models, separate from your own practice.</p></section></article></div>${this.practice(`learning:explorer:${term.id}`,`${term.title} — my practice`,term.practice,[`Use the move: ${term.move}.`,'Your interpretation needs a reason a reader can follow, not just a technique name.'],['I identify a particular choice or pattern.','I explain its effect in context.','I connect the effect to an idea I can support.'])}`;
  }
  response(mode='personal',number=0) {
    mode=mode==='analytical'?'analytical':'personal'; const steps=mode==='personal'?personalSteps:analyticalSteps;
    number=Math.min(5,Math.max(0,Number(number)||0)); const step=steps[number];
    return `${this.header('Build a response','Use short guided practice to develop your thinking. Bring any task or text; write the full assignment wherever you normally work.')}<nav class="response-types" aria-label="Response approach"><a href="#/response/personal/0" ${mode==='personal'?'aria-current="page"':''}>Personal response</a><a href="#/response/analytical/0" ${mode==='analytical'?'aria-current="page"':''}>Analytical response</a></nav><ol class="response-step-tabs">${steps.map((item,index)=>`<li><a href="#/response/${mode}/${index}" ${index===number?'aria-current="step"':''}><span>${index+1}</span>${E(item.title)}</a></li>`).join('')}</ol><section class="response-guidance"><div class="lesson-meta">${mode==='personal'?'Personal':'Analytical'} response · Step ${number+1} of 6</div><h2>${E(step.title)}</h2><p class="concept-definition">${E(step.description)}</p><p>${E(step.explanation)}</p><div class="response-model"><h3>Study the move in a model</h3><p>${E(step.model)}</p><h4>Why it works</h4><p>${E(step.why)}</p><p class="model-source">Original fictional teaching example · the model is not inserted into your response.</p></div><a href="#/lessons/${step.lesson}">Need more teaching? Open the full lesson →</a></section>${this.practice(`learning:response:${mode}:${number}`,`${mode==='personal'?'Personal':'Analytical'} response — ${step.title}`,step.prompt,step.hints)}<nav class="response-navigation" aria-label="Guided response steps">${number>0?link(`/response/${mode}/${number-1}`,'Previous step'):''}${number<5?link(`/response/${mode}/${number+1}`,'Next step',true):link('/study-notes','Review saved practice',true)}</nav>`;
  }
  savedNotes() {
    const notes=this.notes();
    return `${this.header('Saved practice & notes','Keep the learning that helps you. These notes can support any assignment; they do not submit a paper.')}<div class="practice-actions"><button data-study-action="export-notes" ${notes.length?'':'disabled'}>${icon('download')}Export notes as text</button><button data-study-action="print-notes">${icon('printer')}Print / PDF</button><a href="#/settings">Workspace backup</a></div>${notes.length?`<div class="study-note-list">${notes.map(note=>`<article class="study-note"><div class="study-note-meta">${note.originLabel.startsWith('learning:model:')?'Original teaching model':'Your practice'} · ${E(new Date(note.updatedAt).toLocaleDateString())}</div><h2>${E(note.title)}</h2><p class="study-note-body">${E(note.body)}</p>${this.notePath(note.originLabel)?`<a href="#${this.notePath(note.originLabel)}">Return to this practice →</a>`:''}</article>`).join('')}</div>`:'<section class="teaching-empty"><h2>No practice saved yet</h2><p>Start with a lesson or the Analysis Explorer. Save a short response when it helps you, or keep an example as a labelled teaching model.</p>'+link('/lessons','Choose a lesson',true)+'</section>'}<p class="teaching-scope">${this.tabOnly()?'This preview keeps saved practice in this browser tab. Export a backup before closing it.':'Use the save status above to check the current destination.'}</p>`;
  }
  notePath(key) { const [,type,id,number]=key.split(':'); return type==='lesson'?`/lessons/${id}`:type==='explorer'?`/explorer/${id}`:type==='response'?`/response/${id}/${number}`:type==='model'?`/explorer/${id}/${number}`:null; }
  help() {
    const repairs=[
      ['I have a topic, but no idea','Ask a question about a tension, change, or relationship within the topic. Try answering it with two details that could test your thinking.','purpose','Find a focus'],
      ['My analysis only retells the text','Identify a particular choice in your detail. Explain the contrast, effect, or implication it creates, then connect that effect to your point.','beyond-summary','Move beyond summary'],
      ['My paragraph feels short or repetitive','Name its job. Look for missing reasoning rather than adding another example automatically. Remove sentences that repeat the same work.','paragraph','Develop a paragraph'],
      ['I do not know what evidence to choose','Start with your point. Select a detail that a reader needs to consider it, and explain why that detail matters. Verify wording before quoting.','evidence','Choose evidence'],
      ['My personal connection feels random','Explain what the connection helps you understand about an idea in the text. A useful contrast can work as well as a similarity.','personal-connection','Make a meaningful connection'],
      ['My sections do not connect','Give each section a distinct role. Choose an order that changes what the reader understands and write a transition naming that relationship.','organization','Organize the thinking'],
      ['I cannot start the introduction','Try a precise contrast, a relevant moment, or a direct working insight. Treat it as provisional, then revisit it after development.','opening','Write an opening'],
      ['I have feedback but no next move','Locate the concern, name the missing connection, and choose a change you can evaluate. Ask a specific clarification question if needed.','feedback','Use feedback'],
      ['I am revising everything at once','Choose one lens. Resolve focus and development before polishing sentences. Record what your change helps a reader understand.','revision','Revise in passes']
    ];
    return `${this.header('Help with my writing','Choose the difficulty you recognize. Try the next move, then use the full lesson for a model and practice.')}<div class="writing-repairs">${repairs.map(([title,advice,id,label])=>`<details class="writing-repair"><summary>${E(title)}</summary><p>${E(advice)}</p><a href="#/lessons/${id}">${E(label)} →</a></details>`).join('')}</div><section class="teaching-scope"><h2>A way to get started</h2><p>Write what you notice, what you think it suggests, and what you still need to understand. You can learn one move without planning the whole paper.</p>${link('/response/analytical/0','Try guided practice')}</section>`;
  }
  render(path) {
    const [,section,id,extra]=path.split('/');
    if(section==='lessons')return id?this.lesson(id):this.lessonList();
    if(section==='library')return id?this.lesson(legacyGuideRoutes[id]||id):this.lessonList();
    if(section==='explorer')return this.explorer(id,extra);
    if(section==='response')return this.response(id,extra);
    if(section==='study-notes')return this.savedNotes();
    if(section==='writing-help')return this.help();
    return this.home();
  }
  context(path) {
    const [,section,id,extra]=path.split('/');
    if(section==='lessons'&&id){const lesson=lessonContent.lessons.find(item=>item.id===id);if(lesson)return `<section class="teaching-context"><h2>In this lesson</h2>${[['learn','Understand the move'],['model','Study the model'],['check-thinking','Check your thinking'],['try-it','Try it yourself']].map(([target,label])=>`<button data-study-scroll="${target}">${E(label)}</button>`).join('')}<h3>Your focus</h3><p>${E(lesson.aim)}</p><h3>Bring your own work</h3><p>You can use any suitable text or task. The models show a move; they do not supply your answer.</p></section>`;}
    if(section==='explorer')return `<section class="teaching-context"><h2>From detail to meaning</h2><ol><li>Notice a precise choice.</li><li>Explain its effect.</li><li>Connect it to an idea.</li></ol><h3>Need a fuller lesson?</h3><a href="#/lessons/beyond-summary">Move beyond summary →</a><h3>Your own source</h3><p>Apply the same questions to any text, film, or image. Verify wording before quoting.</p></section>`;
    if(section==='response')return `<section class="teaching-context"><h2>Keep the thinking yours</h2><p>Study the original models, then practise using your own idea and details.</p><h3>Useful teaching</h3><a href="#/lessons/paragraph">Develop a paragraph →</a><a href="#/lessons/organization">Choose an order →</a><a href="#/lessons/revision">Review a purposeful change →</a><h3>Your assignment</h3><p>The actual task determines sources, permitted forms, and citation requirements.</p></section>`;
    return `<section class="teaching-context"><h2>How to use the studio</h2><ol><li>Choose a skill you need.</li><li>Study the model and its reasoning.</li><li>Try a short practice.</li><li>Apply the move to your own work.</li></ol><h3>No fixed assignment</h3><p>Return whenever you need an explanation, a model, or a next step.</p><a href="#/study-notes">Open saved practice →</a><h3>Original teaching examples</h3><p>Practice passages are created for this tool. They are not quotations from published works.</p></section>`;
  }
  filterLessons() { let count=0;this.main.querySelectorAll('[data-lesson-search]').forEach(item=>{item.hidden=!(item.dataset.lessonSearch.includes(this.search.toLowerCase())&&(this.category==='all'||item.dataset.lessonCategory===this.category));if(!item.hidden)count++;});const output=this.main.querySelector('[data-lesson-results]');if(output)output.textContent=`${count} lesson${count===1?'':'s'}`; }
  filterTerms() { this.main.querySelectorAll('[data-term-search]').forEach(item=>{item.hidden=!item.dataset.termSearch.includes(this.termSearch.toLowerCase());}); }
  afterRender() { this.filterLessons();this.filterTerms(); }
  async action(name) {
    if(name.startsWith('check:')){const[,id,index]=name.split(':');this.answers.set(id,Number(index));this.repaint();this.main.querySelector(`[data-study-action="${CSS.escape(name)}"]`)?.focus({preventScroll:true});return;}
    if(name.startsWith('save:')){const key=name.slice(5),target=this.main.querySelector(`[data-study-action="save:${CSS.escape(key)}"]`);const body=this.value(key);if(!body.trim())throw Error('Try a response before saving it.');await this.saveResponse(key,target?.dataset.studyTitle||'My practice',body);this.saved.add(key);this.repaint();this.announce('Practice recorded. Check the save status for its destination.');return;}
    if(name.startsWith('reviewed:')){await this.markReviewed(name.slice(9));return;}
    if(name.startsWith('keep-model:')){const[,id,textId]=name.split(':');const term=explorerContent.terms.find(item=>item.id===id),example=term.examples.find(item=>item.textId===textId),text=explorerContent.practiceTexts.find(item=>item.id===textId);await this.saveResponse(`learning:model:${id}:${textId}`,`${term.title} — teaching model`,`Original fictional teaching model from “${text.title}”\n\nObservation: ${example.detail}\n\nInterpretation: ${example.analysis}\n\nReasoning: ${example.why}`);this.announce('Labelled teaching model saved to your notes.');return;}
    if(name==='export-notes'){const notes=this.notes();this.download('Critical Essay Practice Notes.txt',notes.map(note=>`${note.title}\n${note.originLabel.startsWith('learning:model:')?'ORIGINAL TEACHING MODEL':'MY PRACTICE'}\n${note.body}`).join('\n\n--------------------\n\n'),'text/plain');return;}
    if(name==='print-notes')window.print();
  }
}
