const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:1360,height:1050}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const key='calm10-2026-draft:career-standard-v1:b:learning:v3',aKey='calm10-2026-draft:career-standard-v1:a:learning:v3',courseKey='calm10-2026-draft:learning:v3';
const saved={schemaVersion:3,responses:{'co1-03':'Synthetic earlier interview answer','guided:fl2-01:part1':'759','completion:co1-03:criterion1':true},taskVersions:{'co1-03':'2026-09-28.astra.1','guided:fl2-01:part1':'2026-09-28.astra.1','completion:co1-03:criterion1':'2026-09-28.astra.1'},responseHistory:{'co1-03':[{version:'earlier',value:'Synthetic older interview answer',prompt:'Earlier retained prompt'}]},completions:{},savedAt:'2026-10-05T00:00:00Z'};
await ctx.addInitScript(({key,aKey,courseKey,saved})=>{if(!localStorage.getItem(key)){localStorage.setItem(key,JSON.stringify(saved));localStorage.setItem(aKey,'A sentinel');localStorage.setItem(courseKey,'Course sentinel');}},{key,aKey,courseKey,saved});
await page.goto('http://127.0.0.1:4195/review/b/index.html?revision=3#co1-03',{waitUntil:'networkidle'});assert.equal(await page.locator('#field-co1-03').inputValue(),saved.responses['co1-03']);
await page.locator('#field-co1-03').fill('Synthetic revised interview answer');await page.waitForTimeout(650);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#field-co1-03').inputValue(),'Synthetic revised interview answer');
assert.equal(await page.evaluate(k=>localStorage.getItem(k),aKey),'A sentinel');assert.equal(await page.evaluate(k=>localStorage.getItem(k),courseKey),'Course sentinel');let state=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.ok(state.responseHistory['co1-03'].some(x=>x.value==='Synthetic older interview answer'));
const report={status:'pass',revision:3,retainedReviewResponseRestored:true,revisedResponseRestored:true,priorHistoryRetained:true,canonicalAndAStorageUntouched:true,screens:[],limits:['Synthetic review storage only','Selected changed-area desktop/mobile views; not exhaustive responsive or full learner E2E','No Studio, SCORM, Brightspace or release certification']};
fs.mkdirSync(path.join(__dirname,'screens'),{recursive:true});
for(const id of ['co1-03','co2-02','fl1-03','fl2-01','fl3-03','fl4-04']){
await page.goto('http://127.0.0.1:4195/review/b/index.html?revision=3#'+id,{waitUntil:'domcontentloaded'});await page.locator('#'+id).waitFor({state:'visible'});
for(const [name,size]of[['desktop',{width:1360,height:1050}],['mobile',{width:390,height:920}]]){await page.setViewportSize(size);await page.locator('#'+id+'-foundations').evaluate(e=>scrollTo({top:e.getBoundingClientRect().top+scrollY-65,behavior:'instant'}));await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow '+id+' '+name);await page.screenshot({path:path.join(__dirname,'screens',id+'-opening-'+name+'.png')});report.screens.push(id+' opening '+name);}
await page.setViewportSize({width:1360,height:1050});
}
await page.goto('http://127.0.0.1:4195/review/b/index.html?revision=3#fl2-01',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('#field-guided-fl2-01-part1').inputValue(),'759');await page.locator('#fl2-01-stage-5').evaluate(e=>scrollTo({top:e.getBoundingClientRect().top+scrollY-65,behavior:'instant'}));assert.ok(await page.locator('[data-canvas-helper-edit-key="fl2-01-course-changed-allowance"]').isVisible());await page.locator('#field-guided-fl2-01-part1 +button').click();assert.match(await page.locator('#field-guided-fl2-01-part1').locator('..').textContent(),/759.*Count every payment/);report.numericSupportFeedbackVisible=true;
const word=page.locator('#fl2-01-foundations button.vocab-term').first();assert.ok(await word.count());await word.focus();await page.keyboard.press('Enter');await page.waitForTimeout(100);assert.ok(await page.locator('dialog.vocab-dialog').isVisible());await page.keyboard.press('Escape');assert.ok(!await page.locator('dialog.vocab-dialog').isVisible());report.vocabularyKeyboardOpenAndClose=true;
const sources=await page.locator('video source').evaluateAll(es=>es.map(e=>e.src));for(const src of [...new Set(sources)].slice(0,2)){const response=await ctx.request.get(src,{headers:{Range:'bytes=0-255'}});assert.equal(response.status(),206);}report.mediaRangeSamplesAccessible=true;
assert.deepEqual(errors,[]);report.pageErrors=[];fs.writeFileSync(path.join(__dirname,'preview-checks.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log('PASS: review restore/history isolation, numeric feedback, vocabulary keyboard, media samples and 12 changed-area views.');
})().catch(e=>{console.error(e);process.exit(1);});
