const fs=require('fs'),path=require('path'),c=require('cheerio');const root=__dirname,parent=path.dirname(root),m=JSON.parse(fs.readFileSync(path.join(root,'MANIFEST.json'))),target=path.join(parent,'index.html');
let html=fs.readFileSync(target,'utf8');if(!fs.existsSync(path.join(root,'career-comparison-before.html')))fs.writeFileSync(path.join(root,'career-comparison-before.html'),html);else html=fs.readFileSync(path.join(root,'career-comparison-before.html'),'utf8');
const escape=x=>x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
let items='<section id="course-wide"><h2>Remaining lessons · complete Version B</h2><p>Each lesson now opens with its purpose, person, learning journey and final work. Existing documents, detailed reasoning, professional media, fields and completion controls remain. The links below let you follow the entire lesson in the course shell.</p></section>';
for(const id of m.newlyRevised){const a=c.load(fs.readFileSync(path.join(root,id+'-before.html'),'utf8')),b=c.load(fs.readFileSync(path.join(root,'manuscripts',id+'.html'),'utf8'));const custom=id==='co1-01'||id==='fl3-04',points=[['Opening',id+'-foundations'],['Worked example',custom?(id==='co1-01'?id+'-example':id+'-worked'):id+'-stage-4'],['Supported practice',custom?id+'-practice':id+'-stage-5'],['Independent task',custom?id+'-apply':id+'-stage-7']];
items+='<section id="'+id+'"><h2>'+id.toUpperCase()+' · '+escape(b('h1').text())+'</h2><p><a href="review/b/index.html?revision=3#'+id+'"><strong>Read complete B</strong></a> · <a href="review/a/index.html#'+id+'">Read A</a> · <a href="course-wide/manuscripts/'+id+'.md">Complete manuscript</a></p><table><thead><tr><th>Review point</th><th>A</th><th>B</th></tr></thead><tbody>'+points.map(([label,anchor])=>'<tr><td>'+label+'</td><td><a href="review/a/index.html#'+anchor+'">Read A here</a></td><td><a href="review/b/index.html?revision=3#'+anchor+'">Read B here</a></td></tr>').join('')+'</tbody></table><details><summary>Compare the opening instructions</summary><div class="review-pair"><blockquote><strong>A</strong><p>'+escape(a('#'+id+'-foundations >p:not(.section-label)').first().text())+'</p></blockquote><blockquote><strong>B</strong><p>'+escape(b('#'+id+'-foundations >p:not(.section-label)').first().text())+'</p></blockquote></div></details></section>';
}
html=html.replace('<title>CALM · Career lessons review</title>','<title>CALM · Whole-course teaching review</title>').replace('<h1>Career planning: the next six lessons</h1>','<h1>CALM: the complete teaching review</h1><p>Revision 3 carries the approved approach through all forty lessons. Start with <a href="review/b/index.html?revision=3#co1-03">the full Version B course</a>, or use the paired links below to compare a particular lesson.</p>').replace('<section><h2>Review decision</h2>',items+'<section><h2>Review decision</h2>').replace('The workplace, financial-literacy and personal-information lessons remain later work.','All forty lessons are available in B: the seven career lessons and the thirty-three remaining proposals. Canonical integration follows your review decision.').replaceAll('CALM six-lesson review','CALM course-wide review');
fs.writeFileSync(target,html);console.log('Updated the existing comparison with 33 complete lesson links.');
