module.exports={
'fl2-01':{
title:'Learning to read what a borrowing offer actually requires',
purpose:'Borrowing supplies money now in exchange for obligations later. In this lesson, you will learn to read the amount received, payment schedule, fees and total borrowing cost. A small payment can be easier each month while costing more across the agreement.',
context:'Alex needs $600 for equipment. Two offers provide that same amount but use different payment periods and setup charges. Alex’s monthly repayment allowance and separate setup money let us examine fit as well as total cost.',
journey:'First, learn the parts of an offer. Read Alex’s summaries, then follow the twelve-month comparison. You will calculate the longer offer and reconsider it when the repayment allowance changes. The application-information card explains why a quotation is not approval.',
product:'The final task introduces Bea’s coat deadline, two financed offers and a confirmed free alternative. Calculate the financed totals and costs above the cash price, then recommend a workable option and name terms still needing review.',
bridge:'We will read the whole obligation before deciding whether borrowing solves the need. The comparison includes the same purchase and any confirmed alternative, not just the smallest monthly figure.',
method:['Multiply each payment by its number of months and add a separately charged fee once. Subtract the amount borrowed to identify borrowing cost. Do not subtract a fee that was already included or assume a setup fee can come from money reserved for repayment.','Then check each due amount against available money. An affordable quoted schedule still leaves missed-payment and early-payment terms to investigate. Eligibility, approval and whether the borrowing is useful are separate questions.'],
worked:['Alex’s A requires twelve payments of $55: $660 in total, $60 above the $600 received. It fits the supplied $60 monthly allowance and requires no setup money.','That supports considering A under the stated conditions; it is not an approval or a complete account of unspecified consequences. Read the worked explanation for both the calculation and the remaining checks.'],
practice:'Calculate B’s twenty-four payments plus its separate $15 fee, then compare the total and monthly fit with A. In the changed case Alex has only $40 per month for each of the first six months, then $60 per month. Explain what that confirmed timing changes; do not borrow the old allowance from the model.',
independent:'Bea has no purchase cash or setup fund today. Read both coat offers and the suitable free coat confirmation before recommending. A preference for a new colour can be acknowledged without treating it as the warmth or fit requirement.',
close:'A borrowing decision should identify a workable payment schedule and explain why accepting that obligation helps the actual need. Next we will calculate interest when a rate and duration are expressed in different units.'
},
'fl2-02':{
title:'Learning to make an interest rate and duration speak the same unit',
purpose:'A percentage does not give a borrowing cost until we know what amount and period it applies to. In this lesson, you will learn simple-interest calculation and explain its assumptions. We will use a stated model, not treat every real loan as if it uses the same rule.',
context:'Mina borrows $600 for three months under an agreement expressly using 12% simple interest per year. The principal stays unchanged until repayment. The rate is annual, so three months must be expressed as part of a year.',
journey:'First, learn principal, decimal rate and time conversion. Read the agreement, then follow the three-month calculation. You will practise changing duration first and rate second, holding the other facts steady so each effect is understandable.',
product:'Imani’s final offer supplies four months, $800 and a 9% annual rate, but leaves one setup fee blank. Calculate interest, repayment before the fee and the largest fee consistent with the total limit; explain the conditional conclusion.',
bridge:'The calculation is useful only when its units and assumptions match the agreement. We will name those before multiplying anything.',
method:['Write the principal in dollars, the annual rate as a decimal and months as months divided by twelve. Three months is 3/12 of a year; using 3 as years would calculate a much longer borrowing period.','Simple interest here means the charge uses the unchanged principal, with no compounding or interim payment. Add the calculated interest to principal for repayment. Any separately stated fee belongs in a further step.'],
worked:['Mina’s calculation is $600 × 0.12 × 3/12 = $18. The $618 repayment contains both the original $600 and that interest; $18 is not the whole debt.','Read the completed explanation for what the numbers mean and why the rule fits this particular agreement. The absence of fees and changing balances is supplied, not inferred from the rate.'],
practice:'Use six months first at 12%, then at 9%. Enter the required interest and repayment fields and explain which input changed each time. Keeping the comparison controlled lets you identify a duration effect separately from a rate effect.',
independent:'Imani’s fee is unknown, so establish the known interest and principal-plus-interest before finding the remaining space under $835. Your conclusion should say what fee would fit, not assert that the actual lender has quoted that amount.',
close:'An interest answer should make its time unit and assumptions visible. Next we will follow a loan whose outstanding principal changes after every payment.'
},
'fl2-03':{
title:'Learning what happens inside a regular loan payment',
purpose:'A monthly payment can cover both interest and repayment of the borrowed amount. In this lesson, you will learn to read those two parts in a repayment schedule. That helps explain why reducing a payment can improve monthly fit while increasing total cost.',
context:'Alex’s $1,000 loan provides a complete twelve-month schedule. We will follow its first two payments before comparing a twenty-four-month version. The course calculator is available through Tools; the supplied written outputs are sufficient if you prefer to read them.',
journey:'First, learn what opening balance, interest, principal repaid and closing balance mean. Then read Alex’s schedule, follow the worked reasoning and predict the effect of a longer repayment period. Practice uses the same loan with only its duration changed.',
product:'Your final comparison uses Ren’s two $1,800 equipment loans. Calculate each borrowing cost and A’s first closing balance, then recommend using Ren’s $160 monthly limit and lower-total-cost preference. A separate setup allowance is already supplied.',
bridge:'We will keep the payment’s two jobs visible in each row. Read the rate convention before using the calculator; loading a supplied case is deliberate and does not replace your retained experiment automatically.',retainPilot:true
},
'fl2-04':{
title:'Learning to direct extra repayments without breaking the budget',
purpose:'A repayment strategy must cover required payments before assigning extra money. In this lesson, you will learn to compare highest-rate-first and smallest-balance-first approaches using the same available amount. We will also test what happens when that amount changes.',
context:'Jo has two current debts and $120 monthly after essentials and emergency saving. The supplied schedules show the results of two strategies under that exact budget. Their totals are evidence for this model, not promises for a changed budget.',
journey:'First, learn minimum and extra payments. Read Jo’s accounts, then follow how the extra amount is directed. Supported practice lowers the allowance to $90 and then asks how to respond when even the minimums cannot be met.',
product:'Dara’s final task asks for first payments to two debts and a response to a borrowing-to-invest proposal. Calculate the investment stress-scenario shortfall, then explain a strategy consistent with Dara’s priority of reducing existing debt cost.',
bridge:'Choosing a target for extra payments comes after identifying how much extra really exists. Neither strategy creates money or removes a minimum obligation.',
method:['Add Jo’s required $25 and $45 payments first. Their $70 total leaves $50 extra from $120. Direct that extra according to the chosen strategy while continuing the other required payment.','Compare the supplied schedules under the same budget and assumptions. If the budget changes, the old payoff dates no longer establish the new result. A proposed investment gain also cannot be treated as money already available for debt repayment.'],
worked:['Highest-rate-first sends Jo’s extra to the 19% account while paying $25 to A. The supplied schedules finish in the same number of months, but differ in total interest.','I explain the cost difference using those schedules rather than pretend a strategy name alone establishes the result. Read the completed comparison for both the allocation and why a person might value a visible smaller-balance milestone.'],
practice:'With $90, calculate the extra remaining after the same $70 minimums and assign the two payments. Explain what the old schedule cannot promise. The $60 question is a different shortfall case: identifying it is necessary before seeking a workable arrangement.',
independent:'Dara’s balances, rates and $100 allowance are new. Allocate the first payments from these records. Separately compare the proposed $648 repayment with the $540 investment stress value; the scenario exposes risk rather than forecasting an actual loss.',
close:'A sustainable strategy links required amounts, available extra and realistic uncertainty. Next we will compare borrowing with a confirmed way to meet the need without that debt.'
},
'fl2-05':{
title:'Learning to ask whether a loan solves the actual deadline',
purpose:'A loan can provide an item sooner, but a confirmed alternative may meet the same need at lower cost. In this lesson, you will learn to compare the deadline, available money and full obligation before treating financing as the only route.',
context:'Nico needs a suitable device for an online course. A financing quotation is available, but an equipment library has also confirmed a free suitable loaner long enough to build the purchase fund. Borrowing an object and borrowing money are different arrangements.',
journey:'First, learn how to test suitability, timing and funding together. Read Nico’s quotation and library confirmation, then follow the saving route. Practice shortens the loaner period so you can identify a gap rather than assume an extension.',
product:'Taylor’s final boots case has a fourteen-day deadline, a confirmed payment on day seven and a financing offer. Calculate financing total, its extra cost and cash available on day seven; explain a recommendation that meets the specification and date.',
bridge:'An alternative helps only if it covers the needed use and lasts long enough. We will use actual confirmations rather than imagine a free replacement or future income.',
method:['Calculate financing as eighteen payments plus the upfront fee. Then trace Nico’s $100 and four confirmed $80 deposits to the date the suitable loaner must be returned. The same purchase price remains valid through that date.','The loaner solves temporary access, not ownership. Its confirmed duration allows the saving route to be tested. No income after the fourth deposit is promised, so do not base a financing obligation on an invented later budget.'],
worked:['Nico’s saving fund reaches the $420 price after the fourth deposit, when the loaner ends. That timing matters as much as the total. The library confirmation bridges the course’s start to the purchase.','The financing costs more and lasts longer than the course. Read the completed comparison for why the confirmed alternative meets the need without that obligation, while still requiring the loaner’s return.'],
practice:'The revised loaner ends after only two deposits. Calculate available cash and the gap at that exact return date. Explain what must be verified before choosing; the previous four-month conclusion cannot simply be carried over.',
independent:'Taylor’s confirmed day-seven money arrives before the required boots date. Compare the suitable cash purchase and full financed cost. The unverified-fit borrowed pair lasts only five days, so it is not a confirmed solution to day fourteen.',
close:'A good recommendation connects a suitable item to the deadline and confirmed funding. Next we will examine how a changing rate can alter a loan’s later payments.'
},
'fl2-06':{
title:'Learning to test a variable-rate offer beyond its starting payment',
purpose:'A lower starting rate does not tell us what a changing-rate agreement will later require. In this lesson, you will learn to compare a fixed quotation with supplied variable-rate scenarios. We will distinguish a possible path from a promised future rate.',
context:'Ari is comparing two $5,000 loans over twenty-four months. The fixed offer keeps its rate; the variable agreement recalculates payments if the rate changes. Ari’s $223 monthly allowance lets us test the later payment as well as total interest.',
journey:'First, learn what stays fixed and what may change. Read the quotations and follow the supplied 5%-then-7% scenario. Practice changes the second-year rate to 10% so you can explain the effect without guessing future market rates.',
product:'Jules’s final comparison supplies two thirty-six-month schedules and a $250 monthly allowance. Calculate the variable offer’s later margin and extra total interest, then explain a recommendation using predictability, cost and scenario limits.',
bridge:'The labels identify matching offers, not quality ratings. We will compare the same principal and duration, then inspect each period’s payment under the stated agreement.',
method:['Ari’s variable offer changes payment at month thirteen while preserving the original finish date. That contractual mechanism matters: a changing rate does not behave identically under every loan.','Compare early and later payments with the allowance, then compare total interest. The 7% second year is supplied as one scenario; it cannot establish that next year’s rate will be 7% or that the variable option always costs less.'],
worked:['Both fixed and supplied 7% scenario payments fit $223, and that scenario has lower total interest. I retain the scenario qualification rather than turn it into a guaranteed saving.','Read the completed comparison for why Ari should examine sensitivity before relying on a small monthly margin. The next practice holds the other inputs steady and makes that uncertainty concrete.'],
practice:'Use the supplied 10% second-year record. Compare the later regular payment with $223 and interest with the fixed offer, then explain the change in your recommendation. Do not replace the first twelve payments with the later amount.',
independent:'Jules’s G and H records use new figures and a different term. Identify H’s later monthly margin and total-interest difference using its matching columns. Explain why the lower initial payment is insufficient to settle Jules’s preference for predictable, lower-cost repayment.',
close:'A useful rate comparison explains the agreement’s response to change and tests a plausible stress case. Next we will distinguish mortgage term, amortization and extra-payment conditions.'
},
'fl2-07':{
title:'Learning what a mortgage payment leaves unfinished',
purpose:'A mortgage’s monthly payment does not tell us when the entire debt ends or what remains at renewal. In this lesson, you will learn to distinguish down payment, term and amortization, then read remaining balance and extra-payment conditions.',
context:'Lee and Noor have a fictional property quotation and a separate allocation for other ownership costs. The five-year term and twenty-five-year amortization describe different periods. We will use supplied outputs rather than require you to derive the mortgage formula.',
journey:'First, learn what each period and amount means. Read the quotation and follow the first sixty payments. Practice shortens amortization while holding the term steady, showing the payment and balance trade-off.',
product:'Morgan’s final task compares two quotations under a $1,200 loan-payment allowance. Calculate P’s monthly margin and each annual lump-sum privilege, then explain the remaining balance and how an unconfirmed $20,000 extra payment affects the comparison.',
bridge:'These are loan-only teaching records. The excluded ownership costs still exist; neither a supplied allowance nor our classroom calculation is a lender’s approval.',
method:['Subtract the down payment from the property price to find mortgage principal. The term describes the current rate-and-agreement period; amortization describes the projected repayment length. Finishing the term need not clear the debt.','Use the supplied sixty-payment record to separate total payments, interest and principal reduction. Then read the extra-payment allowance as a contract condition with a base and reset period, not a general rule for all mortgages.'],
worked:['Lee and Noor start with $120,000 principal. Their first sixty payments include interest and principal reduction, leaving a substantial balance at the end of the five-year term.','The worked explanation connects those outputs instead of calling all $46,066.20 principal repaid. Read the extra-payment condition for why a larger proposed lump sum needs its own charge check.'],
practice:'The twenty-year version keeps principal, rate and term unchanged. Calculate the monthly increase, month-sixty balance reduction and margin under $860. Explain the benefit and tighter cash commitment without treating the five-year term as the full repayment period.',
independent:'Morgan’s quotations supply new principal and allowances. Compare monthly fit and remaining debt alongside the 10% and 15% privileges. The hoped-for year-three payment is unconfirmed; explain its contractual fit without assuming that money will arrive.',
close:'A mortgage comparison follows both current affordability and unfinished obligations. We will next ask what saving goals need their money to do and when it must be available.'
}
};
