module.exports={
'fl4-01':{
title:'Learning to connect an online detail with the protection it needs',
purpose:'Sharing a picture can reveal more than the caption intends. In this lesson, you will learn to identify public clues, distinguish possible misuse from a proven incident and match a control to each exposure. Protecting an account and limiting a post’s audience do different jobs.',
context:'Casey’s fictional profile shows a practice routine and recognizable venue. Separate records describe password reuse, sign-in protection and location permission. No unexpected account activity has been observed, so we are reducing exposure rather than claiming an attack occurred.',
journey:'First, learn how a digital footprint can support an inference. Read Casey’s records and control guide, then follow the audit. Practice changes the post and audience while leaving other settings unchanged, so you can identify what remains to do.',
product:'Morgan’s final art-profile case asks for public clues, a revised bio and photo decision, account/permission controls and a review habit. Preserve the purpose of sharing art while explaining each protection and its limits. No real account needs to be opened.',
bridge:'We will connect a specific detail to a plausible risk before recommending a control. An important-sounding list of settings is less useful than explaining what each one addresses.',
method:['Read the repeated time and recognizable venue together. They can suggest a routine without proving an exact home address, harmful intent or an incident. Name both the inference and its limit.','Then match controls by job. A post edit reduces displayed detail; audience settings limit future viewers; location permission controls app access; separate credentials and MFA protect sign-in. None authenticates an incoming payment request or recalls every old screenshot.'],
worked:['Casey’s original post combines a repeated departure time with a recognizable place. I use those actual clues rather than invent a displayed phone number or address. The first changes reduce routine disclosure while preserving the social purpose.','The account habits need separate attention. Read the completed audit for how public exposure and password reuse receive different controls, with no claim that either change guarantees safety.'],
practice:'The replacement post and approved-contact audience reduce particular clues, but continuous location access and password reuse remain. In the three fields explain what changed, select two remaining controls and write a repeatable review habit. Use the supplied provider guide rather than assume one setting changes everything.',
independent:'Morgan wants to share artwork without publishing a mailing address or recurring attendance schedule. Use the art and ticket account facts to distinguish already-enabled protection from missing controls. Your plan should preserve the sharing purpose and acknowledge old screenshots cannot be guaranteed removed.',
close:'A privacy plan explains each exposure, control and remaining limit. Next we will examine incoming requests, because knowing public details does not prove a sender is trustworthy.'
},
'fl4-02':{
title:'Learning to verify a request without doing what an unverified sender asks',
purpose:'A convincing message can contain a real organization’s name and still ask for a dangerous action. In this lesson, you will learn to examine the request, identify a concerning pattern and verify through an independent route. We will also distinguish an unverified contact from proof that every contact is fraudulent.',
context:'Leah has a bank-looking text and a caller claiming to be CRA. She has not clicked, paid, replied or shared a code. The complete training cards let us examine their instructions without visiting a live message.',
journey:'First, learn request, evidence and verification. Read the A/B contacts and follow a two-contact response. Practice adds a remote-access demand and an independently confirmed CRA document request. The FINLIT activity then helps classify three other supplied patterns.',
product:'The final task introduces Devon’s job message and appointment call. Write one two-contact plan: classify with evidence, specify safe verification and boundaries, and explain what happens after checking. No live contact or transfer is made.',
bridge:'The safest check should not require first giving the unverified sender the access, payment or information in question. We will use known routes already supplied in the case.',
method:['Start with the requested action. A secret “safe account” transfer and sign-in-code request pose a different concern from a document discussion that permits independent checking. Sender names and caller ID do not establish identity in either case.','Choose a separate route, such as a known bank app or independently reached official verification service. Record exactly what that check confirms. Confirmation of a document request does not automatically authenticate the earlier incoming caller.'],
worked:['I decline A’s transfer and code request and independently reach the bank. For B, I end the unverified call and check through the official route before sharing information. This response accommodates the possibility of a genuine request without trusting caller ID.','Read the two-contact plan for how the boundary and verification differ. Fraud-pattern labels help describe the concern; they do not establish who sent a message or replace the check.'],
practice:'A’s installation demand adds a new access risk without making installation a verification step. B’s official result confirms a document request and secure route, but not the original caller. Explain both updates in the three fields, then use the supplied FINLIT-adapted cards to practise request, pattern and separate check.',
independent:'Devon did not apply for the job, and the message requests a deposit and personal-account forwarding. The appointment call follows a real request but remains unverified. Explain a proportionate boundary for each and the known route that can establish the relevant facts.',
close:'Verification describes what is established and what action becomes appropriate afterward. Next we will plan a response when someone has already disclosed information.'
},
'fl4-03':{
title:'Learning to respond to the information that was actually exposed',
purpose:'After information has been entered on a suspicious page, a useful response starts by identifying what was exposed and which services it affects. In this lesson, you will learn to prioritize protective actions, preserve safe evidence and distinguish completed controls from confirmed outcomes.',
context:'Finley entered a music-service password that is also used on the recovery email account. No payment, card or identity-document details were entered. A separate updated phone and known service routes are available for the written response.',
journey:'First, learn exposure, connected accounts and sessions. Read the incident and provider guide, then follow the account response. Practice adds completed password changes but an unfamiliar continuing session, letting you identify the unfinished work.',
product:'René’s final case exposes card details and shows an unapproved transaction, rather than a reused password. Write exposure boundaries, immediate response, privacy-safe evidence and follow-up. All actions remain a plan; no real account or provider is contacted.',
bridge:'We will match protection to the record instead of inventing every possible theft. That makes the priority and the recipient’s role explainable.',
method:['Finley’s email can recover the music account, and both share the exposed password. That connection supports prompt attention to the recovery account as well as the original service. Read the guide’s controls instead of assume changing a password ends every session.','A log should record categories exposed, time, actions and pending checks without passwords or codes. A protective action can be justified before misuse is proved; completing it still does not establish that no information was copied earlier.'],
worked:['I record both the exposure and its boundaries, then use the separate phone and known routes. Securing the email recovery path and music account includes passwords, recovery details, sessions and supported MFA under this case guide.','Read the plan for how each action closes a specific route. There is no known transfer to reverse here. Reporting suspected fraud and securing an account have different jobs, neither with a guaranteed outcome.'],
practice:'Keep the original log and add the 3:40 status. The password changes are completed; the unfamiliar music session and unfinished MFA remain. Write the next two actions and a dated follow-up without reopening the suspicious page or recording credentials.',
independent:'René’s genuine issuer app shows an $84 transaction René did not make or approve. Prioritize the issuer through an independently known route, explain safe evidence and pending investigation, and reject the stranger’s code request. Do not import Finley’s password or an unreported SIN exposure.',
close:'A response plan makes the exposure, action and unresolved result distinct. Next we will examine a recognized purchase where the concern is conflicting price or contract representations.'
},
'fl4-04':{
title:'Learning to compare what a business promised with what it charged',
purpose:'A consumer concern becomes clearer when the advertisement, checkout, terms and correspondence are compared directly. In this lesson, you will learn to identify a discrepancy, request resolution and select an appropriate route without promising a legal outcome or refund.',
context:'Mina has not purchased the tablet. Its advertisement says mandatory store fees are included, while checkout adds two unavoidable store charges. The dated in-course records distinguish these fees from the separately supplied tax line and describe Alberta and federal routes.',
journey:'First, learn to compare the same item and required charges. Read Mina’s records and follow the concern summary. Practice replaces the advertisement and checkout with matching prices so you can identify what is corrected and what remains part of the historical evidence.',
product:'Omar’s final case concerns an accepted subscription with conflicting cancellation representations and a $54 charge. Compare the promise, terms and charge; draft a concern summary; choose recipients; and plan evidence and follow-up. It is not a card-theft case.',
bridge:'We will describe the concern from the documents before choosing a route. A correction, refund and investigation are different possible results, not interchangeable promises.',
method:['Compare the advertised $120 with the required pre-tax $150 for the same tablet. Identify the $25 and $5 store fees separately from government tax. Mina’s record supplies no personal budget limit, so do not invent one to explain the concern.','Use the dated source records to connect the pricing issue with the appropriate review route. Preserve the offer and correspondence, seek resolution with the business and describe what an investigation can and cannot do.'],
worked:['Mina’s concern is that the advertised price cannot be obtained under the stated mandatory store charges. I identify the same model and fixed fees, then request an explanation or correction through the business’s known route.','Read the worked record for the difference between supporting a concern and deciding the legal outcome. A purchase need not already have happened for the supplied Alberta unfair-practice record to be relevant.'],
practice:'The revised advertisement now matches the $150 pre-tax checkout and $157.50 total. Explain that correction without claim it supplies the old $120 price. Mina can decide whether to purchase at the disclosed price; retain the original and revised records for any remaining inquiry.',
independent:'Omar recognizes the subscription but disputes cancellation representations and the later charge. Compare dates and accepted terms with the advertisement and cancellation request. Choose business, issuer and applicable consumer routes by role; do not describe a recognized transaction as one Omar never made merely because its terms are disputed.',
close:'A consumer plan makes the documentary comparison easy to review and keeps the desired remedy separate from a guaranteed result. Next we will coordinate several response routes when an incident affects money and account access.'
},
'fl4-05':{
title:'Learning to coordinate a recovery plan without adding another exposure',
purpose:'An incident can need several responses at once, but every recipient has a different role. In this lesson, you will learn to map confirmed exposure and misuse, prioritize independently reached services and keep completed actions separate from pending recovery.',
context:'Ari approved a deceptive ticket transfer and entered a password used on two connected accounts. An unverified stranger now promises recovery for a fee and verification code. We have an incident log, known provider routes and dated source records to plan a response.',
journey:'First, learn to separate payment review, account protection and reporting. Read Ari’s records and follow the coordinated plan. Practice supplies a bank acknowledgement and completed email controls while leaving the music account unfinished.',
product:'Nico’s final file involves identity information and an observed CRA direct-deposit change, without an entered password or sent payment. Map exposure and unknowns, prioritize responses, prepare a reporting log and set boundaries and follow-up triggers.',
bridge:'A credible-looking reference or knowledge of an amount does not verify a recovery agent. We will keep the person’s next actions inside independently reached official routes.',
method:['Ari’s approved transfer needs bank review, while the exposed and reused password needs service security controls. Explain each role and priority using the actual record. A fraud report cannot replace urgent provider contact or itself secure a session.','Reject the new fee-and-code demand. Keep a privacy-safe record of evidence and completed actions, then note what each provider still needs to establish. Neither a reference number nor a classroom plan guarantees money will be returned.'],
worked:['I begin with the deposited transfer and connected password exposure, naming what was not disclosed. The bank reviews the payment; known email and music services provide account controls; relevant reporting preserves the incident evidence.','Read the complete plan for this division of responsibilities. It avoids inventing a stolen SIN or bank password, and it does not let the recovery stranger’s knowledge replace independent verification.'],
practice:'Bank review is pending, email controls are recorded complete and music remains unsecured. Update those three statuses, name the next priority and explain why the stranger’s use of T-18 supplies no bank referral. The label identifies Ari’s report, not the stranger’s authority.',
independent:'Nico’s observed CRA change needs its own official response, alongside the bank and identity-information concerns. Use the supplied SIN/credit guidance and fraud-reporting routes according to their roles. Record unknown cause and unconfirmed credit misuse; reject the fee and CRA-code demand without promising an identity reset.',
close:'A coordinated plan states who does what, what evidence supports each action and what result is still pending. Across the course, that habit turns a persuasive claim or worrying event into a decision another person can understand and check.'
}
};
