module.exports={
'fl3-01':{
title:'Learning to give each savings dollar a purpose and a date',
purpose:'A savings goal becomes a plan when you know its remaining gap, deadline and contribution. In this lesson, you will learn to share a limited weekly amount between two goals without promising the same money twice.',
context:'Sam wants a winter jacket and a used bicycle. Some money is already assigned to each, and $35 is available weekly after other costs. The jacket date cannot move; the bicycle date can. A separate emergency reserve is not part of either purchase fund.',
journey:'First, learn to subtract existing goal money and count remaining deposits. Read Sam’s board, then follow a plan protecting the jacket deadline. Practice reduces weekly saving to $25 so you can test what must change.',
product:'Lena’s final task compares a fixed activity-fee deadline with a flexible hobby goal. Calculate the weekly fee contribution and eight-week balance, then write a saving instruction that makes the priority and postponement clear.',
bridge:'Already saved and future saving are different resources. We will assign each contribution to a goal and check the balance at the actual deadline.',
method:['Find each goal’s remaining gap by subtracting the money already reserved for it. Divide the jacket gap across the six deposits that arrive before its deadline. That sets the first priority without taking money from the emergency reserve.','Then allocate the remaining weekly amount to the bicycle. After the jacket is funded, its contribution can change jobs. A phased plan records when that redirection happens; it does not count the same deposit for both goals.'],
worked:['Sam needs another $120 for the jacket, so $20 weekly for six weeks meets its deadline. The remaining part of $35 goes to the bicycle in those weeks, followed by the full available amount afterward.','Read the completed plan for the two phases and deadline balances. The prices are fixed exercise assumptions; the board is a plan for deposits still to happen, not proof the money already exists.'],
practice:'Keep the jacket’s $20 contribution with only $25 weekly available. Calculate what reaches the bicycle in each phase and its week-twelve shortfall. Explain a feasible later bicycle date rather than silently use the emergency reserve or miss the jacket deadline.',
independent:'Lena has no opening fee balance and only $18 weekly. Work backward from the $144 deadline before allocating a hobby contribution. Your instruction should explain why the desired $6 hobby saving cannot be added to the same $18 without a change.',
close:'A savings instruction gives each dollar one job and makes the timetable testable. Next we will compare saving with debt repayment and investing when one extra amount must be allocated.'
},
'fl3-02':{
title:'Learning to choose what one extra amount should do next',
purpose:'Extra money can increase accessible saving, reduce debt or buy an investment, but it cannot do all three at once. In this lesson, you will learn to compare those jobs using a person’s stated priorities, deadline and risk.',
context:'Avery has $80 after essentials and required debt payments. The emergency reserve is below its target, a debt charges interest and an investment has uncertain outcomes. The case supplies a priority order so the recommendation has a clear basis.',
journey:'First, learn access, debt reduction and opportunity cost. Read Avery’s alternatives and follow the reserve decision. Practice starts with the reserve already funded so you can reconsider the next dollar’s job under changed facts.',
product:'Jules’s final repair case gives a fixed deadline and three competing uses for $40. Calculate the repair gap and funded total, then explain the decision and what is postponed. No personal investment or bank action is required.',
bridge:'We will ask what problem the money needs to solve before compare possible returns. A hoped-for gain cannot replace confirmed funding for an essential deadline.',
method:['Accessible saving remains available under the supplied account terms. An extra debt payment lowers principal but cannot be withdrawn again under this loan. An investment may gain or lose value. These different jobs matter before a return comparison.','Apply Avery’s stated order to the current balances. Then name the opportunity cost: choosing one benefit means giving up another use of this particular $80 for now. That is a trade-off to explain, not necessarily evidence of a bad decision.'],
worked:['Adding $80 to the $20 reserve reaches Avery’s first $100 target. I do not also subtract $80 from the debt, because that would use the same money twice.','Read the explanation for why the priority and access support this choice even though the debt rate is high. The next scenario changes the reserve status rather than supply a second $80 to the previous answer.'],
practice:'Begin the new version with the reserve already at $100 and one $80 available. Use the supplied priorities to choose its next job, calculate the resulting debt balance and explain the benefit and opportunity cost. Keep uncertain investment outcomes separate from guaranteed repayment money.',
independent:'Jules’s repair needs the remaining $40 within two weeks. Compare the confirmed repair cost with the outing and uncertain investment. Explain the missed alternative honestly, without inventing future income or a guaranteed quick gain.',
close:'A sound next-dollar decision connects the available amount to priorities and real constraints. Next we will distinguish the account holding money from the product that determines its access and risk.'
},
'fl3-03':{
title:'Learning to distinguish an account’s rules from the investment inside it',
purpose:'An account name alone does not tell us whether its money is accessible or protected from market loss. In this lesson, you will learn to make two connected decisions: which holding suits the goal, and which account arrangement can hold it under the supplied rules.',
context:'Noor needs $500 for a course fee in six months. The case compares a savings deposit, a locked one-year GIC and an equity fund. Noor’s fictional TFSA eligibility and remaining room are explicitly confirmed; they are not limits for every learner.',
journey:'First, learn the difference between the account arrangement and its holding. Read product access and risk before comparing return. I will show a short-deadline decision, then practice changes the purpose to eight years and a tolerance for loss.',
product:'Milan’s final task separates a three-month course fund from a ten-year flexible goal. Choose the short-term holding, state the proposed TFSA contribution and explain both account and holding decisions without exceeding the confirmed room.',
bridge:'We will begin with when the money is needed and what loss would do. A tax arrangement cannot make a locked or volatile product suitable for every goal.',
method:['The product controls its access, charges and risk: a non-redeemable GIC cannot supply this six-month payment under its stated contract, and a fund sale may produce less than the needed amount. A higher advertised return does not solve either problem.','The account arrangement supplies a different set of tax and contribution rules. Use the dated in-course distinctions and Noor’s confirmed room. Calling a holding a TFSA confuses the container with what it contains.'],
worked:['Noor’s course money needs stable value and access in six months. I therefore read the savings deposit’s terms before calculating the illustration. Its suitability comes from the deadline and consequence of loss, not simply its account label.','Read the complete plan for the holding and account decisions separately. The comparison identifies the locked GIC and market uncertainty rather than promise that a registered account prevents either.'],
practice:'The eight-year version uses a separate $500, funded emergency money and tolerance for some loss. Explain why the equity fund could now be considered while its fees, access and uncertainty still need examination. Identify the account arrangement and holding in their separate fields.',
independent:'Milan has two goals and $1,200 confirmed TFSA room for $1,500 total goal money. Keep the essential three-month fund distinct from the flexible long-term amount. State the total contribution and where remaining money is held; do not assume both goals automatically fit inside the room.',
close:'An account-and-holding plan explains both sets of rules and their fit with the goal. Next we will compare the number of dollars with what those dollars can buy.'
},
'fl3-04':{
title:'Learning to compare a savings balance with the price of its goal',
purpose:'A savings balance can rise while buying less of the same goods. In this lesson, you will learn the difference between the nominal number of dollars and purchasing power. We will compare a known goal price with known money before considering modelled growth.',
context:'A fictional basket begins at $100 and later costs $103, while its savings balance grows to $101. These records concern the same items and year. They introduce the price-and-balance comparison; they do not report Canada’s current inflation.',
journey:'First, learn the two measures. Read the basket and balance, then follow their price-adjusted comparison. The professional purchasing-power clip supports that reasoning. Practice isolates a fee in two otherwise identical model runs. The longer compounding investigation remains optional.',
product:'Riley’s required final task uses a confirmed course-material price increase and two suitable purchase choices. Calculate the new price and funding gap, then explain timing, remaining money and a trade-off. Do not use an assumed investment gain to meet the deadline.',
bridge:'Keep a transaction in the account separate from a change in what its balance can buy. We will use this distinction throughout the required lesson and label the optional growth model separately.',retainPilot:true
},
'fl3-05':{
title:'Learning to coordinate two goals over a changing contribution plan',
purpose:'Two savings goals need one coordinated plan when they share the same monthly money. In this lesson, you will learn to fund a nearer priority, redirect contributions and check a later deadline. You will also identify what a calculator or professional can help verify.',
context:'Fei wants a laptop and a training fund. Existing money belongs to each goal, and $70 is available monthly. The training amount is a fictional saving target rather than a real tuition or admission quotation.',
journey:'First, learn a phased contribution plan. Read Fei’s targets, then follow the nearer-goal calculation and redirection. Practice lowers monthly money to $60. The support directory helps you choose a useful next question without contacting anyone.',
product:'Mina’s final goals cannot both retain their original dates under $35 monthly. Calculate the earliest nearer-goal and combined completion months, then explain revised dates and how contributions move between goals.',
bridge:'We will distinguish the desired date from a date the deposits can actually support. A planning tool organizes assumptions; it cannot verify that a real course price or income is correct.',
method:['Subtract Fei’s existing laptop saving from its target, then divide the gap across eight deposits. Allocate only the remaining monthly money to training during that phase. After the laptop is funded, redirect the available contribution.','Check the training balance across both phases rather than divide its opening gap by a contribution that was not available from the start. Then ask which actual cost or condition should be verified, and which support has the role to answer.'],
worked:['Fei’s nearer laptop requires $45 monthly for eight months. I allocate the rest of the $70 to training in those months, then use the full amount afterward. The completed plan makes that changeover visible.','Read the support comparison alongside the plan: a calculator can organize these deposits, while relevant official or qualified sources help examine the underlying assumptions. A title or model output alone cannot establish expertise or admission.'],
practice:'Start the changed version with $60 monthly throughout and the same $45 laptop allocation. Calculate training contributions, its month-eight balance and completion month. Explain the phase instruction and select a question that checks a real uncertainty.',
independent:'Mina’s original dates are desired dates that can move. Use $35 deposits and the nearer-goal priority without adding interest or gifts. Account for any remainder in the month the nearer goal is finished, then explain how the later goal is funded.',
close:'A coordinated plan states amounts, phases, revised dates and the assumptions to check. Next we will update a plan from actual transactions rather than treat its original schedule as money already saved.'
},
'fl3-06':{
title:'Learning to revise a savings plan from what actually happened',
purpose:'An unexpected expense changes a plan’s starting point for the work still ahead. In this lesson, you will learn to reconstruct the actual balance, calculate the remaining gap and revise contributions or timing from that point.',
context:'Ari saved two deposits and then paid a necessary repair from the fund. The expense has happened and is not refundable. A confirmed temporary budget adjustment may still meet the original purchase date.',
journey:'First, learn the difference between planned and completed transactions. Read Ari’s log, then follow the revised gap and remaining deposits. Practice removes the temporary adjustment but permits a later deadline.',
product:'Devon’s final task has different completed deposits, an expense and three remaining months. Calculate the new balance, gap and required contribution, then write a revision consistent with the confirmed budget and fixed date.',
bridge:'We will begin with the money actually remaining. Neither a deposit planned for later nor an expense already paid can be counted as if it were still in the fund.',
method:['Rebuild Ari’s balance from the opening amount, completed deposits and actual withdrawal. Subtract that balance from the target to find the gap. Count only deposits still available before the deadline.','Compare the required contribution with the confirmed budget options. If it fits, write when and how it changes. If not, identify an allowed change in timing rather than invent an investment return or another source of income.'],
worked:['After the repair Ari has $170, leaving $180 toward $350. Four $45 deposits meet the original date under the confirmed temporary adjustment. The earlier deposits are already part of $170; adding them again would overstate the fund.','Read the revision for both arithmetic and the new instruction. It explains the expense, replacement contribution and feasibility rather than blame the unexpected event or silently keep the old schedule.'],
practice:'Use $30 monthly from month three onward, with a movable deadline. Calculate deposits still needed and the calendar completion month. Explain the revised instruction without importing the unavailable $45 adjustment.',
independent:'Devon has three completed deposits and a paid $90 expense. Work from the actual post-expense balance, then test the three remaining contributions against the confirmed temporary $60 amount. State what changes and how the fixed date can be met.',
close:'A revision connects the recorded change to a feasible new instruction. The next lessons apply that same fact-first approach to information exposure, suspicious requests and financial recovery.'
}
};
