import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { readBiology30TopicContract, type TopicUnit } from "./lib/biology30-course/v1/pilot2-contract.js";
function syllables(raw:string){const word=raw.toLowerCase().replace(/[^a-z]/g,"");if(!word)return 0;if(word.length<=3)return 1;return Math.max(1,word.replace(/(?:[^l]e|ed|es)$/i,"").replace(/^y/,"").match(/[aeiouy]{1,2}/g)?.length??1);}
function reading(text:string){const normalized=text.replace(/\s+/g," ").trim(),words=normalized.match(/[A-Za-z][A-Za-z'’-]*/g)??[],sentences=Math.max(1,normalized.match(/[.!?]+(?=\s|$)/g)?.length??1);const grade=.39*(words.length/sentences)+11.8*(words.reduce((n,w)=>n+syllables(w),0)/Math.max(1,words.length))-15.59;return {words:words.length,sentences,averageSentenceWords:Number((words.length/sentences).toFixed(1)),fleschKincaidGrade:Number(grade.toFixed(1))};}
const args=process.argv.slice(2);if(args.some(a=>!["--write","--require-reading"].includes(a)))throw new Error("Usage: audit-biology30-topic-content [--write] [--require-reading]");
const reports=[];
for(const unit of ["B","C","D"] as TopicUnit[]){
 const base=`projects/resources/biology30-production/v1/units/unit-${unit.toLowerCase()}`;const {contract}=await readBiology30TopicContract(process.cwd(),unit);const bytes=await readFile(`${base}/pilot2-content.json`);const content=JSON.parse(bytes.toString("utf8")) as {unit:string;parts:{id:string;title:string;paragraphs:string[]}[]};
 if(content.unit!==unit||JSON.stringify(content.parts.map(p=>p.id))!==JSON.stringify(contract.topics.flatMap(t=>t.parts.map(p=>p.id))))throw new Error(`Core part inventory drift: ${unit}`);
 const byPart=new Map(content.parts.map(p=>[p.id,p]));const partReports=content.parts.map(p=>({partId:p.id,...reading(p.paragraphs.join(" ")),paragraphs:p.paragraphs.length,minParagraphWords:Math.min(...p.paragraphs.map(t=>t.trim().split(/\s+/).length)),maxParagraphWords:Math.max(...p.paragraphs.map(t=>t.trim().split(/\s+/).length))}));
 const topicReports=contract.topics.map(topic=>({topicId:topic.id,...reading(topic.parts.flatMap(p=>byPart.get(p.id)!.paragraphs).join(" "))}));
 const failures=topicReports.filter(t=>t.fleschKincaidGrade>12||t.averageSentenceWords>20);const report={unit,sourceSha256:createHash("sha256").update(bytes).digest("hex"),status:failures.length?"reading-revision-required":"core-reading-estimate-passes-manual-and-complete-content-audit-pending",scope:"Core explanatory paragraphs only; definitions, navigation, guides and controls excluded. Same deterministic estimate as the preserved A method; this is not a comprehension score.",targetRange:[9.5,11.5],ceiling:12,topicReports,partReports,failures:failures.map(t=>t.topicId),pending:["source and first-use review","worked/figure/stop-check/advanced authoring","rendered teaching-before-assessment proof","manual accessible-reading review"]};if(args.includes("--write"))await writeFile(`${base}/pilot2-reading-report.json`,JSON.stringify(report,null,2)+"\n");reports.push(report);
}
console.log(JSON.stringify(reports.map(r=>({unit:r.unit,status:r.status,topics:r.topicReports,highParts:r.partReports.filter(p=>p.fleschKincaidGrade>12).map(p=>({id:p.partId,grade:p.fleschKincaidGrade}))})),null,2));if(args.includes("--require-reading")&&reports.some(r=>r.failures.length))process.exitCode=1;
