from course_authoring import *
L=[]
L.append(lesson('Chromosomes, DNA and chromosome sets','What exactly are we counting in a cell-division diagram?',
'Distinguish chromatin, chromosomes, homologous chromosomes and chromosome sets.',
'DNA carries inherited information. A gamete contributes one chromosome set at fertilization.',[550,551],[3,4,5,6,7,8,9,10,11,12],
[term('chromosome','A DNA molecule with associated proteins, organized as a distinct genetic unit.','A condensed genetic structure becomes visible as a cell prepares to divide.','An unreplicated chromosome has one DNA molecule; a replicated chromosome has two sister chromatids until they separate.','Every chromosome is always X-shaped.'),term('chromatin','DNA and its associated proteins in the nucleus, often less condensed between divisions.','Genetic material appears less individually distinguishable during much of interphase.','Chromatin and condensed chromosomes are different organizations of the same genetic material.','Chromatin is a different hereditary molecule from DNA.'),term('homologous chromosomes','A pair of chromosomes with the same genes at corresponding loci, one typically inherited from each parent.','A maternal and paternal chromosome carry the same gene positions but may carry different alleles.','Homologues are not the same as two copies made by DNA replication.','Homologous chromosomes must carry identical alleles.',['homologues']),term('chromosome set','One of each type of chromosome characteristic of a species.','A human gamete contains one set of 23 chromosomes.','The number of sets, not the X shape, defines ploidy.','A chromosome set means two sister chromatids.')],
[sec('The genetic material can be packaged differently','''DNA associates with proteins to form chromatin. During much of a cell's life, this material is less condensed. As a cell prepares to divide, the DNA becomes more tightly organized into visible chromosomes. Condensation helps the cell move and separate its genetic material without leaving it as a tangled mass.

The chromosome is not created from nothing when it becomes visible. The same genetic material is being packaged differently. Likewise, an uncondensed nucleus has DNA even when you cannot identify individual chromosomes in a light-microscope image.'''),sec('One type from each parent forms a homologous pair','''A typical human body cell has 46 chromosomes arranged in 23 pairs. Most pairs are homologous: the two chromosomes have the same genes at corresponding positions. One typically comes from the mother and one from the father. The alleles, or versions of those genes, need not be identical.

The sex chromosomes require care. In an XX pair the chromosomes are homologous; X and Y share some corresponding regions but are not matching copies over their whole lengths. Autosomes are the chromosomes other than the sex chromosomes.

A karyotype arranges photographed chromosomes by size and other features. It helps examine chromosome number and larger structural differences; it does not directly reveal every DNA sequence or every possible genetic condition.'''),sec('Sets and copies answer different questions','''A haploid cell contains one chromosome set, represented by n. A diploid cell contains two sets, represented by 2n. Human gametes are normally haploid with 23 chromosomes, while the zygote and most body cells are diploid with 46.

Ploidy refers to chromosome sets, not how tightly DNA is packed or whether a chromosome has replicated. A chromosome may be drawn as a single rod or as two joined chromatids. You need the stage and the relationship between the structures before deciding what the picture means.

For any diagram, first ask: how many chromosome types are shown, how many sets are present, and which structures are homologues? Only then consider replication.''')],
worked('Identify two different relationships','A model diploid cell has a long maternal chromosome, a long paternal chromosome, a short maternal chromosome and a short paternal chromosome.',
'Pair chromosomes by corresponding type: the two long chromosomes form one homologous pair, and the two short chromosomes form another.','There are two chromosome types, so one complete set contains two chromosomes.','The cell contains two sets: n = 2 and 2n = 4.','A maternal and paternal homologue can have different alleles even though they carry the same genes at corresponding positions.'),
[g('A model has three chromosome types and two of each type. What is 2n?','6',['3','12'],'Two sets of three types give six chromosomes.','Count both members of each homologous pair.'),g('Two matching-length chromosomes came from different parents. What is their relationship?','Homologous chromosomes',['Sister chromatids made by replication','Two separate species'],'Homologues share gene positions but can have different alleles.','Ask whether the pair came from two parents or one replication event.')],
[q('Which statement best describes homologous chromosomes?','They have corresponding genes but may carry different alleles',['They are always two chromatids joined at one centromere','They must have identical DNA sequences throughout','They exist only in bacterial cells'],'Homology concerns corresponding gene organization, not complete allele identity.'),q('A diploid species has 2n = 10. How many chromosome types are present in one normal gamete?','5',['10','20','2'],'A gamete contains one of each type: n = 5.')],
[w('Compare chromatin and condensed chromosomes without suggesting that a cell gains DNA only when it divides.','Chromatin is DNA associated with proteins. It is often less condensed between divisions and becomes tightly packaged into visible chromosomes during division. The change is packaging of existing genetic material, not DNA appearing for the first time.'),w('Explain why a homologous chromosome pair is not the same as a pair of sister chromatids.','Homologous chromosomes typically originate from the two parents and carry corresponding genes, potentially with different alleles. Sister chromatids are the replicated copies of one chromosome and remain associated until separation.')],
q('A karyotype shows the expected number of chromosomes. Which conclusion goes beyond this evidence?','Every DNA sequence in the person is normal',['The observed chromosome count matches the expected count','Large chromosome differences may be investigated','The image can be organized into chromosome pairs'],'A normal count does not rule out small sequence variants or every genetic condition.'),
('Does an X-shaped drawing automatically show a homologous pair?','No. It often shows one replicated chromosome consisting of two sister chromatids.')))

L.append(lesson('The cell cycle and DNA replication','How does a cell prepare its genetic material before division?',
'Explain G1, S, G2, mitosis and cytokinesis, connecting DNA replication with later inheritance by daughter cells.',
'Ploidy counts chromosome sets. Copying a chromosome does not yet separate the copies into different cells.',[551,555],[13,14,15,16,17,18,19],
[term('cell cycle','The ordered sequence of growth, DNA replication and division in a dividing cell.','A cell grows, copies DNA, prepares for division and then divides.','Not every cell continuously cycles; some leave the active cycle.','Every cell divides at the same constant rate.'),term('interphase','The G1, S and G2 parts of the cycle between divisions.','A cell carries out metabolism and replicates its DNA before mitosis.','Interphase is active preparation and function, not a period with no activity.','Interphase is an inactive resting period.'),term('S phase','The part of interphase during which DNA is replicated.','Each chromosome is copied before its chromatids are separated.','DNA amount increases without an immediate doubling of chromosome number.','S phase immediately doubles the chromosome count.'),term('sister chromatids','The two replicated copies of a chromosome before their separation.','Two copied DNA structures remain associated at the centromere region.','After separation, each chromatid is counted as an individual chromosome.','Sister chromatids are maternal and paternal homologues.')],
[sec('Interphase contains different kinds of work','''During G1, a cell grows and carries out its normal activities. During S phase, it replicates its DNA. During G2, it continues preparing for division, including producing and organizing materials needed for chromosome movement. Together G1, S and G2 make up interphase.

Interphase is not inactivity. Many observed cells are in interphase because it occupies much of the cycle. The proportion of cells seen in each stage can provide evidence about relative time spent there, if the sampled population and observation method are appropriate.'''),sec('Replication prepares two copies for distribution','''In S phase, each chromosome's DNA is copied. The replicated chromosome consists of two sister chromatids associated at the centromere region. This provides copies that can later be distributed to daughter cells.

Keep chromosome number and DNA amount separate. A human body cell in G1 normally has 46 chromosomes. After S phase, before the sister chromatids separate, it still has 46 chromosomes but now has 92 chromatids. The DNA amount has doubled.

The X-shaped drawing is a simplified way of showing a condensed replicated chromosome. DNA is not necessarily condensed into that shape throughout S phase. A drawing can make relationships clearer without being a literal image of every stage.'''),sec('Division has nuclear and cytoplasmic parts','''Mitosis distributes replicated chromosomes into two nuclei. Cytokinesis divides the cytoplasm, producing separate daughter cells. These processes are coordinated but not identical. A cell can divide its nucleus without immediately completing cytoplasmic division.

Cell-cycle checkpoints help regulate whether a cell continues through the cycle. If regulation fails, uncontrolled division can contribute to cancer. “Dividing quickly” and “cancer” are not synonyms: normal growth and repair can also involve rapid cell division.

Follow the sequence as a preparation-and-distribution process. Replication supplies copies before mitosis separates them; cytokinesis then establishes separate cells.''')],
worked('Follow one chromosome through preparation','A G1 cell has an unreplicated chromosome with one DNA molecule.',
'During S phase, the DNA is copied.','The copied structures remain associated as sister chromatids of one chromosome.','DNA amount has doubled for that chromosome, but the chromosome has not yet separated into two counted chromosomes.','During anaphase, separation will change the chromosome count within the still-undivided cell.'),
[g('Which phase copies the DNA?','S phase',['G1 only','Cytokinesis'],'DNA replication is the defining event of S phase.','S stands for synthesis in this context.'),g('A G1 cell has 8 chromosomes. After S phase and before chromatid separation, how many chromosomes does it have?','8',['16','4'],'The copies are still joined as sister chromatids, so chromosome count is unchanged.','Separate DNA amount from chromosome count.')],
[q('What distinguishes mitosis from cytokinesis?','Mitosis divides nuclear genetic material; cytokinesis divides the cytoplasm',['Mitosis makes gametes only; cytokinesis copies DNA','Cytokinesis produces homologous pairs before S phase','Both terms mean DNA replication'],'They describe different coordinated parts of cell division.'),q('Most cells in a sampled tissue are in interphase. Which explanation is reasonable for an actively cycling population?','Cells spend much of the cycle in interphase',['Interphase cells contain no DNA','Every cell in mitosis is immediately destroyed','Interphase is always shorter than every other stage'],'A longer stage tends to be represented by more cells in a snapshot, under suitable sampling assumptions.')],
[w('Trace the cell cycle from G1 through production of daughter cells. Explain why S phase must precede normal mitosis.','In G1 the cell grows and functions. In S phase it copies DNA, producing sister chromatids. G2 prepares for division. Mitosis distributes the copied chromosomes to daughter nuclei, and cytokinesis separates the cytoplasm. Replication provides a chromosome copy for each daughter cell.'),w('Explain why a replicated chromosome is still counted as one chromosome before its sister chromatids separate.','The sister chromatids remain associated at the centromere region and are counted as one replicated chromosome. DNA amount has doubled, but the chromatids have not separated. After separation, each becomes an individual chromosome.')],
q('A model cell completes nuclear division but not cytokinesis. What is most directly possible?','Two nuclei within a shared cytoplasm',['Two cells with no nuclei','Four haploid gametes immediately','Loss of all copied DNA'],'Nuclear and cytoplasmic division are distinct processes.'),
('Why should interphase not be called a time when nothing happens?','Growth, metabolism, DNA replication and preparation for division occur during interphase.'),['G1: cell growth and normal activity','S: DNA replication','G2: preparation for division','Mitosis: nuclear chromosome distribution','Cytokinesis: cytoplasmic division']))

L.append(lesson('Reading chromosome number and DNA amount','Why can two cells have the same chromosome number but different DNA amounts?',
'Count chromosomes and chromatids through replication and separation, stating whether a count applies to a whole cell or one future nucleus.',
'After S phase, sister chromatids remain joined until they separate. Each separated chromatid becomes a chromosome.',[552,557],[15,20,21,22,23,24],
[term('centromere','The chromosome region associated with the attachment and separation of sister chromatids.','Sister chromatids remain linked at a constricted chromosome region before division.','Counting separated centromere units helps distinguish chromosomes from chromatids.','A centromere is a whole homologous pair.'),term('chromosome number','The count of individual chromosomes in a specified cell or nucleus.','A diploid model cell retains four chromosomes after replication until sister chromatids separate.','Always state which cell, nucleus or pole is being counted.','Chromosome number and DNA amount always change together.'),term('DNA amount','The quantity of DNA in the specified cell or nucleus.','The DNA quantity doubles during S phase before the cell divides.','DNA amount can change while chromosome number stays the same.','DNA amount is always equal to the number of chromosome sets.'),term('anaphase','The mitotic stage in which sister chromatids separate and move toward opposite poles.','Copied chromosome units become independent chromosomes as they separate.','The whole-cell chromosome count briefly increases before cytokinesis.','Sister chromatids stay joined throughout mitotic anaphase.')],
[sec('Ask three questions before you count','''First identify the stage. Has DNA replicated, and have sister chromatids separated? Next identify the boundary: are you counting the whole cell, one nucleus, or the chromosomes moving toward one pole? Finally state the quantity: chromosomes, chromatids or DNA amount.

Many errors come from answering a different question than the one asked. “Eight” can be correct for chromatids but incorrect for chromosomes in the same model cell. A count without its quantity and boundary is incomplete.'''),sec('Use a small diploid model','''Consider a cell with 2n = 4. In G1 it contains four unreplicated chromosomes, each with one DNA molecule. After S phase it still contains four chromosomes, now represented by eight chromatids. DNA amount has doubled.

During mitotic anaphase, the sister chromatids separate. Each is now a chromosome. The still-undivided cell therefore briefly contains eight chromosomes, with four moving toward each pole. After mitosis and cytokinesis, each daughter cell contains four chromosomes.

Do not interpret the temporary whole-cell count of eight as proof that the normal daughter cells have doubled their ploidy. The separated groups are being distributed into two cells. The scope of the count explains the apparent change.'''),sec('Keep diagrams consistent with their meaning','''A joined pair of rods or an X often represents one replicated chromosome. Two differently coloured X shapes of corresponding size may represent a replicated homologous pair: two chromosomes and four chromatids. The colour key should identify parental origin, not create a new counting rule.

Use centromere separation rather than counting every visible arm. A replicated chromosome with two chromatids can have four visible arms, but that does not make it four chromosomes.

A useful final check is conservation of the copied genetic material. Normal mitosis distributes one copy of each chromosome type to each daughter cell; it does not selectively discard one whole parental set.''')],
worked('Count at four stages','A diploid cell has 2n = 6. Count chromosomes before replication, after replication, during whole-cell mitotic anaphase and in each daughter cell.',
'G1: 6 chromosomes, each unreplicated.','After S: 6 chromosomes with 12 chromatids; DNA amount is doubled.','Anaphase before cytokinesis: 12 separated chromosomes in the whole cell, with 6 moving to each pole.','Each daughter cell: 6 chromosomes.','The chromosome count per daughter remains 2n = 6; specify boundaries when reporting the temporary anaphase count.'),
[g('For 2n = 10, how many chromatids are present after S phase before separation?','20',['10','5'],'Ten replicated chromosomes each have two chromatids.','Multiply chromosome count by two only for the chromatid count at this stage.'),g('A 2n = 4 model is in mitotic anaphase. How many chromosomes are moving toward one pole?','4',['8','2'],'Each pole receives one full diploid set for the future daughter nucleus.','The question asks about one pole, not the whole cell.')],
[q('A replicated homologous pair contains how many chromosomes and chromatids?','2 chromosomes and 4 chromatids',['4 chromosomes and 2 chromatids','1 chromosome and 4 chromatids','2 chromosomes and 2 chromatids'],'Each of the two homologues has replicated into two chromatids.'),q('A 2n = 8 cell has separated sister chromatids but not completed cytokinesis. What is its whole-cell chromosome count?','16',['8','4','32'],'Separated chromatids each count as chromosomes; eight move to each pole.')],
[w('Describe the chromosome and chromatid counts in a 2n = 12 cell immediately before and immediately after S phase.','Before S phase there are 12 unreplicated chromosomes, each with one DNA molecule. After S phase there are still 12 chromosomes but 24 sister chromatids. DNA amount has doubled without chromosome separation.'),w('Explain why a whole-cell count during anaphase can differ from the count in each daughter cell.','In anaphase sister chromatids have separated into individual chromosomes, so the undivided cell contains both future chromosome groups. Cytokinesis separates these groups into two cells. Each daughter receives the original diploid chromosome number.')],
q('A student counts four visible arms on a single replicated chromosome and reports four chromosomes. What should be corrected?','Arms are not the unit used to count chromosomes',['A chromosome never contains DNA','Every arm must be a gamete','The cell must be haploid because it has four arms'],'The joined sister chromatids comprise one replicated chromosome until separation.'),
('What must accompany any chromosome count?','The stage, the quantity counted and the boundary—whole cell, nucleus or pole.')))

L.append(lesson('Mitosis: chromosome movement through the stages','How does mitosis give two nuclei a matching chromosome complement?',
'Trace prophase, metaphase, anaphase and telophase, connecting visible events with accurate chromosome distribution.',
'DNA replication has already occurred before normal mitosis. Sister chromatids are copies of one chromosome.',[556,559],[20,21,22,23,24,25,26,27,28,29,30,31,32,33],
[term('prophase','The mitotic stage in which chromosomes condense and the division machinery becomes organized.','Condensed replicated chromosomes become visible as spindle structures develop.','DNA replication precedes prophase in the normal cycle.','The cell first copies its DNA during prophase.'),term('metaphase','The mitotic stage in which replicated chromosomes align at the cell equator.','Replicated chromosomes line up individually across the middle of the cell.','Homologous pairs do not normally align as tetrads in mitotic metaphase.','Mitosis always pairs homologues into tetrads at metaphase.'),term('spindle fibre','A microtubule structure involved in chromosome attachment and movement during division.','Fibres from opposite poles attach to the replicated chromosome’s kinetochore regions.','Spindle attachment guides chromosome movement; it does not create new DNA.','Spindle fibres manufacture DNA nucleotides.'),term('telophase','The mitotic stage in which chromosome groups reach the poles and daughter nuclei form.','Nuclear envelopes reform around the two chromosome groups.','Cytokinesis is a separate, coordinated division of the cytoplasm.','Telophase is another name for S phase.')],
[sec('Prepare and align the chromosomes','''During prophase, replicated chromosomes condense and the spindle becomes organized. The nuclear envelope breaks down as division proceeds, allowing spindle microtubules to interact with chromosome attachment regions. Some accounts distinguish part of this interval as prometaphase; the four-stage model groups these events for learning.

During metaphase, replicated chromosomes align individually along the equator of the cell. The two sister chromatids are connected to opposite spindle poles. This arrangement makes it possible to separate one copy toward each future daughter nucleus.'''),sec('Separate copies, not homologous pairs','''During anaphase, sister chromatids separate. Each becomes an individual chromosome and moves toward its assigned pole. The important event is separation of the copies made during S phase.

Mitosis does not normally pair maternal and paternal homologues into tetrads and separate those pairs as meiosis I does. A diploid cell uses mitosis to preserve the chromosome complement in the two daughter nuclei.

If a diagram uses two colours for parental origin, each normal mitotic daughter receives both parental contributions. Do not place all maternal chromosomes in one daughter and all paternal chromosomes in the other.'''),sec('Finish nuclear organization','''During telophase, chromosomes arrive at opposite poles, become less condensed and are enclosed by forming nuclear envelopes. The spindle breaks down. Cytokinesis then completes or overlaps the separation into daughter cells, depending on the cell type.

The sequence is often abbreviated PMAT: prophase, metaphase, anaphase and telophase. The abbreviation is useful only when connected with the events. In a new image, locate condensed chromosomes, their alignment, their separation or the forming nuclei.

Normal mitosis produces daughter nuclei with matching chromosome complements. Mutations or division errors can introduce differences, so “identical” describes the expected genetic distribution, not a guarantee against every possible change.''')],
worked('Identify a stage without relying on the caption','A model cell contains two groups of separated chromosomes moving toward opposite poles, and new nuclear envelopes have not formed.',
'The chromosomes are no longer lined up at the equator, so this is not metaphase.','Sister chromatids have separated and are moving apart.','These observations identify anaphase.','Count each separated chromatid as a chromosome, and state whether counting one pole or the whole cell.'),
[g('Replicated chromosomes line up individually across the equator. Which stage is shown?','Metaphase',['Telophase','G1'],'Individual chromosome alignment at the equator identifies mitotic metaphase.','Look at position before deciding from chromosome shape.'),g('Which structures separate during normal mitotic anaphase?','Sister chromatids',['Intact homologous pairs only','The two strands of every DNA molecule'],'Sister chromatids separate into individual chromosomes.','Compare copied chromosomes with the two strands inside a DNA molecule.')],
[q('Which observation best identifies telophase?','New nuclei form around chromosome groups at opposite poles',['DNA is being replicated in an intact interphase nucleus','Tetrads cross over at the cell equator','Gametes fuse to form a zygote'],'Telophase reorganizes nuclei after chromosome separation.'),q('Why is attachment of sister chromatids to opposite poles important?','It supports delivery of one replicated copy to each daughter nucleus',['It halves chromosome number in every body cell','It ensures one daughter receives only maternal chromosomes','It creates alleles needed by the organism'],'Opposite-pole attachment helps distribute copied chromosomes accurately.')],
[w('Trace chromosome behaviour through the four stages of mitosis.','In prophase chromosomes condense and the spindle becomes organized. In metaphase replicated chromosomes align individually at the equator. In anaphase sister chromatids separate and move to opposite poles. In telophase nuclei reform around the chromosome groups as chromosomes become less condensed.'),w('Contrast what separates in mitosis with the separation of a maternal and paternal homologue.','Mitosis separates sister chromatids, the replicated copies of one chromosome. A maternal and paternal chromosome are homologues, not sister chromatids. Their separation as intact replicated chromosomes occurs in meiosis I, which reduces chromosome sets.')],
q('A mitotic daughter receives only maternal homologues while the other receives only paternal homologues. What is wrong with this normal-mitosis model?','It confuses homologue segregation with distribution of replicated copies',['It correctly shows ordinary mitosis','It proves DNA never replicated','It shows normal formation of a zygote'],'Normal mitosis preserves both chromosome-set contributions in each daughter.'),
('Why is PMAT alone not enough for identifying stages?','You must connect each stage with observable chromosome events.'),['Prophase: chromosomes condense and spindle organizes','Metaphase: replicated chromosomes align individually','Anaphase: sister chromatids separate','Telophase: daughter nuclei form']))

L.append(lesson('Cytokinesis, growth and tissue maintenance','How does division produce separate cells and support a multicellular body?',
'Compare plant and animal cytokinesis, explain growth and repair, and distinguish normal cell-cycle control from uncontrolled division.',
'Mitosis produces two nuclear chromosome groups. Separate cells also require division of the cytoplasm.',[559,562],[29,30,31,34,35,36,37,38],
[term('cytokinesis','Division of the cytoplasm into separate daughter cells.','Two daughter nuclei become enclosed within separate cells.','Nuclear division and cytoplasmic division are related but not identical.','Cytokinesis is the process that duplicates DNA.'),term('cleavage furrow','An inward constriction of an animal cell during cytokinesis.','A dividing animal cell pinches inward at its middle.','A rigid plant cell wall prevents this same pinching mechanism.','A cleavage furrow is a new plant cell wall.'),term('cell plate','A developing partition that contributes to the new wall between dividing plant cells.','Vesicles fuse in the middle of a plant cell to establish a separating partition.','Plant cytokinesis builds a partition rather than simply pinching a rigid wall inward.','A cell plate is the equator where animal chromosomes align.'),term('cell-cycle checkpoint','A control mechanism that helps determine whether a cell proceeds to a later stage.','A cell with damaged DNA pauses instead of immediately entering division.','Checkpoint failure can contribute to uncontrolled division; rapid normal growth is not automatically cancer.','All rapidly dividing cells are cancerous.')],
[sec('Animal and plant cells divide differently','''In an animal cell, a contractile ring helps constrict the cell surface. The resulting cleavage furrow deepens until the cytoplasm is separated. Each daughter cell receives a nucleus and cytoplasmic components.

A plant cell has a rigid cell wall, so it cannot complete division by the same inward pinching process. Vesicles gather and fuse near the cell middle, forming a cell plate. This partition expands and contributes to the new membranes and wall separating the daughter cells.

In both cases, the goal is separation into cells. The physical method differs because of cell structure. The word cytokinesis identifies the cytoplasmic process, not one specific shape of a dividing cell.'''),sec('Division supports growth and replacement','''A multicellular body grows partly by increasing cell number. Mitosis and cytokinesis also replace cells lost through normal wear and support repair after injury. Different tissues vary in how frequently their cells divide and in their ability to regenerate.

Stem cells can retain a capacity for division and produce cells that become specialized. This does not mean every body cell can form every tissue. The developmental potential of a stem cell depends on the type and its context.

A cell culture or tissue sample can help investigate division, but a visible increase in cell number alone does not show that a complete functional organ has been repaired.'''),sec('Control matters as much as the capacity to divide','''Checkpoints and signalling systems help regulate the cell cycle. They can delay division when conditions are unsuitable or DNA is damaged. Changes to genes involved in these controls can allow uncontrolled proliferation and contribute to cancer.

Telomeres are protective regions at chromosome ends. They shorten during many somatic-cell divisions and are involved in limitations on continued proliferation. Telomere length is not a simple personal countdown clock, and not every cell has the same maintenance mechanisms.

Compare outcomes using evidence: organized replacement supports tissue function; uncontrolled division can disrupt it. The rate of division by itself does not provide a complete diagnosis.''')],
worked('Explain the shape of cytokinesis','Two images show an animal cell pinching inward and a plant cell developing a partition through its centre.',
'Both show cytoplasmic separation after or during nuclear division.','The animal cell can constrict its flexible boundary, forming a cleavage furrow.','The plant cell builds a cell plate because a rigid wall prevents the same pinching mechanism.','Different mechanisms accomplish the same broad task of separating daughter cells.'),
[g('Which structure is expected during plant cytokinesis?','Cell plate',['Cleavage furrow as the only mechanism','Acrosome'],'The cell plate contributes to a partition and new wall.','Consider the constraint imposed by the existing wall.'),g('Why is rapid cell division in a root tip not sufficient evidence of cancer?','Rapid division can be part of normal controlled growth',['Plant cells never contain DNA','Cancer means any cell in metaphase'],'Rate alone does not establish loss of regulation.','Separate growth rate from control of growth.')],
[q('Which event is cytokinesis rather than mitosis?','Separation of cytoplasm into daughter cells',['Alignment of chromosomes at the equator','Condensation of chromatin','Separation of sister chromatids'],'Cytokinesis divides cytoplasm; mitosis distributes nuclear chromosomes.'),q('A cell detects DNA damage and delays division. Which function is illustrated?','A cell-cycle checkpoint',['Fertilization','Independent assortment','Formation of a homologous pair'],'A checkpoint can delay progression while conditions are evaluated.')],
[w('Compare animal and plant cytokinesis and explain how their structures affect the mechanism.','Animal cells commonly constrict through a cleavage furrow. Plant cells have a rigid wall, so vesicles establish a cell plate that grows into a partition and new wall. Both separate cytoplasm into daughter cells after nuclear genetic material has been distributed.'),w('Explain why an experiment showing more cells does not by itself prove successful tissue repair.','The cells must also be appropriately specialized, organized and functional, with controlled growth. Increased number alone does not establish integration or restoration of the tissue’s normal role.')],
q('A checkpoint-defective model divides despite severe DNA damage. What is the main concern?','Errors may be propagated while growth control is impaired',['The cell has necessarily become a normal gamete','DNA amount can no longer increase','All daughter cells must be harmless'],'Loss of checkpoint control can allow damaged information and abnormal proliferation to continue.'),
('Does every adult cell divide continuously?','No. Division frequency and capacity differ among cell types.')))

L.append(lesson('Meiosis I and separation of homologous chromosomes','How is the number of chromosome sets reduced?',
'Trace meiosis I and explain why separation of homologues produces haploid chromosome sets while chromatids remain paired.',
'DNA replicates before meiosis begins. Homologous chromosomes are not sister chromatids.',[563,566],[39,40,41,42,43,44,45,46,47,48,49],
[term('meiosis I','The first meiotic division, in which homologous chromosomes separate.','Members of each replicated homologous pair move to opposite poles.','Sister chromatids normally remain together during this division.','Meiosis I separates all sister chromatids first.'),term('synapsis','Pairing of homologous chromosomes during prophase I.','Maternal and paternal homologues align closely along corresponding regions.','This pairing differs from individual chromosome alignment in mitosis.','Synapsis means fusion of sperm and egg.'),term('tetrad','A paired set of two replicated homologous chromosomes containing four chromatids.','Two replicated homologues align as a four-chromatid unit.','A tetrad contains two chromosomes, not four independently counted chromosomes.','A tetrad contains four chromosome sets.'),term('reduction division','A division that reduces chromosome sets from diploid to haploid, as in meiosis I.','One homologue of each pair enters each daughter cell.','Reduced sets can coexist with chromosomes still having two chromatids.','Haploid cells can never contain replicated chromosomes.')],
[sec('Replication happens once before the two divisions','''Meiosis begins after DNA replication. A diploid cell therefore has replicated chromosomes, each with two sister chromatids. It will undergo two divisions, but it does not perform another full round of DNA replication between them.

During prophase I, homologous chromosomes pair through synapsis. Each paired unit contains two replicated homologues and four chromatids, so it is called a tetrad. This organized pairing allows interactions, including crossing over, between corresponding regions of non-sister chromatids.'''),sec('Arrange pairs, then separate homologues','''At metaphase I, homologous pairs align at the equator. Their orientation relative to other pairs can vary. A replicated maternal homologue faces one pole and its paternal partner faces the other, but different pairs can orient independently.

During anaphase I, the homologues separate. The sister chromatids of each chromosome normally remain joined. The event is therefore different from mitotic anaphase, which separates sister chromatids.

After this distribution, each future daughter receives one chromosome of each homologous pair. It has one set rather than two. That is the reduction in ploidy.'''),sec('A haploid cell can still have paired chromatids','''At the end of meiosis I, the cells are haploid because each contains one homologue of each type. Their chromosomes are still replicated. In a 2n = 4 model, each daughter has two chromosomes, each containing two chromatids.

Do not call these daughter cells diploid merely because their chromosomes look like X shapes. The X shape represents replication, not two homologous sets. Meiosis II will separate the sister chromatids.

This distinction is central: meiosis I reduces sets; meiosis II separates the remaining copies. You cannot identify ploidy reliably by the shape of one chromosome alone.''')],
worked('Follow a 2n = 4 model through meiosis I','The starting cell contains one long homologous pair and one short homologous pair, both replicated.',
'At metaphase I, the long homologues pair and the short homologues pair.','At anaphase I, one long homologue and one short homologue move to each pole.','Each resulting cell has one of each chromosome type: n = 2.','Each chromosome still has two sister chromatids, so each cell has two chromosomes and four chromatids.','The reduction concerns homologous sets, not immediate separation of every chromatid.'),
[g('What separates during anaphase I?','Homologous chromosomes',['Sister chromatids in every chromosome','DNA bases from their sugars'],'The homologues separate while sister chromatids normally remain paired.','Identify the paired units at metaphase I.'),g('For a species with 2n = 12, how many chromosomes are in each normal cell after meiosis I?','6',['12','24'],'Each cell receives one of each homologous pair.','Halve the chromosome sets, not the number of chromatid arms.')],
[q('Why is a cell after meiosis I haploid even though its chromosomes remain replicated?','It has one homologue of each chromosome type',['It has no centromeres','It contains only one DNA molecule total','It has already completed fertilization'],'Ploidy counts sets; replication state is a separate property.'),q('What makes a tetrad different from one replicated chromosome?','A tetrad contains two replicated homologues and four chromatids',['A tetrad contains no DNA','A tetrad is always four unreplicated gametes','A tetrad is a single RNA molecule'],'Pairing two replicated homologues brings four chromatids together.')],
[w('Explain how meiosis I reduces chromosome number without separating sister chromatids.','Homologous pairs align and the two homologues move to opposite poles during anaphase I. Each future daughter receives one chromosome of each pair, so it is haploid. The sister chromatids within each chromosome remain together until meiosis II.'),w('For a 2n = 8 species, describe chromosome and chromatid counts after meiosis I.','Each cell has n = 4 chromosomes. Each chromosome is still replicated, so there are 8 chromatids per cell. The cell is haploid because it has one homologue of each type, not because the chromatids have separated.')],
q('A model places all long homologues in one cell and all short homologues in the other after meiosis I. What is the error?','Each daughter should receive one chromosome of each type',['All daughters should receive every homologue','Long chromosomes must always be destroyed','Chromosome size determines the daughter’s species'],'Normal segregation gives each daughter a complete haploid set, not a random assortment missing whole types.'),
('Is meiosis I just mitosis performed on a diploid cell?','No. Homologue pairing and segregation reduce chromosome sets in meiosis I.'),['Replicated homologues pair in prophase I','Tetrads align at metaphase I','Homologues separate at anaphase I','Two haploid cells retain replicated chromosomes']))

L.append(lesson('Meiosis II and production of haploid cells','How does the second division complete the distribution of copied chromosomes?',
'Trace meiosis II and compare chromosome sets, chromatid state and functional products in sperm and egg production.',
'Meiosis I produces haploid cells whose chromosomes are still replicated.',[566,568],[50,51,52,53,54,55,56,57],
[term('meiosis II','The second meiotic division, in which sister chromatids separate.','Each of two haploid cells distributes its remaining copied chromosome units.','No normal S phase occurs between meiosis I and meiosis II.','A full DNA replication occurs between both meiotic divisions.'),term('gametogenesis','The formation and development of gametes.','Meiotic products differentiate into functional reproductive cells.','Meiosis is part of gamete formation, but differentiation and cytoplasm allocation also matter.','Gamete formation involves only copying DNA.'),term('spermatogenesis','The process producing sperm from precursor cells in the testes.','One primary spermatocyte can produce four haploid sperm through division and differentiation.','Mature sperm form through further differentiation after meiosis.','Each primary spermatocyte produces one diploid sperm.'),term('polar body','A small cell produced during unequal meiotic divisions in oogenesis.','Most cytoplasm remains in one developing egg while small cells receive other chromosome sets.','Polar bodies receive chromosomes but relatively little cytoplasm.','Polar bodies receive no chromosomes.')],
[sec('Separate the copies that remain','''After meiosis I, each daughter cell has one chromosome of each type, but each chromosome still has two chromatids. Meiosis II separates these remaining copies. There is no normal full S phase between the divisions.

At metaphase II, chromosomes align individually in each cell. During anaphase II, sister chromatids separate and move toward opposite poles. Telophase II and cytokinesis establish the final haploid products.

The chromosome movements resemble mitosis, but the starting cells have one set of homologues rather than two. Because crossing over may have occurred, the chromatids that separate are not necessarily genetically identical over their whole lengths.'''),sec('Check the final counts','''In a 2n = 4 starting model, each cell after meiosis I has two replicated chromosomes. After meiosis II, each product has two unreplicated chromosomes. It remains haploid, n = 2. Meiosis II does not halve the number of chromosome types again.

The complete meiotic process usually produces four haploid nuclear products from one diploid precursor. Each contains a chromosome of every type needed for a haploid set. Random assortment and recombination create genetic differences among those products.'''),sec('Functional gametes are not always four equal cells','''During spermatogenesis, meiotic products can differentiate into four sperm. Their shape and cell contents are modified for their role in fertilization. A spermatid is not yet a fully mature sperm simply because meiosis has ended.

During oogenesis, cytoplasmic division is unequal. Most cytoplasm is retained in one large cell, while polar bodies receive other chromosome complements and little cytoplasm. This concentrates cellular resources in the future egg. In humans, the secondary oocyte normally completes meiosis II in connection with fertilization.

Distinguish four nuclear products from four equally functional gametes. The patterns of cytoplasm allocation and differentiation affect what the products become.''')],
worked('Do not halve n twice','A species has 2n = 10. Follow one cell from the end of meiosis I to the end of meiosis II.',
'After meiosis I the cell has five chromosomes, each with two chromatids.','No full DNA replication occurs before meiosis II.','Sister chromatids separate in meiosis II.','Each final product has five unreplicated chromosomes: n = 5, not 2.5.','Meiosis I reduced sets; meiosis II separated copies.'),
[g('After meiosis II in a 2n = 6 model, how many chromosomes does each normal product contain?','3',['6','1.5'],'Each product contains one complete haploid set.','Do not halve the haploid chromosome number again.'),g('Why does oogenesis allocate most cytoplasm to one cell?','To retain resources in the future egg',['To remove all chromosomes from the polar bodies','To make the egg diploid before fertilization'],'Unequal cytoplasm allocation preserves resources while chromosome separation proceeds.','Distinguish cytoplasm quantity from chromosome set number.')],
[q('Which statement about meiosis II is correct?','Sister chromatids separate without a preceding full S phase',['Homologues first pair into tetrads after DNA doubles again','The final chromosome number is half of n','Every product must be genetically identical'],'Meiosis II distributes chromatids left after the first division.'),q('Why can “meiosis produces four eggs” be misleading in human oogenesis?','Unequal cytokinesis usually leaves one functional egg and small polar bodies',['No chromosomes ever segregate in oogenesis','Every egg is normally diploid','Polar bodies contain all the cytoplasm'],'Four meiotic nuclear products are not four equal functional ova.')],
[w('Compare what separates in meiosis I and meiosis II.','Meiosis I separates homologous chromosomes and reduces the number of sets to haploid. Meiosis II separates sister chromatids. No full DNA replication occurs between the divisions, and the final products retain one complete chromosome set.'),w('Explain why sperm and egg production can have different functional outcomes even though both use meiosis.','Both reduce chromosome sets, but differentiation and cytokinesis differ. Spermatogenesis can produce four functional sperm from one primary spermatocyte. Oogenesis allocates most cytoplasm to one egg-lineage cell and produces small polar bodies, concentrating resources in the future egg.')],
q('A model incorrectly inserts an S phase between meiosis I and II. What needs correction?','The second division normally distributes existing chromatids without another full replication',['Meiosis II normally creates a diploid zygote','Meiosis I should be removed entirely','All DNA should be destroyed after meiosis I'],'The normal sequence is one replication followed by two divisions.'),
('Are separated chromatids still counted as parts of one chromosome?','No. Once separated, each is an individual chromosome.'),['Haploid cells retain replicated chromosomes after meiosis I','Chromosomes align individually in metaphase II','Sister chromatids separate in anaphase II','Haploid products contain unreplicated chromosomes']))

L.append(lesson('Crossing over and independent assortment','How can meiosis create different genetic combinations?',
'Explain crossing over, independent assortment and random fertilization, keeping chromosome sets complete.',
'Homologues can carry different alleles. Their orientation at metaphase I affects which combinations enter gametes.',[564,569],[43,44,45,46,47,48],
[term('crossing over','Exchange of corresponding DNA segments between non-sister chromatids of homologous chromosomes during prophase I.','A chromatid contains segments derived from both parental homologues.','Crossing over rearranges existing alleles rather than creating every new allele.','Crossing over happens only between identical sister chromatids.'),term('independent assortment','Independent orientation and segregation of different homologous chromosome pairs during meiosis I.','The maternal member of one pair can segregate with either parental member of another pair.','Genes close together on one chromosome do not necessarily assort independently.','Independent assortment requires every gene on the same chromosome to separate.'),term('recombination','Formation of new combinations of existing genetic variants.','A gamete carries an allele combination different from the parental chromosome arrangement.','A new allele combination is not necessarily a new DNA mutation.','Every recombinant combination is a mutation.'),term('random fertilization','The chance combination of gametes contributing to a zygote.','One of many possible sperm chromosome combinations joins one of many possible egg combinations.','It adds variation beyond the combinations produced by one meiosis.','Random fertilization makes every sibling genetically identical.')],
[sec('Crossing over changes combinations within chromosomes','''During prophase I, homologous chromosomes pair closely. Corresponding segments can be exchanged between non-sister chromatids. Because the homologues may carry different alleles, the exchange can produce chromatids with new combinations of parental variants.

The exchange normally occurs between corresponding regions. It should not be drawn as random loss of large unmatched chromosome pieces. A schematic can use two colours to track parental origin, but each resulting chromosome still needs the appropriate set of gene regions.

Crossing over reshuffles existing information. Mutation is a change in DNA sequence that can produce a new allele; these mechanisms are related to variation but are not the same event.'''),sec('Different chromosome pairs orient independently','''At metaphase I, one pair's orientation does not determine another pair's orientation. A gamete can therefore receive a mixture of maternal and paternal homologues. It does not normally receive an exclusively maternal set or exclusively paternal set as a rule.

For n independently assorting chromosome pairs, 2 to the power n gives the number of possible chromosome combinations from assortment alone. For a 2n = 4 model, n = 2, so 2² = 4 possible combinations. This counts types of possible combinations, not the number of cells made by one division.

For humans, n = 23, giving 2²³ = 8,388,608 possible combinations before including crossing over. The number illustrates why chromosome-set organization creates extensive variation.'''),sec('Fertilization adds another combination step','''A sperm and egg then combine by fertilization. Each may carry a different allele combination. Independent assortment, crossing over and random fertilization together make genetically different offspring possible.

The “independent” model has limits. Genes close together on one chromosome may travel together unless crossing over separates them. Chapter 17 will connect that linkage to inheritance ratios.

When explaining variation, name the mechanism and what it changes. Do not claim a process creates extra chromosome types when it actually rearranges which versions are inherited together.''')],
worked('Calculate assortment combinations','A species has 2n = 6 and the three homologous pairs assort independently. Ignore crossing over.',
'Find n: three chromosome pairs means n = 3.','Each pair has two possible parental orientations relative to a gamete.','Multiply the independent choices: 2 × 2 × 2 = 2³ = 8.','These are eight possible chromosome combinations across possible meiotic events, not eight products from one meiosis.','Crossing over would add further allele combinations beyond this simplified count.'),
[g('For 2n = 8, how many assortment-only chromosome combinations are possible?','16',['8','256'],'n = 4, so 2⁴ = 16.','Use the number of pairs as the exponent.'),g('Which structures exchange segments in the usual crossing-over model?','Non-sister chromatids of homologues',['Unrelated chromosomes from different species','Sister cells after cytokinesis'],'Corresponding regions of non-sister chromatids can exchange during prophase I.','Identify both the chromosome relationship and the chromatid relationship.')],
[q('A gamete contains a chromosome with both maternal-origin and paternal-origin segments. Which mechanism most directly explains this?','Crossing over',['Cytokinesis alone','DNA condensation alone','The chromosome becoming an organelle'],'Exchange between homologues can create mixed-origin chromatids.'),q('What does 2ⁿ count in the simple assortment model?','Possible chromosome combinations from independent assortment',['The guaranteed number of offspring in a family','The number of mutations in one gene','The number of cells made by one mitosis'],'It is a possibility count based on n independently assorting pairs.')],
[w('Compare crossing over and independent assortment as sources of genetic variation.','Crossing over exchanges corresponding segments between non-sister chromatids, changing combinations within chromosomes. Independent assortment changes which maternal and paternal homologues from different pairs enter a gamete together. Both rearrange inherited variants without necessarily creating new alleles.'),w('A 2n = 12 species has independently assorting pairs. Calculate the assortment-only possibilities and explain the limitation of the result.','There are n = 6 pairs, so 2⁶ = 64 possible chromosome combinations. This count ignores crossing over and does not mean one meiosis produces 64 cells. Random fertilization also adds combinations at the zygote stage.')],
q('Two closely linked genes do not produce equal frequencies of all gamete combinations. Why need this not contradict the chromosome-assortment model?','The genes share a chromosome and may be inherited together',['Meiosis never includes chromosome orientation','All gametes must contain only maternal chromosomes','Linked genes cannot ever recombine'],'Different chromosome pairs assort independently; nearby genes on one chromosome can remain associated.'),
('Does recombination necessarily create a new allele?','No. It often creates a new combination of alleles already present.')))

L.append(lesson('Comparing mitosis and meiosis','How do chromosome movements explain the different outcomes?',
'Compare replication, pairing, divisions, ploidy and genetic similarity in mitosis and meiosis.',
'Mitosis separates sister chromatids; meiosis I separates homologues and meiosis II separates chromatids.',[568,572],[58,59],
[term('somatic cell','A body cell other than a gamete or its germ-line precursor context.','Skin cells contribute to body tissues rather than fertilizing an egg.','Many somatic cells use mitosis, but not all divide continuously.','Somatic cell means only a sperm or egg.'),term('germ line','The lineage of cells that gives rise to gametes.','Precursor cells in reproductive tissue ultimately contribute genetic information to offspring.','Germ-line cells are not the same as every supporting cell in a gonad.','Every cell in a gonad becomes a gamete.'),term('mitosis','Nuclear division that normally preserves chromosome number in daughter nuclei.','A diploid precursor produces two nuclei each retaining two chromosome sets.','Mitosis can also occur in haploid organisms or stages.','Mitosis always turns haploid cells into diploid cells.'),term('meiosis','A two-division process after one DNA replication that reduces chromosome sets and generates haploid products.','A diploid precursor produces haploid nuclear products for a sexual life cycle.','Meiosis is not simply two independent cycles of mitosis with replication before each.','Meiosis includes two complete rounds of DNA replication.')],
[sec('Begin with the purpose of chromosome distribution','''Mitosis preserves the chromosome complement when a cell divides. It supports growth, replacement and asexual reproduction in many eukaryotes. A diploid cell normally makes diploid daughter nuclei; a haploid cell can make haploid daughter nuclei by mitosis.

Meiosis reduces chromosome sets in sexual life cycles. The reduction allows fertilization to restore a diploid set without chromosome number doubling at every generation. A diploid precursor undergoes one replication and two divisions.'''),sec('Compare the mechanism before the outcome','''Before both processes, DNA replication creates sister chromatids. In mitosis, chromosomes align individually and sister chromatids separate in one nuclear division. The result is normally two nuclei with matching chromosome complements.

In meiosis I, homologues pair, may exchange segments and then separate. In meiosis II, the sister chromatids separate without another full replication. The result is usually four haploid nuclear products, with genetic differences arising from assortment and recombination.

The presence of spindle fibres or condensed chromosomes alone does not distinguish the processes. Look for homologous pairing, which units separate and how chromosome sets change.'''),sec('Connect a changed mechanism to a changed outcome','''If a question shows two products, do not automatically choose mitosis; it may show only the end of meiosis I. Likewise, four pictures may show four stages of one process rather than four final cells. Read what each image represents.

To compare fairly, use the same starting chromosome model. For 2n = 4, normal mitosis produces two 2n = 4 nuclei. Complete meiosis produces haploid products with n = 2. Explain how the separation events produce these outcomes.

“Identical” is a useful expected pattern in normal mitosis, but mutations can occur. “Different” in meiosis concerns genetic combinations, not an instruction to remove essential chromosome types.''')],
worked('Identify a process from several clues','A diagram shows one DNA replication, homologous pairing, two successive divisions and products with half the starting chromosome sets.',
'One replication alone fits both mitosis and meiosis, so it is not decisive.','Homologous pairing and a reduction division point toward meiosis I.','A second division separating chromatids completes meiosis.','The haploid final products agree with that mechanism.'),
[g('A haploid plant gametophyte divides by mitosis. What ploidy do its daughter cells normally have?','Haploid',['Diploid','Triploid'],'Mitosis preserves the chromosome-set number of the starting cell.','Do not define mitosis as always diploid.'),g('Two cells retain paired sister chromatids and each has half the original sets. Which endpoint fits?','End of meiosis I',['End of normal diploid mitosis','Fertilization'],'Set reduction with replicated chromosomes identifies the first meiotic division.','Separate set number from chromatid state.')],
[q('Which comparison is correct for a normal diploid starting cell?','Mitosis preserves sets; meiosis reduces sets',['Mitosis always requires two nuclear divisions','Meiosis replicates DNA before both divisions','Mitosis produces only gametes'],'The distinct segregation patterns explain preservation versus reduction.'),q('Which observation is most specific to meiosis I rather than ordinary mitosis?','Homologues align as paired tetrads',['DNA is present','Spindle fibres form','Chromosomes become condensed'],'Tetrad pairing is characteristic of prophase/metaphase I, not normal mitosis.')],
[w('Compare mitosis and meiosis using replication number, nuclear divisions, chromosome pairing and final ploidy.','Both normally follow one DNA replication. Mitosis has one nuclear division without tetrad pairing and preserves starting ploidy. Meiosis has homologous pairing and two divisions; meiosis I separates homologues and meiosis II separates chromatids, producing haploid products from a diploid precursor.'),w('Explain why counting the number of pictures or cells in a diagram is insufficient to identify the process.','Pictures may show stages rather than final products, and two cells can represent either complete mitosis or only meiosis I. Chromosome relationships, separation events and ploidy provide the needed evidence.')],
q('A 2n = 14 precursor produces two nuclei each with 14 chromosomes after one nuclear division. Which normal process fits?','Mitosis',['Complete meiosis','Fertilization','Crossing over without division'],'Preservation of the diploid complement after one division fits mitosis.'),
('Which question is more useful than “Does this picture have X shapes?”','Ask which units are pairing or separating, and how chromosome sets change.')))

L.append(lesson('Nondisjunction and chromosome abnormalities','How do segregation errors change gamete chromosome numbers?',
'Predict products of nondisjunction in meiosis I or II and distinguish aneuploidy from a change in whole chromosome sets.',
'Normal meiosis I separates homologues; normal meiosis II separates sister chromatids.',[569,572],[60,61,62,63,64,65,66],
[term('nondisjunction','Failure of homologous chromosomes or sister chromatids to separate properly during division.','Both members intended for different products move into one product.','The outcome depends on which division and chromosome are affected.','Nondisjunction always produces the same four gametes.'),term('aneuploidy','An abnormal number of individual chromosomes rather than complete chromosome sets.','A cell has one extra copy of chromosome 21 while most other chromosomes retain their usual copy number.','Aneuploidy differs from gaining an entire extra set.','Aneuploidy always means triploidy.'),term('trisomy','Presence of three copies of one chromosome in an otherwise diploid context.','A zygote has three copies of one chromosome type.','Trisomy is 2n + 1, not three complete sets.','Trisomy and triploidy are the same.'),term('monosomy','Presence of only one copy of a chromosome in an otherwise diploid context.','A zygote is missing one chromosome from an expected pair.','Monosomy is 2n − 1, not the loss of every second chromosome.','Monosomy is the same as a normal haploid gamete.')],
[sec('Track the affected chromosome separately','''Nondisjunction occurs when chromosomes that should separate fail to do so. In meiosis I, a homologous pair may move together instead of separating. In meiosis II, sister chromatids may fail to separate in one of the cells.

To solve the problem, track one affected chromosome type through the divisions. Keep all other types behaving normally unless the question says otherwise. Mark which product receives both copies and which receives none.'''),sec('Compare first-division and second-division errors','''If a homologous pair fails to separate in meiosis I and meiosis II otherwise proceeds normally, all four final products have an abnormal number for that chromosome type. Two have an extra chromosome, n + 1, and two are missing one, n − 1.

If meiosis I is normal but sister chromatids fail to separate in one cell during meiosis II, two products can remain normal. The affected cell produces one n + 1 product and one n − 1 product. The other cell produces two normal n products.

These predictions assume one specified error and otherwise normal divisions. Multiple errors can produce other patterns, so do not apply the simplified pattern without checking the question.'''),sec('Fertilization converts a gamete error into a zygote count','''An n + 1 gamete joining a normal n gamete produces a 2n + 1 zygote, a trisomic complement for one chromosome. An n − 1 gamete joining a normal gamete produces 2n − 1, a monosomic complement.

An extra copy of one chromosome differs from an extra complete set. Trisomy 21, for example, concerns chromosome 21, not three copies of every chromosome. Polyploidy refers to additional whole sets.

A karyotype can identify many count abnormalities. The detailed effects depend on the chromosome and biological context; a schematic should not be treated as a complete prediction of a person's abilities or health.''')],
worked('Infer where the error occurred','Four meiotic products have counts n + 1, n − 1, n and n for one chromosome type.',
'Two products are normal, so the simple meiosis-I nondisjunction pattern does not fit.','A normal meiosis I can produce two cells with the correct homologues.','An error in only one of those cells during meiosis II produces one extra and one missing chromosome.','The unaffected cell produces two normal products.','Under the stated single-error model, meiosis II nondisjunction fits.'),
[g('An n + 1 gamete joins a normal n gamete. What is the zygote count?','2n + 1',['3n','2n − 1'],'One extra chromosome is retained in the zygote.','Add the gamete complements algebraically.'),g('Which condition means an extra complete chromosome set?','Triploidy',['Trisomy','Monosomy'],'Triploidy is three sets, whereas trisomy is one extra individual chromosome.','Distinguish sets from a single chromosome type.')],
[q('Under a single meiosis-I nondisjunction model, which four-product pattern is expected?','Two n + 1 and two n − 1',['Four normal n products','Two normal n, one n + 1 and one n − 1','Four diploid 2n products'],'The affected homologues segregate together before the second division, affecting all products.'),q('Which statement correctly distinguishes monosomy from haploidy?','Monosomy loses one chromosome; haploidy has one complete set',['Both mean no chromosomes','Haploidy is always a segregation error','Monosomy means three complete sets'],'A complete haploid set differs from a missing member of a diploid pair.')],
[w('Explain the different four-product outcomes of one nondisjunction error in meiosis I versus one cell in meiosis II.','A meiosis-I failure to separate homologues yields two n + 1 and two n − 1 products after an otherwise normal second division. A meiosis-II error in one cell yields one n + 1, one n − 1 and two normal n products because the other cell divides normally.'),w('A normal gamete fertilizes a gamete missing one chromosome. Describe the zygote and distinguish it from a haploid cell.','Combining n with n − 1 produces 2n − 1. The zygote is monosomic for one chromosome type but otherwise has the diploid complement. It is not a normal haploid cell, which has one complete set.')],
q('A 2n = 6 species produces a gamete with 4 chromosomes through nondisjunction. It joins a normal gamete. How many chromosomes result?','7',['6','9','4'],'Normal n = 3; the abnormal gamete has n + 1 = 4. The zygote has 4 + 3 = 7.'),
('Must a gamete with an abnormal count be missing every chromosome of one parental origin?','No. A single nondisjunction event usually concerns one chromosome type in the simplified model.')))

L.append(lesson('Sexual and asexual reproductive strategies','How do different reproductive strategies combine continuity and variation?',
'Classify reproductive strategies from evidence, distinguish bacterial division from mitosis, and connect reproduction with genetic variation.',
'Mitosis preserves chromosome complements; meiosis and fertilization provide a sexual-cycle pathway.',[573,576],[67,68,69,70,71,72,73,74],
[term('asexual reproduction','Production of offspring without fusion of gametes.','A new hydra develops from a bud on one parent.','Asexual offspring can still acquire mutations.','Asexual offspring can never differ genetically.'),term('sexual reproduction','A reproductive process involving combination of gametic genetic contributions.','Haploid gametes join to restore a diploid stage.','Meiosis and fertilization can occur at different positions in different life cycles.','Every sexual life cycle is identical to the human cycle.'),term('binary fission','Division of a prokaryotic cell into two cells after its genetic material is copied.','A bacterium copies its chromosome and divides.','Bacteria do not use nuclear mitosis because they do not have a membrane-bound nucleus.','Bacterial binary fission is ordinary mitosis with PMAT.'),term('conjugation','Transfer of genetic material between cells through direct contact.','A bacterium transfers a plasmid to another cell.','Transfer can increase genetic variation without directly increasing cell number.','Conjugation is the same as one bacterium splitting into two.')],
[sec('Classify the mechanism, not the species name','''In asexual reproduction, offspring form without fusion of gametes. Budding in hydra and vegetative reproduction in plants are examples. Eukaryotic asexual reproduction often uses mitosis, maintaining the genetic complement of the parent lineage.

Sexual reproduction combines gametic contributions. Meiosis and fertilization create opportunities for new combinations of alleles. Some organisms use both sexual and asexual strategies at different times, so one familiar species name does not always determine the answer.'''),sec('Different strategies have different trade-offs','''Asexual reproduction can establish offspring without finding a mate and can preserve a successful genotype. However, genetically similar descendants may share vulnerabilities when conditions change. Mutation can still create differences, so clones are not permanently immune to variation.

Sexual reproduction can produce more varied allele combinations, potentially increasing the range of responses within offspring. It also involves costs such as gamete production and, in many organisms, finding or interacting with a mate. Neither strategy is universally best in every environment.

Parthenogenesis involves development from an unfertilized egg. Because different organisms use different cellular mechanisms, read the supplied life-cycle information before assigning ploidy or claiming all resulting offspring are identical.'''),sec('Bacteria transfer DNA and divide by different processes','''Bacteria reproduce by binary fission, copying genetic material and dividing the cell. They do not have a membrane-bound nucleus, so this is not nuclear mitosis with the same chromosome-stage sequence used for eukaryotes.

Bacteria can also exchange genetic material. During conjugation, direct contact can transfer DNA such as a plasmid. This changes genetic content but is not itself the production of an additional cell. Division and genetic exchange are different events.

Use the number of cells and the movement of DNA as separate observations. A diagram showing a connection between two cells may show exchange, not two gametes fusing.''')],
worked('Read two bacterial diagrams','Diagram A shows one bacterium copying its chromosome and separating into two cells. Diagram B shows DNA passing between two cells that remain distinct.',
'Diagram A increases cell number through binary fission.','Diagram B changes genetic content through contact-mediated transfer, consistent with conjugation.','Neither requires a eukaryotic nucleus or the PMAT stages of mitosis.','Do not label both events reproduction merely because both involve DNA.'),
[g('A hydra produces an attached bud without gamete fusion. Which category fits?','Asexual reproduction',['Fertilization','Meiosis by itself'],'The new individual arises without gamete fusion.','Look for the mechanism rather than the adult body form.'),g('Two bacteria exchange a plasmid but the cell count remains two. What is described?','Conjugation',['Binary fission','Zygote formation'],'Genetic exchange need not immediately increase cell number.','Track DNA transfer separately from division.')],
[q('Which statement about asexual offspring is accurate?','They may be genetically similar but can acquire mutations',['They always contain no DNA','They must be diploid in every species','They can never be affected differently by the environment'],'Clonal inheritance does not prevent mutation or environmental differences.'),q('Why should binary fission not simply be labelled mitosis?','Prokaryotes divide without the nuclear mitotic machinery of eukaryotic cells',['Bacteria have no hereditary information','Binary fission always joins two gametes','Mitosis cannot increase cell number'],'The cell organization and division mechanism differ.')],
[w('Compare one potential advantage and one limitation of sexual and asexual reproduction.','Asexual reproduction can occur without finding a mate and preserve a successful genotype, but similar offspring may share vulnerabilities. Sexual reproduction creates new allele combinations but involves costs associated with gametes and, often, mating. The value of each depends on conditions.'),w('Explain why conjugation and binary fission should be distinguished.','Conjugation transfers DNA between cells through contact and can change genetic combinations without increasing cell number. Binary fission copies cellular genetic material and divides one bacterium into two cells. One is exchange; the other is cell reproduction.')],
q('An unfamiliar life cycle includes a new individual developing from an unfertilized egg. What can be stated before more details are supplied?','It is parthenogenetic development, but ploidy requires the stated mechanism',['It must always be a diploid clone','It necessarily includes two gametes fusing','It is bacterial conjugation'],'Unfertilized-egg development does not alone specify the ploidy mechanism in every species.'),
('Would the same reproductive strategy always be favoured in every environment?','No. Costs, resources, mates and environmental change alter the trade-offs.')))

L.append(lesson('Life cycles and alternation of generations','How can you follow ploidy through an unfamiliar life cycle?',
'Trace mitosis, meiosis and fertilization through haploid and diploid stages, including sporophytes, spores and gametophytes.',
'Mitosis preserves ploidy. Meiosis reduces chromosome sets; fertilization combines haploid sets.',[576,580],[75,76,77,78,79],
[term('alternation of generations','A plant life cycle with multicellular diploid sporophyte and haploid gametophyte stages.','A diploid plant stage produces spores that grow into a haploid stage.','This is alternation of chromosome-set stages, not merely taking turns between two adult sizes.','Alternation of generations means every plant alternates male and female each year.'),term('sporophyte','The diploid multicellular generation that produces haploid spores by meiosis.','A familiar conifer tree produces spores within reproductive structures.','A sporophyte makes spores by meiosis, not gametes directly in this model.','A sporophyte is the haploid gamete-producing stage.'),term('gametophyte','The haploid multicellular generation that produces gametes by mitosis.','A haploid plant stage produces eggs or sperm without another ploidy reduction.','A haploid stage can produce gametes by mitosis.','All gametes in all organisms must be made directly by meiosis.'),term('spore','A reproductive cell that can develop without fusing with another cell.','A haploid product of plant meiosis grows into a gametophyte.','A spore differs from a gamete, which participates in fusion.','Every spore must fuse with another spore before it can grow.')],
[sec('Use three rules through any diagram','''Mitosis normally preserves ploidy. Meiosis reduces a diploid complement to haploid. Fertilization combines haploid gametic complements to form a diploid zygote. These rules help you interpret an unfamiliar life cycle without memorizing every species illustration.

Look for the arrows where chromosome sets change. A 2n-to-n transition suggests meiosis in the standard model. Fusion of two n cells to make 2n identifies fertilization. Growth from n to n or 2n to 2n commonly involves mitosis.'''),sec('Follow a plant’s two multicellular stages','''A diploid sporophyte produces haploid spores through meiosis. A spore develops by mitosis into a haploid gametophyte. The gametophyte then produces haploid gametes by mitosis. When gametes fuse, the diploid zygote grows by mitosis into a new sporophyte.

The surprising step for learners is gamete production by mitosis in the gametophyte. The parent stage is already haploid, so another reduction division is not needed. The meiotic products in this plant cycle are spores, not the final gametes.

Spores and gametes therefore have different roles. A spore can grow into a multicellular stage without fusion. A gamete contributes to the next diploid stage through fertilization.'''),sec('The most visible stage depends on the organism','''In mosses, the familiar green plant is usually the gametophyte, while the sporophyte remains attached to it. In conifers, the familiar tree is the sporophyte; the gametophytes are much smaller and develop in association with reproductive structures.

Do not label the largest structure diploid merely because it is large. Use the life-cycle arrows and the chromosome information. An unfamiliar organism may also alternate sexual and asexual reproduction without following the same plant pattern.

When answering, state the evidence: “These two haploid cells fuse, so this arrow represents fertilization.” That is stronger than guessing from a familiar-looking shape.''')],
worked('Identify three arrows','A cycle shows a 2n plant producing n spores, spores growing into an n plant, and two n gametes fusing.',
'The 2n-to-n spore-producing step is meiosis.','Growth from an n spore to an n multicellular stage preserves ploidy and uses mitosis.','The fusion of two n gametes produces a 2n zygote through fertilization.','The diploid multicellular stage is the sporophyte and the haploid one the gametophyte.'),
[g('A haploid gametophyte produces haploid gametes. Which division fits?','Mitosis',['Another reduction division to half of n','Fertilization'],'Mitosis preserves the already-haploid set.','Check the ploidy before and after the arrow.'),g('Which stage produces spores by meiosis?','Sporophyte',['Gamete','Zygote before any growth'],'The diploid sporophyte is the spore-producing stage.','Use both the name and the change from 2n to n.')],
[q('Which sequence correctly describes alternation of generations?','Sporophyte → meiosis → spores → gametophyte → gametes → fertilization',['Gametophyte → fertilization → spores → meiosis → adult haploid zygote','Spores → gamete fusion → chromosome-free plant','Sporophyte → mitosis only → no haploid stages'],'The standard plant cycle includes a diploid spore-producing stage and a haploid gamete-producing stage.'),q('Why does the statement “all gametes are made directly by meiosis” fail in a plant gametophyte?','The gametophyte is already haploid and produces gametes by mitosis',['Plants never contain chromosomes','The gametophyte is always diploid','Every plant gamete is actually a bacterium'],'Gamete production occurs at different positions in different life cycles.')],
[w('Trace the chromosome-set changes through alternation of generations.','A diploid sporophyte makes haploid spores by meiosis. Spores grow by mitosis into haploid gametophytes, which make haploid gametes by mitosis. Fertilization joins gametes to make a diploid zygote, which grows by mitosis into the sporophyte.'),w('Explain how to identify meiosis, mitosis and fertilization in an unfamiliar life-cycle diagram.','Use ploidy and fusion evidence. A standard 2n-to-n transition indicates meiosis. Fusion of two n gametes to produce 2n indicates fertilization. Growth or cell production preserving n or 2n generally uses mitosis. Body size alone is insufficient.')],
q('A diagram labels a large plant n and a smaller attached structure 2n. Which claim follows?','The large plant can be the gametophyte despite its size',['The labels must be wrong because larger always means diploid','Both stages must have no meiosis','The smaller stage must be a gamete'],'Dominant visible size does not determine chromosome-set number.'),
('How does a spore differ from a gamete in this model?','A spore can develop without fusion; a gamete joins another gamete at fertilization.'),['Diploid sporophyte','Meiosis produces haploid spores','Spores grow by mitosis into gametophytes','Gametes form by mitosis','Fertilization produces a diploid zygote','Mitosis builds the next sporophyte']))

F=[q('After S phase, a 2n = 10 cell before chromatid separation has:','10 chromosomes and 20 chromatids',['20 chromosomes and 10 chromatids','5 chromosomes and 10 chromatids','10 chromosomes and 10 chromatids'],'Replication doubles DNA amount but not the joined chromosome count.'),q('What separates during meiosis I?','Homologous chromosomes',['All sister chromatids','The sugar-phosphate backbone of each DNA strand','Mature gametes'],'Homologue separation reduces chromosome sets.'),q('Why do normal daughter cells after mitosis retain the starting chromosome complement?','Replicated copies are distributed to opposite daughter nuclei',['Only maternal chromosomes are retained','DNA replicates separately after every chromosome has been destroyed','Homologous sets fuse at the equator'],'Sister-chromatid separation distributes a copy of each chromosome.'),q('For n = 5 independently assorting pairs, how many assortment-only chromosome combinations are possible?','32',['5','10','25'],'2⁵ = 32, before crossing over.'),q('A single nondisjunction error in one meiosis-II cell can yield:','Two normal products, one n + 1 and one n − 1',['Four normal products necessarily','Four n + 1 products','Two diploid zygotes'],'The unaffected meiosis-II cell makes two normal products.'),q('How does a haploid gametophyte produce gametes in the standard alternation-of-generations model?','By mitosis',['By fertilization','By reducing n to half of n again','By forming a diploid nucleus first in every case'],'The haploid set is preserved during gamete production.')]
FW=[w('Use a 2n = 4 model to compare chromosome distribution in mitosis and complete meiosis.','After replication the cell has four chromosomes and eight chromatids. Mitosis separates sister chromatids and produces two cells with four chromosomes each. Meiosis I separates homologues into cells with two replicated chromosomes; meiosis II separates chromatids, producing haploid products with two chromosomes each.'),w('Explain how chromosome-set continuity and genetic variation are both maintained in sexual life cycles.','Meiosis reduces sets to haploid and fertilization restores diploidy, preventing set number from doubling each generation. Crossing over, independent assortment and random fertilization create varied combinations while normal segregation preserves a complete set of chromosome types in gametes.')]
TR=[q('A 2n = 12 model has completed meiosis I. Which description is correct for each daughter?','6 chromosomes, each still with two chromatids',['12 unreplicated chromosomes','3 replicated chromosomes','24 chromosomes'],'The first division halves sets but retains sister chromatids.'),q('A tissue culture shows two nuclei inside one cell. Which incomplete process is most directly suggested?','Cytokinesis',['S phase necessarily','Fertilization necessarily','Homologous pairing necessarily'],'Nuclei can form before the cytoplasm separates.'),q('A life cycle produces n cells that grow independently before making gametes by mitosis. Which identification fits the first n cells?','Spores',['Diploid zygotes','Replicated homologous pairs','Maternal somatic nuclei'],'Spores develop without fusion into a haploid gametophyte in this model.')]
TW=w('Four products have counts n + 1, n + 1, n − 1 and n − 1 for one chromosome type. Infer a possible single error and explain what additional assumptions your answer uses.','Failure of homologues to separate in meiosis I fits this pattern if meiosis II proceeds normally. The conclusion assumes one affected pair and no additional segregation errors or product losses. Counts alone should be interpreted within those stated conditions.')
EX={'title':'Cell division and restoring tissue function','question':'Would making more sensory cells be enough to restore hearing?','sections':[sec('Replacement and function','''Damage to sensory hair cells can impair hearing. A proposed repair approach might try to stimulate cell division or produce replacement cells. Increasing cell number is only one requirement: cells must also have the right structure, location and connections.

Consider a hypothetical culture in which treated cells divide more frequently and acquire hair-cell-like projections. The result supports an increase in cell number and a change in appearance. It does not yet establish sound detection or useful signalling to the nervous system.'''),sec('Evidence beyond appearance','''A stronger claim would require tests of mechanical sensitivity, appropriate neural communication and controlled growth. A cell that divides indefinitely would not automatically be a successful replacement.

The case connects cell-cycle control with specialization. It is a paper analysis, not a recommendation to attempt a treatment or manipulate biological samples.''')],'writing':w('Explain why increased cell number and hair-cell-like appearance are not enough to prove restored hearing. Name two additional kinds of evidence.','Replacement cells need appropriate function and integration, not only a similar appearance. Tests should show responses to mechanical stimulation, communication with neural pathways and controlled division. A culture result alone does not establish hearing restoration in an organism.')}
save(16,'Cellular Reproduction',548,583,L,{'mc':F,'writing':FW},{'mc':TR,'writing':TW},EX,['Read chromosome sets, replication state and DNA amount separately.','Trace mitosis and meiosis through their actual segregation events.','Explain genetic variation and predict consequences of nondisjunction.','Use ploidy to interpret sexual, asexual and plant life cycles.'],
{'question':'Can you explain a cell-division diagram without relying on memorized shapes?','goal':'Connect chromosome relationships, counts and movement with the biological outcome.','prior':'Name the stage and counting boundary before calculating.','pages':[581,583],'anchors':['chromosome','sister chromatids','meiosis','alternation of generations'],
'sections':[sec('One counting method across the chapter','''Identify homologues, sister chromatids and chromosome sets separately. DNA replication increases DNA amount while chromatids remain associated. Chromatid separation changes the number of independently counted chromosomes within the still-undivided cell. Always state whether the count refers to a whole cell, a pole or a daughter nucleus.

The same approach works for a small 2n = 4 model and a human 2n = 46 cell. The model simplifies the number of structures, not the underlying rules.'''),sec('Mechanisms explain outcomes','''Mitosis distributes copied chromosomes and normally preserves ploidy. Meiosis separates homologues and then chromatids, reducing sets while creating new combinations. Nondisjunction changes the count of a chromosome type when segregation fails.

In a life cycle, follow the arrows where sets change. Meiosis and fertilization balance the reduction and restoration of ploidy. Mitosis can occur in haploid or diploid stages; the largest visible body is not automatically diploid.''')],
'worked':worked('Compare three cell snapshots','A 2n = 6 model shows A: six replicated chromosomes; B: three replicated chromosomes per cell; C: three unreplicated chromosomes per product.','A can represent a post-S diploid cell before reduction: six chromosomes and twelve chromatids.','B fits the end of meiosis I: one complete haploid set, still replicated.','C fits the end of meiosis II: one complete haploid set with separated chromosomes.','The change from B to C separates copies, not another halving of the chromosome types.')})
