// Approved presentation adaptation. Reference copy for this one-time edit; canonical HTML owns the lesson.
module.exports = {
'ce1-02': {
read: ['Trace the duty to its document.|Find the Graphic Designer duties that connect to Jordan’s interest.', 'Check the schedule claim.|Compare the profile’s deadline warning with the fictional posting’s Saturday shift.', 'Read the conclusion and its limit.|Find the reason to investigate, the dated evidence and the question still unanswered.'],
help: 'A research note explains what a record supports and what still needs checking. An occupation profile covers a kind of work; one posting describes one opening. Their different scopes matter when you compare them.',
practice: ['Classify the paid-experience statement using the wording in the posting.', 'Name the preparation detail and the document it came from.', 'Explain what this opening allows Jordan to investigate without claiming professional expertise.', 'Ask one question the preparation evidence leaves unanswered.'],
apply: ['Identify a duty, condition and preparation detail, with the Graphic Designer record and date.', 'Identify the same three kinds of evidence, with the Web Designer record and date.', 'Choose a direction to investigate first, explain the uncertainty and ask one next question for each direction.']},
'ce1-03': {
read: ['Find the destination and entry check.|Read why Route A is relevant to Leah’s assistant role and whether the named courses and time fit.', 'Follow the full cost calculation.|Find fees, supplies and all four travel months before comparing the total with $1,400.', 'Find the provisional decision.|Locate the reason to investigate A and the selection/date check that still matters.'],
help: 'A primary route is the option to investigate first. A backup is an alternative that could become workable if its conditions are met. Neither label means that a place or paid job is guaranteed.',
practice: ['Multiply the monthly travel amount by all ten Route B months.', 'Add the fees, supplies and full travel amount from Route B’s notice.', 'Use Leah’s completed courses and Route B’s entry notice to identify the missing preparation.', 'Explain what would need to change for B to fit Leah’s entry, time and budget.'],
apply: ['Add every listed fee, supply and travel cost for Owen’s Route C.', 'Do the same for Route D using its own duration and costs.', 'Compare entry, time and full costs; recommend a primary route, a possible backup, a trade-off and the next check or date.']},
'ce1-04': {
read: ['Identify each measure.|Find what the Alberta employment count and forecast label actually describe.', 'Compare the search limits.|Find the date, travel area and boards covered by Noor’s local log.', 'Find a supported next step.|Read why the example keeps investigating without declaring guaranteed jobs or no future.'],
help: 'A forecast, an employment count and a count of advertisements answer different questions. A search log records how and when a search was done. Its results do not describe every employer or explain why an advertisement disappeared.',
practice: ['Choose the statement supported by the October 1 search log.', 'State what the search found, its date and the search limits.', 'Explain what the two snapshots cannot tell Noor about the wider market or the reasons for change.', 'Name another comparison that could help Noor’s travel-limited plan; you are planning a check, not doing an outside search.'],
apply: ['Explain the measure, group, place, period, retrieval date and limit of the Graphic Designer record.', 'Explain the same details for the Web Designer record.', 'Use both provincial records and the Lakeford log to propose a next step; explain why their different measures cannot be ranked as one number.']},
'ce1-05': {
read: ['Follow the prerequisite order.|Find how Tariq’s core and elective courses build on completed preparation.', 'Check the plan’s capacity.|Track the single elective slots, weekly hours, materials and portfolio deadline.', 'Find the review points.|Locate the primary route, backup and question that remains before application.'],
help: 'A prerequisite must be completed before the next course or entry point. A checkpoint is a planned time to review progress. Meeting preparation conditions makes a plan possible; it does not guarantee admission.',
practice: ['Choose a design sequence supported by the cancellation notice.', 'List all four Grade 11/12 fall and winter elective slots.', 'Check prerequisite order, the portfolio deadline, one slot per term and the weekly limit.', 'Give a review date and one precise question that the records do not settle.'],
apply: ['List the communication core and all four elective slots in a feasible Grade 10–12 route.', 'Explain the goals, material and weekly limits, both deadlines and how your revision addresses the supplied feedback.', 'Give two review checkpoints with focused support questions. Draft questions only; do not send a message.']},
'ce1-06': {
read: ['Separate revenue from money remaining.|Follow five sales, the parts costs and the other listed costs in Kai’s trial.', 'Compare the employment offer.|Find the gross wage calculation and which responsibilities belong to the shop.', 'Check the recommendation’s limits.|Find how Kai’s goals shape the next step without turning missing costs or future demand into known facts.'],
help: 'Revenue is money from sales. Money remaining after the listed costs is incomplete when other costs or payment for the person’s time have not been calculated. Gross wages are before deductions. These amounts should be labelled when comparing routes.',
practice: ['Identify which supplied cost repeats for each job.', 'Calculate revenue for the three paid jobs.', 'Include both the per-job parts cost and the weekly charge.', 'Subtract the listed costs from revenue; keep the unlisted-cost limit.', 'Explain what the reduced customer count changes about the opportunity.', 'Propose a learning step that tests the idea without inventing sales or requiring actual repairs.'],
apply: ['Calculate the four-sale revenue less both types of listed cost.', 'Compare the shop and venture amounts, responsibilities and limits; recommend a next learning step tied to Samir’s goals.', 'Write one or two truthful sentences from the craft-display evidence, without paid-retail claims or private contact details.']},
'ce1-07': {
read: ['Find the assumption that changed.|Compare Maya’s old Tuesday travel plan with the new family commitment.', 'Check the replacement’s full timing.|Follow the supplied Saturday package and the protected rest and buffer blocks.', 'Find the review trigger.|Read when Maya will check whether the new route worked and what could require another change.'],
help: 'A goal is what the person wants to achieve; a route is how they plan to reach it. Changing a route can protect the same goal. A buffer is time deliberately left available for delays, rather than another promised task.',
practice: ['Choose a Thursday revision supported by the new transport and package notice.', 'Name the original assumption that is no longer valid.', 'Give the complete Thursday timing for both parts of the at-home package.', 'Set a review trigger and a specific digital habit that protects focus time.'],
apply: ['Use the old assumption and new records to give Arun’s full replacement schedule.', 'Explain the option, buffer, digital habit and a support question for a later real application.', 'Choose a review before October 20 and say what evidence would trigger another revision.']},
'co1-01': {
read: ['Match the two sides.|Find the welcome-desk duty and the matching action in Rowan’s welcome-evening notes.', 'Follow context, action and result.|Read how those three parts become a short response written as Rowan using “I.”', 'Check the truthful boundary.|Compare the finished response with the unsupported expert claim.'],
help: 'Context tells the employer where the example happened. Action tells what Rowan personally did. Result tells what happened afterward. A school activity can show a relevant skill without becoming paid library experience.',
practice: ['Choose the experience that best supports accurate records, then use the choice feedback.', 'Name the club setting and the list that needed checking.', 'Describe what Rowan checked and did when forms were missing.', 'State the result after the adviser obtained the forms.', 'Combine the notes into one or two sentences as Rowan using “I”; compare with the model and revise.'],
apply: ['Choose one duty from the festival notice that the fundraiser evidence supports.', 'Write one or two sentences as Rowan using the school-fundraiser context, Rowan’s own action and the supplied result.']},
'co1-02': {
read: ['Identify the request and missing permission.|Read the 9:10 reservation request and the access Rowan has not yet been given.', 'Follow the rule-to-action match.|Find how the completed decision row protects records while keeping the visitor informed.', 'Check what happens while waiting.|Locate the permitted next task and compare it with the borrowed-login shortcut.'],
help: 'A boundary is a limit on what the helper is permitted or prepared to do. A useful decision row names the boundary, an immediate action, the supporting rule and the message needed; “ask Morgan” alone does not describe what happens while waiting.',
practice: ['Choose an action for the 9:20 brochure moment using the clear-route and permission rules.', 'Choose an immediate action for the 9:25 spill and approaching visitor.', 'Choose an action for the 9:35 face-up participant list.', 'Write a two- or three-sentence spill message with location, immediate protection and the help needed.'],
apply: ['For the spray, state the use boundary and what Rowan does immediately while waiting.', 'Name the supporting label or brief detail and draft the exact spray-related question or message.', 'For the phone-number request, state the privacy boundary and immediate action.', 'Name the privacy instruction and draft the message. Use two or three sentences in each field.']},
'co1-03': {
read: ['Match the interview question to the record.|Find why Record A answers a question about a changed plan.', 'Trace the answer’s sequence.|Locate the situation, Rowan’s responsibility, personal action and shared result.', 'Check the scope of the claim.|Find what the answer establishes and what it leaves for learning or a follow-up question.'],
help: 'An interview answer is easier to follow when the listener can distinguish the setting, the person’s responsibility, their action and the result. A shared success should not be described as work the person did alone.',
practice: ['Choose an action from Record B relevant to the card mix-up.', 'Set the scene and identify Rowan’s responsibility.', 'Describe Rowan’s own action and the shared result.', 'State a truthful limit or a specific improvement for another occasion.'],
apply: ['Write a four- to six-sentence answer about the new disagreement using the supplied actions, result and a truthful limit.', 'Ask a focused question about the role or pathway.', 'Explain how the question could be investigated without claiming an answer that the records do not supply.']},
'co1-04': {
read: ['Separate history from an improved response.|Find what actually happened in the printer incident and what the model proposes for a future situation.', 'Follow the changed order.|Trace reporting, approval and a workable backup against the activity deadline.', 'Find the reason for the change.|Read why an on-time result does not erase the feedback about delayed reporting.'],
help: 'A decision log records actions in order, with times when timing matters. A proposed improvement describes what to do next time; it should not rewrite the original incident as though the improved action already happened.',
practice: ['Choose a sequence that uses waiting time without skipping location approval or the area check.', 'State Rowan’s first action at 10:20.', 'Draft the 10:25 update and divide the approved tasks between Rowan and Lee.', 'Give feasible notice, area-check and setup times against the supplied deadlines.'],
apply: ['Write the timed room-change log: immediate protection, privacy, the message to Morgan, the sequential approved tasks and an improvement linked to earlier feedback.', 'Enter when the public notice will be posted.', 'Enter when moving the card box will finish; check both times against the available helper and deadline.']},
'co1-05': {
read: ['Separate outcome from process.|Find the ready cards and the fifteen-minute reporting delay in Rowan’s record.', 'Trace feedback into a growth action.|Read how the completed reflection names a communication habit to practise.', 'Find the next test.|Locate the success criterion and the limited conclusion about program-support work.'],
help: 'A growth action states a behaviour to practise. A success criterion states what evidence would show improvement. “Be confident” does not supply either by itself. A written simulation remains a simulation when reflecting on experience.',
practice: ['Choose the claim supported by Morgan’s visitor-directions observation.', 'Describe the observation and a limited strength it supports.', 'Give another explanation task and the evidence you would use to judge it.', 'Choose an arrangement from the supplied cards and include work plus travel hours.'],
apply: ['Use Casey’s observation to write six to eight sentences or equivalent notes: strength, limit, growth action, practice test, criterion and career or school-plan change.', 'Ask one focused training or role question that the supplied record does not answer.']},
'co2-01': {
read: ['Select the relevant rule group.|Find how Ellis’s age, ordinary retail employment and school record select the conditions.', 'Follow the shift timeline.|Trace where supervision, permission and the overnight boundary change.', 'Read the correction request.|Find the specific mismatch and proposed next action without treating permission as an override.'],
help: 'A shift review compares proposed facts with the rule that applies to that age, task and arrangement. Meeting one condition does not cancel another. A limited conclusion explains this supplied offer; it does not claim every employment or safety rule has been checked.'},
'co2-02': {
read: ['Separate observation from guesses.|Find the hazard details in Devin’s record without testing the substance.', 'Follow the safe sequence.|Read how the model pauses, reports and asks for verified information, training and controls.', 'Find the condition for resuming.|Locate what must be confirmed and what follow-up applies if danger remains.'],
help: 'An observation is something the record directly reports. A possible harm explains why it matters without pretending an unknown substance is identified. A control reduces the hazard or exposure; a co-worker’s guess does not verify it.'},
'co2-03': {
read: ['Trace the dated facts.|Find what Owen observed, when it happened and which records support it.', 'Follow the concern to the correct recipient.|Read the specific request and interim action in the response plan.', 'Check the follow-up boundary.|Find what remains pending and why the relevant authority depends on the kind of issue.'],
help: 'A concern record keeps observations, reports and confirmed outcomes separate. Appending a new entry means adding later information without rewriting the earlier event. A safety issue and a wage issue use different external routes.'},
'co2-04': {
read: ['Build the chronology.|Follow Jules’s request, reply and schedule in their recorded order.', 'Connect the concern to evidence.|Find the work-related need, published criteria and recorded effect.', 'Check the review request’s limit.|Read the specific support request without assuming the complete assessment or a guaranteed outcome.'],
help: 'A concern record states the request, response and effect accurately. A support plan identifies an accessible route and relevant records. It can recognize a possible barrier while leaving missing circumstances and a legal outcome unresolved.'},
'fl1-01': {
read: ['Check the time record first.|Follow Mika’s hours and agreed rate to the supported gross amount.', 'Check the stub separately.|Find how listed deductions lead to net pay, then compare the bank payment.', 'Find the precise question.|Read what the note can establish and what payroll still needs to explain.'],
help: 'Gross pay is before deductions; net pay is after the listed deductions. Checking a stub’s internal arithmetic does not supply new deduction figures for corrected hours. Use the current pay period rather than year-to-date totals.',
apply: ['Total the hours in Ellis’s time record.', 'Multiply those hours by the agreed rate for supported gross pay.', 'Check the current stub’s listed gross less its listed deductions.', 'Write four to six sentences explaining the mismatch and gross difference, the conclusion’s limit and a specific payroll question.']},
'fl1-02': {
read: ['Follow the available-money calculation.|Find Ari’s commitments before considering the hoodie.', 'Separate price from influence.|Locate the deadline, social pressure and the function Ari wants.', 'Read the decision’s trade-off.|Find what the choice protects and what Ari gives up without judging the person.'],
help: 'An influence can affect a choice without determining it. A trade-off is what the chosen option gives up. Confirmed extra money changes affordability, but it does not remove a deadline or create an obligation to buy.',
practice: ['Choose the statement supported by the confirmed $50 gift.', 'Include the gift, then subtract the original commitments.', 'Subtract the hoodie cost from that available amount.', 'Write two or three sentences explaining the revised decision, a benefit and a trade-off.'],
apply: ['Choose a supplied feasible way to meet Ren’s bag need by Monday.', 'Subtract commitments and the chosen option’s cost from Ren’s available money.', 'Write four or five sentences explaining feasibility, the function protected and a social or marketing assumption you questioned.']},
'fl1-03': {
read: ['Check balances by date.|Follow Sam’s income and payment dates, not only the monthly total.', 'Locate the timing repair.|Find how the supported payment option changes the tight point.', 'Check the ending requirement.|Read why a workable plan needs both on-time payments and the required ending balance.'],
help: 'A dated balance shows money available after a particular event. An ending surplus does not prove that an earlier payment could be made. A split payment is still an obligation; do not count the same income twice.',
practice: ['Choose a change that preserves required payments in the new repair case.', 'Enter a revised saving transfer within the adjustable amount.', 'Enter revised recreation; together the flexible amounts may total no more than $55.', 'Explain reductions and check the balance after October 10 and at month-end.'],
apply: ['Choose the full-payment or confirmed two-payment boots option.', 'Enter the balance after the November 18 event in your plan.', 'Enter the month-end balance.', 'List balances after every November event, identify the tightest point and explain your allocations and recommendation.']},
'fl1-04': {
read: ['Put both offers on the same basis.|Follow Dani’s full base-period costs and the stated terms.', 'Separate cost from conditions.|Find how ownership and protection affect the comparison.', 'Read a bounded recommendation.|Locate the relevant benefit, risk and term still needing confirmation.'],
help: 'A refundable deposit affects cash needed now but is not a final cost when the case confirms its full return. A repair scenario is a specified comparison, not a prediction. Keep each offer’s own coverage and charges attached to it.',
practice: ['Add A’s confirmed repair cost to A’s base total.', 'Add B’s eligible claim fee to B’s base total.', 'Write two or three sentences explaining what this one event changes and which original terms remain unchanged.'],
apply: ['Include all sixteen rental weeks and the deposit in cash needed at pickup.', 'Calculate rental cost after the confirmed deposit return.', 'Include the used calculator and immediate battery cost.', 'Write five or six sentences recommending an option using Riley’s budget, need, ownership or risk, and a precise term to verify.']},
'fl1-05': {
read: ['Follow the promotional timeline.|Find Marin’s service price before and after the promotion.', 'Keep the device separate.|Track device instalments alongside service costs.', 'Read the full comparison.|Find the relevant contract and exit conditions before judging by the starting price.'],
help: 'Ending service does not necessarily erase an unpaid device balance. Count service only for the stated months, then apply the supplied exit terms. An amount already paid should not be charged a second time in the comparison.',
practice: ['Count A’s nine service months, nine device payments and remaining device balance.', 'Count B’s nine service months under its own terms.', 'Explain the exit difference in two or three sentences without assuming a refund or resale payment.'],
apply: ['Count C’s promotional and later months plus setup for twelve months.', 'Calculate D’s twelve-month cost.', 'Count C’s first six months and setup for the six-month departure.', 'Calculate D’s six-month cost.', 'Write four to six sentences comparing the two periods, first-bill affordability and a fact to verify before Sacha’s possible move.']},
'fl1-06': {
read: ['Sort the money needed at the start.|Follow Tess’s deposit, setup and other move-in amounts.', 'Separate recurring costs.|Find the amounts that repeat and which figure is still unquoted.', 'Read the feasibility limit.|Locate what the known money supports without silently filling a missing cost.'],
help: 'An initial cost is needed to begin; a recurring cost repeats. A refundable deposit has a different purpose from a purchase. Unknown costs stay unknown until a confirmed update supplies them.',
practice: ['Use the new setup price and utility quote in the September 1 starting requirement.', 'Include the confirmed August 30 payment in money available before move-in.', 'Total the supplied recurring monthly amounts; do not repeat the deposit.', 'Explain what the updated figures establish and any remaining limit.'],
apply: ['Add the bike, lock and initial service, excluding storage as the field specifies.', 'Include all four months of storage in the four-month bike total.', 'Calculate four months of bus passes.', 'Write four to six sentences comparing funds remaining from $550, a benefit and an unknown or condition; recognize the repair allowance if choosing the bike.']},
'fl2-01': {
read: ['Count every repayment and charge.|Follow offer A’s payment schedule and setup terms.', 'Separate total paid from borrowing cost.|Find where returned principal is removed to identify cost.', 'Check access and affordability.|Read the conclusion against the monthly allowance and money due today.'],
help: 'Total repayment includes returning the money borrowed. Borrowing cost is the amount paid above that principal, including supplied charges. A smaller monthly payment can still create a larger total commitment.',
practice: ['Count every offer B payment and its setup fee.', 'Subtract the $600 principal from B’s total paid.', 'Compare A and B using total cost and monthly fit.', 'Use the changed repayment allowance in the additional choice; do not reuse the earlier budget.'],
apply: ['State C’s total paid and cost above $240 with units.', 'State D’s total paid and cost above $240 with units.', 'Write four or five sentences comparing monthly fit, cash due today, the benefit and confirmed non-borrowing option, plus terms still needing checking.']},
'fl2-02': {
read: ['Match the rate and duration.|Find why Mina’s three months use three-twelfths of an annual rate.', 'Follow principal, interest and repayment.|Trace the simple-interest calculation before adding interest back to principal.', 'Check the assumptions.|Locate the unchanged principal and absence of fees, interim payments or compounding.'],
help: 'In simple interest, the annual rate needs time expressed in years. Months divided by twelve gives that fraction. Interest is the added cost; repayment includes principal as well. Keep rate and duration changes separate.',
practice: ['Use six months at 12% for Mina’s interest.', 'Add that interest to the unchanged $600 principal.', 'Keep six months and $600, but use the new 9% annual rate.', 'Explain in two or three sentences what changed and stayed constant; use the duration and rate checks beside the fields.'],
apply: ['Calculate interest using $800, 9% annually and four-twelfths of a year.', 'Add the interest to principal before the unknown fee.', 'Find how much of the $835 limit remains for that one fee.', 'Show the formula and time unit, and explain why the exact total cannot yet be known.']},
'fl2-03': {
read: ['Follow the first payment split.|Find how interest is paid before the rest reduces Alex’s principal.', 'Carry the closing balance forward.|Follow the smaller opening balance into month two and its interest calculation.', 'Check the unsupported shortcut.|Read why subtracting the whole payment from principal gives the wrong closing balance.'],
help: 'Principal is the amount still borrowed. A payment contains interest and principal repayment. The closing balance becomes the next opening balance. The written schedules remain usable without opening a calculator.',
practice: ['Predict how extending Alex’s period to 24 months affects payment and interest.', 'Subtract first-month interest from the 24-month payment.', 'Subtract the principal part from the opening balance.', 'Compare total interest in the supplied 24- and 12-month outputs.', 'Explain what the smaller payment changes and what the longer commitment costs.'],
apply: ['Find A’s cost above the $1,800 principal, including the separate setup fee once.', 'Do the same for B using its own total payments and fee.', 'Use A’s first interest charge and payment split to find the closing balance.', 'Compare both offers against Ren’s cash-flow limits and costs; explain a recommendation using the supplied records.']},
'fl2-04': {
read: ['Protect both required payments.|Find Jo’s minimums before allocating any extra money.', 'Follow the chosen priority.|Trace where the remaining amount goes under highest-rate-first.', 'Read the schedule’s limits.|Find why the result depends on the stated budget, rates and payment pattern.'],
help: 'A minimum payment is a required amount. Extra repayment is money left after all minimums. A payoff schedule belongs to its stated inputs; a new budget requires a new calculation rather than the old promised date.',
practice: ['Subtract both unchanged minimums from the new $90 budget.', 'Enter A’s payment while following highest-rate-first.', 'Enter B’s payment and check that both payments total no more than $90.', 'Explain why the earlier payoff date no longer follows.', 'For the additional $60-budget choice, check whether both minimums can be covered.'],
apply: ['Allocate C’s first payment from the existing $100 budget.', 'Allocate D’s first payment, explaining the strategy after covering both minimums.', 'Compare the proposed $540 sale value with the new loan’s $648 repayment.', 'Write four or five sentences with repayment instructions and a reasoned response to the investment proposal; do not invent a payoff date.']},
'fl2-05': {
read: ['Start with the device deadline.|Find the need Nico must meet and the confirmed loaner period.', 'Follow the cash timeline.|Track the starting money and deposits against the cash price.', 'Read the supported alternative.|Find what is confirmed and what still needs verification before relying on it.'],
help: 'A confirmed resource has stated availability and conditions. A possible extension, gift or replacement cannot be added to a plan without evidence. Compare the date money arrives with the date the item is needed.',
practice: ['Count only the opening money and deposits received before the new loaner-return deadline.', 'Subtract that available cash from the unchanged $420 price.', 'Write two sentences naming the missing arrangement to verify and why it matters.'],
apply: ['Include all six payments and the setup fee in financing total.', 'Compare that total with the all-in cash price.', 'Add the opening money and confirmed day-seven payment.', 'Write three or four sentences linking Taylor’s requirement, deadline, cost and uncertainty without assuming the unverified borrowed boots solve it.']},
'fl2-06': {
read: ['Separate the fixed offer from the scenario.|Find which rate remains fixed and which later rate is assumed.', 'Follow the changed payment.|Track the variable offer’s recalculation at the specified month.', 'Compare fit and total cost.|Read why the lower starting payment is only one part of Ari’s decision.'],
help: 'A variable-rate scenario shows what would happen under a stated change; it is not a forecast of that rate. Monthly margin is the amount left within the payment allowance. Compare the later payment as well as the starting one.',
practice: ['Compare the recalculated regular payment with Ari’s $223 limit.', 'Compare the stress scenario’s interest total with fixed offer F.', 'Explain in two or three sentences how the 10% second-year scenario changes your recommendation.'],
apply: ['Subtract H’s later regular payment from Jules’s $250 monthly allowance.', 'Compare H’s total interest with fixed offer G.', 'Write four or five sentences comparing monthly fit, cost, rate certainty and a condition that could change the result.']},
'fl2-07': {
read: ['Separate term from amortization.|Find the five-year contract period within the longer repayment plan.', 'Trace the debt at renewal.|Follow total payments, interest and the balance still remaining after sixty payments.', 'Read the comparison’s boundary.|Find what the quotation says about monthly fit and what it cannot promise beyond the term.'],
help: 'The term is the period covered by the contract’s stated conditions. Amortization is the planned time to repay the debt. A prepayment privilege describes an allowed extra payment under that contract; unconfirmed future money is not a guaranteed payment.',
practice: ['Compare the new regular payment with the original payment.', 'Compare the two balances at month sixty.', 'Subtract the new payment from the $860 allowance.', 'Explain in two sentences what the shorter amortization changes and what remains outside this calculation.'],
apply: ['Subtract P’s payment from Morgan’s $1,200 allowance.', 'Use P’s stated annual privilege to calculate its dollar amount.', 'Use Q’s own stated privilege to calculate its dollar amount.', 'Write four to six sentences about monthly fit, remaining balance, the hoped-for extra payment and limits of the quotation.']},
'fl3-01': {
read: ['Find each target gap.|Follow Sam’s starting balances, prices and deadlines.', 'Track the weekly phases.|Read how the same available amount is divided, then redirected after a goal is funded.', 'Check feasibility and review.|Locate the week each target is met and what would require revision.'],
help: 'A target gap is the amount still needed after current savings. A phase is a period with a particular allocation. Money assigned to one goal cannot also fund another, and a protected reserve stays separate.',
practice: ['Find the bicycle contribution left after the protected jacket amount in weeks one to six.', 'Include the starting bicycle balance and both contribution phases through week twelve.', 'Compare that balance with the unchanged bicycle price.', 'Give a feasible change in two sentences without inventing extra money or using the protected reserve.'],
apply: ['Divide Lena’s remaining fee target by the eight available weekly deposits.', 'Calculate the fee balance immediately after week eight’s deposit.', 'Write three or four sentences explaining the hobby adjustment, feasibility and review point.']},
'fl3-02': {
read: ['Follow the stated priorities.|Find which of Avery’s needs is not yet funded.', 'Compare what each use provides.|Locate access, debt reduction and uncertainty in the supplied options.', 'Find the opportunity cost.|Read what is given up by allocating the same $80 to one purpose.'],
help: 'Opportunity cost is the benefit forgone when money is used elsewhere. It is not another charge. A stated priority helps compare options; a possible investment gain is not confirmed money for an approaching deadline.',
practice: ['Choose the next use under the changed case’s priority order.', 'Subtract the extra payment from the debt balance.', 'Explain the benefit and the forgone alternative in two sentences.'],
apply: ['Subtract Jules’s reserved repair money from the confirmed repair price.', 'Add the extra $40 if assigned to the repair.', 'Write three or four sentences using the deadline and ranking; explain the opportunity cost and why the investment headline does not fund the gap.']},
'fl3-03': {
read: ['Identify the two layers.|Find the difference between an account arrangement and the asset held inside it.', 'Match access to the deadline.|Trace why Noor’s course-fee money needs a holding available at the required date.', 'Read the risk limit.|Find why an account label does not guarantee the holding’s value.'],
help: 'An account arrangement sets rules for holding money or assets. A holding is the deposit, fund or other asset inside it. Access, fees and uncertain value belong to the actual product’s terms; an account name alone does not settle them.',
practice: ['Choose the product details that still need checking for the eight-year goal.', 'Name the account arrangement separately from the holding.', 'Name the holding from Product F’s record.', 'Explain in two or three sentences why F could be considered and what the horizon and account cannot guarantee.'],
apply: ['Choose a supplied holding that can serve the three-month course payment.', 'Enter the total proposed TFSA contribution within the confirmed $1,200 room.', 'Write four or five sentences assigning both goals to account and holding layers, with access, risk and contribution limits.']},
'fl3-04': {
read: ['Keep dollars and prices separate.|Find the $101 balance and the $103 price of the unchanged basket.', 'Follow the purchasing-power adjustment.|Trace how the answer puts the balance back on the old price scale.', 'Read what the difference means.|Find why a shortfall or lower buying power is not money the bank removed.'],
help: 'Nominal balance is the displayed dollar amount. Purchasing power describes what it can buy at the relevant prices. Comparing two model runs can isolate one assumption; their outputs are not promised investment results.',
practice: ['Subtract the with-fee nominal balance from the no-fee nominal balance.', 'Choose the claim supported by the two supplied runs.', 'Write two sentences explaining the fee’s effect and why the model outputs are not a promise.'],
apply: ['Apply the 5% price change to Riley’s original $240 quotation.', 'Compare the new price with the $248 already saved.', 'Choose the new set with the confirmed addition or the supplied suitable used set.', 'Explain the updated price, funding, choice and what changed; do not reuse the optional long-term investment assumptions.']},
'fl3-05': {
read: ['Find the gaps and priorities.|Read Fei’s opening balances, targets and dates.', 'Follow each phase.|Trace contributions before and after the nearer goal is funded.', 'Check the last deposit and review.|Find the partial final amount and what information could change the plan.'],
help: 'A phased plan reallocates the available money when a goal is reached. Count later deposits from the end of the earlier phase. The last deposit need only cover the remaining gap, unless the case specifies otherwise.',
practice: ['Subtract the protected laptop contribution from the new $60 monthly amount.', 'Use the opening balance and eight training deposits for the month-eight balance.', 'Count whole deposits after month eight to find when training reaches its target.', 'Write the revised phase instruction in two sentences.', 'Choose a useful next question rather than assuming extra resources.'],
apply: ['Find the earliest month the priority nearer goal can be funded.', 'Carry its partial final deposit and remaining monthly money into the longer goal to find when both are funded.', 'Write five or six sentences with phases, the original-date problem, partial deposits, a review point and a useful support question within $35 monthly.']},
'fl3-06': {
read: ['Preserve the actual history.|Follow Ari’s recorded deposits and expense before revising.', 'Start from the present balance.|Find the new gap and number of deposits remaining.', 'Read the supported adjustment.|Trace the confirmed temporary amount and the review point without adding interest or gifts.'],
help: 'A revision begins with the balance after actual transactions. An original plan is not proof that every planned deposit happened. Count remaining deposits from the current month and keep unconfirmed returns or refunds out of the calculation.',
practice: ['Find how many $30 deposits cover the remaining gap.', 'Count those deposits from month three to give the completion month.', 'Write two sentences stating the changed date and unchanged balance, target and contribution.'],
apply: ['Subtract the necessary expense from Devon’s recorded month-three balance.', 'Subtract the current balance from the unchanged target.', 'Divide the gap by the three deposits left before the deadline.', 'Write four or five sentences explaining history, the ordinary amount’s shortfall, the confirmed adjustment and a review point.']},
'fl4-01': {
read: ['Identify the visible clues.|Find what Casey’s public details could reveal without assuming misuse already occurred.', 'Follow the purpose-preserving edits.|Read how the example reduces unnecessary exposure while keeping the profile useful.', 'Check controls and limits.|Locate permission and account changes, a review habit and what the plan cannot guarantee.'],
help: 'Exposure means information or access is available beyond what the activity needs. A possible inference is not proof of misuse. Removing public details can reduce future exposure without recalling copies already made.'},
'fl4-02': {
read: ['Read the requested action first.|Find what each contact asks Leah to do, not just the name or logo used.', 'Follow the independent check.|Locate the separate known route and what it establishes.', 'Find the decision boundaries.|Read how the plan distinguishes confirmed, rejected and unresolved requests.'],
help: 'Independent verification uses a route known separately from the questionable contact. A genuine-looking name or an expected appointment can make a contact plausible without authenticating that particular sender or caller.'},
'fl4-03': {
read: ['Map the actual exposure.|Find what Finley entered and what the record says was not entered.', 'Follow the recovery order.|Trace why email recovery and existing sessions need attention alongside password changes.', 'Check pending results.|Find the monitoring and support steps without claiming cleanup or recovery is guaranteed.'],
help: 'Containment reduces further exposure while the outcome is still uncertain. Completed password changes, ended sessions and enabled protections are different actions. A log should record what happened without storing actual secrets or card data.'},
'fl4-04': {
read: ['Compare the same offer at each stage.|Find Mina’s advertisement, checkout and business reply for the same tablet.', 'Separate store fees from tax.|Follow the pre-tax difference and the supplied checkout total.', 'Match the action to the transaction stage.|Read why the response raises a concern without inventing a paid transaction or automatic refund.'],
help: 'A concern file keeps the advertisement, accepted terms, charges and correspondence in date order. A corrected later offer does not erase an earlier record. A request for review is different from a legal finding or guaranteed refund.'},
'fl4-05': {
read: ['Map the transfer and account exposure separately.|Find the approved deceptive transfer and the reused credential in Ari’s record.', 'Follow each recipient’s job.|Trace the bank action, account security and separate fraud-reporting roles.', 'Check the recovery-message boundary.|Read why knowledge of an amount or case label does not verify a stranger or promise recovery.'],
help: 'A coordinated plan gives each recipient a specific purpose and independently reached route. A report reference records a report; it is not proof that everyone repeating it is authorized. Keep completed actions and pending outcomes separate.'}
};
