# Adapted from the frozen v1.2 independent 88-assertion host harness; runtime unchanged.
#!/usr/bin/env python3
"""Exercise the actual standalone runtime in Chromium, without a mock/debug app.
Managed browser navigation is restricted in the authoring environment, so this harness
loads the exact PLAY.html bytes using set_content; real file:// and host routing are separate gates.
Requires: pip install playwright; Chromium available at CHROMIUM or /usr/bin/chromium.
"""
from pathlib import Path
import json, os, traceback, sys, hashlib
from playwright.sync_api import sync_playwright
ROOT=Path(os.environ['S24_A1_OUTPUT']); (ROOT/'qa/host-screenshots').mkdir(parents=True,exist_ok=True)
REPORT=ROOT/'qa/host-browser-tests.json'
items=[]
def check(name,value,detail=''):
    items.append({'test':name,'status':'PASS' if value else 'FAIL','detail':detail})
    if not value: raise AssertionError(name+' '+detail)
def button(page,action):return page.locator(f'[data-action="{action}"]').first
def load(page):
    page.set_default_timeout(5000)
    page.goto(os.environ['S24_A1_URL'],wait_until='load')
def begin(page):button(page,'start').click();button(page,'practice').click()
def openpair(page,ids,prediction='insufficient'):
    if page.locator('#prediction').count():page.locator('#prediction').select_option(prediction)
    for id in ids:page.locator(f'[data-action=reveal][data-id="{id}"]').click()
    for id in ids:page.locator(f'#select-{id}').check()
def answer(page,conclusion,reaction=None,response=None,explanation='The supplied records identify the substances and support this conclusion. I compared them before and after the change.'):
    page.locator(f'#conclusion-{conclusion}').check()
    if reaction:page.locator('#reaction').select_option(reaction)
    if response:page.locator('#response').select_option(response)
    page.locator('#explanation').fill(explanation)
    button(page,'submit').click()
def advance(page):
    for x in page.locator('[data-rubric]').all():x.check()
    check('Next enabled only after explanation review',not button(page,'advance').is_disabled())
    button(page,'advance').click()
def nooverflow(page,label):check(label+' / no document overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
def semantics(page,label):
    missing=page.locator('input,select,textarea').evaluate_all("els=>els.filter(e=>!e.disabled&&e.getClientRects().length&&!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.outerHTML)")
    check(label+' / native inputs named',not missing,str(missing))
    missing=page.locator('button').evaluate_all("els=>els.filter(e=>e.getClientRects().length&&!e.innerText.trim()&&!e.getAttribute('aria-label')).map(e=>e.outerHTML)")
    check(label+' / buttons named',not missing,str(missing))
    check(label+' / whole main is not live',page.locator('main').get_attribute('aria-live') is None)
    check(label+' / one h1',page.locator('h1').count()==1)
def snap(page,name):page.screenshot(path=str(ROOT/'qa/host-screenshots'/name),full_page=True,timeout=30000)
def run():
  with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM') or None,headless=True,args=['--no-sandbox'])
    page=b.new_page(viewport={'width':1648,'height':1050},device_scale_factor=1)
    errors=[];requests=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
    load(page);semantics(page,'Intro');nooverflow(page,'Intro');snap(page,'01_intro_desktop.png')
    button(page,'help').click();check('Help dialog open',page.locator('dialog').evaluate('(e)=>e.open'))
    check('Dialog safe close autofocus',page.evaluate('document.activeElement.dataset.action')=='modal-close')
    page.keyboard.press('Escape');check('Escape closes dialog',not page.locator('dialog').evaluate('(e)=>e.open'))
    check('Dialog focus restored',page.evaluate('document.activeElement.dataset.action')=='help')
    button(page,'start').click();snap(page,'02_worked_desktop.png');semantics(page,'Worked');nooverflow(page,'Worked')
    check('No labelled original peroxide bottle in runtime',page.locator('.scene-frame img').evaluate('(e)=>e.naturalWidth>0'))
    button(page,'practice').click();semantics(page,'P01');snap(page,'03_investigation_desktop.png')
    check('Evidence locked before prediction',all(x.is_disabled() for x in page.locator('[data-action=reveal]').all()))
    button(page,'submit').click();check('Empty submission focuses missing prediction',page.evaluate('document.activeElement.id')=='prediction')
    check('Empty attempt does not unlock hints',button(page,'hint').is_disabled())
    openpair(page,['p01_e1','p01_e3'])
    check('Reveal focus stays on new evidence',page.evaluate('document.activeElement.id').startswith('select-'))
    button(page,'previous').click();check('Previous returns to worked example','Worked example' in page.locator('.subtitle').inner_text())
    button(page,'practice').click();check('Back-forward restores opened evidence',page.locator('#select-p01_e1').is_checked() and page.locator('#select-p01_e3').is_checked())
    check('Back-forward preserves locked prediction',page.locator('#prediction').count()==0)
    check('Prediction freezes on first reveal',page.locator('#prediction').count()==0)
    check('Two record budget enforced',page.locator('[data-action=reveal]:disabled').count()==2)
    answer(page,'insufficient')
    check('Uncertainty accepted but does not complete case',page.locator('#feedback-title').inner_text()=='Uncertainty is justified' and page.locator('[data-action=advance]').count()==0)
    check('Successful checkpoint answer locks',page.locator('#explanation').is_disabled())
    button(page,'followup').click()
    check('Follow-up focus on identity record',page.evaluate('document.activeElement.id')=='evidence-p01_e2')
    page.locator('#select-p01_e2').click()
    check('Third evidence selection prevented',not page.locator('#select-p01_e2').is_checked())
    page.locator('#select-p01_e3').uncheck();page.locator('#select-p01_e2').check()
    answer(page,'physical',explanation='The identity analysis reports no new substances and the recovered solid matches the original. This supports a physical change in this model; cooling alone was inconclusive.')
    check('P01 supported answer accepted','Structured choices supported'==page.locator('#feedback-title').inner_text())
    check('Feedback receives focus',page.evaluate('document.activeElement.id')=='feedback-title')
    check('Next disabled until rubric reviewed',button(page,'advance').is_disabled())
    for x in page.locator('[data-rubric]').all():x.check()
    check('Next available after rubric',not button(page,'advance').is_disabled())
    snap(page,'04_feedback_desktop.png')
    button(page,'revise').click();check('Revision invalidates successful progression',page.locator('[data-action=advance]').count()==0)
    answer(page,'chemical','combustion');check('Wrong revision cannot advance',page.locator('[data-action=advance]').count()==0)
    for i in range(3):button(page,'hint').click()
    check('P01 hints capped at three',button(page,'hint').is_disabled())
    button(page,'reopen').click();button(page,'modal-close').click();check('Cancel keeps current records',page.locator('#select-p01_e2').is_checked())
    button(page,'reopen').click();button(page,'modal-confirm').click()
    check('Reopen keeps attempts',page.locator('.attempt').count()==3)
    check('Reopen keeps hint count',button(page,'hint').is_disabled())
    check('Earlier evidence remains readable',page.locator('.disclosure').filter(has_text='Records you read earlier').count()==1)
    openpair(page,['p01_e1','p01_e2']);answer(page,'physical');advance(page)
    check('New case correctly named','workshop tool' in page.locator('#case-heading').inner_text())
    check('New case fields cleared',page.locator('#explanation').input_value()=='' and page.locator('input[name=conclusion]:checked').count()==0)
    page.locator('#prediction').select_option('chemical');page.locator('#explanation').fill('Draft work to preserve while moving backward.')
    button(page,'previous').click();check('Previous case restores completed P01','Structured choices supported'==page.locator('#feedback-title').inner_text())
    button(page,'advance').click();check('Returning forward restores later draft',page.locator('#prediction').input_value()=='chemical' and page.locator('#explanation').input_value()=='Draft work to preserve while moving backward.')
    openpair(page,['p02_e1','p02_e2'],'chemical')
    check('Blanket composition alternative removed',page.locator('#reaction option[value=composition]').count()==0)
    answer(page,'chemical','corrosion','polish_only')
    check('Corrosion response actually validated','barrier' in page.locator('#feedback-zone').inner_text().lower())
    page.locator('#response').select_option('barrier_coating');button(page,'submit').click();semantics(page,'P02 feedback')
    snap(page,'05_rusting_desktop.png');advance(page)
    check('P03 no early sentence starter','Sentence starter' not in page.locator('main').inner_text())
    openpair(page,['p03_e1','p03_e2']);answer(page,'chemical','neutralization')
    check('Acid-carbonate neutralization accepted',page.locator('#feedback-title').inner_text()=='Structured choices supported')
    snap(page,'06_antacid_desktop.png');advance(page)
    check('P04 reduced hint cap','Hint 1 of 1' in button(page,'hint').inner_text())
    check('P04 no early teaching scaffold','Sentence starter' not in page.locator('main').inner_text())
    openpair(page,['p04_e1','p04_e2']);answer(page,'chemical','combustion','water')
    check('Greenhouse question disambiguates water vapour','Water vapour is also a greenhouse gas' in page.locator('#feedback-zone').inner_text())
    page.locator('#response').select_option('carbon_dioxide');button(page,'submit').click();snap(page,'07_combustion_desktop.png');advance(page)
    check('Transfer has no hints, tokens, art or help',page.locator('[data-action=hint],[data-action=help],.tokens,.scene-frame').count()==0)
    check('Transfer no model before submission',page.locator('summary').filter(has_text='Compare with a model explanation').count()==0)
    snap(page,'08_transfer_desktop.png');semantics(page,'Transfer')
    answer(page,'chemical');check('Transfer first error requires revision',page.locator('[data-action=advance]').count()==0)
    answer(page,'physical',explanation='The change is physical: the identity record remains H₂O before heating and after condensation. The bubbles show a change of state, not a new substance.');advance(page)
    check('Review preserves failed first transfer','Transfer: corrected after feedback' in page.locator('main').inner_text())
    check('Five completed learner tasks displayed',page.locator('.result-card').count()==5)
    check('Review does not grade written explanations',page.locator('main').inner_text().count('not automatically graded')>=5)
    check('Support not erased on case reset','3 hints' in page.locator('.result-card').first.inner_text() and '1 investigation restarts' in page.locator('.result-card').first.inner_text())
    snap(page,'09_review_desktop.png');semantics(page,'Review');nooverflow(page,'Review')
    card=page.locator('.result-card').filter(has_text='Boiling Water');card.locator('[data-action=replay]').click()
    check('Replay not presented as a fresh independent attempt','A first response is already on record' in page.locator('main').inner_text())
    answer(page,'physical');advance(page)
    check('Replay does not overwrite original transfer result','Transfer: corrected after feedback' in page.locator('main').inner_text())
    page.evaluate('window.print=()=>{window.__printRequested=true;}');button(page,'print').click()
    check('Print review action works',page.evaluate('window.__printRequested===true'))
    page.emulate_media(media='print');snap(page,'10_review_print.png');page.emulate_media(media='screen')
    check('All runtime images decoded',page.locator('img').evaluate_all('els=>els.every(e=>e.naturalWidth>0)'))
    check('No page JavaScript errors',not errors,str(errors))
    check('No external network requests',not [r for r in requests if not (r.startswith('data:') or r.startswith(os.environ['S24_A1_URL']))],str(requests))
    button(page,'restart').click();button(page,'modal-close').click();check('Restart cancel keeps review',page.locator('.result-card').count()==5)
    button(page,'restart').click();button(page,'modal-confirm').click();check('Explicit new session returns to intro',page.locator('[data-action=start]').count()==1)
    b.close()
try:
    run()
except Exception as e:
    items.append({'test':'Harness execution','status':'FAIL','detail':traceback.format_exc()})
finally:
    REPORT.write_text(json.dumps({'artifact_sha256':hashlib.sha256((ROOT/'PLAY.html').read_bytes()).hexdigest(),'method':'Independent full core browser flow via actual candidate URL supplied by S24_A1_URL. Only that origin and data URLs allowed.','tests':items,'passed':sum(x['status']=='PASS' for x in items),'failed':sum(x['status']=='FAIL' for x in items)},indent=2))
    print(json.dumps({'passed':sum(x['status']=='PASS' for x in items),'failed':sum(x['status']=='FAIL' for x in items),'last':items[-1] if items else None},indent=2))
    if any(x['status']=='FAIL' for x in items):sys.exit(1)
