import {evaluatePlan,devicesFrom} from './engine.js';
import {escapeHTML as h,number,asset,panel,scene,prediction,table,field,selectField,explanation,checkButtons,formGate,modelGate} from './ui.js';
function budget(s,m){try{const r=evaluatePlan({devices:devicesFrom(s,m.modelInputs),cap_kwh:s.cap_kwh,requirements:s.serviceRequirements});return table(['Energy','Cap','Service'],[[number(r.total_kwh)+' kWh',s.cap_kwh+' kWh',r.servicesMet?'Met':'Not met']],'Your current selected plan')+`<p>${r.underCap?'Within':'Above'} the cap; ${r.servicesMet?'required services retained':'restore missing services'}.</p><div class="budget-meter"><span style="width:${Math.min(100,r.total_kwh/s.cap_kwh*100)}%"></span></div>`;}catch(e){return `<p>${h(e.message)}</p>`;}}
export function render(s,m,transfer=false){
 if(s.input_j!=null)return panel('Efficiency Evidence',1,'Useful output must be supplied',scene(s,'Context illustration of equipment')+table(['Quantity','Value'],[['Input',s.input_j+' J'],['Useful output',s.useful_j+' J']])+prediction(s,m))+panel('Your Calculation',2,'Useful ÷ input × 100',formGate(m,field('efficiency','Efficiency',m.modelInputs.efficiency,'%')))+panel('Reasoning',3,'Power and efficiency are different',explanation(m.explanation,s.explanationPrompt)+checkButtons(m));
 const services=table(['Required equipment','Quantity','Hours','Power options'],s.serviceRequirements.map(r=>[r.name,r.requiredCount,r.requiredHours,r.powers.join(' or ')+' W']),'Mandatory services; power options provide the same stated service');
 const plan=s.serviceRequirements.map(r=>`<div class="device-card"><h3><img class="equipment-icon" src="${asset('assets/sprites/sprite_'+(r.id.includes('lamp')?'lamp':r.id.includes('fan')?'fan':r.id.includes('projector')?'projector':'computer')+'.png')}" alt="">${h(r.name)}</h3>${selectField(r.id+'_power','Power',m.modelInputs[r.id+'_power'],r.powers.map(w=>[w,w+' W']))}${field(r.id+'_count','Quantity',m.modelInputs[r.id+'_count'])}${field(r.id+'_hours','Operating time',m.modelInputs[r.id+'_hours'],'h')}</div>`).join('');
 return panel(transfer?'Fresh Transfer':'Service Brief',1,transfer?'Conventional equipment table':'Services cannot be turned off',(transfer?'':scene(s,'Context illustration of powered equipment'))+`<p>Energy cap: ${s.cap_kwh.toFixed(3)} kWh.</p>`+services+(transfer?'<p>Calculate the original plan and a repaired plan. No budget animation is supplied before submission.</p>':prediction(s,m)))+
 panel(transfer?'Your Plan':'Device Plan',2,'Select, calculate and justify',formGate(m,plan+(transfer?field('initialTotal','Original total',m.modelInputs.initialTotal,'kWh')+field('repairedTotal','Repaired total',m.modelInputs.repairedTotal,'kWh'):field('total','Your energy total',m.modelInputs.total,'kWh')),transfer))+
 panel('Service & Energy Check',3,'E = P × t',`<div id="live-budget">${!transfer||m.firstTransferResponse?modelGate(m,budget(s,m),transfer):'<p>Submit your independent calculations before revealing the budget account.</p>'}</div>`+explanation(m.explanation,s.explanationPrompt)+checkButtons(m,transfer));
}
export function refresh(root,s,m){const el=root.querySelector('#live-budget');if(el&&(m.predictionLocked||m.firstTransferResponse))el.innerHTML=budget(s,m);}
export function worked(){}
