export function finite(v,name){if(v===''||v==null||!Number.isFinite(Number(v))||Number(v)<0)throw new Error(name+' must be a finite non-negative value.');return Number(v);}
export function reactionDistance(speed,time){return finite(speed,'Speed')*finite(time,'Reaction time');}
export function totalStop({speed,reactionTime,brakingDistance,gap}){const reaction=reactionDistance(speed,reactionTime),total=reaction+finite(brakingDistance,'Braking distance'),margin=finite(gap,'Gap')-total;return{reactionDistance:reaction,totalStoppingDistance:total,margin,stopsBefore:margin>1e-9,outcome:Math.abs(margin)<=1e-9?'touches':margin>0?'before':'passes'};}
export function positionAt({speed,reactionTime,deceleration=5},time){const v=finite(speed,'Speed'),tr=finite(reactionTime,'Reaction time'),a=finite(deceleration,'Deceleration'),t=finite(time,'Time');if(a<=0)throw new Error('Deceleration must be positive.');if(t<=tr)return v*t;const tau=Math.min(t-tr,v/a);return v*tr+v*tau-0.5*a*tau*tau;}
export function distanceTimePoints({speed,reactionTime,brakingTime,deceleration=5}){const v=finite(speed,'Speed'),tr=finite(reactionTime,'Reaction time'),a=finite(deceleration,'Deceleration');if(a<=0)throw new Error('Deceleration must be positive.');const tb=v/a;if(brakingTime!=null&&Math.abs(finite(brakingTime,'Braking time')-tb)>1e-6)throw new Error('Braking duration conflicts with the stated deceleration.');const end=tr+tb+1.5;return Array.from({length:101},(_,i)=>{const t=end*i/100;return[t,positionAt({speed:v,reactionTime:tr,deceleration:a},t)];});}
function entered(v){if(v===''||v==null||!Number.isFinite(Number(v)))throw new Error('Complete every calculation with a finite number.');return Number(v);}
export function validate(s,a){try{
 if(s.kind==='comparison'){if(s.reaction_distances.some((v,i)=>Math.abs(entered(a['reaction'+i])-v)>1e-6)||a.brakingChange!=='unchanged')return{valid:false,message:'Change only reaction time: reaction travel changes linearly, while the supplied braking distance stays unchanged.'};return{valid:true,message:'Your controlled comparison separates reaction travel from unchanged braking travel.'};}
 if(s.kind==='graph'){if(entered(a.reactionSpeed)!==20||a.slope!=='speed'||a.horizontal!=='stopped'||a.brakingSlope!=='decreasing')return{valid:false,message:'Slope represents speed. The braking slope decreases to zero, and a horizontal distance-time segment means stopped.'};return{valid:true,message:'Your graph interpretation matches the synchronized motion model.'};}
 const r=totalStop({speed:s.speed,reactionTime:s.reaction_time,brakingDistance:s.braking_distance,gap:s.gap});
 if(['reaction','total','margin'].some((k,i)=>Math.abs(entered(a[k])-[r.reactionDistance,r.totalStoppingDistance,r.margin][i])>1e-6))return{valid:false,message:'Calculate reaction distance first, add the supplied braking distance, then subtract the total from the gap.',details:r};
 if(a.outcome!==r.outcome)return{valid:false,message:'Distinguish stopping before, exactly reaching, and passing the obstacle position. Zero clearance is not stopping before.',details:r};
 return{valid:true,message:'Your distances, units and obstacle comparison agree with the supplied model.',details:r};
}catch(e){return{valid:false,message:e.message};}}
