import {positionAt,distanceTimePoints,totalStop} from './engine.js';
import {escapeHTML as h,number,asset,panel,scene,prediction,table,field,selectField,explanation,checkButtons,formGate} from './ui.js';
function graph(s,now=0){const points=distanceTimePoints({speed:s.speed,reactionTime:s.reaction_time,brakingTime:s.braking_time,deceleration:5}),end=points.at(-1)[0],max=Math.max(s.gap,s.total)+10;
 const xy=([t,x])=>[45+t/end*410,240-x/max*205];
 const path=points.map((p,i)=>(i?'L':'M')+xy(p).map(v=>v.toFixed(2)).join(' ')).join(' ');
 return `<svg class="graph-svg" viewBox="0 0 500 290" role="img" aria-label="Distance-time curve: straight during reaction, curved during braking, then horizontal when stopped">${[0,1,2,3,4,5].map(i=>`<path d="M45 ${240-i*41}H455M${45+i*82} 35V240" fill="none" stroke="#dde6e0"/>`).join('')}<path d="M45 30 V240 H470" fill="none" stroke="#56635b" stroke-width="2"/><path d="${path}" fill="none" stroke="#1f6b3a" stroke-width="3"/><circle cx="${xy([now,positionAt({speed:s.speed,reactionTime:s.reaction_time},now)])[0]}" cy="${xy([now,positionAt({speed:s.speed,reactionTime:s.reaction_time},now)])[1]}" r="5" fill="#172b23"/><text x="200" y="280">Time (s)</text><text x="8" y="20">Distance (m)</text>${[0,s.reaction_time,s.reaction_time+s.braking_time,end].map(t=>`<text x="${xy([t,0])[0]-10}" y="260">${number(t)}</text>`).join('')}${[0,s.total].map(x=>`<text x="5" y="${xy([0,x])[1]+5}">${number(x)}</text>`).join('')}</svg>`;
}
function model(s,m){const end=s.reaction_time+s.braking_time,now=Math.min(m.replayTime,end+1.5),position=positionAt({speed:s.speed,reactionTime:s.reaction_time},now),span=Math.max(s.gap,s.total)+10;
 return `<div class="replay-stage"><img class="replay-car" src="${asset('assets/sprites/sprite_car.svg')}" alt="Model vehicle; front marks its position" style="width:45px;height:40px;transform:translateX(-100%);left:${10+position/span*75}%"><span class="replay-obstacle" style="left:${10+s.gap/span*75}%" aria-label="Stationary obstacle"></span></div><p>Replay: ${number(now)} s · front position ${number(position)} m. Obstacle: ${s.gap} m.</p>`+'<details class="model-table"><summary>Distance table and replay values</summary>'+table(['Time (s)','Position (m)'],[now,0,s.reaction_time,s.reaction_time+s.braking_time/2,end,end+1.5].map(t=>[number(t),number(positionAt({speed:s.speed,reactionTime:s.reaction_time},t))]),'Current replay position first; then fixed curve reference points')+'</details>';
}
export function render(s,m,transfer=false){
 let fields='';
 if(s.kind==='comparison')fields=s.reaction_times.map((t,i)=>field('reaction'+i,'Reaction travel at '+t+' s',m.modelInputs['reaction'+i],'m')).join('')+selectField('brakingChange','Braking travel when only reaction time changes',m.modelInputs.brakingChange,[['unchanged','Unchanged: the supplied 40 m'],['changes','Changes with reaction time']]);
 else if(s.kind==='graph')fields=field('reactionSpeed','Reaction-segment speed',m.modelInputs.reactionSpeed,'m/s')+selectField('slope','Slope represents',m.modelInputs.slope,[['speed','Speed'],['distance','Distance only']])+selectField('brakingSlope','Slope during braking',m.modelInputs.brakingSlope,[['decreasing','Decreases to zero'],['constant','Stays constant']])+selectField('horizontal','Horizontal distance-time segment',m.modelInputs.horizontal,[['stopped','Vehicle stopped'],['moving','Constant nonzero speed']]);
 else fields=field('reaction','Reaction distance',m.modelInputs.reaction,'m')+field('total','Total stopping distance',m.modelInputs.total,'m')+field('margin','Clearance to obstacle',m.modelInputs.margin,'m')+selectField('outcome','Stopping position',m.modelInputs.outcome,[['before','Before obstacle'],['touches','Exactly at obstacle'],['passes','Past obstacle position']]);
 return panel(transfer?'Fresh Transfer':'Road Scenario',1,'Stationary-obstacle model',(transfer?'':scene(s,'Context illustration of a model vehicle and stationary obstacle'))+table(['Quantity','Supplied value'],[['Speed',s.speed+' m/s'],['Reaction time',s.kind==='comparison'?s.reaction_times.join(', ')+' s':s.reaction_time+' s'],['Braking distance',s.braking_distance+' m'],['Obstacle gap',s.gap+' m']])+(transfer?'<p>Compare this total stop with the worked 70 m case. All braking data assume 5 m/s² deceleration.</p>':prediction(s,m)))+
 panel(transfer?'Your Calculation':'Your Prediction & Calculation',2,transfer?'No replay before submission':'Separate reaction and braking',formGate(m,fields,transfer)+`<div id="motion-graph">${(m.revealed||s.kind==='graph')&&m.predictionLocked||m.firstTransferResponse?graph(s,Math.min(m.replayTime,s.reaction_time+s.braking_time+1.5)):''}</div>`+explanation(m.explanation,s.explanationPrompt)+checkButtons(m,transfer))+
 panel('Replay & Graph',3,'Slope shows speed',`<div id="motion-model">${(m.revealed||s.kind==='graph')&&m.predictionLocked||m.firstTransferResponse?model(s,m):'<p>Commit a prediction and run the replay to reveal the synchronized curve and table.</p>'}</div>${transfer&&!m.firstTransferResponse?'':'<div class="btn-row"><button class="btn" data-action="step">Step +0.5 s</button><button class="btn primary" data-action="replay">Run slow replay</button><button class="btn" data-action="pause">Pause</button></div>'}`);
}
export function refresh(root,s,m){const allowed=m.predictionLocked||m.firstTransferResponse||s.stage==='worked',el=root.querySelector('#motion-model'),gr=root.querySelector('#motion-graph');if(el&&allowed)el.innerHTML=model(s,m);if(gr&&allowed)gr.innerHTML=graph(s,Math.min(m.replayTime,s.reaction_time+s.braking_time+1.5));}
export function worked(root,s,m){const body=root.querySelector('.workspace section:nth-child(3) .panel-body');body.innerHTML='<p class="panel-subtitle">Graph must match the numbers</p><div id="motion-model">'+model(s,m)+'</div>';}
