"""Deterministic, reviewable scientific diagrams. Separate teaching/key-free assets.
All spatial geometry and all quantitative values are authored here, not generated by a model at run time.
"""
from pathlib import Path
import json,math,html,hashlib,textwrap
import cairosvg
R=Path(__file__).resolve().parent.parent; O=R.parent
GREEN='#154212';TEAL='#146c60';INK='#171b1b';MUTED='#5b635d';BORDER='#d9ded8';BLUE='#367aaa';ORANGE='#c27832';RED='#a43f35';PURPLE='#7962a0'
def esc(x):return html.escape(str(x),quote=True)
class Art:
 def __init__(self,ch,id,title,lesson,purpose,subtitle='Schematic — not to scale',height=900):
  self.ch=ch;self.id=f'ch{ch}-{id}';self.title=title;self.lesson=lesson;self.purpose=purpose;self.h=height;self.bits=[];self.targets={};self.geometry={};self.note=subtitle
  self.add(f'<rect width="1400" height="{height}" fill="white"/>')
  self.text(50,65,title,36,GREEN,weight='700');self.text(50,105,subtitle,21,MUTED)
 def add(self,s):self.bits.append(s)
 def text(self,x,y,s,size=24,color=INK,anchor='start',weight='400'):
  self.add(f'<text x="{x}" y="{y}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}" text-anchor="{anchor}" font-weight="{weight}">{esc(s)}</text>')
 def wrap(self,x,y,s,w=35,size=22,color=INK,anchor='start',weight='400'):
  lines=[]
  for part in s.split('\n'):lines.extend(textwrap.wrap(part,width=w,break_long_words=False,break_on_hyphens=False))
  for i,line in enumerate(lines):self.text(x,y+i*(size+8),line,size,color,anchor,weight)
 def line(self,x1,y1,x2,y2,color=INK,width=3,dash=None):
  self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{color}" stroke-width="{width}"'+(f' stroke-dasharray="{dash}"'if dash else'')+'/>')
 def arrow(self,x1,y1,x2,y2,color=TEAL,width=5):
  self.line(x1,y1,x2,y2,color,width);ang=math.atan2(y2-y1,x2-x1);l=17
  pts=[(x2,y2),(x2-l*math.cos(ang-.5),y2-l*math.sin(ang-.5)),(x2-l*math.cos(ang+.5),y2-l*math.sin(ang+.5))]
  self.add('<polygon points="'+' '.join(f'{x:.1f},{y:.1f}'for x,y in pts)+f'" fill="{color}"/>')
 def box(self,x,y,w,h,s='',fill='#f0f6f3',size=24):
  self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{BORDER}" stroke-width="2"/>')
  if s:self.wrap(x+w/2,y+36,s,max(12,int(w/(size*.52))),size,anchor='middle')
 def circle(self,x,y,r,fill='white',stroke=INK,width=3):self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def ellipse(self,x,y,rx,ry,fill='white',stroke=INK,width=3):self.add(f'<ellipse cx="{x}" cy="{y}" rx="{rx}" ry="{ry}" fill="{fill}" stroke="{stroke}" stroke-width="{width}"/>')
 def label(self,key,x,y,answer,tx=None,ty=None):
  assert key not in self.targets,(self.id,key)
  self.targets[key]=answer;self.geometry[key]={'letter':[x,y],'endpoint':[tx,ty]if tx is not None else[x,y]}
  if tx is not None:
   self.line(x,y,tx,ty,INK,2.5);self.circle(tx,ty,5,INK,'white',2)
  self.circle(x,y,22,'white',TEAL,2.5);self.text(x,y+8,key,23,INK,'middle','700')
 def chr(self,x,y,color=BLUE,rep=True,scale=1):
  if rep:
   self.line(x-17*scale,y-40*scale,x+17*scale,y+40*scale,color,11*scale);self.line(x+17*scale,y-40*scale,x-17*scale,y+40*scale,color,11*scale)
  else:self.line(x,y-40*scale,x,y+40*scale,color,11*scale)
  self.circle(x,y,5*scale,INK,INK,1)
 def build(self,blank=False):
  bits=self.bits.copy();yy=self.h-118
  bits.append(f'<line x1="50" y1="{yy-25}" x2="1350" y2="{yy-25}" stroke="{BORDER}" stroke-width="2"/>')
  if blank:
   bits.append(f'<text x="50" y="{yy+8}" font-family="Arial,sans-serif" font-size="21" fill="{MUTED}">Use the lettered features and the nearby lesson explanation.</text>')
  else:
   n=len(self.targets);cols=3;rows=math.ceil(n/cols);size=19 if rows<5 else 17
   for i,(k,v)in enumerate(self.targets.items()):
    x=50+(i%cols)*445;y=yy+(i//cols)*43
    for j,line in enumerate(textwrap.wrap(k+' · '+v,width=42,break_long_words=False)):
     bits.append(f'<text x="{x}" y="{y+j*21}" font-family="Arial,sans-serif" font-size="{size}" fill="{INK}">{esc(line)}</text>')
  return f'<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="{self.h}" viewBox="0 0 1400 {self.h}" role="img"><title>{esc(self.title)}</title><desc>{esc(self.purpose)}</desc>'+''.join(bits)+'</svg>'
 def save(self):
  root=O/f'chapter-{self.ch}';a=root/'workspace/assets';(a/'figures').mkdir(parents=True,exist_ok=True);(a/'labeling').mkdir(exist_ok=True);(root/'authoring').mkdir(exist_ok=True)
  for blank,folder in [(False,'figures'),(True,'labeling')]:
   p=a/folder/(self.id+'.svg');p.write_text(self.build(blank))
  rec={'id':self.id,'title':self.title,'lesson':self.lesson,'src':f'./assets/figures/{self.id}.svg','alt':self.purpose,'caption':self.purpose+' '+self.note+'.','source':'Original course schematic; reproducible geometry in scripts/make_media.py.','kind':'precisely authored SVG','reviewStatus':'Construction and target identities checked; render inspection recorded in verification.','targets':self.targets,'geometry':self.geometry}
  label={'id':self.id+'-label','title':self.title,'lesson':self.lesson,'src':f'./assets/labeling/{self.id}.svg','alt':self.purpose+' Lettered identification version; answer key is not drawn.','answers':self.targets,'options':list(dict.fromkeys(self.targets.values())),'reviewNote':'Follow each letter or its leader line. Use the model assumptions and units shown.'}
  MEDIA.setdefault(self.ch,[]).append(rec);LABELS.setdefault(self.ch,[]).append(label)
MEDIA={};LABELS={}

def flow(ch,id,title,lesson,items,purpose,subtitle='Schematic — arrows show the specified causal sequence'):
 art=Art(ch,id,title,lesson,purpose,subtitle)
 # Three-column rows, clear numbered route; row ends connect around outer edge.
 n=len(items);cols=3;rows=math.ceil(n/cols);bw=330;bh=150;ys=[220,470]
 if rows>2:raise ValueError('Keep flow bounded to six features')
 for i,(ans,description)in enumerate(items):
  row=i//3;col=i%3;x=90+col*450;y=ys[row];art.box(x,y,bw,bh,description,size=23);art.label(chr(65+i),x+35,y-24,ans)
  if col<2 and i<n-1:art.arrow(x+bw+12,y+bh/2,x+450-12,y+bh/2)
 if n>3:
  art.line(1155,ys[0]+bh,1155,ys[0]+bh+50,TEAL,4);art.line(1155,ys[0]+bh+50,60,ys[0]+bh+50,TEAL,4);art.line(60,ys[0]+bh+50,60,ys[1]+bh/2,TEAL,4);art.arrow(60,ys[1]+bh/2,90,ys[1]+bh/2)
 if id=='birth-feedback':
  art.line(705,620,705,710,TEAL,4);art.line(705,710,40,710,TEAL,4);art.line(40,710,40,245,TEAL,4);art.arrow(40,245,90,245);art.text(440,741,'Reinforces cervical stretch',21,MUTED,'middle')
 if id=='alternation':
  art.line(1155,620,1155,705,TEAL,4);art.line(1155,705,42,705,TEAL,4);art.line(42,705,42,245,TEAL,4);art.arrow(42,245,90,245);art.text(700,738,'Zygote grows by mitosis into the sporophyte',21,MUTED,'middle')
 art.save()

# CHAPTER17

a=Art(17,'punnett','A single-trait cross: Aa × Aa',3,'Each row and column represents a gamete. Four equally likely combinations give a 1:2:1 genotype ratio under the stated model. A is completely dominant to a.')
a.text(355,240,'A',35,BLUE,'middle');a.text(625,240,'a',35,ORANGE,'middle');a.text(180,360,'A',35,BLUE,'middle');a.text(180,560,'a',35,ORANGE,'middle')
for i,(x,y,ans)in enumerate([(230,275,'AA'),(500,275,'Aa'),(230,475,'Aa'),(500,475,'aa')]):
 a.box(x,y,270,190,'');a.label(chr(65+i),x+135,y+95,ans)
a.wrap(1000,295,'Interpret each lettered box as an offspring genotype, not as a gamete.',22,26,anchor='middle');a.wrap(1000,455,'One allele comes from the row and one from the column.',22,26,anchor='middle');a.save()
a=Art(17,'two-trait','Independent assortment: follow both allele choices',5,'Follow each branch from AaBb through one allele at the first locus and one at the second. Each endpoint is one haploid gamete, with probability one quarter.')
a.box(470,150,460,75,'Parent: AaBb',size=28)
for x,al in [(365,'A'),(1035,'a')]:
 a.arrow(700,230,x,315);a.circle(x,350,32,'#e7f1ea',TEAL);a.text(x,360,al,30,INK,'middle')
for i,(x,al,ans,parent)in enumerate([(190,'B','AB',365),(520,'b','Ab',365),(870,'B','aB',1035),(1200,'b','ab',1035)]):
 a.arrow(parent,388,x,457);a.circle(x,490,30,'#f7e9b6',ORANGE);a.text(x,500,al,30,INK,'middle');a.arrow(x,526,x,583);a.label(chr(65+i),x,615,ans);a.text(x,685,'Probability 1/4',22,MUTED,'middle')
a.save()
a=Art(17,'abo','ABO inheritance: IAi × IBi',7,'The standard three-allele ABO model produces four possible offspring genotypes in this cross. Each letter marks one phenotype to infer from its genotype.')
a.text(410,230,'IA',30,BLUE,'middle');a.text(750,230,'i',30,ORANGE,'middle');a.text(160,370,'IB',30,BLUE,'middle');a.text(160,590,'i',30,ORANGE,'middle')
for k,(x,y,geno,ans)in enumerate([(250,275,'IAIB','AB'),(590,275,'IBi','B'),(250,495,'IAi','A'),(590,495,'ii','O')]):
 a.box(x,y,340,190,geno,size=30);a.label(chr(65+k),x+170,y+120,ans)
a.wrap(1110,330,'IA and IB are codominant. Both are dominant to i.',17,25,anchor='middle');a.save()
a=Art(17,'pedigree','Pedigree: use the stated inheritance model',10,'In this fully penetrant autosomal recessive model, filled symbols are affected. Unaffected parents with an affected child must both be carriers. The unaffected sibling remains AA or Aa.')
def square(a,x,y,fill='white'):a.add(f'<rect x="{x-32}" y="{y-32}" width="64" height="64" fill="{fill}" stroke="{INK}" stroke-width="3"/>')
square(a,510,245);a.circle(870,245,32);a.line(542,245,838,245);a.line(690,245,690,365);a.line(470,365,910,365)
for x in [470,910]:a.line(x,365,x,470)
square(a,470,502,INK);a.circle(910,502,32)
a.label('A',420,170,'Aa',510,245);a.label('B',990,170,'Aa',870,245);a.label('C',340,590,'aa',470,502);a.label('D',1070,590,'AA or Aa',910,502)
a.text(700,690,'Filled = affected · square = male · circle = female · fully penetrant autosomal recessive model',20,MUTED,'middle');a.save()
a=Art(17,'linkage','Linked allele arrangements and gamete classes',12,'The starting arrangement is AB/ab. Without crossing over, AB and ab are parental combinations; Ab and aB are recombinants.')
a.text(280,195,'Starting homologues',26,INK,'middle')
for y,c,t1,t2 in [(300,BLUE,'A','B'),(465,ORANGE,'a','b')]:
 a.line(105,y,495,y,c,18);a.text(165,y-25,t1,30,c,'middle');a.text(435,y-25,t2,30,c,'middle')
a.arrow(545,380,715,380)
for i,(xx,yy,txt,ans)in enumerate([(815,280,'AB','Parental gamete'),(1150,280,'ab','Parental gamete'),(815,505,'Ab','Recombinant gamete'),(1150,505,'aB','Recombinant gamete')]):
 a.box(xx-135,yy-50,270,130,txt,size=32);a.label(chr(65+i),xx,yy+130,ans)
a.save()
a=Art(17,'map','A short-interval chromosome map',13,'The schematic positions are 0, 8 and 20 cM. The middle locus is 8 cM from the left locus and 12 cM from the right locus; the total map interval is 20 cM.',subtitle='Constructed short-interval teaching example — not physical base-pair distances')
a.line(130,360,1270,360,TEAL,10)
for key,x,num in [('A',170,0),('B',594,8),('C',1230,20)]:a.line(x,335,x,385,INK,4);a.label(key,x,270,f'Locus at {num} cM',x,360);a.text(x,430,str(num)+' cM',28,INK,'middle')
a.line(170,530,594,530,BLUE,4);a.line(594,600,1230,600,ORANGE,4);a.label('D',382,550,'8 cM');a.label('E',912,620,'12 cM');a.save()


# Current SVGs are regenerated. Keep source-figure records and retain stable mappings.
root=R
p=root/'authoring/diagram-review.json';old=json.loads(p.read_text());new=MEDIA[17];ids={x['id']for x in new};p.write_text(json.dumps([x for x in old if x['id']not in ids]+new,ensure_ascii=False,indent=2))
(root/'authoring/label-diagrams.json').write_text(json.dumps(LABELS[17],ensure_ascii=False,indent=2))
print('Regenerated reviewed geometry for Chapter',17,'; reconcile any intentional answer-map edit with course-config.json before rebuilding.')
