// Focused Build check: migrated response history, new feedback, saving and completion.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),c=require('cheerio');
const {chromium}=require('playwright');const w=path.resolve(__dirname,'../../../workspace');
const $=c.load(fs.readFileSync(path.join(w,'index.html'),'utf8')),before=require('./before.json');
const clean=x=>x.replace(/^\.\//,'');
assert.deepEqual($('video').map((i,e)=>clean($(e).attr('src')||$(e).find('source').attr('src'))).get().sort(),before.videos.map(clean).sort());
for(const [name,hash]of Object.entries(before.pdfHashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(w,'assets/resources',name))).digest('hex'),hash);
const ids=$('[id]').map((i,e)=>e.attribs.id).get();assert.equal(new Set(ids).size,ids.length);assert.equal($('article[data-lesson-id]').length,40);
for(const id of ['ce1-03','fl3-04']){assert.equal($('#'+id+' [data-signoff]').length,4);assert.equal($('#'+id+' [data-lesson-evidence]').attr('data-save-key'),id);}
const missing=[];$('video source,video[src],track,link[rel=stylesheet],script[src],a[href*="assets/resources/"]').each((i,e)=>{const u=e.attribs.src||e.attribs.href;if(u&&!fs.existsSync(path.resolve(w,u.split('#')[0])))missing.push(u);});assert.deepEqual(missing,[]);
(async()=>{const browser=await chromium.launch({headless:true});try{
const context=await browser.newContext({viewport:{width:1440,height:950}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const key='calm10-2026-draft:learning:v3';const seed={schemaVersion:3,responses:{'ce1-03':'Earlier Owen answer','guided:ce1-03:part3':'Earlier backup note','media:fl3-06:notice':'B','co1-01':'Unaffected Rowan answer'},taskVersions:{'ce1-03':'2026-09-28.astra.1','guided:ce1-03:part3':'2026-09-28.astra.1','media:fl3-06:notice':'2026-09-28.finlit.1','co1-01':'2026-09-28.astra.1'},responseHistory:{'ce1-03':[{version:'older',value:'Original old answer',prompt:'Original old wording'}]},completions:{}};
await page.goto('http://127.0.0.1:4189/index.html#ce1-03');await page.evaluate(([k,s])=>localStorage.setItem(k,JSON.stringify(s)),[key,seed]);await page.reload();await page.waitForTimeout(550);
let saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(saved.responses['ce1-03'],'');assert.equal(saved.responses['co1-01'],'Unaffected Rowan answer');assert.equal(saved.responseHistory['ce1-03'].length,2);assert(saved.responseHistory['ce1-03'][1].prompt.includes('Owen'));assert.equal(saved.responseHistory['guided:ce1-03:part3'][0].value,'Earlier backup note');assert(saved.responseHistory['media:fl3-06:notice'][0].prompt.includes('Ari'));assert(!('guided:ce1-03:part3'in saved.responses));
await page.reload();await page.waitForTimeout(200);saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(saved.responseHistory['ce1-03'].length,2);assert.equal(saved.responseHistory['guided:ce1-03:part3'].length,1);
await page.locator('#ce-b-travel').fill('80');await page.locator('#ce-b-total').fill('1930');await page.locator('[data-review-check="ce-cost"]').click();assert.match(await page.locator('#ce-cost-feedback').textContent(),/one month/);
await page.locator('#ce-b-travel').fill('800');await page.locator('#ce-b-total').fill('2650');await page.locator('[data-review-check="ce-cost"]').click();assert.match(await page.locator('#ce-cost-feedback').textContent(),/Correct/);
await page.locator('#ce-final-c').fill('1410');await page.locator('#ce-final-d').fill('2700');await page.locator('#ce-final-response').fill('Investigate C first because its listed cost and timing fit Owen. D needs the missing preparation and more money; verify availability before deciding.');for(const f of await page.locator('#ce1-03 [data-signoff]').all())await f.check();await page.locator('#ce1-03 [data-complete-lesson]').click();assert(await page.locator('.nav-link[data-page-target="ce1-03"]').evaluate(e=>e.classList.contains('lesson-complete')));
await page.reload();await page.waitForTimeout(200);assert.equal(await page.locator('#ce-b-total').inputValue(),'2650');assert(await page.locator('.nav-link[data-page-target="ce1-03"]').evaluate(e=>e.classList.contains('lesson-complete')));await page.locator('#ce-final-response').fill('Revised answer.');assert.equal(await page.locator('#ce1-03 [data-signoff]:checked').count(),0);assert.equal(await page.locator('.nav-link[data-page-target="ce1-03"]').evaluate(e=>e.classList.contains('lesson-complete')),false);
await page.goto('http://127.0.0.1:4189/index.html#fl3-04');await page.locator('#fl-run-compounding').click();assert(await page.locator('#fl-compounding-results').isVisible());await page.locator('#fl-compounding-extra').fill('9600');await page.locator('#fl-compounding-reason').selectOption('interest');await page.locator('#fl-compounding-limit').fill('Actual returns and future prices are uncertain.');await page.locator('#fl-check-compounding').click();assert.match(await page.locator('#fl-compounding-feedback').textContent(),/29,650.49/);
await page.locator('#fl-fee-difference').fill('1.04');await page.locator('#fl-fee-claim').selectOption('supported');await page.locator('#fl-fee-explain').fill('Both returns are model assumptions.');await page.locator('#fl-check-fee').click();assert.match(await page.locator('#fl-fee-feedback').textContent(),/Correct/);
// Optional work must not gate required completion; explicitly empty it.
await page.locator('#fl-compounding-extra').fill('');await page.locator('#fl-compounding-limit').fill('');await page.locator('#fl-compounding-reason').selectOption('');
for(const [id,v]of Object.entries({'fl-final-price':'252','fl-final-gap':'4','fl-final-response':'Buy the used set for $226 before the deadline, leaving $22. It meets the requirement but has cosmetic wear.'}))await page.locator('#'+id).fill(v);await page.locator('#fl-final-choice').selectOption('used');for(const f of await page.locator('#fl3-04 [data-signoff]').all())await f.check();await page.locator('#fl3-04 [data-complete-lesson]').click();assert(await page.locator('.nav-link[data-page-target="fl3-04"]').evaluate(e=>e.classList.contains('lesson-complete')));
await page.goto('http://127.0.0.1:4189/index.html#fl2-01');await page.locator('#fl2-01-finlit-inquiry summary').first().click();await page.locator('#borrow-cost-difference').fill('36.08');await page.locator('[data-finlit-number]').click();assert.match(await page.locator('#borrow-cost-feedback').textContent(),/Yes/);
await page.goto('http://127.0.0.1:4189/index.html#fl4-02');await page.locator('input[name="fl4-02-card-d"][value="1"]').check();assert.match(await page.locator('input[name="fl4-02-card-d"]').first().locator('xpath=ancestor::fieldset').textContent(),/Yes/);
await page.goto('http://127.0.0.1:4189/index.html#fl4-05');await page.locator('#fl4-05-cra-reading summary').first().click();await page.locator('input[name="fl4-05-cra-action"][value="1"]').check();await page.waitForTimeout(450);await page.reload();await page.locator('#fl4-05-cra-reading summary').first().click();assert(await page.locator('input[name="fl4-05-cra-action"][value="1"]').isChecked());
assert.deepEqual(errors,[]);
// Changed-area visual captures only, not full-course responsive certification.
for(const [name,width,height,id,target]of [['routes-desktop',1440,950,'ce1-03','ce1-03-documents'],['growth-mobile',390,844,'fl3-04','fl3-04-compounding'],['borrowing-desktop',1440,950,'fl2-01','fl2-01-finlit-inquiry'],['fraud-mobile',390,844,'fl4-02','fl4-02-finlit-classify'],['recovery-desktop',1440,950,'fl4-05','fl4-05-cra-reading']]){
 await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:4189/index.html#'+id);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(350);if(['fl2-01','fl4-05'].includes(id))await page.locator('#'+target).evaluate(e=>e.open=true);await page.locator('#'+target).evaluate(e=>window.scrollTo({top:e.getBoundingClientRect().top+window.scrollY-110,behavior:'instant'}));await page.waitForTimeout(100);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,name+' overflow');await page.screenshot({path:path.join(__dirname,name+'.png')});
}
console.log('PASS: 40 lessons; 23 media placements preserved; PDFs byte-identical; local dependencies and unique IDs; historical migration + repeat load; focused feedback; saving/completion/reopen; optional work not required; five changed-area viewport checks.');
fs.writeFileSync(path.join(__dirname,'check-result.json'),JSON.stringify({passed:true,at:new Date().toISOString(),lessons:40,videos:23,pdfCount:Object.keys(before.pdfHashes).length,consoleErrors:errors,scope:'Focused Build check; full rollout deferred'},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
