import {load} from 'cheerio';
import type {TopicCourseInputs} from './pilot2-render-course.js';
import type {TopicRenderInputs} from './pilot2-render-topic.js';
import type {TopicLayout} from './topic-layout.js';
import {topicHtml as h} from './pilot2-render-common.js';
/** Adapt A's hub hierarchy without replacing scientific work or its saved IDs. */
type HubInputs=Pick<TopicCourseInputs,'models'|'seminar'|'textbookGroups'|'videos'|'sourceVideos'>&{topic:TopicRenderInputs<TopicLayout>};
export function adaptTopicHubs(input:HubInputs,pages:Map<string,{title:string;html:string}>,options:{preserveSources?:boolean;standaloneWork?:boolean;omitDiploma?:boolean}={}){
 const u=input.topic.state.unit.toLowerCase(),routeLink=(id:string,label:string)=>`<a class="text-link" href="#${h(id)}" data-page-target="${h(id)}">${h(label)}</a>`;
 for(const [id,page]of pages){const $=load(page.html,null,false),body=$('.p2-topic').first(),header=body.children('.page-header'),minutes=input.topic.timing?.routes.find(r=>r.routeId===id)?.requiredMinutes;
  if(id.endsWith('-practice')||id.endsWith('-diploma-challenge')){
   const questions=body.find('.p2-practice'),count=questions.length,required=!id.endsWith('challenge');
   header.append(`<dl class="lesson-meta">${minutes?`<div><dt>Required time</dt><dd>${minutes} minutes</dd></div>`:''}<div><dt>Questions</dt><dd>${count} ${required?'core':'optional'} items</dd></div></dl>`);
   body.find('.textbook-review-support').each((_i,n)=>{const panel=$(n),guide=panel.children('details'),group=input.textbookGroups.find(g=>`${g.id}-practice`===panel.attr('id'));if(!group)return;panel.prepend('<p class="section-label">Textbook reinforcement</p>');guide.attr('data-p2-textbook-group-guide','').attr('hidden','');guide.children('summary').text('Check your work');guide.before(`<p>Source questions: ${group.items.map(q=>h(q.questionNumber)).join(', ')}.</p><p class="textbook-review-links">${[...new Map(group.items.map(q=>[q.printedPage,q])).values()].map(q=>`<a href="${h(q.chapterPdf)}#page=${q.physicalPage}" target="_blank" rel="noopener">Open textbook p. ${q.printedPage}</a>`).join(' · ')}</p><div class="textbook-review-reveal"><button class="button button--secondary" type="button" data-p2-textbook-group-attempt aria-expanded="false">I attempted the textbook review</button><span>The answer guide opens after you confirm an attempt.</span></div>`);});
   const wrapper=body.children('.collection-section');wrapper.children().unwrap();
   if(questions.length){questions.first().before(`<section class="course-question-intro"><p class="section-label">Course practice</p><h2 id="${id}-questions" tabindex="-1">${count} ${required?'course':'optional challenge'} questions</h2><p>${required?'Attempt each question, use the feedback, and revise before moving on.':'These questions do not affect required completion.'}</p></section>`);questions.wrapAll('<div class="practice-stack"></div>');}
   if(required)body.append(`<footer class="lesson-completion"><div><p class="section-label">${id.includes('final')?'Final':'Chapter'} check</p><p>Attempt all ${count} core questions. Your saved attempts update completion automatically.</p></div><strong data-pilot2-route-status="${id}" role="status">In progress</strong></footer>`);
  }
  if(id===input.seminar.id){header.find('h1').text('Review Seminar');header.append(`<p>Explain the mechanism, use the evidence, and state a limit before Final Practice.</p>${minutes?`<dl class="lesson-meta"><div><dt>Required time</dt><dd>${minutes} minutes</dd></div><div><dt>Advanced extension</dt><dd>${input.seminar.optionalExtension.minutes} optional minutes</dd></div></dl>`:''}`);body.children('.collection-section').children().unwrap();header.after('<section class="review-orientation"><p class="section-label">Review method</p><h2>Explain before you compare</h2><ol class="review-steps"><li>Read the supplied case and identify the changed variable.</li><li>Write your explanation using the criteria.</li><li>Compare with the course model and revise your reasoning.</li><li>Save the three responses to your Process Collection.</li></ol></section>');body.children('.p2-writing').addClass('seminar-session').wrapAll('<div class="seminar-sessions"></div>');body.children('details').addClass('advanced-learning');body.children('button[data-pilot2-collect]').addClass('button').wrap('<footer class="lesson-completion"></footer>');}
  if(id.endsWith('-advanced')){const chapters=[...new Set(input.topic.contract.topics.map(t=>t.chapter))];const intro=header.clone();intro.append(`<p class="advanced-progress"><strong data-p2-advanced-progress>0 of ${input.topic.contract.topics.reduce((n,t)=>n+t.parts.length,0)}</strong> complete</p>`);body.empty().append(intro);body.append('<section class="advanced-index-intro"><h2>Choose a deeper-thinking block</h2><p>Open a block in its lesson, work through the evidence, and mark it complete. This checklist is separate from required course progress.</p></section>');body.append(`<div class="advanced-index">${chapters.map(ch=>`<section class="advanced-index-chapter"><h2>Chapter ${ch}</h2>${input.topic.contract.topics.filter(t=>t.chapter===ch).map(t=>`<section class="advanced-index-lesson"><h3>${h(t.title)}</h3><ol>${t.parts.map(part=>{const a=input.topic.instruction.parts.find(p=>p.partId===part.id)!.advanced;const min=input.topic.timing?.optionalAllocations.find(x=>x.id===a.id)?.minutes;return `<li><div class="advanced-index-copy"><strong>${h(a.title)}</strong>${min?`<span>${min} minutes</span>`:''}</div><div class="advanced-index-actions"><label><input type="checkbox" data-pilot2-optional-flag="${h(a.id)}-complete"> <span>Completed</span></label><a href="#${h(t.id)}" data-pilot2-return-route="${h(t.id)}" data-pilot2-return-focus="${h(a.id)}">Open in lesson</a></div></li>`;}).join('')}</ol></section>`).join('')}</section>`).join('')}</div>`);}
  if(id.endsWith('-glossary')){header.find('h1').text('Glossary and Data');body.children('.collection-section').children().unwrap();body.children('label').addClass('glossary-search');body.children('dl').addClass('glossary-list');body.append('<section class="data-reference"><h2>Unit data reminders</h2><table><caption>Reading evidence in this unit</caption><tbody><tr><th>Units and scales</th><td>Use the units, axis labels and legends supplied with each dataset.</td></tr><tr><th>Model limits</th><td>Distinguish a model prediction from an observed result.</td></tr><tr><th>Source and scope</th><td>Read the provenance and limitations beside each case.</td></tr></tbody></table></section>');}
  if(id.endsWith('-video-library')&&!input.videos.length&&!input.sourceVideos?.length){body.empty().append(`<header class="page-header"><p class="eyebrow">Resources</p><h1>Video Library</h1><p>Use the complete illustrated walkthroughs for this unit. External clips have not been selected; each connected lesson contains its own sense-making checkpoint.</p></header><div class="video-library-layout" data-p2-hub><nav class="video-playlist" aria-label="Walkthrough topics">${input.topic.contract.topics.map(t=>`<button type="button" data-p2-panel-target="${t.id}-library-walkthrough">${h(t.title)}<small>Chapter ${t.chapter} · illustrated pathway</small></button>`).join('')}</nav><div class="video-reader">${input.topic.contract.topics.map(t=>{const framing=input.topic.framing.topics.find(f=>f.topicId===t.id)!;const figure=input.topic.figures.find(f=>f.id===`${t.parts[0].id}-figure`);return `<article id="${t.id}-library-walkthrough" data-p2-panel hidden><p class="eyebrow">Chapter ${t.chapter}</p><h2>${h(t.title)}</h2><div class="concept-summary"><h3>Concept focus</h3><p>${h(framing.learningGoal)}</p></div>${figure?`<img class="p2-library-figure" src="${h(figure.src)}" alt="${h(figure.alt)}">`:''}<p class="resource-links"><a href="#${t.id}" data-pilot2-return-route="${t.id}" data-pilot2-return-focus="${t.id}-walkthrough">Open the illustrated walkthrough</a><a href="#${t.id}" data-pilot2-return-route="${t.id}" data-pilot2-return-focus="${t.id}-media">Return to the lesson checkpoint</a></p></article>`;}).join('')}</div></div>`);}
  if(id.endsWith('-models')){header.append('<p>Use each model to answer one clear scientific question. Choose what to change, predict the result, test it against the model, explain the evidence, and save your investigation when it shows your thinking.</p>');header.append(`<p class="vocab-progress"><strong data-p2-model-progress>0 of ${input.models.length}</strong> investigations saved</p>`);body.find('.p2-hub-layout').addClass('model-lab-layout');const chapters=[...new Set(input.topic.contract.topics.map(t=>t.chapter))];body.find('.p2-hub-layout>nav').attr('aria-label','Lesson investigations').html(chapters.map(ch=>{const models=input.models.filter(m=>input.topic.contract.topics.find(t=>t.id===m.teachingTopicId)?.chapter===ch);return models.length?`<section><h2>Chapter ${ch}</h2>${models.map(m=>`<button type="button" data-p2-panel-target="${h(m.id)}"><span>${h(m.title)}</span><small>${h(input.topic.contract.topics.find(t=>t.id===m.teachingTopicId)!.title)}</small></button>`).join('')}</section>`:'';}).join(''));}
  page.html=$.html();
 }
 // Sources has no saved response. Give it A's own resource page; it does not add a state key.
 const textbook=pages.get(`${u}-textbook`)!,$=load(textbook.html,null,false),sources=$(`#${u}-sources`).remove();sources.removeAttr('data-p2-panel').removeAttr('hidden');const sourceHeading=sources.children('h2').remove().text();sources.children('section').addClass('source-list');if(!options.preserveSources)pages.set(`${u}-sources-and-credits`,{title:'Sources and Credits',html:`<div class="p2-topic"><header class="page-header"><p class="eyebrow">Resources</p><h1>${h(sourceHeading)}</h1><p>Curriculum guidance, class materials and local illustrations support this unit.</p></header>${$.html(sources)}</div>`});$(`[data-p2-panel-target="${u}-sources"]`).remove();
 for(const group of input.textbookGroups.filter(g=>g.textbookUnit)){const label=`Unit ${group.textbookUnit} Review`;$(`[data-p2-panel-target="${group.id}"]`).text(label);const panel=$(`#${group.id}`);panel.children('h2').text(label);panel.find('iframe').attr('title',label).attr('src',`${group.items[0].chapterPdf}#page=${group.items[0].physicalPage}`);}
 const hub=$('[data-p2-hub]');hub.removeClass('p2-hub-layout p2-textbook-layout');hub.children('nav').addClass('library-tabs').attr('role','tablist');hub.find('[data-p2-panel-target]').attr('role','tab');const select=$('<label class="library-select">Choose a chapter<select data-p2-library-select></select></label>');hub.find('[data-p2-panel-target]').each((_i,n)=>{select.find('select').append(`<option value="${$(n).attr('data-p2-panel-target')}">${h($(n).text())}</option>`);});hub.children('nav').after(select);hub.find('.p2-hub-reader').removeClass('p2-hub-reader');hub.find('[data-p2-panel]').addClass('library-panel');hub.find('.library-panel').each((_i,n)=>{const panel=$(n),title=panel.children('h2'),links=panel.children('.resource-links');title.add(links).wrapAll('<div class="library-panel-header"></div>');const href=links.find('a').first().attr('href');if(href)links.append(`<a href="${h(href.split('#')[0])}" download>Download chapter</a>`);});textbook.html=$.html();
 // Keep original activity route IDs while placing their single instances where A puts them.
 const collection=pages.get(`${u}-all-my-work`)!,$c=load(collection.html,null,false);$c('[data-p2-collection-shortcuts]').html(routeLink(`${u}-core-vocabulary`,'Work on Core Vocabulary')+routeLink(`${u}-advanced`,'Open Advanced Learning checklist')+routeLink(`${u}-models`,'Open Models and Data Lab'));
 if(!options.standaloneWork)for(const [suffix,title]of [['investigations','Investigations'],['notes','Learner-created process note']]){const id=`${u}-${suffix}`,child=pages.get(id)!,$child=load(child.html,null,false);$child('.page-header').remove();$c('[data-p2-collection-continue]').append(`<section class="collection-section continue-work"><div class="collection-heading"><div><p class="section-label">Continue your work</p><h2>${title}</h2></div>${routeLink(id,'Return to this work')}</div><div data-p2-embed-route="${id}"></div></section>`);child.html=$child.html();}collection.html=$c.html();
 if(options.omitDiploma)return;
 const final=pages.get(`${u}-final-practice`);if(!final)return;const $f=load(final.html,null,false);$f('.lesson-completion').before(`<details class="advanced-learning final-challenge"><summary><span>Diploma Challenge</span><span>${input.topic.practice.filter(p=>p.role==='challenge').length} optional questions</span></summary><div><p>These items extend your reasoning and do not affect required completion.</p>${routeLink(`${u}-diploma-challenge`,'Open optional challenge')}<div data-p2-embed-route="${u}-diploma-challenge"></div></div></details>`);final.html=$f.html();
}
