import {topicHtml as h} from './pilot2-render-common.js';
import type {TopicRenderInputs} from './pilot2-render-topic.js';
export function renderPresentationLessonHeader(topicId:string,input:TopicRenderInputs){
 const topic=input.contract.topics.find(t=>t.id===topicId)!,frame=input.framing.topics.find(t=>t.topicId===topicId)!;
 const terms=input.vocabulary.introducedTerms,extended=topic as typeof topic&{anchorTermIds?:string[];newTermIds?:string[];reusedTermIds?:string[];teacherTextbookAssignment?:string};
 const ids=extended.newTermIds??terms.filter(t=>topic.parts.some(p=>p.id===t.firstTeachingPartId)).map(t=>t.id),reused=extended.reusedTermIds??[];
 const resolve=(id:string)=>{const term=terms.find(t=>t.id===id);if(!term)throw new Error(`Missing lesson opening definition: ${id}`);return term;};
 const anchors=(extended.anchorTermIds??ids.slice(0,4)).map(resolve);
 if(extended.anchorTermIds&&anchors.length!==4)throw new Error(`Four anchor terms missing: ${topicId}`);
 const termRows=(list:string[])=>list.map(id=>{const term=resolve(id),route=input.contract.topics.find(t=>t.parts.some(p=>p.id===term.firstTeachingPartId))!.id,family=input.vocabulary.conceptFamilies.find(f=>f.termIds.includes(id));return `<div class="lesson-term-row"><div><dt>${h(term.term)}</dt><dd>${h(term.definition)}</dd></div><p><a href="#${h(route)}" data-pilot2-return-route="${h(route)}" data-pilot2-return-focus="${h(term.firstTeachingPartId)}">First use</a>${family?` · <a href="#${input.contract.unit.toLowerCase()}-core-vocabulary" data-pilot2-return-route="${input.contract.unit.toLowerCase()}-core-vocabulary" data-pilot2-return-focus="${h(family.id)}">Core Vocabulary</a>`:''}</p></div>`;}).join('');
 const time=input.timing?.routes.find(r=>r.routeId===topicId),optional=input.timing?.optionalAllocations.filter(r=>topic.parts.some(p=>r.id===p.id+'-advanced')).reduce((n,r)=>n+r.minutes,0),book=input.textbookLinks?.find(b=>b.topicId===topicId);
 return `<header class="lesson-header"><p class="eyebrow">Lesson ${input.contract.topics.indexOf(topic)+1} · Chapter ${topic.chapter}</p><h1>${h(topic.title)}</h1><p class="lesson-question">${h(frame.observableQuestion)}</p>${time?`<dl class="lesson-meta"><div><dt>Required time</dt><dd>${time.requiredMinutes} minutes</dd></div><div><dt>Advanced Learning</dt><dd>${optional??0} optional minutes</dd></div></dl>`:''}<div class="goal-strip"><div><p class="section-label">Learning goal</p><p>${h(frame.learningGoal)}</p></div><div><p class="section-label">Before you begin</p><p>${h(frame.priorKnowledgeSupport)}</p></div></div>${book?`<div class="textbook-band"><div><p class="section-label">In the textbook</p><p><strong>Chapter ${topic.chapter}</strong> · ${h(extended.teacherTextbookAssignment??'')}</p></div><a href="${h(book.pdf)}#page=${book.physicalPage}" target="_blank" rel="noopener">Open at p. ${book.printedPage}</a></div>`:''}<section class="lesson-words"><p class="section-label">Four anchor words</p><h2>Start with four words</h2><p>These four anchors will help you enter the lesson. The full list below includes the supporting terms.</p><dl>${anchors.map(t=>`<div><dt>${h(t.term)}</dt><dd>${h(t.definition)}</dd></div>`).join('')}</dl></section><details class="lesson-term-inventory"><summary>All terms used in this lesson (${ids.length+reused.length})</summary><div><section><h3>New in this lesson</h3><dl>${termRows(ids)}</dl></section>${reused.length?`<section><h3>Used again</h3><dl>${termRows(reused)}</dl></section>`:''}</div></details></header>`;
}
