import type { TopicModel } from "./pilot2-models.js";
import type { TopicStateSchema } from "./pilot2-state.js";
import type {RenderTopicInvestigation} from './pilot2-render-investigation.js';
import { renderTopicResponse } from "./pilot2-render-controls.js";
import { topicHtml as h } from "./pilot2-render-common.js";
export type RenderTopicModel=TopicModel&{title:string;predictionId:string;explanationId:string;testFlag:string;collectionFlag:string;predictionPrompt:string;explanationPrompt:string;dataProvenance:string;requiredForCompletion:boolean;requiredForScore:boolean;teachingTopicId?:string;sourceInvestigationId?:string};
export function renderTopicModel(model:RenderTopicModel,schema:TopicStateSchema,context?:{lesson?:{id:string;title:string;chapter:number};investigation?:RenderTopicInvestigation;teaching?:{observableQuestion:string;learningGoal:string;priorKnowledgeSupport:string}}) {
  if(model.requiredForCompletion||model.requiredForScore||!schema.flags[model.testFlag]||!schema.flags[model.collectionFlag]||!schema.choices[model.id]||JSON.stringify(schema.choices[model.id].values)!==JSON.stringify(model.options))throw new Error(`Model renderer contract drift: ${model.id}`);
  const investigation=context?.investigation,lesson=context?.lesson,teaching=context?.teaching,plan=investigation?.variables??{compare:model.cases.map(c=>c.label).join('; '),holdConstant:'The model’s calculation rules and stated assumptions.',observe:model.explanationPrompt};
  return `<section class="p2-model model-panel" id="${h(model.id)}" tabindex="-1" data-pilot2-model="${h(model.id)}">
  ${lesson?`<p class="section-label">Chapter ${lesson.chapter} · ${h(lesson.title)} investigation</p>`:''}<h2>${h(model.title)}</h2>
  <section class="model-orientation"><p class="model-orientation__label">Investigation question</p><h3>${h(investigation?.question??teaching?.observableQuestion??model.predictionPrompt)}</h3>${teaching?`<p><strong>What you are learning:</strong> ${h(teaching.learningGoal)}</p>`:''}<dl class="model-plan"><div><dt>What you change</dt><dd>${h(plan.compare)}</dd></div><div><dt>What stays the same</dt><dd>${h(plan.holdConstant)}</dd></div><div><dt>Evidence to examine</dt><dd>${h(plan.observe)}</dd></div></dl></section>
  ${teaching?`<section class="model-mechanism"><p class="model-stage-label">Before you investigate</p><h3>Review the base mechanism</h3><p>${h(teaching.priorKnowledgeSupport)}</p>${lesson?`<a href="#${h(lesson.id)}" data-page-target="${h(lesson.id)}">Review the explanation in ${h(lesson.title)}</a>`:''}</section>`:''}
  <div class="model-use-sequence" aria-label="Investigation sequence"><span>1. Predict</span><span>2. Test</span><span>3. Explain</span><span>4. Save</span></div>
  <section class="model-workflow-step model-workflow-step--predict"><p class="model-stage-label">Step 1</p><h3>Choose a case and make a prediction</h3><div class="model-controls" role="group" aria-label="Choose a case to investigate">${model.cases.map(item=>`<button class="button button--secondary" type="button" data-pilot2-model-case="${h(model.id)}" data-pilot2-model-case-value="${h(item.value)}" aria-pressed="false">${h(item.label)}</button>`).join('')}</div><select hidden aria-label="Selected model case" data-pilot2-model-choice="${h(model.id)}"><option value="">Choose…</option>${model.cases.map(item=>`<option value="${h(item.value)}">${h(item.label)}</option>`).join('')}</select>${renderTopicResponse(schema,model.predictionId,model.predictionPrompt,[model.testFlag,model.collectionFlag])}<div class="model-test-row"><button type="button" data-pilot2-model-test="${h(model.id)}" disabled>Test my prediction</button><p data-pilot2-model-status="${h(model.id)}" role="status">Choose a case, then write your prediction.</p></div></section>
  <section class="model-workflow-step"><p class="model-stage-label">Step 2</p><h3>Examine the evidence</h3><div class="model-empty" data-pilot2-model-empty="${h(model.id)}"><h3>No result yet</h3><p>Your evidence will appear after you choose a case, write a prediction, and select <strong>Test my prediction</strong>.</p></div><div class="model-output" data-pilot2-model-result="${h(model.id)}" hidden></div><p class="activity-note">${h(model.dataProvenance)}</p></section>
  <section class="model-workflow-step model-workflow-step--explain"><p class="model-stage-label">Step 3</p><h3>Explain what the evidence means</h3>${renderTopicResponse(schema,model.explanationId,model.explanationPrompt,[model.collectionFlag])}</section>
  <section class="model-workflow-step model-workflow-step--save"><p class="model-stage-label">Step 4</p><h3>Save the investigation you can explain</h3><p>Your saved record includes your prediction, tested case, model evidence and explanation.</p><div class="model-save-row"><button type="button" data-pilot2-collect="${h(model.collectionFlag)}" data-pilot2-requires="${h(model.predictionId)} ${h(model.explanationId)}" data-pilot2-required-flag="${h(model.testFlag)}" disabled>Save my investigation to Process Collection</button>${lesson?`<a href="#${h(lesson.id)}" data-page-target="${h(lesson.id)}">Return to ${h(lesson.title)}</a>`:''}</div><p data-pilot2-collection-status="${h(model.collectionFlag)}" role="status"></p></section></section>`;
}
