import type {TopicContract} from './pilot2-contract.js';
import type {TopicMediaManifest} from './pilot2-media.js';
import {topicHtml as h} from './pilot2-render-common.js';
export type SourceVideo={videoId:string;title:string;provider:string;chapter:number;metadataReachable:boolean;sourceLabels:string[];topics:{id:string;title:string;walkthroughId:string;checkpointId:string}[]};
export type SourceVideoMetadata={checks:{videoId:string;status:string;title?:string;provider?:string}[]};
/** User-requested original PowerPoint resources. This never selects or certifies a reviewed clip. */
export function selectSourceVideos(manifest:TopicMediaManifest&{sourceLibrary?:{enabled:boolean;authorityEvidence:string}},metadata:SourceVideoMetadata,contract:TopicContract):SourceVideo[]{
 if(!manifest.sourceLibrary?.enabled)return[];
 if(!manifest.sourceLibrary.authorityEvidence.startsWith('projects/resources/biology30-production/v1/pilot2/source-review/'))throw Error('Missing source-library authority');
 return [...manifest.youtubeCandidates].sort((a,b)=>String((a.sourceOccurrences[0] as {slideId?:string}).slideId).localeCompare(String((b.sourceOccurrences[0] as {slideId?:string}).slideId),undefined,{numeric:true})).map(candidate=>{const evidence=metadata.checks.find(c=>c.videoId===candidate.videoId);if(!evidence||!candidate.sourceOccurrences.length||candidate.required||candidate.providerFilesDownloaded||!candidate.teachingTopicIds.length)throw Error('Source video lost its source evidence or optional boundary');const topics=candidate.teachingTopicIds.map(id=>{const topic=contract.topics.find(t=>t.id===id);if(!topic)throw Error('Source video lost its lesson mapping');return{id,title:topic.title,walkthroughId:`${id}-walkthrough`,checkpointId:`${id}-media`};});const chapter=Number((candidate.sourceOccurrences[0] as {slideId?:string}).slideId?.match(/^deck-(\d+)-slide-/)?.[1])||contract.topics.find(t=>t.id===topics[0].id)!.chapter;
 const sourceLabels=candidate.sourceOccurrences.map(o=>{const slide=(o as {slideId?:string}).slideId;return slide?slide.replace(/^deck-/,'Chapter ').replace('-slide-',' · slide '):`Chapter ${chapter} PowerPoint`;});
 return {videoId:candidate.videoId,title:evidence.title??(candidate as {titleFromMetadata?:string}).titleFromMetadata??`PowerPoint video · ${sourceLabels[0]}`,provider:evidence.provider??'YouTube',chapter,metadataReachable:evidence.status==='metadata-reachable',sourceLabels,topics};});
}
export function renderSourceVideo(video:SourceVideo,instance:string){return `<section class="source-video" data-p2-source-video="${h(video.videoId)}" data-p2-source-preview="${video.metadataReachable}"><h3>${h(video.title)}</h3><p class="video-meta">${h(video.provider)} · ${video.sourceLabels.map(h).join(' · ')}</p><div class="video-stage" data-p2-source-video-host id="${h(instance)}">${video.metadataReachable?'<p>The player loads when this video is selected.</p>':'<p>The video preview is unavailable. The original source link is retained below.</p>'}</div><p class="resource-links"><a href="https://www.youtube.com/watch?v=${h(video.videoId)}" target="_blank" rel="noopener noreferrer">Watch on YouTube</a>${video.topics.map(t=>`<a href="#${h(t.id)}" data-pilot2-return-route="${h(t.id)}" data-pilot2-return-focus="${h(t.walkthroughId)}">Illustrated walkthrough: ${h(t.title)}</a>`).join('')}</p></section>`;}
export function renderSourceVideoLibrary(videos:SourceVideo[]){const chapters=[...new Set(videos.map(v=>v.chapter))];return `<div class="p2-topic"><header class="page-header"><p class="eyebrow">Resources</p><h1>Video Library</h1><p>Find the videos linked in your class PowerPoints. Choose a title to open its player, or return to the connected lesson and illustrated walkthrough.</p></header><div class="video-library-layout" data-p2-hub><nav class="video-playlist" aria-label="Video topics">${chapters.map(ch=>`<section><h2>Chapter ${ch}</h2>${videos.filter(v=>v.chapter===ch).map(v=>`<button type="button" data-p2-panel-target="source-library-${h(v.videoId)}">${h(v.title)}<small>${h(v.provider)}</small></button>`).join('')}</section>`).join('')}</nav><div class="video-reader">${videos.map(v=>`<article id="source-library-${h(v.videoId)}" data-p2-panel hidden><p class="eyebrow">Chapter ${v.chapter}</p>${renderSourceVideo(v,`source-player-${v.videoId}`)}<div class="concept-summary"><h3>Connected lessons</h3>${v.topics.map(t=>`<p><a href="#${h(t.id)}" data-page-target="${h(t.id)}">${h(t.title)}</a></p>`).join('')}</div></article>`).join('')}</div></div></div>`;}
/** Native provider controls; hidden players are removed to stop playback. No playback claims from iframe load. */
export function mountSourceVideos(root:HTMLElement){const items=[...root.querySelectorAll<HTMLElement>('[data-p2-source-video]')];let frame=0;
 const refresh=()=>{for(const item of items){const host=item.querySelector<HTMLElement>('[data-p2-source-video-host]')!,box=item.getBoundingClientRect(),visible=!item.closest('[hidden]')&&box.width>0&&box.bottom>0&&box.top<innerHeight;const player=host.querySelector('iframe');if(!visible){player?.remove();continue;}if(item.dataset.p2SourcePreview!=='true')continue;if(!navigator.onLine){host.textContent='You are offline. Use the illustrated walkthrough linked below.';continue;}if(player)continue;const id=item.dataset.p2SourceVideo!;if(!/^[A-Za-z0-9_-]{11}$/.test(id))throw Error('Invalid source video ID');const iframe=root.ownerDocument.createElement('iframe');iframe.src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=0&rel=0&playsinline=1&cc_load_policy=1`;iframe.title=item.querySelector('h3')!.textContent!;iframe.allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';host.replaceChildren(iframe);}};
 const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(refresh);};root.addEventListener('click',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('online',schedule);window.addEventListener('offline',schedule);schedule();return{dispose(){cancelAnimationFrame(frame);root.removeEventListener('click',schedule);window.removeEventListener('hashchange',schedule);window.removeEventListener('scroll',schedule);window.removeEventListener('online',schedule);window.removeEventListener('offline',schedule);items.forEach(i=>i.querySelector('iframe')?.remove());}};}
