import type {TopicState,TopicStateSchema} from './pilot2-state.js';
import type {TopicControlSave} from './pilot2-controls-runtime.js';
/** Unit A navigation and reader interactions adapted to the existing B/C/D state. */
export function mountTopicPresentation(root:HTMLElement,state:TopicState,schema:TopicStateSchema,controls:{saveDraft():TopicControlSave}){
 const doc=root.ownerDocument,host=doc.defaultView!,pages=[...root.querySelectorAll<HTMLElement>('.course-page')],sidebar=root.querySelector<HTMLElement>('.sidebar')!,scrim=root.querySelector<HTMLElement>('[data-p2-scrim]')!,menu=root.querySelector<HTMLButtonElement>('[data-p2-menu]')!;
 const search=root.querySelector<HTMLInputElement>('[data-p2-vocabulary-search]'),filter=root.querySelector<HTMLSelectElement>('[data-p2-vocabulary-filter]'),familyButtons=[...root.querySelectorAll<HTMLButtonElement>('[data-p2-family-target]')],familyPanels=[...root.querySelectorAll<HTMLElement>('[data-p2-family-panel]')];
 let selectedFamily=state.vocabularyActiveId??'',saveTimer:ReturnType<typeof setTimeout>|undefined;
 const closeMenu=()=>{sidebar.classList.remove('is-open');doc.body.classList.remove('nav-open');scrim.hidden=true;menu?.setAttribute('aria-expanded','false');};
 function vocabulary(){
  const advanced=[...root.querySelectorAll<HTMLInputElement>('[data-pilot2-optional-flag]')];advanced.forEach(n=>n.checked=state.flags.includes(n.dataset.pilot2OptionalFlag!));const advancedIds=[...new Set(advanced.map(n=>n.dataset.pilot2OptionalFlag!))];const advancedProgress=root.querySelector<HTMLElement>('[data-p2-advanced-progress]');if(advancedProgress)advancedProgress.textContent=`${advancedIds.filter(id=>state.flags.includes(id)).length} of ${advancedIds.length}`;const models=[...root.querySelectorAll<HTMLElement>('[data-pilot2-model]')];const modelProgress=root.querySelector<HTMLElement>('[data-p2-model-progress]');if(modelProgress)modelProgress.textContent=`${models.filter(n=>state.flags.includes(n.querySelector<HTMLElement>('[data-pilot2-collect]')?.dataset.pilot2Collect??'')).length} of ${models.length}`;
  const query=search?.value.trim().toLowerCase()??'',view=filter?.value??'all';
  for(const button of familyButtons){const learned=state.visited.includes(button.dataset.p2FamilyRoute!);button.hidden=!(button.dataset.p2FamilySearch??'').includes(query)||(view==='learned'&&!learned)||(view!=='learned'&&view!=='all'&&button.dataset.p2FamilyChapter!==view);const label=button.querySelector<HTMLElement>('[data-p2-term-state]');if(label&&learned)label.textContent='Learned';}
  const visible=familyButtons.filter(b=>!b.hidden);if(!visible.some(b=>b.dataset.p2FamilyTarget===selectedFamily))selectedFamily=visible[0]?.dataset.p2FamilyTarget??'';
  familyButtons.forEach(button=>{button.classList.toggle('active',button.dataset.p2FamilyTarget===selectedFamily);button.setAttribute('aria-pressed',String(button.dataset.p2FamilyTarget===selectedFamily));});
  familyPanels.forEach(panel=>{panel.hidden=panel.dataset.p2FamilyPanel!==selectedFamily;const learned=state.visited.includes(panel.dataset.p2UnlockRoute!);panel.querySelector<HTMLElement>('[data-p2-family-locked]')!.hidden=learned;panel.querySelector<HTMLElement>('[data-p2-family-content]')!.hidden=!learned;});
  const empty=root.querySelector<HTMLElement>('[data-p2-vocabulary-empty]');if(empty)empty.hidden=visible.length>0;
  root.querySelectorAll<HTMLButtonElement>('[data-p2-choose-family]').forEach(b=>{const selected=state.frayerChoices.includes(b.dataset.p2ChooseFamily!);b.disabled=selected;b.textContent=selected?'Selected for Frayer':'Choose this concept';});
  const progress=root.querySelector<HTMLElement>('[data-p2-vocabulary-progress]');if(progress)progress.textContent=`${[...schema.families.fixed,...state.frayerChoices].filter(id=>state.flags.includes(id+'-collected')).length} of 8`;
 }
 function openPanel(id:string){const panel=root.querySelector<HTMLElement>(`#${CSS.escape(id)}`);if(!panel)return;const hub=panel.closest<HTMLElement>('[data-p2-hub]');if(!hub)return;hub.querySelectorAll<HTMLElement>('[data-p2-panel]').forEach(p=>p.hidden=p.id!==id);const select=hub.querySelector<HTMLSelectElement>('[data-p2-library-select]');if(select)select.value=id;hub.querySelectorAll<HTMLElement>('[data-p2-panel-target]').forEach(b=>{b.classList.toggle('active',b.dataset.p2PanelTarget===id);b.setAttribute('aria-pressed',String(b.dataset.p2PanelTarget===id));if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.p2PanelTarget===id));});}
 function reveal(target:HTMLElement){const family=target.closest<HTMLElement>('[data-p2-family-panel]');if(family){selectedFamily=family.id;state.vocabularyActiveId=selectedFamily;if(filter)filter.value='all';if(search)search.value='';vocabulary();}const panel=target.closest<HTMLElement>('[data-p2-panel]');if(panel)openPanel(panel.id);}
 function navigate(){let id='';try{id=decodeURIComponent(host.location.hash.slice(1));}catch{}if(!pages.some(p=>p.id===id))id=state.route.endsWith('-overview')?'overview':state.route;if(!pages.some(p=>p.id===id))id='overview';const current=pages.find(p=>p.id===id)!;pages.forEach(p=>p.hidden=!(p===current||p.contains(current)||(current.contains(p)&&p.hasAttribute('data-p2-embedded'))));for(let parent=current.parentElement;parent;parent=parent.parentElement)if(parent instanceof HTMLDetailsElement)parent.open=true;root.querySelectorAll<HTMLElement>('.nav-link').forEach(a=>{const active=a.dataset.pageTarget===id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});closeMenu();host.scrollTo(0,0);vocabulary();}
 function click(event:Event){const target=event.target instanceof Element?event.target:null;if(!target)return;
  const bookLink=target.closest<HTMLElement>('[data-p2-open-book]');if(bookLink){const panel=root.querySelector<HTMLElement>(`#${CSS.escape(bookLink.dataset.p2OpenBook!)}`),frame=panel?.querySelector<HTMLIFrameElement>('[data-p2-book-base]'),page=Number(bookLink.dataset.p2BookPage);if(!frame||!Number.isInteger(page)||page<1)throw Error('Invalid textbook link');frame.src=frame.dataset.p2BookBase+`#page=${page}&zoom=page-width`;const location=panel!.querySelector<HTMLElement>('[data-p2-book-location]');if(location)location.textContent=`Opened from ${bookLink.textContent?.trim()}. PDF page ${page}.`;const fullScreen=panel!.querySelector<HTMLAnchorElement>('.resource-links a:not([download])');if(fullScreen)fullScreen.href=frame.src;}
  const bookGroup=target.closest<HTMLButtonElement>('[data-p2-textbook-group-attempt]');if(bookGroup){const panel=bookGroup.closest<HTMLElement>('.textbook-review-support')!,guide=panel.querySelector<HTMLDetailsElement>('[data-p2-textbook-group-guide]')!;const open=guide.hidden;guide.hidden=!open;guide.open=open;bookGroup.setAttribute('aria-expanded',String(open));bookGroup.textContent=open?'Hide answer guide':'I attempted the textbook review';if(open)panel.querySelectorAll<HTMLButtonElement>('[data-pilot2-textbook-attempt]').forEach(button=>button.click());return;}
  const family=target.closest<HTMLButtonElement>('[data-p2-family-target]');if(family){selectedFamily=family.dataset.p2FamilyTarget!;state.vocabularyActiveId=selectedFamily;controls.saveDraft();vocabulary();familyPanels.find(p=>p.id===selectedFamily)?.querySelector<HTMLElement>('h2')?.focus();return;}
  const panel=target.closest<HTMLElement>('[data-p2-panel-target]');if(panel){openPanel(panel.dataset.p2PanelTarget!);return;}
  const choice=target.closest<HTMLButtonElement>('[data-p2-choose-family]');if(choice){const slot=state.frayerChoices.length<2?state.frayerChoices.length:-1,status=root.querySelector<HTMLElement>('[data-pilot2-frayer-status]');if(slot<0){root.querySelector<HTMLDetailsElement>('.p2-family-choices')!.open=true;if(status){status.textContent='Both learner choices are in use. Keep a copy and clear a chosen family before replacing it.';status.scrollIntoView({block:'center'});}return;}const select=root.querySelector<HTMLSelectElement>(`[data-pilot2-frayer-choice="${slot}"]`)!;select.value=choice.dataset.p2ChooseFamily!;select.dispatchEvent(new Event('change',{bubbles:true}));vocabulary();return;}
  if(target.closest('[data-p2-menu]')){const open=!sidebar.classList.contains('is-open');sidebar.classList.toggle('is-open',open);doc.body.classList.toggle('nav-open',open);scrim.hidden=!open;menu.setAttribute('aria-expanded',String(open));return;}
  if(target.closest('[data-p2-scrim]')){closeMenu();menu.focus();return;}
  const collapse=target.closest<HTMLButtonElement>('[data-p2-collapse]');if(collapse){const collapsed=doc.body.classList.toggle('sidebar-collapsed');collapse.setAttribute('aria-expanded',String(!collapsed));collapse.setAttribute('aria-label',collapsed?'Expand course navigation':'Collapse course navigation');return;}
  if(target.closest('[data-p2-save-exit]')){controls.saveDraft();return;}
  const link=target.closest<HTMLElement>('[data-page-target]');if(link&&!target.closest('[data-pilot2-return-route]')){const id=link.dataset.pageTarget!;if(!pages.some(p=>p.id===id))return;event.preventDefault();if(host.location.hash===`#${id}`)navigate();else host.location.hash=id;}
 }
 const librarySelect=root.querySelector<HTMLSelectElement>('[data-p2-library-select]');const libraryChange=()=>{if(librarySelect)openPanel(librarySelect.value);};librarySelect?.addEventListener('change',libraryChange);
 const revealEvent=(event:Event)=>{const target=(event as CustomEvent<HTMLElement>).detail;if(target)reveal(target);};
 const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&sidebar.classList.contains('is-open')){closeMenu();menu.focus();}};
 const stateChange=()=>{vocabulary();const toast=root.querySelector<HTMLElement>('[data-pilot2-save-status]');if(toast?.textContent){toast.classList.add('p2-show-save');clearTimeout(saveTimer);saveTimer=setTimeout(()=>toast.classList.remove('p2-show-save'),5000);}};
 root.querySelectorAll<HTMLElement>('[data-p2-hub]').forEach(hub=>{const first=hub.querySelector<HTMLElement>('[data-p2-panel]');if(first)openPanel(first.id);});
 root.addEventListener('click',click);root.addEventListener('pilot2-reveal-target',revealEvent);root.addEventListener('pilot2-state-change',stateChange);root.addEventListener('pilot2-draft-change',stateChange);host.addEventListener('hashchange',navigate);doc.addEventListener('keydown',key);search?.addEventListener('input',vocabulary);filter?.addEventListener('change',vocabulary);navigate();
 return{dispose(){librarySelect?.removeEventListener('change',libraryChange);clearTimeout(saveTimer);closeMenu();root.removeEventListener('click',click);root.removeEventListener('pilot2-reveal-target',revealEvent);root.removeEventListener('pilot2-state-change',stateChange);root.removeEventListener('pilot2-draft-change',stateChange);host.removeEventListener('hashchange',navigate);doc.removeEventListener('keydown',key);search?.removeEventListener('input',vocabulary);filter?.removeEventListener('change',vocabulary);}};
}
