import type {TopicLayout} from './topic-layout.js';
import type {TopicStateSchema} from './pilot2-state.js';
import type {GraphWork} from './pilot2-graph-work.js';
import {topicHtml as h,renderTopicDataset,type TopicDataset} from './pilot2-render-common.js';
import {renderTopicWritingActivity} from './pilot2-render-controls.js';
import {renderTopicTeachingLink} from './pilot2-render-textbook.js';
import {renderTopicFigure,type TopicFigure} from './pilot2-render-topic.js';
export type RenderTopicInvestigation={id:string;title:string;question:string;sourceKind:string;variables:{compare:string;observe:string;holdConstant:string};dataset:TopicDataset&{habitatAreaSquareMetres?:number;separateDemographicScenario?:Record<string,number>};prediction:string;procedure:string[];expected:string;limitations:string[];coreSkillPartId:string;investigationExtensionRequired:boolean;collaborationEvidence:string;responseFields:{id:string;label:string;prompt:string;modelResponse:string;comparisonPolicy:string;attemptBeforeGuide:boolean}[];materialFiles:{path:string;sha256:string;role:string}[];suppliedCodonKey?:Record<string,string>;graphExercise?:{responseId:string;requiredForInvestigationExtension:boolean}};
export function renderTopicInvestigation(item:RenderTopicInvestigation,contract:TopicLayout,schema:TopicStateSchema,graphs:GraphWork[],materials:{sourcePath:string;figure:TopicFigure}[]) {
  if(item.investigationExtensionRequired||!schema.flags[`${item.id}-saved`]||item.responseFields.length!==4||item.responseFields.some(field=>!field.attemptBeforeGuide))throw new Error(`Investigation renderer contract drift: ${item.id}`);
  const figures=item.materialFiles.filter(file=>/\.(svg|png|jpe?g|webp)$/i.test(file.path)).map(file=>{const figure=materials.find(binding=>binding.sourcePath===file.path)?.figure;if(!figure||figure.sha256!==file.sha256)throw new Error(`Missing exact investigation material: ${file.path}`);return renderTopicFigure(figure,`-${item.id}`);}).join('');
  const scenario=item.dataset.separateDemographicScenario,scenarioLabels:Record<string,string>={initialN:'Initial population (individuals)',births:'Births (individuals)',immigration:'Immigration (individuals)',deaths:'Deaths (individuals)',emigration:'Emigration (individuals)',days:'Interval (days)'};
  let graphLink='';
  if(item.graphExercise&&!item.responseFields.some(field=>field.id===item.graphExercise!.responseId)){
    const graph=item.graphExercise.responseId,topic=contract.topics.find(topic=>graph.startsWith(topic.id+'-'));
    if(!topic||!graphs.some(work=>work.responseId===graph))throw new Error('Missing shared investigation graph activity');
    graphLink=`<p><a href="#${h(topic.id)}" data-pilot2-return-route="${h(topic.id)}" data-pilot2-return-focus="${h(graph)}">Open your saved core graph construction</a></p>`;
  }
  return `<section class="p2-topic" id="${h(item.id)}" tabindex="-1"><h2>${h(item.title)}</h2><p>Optional investigation extension</p><p>${h(item.question)}</p><p>${h(item.sourceKind)}</p><dl><dt>Compare</dt><dd>${h(item.variables.compare)}</dd><dt>Observe</dt><dd>${h(item.variables.observe)}</dd><dt>Hold constant</dt><dd>${h(item.variables.holdConstant)}</dd></dl><h3>Plan your comparison</h3><p>${h(item.prediction)}</p><ol>${item.procedure.map(step=>`<li>${h(step)}</li>`).join('')}</ol>${renderTopicWritingActivity(schema,item.responseFields[0].id,item.responseFields[0].label,item.responseFields[0].prompt,{guide:item.responseFields[0].modelResponse+' '+item.responseFields[0].comparisonPolicy})}<button type="button" data-pilot2-group-compare="${h(item.id)}-observations" data-pilot2-requires="${h(item.responseFields[0].id)}" aria-controls="${h(item.id)}-observations-overall-guide" aria-expanded="false" disabled>Reveal the supplied observations</button><div id="${h(item.id)}-observations-overall-guide" hidden>${figures}${renderTopicDataset(item.dataset,'Supplied observations')}${item.dataset.habitatAreaSquareMetres===undefined?'':`<p>Habitat area for the quadrat estimate: ${item.dataset.habitatAreaSquareMetres} m².</p>`}${scenario?renderTopicDataset({columns:['Separate demographic quantity','Value'],rows:Object.entries(scenario).map(([key,value])=>[scenarioLabels[key]??key,value])},'Separate whole-population scenario'):''}${item.suppliedCodonKey?`<p>${h(item.suppliedCodonKey.orientation)}</p>${renderTopicDataset({columns:['mRNA codon','Meaning'],rows:Object.entries(item.suppliedCodonKey).filter(([key])=>key!=='orientation')},'Supplied codon key')}`:''}</div>${graphLink}<p>${renderTopicTeachingLink(contract,item.coreSkillPartId)}</p><h3>Keep the model’s limits visible</h3><ul>${item.limitations.map(text=>`<li>${h(text)}</li>`).join('')}</ul><p>${h(item.collaborationEvidence)}</p>${item.responseFields.slice(1).map(field=>renderTopicWritingActivity(schema,field.id,field.label,field.prompt,{guide:field.modelResponse+' '+field.comparisonPolicy,graph:graphs.find(graph=>graph.responseId===field.id)})).join('')}<button type="button" data-pilot2-collect="${h(item.id)}-saved" data-pilot2-requires="${item.responseFields.map(field=>h(field.id)).join(' ')}" disabled>Save investigation to Process Collection</button><p data-pilot2-collection-status="${h(item.id)}-saved" role="status"></p><button type="button" data-pilot2-group-compare="${h(item.id)}" data-pilot2-requires="${item.responseFields.map(field=>h(field.id)).join(' ')}" aria-controls="${h(item.id)}-overall-guide" aria-expanded="false" disabled>Compare the overall interpretation</button><div id="${h(item.id)}-overall-guide" hidden><p>${h(item.expected)}</p></div></section>`;
}
