import {activateTopicRestore,type TopicRestoreInspection} from './pilot2-restore.js';
import type {TopicState,TopicStateSchema,KeyValueStorage} from './pilot2-state.js';
import {topicHtml as h} from './pilot2-render-common.js';
export function renderTopicRecovery(inspection:TopicRestoreInspection) {
 return `<section class="p2-topic p2-recovery" aria-label="Saved work recovery"><h1>Choose the work to continue</h1><p>More than one version or an unreadable save needs attention. Your original work stays available below. Continuing keeps verified copies before changing the active save on this device.</p>${inspection.candidates.length?`<label>Version to continue<select data-pilot2-recovery-choice><option value="">Choose a version…</option>${inspection.candidates.map(candidate=>`<option value="${h(candidate.id)}">${h(candidate.label)}</option>`).join('')}</select></label><p data-pilot2-recovery-summary></p><label><input type="checkbox" data-pilot2-recovery-confirm> Continue with this version and keep copies of the originals.</label><button type="button" data-pilot2-recovery-continue disabled>Keep originals and continue</button>`:'<p>No complete version can be opened safely. Keep the original text below for recovery; nothing has been reset.</p>'}<p data-pilot2-recovery-status role="status"></p>${inspection.sources.map(source=>`<details><summary>${h(source.label)} — original saved work</summary><textarea readonly rows="10" aria-label="${h(source.label)} original saved work">${h(source.raw)}</textarea></details>`).join('')}</section>`;
}
export function mountTopicRecovery(root:HTMLElement,inspection:TopicRestoreInspection,schema:TopicStateSchema,storage:KeyValueStorage|null,onReady:(state:TopicState)=>void) {
 const choose=root.querySelector<HTMLSelectElement>('[data-pilot2-recovery-choice]'),confirm=root.querySelector<HTMLInputElement>('[data-pilot2-recovery-confirm]'),button=root.querySelector<HTMLButtonElement>('[data-pilot2-recovery-continue]'),status=root.querySelector<HTMLElement>('[data-pilot2-recovery-status]');
 if(!status)throw new Error('Missing recovery status');
 const update=()=>{if(button)button.disabled=!storage||!choose?.value||!confirm?.checked;const candidate=inspection.candidates.find(candidate=>candidate.id===choose?.value),summary=root.querySelector<HTMLElement>('[data-pilot2-recovery-summary]');if(summary)summary.textContent=candidate?`${Object.values(candidate.state.responses).filter(value=>value.trim()).length} written responses.${Date.parse(candidate.state.updatedAt)>0?' Saved '+new Date(candidate.state.updatedAt).toLocaleString()+'.':''}`:'';};
 if(!storage)status.textContent='Device storage is unavailable. Keep the original text before leaving; no save will be replaced.';
 const continueWork=()=>{if(!button||button.disabled||!storage||!choose||!confirm)return;try{const result=activateTopicRestore(inspection,choose.value,schema,storage,confirm.checked);button.disabled=true;onReady(result.state);}catch{status.textContent='Recovery could not be completed. The originals remain available. Keep a copy and reopen this page before trying again.';}};
 choose?.addEventListener('change',update);confirm?.addEventListener('change',update);button?.addEventListener('click',continueWork);update();
 return{dispose(){choose?.removeEventListener('change',update);confirm?.removeEventListener('change',update);button?.removeEventListener('click',continueWork);}};
}
